### ISSUE TITLE
Validate YAML/JSON syntax on VariableField before submit request

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8181] opened 2020-09-18 17:48 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Validate YAML/JSON syntax on `VariableField` before submit request.

**Comment by dsesami** [comment] 2020-09-18 18:59
Although technically it's new, I'm calling this a bug just because it's more about stopping something from breaking.

**Comment by mabashian** [comment] 2021-02-04 15:43
Dupe of #8906

**Closed as completed by mabashian** 2021-02-04 15:43 UTC
Labels: type:bug, type:enhancement, component:ui
