### ISSUE TITLE
Not able to add Job template on Git project

### ISSUE THREAD

**Issue by itpgithub** [ansible/awx#1364] opened 2018-02-27 12:45 UTC
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME
 - UI

##### SUMMARY

Added Git project and created template now want to add template into the project so the git pull directly on inventory server not on project directory but not able to add job template on git project

##### ENVIRONMENT
* AWX version: development
* AWX install method: docker on linux
* Ansible version:  2.4
* Operating System: Centos
* Web Browser: chrome

##### STEPS TO REPRODUCE
Create git project to pull source code from git
Create template to run playbook on inventory server

Then try to add job template on project

##### EXPECTED RESULTS

Pull Source code directly to inventory servers and then run playbook to build.

##### ACTUAL RESULTS

Not able to add job template on project

**Comment by itpgithub** [comment] 2018-02-27 13:25
![error](https://user-images.githubusercontent.com/3985273/36731112-201c3d0c-1be3-11e8-8b31-c269aa82e028.png)

**Comment by matburt** [comment] 2018-02-27 13:51
I'm a little confused on what you are trying to do. Did you add the project to the AWX projects screen? What happens when you try to add a job template? Is the project just not listed there?

Alternatively did you manually check out the project on the filesystem of the container? If so, don't do that... add the project in the Projects section of AWX itself.

**Comment by itpgithub** [comment] 2018-02-28 08:09
Hi Mat,

May be the wrong way i am trying to achieve but my requirement is:

Project -- Checkout code from git to inventory server ( Web servers) not on AWX project folder. 

When i am creating a project there is a tab (Job Template) while i am going there , nothing is listing there ( Already we have templates ) and add button also not responding .

Thanks

**Comment by matburt** [comment] 2018-02-28 13:58
Is there an error on your javascript console when you click the `Add` button to add a project?

**Comment by itpgithub** [comment] 2018-03-01 06:25
No error No response its identical same like above shared screenshot.............

**Comment by goharma** [comment] 2018-03-02 16:22
I have the same problem.  This is the error I get in Chrome console when the page loads:

vendor.55410e4f142c1e5ce12d.js:570 Error: [$controller:ctrlreg] The controller with the name 'TemplatesListController' is not registered.
http://errors.angularjs.org/1.6.9/$controller/ctrlreg?p0=TemplatesListController
    at vendor.55410e4f142c1e5ce12d.js:570
    at vendor.55410e4f142c1e5ce12d.js:570
    at Object.<anonymous> (vendor.55410e4f142c1e5ce12d.js:603)
    at vendor.55410e4f142c1e5ce12d.js:570
    at invokeLinkFn (vendor.55410e4f142c1e5ce12d.js:570)
    at nodeLinkFn (vendor.55410e4f142c1e5ce12d.js:570)
    at compositeLinkFn (vendor.55410e4f142c1e5ce12d.js:570)
    at vendor.55410e4f142c1e5ce12d.js:570
    at vendor.55410e4f142c1e5ce12d.js:570
    at updateView (vendor.55410e4f142c1e5ce12d.js:603) "<div ui-view="related" class="ng-scope">"

**Comment by matburt** [comment] 2018-03-02 18:02
Thanks @goharma that's more helpful.

@unimity I'm sorry, I'm not sure what you are trying to say but please grab the web console output as you can see @goharma has already.

**Comment by matburt** [comment] 2018-03-02 18:03
It would also be super helpful to have the version number 

`AWX version: development`

Isn't super helpful.

**Comment by jakemcdermott** [comment] 2018-03-02 18:07
Hello unimity, thanks for filing this issue.

This is a duplicate of https://github.com/ansible/awx/issues/960 and is being addressed here: https://github.com/ansible/awx/pull/1323 so I'm going to close.

**Closed as completed by jakemcdermott** 2018-03-02 18:07 UTC
Labels: type:bug, component:api
