### ISSUE TITLE
Job output screen- search for host- enhance error handling to inform user

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11405] opened 2021-12-01 15:23 UTC
On the job output screen of a completed job,  when the user performs an advanced search for a host and puts a host name instead of a host id, the user is redirected to an error page (the error explains that the name give "is improper id"). 

Suggestion: instead of this vague error, can we handle this differently? For example, validate user input instead of redirecting to an error page?

![image](https://user-images.githubusercontent.com/63685497/144261749-8e74d1d0-48ba-46dd-8a09-8dba765c6eba.png)

![image](https://user-images.githubusercontent.com/63685497/144261813-698445ea-2519-4a31-8e6e-ed519ffc7e34.png)

**Comment by nixocio** [comment] 2021-12-02 13:22
@akus062381 This is not a job output issue. It is a an advanced search issue. If you expand the details it will have an explanation of the reason of the failure. There is another issue tracking similar issue. I will try to find it.

**Comment by shanemcd** [comment] 2022-01-31 16:21
@nixocio Did you ever find the related issue?

**Comment by nixocio** [comment] 2022-01-31 19:49
This is the one https://github.com/ansible/awx/issues/9956
See comment: https://github.com/ansible/awx/issues/9956#issuecomment-825785431

The issue is on the advanced search itself - not on the job out screen.

I tested this again, and below it is the error details.

![image](https://user-images.githubusercontent.com/9053044/151861877-a8f19aef-5234-4e95-9200-e4b2b66afbf6.png)

I am closing this one as duplicated. Since we already have several issues detailing similar problems.

**Closed as completed by nixocio** 2022-01-31 19:49 UTC
Labels: type:enhancement, component:ui, needs_triage
