### ISSUE TITLE
Map users in teams based on SAML attributes

### ISSUE THREAD

**Issue by chuegel** [ansible/awx#5854] opened 2020-02-10 14:57 UTC
##### ISSUE TYPE
We are using Keycloak as an IDP and are looking for a way to map users groups to teams in awx/tower based on their saml attributes.

This are the attributes passed to awx/tower when logging in via sso:

```
Issuer                      = https://sso.keycloak.example.com/auth/realms/automation
Subject                     = user1
NameID                      = user1

AttributeStatement:
 * email                                                              = user1@example.com
 * last_name                                                          = Some
 * memberOf                                                           = g-AWX_Network
 * memberOf                                                           = g-AWX-Admin
 * username                                                           = user1
 * first_name                                                         = User
 * Role                                                               = offline_access
 * Role                                                               = manage-account
 * Role                                                               = view-profile
 * Role                                                               = manage-account-links
 * Role                                                               = g-AWX-Admin
 * Role                                                               = uma_authorization
```
On awx we have multiple teams configured e.g Network
##### SUMMARY

I couldn't find a way to map the groups to a particular team in awx
Ideally, all users belonging to g-AWX_Network to get mapped to *Network* in awx

Any hints are much appreciated.

**Comment by egmar** [comment] 2020-02-12 07:50
Hi, for us it works with following in `SAML Team Attribute Mapping`:
```
{
 "saml_attr": "<saml_response_attribute_name>",
 "remove": true,
 "team_org_map": [
  {
   "organization": "<organization_name>",
   "team": "<saml_response_attribute_value>"
  }
 ]
}
```
Replace the values as needed. Also see https://docs.ansible.com/ansible-tower/latest/html/administration/ent_auth.html#saml-authentication-settings since it has some examples too.

**Comment by chuegel** [comment] 2020-02-12 14:53
Hi, thanks I´ve figured that out but that will create new groups with the group name fetched from IDP (eg. g-AWX_Network). Since we have already a lot of groups with their specific permissions , it would make more sense for us to map those idp groups to existing groups in awx/tower.
Any hints?
Cheers

**Comment by chuegel** [comment] 2020-02-14 14:33
https://github.com/ansible/awx/issues/2688

**Comment by ryanpetrello** [comment] 2020-02-14 18:24
duplicate of https://github.com/ansible/awx/issues/2688

**Closed as completed by ryanpetrello** 2020-02-14 18:24 UTC
