### ISSUE TITLE
AWX Operator deployment on k3s: cannot create directory ‘/var/lib/postgresql/data’: Permission denied 

### ISSUE THREAD

**Issue by twobombs** [ansible/awx#10812] opened 2021-08-04 08:43 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Postgress complains about no rights to write data directory after deployment by awx operator under k3s.

<img width="734" alt="Screenshot 2021-08-04 at 10 24 34" src="https://user-images.githubusercontent.com/12692227/128150616-3c1f088b-af71-4d37-8a54-89ae1335d0be.png">

Error similar to https://github.com/ansible/awx/issues/1047 but this time not using docker, but K3s.

### AWX version

AWX operator 0.12.0

### Installation method

kubernetes

### Modifications

yes

### Ansible version

nav

### Operating system

Ubuntu 20.04

### Steps to reproduce

curl -sfL https://get.k3s.io | sh -
k3s kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.12.0/deploy/awx-operator.yaml
k3s kubectl apply -f awx-k3s.yml

awx-k3s.yml :

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-k3s
spec:
  service_type: nodeport
  ingress_type: none
  hostname: awx-k3s.test.com

### Expected results

succesfull install: awx site

### Actual results

![Screenshot 2021-08-04 at 10 37 48](https://user-images.githubusercontent.com/12692227/128150210-29be8a5d-d91c-4b08-8074-1289e7165fa2.png)

<img width="1406" alt="Screenshot 2021-08-04 at 10 31 07" src="https://user-images.githubusercontent.com/12692227/128150229-a6619ee9-be5e-47ba-b780-8467405276a8.png">

<img width="734" alt="Screenshot 2021-08-04 at 10 24 34" src="https://user-images.githubusercontent.com/12692227/128150251-4c6c9092-d5b2-4468-9d4c-36e8ef341c40.png">

### Additional information

Used AWX operator to install on minicube for dev. 
Now stepping up to the default k3s stack

**Comment by wenottingham** [comment] 2021-08-04 18:58
This looks like a duplicate of https://github.com/ansible/awx-operator/issues/483

**Closed as completed by wenottingham** 2021-08-04 18:58 UTC
