### ISSUE TITLE
can you add web ui import

### ISSUE THREAD

**Issue by thisID** [ansible/awx#8066] opened 2020-09-03 07:47 UTC
Importing the host can only be done by file and manual import, which is too much trouble.
When several hosts of the list need to be closed to perform tasks, clicking one by one is too cumbersome,
want to be able to close and open  host  in bulk, or open and close them in groups.
                                                    

Thank you for your efforts. I wish you good health

**Comment by unlikelyzero** [comment] 2020-09-03 12:28
@thisID do you think this ticket https://github.com/ansible/awx/issues/4470 captures the same request?

**Comment by thisID** [comment] 2020-09-04 07:16
> @thisID do you think this ticket #4470 captures the same request?

Have your considered adding this feature

**Comment by wenottingham** [comment] 2020-09-04 17:07
CLosing as a duplicate of #4470

**Closed as completed by wenottingham** 2020-09-04 17:07 UTC
