### ISSUE TITLE
AWX 9.2 python 3.6 error

### ISSUE THREAD

**Issue by yagashiraevil** [ansible/awx#6175] opened 2020-03-05 05:40 UTC
##### ISSUE TYPE
 - Unable to run linux playbooks, geting this issue
![image](https://user-images.githubusercontent.com/26820733/75951128-f382db00-5ecc-11ea-9cf7-7f591e0e2835.png)

##### SUMMARY
Installed a new centos 7.7 machine with python 3 as default interpeter 
[root@awx awxcompose]# alternatives --config python

There are 2 programs which provide 'python'.

  Selection    Command
-----------------------------------------------
   1           /usr/bin/python2
*+ 2           /usr/bin/python3

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux, 
* Ansible version:  2.9.3
* Operating System: Centos 7.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

using a ping in a playbook to check connectivity of the host
- hosts: all
  gather_facts: false
  tasks:
    - ping:
when i ran the playbook it started giving me the above error, its only doing it with linux machines , windows host connecting with winrm are working.

**Comment by ryanpetrello** [comment] 2020-03-05 14:02
@yagashiraevil,

Could you copy and paste the full contents of the "Error Details" from your screenshot?

**Comment by yagashiraevil** [comment] 2020-03-06 04:46
@ryanpetrello 
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1275, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1879, in pre_run_hook job.project.scm_type, job_revision File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2263, in make_local_copy for submodule in git_repo.submodules: File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 340, in submodules return Submodule.list_items(self) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/util.py", line 928, in list_items out_list.extend(cls.iter_items(repo, *args, **kwargs)) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/objects/submodule/base.py", line 1192, in iter_items sm._name = n AttributeError: 'Tree' object has no attribute '_name'

**Comment by yagashiraevil** [comment] 2020-03-06 08:24
for what i have worked on it has to do something with GitPython submodule. https://github.com/ishepard/pydriller/issues/66. I removed .gitmodule from myproject and all got well.

**Comment by ryanpetrello** [comment] 2020-03-06 13:15
Interesting - glad you figured it out.

@AlanCoding this might be something that interests you - it looks like the `gitpython` we're using might have a bug working w/ certain clones that have submodules?

**Comment by AlanCoding** [comment] 2020-03-06 18:40
There's been some movement, but not a whole lot around that bit of code:

https://github.com/gitpython-developers/GitPython/blob/3.0.5/git/objects/submodule/base.py#L1192

The [obvious issue](https://github.com/gitpython-developers/GitPython/pull/818) was supposed to be resolved in the version we have, particularly since they're on 9.2.0.

A full reproducer would be of interest. If it can only be hit with some poorly configured remote, you can set up the repo locally on the machine and then make a project starting with `file://`. I do this all the time for testing. Specifically, some variation of what was [suggested in this comment](https://github.com/ishepard/pydriller/issues/66#issuecomment-566481892) might be worth trying inside AWX.

**Comment by ryanpetrello** [comment] 2020-04-01 01:37
Marking this low priority; it looks like it's an issue w/ the underlying `git-python` library related to clones that have `.gitmodules` (we don't have a conclusive reproducer yet, though).

**Comment by shanemcd** [comment] 2020-09-23 18:09
Is this still an issue? Probably going to close this if no one else chimes in within the next few days.

**Comment by jboss4332** [comment] 2020-11-02 20:37
I am having this issue so I would be interested in if anyone has found a solution.

`Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1279, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1862, in pre_run_hook sync_task.run(local_project_sync.id) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 698, in _wrapped return f(self, *args, **kwargs) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1444, in run raise AwxTaskError.TaskError(self.instance, rc) Exception: project_update 4267 (failed) encountered an error (rc=2), please see task stdout for details.`

I am working off of AWX 9.3.0 and Ansible 2.9.5

**Comment by kevincoakley** [comment] 2020-11-18 22:37
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1376, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1948, in pre_run_hook
    RunProjectUpdate.make_local_copy(job.project, private_data_dir, scm_revision=job_revision)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2371, in make_local_copy
    for submodule in git_repo.submodules:
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 337, in submodules
    return Submodule.list_items(self)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/util.py", line 921, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/objects/submodule/base.py", line 1200, in iter_items
    sm._name = n
AttributeError: 'Tree' object has no attribute '_name'
```

AWX 15.0.1 using the ansible/awx:15.0.1 docker image

**Comment by AlanCoding** [comment] 2020-12-02 20:32
Given that info, https://github.com/ansible/awx/pull/7367 is where I would start for a fix.

**Comment by shanemcd** [comment] 2022-01-26 13:54
Since this is not a bug we ourselves can fix, I am going to close this in favor of https://github.com/ansible/awx/issues/11379

**Closed as completed by shanemcd** 2022-01-26 13:54 UTC
Labels: type:bug, component:api
