### ISSUE TITLE
Custom certificates cannot be trusted

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#442] opened 2017-10-16 15:48 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME 
- Installer

##### SUMMARY

Custom certificates cannot be installed on the `awx_web` or `awx_task` containers without modifying the installer. I use LDAPS with a domain-trusted TLS certificate for user authentication in AWX. My container *host* is domain joined, and trusts this certificate, but `awx_web` container, which makes the LDAPS request, does not trust it. I resolved this by bind-mounting `/etc/pki/ca-trust` from the host to the container, but this required modifying the `local_docker` Ansible rules.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.3.1

##### STEPS TO REPRODUCE

1. Have an LDAPS server with a self-signed or site-signed certificate
2. Configure it as an authentication source for AWX, using LDAPS
3. Attempt to log in as a user from the LDAPS source
4. Get invalid username or password response
5. See log messages from the `awx_web` container that the LDAP server is down because the TLS response could not be validated

##### EXPECTED RESULTS

If the host server trusts the upstream LDAP source, then the `awx_web` container should be able to trust it as well. At least, it should be easy to configure.

##### ACTUAL RESULTS

The `awx_web` container uses strictly the default CentOS 7 CA trust sources, and cannot be configured to use the host's CA trust bundle instead.

##### ADDITIONAL INFORMATION

To resolve, I added the following option to the `Activate AWX Web Container` task in `local_docker`:

```yaml
- name: Activate AWX Web Container
  # ...
  volumes:
    - /etc/pki/ca-trust:/etc/pki/ca-trust:ro
```

I skirted this issue in the last version because it was possible to disable certificate verification for LDAPS authentication. This was a temporary workaround, and needs a more permanent solution anyway.

**Comment by matburt** [comment] 2017-10-17 03:24
Dupe of #411

**Closed as completed by matburt** 2017-10-17 03:24 UTC
Labels: type:bug, component:installer
