### ISSUE TITLE
AWX18 git inventory from project fails to import

### ISSUE THREAD

**Issue by lerminou** [ansible/awx#9763] opened 2021-03-31 10:47 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

inventory no more get imported in AWX

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minikube
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

create a project and create an inventory from this project and try to sync it

was OK in AWX 17.1.0 before the upgrade

##### EXPECTED RESULTS

inventory is imported

##### ACTUAL RESULTS

```
ansible-inventory [core 2.11.0b3.post0] 
  config file = /tmp/pdd_wrapper_6286_0_2c6y55/awx_6286_jvkm6xbz/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
Using /tmp/pdd_wrapper_6286_0_2c6y55/awx_6286_jvkm6xbz/project/ansible.cfg as config file
[WARNING]: Ignoring invalid path provided to plugin path:
'/runner/project/inventories/dev/hosts' is not a directory
host_list declined parsing /runner/project/inventories/dev/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /runner/project/inventories/dev/hosts as it did not pass its verify_file() method
auto declined parsing /runner/project/inventories/dev/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /runner/project/inventories/dev/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /runner/project/inventories/dev/hosts as it did not pass its verify_file() method
```

**Comment by shanemcd** [comment] 2021-03-31 13:02
Dupe of https://github.com/ansible/awx/issues/9704

**Closed as completed by shanemcd** 2021-03-31 13:02 UTC
Labels: type:bug
