### ISSUE TITLE
Job Result Detail Doc link routes to 3.3.0 docs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2864] opened 2018-12-03 21:59 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Job Result Detail Doc link routes to 3.3.0 docs. This is unlike the rest of the doc links.

##### ENVIRONMENT
* AWX version: 3.3.0+

##### STEPS TO REPRODUCE
1. Open up the doc link on the Job Result Page under 'Key'
2. Routed to 3.3.0 docs

##### EXPECTED RESULTS
Expect to be routed to latest or statically set determined for the specific build (like schedules resource page, etc)

##### ADDITIONAL INFORMATION
https://github.com/ansible/awx/blob/63b079673817db672d8dd7e546f632dcf71109b2/awx/ui/client/features/output/constants.js#L46

**Comment by unlikelyzero** [comment] 2018-12-03 22:02
@docschick we aren't doing this the same way as the rest (determining doc link version dynamically with an API call) because we want to have one fewer API calls on this particular page to improve performance

**Comment by jakemcdermott** [comment] 2018-12-03 22:14
👍 see linked pr - as mentioned above we avoid the extra api request as longer page loads increase the likelihood of missing a socket event.

Longer page loads _shouldn't_ matter, but we'd need to make some significant changes to how our shared `SocketService` establishes connections and channel subscriptions for that to actually be the case.

**Comment by wenottingham** [comment] 2018-12-07 18:13
Fixed in the referenced PR.

**Closed as completed by wenottingham** 2018-12-07 18:13 UTC
Labels: type:bug, component:ui

**Comment by elyezer** [comment] 2018-12-10 17:33
The link now directs the user to the latest docs, as intended. This is now verified.
