### ISSUE TITLE
UX Enhancement - Ability to rename jobs

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#2010] opened 2018-06-21 15:27 UTC
It would be beneficial to have the ability to rename jobs in AWX.  For something with a long survey, it would be useful to be able to quickly get access to and rerun the job with the same parameters.

You can't do this with labels, because you can only add labels at the jt level, not the job (and thus the populated-with-particular-survey-based-extra-vars value can't be different by them)

The closest thing you can do is search for the template or the jobs that are `created_by:you` and remember when you last ran the job, which works, but is kind of a finicky flow.

There isn't a "detail" form-based view for jobs, so this is dependent on some sort of ux concept for inline-editing flow, a rename modal, something else?

Also would need to be able to PUT the new job name to the API.

**Comment by sumkincpp** [comment] 2018-06-29 11:14
Though about something similar but for workflow template nodes.
Having aliases for templates within workflow will allow to save "run context" within job for multi-purpose templates.
Here is an issue #2032

**Comment by unlikelyzero** [comment] 2021-01-23 16:48
closing as dupe of https://github.com/ansible/awx/issues/2032

**Closed as completed by unlikelyzero** 2021-01-23 16:48 UTC
Labels: type:enhancement, component:api, component:ui, component:ux
