### ISSUE TITLE
Inventory related groups advanced search 

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8422] opened 2020-10-20 20:39 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Making an advance search the kebab button and the select all option breaks the line when the menu is opened (the same problem happens on the Inventory Group Host List)

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.13
* Operating System: Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to inventories
2. Click on an inventory
3. Click on Groups tab
4. Click on a group
5. Click on the Related Groups tab
6. Perform an advanced search 

##### EXPECTED RESULTS

The select all option and the kebab button should be aligned at the same row

##### ACTUAL RESULTS

The position of the select all option and the kebab button changes while you interact with the search inputs

##### ADDITIONAL INFORMATION

![kebab](https://user-images.githubusercontent.com/12464858/96641200-c0c21180-12fa-11eb-8dfa-8dd3bccf9181.gif)

**Comment by unlikelyzero** [comment] 2020-10-28 17:47
Dupe of https://github.com/ansible/awx/issues/7825

**Closed as completed by unlikelyzero** 2020-10-28 17:47 UTC
Labels: type:bug
