### ISSUE TITLE
AWX 18.0 - Admin user not created.

### ISSUE THREAD

**Issue by spaldingd** [ansible/awx#9587] opened 2021-03-15 18:53 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Whilst carrying out a fresh install as per the latest installation instructions (https://github.com/ansible/awx/blob/devel/INSTALL.md) it appears a super user account is not created. 

##### ENVIRONMENT
* AWX version: 18.0
* AWX install method: Minikube & Operator (As per iinstallation instructions)
* Ansible version:  2.9.6
* Operating System: Ubuntu 20.04
* Web Browser: Mozilla Firefox 86.0

##### STEPS TO REPRODUCE

Follow installation documentation as written (Linked above). Fault manifests itself in the section titled "Accessing AWX" and more specifically the second step whereby you execute the command "minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode" to return the Admin user password. All output from prior sections is nominal.

##### EXPECTED RESULTS

It is expected that the Admin user password will be shown on the terminal.

##### ACTUAL RESULTS

The error message "Error from server (NotFound): secrets "awx-admin-password" not found" is displayed. 

##### ADDITIONAL INFORMATION

After a bit of research I have found the command "kubectl get secrets" which I understand is meant to show all secrets stored. Based on the output from my installation I can see the "awx-admin-password" does not exist.

USER@HOSTNAME:~$ kubectl get secrets
| NAME                       	| TYPE                                	| DATA 	| AGE  	|
|----------------------------	|-------------------------------------	|------	|------	|
| awx-operator-token-rx7nw   	| kubernetes.io/service-account-token 	| 3    	| 135m 	|
| awx-postgres-configuration 	| Opaque                              	| 5    	| 134m 	|
| awx-secret-key             	| Opaque                              	| 1    	| 134m 	|
| awx-secrets                	| Opaque                              	| 5    	| 134m 	|
| default-token-m4ttr        	| kubernetes.io/service-account-token 	| 3    	| 137m 	|

I have tried this on two clean built VM's and both exhibit the same symptoms.

If you have any further questions or want some sample output of another commands please let me know.

**Comment by ryanpetrello** [comment] 2021-03-15 19:18
Duplicate of https://github.com/ansible/awx/issues/9529, see: https://github.com/ansible/awx/issues/9529#issuecomment-794181490

**Closed as completed by ryanpetrello** 2021-03-15 19:18 UTC
Labels: type:bug
