### ISSUE TITLE
Encrypted Credentials appear in plain text during SCM update

### ISSUE THREAD

**Issue by seansabour** [ansible/awx#1813] opened 2018-04-27 19:08 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Using Source Control Credentials(password) and running an SCM update the stdout will have the credentials appear in plain text.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version: 2.5.0
* Operating System: Linux
* Web Browser: Firefox 59.0.2 (64-bit)

##### STEPS TO REPRODUCE

1. Create Source Control Credentials for GitHub, using password instead of SCM private key
2. Launch an SCM update
3. View credentials in plain text in the standard out.

##### EXPECTED RESULTS

Have encrypted data XXXXXXX out with stdout

##### ACTUAL RESULTS

Appears in plain text.

##### ADDITIONAL INFORMATION

Here is a output, i've remove my password:

```
Using /etc/ansible/ansible.cfg as config file


PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost]

TASK [check repo using git] ****************************************************
skipping: [localhost]

TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git", "fetch", "--tags", "origin"], "msg": "Failed to download remote objects and refs:  fatal: unable to access 'https://<USER>:<PASSWORD>@<GITHUBENTERPRISE_URL>/sean-sabour/ansible-poc.git/': The requested URL returned error: 504\\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   


```
I just re-ran and now see that it is $encrypted:$encrypted, but when you download the log it appears to be in plain text.

**Comment by ryanpetrello** [comment] 2018-04-27 19:33
@seansabour can you give this a shot with the latest version of awx?  I'm having trouble reproducing:

<img width="709" alt="screen shot 2018-04-27 at 3 31 48 pm" src="https://user-images.githubusercontent.com/214912/39381446-2032e266-4a30-11e8-8bcf-88b152600c65.png">

**Comment by seansabour** [comment] 2018-04-27 19:34
@ryanpetrello can you try to click the download output button and see if it is encrypted still.

**Comment by ryanpetrello** [comment] 2018-04-27 19:36
When I click the download button, this is the content that I see (no sensitive data contained):

```
Using /etc/ansible/ansible.cfg as config file


PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
ok: [localhost]

TASK [check repo using git] ****************************************************
skipping: [localhost]

TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin 'https://$encrypted$:$encrypted$@githubenterprise_url.org/sean-sabour/ansible-poc.git' /projects/_4__demo_project", "msg": "Cloning into '/projects/_4__demo_project'...\\nfatal: unable to access 'https://$encrypted$:$encrypted$@githubenterprise_url.org/sean-sabour/ansible-poc.git/': Could not resolve host: githubenterprise_url.org; Name or service not known", "rc": 128, "stderr": "Cloning into '/projects/_4__demo_project'...\\nfatal: unable to access 'https://$encrypted$:$encrypted$@githubenterprise_url.org/sean-sabour/ansible-poc.git/': Could not resolve host: githubenterprise_url.org; Name or service not known\\n", "stderr_lines": ["Cloning into '/projects/_4__demo_project'...", "fatal: unable to access 'https://$encrypted$:$encrypted$@githubenterprise_url.org/sean-sabour/ansible-poc.git/': Could not resolve host: githubenterprise_url.org; Name or service not known"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   


```

**Comment by wenottingham** [comment] 2018-04-27 19:36
There was a specific fix for this in 1.0.6, if I recall.

**Comment by ryanpetrello** [comment] 2018-04-27 19:40
Looks like: https://github.com/ansible/awx/commit/09d5645b90ff96ba67f0b84c0265679e66fec318

**Comment by ryanpetrello** [comment] 2018-04-27 19:46
@seansabour to confirm, I reverted 09d5645b90ff96ba67f0b84c0265679e66fec318 in a local install of mine and I see the behavior you're describing.

If you see this bug in 1.0.6, please re-open and let us know.

**Closed as completed by ryanpetrello** 2018-04-27 19:46 UTC
Labels: type:bug, component:ui

**Comment by seansabour** [comment] 2018-04-27 22:09
thanks @ryanpetrello ! i'll try to upgrade later this week .
