### ISSUE TITLE
Display tags for imported execution environments

### ISSUE THREAD

**Issue by cloin** [ansible/awx#11321] opened 2021-11-09 15:03 UTC
Within AWX UI, it's not clear which version of the EE has been imported. It would be great to display tag information from the images to ensure the latest or expected image is being used.

##### ISSUE TYPE
 - Feature Idea

**Comment by nixocio** [comment] 2021-11-11 14:20
Possible related to: https://github.com/ansible/awx/issues/10409

**Comment by AlanCoding** [comment] 2022-05-18 13:48
I'm going to close this as a duplicate of that linked issue. Our EE use is modeled after the podman / docker CLI, but that left a pretty big blind spot with versioning.

**Closed as completed by AlanCoding** 2022-05-18 13:48 UTC
Labels: type:enhancement, component:api, component:ui
