### ISSUE TITLE
Aliases for templates/jobs within workflow

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#2032] opened 2018-06-29 10:24 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Would be great to have job aliases for templates/jobs within workflow which will be shown on workflow pipeline.

Currently only template name is shown. If it is reusable template with many configurable options it's name might not fully describe exact template action performed within workflow.

**Comment by wenottingham** [comment] 2018-06-29 14:21
Assume this would apply to schedule configurations as well.

**Comment by AlanCoding** [comment] 2018-07-09 15:03
This is a duplicate of https://github.com/ansible/awx/issues/1422, although I had no traction for that one and I'll be happy to close that in favor of this one.

> Assume this would apply to schedule configurations as well.

I don't follow that. Schedules have a `name` field already. Yes, schedules and workflow nodes have a commonality that they may contain promotable fields, but this lack of an identifier/name problem is unique to the case of workflow nodes.

**Comment by unlikelyzero** [comment] 2020-03-24 15:08
Note there is a similar request here https://github.com/ansible/awx/issues/5824

**Comment by AlanCoding** [comment] 2020-03-24 18:57
Status update: merging https://github.com/ansible/awx/pull/6291 for adding the `identifier` field, which does something like this, but targeted toward API clients / the CLI / the Ansible modules.

As a UI request, this still stands.

I would encourage the UI to leverage the `identifier` field, but the auto-generation of UUIDs when it's blank could give it some challenges (which gets parity between the UI and playbook-created content). I understand if the UI instead goes its own way and adds a different description-like field.

Anyway, I'm taking the API label off because it's not sure to require API changes, and it is oriented towards UI-next.

**Comment by gpiucco** [comment] 2020-04-23 11:56
+1. without this I have to pragmatically created thousands of JT just so my users can understand what the workflow is doing

**Comment by Gianlu** [comment] 2020-10-23 16:49
Hello,
do you have any news about this issue? It would be very useful.

Thanks

**Comment by AlexSCorey** [comment] 2020-11-12 14:39
@Gianlu and @gpiucco no news yet.  Discussions about adding this feature to the new ui have started but nothing definitive has been set.    Follow this issue for updates, if you aren't already doing so.

**Comment by tiagodread** [comment] 2021-08-03 18:51
The aliasing in workflow nodes was added by #10592, closing this ticket.

**Closed as completed by tiagodread** 2021-08-03 18:51 UTC
Labels: type:enhancement, component:ui, good first issue
