### ISSUE TITLE
Can't reorder "survey" items in Chrome

### ISSUE THREAD

**Issue by theasp** [ansible/awx#131] opened 2017-09-12 13:39 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The drop zone does not appear in Chrome when re-ordering survey items.  Works fine in FireFox.

##### ENVIRONMENT
* AWX version: 1.0.0.312
* Ansible version:  2.3.1.0 
* Operating System: Docker/CentOS
* Web Browser: Chrome 61.0.3163.79

##### STEPS TO REPRODUCE
1. Create two or more survey items in a task template.
2. Attempt to drag and drop the survey items to change their order.

##### EXPECTED RESULTS
The drop zone should appear, and the list should re-order it's self after releasing the button.

##### ACTUAL RESULTS
Nothing changes.

##### ADDITIONAL INFORMATION

Thanks!

**Comment by jlmitch5** [comment] 2017-09-13 16:09
@theasp I wasn't able to reproduce on latest devel in Chrome.

I'm curious if it has to do with specific question types (like multi-selects), or number of elements or something like that.  Could you investigate to see if you can isolate the behavior?

EDIT: thanks for filing this, btw!

**Comment by theasp** [comment] 2017-09-14 18:29
@jlmitch5 What OS are you running Chrome on?  I've only tried it in Linux.  I was able to reproduce it with Chromium 59 in a brand new account, I will give it a try in a different desktop environment.  I'm open to it being something stupid on my part. ;)

**Comment by matburt** [comment] 2017-09-15 18:34
I noticed this too... it's possible but kinda difficult to do, so I'll leave this open.

**Comment by Zokormazo** [comment] 2017-09-21 21:28
I'm not able to fully reproduce this bug, but after talking to @jlmitch5 we found that droping the dragged row on the last position was difficult due to the small drop zone there. PR fixes this expanding the last drop position.

Need more info if the issue was bigger than that

**Comment by Zokormazo** [comment] 2017-09-22 18:34
@theasp can you try now that #247 is merged?

**Comment by jlmitch5** [comment] 2017-09-22 18:37
closing based on merge

**Closed as completed by jlmitch5** 2017-09-22 18:37 UTC
Labels: type:bug, component:ui
