### ISSUE TITLE
job_template UI fetch credentials with bad property.

### ISSUE THREAD

**Issue by paihu** [ansible/awx#2607] opened 2018-11-06 04:31 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Maybe i18n UI probrem.

##### ENVIRONMENT
* AWX version: 1.0.6.49 to 2.1.0 (dockerhub image tag)
* AWX install method: docker on linux, docker for mac
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser: 

##### STEPS TO REPRODUCE
1. set browser language to japanese
1. view job_template
1. push credential search button
1. popup error message `Invalid search term entered. GET returned: 400 無効な credential_type ID: NaN`

##### EXPECTED RESULTS
Request URL: http://localhost/api/v2/credentials/?order_by=name&page_size=5&credential_type=3

##### ACTUAL RESULTS
Request URL: http://127.0.0.1/api/v2/credentials/?order_by=name&page_size=5&credential_type=NaN

##### ADDITIONAL INFORMATION

English
![lang_en](https://user-images.githubusercontent.com/13479783/48042898-26c53500-e1c7-11e8-95b7-5ee54c75e042.gif)

Japanese
![lang_ja](https://user-images.githubusercontent.com/13479783/48042899-275dcb80-e1c7-11e8-8905-73ad03ea51f5.gif)

**Comment by jakemcdermott** [comment] 2018-11-06 05:28
Hello @paihu,

Thanks for creating this issue. This appears to be a duplicate of https://github.com/ansible/awx/issues/2231 so I am closing.

**Closed as completed by jakemcdermott** 2018-11-06 05:28 UTC
Labels: type:bug, component:ui
