### ISSUE TITLE
Change body text  in e-mail sent by AWX

### ISSUE THREAD

**Issue by Ivheror** [ansible/awx#3016] opened 2019-01-17 10:21 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ADDITIONAL INFORMATION

It would be nice to change the body message of notification zone in awx, by default it sends a JSON which if u had some password on it, someone is free to watch

**Comment by qjcg** [comment] 2019-01-17 14:05
This looks like a dupe of #79.

**Comment by wenottingham** [comment] 2019-01-18 01:11
Yes, closing.

**Closed as completed by wenottingham** 2019-01-18 01:11 UTC
Labels: component:api, component:ui, component:installer
