### ISSUE TITLE
Missing job output sections

### ISSUE THREAD

**Issue by sooslaca** [ansible/awx#12194] opened 2022-05-09 13:05 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Not streaming logs, but when I open the output of the job later I have missing sections in the output.
`/#/jobs/playbook/XXXXXX/output`
I cannot find any correlation with the content and between missing sections. (eg not the same part missing even if I include the same role/task)
I cannot find console logs in developer tools, neither any network resources fail to load.
Attaching a screen showing the SAME include (line 95 and 112), but NOT same parts are missing.
Also weird that line numbers are missing next to those empty lines.

Has anyone have an idea how to debug it further or anyone else already affected by this issue?

### AWX version

AWX 21.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Ansible version

awx-ee:latest

### Operating system

linux

### Web browser

Chrome

### Steps to reproduce

Run playbook, I don't have a test playbook, just prod ones I cannot share.

### Expected results

No interruption in job output

### Actual results

Missing parts in job output

### Additional information

![awx_issue](https://user-images.githubusercontent.com/26524201/167415718-9c94cd23-63a9-49b9-877c-8777f41776f3.png)

**Comment by keithjgrant** [comment] 2022-05-09 19:16
Hi, a couple questions to help me narrow this down:

- Is it always the same lines missing if you refresh the page?
- Is it always the same lines missing if you re-run the same job?
- Does the issue resolve itself if you add any query parameters to the page URL? (e.g. `/jobs/playbook/{id}/output?x`) (this will disable the expand/collapse arrows on the left, which I suspect are part of the issue)

**Comment by sooslaca** [comment] 2022-05-10 09:38
Hi @keithjgrant ,

1) yes, same lines are missing
2) yes, same part is missing if I rerun the same job
3) and yes, this helped :) We can live with this for now.
As soon as I add a query parameter, arrows on the left are disappear and page loads fully !

Thanks for the hint ;) I hope it will be fixed sometimes...

**Comment by lals1** [comment] 2022-05-11 11:18
I am having exactly same issue with AWX 20.0.1. 

Adding query parameter in the URL does display all the lines in the job output.

**Comment by keithjgrant** [comment] 2022-05-11 22:44
> I am having exactly same issue with AWX 20.0.1.

If you can, try upgrading to 21.0. We fixed a number of issues here with the expand/collapse feature in this release. Hopefully you're experiencing one of the bugs we took care of already. See #11944

**Comment by keithjgrant** [comment] 2022-05-11 22:46
> 3\. We can live with this for now.
>         As soon as I add a query parameter, arrows on the left are disappear and page loads fully !

Glad it helps. Is there anything you can show from the missing lines? Do they include warnings or logs or any type of special output?

**Comment by nbttmbrg** [comment] 2022-05-12 08:47
Hello,

Same problem here (AWX 21.0.0 running in GKE). Here's an example with a skipped task. 
Any run will show the same lines greyed out.

Without filter :
![image](https://user-images.githubusercontent.com/48053368/168031636-af39931c-f183-4e76-a689-523a7400d807.png)

With filter : 
![image](https://user-images.githubusercontent.com/48053368/168031605-c7927f83-f4bb-45a1-b0c5-6752ce71f7bf.png)

**Comment by sooslaca** [comment] 2022-05-12 09:11
> > 3. We can live with this for now.
> > As soon as I add a query parameter, arrows on the left are disappear and page loads fully !
> 
> Glad it helps. Is there anything you can show from the missing lines? Do they include warnings or logs or any type of special output?

Nothing in common I can say for the missing sections @keithjgrant . I initially thought it is because of empty response, but not. Even one with response can be a miss. 
I have a feeling it is somehow related to paging which has an issue as well https://github.com/ansible/awx/issues/12195
What I can see when I add the query parameter, then paging queries are changing to not_stdout=.

Also for fun if I press the 'double down arrow' to jump to the end and scroll back from there instead of scrolling down from the top, the missing lines appear for me for SOME job outputs (not all)

**Comment by keithjgrant** [comment] 2022-05-12 15:54
> I have a feeling it is somehow related to paging which has an issue as well #12195

Yeah that paging is determined dynamically, so that's behavior is expected –– unless you can see that the paging it's using is skipping over specific events, it's normal

Chances are, the UI has the needed events in memory and there's a problem looking them up/storing them in the events tree that it builds to support expand/collapse.

While you're digging in the network responses, can you post the response you're getting from `/jobs/{id}/job_events/children_summary/`? This is a set of metadata used to build up the events tree

**Comment by sooslaca** [comment] 2022-05-13 07:53
Hi, paging is ok then, got it.
URL I found was `/api/v2/jobs/{id}/job_events/children_summary/`

This is a different job than above one and failing on row 5. Attached screenshot.
Max count for this job that I see on the UI on the left is
1710  (1711 is visible too, but that line is empty)
"PLAY RECAP" line is in row labelled 1704.
1705->1710 (inclusive) holds the changed inventory hosts

children_summary:
```
{"children_summary":{"2":{"rowNumber":1,"numChildren":1673},"3":{"rowNumber":2,"numChildren":1604},"4":{"rowNumber":3,"numChildren":17},"7":{"rowNumber":6,"numChildren":11},"9":{"rowNumber":8,"numChildren":17},"12":{"rowNumber":11,"numChildren":17},"15":{"rowNumber":14,"numChildren":17},"18":{"rowNumber":17,"numChildren":17},"21":{"rowNumber":20,"numChildren":17},"24":{"rowNumber":23,"numChildren":17},"27":{"rowNumber":26,"numChildren":17},"30":{"rowNumber":29,"numChildren":17},"33":{"rowNumber":32,"numChildren":17},"36":{"rowNumber":35,"numChildren":17},"39":{"rowNumber":38,"numChildren":17},"42":{"rowNumber":41,"numChildren":17},"45":{"rowNumber":44,"numChildren":17},"48":{"rowNumber":47,"numChildren":17},"51":{"rowNumber":50,"numChildren":17},"54":{"rowNumber":53,"numChildren":17},"57":{"rowNumber":56,"numChildren":17},"60":{"rowNumber":59,"numChildren":17},"63":{"rowNumber":62,"numChildren":17},"66":{"rowNumber":65,"numChildren":17},"69":{"rowNumber":68,"numChildren":17},"72":{"rowNumber":71,"numChildren":17},"75":{"rowNumber":74,"numChildren":17},"78":{"rowNumber":77,"numChildren":17},"81":{"rowNumber":80,"numChildren":17},"84":{"rowNumber":83,"numChildren":17},"87":{"rowNumber":86,"numChildren":35},"90":{"rowNumber":89,"numChildren":35},"93":{"rowNumber":92,"numChildren":17},"96":{"rowNumber":95,"numChildren":17},"99":{"rowNumber":98,"numChildren":17},"102":{"rowNumber":101,"numChildren":17},"111":{"rowNumber":110,"numChildren":17},"114":{"rowNumber":113,"numChildren":17},"117":{"rowNumber":116,"numChildren":17},"120":{"rowNumber":119,"numChildren":17},"123":{"rowNumber":122,"numChildren":17},"126":{"rowNumber":125,"numChildren":17},"129":{"rowNumber":128,"numChildren":17},"132":{"rowNumber":131,"numChildren":17},"135":{"rowNumber":134,"numChildren":17},"138":{"rowNumber":137,"numChildren":17},"141":{"rowNumber":140,"numChildren":17},"144":{"rowNumber":143,"numChildren":17},"147":{"rowNumber":146,"numChildren":17},"150":{"rowNumber":149,"numChildren":17},"153":{"rowNumber":152,"numChildren":17},"156":{"rowNumber":155,"numChildren":17},"159":{"rowNumber":158,"numChildren":17},"162":{"rowNumber":161,"numChildren":17},"165":{"rowNumber":164,"numChildren":17},"168":{"rowNumber":167,"numChildren":17},"171":{"rowNumber":170,"numChildren":27},"179":{"rowNumber":178,"numChildren":17},"182":{"rowNumber":181,"numChildren":17},"185":{"rowNumber":184,"numChildren":17},"188":{"rowNumber":187,"numChildren":17},"191":{"rowNumber":190,"numChildren":17},"194":{"rowNumber":193,"numChildren":17},"197":{"rowNumber":196,"numChildren":17},"200":{"rowNumber":199,"numChildren":17},"203":{"rowNumber":202,"numChildren":17},"206":{"rowNumber":205,"numChildren":17},"209":{"rowNumber":208,"numChildren":17},"212":{"rowNumber":211,"numChildren":17},"215":{"rowNumber":214,"numChildren":17},"218":{"rowNumber":217,"numChildren":17},"221":{"rowNumber":220,"numChildren":17},"224":{"rowNumber":223,"numChildren":17},"227":{"rowNumber":226,"numChildren":17},"230":{"rowNumber":229,"numChildren":17},"233":{"rowNumber":232,"numChildren":17},"236":{"rowNumber":235,"numChildren":17},"239":{"rowNumber":238,"numChildren":17},"242":{"rowNumber":241,"numChildren":17},"245":{"rowNumber":244,"numChildren":17},"248":{"rowNumber":247,"numChildren":23},"252":{"rowNumber":251,"numChildren":2},"255":{"rowNumber":254,"numChildren":2},"258":{"rowNumber":257,"numChildren":2},"261":{"rowNumber":260,"numChildren":17},"264":{"rowNumber":263,"numChildren":17},"267":{"rowNumber":266,"numChildren":17},"270":{"rowNumber":269,"numChildren":17},"273":{"rowNumber":272,"numChildren":17},"276":{"rowNumber":275,"numChildren":17},"279":{"rowNumber":278,"numChildren":17},"285":{"rowNumber":284,"numChildren":10},"530":{"rowNumber":529,"numChildren":2},"533":{"rowNumber":532,"numChildren":2},"536":{"rowNumber":535,"numChildren":2},"563":{"rowNumber":562,"numChildren":10},"808":{"rowNumber":807,"numChildren":2},"811":{"rowNumber":810,"numChildren":2},"814":{"rowNumber":813,"numChildren":2},"841":{"rowNumber":840,"numChildren":10},"1086":{"rowNumber":1085,"numChildren":2},"1089":{"rowNumber":1088,"numChildren":2},"1092":{"rowNumber":1091,"numChildren":2},"1119":{"rowNumber":1118,"numChildren":10},"1364":{"rowNumber":1363,"numChildren":2},"1367":{"rowNumber":1366,"numChildren":2},"1370":{"rowNumber":1369,"numChildren":2},"1397":{"rowNumber":1396,"numChildren":22},"1642":{"rowNumber":1641,"numChildren":2},"1645":{"rowNumber":1644,"numChildren":2},"1648":{"rowNumber":1647,"numChildren":2},"1672":{"rowNumber":1671,"numChildren":12}},"meta_event_nested_uuid":{"174":"b6063e75-8808-5257-211d-0000000000c0","175":"b6063e75-8808-5257-211d-0000000000c0","176":"b6063e75-8808-5257-211d-0000000000c0","177":"b6063e75-8808-5257-211d-0000000000c0"},"event_processing_finished":true}
```

![screen2](https://user-images.githubusercontent.com/26524201/168236169-45f9901d-67c0-4520-a517-1e3b8ff1146f.png)
![screen3](https://user-images.githubusercontent.com/26524201/168237134-028098d5-1fc5-4268-855c-79bc75ba6d64.png)

**Comment by sooslaca** [comment] 2022-05-13 08:15
One more thing I noticed that might help. 
Without (NO ?x) the "?x" parameter I get much more rows in `/job_events`.

Mainly events like this
```
"event": "runner_on_start",
```
that I don't see in the ?x one.

For these event `stdout` is always empty though

**Comment by lals1** [comment] 2022-05-13 08:24
> > I am having exactly same issue with AWX 20.0.1.
> 
> If you can, try upgrading to 21.0. We fixed a number of issues here with the expand/collapse feature in this release. Hopefully you're experiencing one of the bugs we took care of already. See #11944

Confirming that issue is resolved in 21.0. Thanks

**Comment by keithjgrant** [comment] 2022-05-24 17:58
@sooslaca @nbttmbrg are you running with a strategy specified other than the default? We believe we've nailed this down as the cause in related/duplicate issue #12233

**Comment by nbttmbrg** [comment] 2022-05-25 07:55
@keithjgrant 
Indeed, we are using the free strategy for this playbook

**Comment by keithjgrant** [comment] 2022-05-25 13:41
Good to know. It's likely we'll have to disable expand/collapse for some strategies, since events from different tasks/plays can be interleaved and don't necessarily fit into a logical tree structure while still allowing output to show in order

**Comment by sooslaca** [comment] 2022-05-31 10:47
hi @keithjgrant 
I'm unsure of the explicit strategy we use, but here is the playbook sniplet from the top:
```
  hosts: all
  order: sorted
  become: yes
  serial: 1
  gather_facts: false
  ignore_unreachable: yes
  max_fail_percentage: 100

```

**Closed as completed** 2022-06-16 14:19 UTC
Labels: type:bug, component:ui

**Comment by sooslaca** [comment] 2022-06-16 19:10
@akus062381 why this on closed? I'm not sure there was a solution (PR) for this yet. Thanks

**Comment by fosterseth** [comment] 2022-06-21 15:40
@sooslaca fixed in this PR https://github.com/ansible/awx/pull/12287
