### ISSUE TITLE
Older OpenShift - AWX install failure: Invalid value "awx_settings" and "secret_key"

### ISSUE THREAD

**Issue by DustinTrap** [ansible/awx#495] opened 2017-10-24 17:47 UTC
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Install fails despite defining valid regex for "secret_key" in inventory file.

##### STEPS TO REPRODUCE

Followed guide at: https://developers.redhat.com/blog/2017/10/16/guide-starting-use-awx-top-openshift-upstream-red-hat-ansible-tower/. Installer crashes with this message: 

```
TASK [openshift : Apply Configmap] ********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "oc apply -f /tmp/awx-config/configmap.yml",
    "delta": "0:00:00.163801",
    "end": "2017-10-24 13:38:05.063746",
    "failed": true,
    "rc": 1,
    "start": "2017-10-24 13:38:04.899945"
}

STDERR:

The ConfigMap "awx-config" is invalid.

* data[awx_settings]: Invalid value: "awx_settings": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[secret_key]: Invalid value: "secret_key": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*

to retry, use: --limit @/tmp/Tower/awx/installer/install.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=13   changed=4    unreachable=0    failed=1

```
# relevant inventory contents

```
cat /tmp/Tower/awx/installer/inventory | grep -i secret
# AWX Secret key
awx_secret_key=<valid_regex>
```

##### EXPECTED RESULTS

Install should have completed sucessfully.
##### ACTUAL RESULTS
It died.

##### ADDITIONAL INFORMATION

Thanks!

**Comment by matburt** [comment] 2017-10-25 04:28
> Install fails despite defining valid regex for "secret_key" in inventory file.

Where in the world did you see that `awx_secret_key` needs to be a regular expression? 

I'd really recommend you follow our internal install guide: https://github.com/ansible/awx/blob/devel/INSTALL.md#openshift

**Comment by DustinTrap** [comment] 2017-10-25 18:52
Thanks, I was using another install guide and it was problematic. I'll give this a shot.

**Comment by DustinTrap** [comment] 2017-10-25 19:00
Welp, right back where we started. Either I'm missing something or the instructions are. Any ideas?

```
TASK [openshift : Apply Configmap] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "oc apply -f /tmp/awx-config/configmap.yml",
    "delta": "0:00:00.158708",
    "end": "2017-10-25 14:57:41.662637",
    "failed": true,
    "rc": 1,
    "start": "2017-10-25 14:57:41.503929"
}

STDERR:

The ConfigMap "awx-config" is invalid.

* data[awx_settings]: Invalid value: "awx_settings": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[secret_key]: Invalid value: "secret_key": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*

        to retry, use: --limit @/tmp/Tower/awx/installer/install.retry
```

**Comment by mdhillo** [comment] 2017-10-26 13:55
Getting the same error on the install. I tried the install guide here - https://github.com/ansible/awx/blob/devel/INSTALL.md#openshift , but no luck.

**Comment by DustinTrap** [comment] 2017-10-26 16:58
@matburt Mat, we're still seeing this as an open issue and multiple users are now reporting. Can we re-open?

**Comment by matburt** [comment] 2017-10-27 02:34
I'm not sure why `oc apply` is having trouble with the secret key... what value are you using there? Can you show me what the templated configmap.yml file looks like when rendered by the installer?

**Comment by ssingla71** [comment] 2017-11-01 13:52
This the configmap.yml.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-config
  namespace: ansible-poc
data:
  secret_key: awxsecret
  awx_settings: |
    import os
    import socket
    ADMINS = ()
    
    # Container environments don't like chroots
    AWX_PROOT_ENABLED = False
    
    #Autoprovisioning should replace this
    CLUSTER_HOST_ID = socket.gethostname()
    SYSTEM_UUID = '00000000-0000-0000-0000-000000000000'
    CELERY_QUEUES += (Queue(CLUSTER_HOST_ID, Exchange(CLUSTER_HOST_ID), routing_key=CLUSTER_HOST_ID),)
    CELERY_ROUTES['awx.main.tasks.cluster_node_heartbeat'] = {'queue': CLUSTER_HOST_ID, 'routing_key': CLUSTER_HOST_ID}
    CELERY_ROUTES['awx.main.tasks.purge_old_stdout_files'] = {'queue': CLUSTER_HOST_ID, 'routing_key': CLUSTER_HOST_ID}
    
    STATIC_ROOT = '/var/lib/awx/public/static'
    PROJECTS_ROOT = '/var/lib/awx/projects'
    JOBOUTPUT_ROOT = '/var/lib/awx/job_status'
    SECRET_KEY = file('/etc/tower/SECRET_KEY', 'rb').read().strip()
    ALLOWED_HOSTS = ['*']
    INTERNAL_API_URL = 'http://127.0.0.1:8052'
    AWX_TASK_ENV['HOME'] = '/var/lib/awx'
    SERVER_EMAIL = 'root@localhost'
    DEFAULT_FROM_EMAIL = 'webmaster@localhost'
    EMAIL_SUBJECT_PREFIX = '[AWX] '
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 25
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_USE_TLS = False
    
    LOGGING['handlers']['console'] = {
        '()': 'logging.StreamHandler',
        'level': 'DEBUG',
        'formatter': 'simple',
    }
    
    LOGGING['loggers']['django.request']['handlers'] = ['console']
    LOGGING['loggers']['rest_framework.request']['handlers'] = ['console']
    LOGGING['loggers']['awx']['handlers'] = ['console']
    LOGGING['loggers']['awx.main.commands.run_callback_receiver']['handlers'] = ['console']
    LOGGING['loggers']['awx.main.commands.inventory_import']['handlers'] = ['console']
    LOGGING['loggers']['awx.main.tasks']['handlers'] = ['console']
    LOGGING['loggers']['awx.main.scheduler']['handlers'] = ['console']
    LOGGING['loggers']['django_auth_ldap']['handlers'] = ['console']
    LOGGING['loggers']['social']['handlers'] = ['console']
    LOGGING['loggers']['system_tracking_migrations']['handlers'] = ['console']
    LOGGING['loggers']['rbac_migrations']['handlers'] = ['console']
    LOGGING['loggers']['awx.isolated.manager.playbooks']['handlers'] = ['console']
    LOGGING['handlers']['callback_receiver'] = {'class': 'logging.NullHandler'}
    LOGGING['handlers']['fact_receiver'] = {'class': 'logging.NullHandler'}
    LOGGING['handlers']['task_system'] = {'class': 'logging.NullHandler'}
    LOGGING['handlers']['tower_warnings'] = {'class': 'logging.NullHandler'}
    LOGGING['handlers']['rbac_migrations'] = {'class': 'logging.NullHandler'}
    LOGGING['handlers']['system_tracking_migrations'] = {'class': 'logging.NullHandler'}
    LOGGING['handlers']['management_playbooks'] = {'class': 'logging.NullHandler'}
    
    DATABASES = {
        'default': {
            'ATOMIC_REQUESTS': True,
            'ENGINE': 'transaction_hooks.backends.postgresql_psycopg2',
            'NAME': "awx",
            'USER': "awx",
            'PASSWORD': "awxpass",
            'HOST': "postgresql",
            'PORT': "5432",
        }
    }
    BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
        "awx",
        "abcdefg",
        "localhost",
        "5672",
        "awx")
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
                    'ROUTING': 'awx.main.routing.channel_routing',
                    'CONFIG': {'url': BROKER_URL}}
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': '{}:{}'.format("localhost", "11211")
        },
        'ephemeral': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        },
    }
```

**Comment by matburt** [comment] 2017-11-02 12:55
I'm not sure what's up here, those look like valid values for a configmap and I'm not able to reproduce this problem locally. What version of openshift are you using? What version of the `oc` tools?

**Comment by mdhillo** [comment] 2017-11-02 13:43
OpenShift Master:v3.2.1.31 

oc v3.2.1.4-1-g1864c8f

**Comment by matburt** [comment] 2017-11-02 19:15
I'm running on 3.6.0

I'm guessing configmap has changed a bit since that time period. I don't have access to an Openshift that is that old so you're probably a bit on your own here to try to figure out how to get it to work. Otherwise I can add to the docs a minimum version of Openshift.

**Comment by RoamingQuack** [comment] 2017-11-09 21:06
This is due to older versions of Kubernetes not supporting underscores in regex values. 

https://github.com/kubernetes/kubernetes/issues/13357

**Comment by mdhillo** [comment] 2017-11-14 14:48
We are trying to deploy this on Openshift v 3.6 now and we went past this issue. Now the deployment is failing on postgres which times out on the liveness probe. We couldn't find much logging/information into the cause of the failure. Attaching the deployment log. 
```
--> Scaling postgresql-2 to 1
 
2 --> Waiting up to 10m0s for pods in rc postgresql-2 to become ready
 
3 error: update acceptor rejected postgresql-2: pods for rc "postgresql-2" took longer than 600 seconds to become ready
 ```

```
[postgresql-2.log](https://github.com/ansible/awx/files/1471223/postgresql-2.log)

**Comment by RoamingQuack** [comment] 2017-11-14 20:38
Are you able to upgrade to OpenShift 3.6.1? Curious to see if this has been addressed in that release.

**Comment by matburt** [comment] 2017-11-15 20:26
> deployment is failing on postgres which times out on the liveness probe.

That's definitely unrelated to this issue. As an aside, if you are going to run this in production you might want to some other deployment of postgres. I'm guessing that liveness probe failing is probably related to the PVC configuration of that default postgres deployment.

**Comment by matburt** [comment] 2017-11-15 20:26
I don't see myself ever going back and adding support for older openshifts so I'm going to close this issue... if it's something you care about then feel free to submit a PR for it.

**Closed as completed by matburt** 2017-11-15 20:26 UTC
Labels: type:bug, component:installer, help wanted

**Comment by mdhillo** [comment] 2017-11-16 02:47
Not sure what version you consider old. As per your previous comment, we tried deploying on 3.6.0. Do you have documentation on which versions the build really works on?
At this point we are not really looking for a production deployment, when its even failing to build.

**Comment by matburt** [comment] 2017-11-27 03:31
The original issue was against Openshift 3.2 which is not going to be supported. I don't have any issues deploying to 3.6 or 3.7 so if you are experiencing trouble there then you should open a new issue and provide enough detail for us to figure out what's going on.

Taking a shot in the dark, if your PG is missing readiness probes I'd check your available PVs and see if the PG pod is not able to allocate a PVC against them. The PG pod we pull in is from the red hat access repo so usually responds pretty well unless there aren't enough resources available on the system.
