### ISSUE TITLE
AWX 18.0.0 cannot connect to host awx:8013 ssl

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#9718] opened 2021-03-26 12:32 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

make docker-compose results in the error `WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'`

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install docker on linux
* Ansible version:  2.10.1
* Operating System: Centos 7.9.2009
* Python version: 2.7.5

##### STEPS TO REPRODUCE

`make docker-compose`

##### ACTUAL RESULTS

`2021-03-26 12:25:00,729 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.`

**Comment by shanemcd** [comment] 2021-03-26 16:56
Seems like might be a dupe of https://github.com/ansible/awx/issues/9540?

**Closed as completed** 2021-03-26 17:11 UTC
Labels: type:bug
