### ISSUE TITLE
Credentials Launch on Prompt 400 on starting job

### ISSUE THREAD

**Issue by timothynfarmer** [ansible/awx#8941] opened 2020-12-17 14:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When launching a template with a set of credentials specified for launch on prompt, the system throws an error 400 and doesn't ask for ssh_password or become_password.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Specify credentials with prompt on launch for SSH password and become password with prompt on launch.

##### EXPECTED RESULTS

UI should prompt/display a request to ask for credentials.

##### ACTUAL RESULTS

Credentials are never prompted and system doesn't proceed with template. Can be worked around by including passwords in the credentials (which is not feasible for reasons).

##### ADDITIONAL INFORMATION

None

**Comment by dellarte** [comment] 2020-12-18 17:24
I'm facing the same issue.
I upgraded my AWX yesterday and i'm on the same environment as timothynfarmer.

**Comment by wenottingham** [comment] 2020-12-18 21:01
This looks to be already filed here: https://github.com/ansible/awx/issues/8902. Closing as a duplicate of that issue.

**Closed as completed by wenottingham** 2020-12-18 21:01 UTC
Labels: type:bug, flag:community
