### ISSUE TITLE
AWX is not pulling roles with ansible-galaxy when a roles/requirements.(yml|yaml) file is present

### ISSUE THREAD

**Issue by nategerhart** [ansible/awx#8765] opened 2020-12-07 03:33 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When the **Enable Role Download** toggle is enabled in AWX versions 15.0.0 and 15.0.1 roles are not downloaded. It appears that the **Enable Role Download** toggle is either no longer effective, or is being overwritten by another setting/config.

##### ENVIRONMENT
* AWX version: 15.0.0 and 15.0.1
* AWX install method: openshift
* Ansible version:  2.10.3
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
1. Install Ansible AWX 15.0.0 or 15.0.1 in OpenShift 4.6 or OKD 4.5 and configure a job template for a playbook that includes a roles/requirements.yml file. 
2. Launch the job and watch it fail because the role can not be found.

##### EXPECTED RESULTS

The job would execute successfully. 

##### ACTUAL RESULTS

Job fails because the role could not be found an any paths:
```
ERROR! the role 'blah-blah' was not found in /tmp/awx_10_mxpev78g/project/playbooks/roles:/tmp/awx_10_mxpev78g/requirements_roles:/tmp/awx_10_mxpev78g/project/roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/awx_10_mxpev78g/project/playbooks
```

##### ADDITIONAL INFORMATION
I tried toggling the **Enable Role Download** button to see if the logic had been reversed, that did not resolve the issue. I also tried adding `"roles_enabled": "true"` to the **Extra Environment Variables** of the Settings / Jobs page in AWX - it did not help.

I confirmed that both of the above settings changes were ineffective by adding a debug step at line 167 of project_update.yml to show the value of the roles_enabled variable:
```yaml
    - name: show roles_enabled
      debug:
        msg: "{{roles_enabled|bool}}"
      tags:
        - install_roles
```
In all cases the job output always shows that variable is set to False:
```
TASK [show roles_enabled] ******************************************************
ok: [localhost] => {
    "msg": false
}
```

I also tried adding `roles_enabled: True` to the vars section of the play at line 165, and it still showed that roles_enabled was set to false in play output.

In the end the only way I was able to work around this was to comment out the conditional on this block of the play (line 190), effectively forcing it always run ansible-galaxy to download the roles.

**Comment by moreiramarti** [comment] 2020-12-07 10:51
Same thing here with 15.0.1 on kubernetes

**Comment by moreiramarti** [comment] 2020-12-07 13:02
@nategerhart I think I figured out why roles_enabld is false.
It's because we need Ansible Galaxy creds for your organization. ;)

**Comment by nategerhart** [comment] 2020-12-07 16:10
@moreiramarti, unfortunately, I don't have an organization on Ansible Galaxy, and never have. It worked just fine without having an Ansible Galaxy cred in 14.1.0 and prior releases. Additionally, for this play my requirements file is referencing several roles that are stored in private BitBucket git repos. I have a **Source Control** credential type saved in AWX which is used to pull those roles. This set up worked fine until 15.0.0 and continues to work fine in the 15.x releases if I comment out line 190 in project_update.yml. Is there something else I can try?

**Comment by moreiramarti** [comment] 2020-12-08 12:44
@nategerhart Are you sure you don't have a default organization ?
I started with 15.0.0.

**Comment by balonik** [comment] 2020-12-08 18:21
@moreiramarti I can confirm this happens on 15.*.
Project syncs of our organizations without Ansible Galaxy credentials set on Organization level ignored `requirements.yml` files and skipped the related tasks in `project_update.yml`.
This was not the case in earlier versions.

Setting dummy Ansible Galaxy credentials on Organization level fixed the issue, but I think this is more a workaround than a fix. Unless you make the Ansible Galaxy credentials mandatory field.

We are also using private GIT repositories in our `requirements.yml` file and do not require Ansible Galaxy credentials.

**Comment by nategerhart** [comment] 2020-12-09 04:01
@moreiramarti I don't have a **Default** organization but I do have another organization by a different name, I'm not sure if that matters or not. I tried adding a dummy credential of the **Ansible Galaxy/Automation Hub API Token** type and assigning it to the named organization. My playbook still failed to execute because it couldn't find the needed role. Checking the SCM Update job, it shows that the Ansible-Galaxy steps were still skipped because of the conditional did not evaluate to true.

**Comment by regner** [comment] 2020-12-09 23:13
We are running into the same issue. We are running 15.0.1. We deleted the default organization and created our own. After encountering this issue we attempted to create some new default Anisble Galaxy credentials for our own org in AWX. After having done that the project update still does not install the requirements.yaml file.

**Comment by regner** [comment] 2020-12-10 19:12
A colleague of mine found previous GitHub issue with a solution. We tested it this morning and it worked for us.

Specifically this comment here: https://github.com/ansible/awx/issues/8341#issuecomment-707310633

When we first ran the CURL command we expected to see our custom organization associated with it on the Credentials page. That wasn't the case and so we thought it wasn't working. We ended up just running another project sync to trigger the project_update playbook again and it actually did work.

Hopefully this helps others while waiting on a proper fix and thanks to @ryanpetrello for providing the fix.

**Comment by wenottingham** [comment] 2020-12-10 21:50
Closing per https://github.com/ansible/awx/issues/8341#issuecomment-707310633 - this is the intended behavior for newly created organizations. We are allowing you to control the syncing of content, and the only way to enforce that is that no credential == no syncing.

**Closed as completed by wenottingham** 2020-12-10 21:50 UTC
Labels: type:bug

**Comment by regner** [comment] 2020-12-10 23:41
@wenottingham If this issue is to be closed I think it would be prudent to open some new issues to replace it.

* Documentation should be updated to reflect this change
* The web UI of AWX should be updated to allow setting organizations on the default Ansible Galaxy credentials
