### ISSUE TITLE
Job details are not available

### ISSUE THREAD

**Issue by Erkak** [ansible/awx#1703] opened 2018-03-29 05:35 UTC
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

 - UI

##### SUMMARY

Job is successfull but results are not available.

##### ENVIRONMENT
* AWX version: 1.0.5.13
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Centos 7
* Web Browser: Firefox 52.6

##### STEPS TO REPRODUCE

Run any ad-hoc commands for any host from inventory

##### EXPECTED RESULTS

Jobs details (results and std out) are available.

##### ACTUAL RESULTS

Job is successful:
https://hostingkartinok.com/show-image.php?id=c29231e24ef189b0c88ca732bb2882c8
But results of the job are not availalble:
https://hostingkartinok.com/show-image.php?id=446298b2cf1f59ae234159abc2bf45fa

**Comment by ryanpetrello** [comment] 2018-03-29 13:33
Hey @Erkak, this is a duplicate of https://github.com/ansible/awx/issues/1700, and it should be fixed now via https://github.com/ansible/awx/pull/1691

**Closed as completed by ryanpetrello** 2018-03-29 13:33 UTC
Labels: type:bug, component:ui
