### ISSUE TITLE
_init_projects_container_image is not customizable 

### ISSUE THREAD

**Issue by renanguilhermef** [ansible/awx#13378] opened 2022-12-23 18:56 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Different of init_container_image that it is customizable, i cannot do the same for _init_projects_container_image and fails to upgrade awx-operator from 0.22.0 to 1.1.3 as I use local registry

### AWX version

21.4.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Steps to reproduce

kustomization.yml

      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      resources:
        - github.com/ansible/awx-operator/config/default?ref=1.1.3
        - awxsmt-secret.yml
        - awxsmt-deploy.yml
      
      images:
        - name: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
          newName: harbor.<registry>.com/facitsmartech/kube-rbac-proxy
          newTag: v0.13.0
        - name: quay.io/ansible/awx-operator:latest
          newName: harbor.<registry>.com/facitsmartech/awx-operator
          newTag: 1.1.3
      namespace: awxm

awxsmt-deploy:

    ---
    apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    metadata:
      name: awx
    spec:
      image: harbor.<registry>.com/facitsmartech/awx
      image_version: 21.4.0_vuln_fix 
      redis_image: harbor.<registry>.com/platform_eng_public/redis
      redis_image_version: latest
      ee_images:
      - name:  smt-awx-ee
        image: harbor.<registry>.com/facitsmartech/smt-awx-ee:latest
      control_plane_ee_image: harbor.<registry>.com/facitsmartech/smt-awx-ee:latest
      init_container_image: harbor.<registry>.com/tac-bitnami/<registry>-centos
      init_container_image_version: "latest" 
      _init_projects_container_image: harbor.<registry>.com/tac-bitnami/<registry>-centos:"latest"
      postgres_configuration_secret: awxsmt-postgres-config
      ingress_tls_secret: awxsmt-tls-config
      ingress_type: ingress
      ingress_annotations: |
        kubernetes.io/ingress.allow-http: "false"
      hostname: awxsmt-v1-pks.amer.<registry>.com
      service_type: nodeport
      projects_persistence: true
      projects_storage_access_mode: ReadWriteOnce
      secret_key_secret: awxsmt-secret-key-config
      admin_password_secret: awxsmt-admin-password-config

kubctl command:

    PS C:\Users\renan_francisco\Documents\Projects\Facilities\automation\awx-operator> kubectl apply -k .
    namespace/awxm created
    customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
    customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com created
    customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com created
    serviceaccount/awx-operator-controller-manager created
    role.rbac.authorization.k8s.io/awx-operator-awx-manager-role created
    role.rbac.authorization.k8s.io/awx-operator-leader-election-role created
    clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader created
    clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role created
    rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding created
    clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding created
    secret/awxsmt-admin-password-config created
    secret/awxsmt-postgres-config created
    secret/awxsmt-tls-config created
    service/awx-operator-controller-manager-metrics-service created
    awx.awx.ansible.com/awx created

### Expected results

AWX deployed with new awx-operator

### Actual results

    PS C:\Users\renan_francisco\Documents\Projects\Facilities\automation\awx-operator> kubectl describe pod awx-7c9958dffb-dfg6m -n awxm 
    Name:         awx-7c9958dffb-dfg6m
    Namespace:    awxm
    Priority:     0
    Node:         2c4a4d03-4bbb-4ca4-9076-30370cf9da0a/172.24.22.6
    Start Time:   Fri, 23 Dec 2022 15:33:40 -0300
    Labels:       app.kubernetes.io/component=awx
                  app.kubernetes.io/managed-by=awx-operator
                  app.kubernetes.io/name=awx
                  app.kubernetes.io/operator-version=1.1.3
                  app.kubernetes.io/part-of=awx
                  app.kubernetes.io/version=21.4.0_vuln_fix
                  pod-template-hash=7c9958dffb
    Annotations:  <none>
    Status:       Pending
    IP:           198.18.10.227
    IPs:
      IP:           198.18.10.227
    Controlled By:  ReplicaSet/awx-7c9958dffb
    Init Containers:
      init:
        Container ID:  docker://34410807318e8132f62904fecdc75e0ccc61650cc7b69de675be1d8fee89ba36
        Image:         harbor.<registry>.com/tac-bitnami/<registry>-centos:latest
        Image ID:      docker-pullable://harbor.<registry>.com/tac-bitnami/<registry>-centos@sha256:1b8b3955365fef83074c5d7b69a0b61063f95a3a353f72667d6273a92ff7ad37
        Port:          <none>
        Host Port:     <none>
        Command:
          /bin/sh
          -c
          hostname=$MY_POD_NAME
          receptor --cert-makereq bits=2048 commonname=$hostname dnsname=$hostname nodeid=$hostname outreq=/etc/receptor/tls/receptor.req outkey=/etc/receptor/tls/receptor.key
          receptor --cert-signreq req=/etc/receptor/tls/receptor.req cacert=/etc/receptor/tls/ca/receptor-ca.crt cakey=/etc/receptor/tls/ca/receptor-ca.key outcert=/etc/receptor/tls/receptor.crt verify=yes
    
        State:          Terminated
          Reason:       Error
          Exit Code:    127
          Started:      Fri, 23 Dec 2022 15:34:01 -0300
          Finished:     Fri, 23 Dec 2022 15:34:01 -0300
        Last State:     Terminated
          Reason:       Error
          Exit Code:    127
          Started:      Fri, 23 Dec 2022 15:33:47 -0300
          Finished:     Fri, 23 Dec 2022 15:33:47 -0300
        Ready:          False
        Restart Count:  2
        Requests:
          cpu:     100m
          memory:  128Mi
        Environment:
          MY_POD_NAME:  awx-7c9958dffb-dfg6m (v1:metadata.name)
        Mounts:
          /etc/receptor/tls/ from awx-receptor-tls (rw)
          /etc/receptor/tls/ca/receptor-ca.crt from awx-receptor-ca (ro,path="tls.crt")
          /etc/receptor/tls/ca/receptor-ca.key from awx-receptor-ca (ro,path="tls.key")
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wldnh (ro)
      init-projects:
        Container ID:
        Image:         quay.io/centos/centos:stream9
        Image ID:
        Port:          <none>
        Host Port:     <none>
        Command:
          /bin/sh
          -c
          chmod 775 /var/lib/awx/projects
          chgrp 1000 /var/lib/awx/projects
    
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Environment:
          MY_POD_NAME:  awx-7c9958dffb-dfg6m (v1:metadata.name)
        Mounts:
          /var/lib/awx/projects from awx-projects (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wldnh (ro)
    Containers:
      redis:
        Container ID:
        Image:         harbor.<registry>.com/platform_eng_public/redis:latest
        Image ID:
        Port:          <none>
        Host Port:     <none>
        Args:
          redis-server
          /etc/redis.conf
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Requests:
          cpu:        50m
          memory:     64Mi
        Environment:  <none>
        Mounts:
          /data from awx-redis-data (rw)
          /etc/redis.conf from awx-redis-config (ro,path="redis.conf")
          /var/run/redis from awx-redis-socket (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wldnh (ro)
      awx-web:
        Container ID:
        Image:         harbor.<registry>.com/facitsmartech/awx:21.4.0_vuln_fix
        Image ID:
        Port:          8052/TCP
        Host Port:     0/TCP
        Args:
          /usr/bin/launch_awx.sh
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Requests:
          cpu:     100m
          memory:  128Mi
        Environment:
          MY_POD_NAMESPACE:  awxm (v1:metadata.namespace)
          UWSGI_MOUNT_PATH:  /
        Mounts:
          /etc/nginx/nginx.conf from awx-nginx-conf (ro,path="nginx.conf")
          /etc/receptor/signing/work-public-key.pem from awx-receptor-work-signing (ro,path="work-public-key.pem")
          /etc/receptor/tls/ca/receptor-ca.crt from awx-receptor-ca (ro,path="tls.crt")
          /etc/receptor/tls/ca/receptor-ca.key from awx-receptor-ca (ro,path="tls.key")
          /etc/tower/SECRET_KEY from awxsmt-secret-key-config (ro,path="SECRET_KEY")
          /etc/tower/conf.d/credentials.py from awx-application-credentials (ro,path="credentials.py")
          /etc/tower/conf.d/execution_environments.py from awx-application-credentials (ro,path="execution_environments.py")
          /etc/tower/conf.d/ldap.py from awx-application-credentials (ro,path="ldap.py")
          /etc/tower/settings.py from awx-settings (ro,path="settings.py")
          /var/lib/awx/projects from awx-projects (rw)
          /var/lib/awx/rsyslog from rsyslog-dir (rw)
          /var/run/awx-rsyslog from rsyslog-socket (rw)
          /var/run/redis from awx-redis-socket (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wldnh (ro)
          /var/run/supervisor from supervisor-socket (rw)
      awx-task:
        Container ID:
        Image:         harbor.<registry>.com/facitsmartech/awx:21.4.0_vuln_fix
        Image ID:
        Port:          <none>
        Host Port:     <none>
        Args:
          /usr/bin/launch_awx_task.sh
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Requests:
          cpu:     100m
          memory:  128Mi
        Environment:
          SUPERVISOR_WEB_CONFIG_PATH:  /etc/supervisord.conf
          AWX_SKIP_MIGRATIONS:         1
          MY_POD_UID:                   (v1:metadata.uid)
          MY_POD_IP:                    (v1:status.podIP)
          MY_POD_NAMESPACE:            awxm (v1:metadata.namespace)
        Mounts:
          /etc/receptor/ from awx-receptor-config (rw)
          /etc/receptor/signing/work-private-key.pem from awx-receptor-work-signing (ro,path="work-private-key.pem")
          /etc/tower/SECRET_KEY from awxsmt-secret-key-config (ro,path="SECRET_KEY")
          /etc/tower/conf.d/credentials.py from awx-application-credentials (ro,path="credentials.py")
          /etc/tower/conf.d/execution_environments.py from awx-application-credentials (ro,path="execution_environments.py")
          /etc/tower/conf.d/ldap.py from awx-application-credentials (ro,path="ldap.py")
          /etc/tower/settings.py from awx-settings (ro,path="settings.py")
          /var/lib/awx/projects from awx-projects (rw)
          /var/lib/awx/rsyslog from rsyslog-dir (rw)
          /var/run/awx-rsyslog from rsyslog-socket (rw)
          /var/run/receptor from receptor-socket (rw)
          /var/run/redis from awx-redis-socket (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wldnh (ro)
          /var/run/supervisor from supervisor-socket (rw)
      awx-ee:
        Container ID:
        Image:         harbor.<registry>.com/facitsmartech/smt-awx-ee:latest
        Image ID:
        Port:          <none>
        Host Port:     <none>
        Args:
          /bin/sh
          -c
          if [ ! -f /etc/receptor/receptor.conf ]; then
            cp /etc/receptor/receptor-default.conf /etc/receptor/receptor.conf
            sed -i "s/HOSTNAME/$HOSTNAME/g" /etc/receptor/receptor.conf
          fi
          exec receptor --config /etc/receptor/receptor.conf
    
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Requests:
          cpu:        100m
          memory:     64Mi
        Environment:  <none>
        Mounts:
          /etc/receptor/ from awx-receptor-config (rw)
          /etc/receptor/receptor-default.conf from awx-default-receptor-config (rw,path="receptor.conf")
          /etc/receptor/signing/work-private-key.pem from awx-receptor-work-signing (ro,path="work-private-key.pem")
          /etc/receptor/tls/ from awx-receptor-tls (rw)
          /etc/receptor/tls/ca/receptor-ca.crt from awx-receptor-ca (ro,path="tls.crt")
          /var/lib/awx/projects from awx-projects (rw)
          /var/run/receptor from receptor-socket (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wldnh (ro)
    Conditions:
      Type              Status
      Initialized       False
      Ready             False
      ContainersReady   False
      PodScheduled      True
    Volumes:
      awx-application-credentials:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  awx-app-credentials
        Optional:    false
      awx-receptor-tls:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      awx-receptor-ca:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  awx-receptor-ca
        Optional:    false
      awx-receptor-work-signing:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  awx-receptor-work-signing
        Optional:    false
      awxsmt-secret-key-config:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  awxsmt-secret-key-config
        Optional:    false
      awx-settings:
        Type:      ConfigMap (a volume populated by a ConfigMap)
        Name:      awx-awx-configmap
        Optional:  false
      awx-nginx-conf:
        Type:      ConfigMap (a volume populated by a ConfigMap)
        Name:      awx-awx-configmap
        Optional:  false
      awx-redis-config:
        Type:      ConfigMap (a volume populated by a ConfigMap)
        Name:      awx-awx-configmap
        Optional:  false
      awx-redis-socket:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      awx-redis-data:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      supervisor-socket:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      rsyslog-socket:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      receptor-socket:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      rsyslog-dir:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      awx-receptor-config:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>
      awx-default-receptor-config:
        Type:      ConfigMap (a volume populated by a ConfigMap)
        Name:      awx-awx-configmap
        Optional:  false
      awx-projects:
        Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
        ClaimName:  awx-projects-claim
        ReadOnly:   false
      kube-api-access-wldnh:
        Type:                    Projected (a volume that contains injected data from multiple sources)
        TokenExpirationSeconds:  3607
        ConfigMapName:           kube-root-ca.crt
        ConfigMapOptional:       <nil>
        DownwardAPI:             true
    QoS Class:                   Burstable
    Node-Selectors:              <none>
    Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
    Events:
      Type     Reason                  Age               From                     Message
      ----     ------                  ----              ----                     -------
      Normal   Scheduled               29s               default-scheduler        Successfully assigned awxm/awx-7c9958dffb-dfg6m to 2c4a4d03-4bbb-4ca4-9076-30370cf9da0a
      Normal   SuccessfulAttachVolume  28s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-e56787c4-8d11-42f4-8370-83d1a8ae06f5" 
      Normal   Pulled                  9s (x3 over 23s)  kubelet                  Container image "harbor.<registry>.com/tac-bitnami/<registry>-centos:latest" already present on 
    machine
      Normal   Created                 8s (x3 over 23s)  kubelet                  Created container init
      Normal   Started                 8s (x3 over 23s)  kubelet                  Started container init
      Warning  BackOff                 8s (x3 over 21s)  kubelet                  Back-off restarting failed container
    PS C:\Users\renan_francisco\Documents\Projects\Facilities\automation\awx-operator> 

### Additional information

I pull images to my own local registry and deploy on our Kubernetes cluster

**Comment by kurokobo** [comment] 2022-12-23 19:31
Duplicate of https://github.com/ansible/awx-operator/issues/1162, this should be solved not in AWX but in Operator.

**Comment by relrod** [comment] 2022-12-24 15:42
Closing as duplicate, thanks @kurokobo

**Closed as not planned by relrod** 2022-12-24 15:42 UTC
Labels: type:bug, needs_triage, community
