### ISSUE TITLE
Job Settings save problem

### ISSUE THREAD

**Issue by mak241265** [ansible/awx#10311] opened 2021-05-29 16:41 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: , docker on linux
* Operating System: ubuntu 18.0.4
* Web Browser: chrome, Firefox

##### STEPS TO REPRODUCE

Login to awx as admin and scroll down to the Settings, and click Jobs settings then click edit to update one of the details then try to save

##### EXPECTED RESULTS

new value of parameter submitted and get saved

##### ACTUAL RESULTS

hitting the save button seems not working and nothing chang

##### ADDITIONAL INFORMATION

Another question i have is how to integrate awx 19.1.0 to use redis as a fact caching solution

**Comment by macthev** [comment] 2021-06-01 00:11
Confirming also seeing the issue installed via Operator.
AWX version: 19.1.0
AWX install method: , Operator
Web Browser: chrome, Firefox,Chrome,Safari

looking at the browser debugger, I see no activity pressing the save where as in the other settings panels is various activities on save. 
rgrds ...

**Comment by AlexSCorey** [comment] 2021-06-02 13:19
@mak241265 I am not able to reproduce this bug.  Can you give me a bit more details about which fields you are changing?  What about if you refresh the page, does the update data render? Any other info you can provide would be helpful.

**Comment by mak241265** [comment] 2021-06-02 14:08
> @mak241265 I am not able to reproduce this bug. Can you give me a bit more details about which fields you are changing? What about if you refresh the page, does the update data render? Any other info you can provide would be helpful.

Well for example when i try to change Per-Host Ansible Fact Cache Timeout..i click on edit and set then set the number...if i refreshe the page the field shows me the default value which is 0.....it is not about the field...all the field in Jobs setting seems does not get saved

**Comment by jakemcdermott** [comment] 2021-06-03 14:11
:wave: Hello. This is a duplicate of https://github.com/ansible/awx/issues/10123 and fixed by https://github.com/ansible/awx/pull/10171.

You should see that this is fixed when we release the next version of awx.

**Closed as completed by jakemcdermott** 2021-06-03 14:11 UTC
Labels: type:bug, flag:community
