### ISSUE TITLE
RFE: Expand view for extra vars on job template page

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#2658] opened 2018-11-11 15:49 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

There is the expand button on extra variables in Job View on current AWX release. It will show the full list of extra vars on popup. 

![screenshot from 2018-11-12 00-45-37](https://user-images.githubusercontent.com/4246532/48315030-9d719080-e614-11e8-8c0e-c40af0e67720.png)

It would be great if there is same option on Job Template page since bigger payloads are very difficult to view in small window.

**Comment by sumkincpp** [comment] 2018-11-12 07:28
Opened something similar - #2193, of course resizing extra_variables is useful too.

**Comment by wenottingham** [comment] 2018-11-12 19:15
Closing as a duplicate of #2193

**Closed as completed by wenottingham** 2018-11-12 19:15 UTC
Labels: type:enhancement, component:ui
