### ISSUE TITLE
Symlinked directories in project are missing (still in 19.2.1)

### ISSUE THREAD

**Issue by Seb0042** [ansible/awx#10483] opened 2021-06-21 13:28 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

ansible-galaxy delete links from the scm after the clone/pull.

##### ENVIRONMENT
* AWX version: 19.2.1
* AWX install method: awx-operator
* Ansible version:  2.9.22
* Operating System: 
* Web Browser:

Same as issue https://github.com/ansible/awx/issues/10308 
The installation of 19.2.1 with awx-operator did not solve the problem.

**Comment by shanemcd** [comment] 2021-06-21 13:29
Hello. Did you build a custom EE? Or are you using the defaults?

**Comment by Seb0042** [comment] 2021-06-21 14:41
Hello,
I'm using a custom EE based on the 0.3.0. 
Do I have to rebuild my custom EE ?

**Comment by shanemcd** [comment] 2021-06-21 14:51
Please try rebuilding on the latest awx-ee and see if it helps.

**Comment by Seb0042** [comment] 2021-06-21 16:47
Trying to build one from the 0.4.0 but I have some issues for the moment.
Let you know when it's ok.

**Comment by Seb0042** [comment] 2021-06-22 07:17
I can't manage to have a working EE based on 0.4.0 at the moment, I have this error when launching a job:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1374, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2896, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2959, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Pod Running

**Comment by Seb0042** [comment] 2021-06-22 09:31
I have tested with a "custom" image from 0.4.0 and it fails, links are still deleted.
Here is the Dockerfile from ansible-builder, as you see few modifications:

```
ARG ANSIBLE_RUNNER_IMAGE=quay.io/ansible/awx-ee:0.4.0
ARG PYTHON_BUILDER_IMAGE=quay.io/ansible/python-builder:latest

FROM $ANSIBLE_RUNNER_IMAGE as galaxy

ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
ADD _build /build

WORKDIR /build
RUN ansible-galaxy role install -r requirements.yml --roles-path /usr/share/ansible/roles
RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path /usr/share/ansible/collections

FROM $PYTHON_BUILDER_IMAGE as builder
ADD _build/requirements_combined.txt /tmp/src/requirements.txt
ADD _build/bindep_combined.txt /tmp/src/bindep.txt
RUN assemble

FROM $ANSIBLE_RUNNER_IMAGE
COPY --from=galaxy /usr/share/ansible /usr/share/ansible
COPY --from=builder /output/ /output/
USER root
RUN /output/install-from-bindep && rm -rf /output/wheels
ADD pmp.py /usr/local/lib/python3.8/site-packages/ansible/plugins/lookup/
```

**Comment by Seb0042** [comment] 2021-06-22 09:39
Still not working with a custom image from 0.4.0, links are deleted.

Below the dockerfile of ansible-builder:

```
ARG ANSIBLE_RUNNER_IMAGE=quay.io/ansible/awx-ee:0.4.0
ARG PYTHON_BUILDER_IMAGE=quay.io/ansible/python-builder:latest

FROM $ANSIBLE_RUNNER_IMAGE as galaxy

ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
ADD _build /build

WORKDIR /build
RUN ansible-galaxy role install -r requirements.yml --roles-path /usr/share/ansible/roles
RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path /usr/share/ansible/collections

FROM $PYTHON_BUILDER_IMAGE as builder
ADD _build/requirements_combined.txt /tmp/src/requirements.txt
ADD _build/bindep_combined.txt /tmp/src/bindep.txt
RUN assemble

FROM $ANSIBLE_RUNNER_IMAGE
COPY --from=galaxy /usr/share/ansible /usr/share/ansible

COPY --from=builder /output/ /output/
USER root
RUN /output/install-from-bindep && rm -rf /output/wheels
USER 1000
ADD pmp.py /usr/local/lib/python3.8/site-packages/ansible/plugins/lookup/
```

bindep.txt:
python38-devel

requirements.txt:
```
awxkit>=13.0.0
boto>=2.49.0
botocore>=1.12.249
boto3>=1.9.249
mysql-connector-python>=8.0.23
psycopg2-binary>=2.8.6
python-gitlab>=2.4.0
urllib3>=1.25.11
netaddr>0.1
```
requirements.yml:
```
---
collections:
  - community.vmware
  - theforeman.foreman
```

**Comment by AlanCoding** [comment] 2021-06-24 12:58
@jbradberry could this be resolved by https://github.com/ansible/ansible-runner/pull/737

**Comment by jbradberry** [comment] 2021-06-24 14:39
Yes, this is exactly what that PR was intended to fix.

**Closed as completed** 2021-06-24 14:52 UTC
Labels: type:bug
