### ISSUE TITLE
Job stays in pending 'Waiting' State.

### ISSUE THREAD

**Issue by balu7771** [ansible/awx#1723] opened 2018-04-03 19:27 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

After adding a new project, the project pull job stays with status 'Pending'. 

##### ENVIRONMENT
* AWX version: Code taken from opensource late in Nov 2016 and built locally. 
* AWX install method: docker-compose and deployed to kubernetes. 
* Ansible version:  2.4.2.0
* Operating System: Windows 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. The AWX project was working fine in Dev server. We developers, moved on to build the image with SSL, Vanity URLs etc. Deployed again (in the meantime, our kubernetes clusters got upgraded.). Now, when I test the UI, the job stays at pending state. 
- 
![image](https://user-images.githubusercontent.com/26941146/38270794-207877ac-374a-11e8-915b-eae5c40dec1a.png)

- <CompanyTowerHost>/api/v2/instances/ ==> shows count 57. 
- <CompanyTowerHost>/api/v2/unified_jobs/?status=running ==> shows count 0.

Any help is much appreciated as my prod deployment got stopped after finding this issue. It was working fine before 2 months. And I don't see clearly what might have caused the issue. 
The changes were minimal, like Adding Vanity URLs, Enabling SSL, etc. 
Then, the kubernetes cluster got upgraded too. 

##### EXPECTED RESULTS

Projects can be pulled with no issue. 

##### ACTUAL RESULTS

1. Projects staying in waiting status. 
2. If I try to manually create project, i see project ROOT as /projects/

##### ADDITIONAL INFORMATION

awx-web-devel image has no error log
and awx-rabbit has no error log. 
It is the UI that stays in 'Waiting' status while trying to run the clean/update job of the project. 

Will be watching actively and can provide more info if needed. 
Thank you.

**Comment by jaredevantabor** [comment] 2018-04-04 18:54
This might be a duplicate of #1724. Though I was no able to reproduce this locally on dev.

**Comment by balu7771** [comment] 2018-04-04 23:03
I don't think they are duplicate. I then analyzed and added the new changes to my kubernetes deployment and config files. Specially line 17 in config appeared to fix part of my issue. 

https://github.com/ansible/awx/tree/1.0.5/installer/roles/kubernetes/templates
https://github.com/ansible/awx/blob/1.0.5/installer/roles/kubernetes/templates/configmap.yml.j2#L17

But still see this error in logs and unable to open the UI. Can open the APIs that dont need authentication like ping api. 
_22:57:27 celeryd.1   |     raise RuntimeError("Cluster Host Not Found: {}".format(settings.CLUSTER_HOST_ID))
22:57:27 celeryd.1   | RuntimeError: Cluster Host Not Found: awx-b7bb7fd8d-rjkd8_

currently the kubernetes pod I am running on is that only: awx-b7bb7fd8d-rjkd8 .

So, why the above error comes and how do I fix it.

**Comment by balu7771** [comment] 2018-04-04 23:04
Please see if the pic of my ping api gives any good detail: 

_This ping was showing 57 (even the old pods without line 17 in https://github.com/ansible/awx/blob/1.0.5/installer/roles/kubernetes/templates/configmap.yml.j2#L17 )_
![image](https://user-images.githubusercontent.com/26941146/38339189-98e964ba-3832-11e8-803e-14448f14e2e1.png)

**Comment by balu7771** [comment] 2018-04-04 23:12
FYI, my postgres DB runs externally on a linux node. We connect to the kubernetes awx image (awx-web-devel) using the DB params. And our kubernetes deployment platform has load balancer with multiple worker nodes.

**Comment by wenottingham** [comment] 2018-06-01 17:55
I note that this says `AWX version: Code taken from opensource late in Nov 2016 and built locally.`

Your ping information shows two wildly different versions in your cluster (1.0.5 and 1.0.1). That is not going to work reliably.

Please deploy matching versions, and report back if you have issues.

**Closed as completed by wenottingham** 2018-06-01 17:56 UTC
Labels: type:bug, component:api, component:ui
