### ISSUE TITLE
AWX collection inventory plugin not loading after install

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4925] opened 2019-10-05 16:38 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Installing `awx.awx` collection is not allowing the "tower" inventory plugin to be used.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

This should put the beta content in your user collections location

```
ansible-galaxy collection install awx.awx:0.0.1-beta
```

Then have an inventory file like

```yaml
plugin: awx.awx.tower
host: https://foo.invalid
inventory_id: 302
```

(still need final answer of syntax `plugin: tower` vs `plugin: awx.awx.tower`)

##### EXPECTED RESULTS

Connection / auth errors

##### ACTUAL RESULTS

What's described in https://github.com/ansible/ansible/issues/63148

##### ADDITIONAL INFORMATION

We need to test this with our content specifically when it's fixed, because this still leaves open the possibilities of other bugs on our side.

**Comment by squidboylan** [comment] 2019-10-18 20:40
I tested this with awx.awx version: 7.0.0 by adding the `awx` directory in https://github.com/squidboylan/Ansible-inventory-file-examples/tree/master/collections and installing the ansible devel branch, then running `ansible-inventory -i awx/tower.yml --list --playbook-dir=awx/` from that collections dir:

```
{
    "_meta": {
        "hostvars": {
            "foo": {
                "remote_tower_enabled": "true",
                "remote_tower_id": 2
            },
            "localhost": {
                "ansible_connection": "local",
                "ansible_python_interpreter": "{{ ansible_playbook_python }}",
                "remote_tower_enabled": "true",
                "remote_tower_id": 1
            }
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "foo",
            "localhost"
        ]
    }
}
```

This seems to work as intended. Closing

**Closed as completed by squidboylan** 2019-10-18 20:40 UTC
Labels: type:bug, component:awx_collection
