### ISSUE TITLE
Upgrade Ansible version shipped with awx_web image to 2.9.x 

### ISSUE THREAD

**Issue by thadreez** [ansible/awx#5844] opened 2020-02-07 09:53 UTC
##### ISSUE TYPE
 - Feature Idea
root@ubuntu:/# docker exec -it awx_web bash
bash-4.4# ansible --version
**ansible 2.8.5**
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]

##### SUMMARY

Would it be possible to upgrade ansible version to 2.9.x ? 
The reason why I am asking this is because some modules that are released only in 2.9.x 
- Troubleshooting:
even if i specify these modules manually, i'll need to troubleshoot other issues.  

Would it be possible to upgrade Ansible version to 2.9 ?

**Comment by ryanpetrello** [comment] 2020-02-07 13:23
duplicate of https://github.com/ansible/awx/issues/5827

**Closed as completed by ryanpetrello** 2020-02-07 13:23 UTC
