### ISSUE TITLE
Testing external logging fails for udp syslog logging

### ISSUE THREAD

**Issue by dglinder** [ansible/awx#1062] opened 2018-01-25 22:46 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When I have configured Tower/AWX logging to use "udp/514" for syslog logging, logging works but the "test" button produces a red "toast" message on the GUI reporting "HTTPConnectionPool(host='syslog.net.west.com', port=514): Read timed out. (read timeout=5)" 

##### ENVIRONMENT
* Tower version: 3.2.2
* Tower install method: setup.sh
* Ansible version:  2.4.2
* Operating System: RedHat 7.4
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

We have the following setup in the "Logging" configuration category:
Aggregator: syslog.server.hostname.com
Port: 514
Type: other
Loggers: awx, activity_stream, job_events, system_tracking
Protocol: udp
Threshold: Info
Username: blank (not needed for syslog)
Enable external logging: On
Tracking facts individually: Off

##### EXPECTED RESULTS

Expect a "test" message in syslog and NO error message on the GUI.

##### ACTUAL RESULTS

There is no "test" message in the syslog output, and an error message is displayed in the GUI.

##### ADDITIONAL INFORMATION

It appears that the Test button is expecting to interact with the other logging interfaces and require a TCP HTTP connection, not the simplistic UDP Syslog message.

**Comment by dglinder** [comment] 2018-01-25 22:47
I opened ticket #02015569 with RedHat support on this, but it appears that logging via UDP is working, just the Test button is malfunctioning in this case.

**Comment by matburt** [comment] 2018-01-26 13:40
I'm going to switch this to an enhancement request to support UDP based logging directly to syslog.

**Comment by wenottingham** [comment] 2018-01-26 17:37
Note that 'other' logging is HTTP, not syslog... UDP isn't even valid for that choice.

**Comment by dglinder** [comment] 2018-01-27 15:40
@matburt  - Thanks, our enterprise systems aren't (yet!) really beyond syslog logging at this time.

@wenottingham - I hadn't delved into the code yet to look (\#PythonNewbie), but it is interesting that there is some data showing up in our syslog recipients files.  And it explains why we get the occasional HTML formatted data showing up.

**Comment by ryanpetrello** [comment] 2018-01-30 14:31
awx _does_ currently support UDP for logging, but the "Test" button is broken if you select "UDP" as the protocol.  This is a bug and is being fixed in the near future.

**Comment by matburt** [comment] 2018-01-30 16:45
I think our udp logging mechanism was intended for logstash-based systems ideally.

**Comment by ryanpetrello** [comment] 2018-01-30 16:52
Yep.  When we implemented this initially, it was to support logstash over udp.  If we wanted to extend awx to provide a syslog formatter, that's an enhancement somebody would have to implement.

**Comment by ryanpetrello** [comment] 2018-01-30 18:28
@dglinder for clarity, I'm implementing a change (which will be in awx soon) that fixes _this_ issue for the "Test" button when UDP is in use (which is a bug).

The implementation, however, _will_ work slightly differently than the test for TCP-based endpoints.  We don't really have control over the destination host, so determining UDP "connectivity" with any real certainly likely isn't possible. If there's no socket open, the host will usually respond with an ICMP Destination Unreachable packet. That said, many firewalls filter these packets, so if you don't receive one, you can't really make an accurate judgement call regarding "connectivity". Also, ICMP itself is just as susceptible to failure, and it doesn't do retransmissions.

The best we can probably do here is to fire off a UDP packet and reply with an HTTP 201 in the API response. Actually checking that the log was received on the other end is an exercise for the user.

**Comment by dglinder** [comment] 2018-01-31 00:55
@ryanpetrello  For the most part, those of us who still use syslog over UDP understand that it's a best effort message and it'll be understandable that a full three-way handshake confirmation won't be possible.  However, having a true "this is a test message from AWX/Tower" showing up would help when working with the InfoSec team getting this setup.

**Comment by ryanpetrello** [comment] 2018-01-31 13:35
> However, having a true "this is a test message from AWX/Tower" showing up would help when working with the InfoSec team getting this setup.

@dglinder perfect - that’s exactly what my upcoming patch will provide.

**Comment by ryanpetrello** [comment] 2018-03-28 18:21
Hey @dglinder, this should be resolved in awx as of https://github.com/ansible/awx/commit/982539f4442b3003ba741af9dd30d0ef711a86f4

**Closed as completed by ryanpetrello** 2018-03-28 18:21 UTC
Labels: type:bug, component:api
