### ISSUE TITLE
User Details link is currently broken

### ISSUE THREAD

**Issue by Spredzy** [ansible/awx#8697] opened 2020-11-27 10:39 UTC
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

When clicking on User Details one is being taken to `https://url/users/1/details/` instead of `https://url/#/users/1/details/` leading to a 404.

##### ENVIRONMENT
* AWX version: devel
* AWX install method: N/A
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: Firefox

##### STEPS TO REPRODUCE

* Install
* Log In
* Admin > User Details
* 404

##### EXPECTED RESULTS

*  Landing on proper page

##### ACTUAL RESULTS

* Landing on a 404

##### ADDITIONAL INFORMATION

Seems like it has been dealt with somehow before https://github.com/ansible/awx/issues/7526 but it still seem to fail. Not sure what `/next` is (ie. rather than `/#`

**Comment by unlikelyzero** [comment] 2020-11-27 15:29
This is a dupe of https://github.com/ansible/awx/issues/8478

**Closed as completed by unlikelyzero** 2020-11-27 15:29 UTC
Labels: type:bug
