### ISSUE TITLE
 Show a Markdown file (e.g.: README.md) from the project in the page of a job template

### ISSUE THREAD

**Issue by ragnarensar** [ansible/awx#14436] opened 2023-09-12 20:36 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

In job templates, the playbook is set from a project. It would be useful if a Markdown file (e.g. README.md) from the same project could be selected in the job template. A Markdown browser window could display the content directly in the job template page. For example, the parameterization (variables) of roles or tasks in the playbook could be described this way. The necessary information would be immediately available when a job template is to be executed.

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

In the edit dialog of a job template, a selection field for a Markdown file (similar to that of the playbook) would have to be added.

In the main page of the job template, a Markdown browser window would have to be added, which nicely displays the file content.

### Current results

Currently it is not possible to access documentation of the configured playbook in the job template. Neither by hyperlink nor by direct display of a help page.

### Sugested feature result

The parameterization (variables) of roles or tasks in the playbook  would be immediately available when a job template is to be executed.

**Comment by marshmalien** [comment] 2023-09-13 15:42
Hello! Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report. 

I believe this issue appears to be a duplicate of https://github.com/ansible/awx/issues/2905. To keep the discussion centralized, let's continue the conversation on the original issue. 

Thank you once again for this and your interest in AWX!

**Closed as completed by marshmalien** 2023-09-13 15:42 UTC
Labels: type:enhancement, component:ui, needs_triage, community, component:ui_next
