### ISSUE TITLE
Can't create a new workflow

### ISSUE THREAD

**Issue by giovannifl** [ansible/awx#4179] opened 2019-06-27 16:41 UTC
ISSUE TYPE
 - Bug Report

COMPONENT NAME
 - UI

SUMMARY
When I select to create a new workflow job template, all fields are grayed out and I can't insert any value.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method:  docker on linux
* Ansible version:  2.8.1
* Operating System: Ubuntu 18.04
* Web Browser: Chrome 75.0.3770.100

STEPS TO REPRODUCE
In the Templates section, click on the green button and selected "Workflow Template"

EXPECTED RESULTS
Been able to fill empty fields and save it

ACTUAL RESULTS
It is not possible to edit any field
 
ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/19493042/60284138-ba887480-9902-11e9-8af8-848a5ce9f4ab.png)

**Comment by ryanpetrello** [comment] 2019-06-27 17:02
Duplicate of https://github.com/ansible/awx/issues/4091

**Closed as completed by ryanpetrello** 2019-06-27 17:02 UTC
Labels: component:ui

**Comment by giovannifl** [comment] 2019-07-02 17:01
Just upgraded from AWX 5.0.0 to AWX 6.0.0 and now Workflow templates fields are editable.
