### ISSUE TITLE
Output is not visible until job is finished

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#813] opened 2017-12-13 11:27 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When you start any job there is no output visible until job finishes

##### ENVIRONMENT
* AWX version: 1.0.1 - head as well
* AWX install method: docker on linux
* Operating System: RedHat
* Web Browser: firefox

##### STEPS TO REPRODUCE
Run any job see nothing in output

##### EXPECTED RESULTS

Output should be displayed as it's happening

**Comment by sekozzi** [comment] 2017-12-13 12:04
Hello,

You can follow to below steps that issues fix .

open install.yml
vi installer/local_docker/tasks/main.yml

and you add following line;
- name: Activate AWX Web Container
  docker_container:
    name: awx_web
    state: started
    restart_policy: unless-stopped
    image: "{{ awx_web_docker_actual_image }}"
    volumes:
      **- /awx_shared:/var/lib/awx/job_status:ro**

...
...
...

- name: Activate AWX Task Container
  docker_container:
    name: awx_task
    state: started
    restart_policy: unless-stopped
    image: "{{ awx_task_docker_actual_image }}"
    volumes:
      **- /awx_shared:/var/lib/awx/job_status:rw**
...
...
...

After, you run again install.yml.

# This is unofficial fix.

**Comment by benapetr** [comment] 2017-12-13 13:06
hmm I will try but why there is no official patch?

**Comment by sekozzi** [comment] 2017-12-13 13:21
I don't know. I am waiting for the offical patch.

**Comment by ryanpetrello** [comment] 2017-12-13 14:31
The official solution to this is actively being worked on:

Duplicate of https://github.com/ansible/awx/issues/200

**Closed as completed** 2017-12-13 14:34 UTC
