### ISSUE TITLE
nginx problem in docker-compose deployment

### ISSUE THREAD

**Issue by maxxitutti** [ansible/awx#9923] opened 2021-04-15 19:32 UTC
during the make docker-compose there is an errors 

""tools_awx_1 | 2021-04-15 19:15:53,027 INFO success: awx-receptor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | 2021-04-15 19:15:53,181 INFO exited: awx-nginx (exit status 2; not expected)
tools_awx_1 | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
tools_awx_1 | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'
"

inside the docker container

bash-4.4# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] getpwnam("nginx") failed
nginx: configuration file /etc/nginx/nginx.conf test failed

i need to manually add a user nginx (inside container) 
```
useradd -s /bin/false nginx -g 994
bash-4.4# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
nginx
```
and everythink worked ...
please add on depllyment adding user nginx

**Comment by wenottingham** [comment] 2021-04-15 21:11
Hi - Please don't file multiple copies of the same issue. Closing as a duplicate of #9920.

**Closed as completed by wenottingham** 2021-04-15 21:11 UTC
