### ISSUE TITLE
Can't select a different inventory for a job in a workflow step

### ISSUE THREAD

**Issue by astraios** [ansible/awx#414] opened 2017-10-12 16:14 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

In a workflow template composed of job templates where inventory's "prompt on launch" is checked, It is impossible to select an inventory for those jobs.

##### ENVIRONMENT
* AWX version: AWX 1.0.1.10
* Ansible version: 2.4
* AWX install method: docker on Linux with the awx github repo, "ansible-playbook -i inventory install.yml"

##### STEPS TO REPRODUCE

* Create a Job Template, choose a project, a playbook, choose an inventory and check the "prompt on launch" option.
* Create a Workflow template, Open the workflow editor and add the previously created Job.
* When you edit this step, try to change the inventory and save.
* Open the Workflow template, open the workflow editor and note that your previous change has not been saved

##### EXPECTED RESULTS

* The selected inventory should have been memorized

##### ACTUAL RESULTS

* When you run a Workflow, there is no way to target a different inventory than the one configured in the job template, even if the "prompt on launch" option is check.

**Comment by wenottingham** [comment] 2017-10-12 16:29
This is a duplicate of #169

**Closed as completed by wenottingham** 2017-10-12 16:29 UTC
Labels: type:bug, component:ui

**Comment by astraios** [comment] 2017-10-12 17:10
Hi @wenottingham,

I don't think that's a duplicate of #169, if I get this issue correctly, it's about implementing a new feature concerning Workflow scheduling.

Here, I'm facing a bug. I want to add Job in a workflow step. This job is configured to allow the user to select the inventory when it's scheduled and for this workflow, I want to target another inventory like this

![issue-github](https://user-images.githubusercontent.com/16399198/31508879-c3ab74ea-af7f-11e7-9b20-e93f13eb4f84.gif)

But I can't. With this bug, I can't reuse a Job, through several different workflows because I want those to target different inventories.

Regards,
Thomas
