### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### ISSUE THREAD

**Issue by MichaelPak** [ansible/awx#5496] opened 2019-12-13 07:04 UTC
##### SUMMARY
Sometimes, when I try to open a playbook, I get modal screen with error

```
Invalid search term entered. GET returned: -1
```

In browser's developer tools in the console I see an error

```
vendor.cab15822439fefbeeb84.js:201 GET https://my.domain/api/v2/jobs/35478/job_events/?order_by=-counter&page=1&page_size=50 net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
```

##### ENVIRONMENT
* AWX version: 9.0.1.0
* AWX install method: docker on linux
* Web Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by wenottingham** [comment] 2019-12-13 18:08
Do you have logs from the instance when this happens?

**Comment by MichaelPak** [comment] 2019-12-17 10:13
In `awx_web` container I found nginx errors:
```
{"log":"2019/12/17 09:54:29 [crit] 123#0: *44468 open() \"/var/lib/nginx/tmp/uwsgi/8/11/0000000118\" failed (13: Permission denied) while reading upstream, client: 10.77.15.16, server: _, request: \"GET /api/v2/jobs/35712/job_events/?order_by
=-counter\u0026page=1\u0026page_size=50 HTTP/1.1\", upstream: \"uwsgi://127.0.0.1:8050\", host: \"my.domain\", referrer: \"https://my.domain/\"\n","stream":"stderr","time":"2019-12-17T09:54:29.598346764Z"}
```

And inside container:
```
[root@awx mialpak]# docker exec -it awx_web bash
bash-4.4# ls -l /var/lib/nginx/
total 4
drwxrwxrwx. 7 systemd-coredump render 4096 Jul 24 12:30 tmp
bash-4.4# ls -l /var/lib/nginx/tmp/
total 20
drwx------.  2 nginx root 4096 Jul 24 12:30 client_body
drwx------.  2 nginx root 4096 Jul 24 12:30 fastcgi
drwx------.  2 nginx root 4096 Jul 24 12:30 proxy
drwx------.  2 nginx root 4096 Jul 24 12:30 scgi
drwx------. 12 nginx root 4096 Jul 26 10:59 uwsgi
bash-4.4# ls -l /var/lib/nginx/tmp/uwsgi/
total 40
drwx------. 81 systemd-coredump render 4096 Oct 25 10:47 0
drwx------. 81 systemd-coredump render 4096 Oct 25 08:20 1
drwx------. 81 systemd-coredump render 4096 Oct 25 08:20 2
drwx------. 81 systemd-coredump render 4096 Oct 25 08:20 3
drwx------. 81 systemd-coredump render 4096 Oct 25 08:20 4
drwx------. 81 systemd-coredump render 4096 Oct 25 08:23 5
drwx------. 81 systemd-coredump render 4096 Oct 25 08:32 6
drwx------. 81 systemd-coredump render 4096 Oct 25 08:32 7
drwx------. 81 systemd-coredump render 4096 Oct 25 09:57 8
drwx------. 81 systemd-coredump render 4096 Oct 25 10:13 9
```

**Comment by mdecalf** [comment] 2020-01-31 16:24
Hello,

Exactly same issue for me.

The max size of json playload returned by a query seem's to be limited at 82.51 KB

"SyntaxError: JSON.parse: unterminated string literal at line 1 column 84515 of the JSON data" when I explained the response of a query ex : /api/v2/jobs/***/job_events/?order_by=-counter&page=1&

It's not only on playbook or template but on all kind of resources

**Comment by Hoijima** [comment] 2020-04-18 19:23
+ 
getting net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
trying to open:

1. Setting
2. Running jobs
3. Just randomly browsing templates

Tried to include custom nginx config disabling proxy buffer and increasing client body, didn't help.

**Comment by ryanpetrello** [comment] 2020-04-20 13:35
Are either of you accessing AWX through some sort of proxy?

**Comment by JulianMa** [comment] 2020-05-14 08:09
I think this is a duplicate of #5230.
There is also a workaround for this issue in the comments section.

**Comment by ryanpetrello** [comment] 2020-05-14 14:38
Hey @r3sist3nt - which comment specifically?

**Comment by JulianMa** [comment] 2020-05-18 08:45
@ryanpetrello The File-Owner of the nginx folder ist wrong, changing it manually back to nginx:nginx has fixed this behavior in #5230. As you can see in the comment of @MichaelPak, his file-permissions are also broken (systemd-coredump:render is owning the files).

**Comment by JulianMa** [comment] 2020-05-18 08:49
@wenottingham i think this can be marked as duplicate of #5230. Can you confirm?

**Comment by ryanpetrello** [comment] 2020-05-18 15:40
Duplicate of https://github.com/ansible/awx/issues/5230

**Comment by ryanpetrello** [comment] 2020-05-18 15:40
Thanks for digging into this and helping troubleshoot, @r3sist3nt 🏅

**Closed as completed by ryanpetrello** 2020-05-18 15:40 UTC
Labels: help wanted

**Comment by mdecalf** [comment] 2020-05-19 06:41
I confirm, the workaround of #5230 works

Thank you @r3sist3nt

**Comment by dostonbekabdumuxtorov** [comment] 2022-12-23 05:52
hi
