### ISSUE TITLE
Update Postgress Helm to Bitnami Chart. 

### ISSUE THREAD

**Issue by patrickdeutsch-wk** [ansible/awx#9068] opened 2021-01-12 19:35 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Helm Chart for postgress is not accessible at deprecated location
Updating to bitnami should work           
```
 - name: Deploy and Activate Postgres (Kubernetes)
      shell: |
        helm repo add stable https://charts.bitnami.com/bitnami
        helm repo update
        helm upgrade {{ postgresql_service_name }} \
          --install \
          --namespace {{ kubernetes_namespace }} \
          --version="8.3.0" \
          --values {{ values_file.path }} \
          stable/postgresql
      register: kubernetes_pg_activate
```

##### STEPS TO REPRODUCE

Run a clean install via kubernetes. Build should fail on postgres install

##### EXPECTED RESULTS

Postgres Helm Chart is installed to Kube Cluster. 

##### ACTUAL RESULTS

TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "helm repo add stable https://charts.helm.sh/stable\nhelm repo update\nhelm upgrade awx-postgresql  --install   --version=\"8.3.0\"  --values /var/folders/sd/48bdyf4x0vv_d2nb3dy75hbc0000gn/T/ansible.w74b1uty.yml  stable/postgresql\n", "delta": "0:00:03.157358", "end": "2021-01-12 12:23:54.736955", "msg": "non-zero return code", "rc": 1, "start": "2021-01-12 12:23:51.579597", "stderr": "WARNING: \"kubernetes-charts.storage.googleapis.com\" is deprecated for \"stable\" and will be deleted Nov. 13, 2020.\nWARNING: You should switch to \"https://charts.helm.sh/stable\" via:\nWARNING: helm repo add \"stable\" \"https://charts.helm.sh/stable\" --force-update\nError: repository name (stable) already exists, please specify a different name\nWARNING: \"kubernetes-charts.storage.googleapis.com\" is deprecated for \"stable\" and will be deleted Nov. 13, 2020.\nWARNING: You should switch to \"https://charts.helm.sh/stable\" via:\nWARNING: helm repo add \"stable\" \"https://charts.helm.sh/stable\" --force-update\nWARNING: \"kubernetes-charts.storage.googleapis.com\" is deprecated for \"stable\" and will be deleted Nov. 13, 2020.\nWARNING: You should switch to \"https://charts.helm.sh/stable\" via:\nWARNING: helm repo add \"stable\" \"https://charts.helm.sh/stable\" --force-update\nError: failed to download \"stable/postgresql\" at version \"8.3.0\" (hint: running `helm repo update` may help)", "stderr_lines": ["WARNING: \"kubernetes-charts.storage.googleapis.com\" is deprecated for \"stable\" and will be deleted Nov. 13, 2020.", "WARNING: You should switch to \"https://charts.helm.sh/stable\" via:", "WARNING: helm repo add \"stable\" \"https://charts.helm.sh/stable\" --force-update", "Error: repository name (stable) already exists, please specify a different name", "WARNING: \"kubernetes-charts.storage.googleapis.com\" is deprecated for \"stable\" and will be deleted Nov. 13, 2020.", "WARNING: You should switch to \"https://charts.helm.sh/stable\" via:", "WARNING: helm repo add \"stable\" \"https://charts.helm.sh/stable\" --force-update", "WARNING: \"kubernetes-charts.storage.googleapis.com\" is deprecated for \"stable\" and will be deleted Nov. 13, 2020.", "WARNING: You should switch to \"https://charts.helm.sh/stable\" via:", "WARNING: helm repo add \"stable\" \"https://charts.helm.sh/stable\" --force-update", "Error: failed to download \"stable/postgresql\" at version \"8.3.0\" (hint: running `helm repo update` may help)"], "stdout": "Hang tight while we grab the latest from your chart repositories...\n...Unable to get an update from the \"stable\" chart repository (https://kubernetes-charts.storage.googleapis.com):\n\tfailed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden\nUpdate Complete. ⎈Happy Helming!⎈\nRelease \"awx-postgresql\" does not exist. Installing it now.", "stdout_lines": ["Hang tight while we grab the latest from your chart repositories...", "...Unable to get an update from the \"stable\" chart repository (https://kubernetes-charts.storage.googleapis.com):", "\tfailed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden", "Update Complete. ⎈Happy Helming!⎈", "Release \"awx-postgresql\" does not exist. Installing it now."]}

**Comment by ryanpetrello** [comment] 2021-01-13 17:52
Duplicate of https://github.com/ansible/awx/issues/8715

**Closed as completed by ryanpetrello** 2021-01-13 17:52 UTC
Labels: type:bug
