### ISSUE TITLE
Add yes/no checkbox options for user surveys

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#1782] opened 2018-04-18 22:38 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
I manage a number of playbooks designed for automating highly-branched tasks that used to be performed by operators. The nature of this branching logic is highly boolean, and so I *very* frequently find myself using `multiple choice` type user surveys with `[true, false]` options. This requires more effort to make the survey, more effort to complete it, and requires care in input sanitation (where inputs are not `true` and `false`, but `"true"` and `"false"`. The `bool` filter is a life-saver.)

User surveys should support checkbox type fields, with `true` and `false` defaults.

Perhaps they could be trinary checkboxes, with `true`, `false`, and `omitted`, to be more in-line with other non-required extra variables, but that strikes me as a potential UI headache.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux

**Comment by wenottingham** [comment] 2018-04-19 14:11
duplicate of https://github.com/ansible/awx/issues/553

**Closed as completed by wenottingham** 2018-04-19 14:11 UTC
Labels: component:api, component:ui
