### ISSUE TITLE
AWX 17.0.0 unable to run workflow with system generated surveys

### ISSUE THREAD

**Issue by Lobout** [ansible/awx#9171] opened 2021-01-26 19:28 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
unable to run any templates, or workflows when you have a survey that is created using the awx.tower_workflow_job_template module

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: Docker on Linux
* Ansible version:  2.9.16
* Operating System: Redhat 7
* Web Browser: Firefox/Chrome/Edge

##### STEPS TO REPRODUCE

create a playbook/workflow that needs a survey to fill in information, create another playbook to update the survey based on data collection from other sources.  run the survey playbook to create/update the survey in the workflow/playbook, examine the survey to ensure all values are created, then try and run the playbook/workflow

##### EXPECTED RESULTS

to be able to answer the survey questions and run the playbook/workflow.

##### ACTUAL RESULTS

get a blank screen with no survey presented.

##### ADDITIONAL INFORMATION

If there are any logs/information you require let me know.

**Comment by warriorsoul15** [comment] 2021-01-26 19:32
Any template or workflow with a survey renders a blank page when you launch it.

Also in workflow vizualizer if you try to add a node with a survey attached it also give you a blank rendered screen.

17.0.0  docker
Testing firefox, chrome, edge

**Comment by MaartenMol** [comment] 2021-01-26 22:41
Running AWX 17.0.1 with Ansible 2.9.17 on Docker. Can't reproduce the problem. Maybe it's fixed in this version? Tested in Edge Chromium.

**Comment by Lobout** [comment] 2021-01-27 15:12
> 
> 
> Running AWX 17.0.1 with Ansible 2.9.17 on Docker. Can't reproduce the problem. Maybe it's fixed in this version? Tested in Edge Chromium.

Upgraded to 17.0.1 and that did not fix the issue.

**Comment by Lobout** [comment] 2021-01-27 15:18
If i delete the survey and create it manually it seems to work fine, but if i create/update the survey with my script, the survey is updated, and I can see the details in the API, but when i try and launch the job it does not open the survey and produces a blank screen.

**Comment by blomquisg** [comment] 2021-01-29 18:13
@Lobout do you have any errors in the browser javascript console?  can you include that?

**Comment by Lobout** [comment] 2021-02-01 16:07
> 
> 
> @Lobout do you have any errors in the browser javascript console? can you include that?

![image](https://user-images.githubusercontent.com/20486738/106484314-80d40400-647d-11eb-93d8-62596a309a32.png)
![image](https://user-images.githubusercontent.com/20486738/106484532-b2e56600-647d-11eb-87f9-3541014957a3.png)

**Comment by Here-Be-Dragons** [comment] 2021-03-02 14:56
I am experiencing the same issue with any surveys that are created using the `awx.awx.tower_job_template` resource from collection awx.awx 17.0.1.

**Comment by Here-Be-Dragons** [comment] 2021-03-02 15:22
[The API Documentation](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Job_Templates/Job_Templates_job_templates_survey_spec_create) for survey creation claims that you need to pass an array for multiple choice option types, however when I look at working (via Web GUI creation) and non-working (via API creation), a GET returns different results:


**Not Working, Created via API following the array style shown in the API reference:**
```json
{
    "name": "Deploy Survey",
    "description": "Values needed for deploy",
    "spec": [
        {
            "question_name": "Instance Designator",
            "question_description": "Instance Name",
            "required": true,
            "type": "multiplechoice",
            "variable": "DB_NAME",
            "min": 6,
            "max": 6,
            "default": "",
            "choices": [
                "FID1",
                "FID2",
                "FID3",
                "FID4",
                "FID5",
                "FID6"
            ],
            "new_question": true
        }
    ]
}
```

**Working, created via the Web GUI in AWX 17.0.0:**
```json
{
    "name": "",
    "description": "",
    "spec": [
        {
            "question_name": "Instance Designator",
            "question_description": "Instance Name",
            "required": true,
            "type": "multiplechoice",
            "variable": "DB_NAME",
            "min": 0,
            "max": 1024,
            "default": "",
            "choices": "FID1\nFID2\nFID3\nFID4\nFID5\nFID6",
            "new_question": false
        }
    ]
}
```

**Comment by ManuelPerrot** [comment] 2021-06-02 13:20
I have the same issue on 17.1.0
I haven't checked newer awx versions yet.

**Closed as completed** 2021-06-18 16:07 UTC
Labels: type:bug, component:ui
