### ISSUE TITLE
worker-json 404 and various warnings on job settings page

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#10192] opened 2021-05-13 15:26 UTC
(from @tiagodread, which we found while addressing what ended up being an unrelated issue with saves)

> 
> When the edit page is loaded for Job settings, there are some errors:
> 
> Warning: Failed prop type: Invalid prop `groupTitle` of type `object` supplied to `NavExpandableGroup`, expected `string`.
> 
> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of FindRefWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
> 
> Warning: Failed prop type: The prop `config` is marked as required in `BooleanField`, but its value is `undefined`.
> 
> Warning: Failed prop type: The prop `config` is marked as required in `InputField`, but its value is `undefined`.

Also, when loading the page there's a `worker-json` 404 error that we need to remove. see: https://github.com/ansible/awx/issues/10123#issuecomment-836303358

**Comment by AlexSCorey** [comment] 2021-06-04 15:05
This seems to be addressed by https://github.com/ansible/awx/pull/10171.  Putting it in needs test for confirmation

**Comment by tiagodread** [comment] 2021-06-04 22:29
@AlexSCorey this is not fixed and is still happening across settings details/edit forms

https://user-images.githubusercontent.com/12464858/120868783-2a7deb80-c56b-11eb-85c2-c1c91466106c.mp4

**Comment by AlexSCorey** [comment] 2021-06-09 19:30
I did some digging today into this issue and want to report what I have found so far.

It seems that this issue is related to newly implemented Ace code editor library we are using for our extra-var and variables fields.  In product it seems that, for some reason, the `worker-json.js` file, used by Ace Editor cannot be found.  After doing some digging I came across this [issue/comment](https://github.com/securingsincity/react-ace/issues/725#issuecomment-543109155) that led me to believe that we needed to import `import "ace-builds/webpack-resolver";`. Importing that did solve the problem but it also changed the warning in the console such that the file that is missing seems to be a minified version of the `worker-json.js` file.  I say that because the name of the file is `66699a304f413009231f0473c47d4bc0.js` which I believe is created during the build.  

I also saw some thing that led me to believe that something (maybe webpack) could not find the file in question because it was not where it expected it to be. So I tried adding `"home": "."` to our package.json file as suggested [here](https://github.com/securingsincity/react-ace-create-react-app-example#building-for-relative-paths) but that did not seem to have an affect.

My gut tells me that the `worker-json.js` file does exist in a production build, but that it is just not in the place that it's expected to be. 
@jakemcdermott

**Comment by AlexSCorey** [comment] 2021-06-14 12:22
This could be related also https://github.com/ansible/awx/issues/10435

**Comment by kialam** [comment] 2021-07-07 15:26
This seems related to https://github.com/securingsincity/react-ace/issues/275. See my comments [here](https://github.com/securingsincity/react-ace/issues/275#issuecomment-875698952).

**Comment by kialam** [comment] 2021-07-12 18:15
After days of investigating this issue I've distilled down the following information:

This bug also exists in Notifications when selecting webhooks notification type (it uses the same CodeDetail component).

The `mode` prop set as `javascript` causes Ace Editor to load worker-json.js. Other mode props (`yaml, text, etc`) do not.

Setting `useWorker: false` does not appear to do anything to disable the worker file from loading.

``` js
<CodeEditor
    mode={javascript}
    value={value}
    readOnly
    rows={rows}
    css="margin-top: 10px"
 />
```

`CodeEditor` components in Template Detail/Edit does not give this error - this is because the default `mode` is set to `yaml`.

### The main issue at hand is that the Ace Editor library is attempting to load a JS file that does not exist in a production build with hashed files. 

### Attempted solutions:

- [ ]  importing "react-ace-builds/webpack-resolver-min" as a "plug and play" solution will not work because we use `react-scripts` which handles the bundling and compilation of our dev and production files (via Webpack).
- [ ] using an `onLoad` prop within `CodeEditor` to set `useWorker` to `false` also does not prevent Ace from loading a worker file.
```js
onLoad={(e) => {
      e.getSession().setUseWorker(false)
}}
``` 

- [ ] using a CDN as the source for `worker-json.js` file throws a security content error.
- [ ] import jsonWorkerUrl from 'ace-builds/src-noconflict/worker-json' gives warnings: `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`.

We could try to use `react-app-rewired` to override the existing Webpack config we have for the `ace-builds` directory and have it exist in a static directory so the the resource doesn't return a 404, however that seems like a poor fit for a problem that should be handled by the library itself.

**Comment by AlexSCorey** [comment] 2021-07-12 18:55
@kialam you've made great strides in understanding the problem and that's awesome.  When I was poking at this issue I was unable to find any negative impact on functionality or performance, aside from the error in the console. Did you find any negative impacts?  Do you think it's worth it to work up a POC for the react-app-rewired to see if that route makes sense for us?

**Comment by kialam** [comment] 2021-07-12 20:22
@AlexSCorey the only negative impact I see is that there is no javascript lint integration whereas other areas of the app have code linting in place - see the JSON to YAML conversion with lint in the Templates section of the app. However, we do expose any server side errors in those form fields so this is not as big of an impact. 

<img width="1591" alt="Screen Shot 2021-07-12 at 4 19 10 PM" src="https://user-images.githubusercontent.com/2293210/125350587-f4334900-e32c-11eb-9387-a10123d29862.png">


I don't think at this time it's worth doing a POC. There is even [a similar, existing issue](https://github.com/ajaxorg/ace/issues/4750) that's already been filed in the `ace-builds` repo. I would reach out to the maintainers and see if there is a recommended approach to solving this issue first.

Edit:[ I've reached out to the maintainers to ask for assistance.](https://github.com/ajaxorg/ace/issues/4750)

**Comment by kenichimilo** [comment] 2021-07-27 05:59
The issue is also present in the latest release.. Inventory sync or job run is just stuck in running with no apparent update..
awx:19.2.2 
e.e:0.5.0

**Comment by chris93111** [comment] 2022-05-07 17:39
same in 20.1

**Closed as completed** 2022-06-07 19:34 UTC
Labels: type:bug, component:ui
