### ISSUE TITLE
inventory "update on project change" causing error

### ISSUE THREAD

**Issue by marafa** [ansible/awx#1476] opened 2018-03-08 17:44 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

#/inventories/inventory/3/inventory_sources/edit/7?inventory_search=page_size:20;order_by:name

##### ENVIRONMENT
* AWX version: mar 8 18
* AWX install method: docker on linux
* Ansible version:  mar 8 18
* Operating System: rhel7.4
* Web Browser: firefox 52.6 esr

##### STEPS TO REPRODUCE

go to  INVENTORIES myfirst_inventory SOURCES INVENTORY SOURCES aka  #/inventories/inventory/3/inventory_sources/edit/7?inventory_search=page_size:20;order_by:name
to set up an inventory from project.
when selecting the last of the 4 radio buttons "update on project change" i get that error in a popup

##### EXPECTED RESULTS
just works

##### ACTUAL RESULTS

`data : [object Object] status : 400 headers : function (name){if(headersObj||(headersObj=parseHeaders(headers)),name){var value=headersObj[lowercase(name)];return void 0===value&&(value=null),value}return headersObj} config : [object Object] statusText : Bad Request xhrStatus : complete `

**Comment by awithrow9** [comment] 2018-03-16 19:54
Looks like a dupe of #1295

**Closed as completed by awithrow9** 2018-03-16 19:54 UTC
Labels: type:bug, component:ui

**Comment by abatista75** [comment] 2018-04-29 21:06
Same issue with Ansible 2.5.2 and latest version of AWX.
