### ISSUE TITLE
SAML Service Provider Metadata URL return error Error parsing metadata. xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by mickael1026** [ansible/awx#5971] opened 2020-02-18 13:26 UTC
##### ISSUE TYPE
 - SAML Service Provider Metadata URL return "Error parsing metadata. xmlParseEntityRef: no name, line 18, column 33 (<string>, line 18)"

##### SUMMARY
Do the SAML configuration, save it then try to reach the SAML Service Provider Metadata URL https://XXX/sso/metadata/saml/

Get an error Error parsing metadata. xmlParseEntityRef: no name, line 18, column 33 (<string>, line 18)

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method:  docker on linux
* Ansible version:  2.9.3
* Operating System: centos 7.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Do the SAML configuration, generate certificate/ key with openssl for the SP.
Try to reach https://XXX/sso/metadata/saml/

##### EXPECTED RESULTS

Show xml metadata file

##### ACTUAL RESULTS

Error parsing metadata. xmlParseEntityRef: no name, line 18, column 33 (<string>, line 18)

##### ADDITIONAL INFORMATION

docker logs from awx_web container :

10.236.241.160 - - [18/Feb/2020:13:13:40 +0000] "GET /sso/metadata/saml/ HTTP/1.1" 200 90 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36" "-"
2020-02-18 13:13:40,751 ERROR    awx.sso.views unable to generate SAML metadata
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/onelogin/saml2/metadata.py", line 252, in add_x509_key_descriptors
    root = OneLogin_Saml2_XML.to_etree(metadata)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/onelogin/saml2/xml_utils.py", line 68, in to_etree
    return OneLogin_Saml2_XML._parse_etree(compat.to_bytes(xml), forbid_dtd=True)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/defusedxml/lxml.py", line 145, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3236, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 18
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 18, column 33

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/sso/views.py", line 67, in get
    metadata, errors = saml_backend.generate_metadata_xml()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/social_core/backends/saml.py", line 246, in generate_metadata_xml
    metadata = saml_settings.get_sp_metadata()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/onelogin/saml2/settings.py", line 628, in get_sp_metadata
    metadata = OneLogin_Saml2_Metadata.add_x509_key_descriptors(metadata, cert, add_encryption)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/onelogin/saml2/metadata.py", line 254, in add_x509_key_descriptors
    raise Exception('Error parsing metadata. ' + str(e))
Exception: Error parsing metadata. xmlParseEntityRef: no name, line 18, column 33 (<string>, line 18)

**Comment by wenottingham** [comment] 2020-02-21 18:17
Can you attach your full SAML configuration? (Please leave out any secrets).

**Comment by mickael1026** [comment] 2020-02-24 06:37
[saml.txt](https://github.com/ansible/awx/files/4243336/saml.txt)

Here the saml config, I cut the x509cert parameter.

**Comment by jakemcdermott** [comment] 2020-02-28 18:33
Thanks for the info, moving this to needs_devel.

**Comment by mick1627** [comment] 2020-03-31 14:41
The issue is due to the character "&" used int the contact field for the givenName attribut.

CAn be closed

**Closed as completed** 2020-03-31 14:45 UTC
Labels: type:bug, component:api

**Comment by ryanpetrello** [comment] 2020-03-31 14:57
Thanks for following up, @mick1627!
