### ISSUE TITLE
"sync" type project updates mark their project as failed

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2835] opened 2018-11-29 15:43 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Pre-run project syncs are not supposed to ordinarily make changes to the project they use.

Thus, a failure in a project sync should not cause the project to be marked failed, just as how it does not update its last update link usually.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run a JT and sigkill the process while the project sync is running

##### EXPECTED RESULTS

Project not marked as failed

##### ACTUAL RESULTS

project marked as failed

**Comment by kdelee** [comment] 2018-12-03 19:56
Another reproducing scenario:

1) Create JT with necessary project, etc
2) Launch job
3) Wait until "running" (actually we have just entered the pre-run hook) but BEFORE job events actually coming in
4) Kill dispatcher or rabbit
5) Wait 60 seconds
6) Bring services back up
7) Attempt to launch new job from JT
8) See that you get failure message that revision is unkown because project got marked as failed when job was reaped

**Closed as completed** 2018-12-04 20:10 UTC
Labels: type:bug, component:api
