### ISSUE TITLE
awx 9.2.0 does not use ansible.cfg provided by source repository

### ISSUE THREAD

**Issue by Elyytscha** [ansible/awx#6045] opened 2020-02-24 18:52 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
hangs permanently @ fetch galaxy roles from requierements.yml (with 9.0.2 it worked)

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker-compose
* Ansible version:  2.9+
* Operating System: Ubuntu 18.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

use requierements.yml with tower version 9.2.0
to see it failing
use requierements.yml with tower version 9.0.1
to see it working
##### ACTUAL RESULTS

awx 9.2.0 (canceld it manually after some waiting):
<a href="http://epvpimg.com/V1R1fab"><img src="http://i.epvpimg.com/V1R1fab.png" alt="" title="Hosted by epvpimg.com" /></a>

awx 9.0.1 (working):

<a href="http://epvpimg.com/oTkFeab"><img src="http://i.epvpimg.com/oTkFeab.png" alt="" title="Hosted by epvpimg.com" /></a>
##### ADDITIONAL INFORMATION

we use following ansible.cfg it seems in 9.0.1 this parameters where used, in 9.2.0 not:

```
...
[ssh_connection]
ssh_args = -C -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
#scp_if_ssh=yes
pipelining=True
...
```
in the working version (9.0.1) there i see at the start of project update: 
"Using /etc/ansible/ansible.cfg as config file"

in the failing version (9.2.0) there i dont see at the start of project update: 
"Using /etc/ansible/ansible.cfg as config file" <-- its missing

failing project_update_147.txt (9.2.0):

<a href="http://epvpimg.com/V1R1fab"><img src="http://i.epvpimg.com/V1R1fab.png" alt="" title="Hosted by epvpimg.com" /></a>

working project_update_147.txt (9.0.1):

```
Identity added: /tmp/awx_147_8x_k2q1m/artifacts/147/ssh_key_data (/tmp/awx_147_8x_k2q1m/artifacts/147/ssh_key_data)
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [update project using git] ************************************************
ok: [localhost, -> localhost] => {"after": "46973dd714abf1ab0a6704ac8e6b22f8151ea7d5", "before": "46973dd714abf1ab0a6704ac8e6b22f8151ea7d5", "changed": false, "remote_url_changed": false}

TASK [Set the git repository version] ******************************************
ok: [localhost, -> localhost] => {"ansible_facts": {"scm_version": "46973dd714abf1ab0a6704ac8e6b22f8151ea7d5"}, "changed": false}

TASK [update project using hg] *************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Set the hg repository version] *******************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [parse hg version string properly] ****************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [update project using svn] ************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Set the svn repository version] ******************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [parse subversion version string properly] ********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Ensure the project directory is present] *********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Fetch Insights Playbook(s)] **********************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Save Insights Version] ***************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Repository Version] ******************************************************
ok: [localhost,] => {
    "msg": "Repository Version 46973dd714abf1ab0a6704ac8e6b22f8151ea7d5"
}

PLAY [all] *********************************************************************

TASK [detect requirements.yml] *************************************************
ok: [localhost, -> localhost] => {"changed": false, "stat": {"atime": 1582569541.547898, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 0, "charset": "unknown", "ctime": 1582569541.5438972, "dev": 149, "device_type": 0, "executable": false, "exists": true, "gid": 0, "gr_name": "root", "inode": 12352972, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": true, "isreg": false, "issock": false, "isuid": false, "lnk_source": "/var/lib/awx/projects/_9__ans_artifactory/roles/requirements.yaml", "lnk_target": "requirements.yaml", "mimetype": "unknown", "mode": "0777", "mtime": 1582569541.5438972, "nlink": 1, "path": "/var/lib/awx/projects/_9__ans_artifactory/roles/requirements.yml", "pw_name": "root", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 17, "uid": 0, "version": null, "wgrp": true, "woth": true, "writeable": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}

TASK [fetch galaxy roles from requirements.yml] ********************************
The authenticity of host 'bitbucket.example.com (10.10.206.103)' can't be established.
RSA key fingerprint is SHA256:Oc3f7WVwBm2oo0etKmv2KypSPe/PedFLDP5Gevle9+Y.
Are you sure you want to continue connecting (yes/no)? 
The authenticity of host 'bitbucket.example.com (10.10.206.103)' can't be established.
RSA key fingerprint is SHA256:Oc3f7WVwBm2oo0etKmv2KypSPe/PedFLDP5Gevle9+Y.
Are you sure you want to continue connecting (yes/no)? 
changed: [localhost, -> localhost] => {"changed": true, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/tmp/awx_145_225oubaj/requirements_roles", "-v"], "delta": "0:00:00.918886", "end": "2020-02-24 18:45:27.626085", "rc": 0, "start": "2020-02-24 18:45:26.707199", "stderr": "", "stderr_lines": [], "stdout": "Using /etc/ansible/ansible.cfg as config file\\n- extracting oeamtc.docker to /tmp/awx_145_225oubaj/requirements_roles/oeamtc.docker\\n- oeamtc.docker (master) was installed successfully\\n- extracting oeamtc.filer to /tmp/awx_145_225oubaj/requirements_roles/oeamtc.filer\\n- oeamtc.filer (master) was installed successfully", "stdout_lines": ["Using /etc/ansible/ansible.cfg as config file", "- extracting oeamtc.docker to /tmp/awx_145_225oubaj/requirements_roles/oeamtc.docker", "- oeamtc.docker (master) was installed successfully", "- extracting oeamtc.filer to /tmp/awx_145_225oubaj/requirements_roles/oeamtc.filer", "- oeamtc.filer (master) was installed successfully"]}

TASK [detect collections/requirements.yml] *************************************
ok: [localhost, -> localhost] => {"changed": false, "stat": {"exists": false}}

TASK [fetch galaxy collections from collections/requirements.yml] **************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}

PLAY RECAP *********************************************************************
localhost,                 : ok=6    changed=1    unreachable=0    failed=0    skipped=11   rescued=0    ignored=0   

```

**Comment by wenottingham** [comment] 2020-02-26 17:57
@AlanCoding is this the path override issue with in-project ansible.cfg?

**Comment by AlanCoding** [comment] 2020-02-26 18:14
Here's the first theory that came to my mind:

https://github.com/ansible/awx/blob/35d36a71c761687ee8cf2f965393d830503c8eaa/awx/playbooks/project_update.yml#L159-L161

We install `requirements.yml` from the folder `{{project_path}}/collections`. A really simple fix presents itself that we instead install `collections/requirements.yml` from `{{project_path}}`. That should pick up the `ansible.cfg`, whereas it does not now.

If this theory is correct, then separate issue.

**Comment by ilijamt** [comment] 2020-03-10 20:30
I ran into the same issue fixed it according to this here
https://github.com/ansible/awx/issues/5947

**Comment by blomquisg** [comment] 2020-04-03 16:19
@chrismeyersfsu is this a dup of https://github.com/ansible/awx/issues/5947

**Comment by ryanpetrello** [comment] 2020-04-03 17:37
This *does* look like a dupe of https://github.com/ansible/awx/issues/5947 to me, or at least like it would be resolved by the change we recently made; anybody here want to give this (merged) PR/patch a whirl?

https://github.com/ansible/awx/pull/6488/commits/140dbbaa7db5882d0a66f7f871c1f48ce2415767

**Comment by Elyytscha** [comment] 2020-04-05 10:20
@ryanpetrello , i think that this pr is a workaround which will fix indeed the problem with the hangup on the ssh connection

if the ansible.cfg would by loaded correctly this could not be hardcoded and could be configured dynamically via something like this, provided by the source repo and controlled by git:
ansible.cfg:
```
...
[ssh_connection]
ssh_args = -C -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
pipelining=True
...
```

BUT in my opinion there is still another bug (feature?), if i define provisioning callbacks or ssh speedup or something else in my ansible.cfg which is located in the root folder in my source repo, i want that this ansible.cfg is loaded and used and not bypassed .. (also for requierements.y*ml)

i think @AlanCoding is 100% right with his comment

**Comment by AlanCoding** [comment] 2020-04-07 15:28
This question came up in a conversation I had with @gamuniz recently: should users have control of the Ansible configuration when running project updates? Using the top-level project `ansible.cfg` means that the same configuration would be applied to project updates as job runs, which could be a problem in some cases.

It's impossible to apply the configuration settings to the git clone (you can't apply a config before you have downloaded said config). So this discussion is limited to the 2nd half of the project update playbook where roles are downloaded.

The issue of #5426 still exists, which currently leaves AWX pretty much borked for users wanting to use both roles and Automation Hub, which is basically all users trying to use Automation Hub. Allowing user configurations there could allow workarounds for any issue like that, but it could also make it harder to track down behavior.

**Comment by elyezer** [comment] 2020-06-09 16:35
I was not able to reproduce it after https://github.com/ansible/awx/commit/41014e62b7d6c3d59f692a3ff18bf7b2a7e83ff3 got merged. So we can consider this as being verified.

**Closed as completed** 2020-06-09 16:44 UTC
Labels: type:bug, component:api
