### ISSUE TITLE
authorization-code application acts like implicit type and returns 405 for token call

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3371] opened 2019-03-06 16:17 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
I want to use OAuth2 for launching jobs from the API. The documentation I'm following:
https://github.com/ansible/awx/blob/devel/docs/auth/oauth.md
https://github.com/ansible/awx/blob/devel/awx/api/templates/api/api_o_auth_authorization_root_view.md
I have 2 issues with this:

I created an application in ansible of authorization-code type. 
I send the /api/o/authorize call and I get back the code, but only if I am logged in and if I have an active session, I get this page where I need to authorize. I don't want to be logged in as an user to be able to use the API, but use the client-id and client-secret my application has to be authorized and get a token. This is the first issue. If I don't have an active session I get a message to call /api/login first. This seems more like the Implicit grant type of application.

The second issue is that after I click authorize on the above mentioned page, and I do a post call to the /api/o/token endpoint as per the documentation, i get a 405 Method not supported. Tried GET, it also throws 405.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: kubernetes
* Ansible version:  2.7.7
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create an application in AWX with authorization-code type
2. Make a call to /o/authorize.
3. Here you get a message to call /api/login if there is no active session or if there is, you get redirected to a page that asks you to authorize the call.
4. Call /api/o/token and get a 405.

##### EXPECTED RESULTS

Step number 3 should not occur. 
Step number 4 should return the access token.

##### ACTUAL RESULTS

Step 3 occurs.
Step 4 returns 405.

**Comment by AdrianDutu** [comment] 2019-03-13 09:32
Any feedback on this, please?

**Comment by ryanpetrello** [comment] 2019-03-26 01:52
cc @matburt @rooftopcellist

**Comment by rooftopcellist** [comment] 2019-03-26 03:51
Hi @AdrianDutu, it sounds like you really should be using an application with the `password` grant_type if you don't want to have a user logged in.  

If you need to to use the authorization_code flow, but do not want to have to Authorize the token with a user logged in to tower, can set skip_authorization=False on that application. 


Can you give me more information about your use case and your HTTP call to the `/api/o/token` endpoint?  It sounds you may need to specify `-H "Content-Type: application/x-www-form-urlencoded"`

**Comment by rooftopcellist** [comment] 2019-04-02 03:55
Closing this.  Let me know here if you still have an issue and we can re-open this.

**Closed as completed by rooftopcellist** 2019-04-02 03:55 UTC
Labels: type:bug, component:api

**Comment by AdrianDutu** [comment] 2019-04-02 17:16
Hi @rooftopcellist 

Sorry, was on holiday. My use case is that I have different 3rd party clients (java, scripts etc) that need to trigger jobs in AWX. I do not want these to be linked to any user in AWX since the users all come from LDAP and are actual people that have access to AWX through some specific groups.  I want to use the client id and client secret of the application I define in AWX for authorization for these 3rd party clients.

**Comment by rooftopcellist** [comment] 2019-04-02 21:03
@AdrianDutu It sounds like you are looking for client_credentials grant_type, which allows tokens to be created without linking them to a user.  This is not compatible with the permissions system in AWX today as those role based access control is centered around the user.  Because of this, we aren't currently planning to add the client_credentials grant type.  

I would suggest making an AWX user in the UI or API (rather than through LDAP), then making an application and tokens associated to that user.  To use the client_id and client_secret of the application to authorize and issue tokens, you can POST to the `api/o/authorize` and `api/o/token` endpoints respectively.

**Comment by mrudat** [comment] 2024-05-10 08:47
I think there remains a documentation bug; the documentation in 4.5.0 still suggests that you _might_ be use the authorizaton-code grant type for a non-interactive application, for example a CI run that refreshes a project on commit.

It was surprising to find that I was following the instructions perfectly, but it still _insisted_ on authenticating as a user.

It would be helpful if the documentation could be updated to make it clear that you would need an application account to authenticate with to make things work.

It might save the next person from spending time attempting to do something that is, _by design_, impossible.
