### ISSUE TITLE
[ui_next] Team permissions are not shown on inventory access page. Only User

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8830] opened 2020-12-10 18:52 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Team permissions are not shown on inventory access page. Only Users.

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Add team roles to an inventory
2. Open inventory / access tab from step 1
Note: missing team role

**Comment by mabashian** [comment] 2021-02-03 14:46
<img width="1454" alt="Screen Shot 2021-02-03 at 9 45 25 AM" src="https://user-images.githubusercontent.com/9889020/106763166-91fb4d00-6604-11eb-979f-08d65c3dace8.png">

I created an inv, user, and team.
Added the user to the team
Gave the team admin permissions on the inv

Going to throw this back to needs_info.  Will need more info in order to recreate or can be closed if no longer able to reproduce.

**Comment by akus062381** [comment] 2021-03-01 16:25
Changing back to needs_devel- I just reproduced this bug.

**Comment by akus062381** [comment] 2021-03-01 16:36
Similar to https://github.com/ansible/awx/issues/8708

**Comment by akus062381** [comment] 2021-03-02 15:35
Also- when testing, make sure you verify that the team names will be visible on the access tab next to associated user name

**Comment by mabashian** [comment] 2021-03-08 14:31
@akus062381 you reproduced this using the exact same steps originally outlined?

Did your team have any users in it?  If it does not then no rows will appear because this list shows **users** who have a role on this particular resource.  If that role comes via a team then that should be denoted but without a user it will appear as if the team role is not listed.

If your team did have a user in it, did the user have any other roles assigned to it?

I think (if this is a bug) that we need exact reproduction steps in order to fix it.

**Comment by mabashian** [comment] 2021-04-23 13:59
@tiagodread @one-t @akus062381 I'm still unable to reproduce this bug.  Here's latest devel:

<img width="1497" alt="Screen Shot 2021-04-23 at 9 58 41 AM" src="https://user-images.githubusercontent.com/9889020/115882164-8147bf80-a41a-11eb-9187-454ca06ab3a2.png">

I created a team with one user (foo) and gave that team the admin role on the inventory in question.

**Comment by akus062381** [comment] 2021-05-05 15:45
this is fixed.

**Closed as completed by akus062381** 2021-05-05 15:45 UTC
Labels: type:bug, component:ui
