### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by Lobout** [ansible/awx#7289] opened 2020-06-08 17:57 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
11.2 fresh install fails

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method:  docker on linux
* Ansible version:  ansible 2.9.9
* Operating System: Redhat Linux 8
* Web Browser:

##### STEPS TO REPRODUCE

run:  ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

successful install

##### ACTUAL RESULTS

ok: [localhost]

TASK [local_docker : Start the containers] **********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"b\"pull access denied for ansible/awx, repository does not exist or may require 'docker login'\"\")"}

PLAY RECAP **************************

**Comment by ryanpetrello** [comment] 2020-06-08 18:01
dupe of https://github.com/ansible/awx/issues/7246

**Closed as completed by ryanpetrello** 2020-06-08 18:01 UTC
