### ISSUE TITLE
Job output not displayed while running - AWX 17.0.0

### ISSUE THREAD

**Issue by dossjjx** [ansible/awx#9183] opened 2021-01-28 06:42 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.16
* Operating System: ubuntu server 20.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run any Job Template and navigate to Job Output screen.

##### EXPECTED RESULTS

View Ansible job output in real time while job is running. 

##### ACTUAL RESULTS

Job output window does not show any job output while job is running. Once job completes (succeeds or fails), all job output is displayed.

##### ADDITIONAL INFORMATION

Recently upgrade AWX version 9.3.0 to latest 17.0.0. No issues prior to upgrade.

**Comment by dossjjx** [comment] 2021-01-28 06:44
Below is console output from the developer tools in Chrome and the useWebsocket.js file that seems to error out. Same issue occurring on Firefox as well. AWX 17.0

![image](https://user-images.githubusercontent.com/35515947/106100367-dc129900-6101-11eb-9961-ea1fd565e905.png)

![image](https://user-images.githubusercontent.com/35515947/106100400-e7fe5b00-6101-11eb-937b-9277bb87f809.png)

**Comment by nicosalvadore** [comment] 2021-01-28 09:20
Hello,
I reported the same issue on the mailing list :
https://groups.google.com/g/awx-project/c/BqLZzkzUKmo/m/UUmkCsPMCAAJ

I have this issue on v16.0.0, I haven't upgraded to 17.0.0 or 17.0.1 yet.

**Comment by Speedy1985** [comment] 2021-01-28 13:18
Yes same issue here after upgrading from AWX 10.0.0 to 17.0.1.

**Comment by jakemcdermott** [comment] 2021-01-28 18:07
:wave: hello @dossjj  . 

Thanks for creating this issue.

The job output update bug you described is caused by a combination of https://github.com/ansible/awx/issues/8596 and possibly https://github.com/ansible/awx/issues/9085.

We'll have a fix for these bugs in one of the upcoming awx releases.

I'm closing this issue for now - we're tracking the work for this in the issues linked above. 

also see: 
  - https://github.com/ansible/awx/issues/8930
  - https://github.com/ansible/awx/issues/8973
  - https://github.com/ansible/awx/issues/9105
  - https://github.com/ansible/awx/issues/9112

**Closed as completed by jakemcdermott** 2021-01-28 18:07 UTC
Labels: type:bug, component:ui
