### ISSUE TITLE
AWX 12.0.0 vmware inventory failure

### ISSUE THREAD

**Issue by Lobout** [ansible/awx#7368] opened 2020-06-17 16:05 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
unable to get awx to pull vmware inventory

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: Redhat Linux 7.8
* Web Browser:

##### STEPS TO REPRODUCE

Set up inventory with vcenter credentials
run inventory

##### EXPECTED RESULTS

obtain inventory of vmware systems

##### ACTUAL RESULTS

    2.025 INFO     Updating inventory 3: Vcenter4
    2.472 INFO     Reading Ansible inventory source: /tmp/awx_4_furbkc9p/vmware_vm_inventory.yml
    2.474 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.474 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.474 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1141, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1031, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]:  * Failed to parse /tmp/awx_4_furbkc9p/vmware_vm_inventory.yml with
auto plugin: Invalid empty host name provided: None
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/var/lib/awx/vendor/awx_ansible_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 606, in parse
    cacheable_results = self._populate_from_source()
  File "/var/lib/awx/vendor/awx_ansible_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 689, in _populate_from_source
    self._populate_host_properties(host_properties, host)
  File "/var/lib/awx/vendor/awx_ansible_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 720, in _populate_host_properties
    self.inventory.add_host(host)
  File "/usr/lib/python3.6/site-packages/ansible/inventory/data.py", line 230, in add_host
    raise AnsibleError("Invalid empty host name provided: %s" % host)
[WARNING]: Unable to parse /tmp/awx_4_furbkc9p/vmware_vm_inventory.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by AlanCoding** [comment] 2020-06-19 16:58
Closing as duplicate of #7052

**Closed as completed by AlanCoding** 2020-06-19 16:58 UTC
Labels: type:bug, component:api
