### ISSUE TITLE
HTML displayed when viewing details

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#9070] opened 2021-01-12 20:02 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

I attempted to load the project screen while AWX was reload and got an error message with a details section. When I expanded the detail I got the HTTML response for the 502 instead of a just the body of the 502:
![image](https://user-images.githubusercontent.com/32551173/104366241-0f8cdb00-54e7-11eb-80b7-faa1063e8fbf.png)

Not sure if this is as designed or if the HTML should have been rendered in the details area.

**Comment by mabashian** [comment] 2021-02-04 16:40
Duplicate of https://github.com/ansible/awx/issues/6707.  Under the hood these scenarios are the same and when we fix it it should satisfy both scenarios.

**Closed as completed by mabashian** 2021-02-04 16:40 UTC
Labels: type:bug, component:ui
