### ISSUE TITLE
ansible awx redis permission issue 

### ISSUE THREAD

**Issue by mo-saeed** [ansible/awx#9429] opened 2021-03-01 13:36 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx-redis produces this error in our kubernetes cluster:
```
Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Permission denied
```
and this causes awx-task error
```
MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```
The issue is related to wrong configuration [here](https://github.com/ansible/awx/blob/15.0.1/installer/roles/kubernetes/defaults/main.yml#L33) the user with `1001` id doesn't exist, the actual redis user is with id `999`

here's /etc/passwd from the pod:
```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
redis:x:999:999::/home/redis:/bin/sh
```
##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: kubernetes
* Ansible version:   2.9.14
* Operating System: Linux
* Web Browser: Chrome
* Kubernetes versio: 1.19.6

##### STEPS TO REPRODUCE

Install ansible awx 15.0.1 with the default wrong kubernets security context  `RunAsUser`

##### EXPECTED RESULTS

Redis run without errors
##### ACTUAL RESULTS

Redis throws this error
```
Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Permission denied
```
##### ADDITIONAL INFORMATION
It's easy to have fix by changing [this](https://github.com/ansible/awx/blob/15.0.1/installer/roles/kubernetes/defaults/main.yml#L33) from 1001 to 999

**Comment by rguhr** [comment] 2021-03-01 17:53
Same issue: https://github.com/ansible/awx/issues/9401

**Comment by ryanpetrello** [comment] 2021-03-01 17:56
Duplicate of https://github.com/ansible/awx/issues/9401

**Closed as completed by ryanpetrello** 2021-03-01 17:56 UTC
Labels: type:bug

**Comment by mo-saeed** [comment] 2021-03-01 18:26
Are you sure it’s the same issue? my issue fixed when I Changed the default Value of runAsUser to 999 coz 1001 is the wrong user ID

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
