### ISSUE TITLE
Custom Dynamic Inventories scripts are duplicated when run

### ISSUE THREAD

**Issue by mohclips** [ansible/awx#271] opened 2017-09-24 20:40 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I noticed that the custom inventory scripts are saved twice to the /tmp folder inside the same file - obviously this breaks the dynamic inventories base on them.

The examples below are only test scripts to show the duplication - they do not build a dynamic inventory.  

##### ENVIRONMENT
* AWX version: 1.0.0.358

##### EXPECTED RESULTS

- create a custom inventory script.
- attach this as a source for an inventory
- run source sync
- check temp file created on task container

Scripts should only be saved once

```
[root@awx tmp]# cat awx_*/tmp*
#!/bin/bash

echo "This is a test script"

sleep 30
```

##### ACTUAL RESULTS

Custom inventory script is saved twice to the same file.

```
[root@awx tmp]# cat awx_*/tmp*
#!/bin/bash

echo "This is a test script"

sleep 30#!/bin/bash

echo "This is a test script"

sleep 30[root@awx tmp]# 

```

**Comment by jangsutsr** [comment] 2017-10-06 20:49
@mohclips By replicating the issue, I do see duplicate in inventory script contents, but it was 2 temporary files containing the same inventory script contents, not the same inventory script saved 2 times into *the same file*.

I think some specific `cat` usages might be the key to this issue:
```
[root@awx ~]# cat pre_a
haha
[root@awx ~]# cat pre_b
hehe
[root@awx ~]# cat pre_*
haha
hehe
```
It means if you try `cat` multiple files using wildcard, the result would be the concatenation of the contents of target files.

I still need to dig out why there are 2 copies of the same inventory script during inventory updates, but most likely it's an intended redundancy. Given we are not writing to the same temp file more than once and all temp files are cleared after inventory update finishes, I think we are good here.

**Comment by mohclips** [comment] 2017-10-07 16:19
@jangsutsr  I'll check this out and report back.  thanks.

**Comment by mohclips** [comment] 2017-10-07 20:40
I can confirm i have duplicated folder contents.

Test script (not written as an dynamic inventory)
```
#!/bin/bash
uname -a
sleep 3600
```

Check for interesting folders
```
[root@awx tmp]# ls awx_*
awx_8_C5CJ6s:

awx_inventory_5CyMHz:
tmp2LAz6M

awx_inventory_BUYNVK:
tmpKVXbgB
```

The awx_inventory_* files contain:
```
[root@awx tmp]# grep -ri "sleep 3600" awx_*
awx_inventory_5CyMHz/tmp2LAz6M:sleep 3600
awx_inventory_BUYNVK/tmpKVXbgB:sleep 3600

```

**Comment by jangsutsr** [comment] 2017-10-09 14:09
@mohclips Thanks for the reproduction! So it is confirmed that we somehow have a redundant temporary dynamic inventory script. I can find no signs of adding more than one temporary script in the code base, but `proot` may probably be the cause. It is good to know that we don't really screw up by concatenating the same content twice into the same temp file.

Considering there are no obvious drawback of having redundant temporary files, and all temporary files are deleted after job run. We will close this issue for now but keep the fact of redundant temp files in mind.

We've never noticed this redundancy before, thanks again for the good catch!

**Closed as completed by jangsutsr** 2017-10-09 14:09 UTC
Labels: type:bug, component:api
