### ISSUE TITLE
Custom credential env variable not propagated to module(s) environment, only available with lookup.

### ISSUE THREAD

**Issue by planeturban** [ansible/awx#13577] opened 2023-02-15 15:32 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Running `shell` module I can't seem to pick up an environment variable defined in a custom credential. It's possible using `lookup`, both on localhost and remote hosts. It really can't be (AFAIK) tested in Ansible alone, since custom credentials aren't a thing there.  Looking at `/api/v2/jobs/<job run>/` $I is set in `job_env`, but looking at the output (`Task: Shell - env` below) it's not in stdout when using `shell: "echo {{ item }}"`. 

### AWX version

21.10.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

awx-ee:21.12.0

### Operating system

linux

### Steps to reproduce

Create custom credential and accompanying credential.

```json
{
    "id": 28,
    "type": "credential_type",
    "url": "[/api/v2/credential_types/28/](http://10.0.100.10/api/v2/credential_types/28/)",
    "related": {
        "named_url": "[/api/v2/credential_types/I+cloud/](http://10.0.100.10/api/v2/credential_types/I+cloud/)",
        "created_by": "[/api/v2/users/1/](http://10.0.100.10/api/v2/users/1/)",
        "modified_by": "[/api/v2/users/1/](http://10.0.100.10/api/v2/users/1/)",
        "credentials": "[/api/v2/credential_types/28/credentials/](http://10.0.100.10/api/v2/credential_types/28/credentials/)",
        "activity_stream": "[/api/v2/credential_types/28/activity_stream/](http://10.0.100.10/api/v2/credential_types/28/activity_stream/)"
    },
    "summary_fields": {
        "created_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "modified_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "user_capabilities": {
            "edit": true,
            "delete": true
        }
    },
    "created": "2023-02-15T14:30:46.165335Z",
    "modified": "2023-02-15T14:30:46.165357Z",
    "name": "I",
    "description": "",
    "kind": "cloud",
    "namespace": null,
    "managed": false,
    "inputs": {
        "fields": [
            {
                "id": "i",
                "type": "string",
                "label": "Grjs2"
            }
        ]
    },
    "injectors": {
        "env": {
            "I": "{{ i }}"
        }
    }
}
```

Run template playbook with custom credential:

```yaml
- hosts: all
  gather_facts: no
  tasks:
    - name: Check local
      delegate_to: localhost
      debug:
        msg: "{{ lookup('env', item) }}"
      with_items:
        - I
        - UID

    - name: Check remote
      debug:
        msg: "{{ lookup('env', item) }}"
      with_items:
        - I
        - UID

    - name: Shell - lookup
      shell: "echo {{ lookup('env', item) }}"
      with_items:
        - I
        - UID

    - name: Shell - env 
      shell: "echo ${{ item }}"
      with_items:
        - I
        - UID
```

### Expected results

Task `Shell - env` should return whatever $I is set to.

### Actual results

Task: `Shell - env` does not print $I

### Additional information

job_env:
```json
"job_env": {
        "KUBERNETES_SERVICE_PORT_HTTPS": "443",
        "KUBERNETES_SERVICE_PORT": "443",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_HOST": "10.43.97.242",
        "HOSTNAME": "automation-job-44-bczqt",
        "AWX_SERVICE_PORT_80_TCP": "tcp://10.43.215.58:80",
        "PWD": "/runner",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_PORT": "8443",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_PROTO": "tcp",
        "AWX_SERVICE_SERVICE_PORT": "80",
        "HOME": "/home/runner",
        "KUBERNETES_PORT_443_TCP": "tcp://10.43.0.1:443",
        "AWX_SERVICE_PORT_80_TCP_ADDR": "10.43.215.58",
        "AWX_SERVICE_PORT": "tcp://10.43.215.58:80",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT": "tcp://10.43.97.242:8443",
        "AWX_SERVICE_PORT_80_TCP_PORT": "80",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_PORT_HTTPS": "8443",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_PORT": "8443",
        "SHLVL": "0",
        "KUBERNETES_PORT_443_TCP_PROTO": "tcp",
        "KUBERNETES_PORT_443_TCP_ADDR": "10.43.0.1",
        "AWX_SERVICE_SERVICE_HOST": "10.43.215.58",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP": "tcp://10.43.97.242:8443",
        "AWX_SERVICE_SERVICE_PORT_HTTP": "80",
        "KUBERNETES_SERVICE_HOST": "10.43.0.1",
        "KUBERNETES_PORT": "tcp://10.43.0.1:443",
        "KUBERNETES_PORT_443_TCP_PORT": "443",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "AWX_SERVICE_PORT_80_TCP_PROTO": "tcp",
        "AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_ADDR": "10.43.97.242",
        "LC_CTYPE": "C.UTF-8",
        "ANSIBLE_FORCE_COLOR": "True",
        "ANSIBLE_HOST_KEY_CHECKING": "False",
        "ANSIBLE_INVENTORY_UNPARSED_FAILED": "True",
        "ANSIBLE_PARAMIKO_RECORD_HOST_KEYS": "False",
        "AWX_PRIVATE_DATA_DIR": "/tmp/awx_44_fwubjtoz",
        "JOB_ID": "44",
        "INVENTORY_ID": "3",
        "PROJECT_REVISION": "9ac40446819e230c0c3a0dd4149c22620ee72ef2",
        "ANSIBLE_RETRY_FILES_ENABLED": "False",
        "MAX_EVENT_RES": "700000",
        "AWX_HOST": "https://towerhost/",
        "ANSIBLE_SSH_CONTROL_PATH_DIR": "/runner/cp",
        "ANSIBLE_COLLECTIONS_PATHS": "/runner/requirements_collections:~/.ansible/collections:/usr/share/ansible/collections",
        "ANSIBLE_ROLES_PATH": "/runner/requirements_roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles",
        "I": "hello",
        "ANSIBLE_CALLBACK_PLUGINS": "/usr/local/lib/python3.9/site-packages/ansible_runner/display_callback/callback",
        "ANSIBLE_STDOUT_CALLBACK": "awx_display",
        "AWX_ISOLATED_DATA_DIR": "/runner/artifacts/44",
        "RUNNER_OMIT_EVENTS": "False",
        "RUNNER_ONLY_FAILED_EVENTS": "False"
    },

```

output:
```
ansible-playbook [core 2.14.2]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.16 (main, Dec  8 2022, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
SSH password: 
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: envtest.yml **********************************************************
1 plays in playbooks/envtest.yml

PLAY [all] *********************************************************************

TASK [Check local] *************************************************************
task path: /runner/project/playbooks/envtest.yml:4
ok: [login -> localhost] => (item=I) => {
    "msg": "hello"
}
ok: [login -> localhost] => (item=UID) => {
    "msg": ""
}

TASK [Check remote] ************************************************************
task path: /runner/project/playbooks/envtest.yml:12
ok: [login] => (item=I) => {
    "msg": "hello"
}
ok: [login] => (item=UID) => {
    "msg": ""
}

TASK [Shell - lookup] **********************************************************
task path: /runner/project/playbooks/envtest.yml:19
changed: [login] => (item=I) => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "ansible_loop_var": "item", "changed": true, "cmd": "echo hello", "delta": "0:00:00.007458", "end": "2023-02-15 15:34:19.217124", "item": "I", "msg": "", "rc": 0, "start": "2023-02-15 15:34:19.209666", "stderr": "", "stderr_lines": [], "stdout": "hello", "stdout_lines": ["hello"]}
changed: [login] => (item=UID) => {"ansible_loop_var": "item", "changed": true, "cmd": "echo ", "delta": "0:00:00.007262", "end": "2023-02-15 15:34:19.731707", "item": "UID", "msg": "", "rc": 0, "start": "2023-02-15 15:34:19.724445", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [Shell - env] *************************************************************
task path: /runner/project/playbooks/envtest.yml:25
changed: [login] => (item=I) => {"ansible_loop_var": "item", "changed": true, "cmd": "echo $I", "delta": "0:00:00.005291", "end": "2023-02-15 15:34:20.262252", "item": "I", "msg": "", "rc": 0, "start": "2023-02-15 15:34:20.256961", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
changed: [login] => (item=UID) => {"ansible_loop_var": "item", "changed": true, "cmd": "echo $UID", "delta": "0:00:00.005571", "end": "2023-02-15 15:34:20.733372", "item": "UID", "msg": "", "rc": 0, "start": "2023-02-15 15:34:20.727801", "stderr": "", "stderr_lines": [], "stdout": "1028", "stdout_lines": ["1028"]}

PLAY RECAP *********************************************************************
login                      : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


```

**Comment by planeturban** [comment] 2023-02-15 15:40
Thinking about it, could this be `ansible-runner` problem?

**Comment by akus062381** [comment] 2023-02-15 16:16
Hi @planeturban,

Your question seems to be about using Ansible, not about AWX. https://groups.google.com/g/ansible-project is the best place to visit for user questions about Ansible. Thanks!

**Comment by planeturban** [comment] 2023-02-15 16:25
@akus062381 how come? It’s custom credentials from AWX that’s not propagated. Unless you’re pointing me towards ansible-runner? :)

**Comment by relrod** [comment] 2023-02-22 18:56
@planeturban 

When you use a custom credential that exposes an environment variable, that environment variable gets set on the system where `ansible-playbook` is run (i.e., in an execution environment, where `ansible-playbook` is ultimately called).

Those environment variables are accessible to `ansible-playbook` but they don't get propagated to remote nodes that ansible is managing with modules. This is by design and how ansible works.

You can test this outside of an AWX context:

```
[rick@fedora ~]$ export MYNAME=rick
[rick@fedora ~]$ ansible -i 192.168.122.205, -u root -k -m shell -a 'echo $MYNAME' all
SSH password: 
192.168.122.205 | CHANGED | rc=0 >>

[rick@fedora ~]$ 
```

If you need these variables on the target node, the correct thing to do is to use the lookup plugin, possibly in combination with `environment` on the task.

**Comment by relrod** [comment] 2023-02-22 19:01
I'm going to close this, because there's not a bug here :slightly_smiling_face: And @akus062381's advice to ask the `ansible-project` mailing list if you need more help still applies. There is also a vibrant Matrix community that might be of use: https://docs.ansible.com/ansible/latest/community/communication.html#ansible-community-on-matrix

**Closed as not planned by relrod** 2023-02-22 19:01 UTC
Labels: type:bug, needs_triage, community
