### ISSUE TITLE
Update error handling placeholders in rbac component

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6462] opened 2020-03-27 15:25 UTC
##### SUMMARY
If an error happens when adding roles, we should show the error. 

notes:
`AddResourceRole`

Modal-from-modal might be kind of weird, so I'm guessing the error should be shown somewhere _on_ the rbac modal after the save fails.

**Comment by mabashian** [comment] 2020-09-28 18:17
I'm gonna close this in favor of https://github.com/ansible/awx/issues/7520 since it's got a good reproducer

**Closed as completed by mabashian** 2020-09-28 18:17 UTC
Labels: type:feature
