### ISSUE TITLE
awx.main.tasks Encountered error on initial log configuration

### ISSUE THREAD

**Issue by twhiston** [ansible/awx#1178] opened 2018-02-09 12:36 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I'm having a lot of trouble getting jobs to run consistently. Often they will just hang forever, there doesn't seem to be a specific task that causes this, and it happens randomly, though the bigger the playbook the more likely it seems to happen. When checking the worker container logs I see the following

``` 
018-02-09 12:29:48,578 ERROR    awx.main.tasks Encountered error on initial log configuration.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 114, in task_set_logger_pre_run
    configure_external_logger(settings, is_startup=False)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 342, in configure_external_logger
    is_enabled = settings_module.LOG_AGGREGATOR_ENABLED
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 476, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 389, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 309, in _get_local
    self._preload_cache()
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 271, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed
```
This seems to put the task container in a state where it cannot run any more jobs, and needs to be restarted. However in the interface it seems to think the job is still running, but it just hangs forever

##### ENVIRONMENT
* AWX version: 1.0.2.372
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: RHEL

##### STEPS TO REPRODUCE

This is hard as it seems to happen in a random manner, step that worked before have this error on next run etc......

##### EXPECTED RESULTS

The job does not exit randomly, or if it does it at least does not leave the task container in a broken state which stops all future jobs from proceeding

**Comment by jaredevantabor** [comment] 2018-02-09 18:44
@twhiston I think we would need more detailed information about what specifically causes the error you're seeing to properly debug this issue you're seeing. It might be easier to get real-time assistance by pinging the IRC channel.

**Comment by twhiston** [comment] 2018-02-12 10:12
@jaredevantabor what time are you guys usually on there? (and timezone?) during European daytime it seems hard to get anyone.

**Comment by jaredevantabor** [comment] 2018-02-12 17:48
@twhiston The best time would probably be during the daytime of the EST time zone (US east coast).

**Comment by christoph-kluge** [comment] 2018-03-08 12:01
Hey guys :) I have the same error message but a little bit different stack-trace. 

**ENVIRONMENT**

- AWX version: 1.0.4.57
- AWX install method: docker-compose on linux
- Ansible version: 2.4.3.0
- Operating System: Debian Stretch

**Message** 

```
2018-03-08 11:55:12,617 ERROR    awx.main.tasks Encountered error on initial log configuration.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 117, in task_set_logger_pre_run
    configure_external_logger(settings, is_startup=False)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 357, in configure_external_logger
    is_enabled = settings_module.LOG_AGGREGATOR_ENABLED
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 476, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 389, in __getattr__
    value = self._get_local(name)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 66, in _log_database_error
    if get_tower_migration_version() < '310':
  File "/usr/lib/python2.7/site-packages/awx/main/utils/db.py", line 14, in get_tower_migration_version
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.load_disk()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 114, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/main/migrations/0003_squashed_v300_v303_updates.py", line 16, in <module>
    class Migration(migrations.Migration):
  File "/usr/lib/python2.7/site-packages/awx/main/migrations/0003_squashed_v300_v303_updates.py", line 25, in Migration
    (b'main', '0028_v300_org_team_cascade')] + _squashed.replaces(SQUASHED_30, applied=True)
  File "/usr/lib/python2.7/site-packages/awx/main/migrations/_squashed.py", line 46, in replaces
    squashed_keys, key_index = squash_data(squashed)
  File "/usr/lib/python2.7/site-packages/awx/main/migrations/_squashed.py", line 14, in squash_data
    cm = current_migration()
  File "/usr/lib/python2.7/site-packages/awx/main/migrations/_squashed.py", line 33, in current_migration
    return migration_qs.latest('id')
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 558, in latest
    return self._earliest_or_latest(field_name=field_name, direction="-")
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 552, in _earliest_or_latest
    return obj.get()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed
```

**Comment by christoph-kluge** [comment] 2018-03-08 20:08
Some notes to my previous comment which I found out during the day (because like this AWX is not usable for us): 

* I'm not really able to reproduce it on a specific task. But sometimes it happens directly after restarting the awx_task container when it picks up the first job and then the container fixes himself after some hundred revoked tasks...
* We're using a dedicated Amazon RDS Instance with a single EC2 instance running the docker-containers: awx_web, awx_task, rabbitmq, memcached
* RDS is idling all the time, nothing serious we do also use the "default" parameter and option group for 9.6
* Stopping/Starting of the awx_task container usually helps but not for long

If there is a way how I can support in real-time debugging (because I'm not a python expert) please let me know.

**Comment by matburt** [comment] 2018-03-09 01:46
What's the sizing of your single ec2 instance? what about the rds instance?

Usually we'll see this when there are issues staying connected to postgres. I'm not sure about your situation but sometimes it can manifest if there is a firewall between postgres and the AWX that closes idle connections.

You might can check the postgres logs themselves and see if there is an explanation for it and check to make sure there isn't a low idle timeout set in the database.

**Comment by christoph-kluge** [comment] 2018-03-09 01:55
Hi @matburt, thank you for the answer! 

It's a "t2.medium" (2 vCPUs, 4G RAM) instance and we're using a "db.t2.micro" (1 vCPU, 1G ram) for the RDS postgres database, also the CloudWatch-Logs are showing that the RDS instance is idling all the time. 

> You might can check the postgres logs themselves

RDS is not really logging anything except of wal_checkpoints.. besides that all looks good. 

> make sure there isn't a low idle timeout set in the database.

Do you know which setting it is? I've found a couple timeout settings but none which looks like the expected one (https://www.postgresql.org/docs/9.6/static/runtime-config-client.html).

**Comment by matburt** [comment] 2018-03-09 02:34
I will say that the awx system is right at the bottom of our minimum requirements and we've been seeing issues lately out of systems in this range.

The database is dramatically undersized it really wouldn't surprise me that any sort of non trivial activity might completely wipe out whatever cpu credits you would accrue unless you have crazy small/trivial workloads. Given that this is happening during job launches that's a pretty good indication of what's happening. If you've exhausted all of your credits on a t2.micro then you are going to be limited to 10% cpu utilization... that's not going to work well at all.

Bump the instance to a c4.large, m3.medium... something like that, see if it alleviates you problem.

**Comment by christoph-kluge** [comment] 2018-03-09 16:38
@matburt I have some more info for debugging purposes! I've updated the instances to

* ec2: m5.large (2 vCPUs, 8G ram)
* rds: db.m4.large (2 vCPUs, 8G ram)

but the error is still happening. After changing RDS logging to INFO (default: WARN) I found the following message:

> 2018-03-09 16:08:04 UTC:192.168.10.75(47022):root@awx:[12020]:LOG: SSL error: decryption failed or bad record mac
> 2018-03-09 16:08:04 UTC:192.168.10.75(47022):root@awx:[12020]:LOG: could not receive data from client: Connection reset by peer

After this error-message appears the task-container goes crazy and is not able to connect to the database anymore until I restart it.

**Comment by christoph-kluge** [comment] 2018-03-09 18:37
It seems that according to #709 it was enough for me to set the following `settings.py`. For me there was no need to update the SSL certificate. I will monitor this for some hours to see if the error occurs again and will let you guys know if this fixes the problem for us. 

```
DATABASES = {
    'default': {
        ...
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'sslmode': 'require',
            'keepalives_idle': 5,
            'keepalives_interval': 1,
            'keepalives_count': 5,
        },
    },
}
```

**Edit 1** 

The issue is still existing. It seems that the worker fixes himself now and continues to work. 

**Edit 2**

A quick and dirty - temporary - solution (at least for us) is to configure the container to use a non-ssl database connection. We're injecting a local settings.py through docker-compose volumes.

```
# ./docker-compose.yml
version: '2'
services:
  task:
    image: ansible/awx_task:1.0.4
    volumes:
      - ./settings.py:/etc/tower/settings.py

```


```
# ./settings.py
[..more config..]
DATABASES = {
    'default': {
        ...
        'OPTIONS': {
            'sslmode': 'disable',
        },
    },
}
[..more config..]
```

**Comment by wenottingham** [comment] 2018-06-01 18:05
Closing this, as I believe the original reporter's issue is fixed. @christoph-kluge - please let us know if it's still failing for you, and if the errors you see when using SSL lead to service errors, or if they're already handled by the reconnect logic.

**Comment by matburt** [comment] 2018-11-02 18:53
should have closed

**Closed as completed by matburt** 2018-11-02 18:53 UTC
Labels: type:bug, component:api
