### ISSUE TITLE
Stderr screen on job event host details modal displays http encoded characters

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#9062] opened 2021-01-12 14:38 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When you go to the job page and then click on a failed step you get the popup. On the popup screen you then click on the standard error page. In the details of the standard error there are html encoded entities such as:
    Cloning into &apos;/var/lib/awx/projects/_6__scm_project&apos;...

**Comment by jakemcdermott** [comment] 2021-01-19 18:07
:wave: Can you provide an example playbook and steps to reproduce, as well as a screenshot?

**Comment by john-westcott-iv** [comment] 2021-01-22 21:08
Below is from a failed project sync, you can see the &apos; entries on line 1.
![image](https://user-images.githubusercontent.com/32551173/105547040-12988000-5ccc-11eb-9120-c0fa82f53e49.png)

**Comment by zircon** [comment] 2022-07-19 10:24
Just to add another example, I've encountered the same thing with the Output tab in AWX 21.2.0. It can make the output a bit confusing to a non-technical person:
![awx-job-output](https://user-images.githubusercontent.com/453843/179707694-571f75dc-1ac8-4ad9-9bc6-dd6cdf81331f.png)

After digging into it a bit, this seems to be a consequence of `stdOut` being passed through `encode()` inside `processCodeEditorValue()`:
https://github.com/ansible/awx/blob/33e445f4f6e65e44b90c3988d22f19c14d734272/awx/ui/src/screens/Job/JobOutput/HostEventModal.js#L82 
https://github.com/ansible/awx/blob/33e445f4f6e65e44b90c3988d22f19c14d734272/awx/ui/src/screens/Job/JobOutput/HostEventModal.js#L37-L47

Interestingly, the issue mentioned by @john-westcott-iv appears to have been fixed by #12064 which removed the `processCodeEditorValue()` wrapping from `stdErr`:
https://github.com/ansible/awx/blob/33e445f4f6e65e44b90c3988d22f19c14d734272/awx/ui/src/screens/Job/JobOutput/HostEventModal.js#L81

Result:
![awx-stderr](https://user-images.githubusercontent.com/453843/179723732-2d22a12e-990d-4ef6-88cc-2b8803c149b0.png)

So, the question is: can the same be applied to `stdOut`, or is there a particular reason its run through `encode()`?

**Comment by relrod** [comment] 2022-09-28 21:36
I believe this is fixed by #12950.

**Closed as completed by relrod** 2022-09-28 21:36 UTC
Labels: type:bug, component:ui, flag:community
