### ISSUE TITLE
Task Manager Ideas

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#11306] opened 2021-11-03 19:29 UTC
This is to capture thoughts about the task manager over the years.

# Small - Optimization - Store Decision(s)

I think this was @fosterseth original idea.

The task manager decides to transition a job from `pending` to `waiting` when two conditions are met.

1. No blocking business logic
2. Capacity available

Today, the task manager checks to see if a job is blocked for business logic reasons, possibly multiple times. Instead, we could store when the decision has been made that a job is no longer blocked for business logic reasons (i.e. as a field on the job or even in a node-local cache). This, effectively, moves the job further through the pipeline. Note that if a job is not blocked on business logic and there is capacity, then the only reason to record the decision is for posterity. But, if a job is not blocked on business logic & there is no capacity, this is exactly when we want to record the decision made. The next time the task manager is ran, the marked jobs can avoid running the business logic check(s).

We should measure the performance before and after this optimization. We still need to put the Job from the DB to make the second decision but maybe we need to pull less dependency information i.e. for a job we wouldn't need to pull the project update.

# Large -  Incremental Update

Today, the task manager gets the "state of the world" from the database each time it runs. Technically, a little less than the state of the world. For example, we need all the jobs in the `pending` state. Let's say that we have job `J1`. We would need to know the status of the last project update for `J1`, but we don't need to know about ALL project updates. We don't _need_ to get this state from the database each iteration. Instead, we could keep an up-to-date "state of the world" in cache that is piece-wise updated as events occur.

"As events occur" isn't something we have historically been good at. For example, a developer may add code to a reaper for a new case. Any code that changes job `status` would need need to update this in cache view of the "state of the world". A developer modifying reaper code may not be aware that they need to update this cache. Since we know we aren't historically good at communicating this need this system design will need to be such that a developer need not know this cache exists. As much as I hate code that lives in model `save()`, it's the location in code that comes to mind to capture any `status` transition without the developer having to explicitly do so.

Let's also require that we can rebuild the "state of the world" from persistent storage because crashes happen and it's a nice feature. 

We will also need to propagate the state between all Controller control nodes and stay in-sync. We can use websockets or postgres LISTEN/NOTIFY. We also want to include some kind of hash of the "state of the world" so we can check if we are out of sync and/or corrupt.

Ok, we now have an incremental, robust, HA(ish) "state of the world". Why did we build this in the first place? Because pulling the state of the world from the DB is "expensive". But how expensive? We should probably quantify how far we can go with the current system. How many pending/waiting/running jobs until the task manager is too slow?

Another reason we want to build this incremental update system is because I _think_ it sets us up for "the future". I could imagine wanting to schedule jobs based on topology. Maybe jobs that only run on an instance group that only include remote execution nodes are decided to be ran by those remote execution nodes or at least a controller that only controls those remote execution nodes. This also sets us up for sort of sharding our task manager and the decision(s) is makes.

# Large - Deterministic replay

For correctness, debugablility, and reproducing customer issues it would be great if all the decisions the task manager was modified to operate on `Decision Event` only.

#### What is a Decision Event ?

The input needed by the task manager & the decision it makes.
Example: "can job J1 run" `Decision Event`

```
{
  "type": "Job",
  "status": "pending",
  "allow_simultaneous": false,
  "other_job_template_jobs_running": true,
  "project_update_running": "false",
  "last_project_update_succeeded", "false"
  "decision": "fail job because last project update failed"
}
```

The `decision` is the "output" and the rest of the data structure is the "input".

We already use all the information above but it's spread out over multiple data structures. We are explicitly capturing all of the data that we used to make our decision.

#### What can we do with this data?

* Capture `Decision Event` data and replay it through the task manager. More easily invoke "hard" permutations
* We can make a list of hard-coded rules about the input values that should result in a expected decision or partial rules that shouldn't be violated. For example "when last_project_update_succeeded == false => decision should always be to fail the job"
* Replay customer `Decision Event` to recreate scheduling and/or performance bugs. We should isolate the code that acts on the decision.

#### What we can NOT do with this data?

* Changes to the task manager that results in changes in decisions, effectively, invalidates any existing captured set of `Decision Event`

# Large - Rules based Task Manager

The thought keeps entering my mind at night. Can we represent our currently business logic (and maybe capacity logic) with a set of simple rules? Kind of like a grammar. Users could then "configure" and or define their own business rules. Don't want a job to be considered failed if the dependent project update fails? No problem!

This rules feature, paired with the `Decision Event` would set us up to build a system to validate that the thing is following the rules.

**Comment by AlanCoding** [comment] 2021-11-08 14:56
> Today, the task manager makes the blocking business logic decision over and over. Instead, we could store the fact that the decision has been made (i.e. as a field on the job or even in a node-local cache).

Could you elaborate on what decision you're talking about? I don't quite get it. Blocking decisions are temporary. If J1 is blocked on P1, then that's only true while P1 is running. A decision "J1 is blocked" is transient and has to be re-evaluated every time.

**Comment by AlanCoding** [comment] 2021-11-08 16:33
> The input needed by the task manager & the decision it makes.

Would the job's preferred instance groups and their capacities be part of the decision input?

**Comment by chrismeyersfsu** [comment] 2021-11-08 20:02
> Could you elaborate on what decision you're talking about? I don't quite get it. Blocking decisions are temporary. If J1 is blocked on P1, then that's only true while P1 is running. A decision "J1 is blocked" is transient and has to be re-evaluated every time.

Let me edit that for clarity. The decision of "this job is not blocked" should be saved/cached. So when a job is unblocked for business logic reasons but blocked for capacity reasons.

Done editing the original issue text. Let me know if it's unclear or you have other questions.

**Comment by chrismeyersfsu** [comment] 2021-11-08 20:07
> > The input needed by the task manager & the decision it makes.
> 
> Would the job's preferred instance groups and their capacities be part of the decision input?

Yes. I only include an example `Decision Event` input data for the business logic check. I'd imagine a different data-structure for the Capacity check.

I think our solution has a nice and clear separation between the business logic and the capacity and I'd like to continue with that separation.

**Comment by fosterseth** [comment] 2021-11-09 01:22
another consideration -- right now the task manager has to complete a full cycle before any work can begin, because all of the db transactions are set to be atomic.

This leads to a strange behavior where we can never truly maximize the capacity of instances. For example let's say it takes 30 seconds to run the task manager, and in that time the capacity has freed up on the instance groups. But, because the task manager has "out of date" capacity, it won't know this and won't schedule more jobs to consume that extra capacity. As a result, sometimes capacity can hover around 60% of it's maximum, just because the task manager is sluggish.

This problem goes away if you make the task manager sufficiently fast enough to process everything before a typical job will finish. That said, I think task manager demands will grow and grow, and we could re-enter the same behavior eventually. 

Not sure what the solution here is, or if we even need one. We could try to allow the task manager to become aware of newly-freed instance capacity _as_ it's running.

**Comment by AlanCoding** [comment] 2021-11-09 01:48
> As a result, sometimes capacity can hover around 60% of it's maximum, just because the task manager is sluggish.

How often do people really see this in practice? Playbooks that finish fast enough for this to happen are probably doing all local actions. I'm also unclear what the mechanism here is. Because of the lock it uses, dispatching jobs could become the bottleneck if its time exceeds the period at which it is ran. I have never seen evidence of that, and am skeptical that it has ever happened.

And we're talking about this while we haven't looked at the current performance of the task manager. I am sure we are running queries that can be optimized with some prefetch_related additions. The way I've done this before is to import and run the task manager inside of a view and then view the page with the Django debug toolbar.

I still have some fundamental disconnects about the goal of optimizing the task manager. If the problem is scalability, not performance per se, then wouldn't we prefer to break the task manager up into functional units so they can run independently? Consider:

 - Break out all the logic for workflows to spawn jobs and mark finished. Run it on its own period with its own triggers.
 - Instead of processing all pending jobs, process every `(job.id + i) % N == 0` where
   - `job.id` is the primary key of a unified job
   - you are the ith node in the cluster
   - `%` being modulo

This would basically divvy up the jobs among the nodes within the cluster. One cluster node would never block another cluster node. You could add nodes infinitely without the task manager becoming a bottleneck... again, assuming that this is a problem in the first place.

I could be wrong, but AFAIK, you don't need a list of all the other jobs in order to make business logic decisions about _one_ job. You do need the full array of _instances_, and to have their consumed capacity calculated. If you wanted to optimize calculation of consumed capacity, you could trivially pre-calculate and save `task_impact` for jobs (and do sums in postgres, even with Django ORM). But again, I feel like that's addressing the wrong problem. The biggest problem with our consumed capacity calculations are that they use made up constants (which can go out-of-date) instead of live memory usage metrics.

**Comment by chrismeyersfsu** [comment] 2021-11-09 14:56
The most expensive operation we do _should_ be getting the state of the world from the database. Deciding the business logic and if their is capacity and what node to run on _should_ be cheap operations. I agree @AlanCoding that we can optimize the "state of the world" querie(s). The reality of the problem is ensuring that future developers don't undo those optimizations. We have incrementally iterated on the task manager performance a few times. It just becomes to easy for someone to come in and undo the optimizations in favor of adding a new feature.

 The `Decision Event` design proposal will hopefully force this separation & provide the other benefits mentioned.

psuedocode

```
jobs = get_jobs_from_db()
capacity = get_capacity_from_db()

for j in jobs:
  input = generate_decision_event_for_business_logic(jobs, j)
  output1 = make_business_logic_decision(input) 

  input = generation_decision_event_for_capacity(capacity, j)
  output2 = make_capacity_logic_decision(input)
```

Maybe we need to concentrate and consider more tooling and feedback wrapped around the task manager to measure performance for the developer so that they can see the effect their code changes have on performance.

**Comment by AlanCoding** [comment] 2021-11-09 17:05
Yes, I really like the programmatic separation of business decisions. The easier it is to understand, the less likely anything is to regress in the future. Having a single list of `jobs` passed to the operations is simple. The main loop of the current code cycles through intermediate constructs of `all_sorted_tasks`, `self.all_inventory_sources`, `running_workflow_tasks`, `finished_wfjs`, `previously_running_workflow_tasks`, and `running_workflow_tasks`. The number 1 benefit we can obtain is making the task manager easier to follow.

> The most expensive operation we do _should_ be getting the state of the world from the database.

Why do you need a global state of the world? That's a critical question for me, and I really want to hear more thoughts from other developers on that question.

Does `generate_decision_event_for_business_logic` need a list of _all_ jobs? Or can we pass it a partial list of jobs? We have `settings.START_TASK_LIMIT` limit the number of task manager actions to 100. Given that only 100 actions will be taken at maximum, it seems an extraordinary statement to say we expect our bottleneck to be loading all active jobs (the entire state of the world).

**Comment by AlanCoding** [comment] 2021-11-09 18:30
reviewing the code `finished_wfjs` is a good example where it really means "wfjts that were finished by the last processing step". So that would be a good example of a case where these would be better tracked as generalized "decisions", because there will be followup actions for that type of decision.

**Comment by chrismeyersfsu** [comment] 2021-11-09 20:48
As an example. To decide if a job can run. Has the most recent project update ran and succeeded? Has an update on launch project update kicked off and is it finished?

Same question needs to be asked and answered for the related inventory. But it explodes a bit because it isn't just the related inventory, it's the inventory sources related to the related inventory.

You need to know if another job for the same job template is running when `allow_simultaneous = False`.

The entire state of the world isn't needed to make a decision to run a job. Let's consider the other extreme. What is the minimal state of the world needed to make the decision as to if a job can run. Let's do this using an example.

We consider jobs for transitioning from `pending` to `waiting` in the order that they were created. For example if you launch `J1`, `J2`, `J3` from the same `JT` with `allow_simultaneous=True` `J1` must be considered first. The state change in processing `J1` is important and needed to make the right decision to run or not run `J2`. 

But I digress. I want this example to consider the minimal information needed to make a decision on the job we are considering. So back to `J1`. We need `J1` last project update to see if it was fail. If fail then fail job. We need to know if the related project is marked `update_on_launch`. If so, we create a `ProjectUpdate` just in time and we set the created time to be 1 second before this job. So now the state of the world looks like `PU1`, `J1`, `J2`, `J3`. We need to at least check the `status` of all the related inventory inventorysource's. If those are not in a finished state then `J1` can't run.

Now we can consider `J2`. It needs to wait for `PU1` to finish and then check the cache time to see if another project update should be created. Say `PU1` finishes and the cache doesn't require creating a new PU. The job is `allow_simultaneous=True`, just need to check the related inventories relevant inventory sources which would be the same as `J1` unless prompt on launch inventory is being used.

So you start to see the overlap of the state needed. My thought is that if you query only the state that you need from the database for job then you would do a lot of redundant queries.

**Comment by AlanCoding** [comment] 2021-11-10 16:10
I see 2 inter-related optimizations discussed just now:

1. Efficiency of making a business decision
2. Avoiding the re-computation of business decisions
   - for the case when there isn't _capacity_ to run a job, go straight to looking for capacity next time the task manager is ran, skipping the business decision logic

For (1), we would look to avoid hitting queries for things like:

> just need to check the related inventories relevant inventory sources

I believe we would incur several queries in this particular case, because our job queryset does not prefetch `inventory` or `inventory__inventory_sources`

https://github.com/ansible/awx/blob/62e9e7ea80d9b931e33432a3d393bf29be886c2d/awx/main/scheduler/task_manager.py#L126

But assuming that we are going to do (2) (which is the point of this issue) I honestly don't care about (1).

I agree we have a real problem with the task manager that (2) could solve. It's a home-run. If you were to produce a burst of pending jobs (either by a workflow, or temporarily disabling instances), this would tie up system resources constantly for no reason. Implementation could be as easy as adding a non-editable field `is_unblocked`.

I would go even further, and say that `is_unblocked=False` should be set inside of `create_unified_job()` in many cases. When that method is called, you can be sure that `project` and `inventory` are already loaded for unrelated reasons. Adding on `job.inventory.inventory_sources.filter(update_on_launch=True).exists()` adds _one_ query, and allows us to completely skip the business decision logic for those jobs. This could assure that basically all processing that happens inside of `generate_decision_event_for_business_logic` is productive and not a costly no-op.

In related open issues, I am discussing adding more logic into the business decision logic. This is another reason we may want to avoid optimizations in that space for now.

**Comment by AlanCoding** [comment] 2021-11-15 00:38
> We consider jobs for transitioning from `pending` to `waiting` in the order that they were created. For example if you launch `J1`, `J2`, `J3` from the same `JT` with `allow_simultaneous=True` `J1` must be considered first. The state change in processing `J1` is important and needed to make the right decision to run or not run `J2`. 

Returning to this, I want to challenge the idea that we need to process the jobs in order. Or at least I need more justification of why order needs to be preserved.

In the case of `allow_simultaneous=false`, then it's higher consequence that we run the jobs in order, because the 2nd or 3rd job could be delayed by an hour (the runtime of the job template). But in this case, wouldn't that best be expressed by making `J1` a dependency of `J2`, and likewise, `J2` a dependency of `J3`. If `allow_simultaneous` is True, then you could still do the same thing, but why? Doesn't it seem like it defeats the purpose that jobs can function independently?

The main function of the task manager is to spawn dependencies and then manage job dispatching as a Directed Acyclic Graph. If you've done that correctly, why should you impose any constraints on the processing order of the root nodes? If one item must be ran before another item, then you should add an edge to the graph to express this.

**Comment by chrismeyersfsu** [comment] 2021-11-15 18:53
Hmmmmmm. I don't have a great reason. It always seemed like it made the task manager deterministic. This would be a useful property if we ever had the extra time to create a task manager simulator or verified the state transitions.

Do we unlock something by allowing jobs to start out of order? 

Only thing I can think of is that we can, theoretically, get a higher utilization by doing some sort of bin-packing algorithm. However, our method for representing capacity is so "wrong" we could just end up overloading systems if we "better" utilized nodes.

**Contrived example where ordering matters:**
Assume we modify the task manager to not respect creation order.

`allow_simultaneous=True` When I launch the first job `J1` I provide `ticket: 123`. The `ticket` is used in the playbook to talk to servicenow to pop work item `123` off the queue. Work items from servicenow may only be popped off in order. A request to pop work item `456`, for example, would block until work item(s) `1-455` were all popped off.

Now I launch another job and provide `ticket: 124`. The task manager chooses `J2` to run first & this exhausts the system capacity. `J2` will remain in a deadlock state, waiting for `J1` to pop `ticket: 123` off the servicenow queue.

As the customer, I do not want `allow_simultaneous=False`. My playbook has other work that it does before popping in the work item, that is just the critical section. I want my playbooks to run in parallel and I rely on creation order execution.

**Comment by AlanCoding** [comment] 2021-11-16 14:13
Along the lines of what you were doing in this issue, break down the task manager into 3 steps:

1. process and spawn dependencies
2. assign IG and node based on capacity
3. submit work to the PG queues

I follow what you're saying about (2), that it could lead to a deadlock if a user built their JTs to rely on processing order. I don't have a solution for that, and as long as we respect that requirement, this step (2) is a serial process for the entire cluster. I felt like I had to raise the question, but I admit it may not matter if we can instead go with the optimization you proposed of a bulk update to change job `status` to "running" from processing pending jobs.

I was thinking that (3) doesn't happen in the lock anyway. You could imagine 2 nodes running the task manager at similar times. One node might process 100 jobs while the other processes 1 job. The first node will only be part way through step (3) when the second node fully finishes running the task manager, meaning that the 101th job will leapfrog many other jobs that came before it. So we're not completely religious about maintaining ordering now, but this probably doesn't matter. In the case I give, nothing will be blocked on capacity (as in your case), so it's probably of no consequence.

**Comment by AlanCoding** [comment] 2022-10-13 17:20
@fosterseth since https://github.com/ansible/tower/issues/5943 is closed, are you good to close this?

**Comment by fosterseth** [comment] 2022-10-13 19:07
there are probably good ideas still buried here, but would need to be reevaluated (with a new write-up) given the newer context of the task manager.

We should close the ticket, but remember that it exists.

**Closed as completed by fosterseth** 2022-10-13 19:07 UTC
Labels: component:api
