### ISSUE TITLE
can't create a template

### ISSUE THREAD

**Issue by lamhaison** [ansible/awx#310] opened 2017-09-27 06:44 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When I create a job and fill in all information, after I press save button but job can't see this  at the job list is on bellow . After that I refresh page I can see it but I can't edit job

After I view console browser and i see a error log like that vendor.44274240f889b72a5dfe.js:436 TypeError: Cannot read property 'replace' of undefined

##### STEPS TO REPRODUCE

deploy it by using geerlingguy/ansible-role-awx

##### EXPECTED RESULTS

I can create template and edit it
##### ACTUAL RESULTS

When I create a template I can't edit it

##### ADDITIONAL INFORMATION

[error_image](https://ibb.co/hXHS4Q)

**Comment by kiranos** [comment] 2017-09-27 07:30
Hi it would be great if you could install via the official recommendations and see if the issue is there aswell. I bet its hard to custom installations.

**Comment by matburt** [comment] 2017-09-27 10:49
Yep, I'm going to close this because that's not an installation method we support. Try it with our normal installer and let us know how it goes. Or Ask for help on that role.

**Closed as completed by matburt** 2017-09-27 10:49 UTC
