### ISSUE TITLE
Consolidate Job Sliced View

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#3885] opened 2019-05-13 17:01 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
 Currently the sliced portions of the job show as individual objects from the API which require extra queries to determine the overall sliced job result.

Provide an API endpoint which displays the total number of hosts managed, succeeded, and failed in a sliced job.

**Comment by shanemcd** [comment] 2023-04-05 20:58
Closing as a dupe of https://github.com/ansible/awx/issues/12182 since that has more information.

**Closed as completed by shanemcd** 2023-04-05 20:58 UTC
Labels: type:enhancement, component:api, component:ui
