### ISSUE TITLE
Missing drop down options

### ISSUE THREAD

**Issue by gerrond** [ansible/awx#2619] opened 2018-11-06 19:33 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

  When trying to setup authentication using LDAP, LDAP Group  Type Drop down Menu is empty. I tried other drop down menu options (ie. TACACs+ Authentication Protocol) and it is also empty. I had an older version of AWX and it is working fine on the version of browser.

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: RHEL 7.5
* Web Browser: Google Chrome 69.0.3497.81

##### STEPS TO REPRODUCE

I restarted the app and tried to configure LDAP with the same result.

##### EXPECTED RESULTS

I expect to be able to select different options on the drop down menu on LDAP Group Type

##### ACTUAL RESULTS

LDAP Group Type drop down menu is empty

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/44817325/48088721-bb806080-e1d0-11e8-90ca-8ad053e57393.png)

**Comment by jakemcdermott** [comment] 2018-11-06 21:29
Hello @gerrond 

Thanks for creating this issue. This appears to be a duplicate of https://github.com/ansible/awx/issues/2586 so I am closing. We will track the resolution of this bug in the other issue.

**Closed as completed by jakemcdermott** 2018-11-06 21:29 UTC
Labels: type:bug, component:ui
