### ISSUE TITLE
Continue a failed workflow at the last successful node

### ISSUE THREAD

**Issue by Sasa993** [ansible/awx#14176] opened 2023-06-27 15:38 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

It would be nice if a failed workflow job could be restarted after the last successful workflow node (similar to a Gitlab CI pipeline behavior).

### Select the relevant components

- [X] UI
- [x] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

After relaunching the workflow, do a restart of it - but at the first node it failed.

### Current results

- Launch the workflow job
- 3rd node fails
- Relaunch the workflow job
- Execute 1st node, 2nd node, 3rd node

### Sugested feature result

- Launch the workflow job
- 3rd node fails
- Relaunch the workflow job
- Execute 3rd node and continue further

**Comment by shanemcd** [comment] 2023-06-29 15:20
Dupe of https://github.com/ansible/awx/issues/1284

**Closed as completed by shanemcd** 2023-06-29 15:20 UTC
Labels: type:enhancement, component:api, component:ui, community

**Comment by Sasa993** [comment] 2023-06-29 16:35
Ohh, I haven't notice that one. Thank you @shanemcd
