### ISSUE TITLE
No Job output on any Template launch

### ISSUE THREAD

**Issue by janviudapi** [ansible/awx#9242] opened 2021-02-05 06:49 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Any template/job I launch there is no output on newly deployed Ansible AWX

There is no job output in http://<awx>/#/jobs/playbook/<job_id>/output
Empty job events in https://<awx>/api/v2/jobs/<job_id>/job_events/

##### ENVIRONMENT
AWX version: 17.0.1
AWX install method: Docker containers
Ansible version: 2.9.17
Operating System: Ubuntu 20
Web Browser: Edge and chrome (latest)

##### STEPS TO REPRODUCE

Launch any Job or template, but no output.

##### ACTUAL RESULTS

Must be able to see output whether it is failed or success, but since there is no output not able to determine what is going wrong.

##### ADDITIONAL INFORMATION

I freshly deployed AWX instance

ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/home/vjanvi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                  NAMES
f9f1517879a5        ansible/awx:17.0.1   "/usr/bin/tini -- /u…"   2 days ago          Up 14 hours         8052/tcp               awx_task
a90161753531        ansible/awx:17.0.1   "/usr/bin/tini -- /b…"   2 days ago          Up 14 hours         0.0.0.0:80->8052/tcp   awx_web
65a486047d8e        postgres:12          "docker-entrypoint.s…"   2 days ago          Up 14 hours         5432/tcp               awx_postgres
d7cc1340c825        redis                "docker-entrypoint.s…"   2 days ago          Up 14 hours         6379/tcp               awx_redis

awx_task continer
cd /var/lib/awx
bash-4.4# ls
rsyslog  vendor  venv

![image](https://user-images.githubusercontent.com/60569075/106999854-f0632f80-67ac-11eb-8bb9-7a5de2974e4d.png)

![image](https://user-images.githubusercontent.com/60569075/106999822-dc1f3280-67ac-11eb-9dbf-e76d0454bae2.png)

Please let me know Estimated time to resolve this, and which AWX version is stable one so I can use it.

**Comment by DanyD** [comment] 2021-02-05 08:58
As a hotfix I figured out you can switch to the details tab and back to output which forces a reload and then shows the log. Seems to be a JS issue not triggering a periodic update.

**Comment by dimovstanimir** [comment] 2021-02-05 11:00
The same issue here. There is no update in the template output until the playbook has finished. I only get updates if I refresh manually the page in the browser by hitting F5 every 1-2 seconds or I wait till the template has finished and it dumps all the information regarding the status of the template execution at once. 

My configuration is the same as the poster of this bug:

AWX version: 17.0.1
AWX install method: Docker containers
Ansible version: 2.9.17
Operating System: Ubuntu 20.04 LTS
Web Browser: Chrome, Firefox, Edge. All are latest.

I also created an issue for AWX version 16.0.0 ( https://github.com/ansible/awx/issues/8994 ) and was waiting and hoping that in the new release this would be fixed but in the end it seems that this is not the case. By the way is there anyone who hasn't face this issue? It does not seem to be possible just for "some" people after all we are all using the same setup/installation process.

Is this really so hard to be fixed in all versions till now. I think that this is a major bug which require maximum attention and efforts to be fixed as it is quite annoying and stand in the way of a really important functionality.

**Comment by janviudapi** [comment] 2021-02-05 12:46
Jut to update, I tried with your fix but still there Output window is **Empty** #9242

**Comment by jakemcdermott** [comment] 2021-02-05 20:45
:wave: hello 

Thanks for creating this issue.

The job output update bug you described is caused by a combination of https://github.com/ansible/awx/issues/8596 and possibly https://github.com/ansible/awx/issues/9085.

We'll have a fix for it in the upcoming awx release: https://github.com/ansible/awx/pull/9208#issuecomment-773754460

I'm closing this issue for now - we're tracking the work for this in the issues linked above. 

also see:  
  - https://github.com/ansible/awx/issues/9193
  - https://github.com/ansible/awx/issues/8930
  - https://github.com/ansible/awx/issues/8973
  - https://github.com/ansible/awx/issues/9105
  - https://github.com/ansible/awx/issues/9112
  - https://github.com/ansible/awx/issues/9183

**Comment by jakemcdermott** [comment] 2021-02-05 20:46
> Please let me know Estimated time to resolve this, and which AWX version is stable one so I can use it.

The ETA is: When it's done.

**Closed as completed by jakemcdermott** 2021-02-05 20:46 UTC
Labels: type:bug, component:ui, flag:community

**Comment by dimovstanimir** [comment] 2021-03-19 09:52
In version 17.1.0 the job output does not still update automatically but requires manual refresh.

Is this really so hard to be fixed?

**Comment by kuznetsovkk** [comment] 2021-03-23 19:23
Is it fixed in 18.0.0?

**Comment by lorenzgith** [comment] 2021-03-25 17:58
> Is it fixed in 18.0.0?

Nope
