### ISSUE TITLE
Extra Variable field does not render as read-only in JT Prompt Preview

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3298] opened 2019-02-22 23:14 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The extra variable field on the JT prompt preview modal does not render as read-only.

##### ENVIRONMENT
* AWX version: 3.0.0

##### STEPS TO REPRODUCE
1. Create a WFJT with a promptable inventory and Extra Vars
2. Launch WFJT and view the Preview tab on the Prompt Modal.
Note: Does not appear read-only and the cursor blinks as if the field can be edited

##### EXPECTED RESULTS

A read-only representation of the field would appear as read-only (like an auditor persona)

##### ACTUAL RESULTS
Does not appear read-only and the cursor blinks as if the field can be edited

##### ADDITIONAL INFORMATION

![screen shot 2019-02-22 at 6 13 53 pm](https://user-images.githubusercontent.com/12446869/53276593-a40cab00-36cd-11e9-8203-3104ba993a7c.png)

**Comment by mabashian** [comment] 2019-06-11 14:24
~I think this is actually true everywhere - I see the same thing in the WF form~ Actually - I do think this isolated to a few places.  I'll try to clean up as many of them as I can while I'm fixing the launch preview.

**Comment by mabashian** [comment] 2019-06-11 19:38
OK actually I don't think this is a regression.  You _are_ able to click into the preview and it shows a cursor but you can't actually edit anything.  This behavior is expected because completely disabling the codemirror would prevent the user from copying/pasting out of that block which is something we've battled in the past.  I am going to open up a PR to disable some extra var fields that are currently not disabled for read-only users but I'm going to close this one for now.

**Closed as completed by mabashian** 2019-06-11 19:38 UTC
Labels: type:bug, component:ui, component:ux, qe:regression
