### ISSUE TITLE
Project revision not updating

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#6812] opened 2020-04-23 05:02 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When doing project sync the revision is not updated, I have observed this behavior as well in 10.x

##### ENVIRONMENT
* AWX version: 11.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

NOTE: I'm using git SCM type

1. Modify and commit new changes in SCM
2. Sync the project associated with that SCM
3. Click expand and observe the REVISION

In my testing, I'm switching between branches master to another branch vice versa.

##### EXPECTED RESULTS

Latest revision from SCM should reflect in the UI

##### ACTUAL RESULTS

The latest revision is not reflected in the UI after project sync is done.

<img width="315" alt="Screen Shot 2020-04-23 at 12 50 10 PM" src="https://user-images.githubusercontent.com/10410660/80060802-0bd4b500-8562-11ea-8175-a9897fd757ff.png">

**Comment by ryan012880** [comment] 2020-04-24 02:58
Upon observation, this is an intermittent issue since sometimes revision reflects but not immediately, I have to navigate to another menu and go back to the project.

When it does not reflect and you examine to job log it pulls the same revision even though the branch have changed.

**Comment by AlanCoding** [comment] 2020-04-24 15:10
> 1. Modify and commit new changes in SCM
> 2. Sync the project associated with that SCM
> 3. Click expand and observe the REVISION
>
> In my testing, I'm switching between branches master to another branch vice versa.

These steps of 1-3 look like they don't fully cover what happened, and "switching between branches" could mean more than one thing.

If you could give some more detail, then we return to dive into a test case on our side. Thanks.

**Comment by ryan012880** [comment] 2020-04-29 14:47
Possible duplicate of https://github.com/ansible/awx/issues/6770, the issue occurs when enabling DELETE ON UPDATE or/and UPDATE REVISION ON LAUNCH in SCM UPDATE OPTION

**Comment by fosterseth** [comment] 2020-04-29 15:40
sounds similar to this https://github.com/ansible/awx/issues/6535

I wasn't able to reproduce that issue, but the author remedied the situation by doing a hard refresh of the page.

**Comment by ryan012880** [comment] 2020-04-30 08:10
@fosterseth yeah correct thanks, I did some test again and hard-refresh works when not enabling DELETE ON UPDATE, if I have that enabled I always get the below (incomplete job log) every time:

<img width="670" alt="Screen Shot 2020-04-30 at 3 55 14 PM" src="https://user-images.githubusercontent.com/10410660/80686730-c41ed200-8afb-11ea-9885-6b73e18cc643.png">

Doing hard-refresh did not refresh the revision in the UI. However, if I check directly on the project directory inside the server and do a git log, I have the correct revision.

**Comment by fosterseth** [comment] 2020-04-30 17:19
@ryan012880 the project update job has a successful status though? even in the case where the stdout log is incomplete?

are you launching project updates directly, or are these project updates started by launching a job template?

**Comment by ryan012880** [comment] 2020-05-01 03:49
@fosterseth yes the project update job has a successful status.

launching the project updates directly, I've also tested the project updates started by launching a job template in which I enabled both DELETE ON UPDATE and UPDATE REVISION ON LAUNCH in SCM UPDATE OPTION same issue.

**Comment by ryanpetrello** [comment] 2020-05-01 17:14
@ryan012880 would you mind giving `devel` a try?  I think something I just fixed might explain what you're seeing:

https://github.com/ansible/awx/commit/bf65b40241d60e99e49b3109a33c26f26cd418ec

cc @AlanCoding @fosterseth

**Comment by ryan012880** [comment] 2020-05-02 05:23
@ryanpetrello just tried devel and the sync issue is fixed.

the only remaining minor issue is I think related to cosmetic in which I have to do a hard refresh or navigate to other page and go back again to the project page to see the new revision reflected in the UI, I have a parallel instance running on an earlier version (9.1.1 before redis) in which I didn't have to do that so I don't see this as a connectivity/reliability issue. 

I won't be able to try the new version now in a fast link but I will confirm when I do. thank you for the great effort!

**Comment by kdelee** [comment] 2020-05-04 19:40
Closing this as a duplicate of https://github.com/ansible/tower/issues/4270 and because user reports it as fixed

**Closed as completed by kdelee** 2020-05-04 19:40 UTC
Labels: type:bug

**Comment by chazemery** [comment] 2020-12-08 15:41
@ryanpetrello any idea if the fix will be included in an upcoming Ansible release?

**Comment by ryanpetrello** [comment] 2020-12-08 15:45
@chazemery this should already be resolved in newer versions of AWX (we merged a fix 6 months ago).

**Comment by rtacconi** [comment] 2021-02-10 12:21
I really cannot see that the job is using the latest revision from the master branch, it is driving me crazy
