### ISSUE TITLE
Unable to install via Operator

### ISSUE THREAD

**Issue by bvanev** [ansible/awx#10943] opened 2021-08-26 02:56 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Unable to get AWX installed and operational per instructions here: https://github.com/ansible/awx-operator

### AWX version

0.13.0

### Installation method

minikube

### Modifications

no

### Operating system

Ubuntu 20.04.2 LTS

### Steps to reproduce

Clean VM Install on ESXi from ISO
Install VMWare Tools
Install docker
Install minikube
set docker as default driver
Follow steps here: https://github.com/ansible/awx-operator
I execute `kubectl apply -f awx-demo.yml`  with failed result

### Expected results

$ kubectl get pods -l "app.kubernetes.io/managed-by=awx-operator"
NAME                        READY   STATUS    RESTARTS   AGE
**awx-demo-77d96f88d5-pnhr8   4/4     Running   0          3m24s**
awx-demo-postgres-0         1/1     Running   0          3m34s

### Actual results

`--------------------------- Ansible Task Status Event StdOut  -----------------

PLAY RECAP *********************************************************************
localhost                  : ok=30   changed=0    unreachable=0    failed=1    skipped=27   rescued=0    ignored=0   

-------------------------------------------------------------------------------
{"level":"error","ts":1629908075.1995249,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/awx-demo","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}`

**Comment by shanemcd** [comment] 2021-08-27 17:38
Dupe of https://github.com/ansible/awx-operator/issues/494. Updates will be posted over there.

**Closed as completed by shanemcd** 2021-08-27 17:38 UTC
