### ISSUE TITLE
No error received when management jobs are scheduled in past date

### ISSUE THREAD

**Issue by soniya20** [ansible/awx#5523] opened 2019-12-17 10:26 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
No error received when management jobs are scheduled in past date

##### ENVIRONMENT
AWX version: 9.0.1
AWX install method: doocker
Operating System: rhel7.4
Web Browser: Chrome 78.0.3904.108

##### STEPS TO REPRODUCE

Case 1:END date = Never
1. Login to AWX dashboard with admin user.
2. Now click on the management job and select "Cleanup Activity Stream"
3. Select END date is 'Never'
4. Schedule the job at a past date.
5. Analyze the behavior.

Case 2:END date = After
1. Login to AWX dashboard with admin user.
2. Now click on the management job and select "Cleanup Activity Stream"
3. Select END date is 'After'
4. Schedule the job at a past date.
5. Analyze the behavior.

Case 3:END date = OnDate
1. Login to AWX dashboard with admin user.
2. Now click on the management job and select "Cleanup Activity Stream"
3. Select END date is 'On Date'
4. Schedule the job at a past date.
5. Analyze the behavior.

##### EXPECTED RESULTS
Error or warning message should be displayed  when user tries to schedule a job at past date.

##### ACTUAL RESULTS
It is observed that when management job is scheduled in past date with 'END' parameter set as -
Case 1:Never
Case 2:After
Case 3:On Date,
job gets scheduled successfully.

**Comment by ryanpetrello** [comment] 2020-01-03 18:27
This is mostly a duplicate of https://github.com/ansible/awx/issues/5524 (if we resolved #5524, it would likely resolve this case as well since the code is shared).

**Closed as completed by ryanpetrello** 2020-01-03 18:27 UTC
Labels: type:bug
