### ISSUE TITLE
[ui_next] Inventory Sync Job Status does not finalize via websocket

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8076] opened 2020-09-03 18:12 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory Sync Job Status does not finalize via websocket

##### ENVIRONMENT
* AWX version: cce66e366fb1f8c866d89f8551e5909c2888fbf5

##### STEPS TO REPRODUCE
1. Launch an Inventory sync job via Workflow Job Visualizer or Jobs List
2. Wait for Job to complete in success or failure
Note: Inventory Sync job never completes without refresh

##### EXPECTED RESULTS
1. Job status to update

##### ACTUAL RESULTS
1. All job statuses received except finalization

##### GIF
https://share.getcloudapp.com/7KuLWYyQ

**Comment by mabashian** [comment] 2020-11-17 15:15
Dupe of https://github.com/ansible/awx/issues/8063

**Closed as completed by mabashian** 2020-11-17 15:15 UTC
Labels: type:bug
