### ISSUE TITLE
GUI bug: add an existing group to the host is not shown properly

### ISSUE THREAD

**Issue by showblue** [ansible/awx#11280] opened 2021-10-26 12:38 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When I try to add an existing group to a host, the GUI doesn't show the group names, and the list of available groups are blank. 
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/15809379/138879835-69f157f3-383d-4e59-a722-27a9ef49361e.png">

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

Select 'Hosts' from side bar, pick a host, then select 'Groups' tab, click 'Add', and the 'Select Groups' window will show a list of blank group names 

### Expected results

The list of group names should be displayed properly

### Actual results

The list of group names are shown as blanks

**Comment by nixocio** [comment] 2021-10-26 13:01
@showblue thanks for filing this issue. This is a duplicate of https://github.com/ansible/awx/issues/11256. There is an open PR to address that one.

**Closed as completed by nixocio** 2021-10-26 13:01 UTC
