### ISSUE TITLE
Job progress is not updated in the browser but the job is running fine (f5 works)

### ISSUE THREAD

**Issue by DBLaci** [ansible/awx#654] opened 2017-11-15 14:07 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
My browser is not updated when I launch a job. Any job, including a projetct vcs update for example.

##### ENVIRONMENT
* AWX version: 1.0.1.203
* AWX install method: docker on linux (docker-compose AND docker-compose stack deployed to swarm)
* Ansible version:  2.4.1.0 (irrelevant)
* Operating System: Ubuntu 16.04 LTS
* Web Browser: Chrome 63

##### STEPS TO REPRODUCE

Fresh install, log in, add vcs credentials, add project, manually trigger project update.

##### EXPECTED RESULTS

I expect the green sphere to turn to grey (pending) then the blinking one and finally green again. At this point the project should show the update date, etc.

##### ACTUAL RESULTS

I press update, the indicator turns to grey. If in the job view: "Waiting for results...".
If i press F5 (refresh) the progress is shown (half progress for example) but not refreshing automatically.

##### ADDITIONAL INFORMATION

I experienced this problem with local docker-compose (ansible/awx_*:1.0.1.203 images) and in Swarm too. The latter is behind reverse proxy.

In the chrome network tab there is no error. The websocket seems to be working too.

![2017-11-15 14-51-24_awx_update](https://user-images.githubusercontent.com/5806644/32840018-af8ce672-ca16-11e7-806f-bdeeeb7a00a2.png)

**Comment by ryanpetrello** [comment] 2017-11-15 14:41
@DBLaci a change recently landed in awx that upgraded Django and a handful of other third party libraries that awx relies on (including one we use for managing websockets).  What you're encountering is a bug that's currently being diagnosed in the websocket library:

https://github.com/ansible/awx/issues/615

Stay tuned!

**Comment by ryanpetrello** [comment] 2017-11-15 14:41
Duplicate of #615

**Closed as completed by ryanpetrello** 2017-11-15 14:41 UTC
Labels: type:bug, component:ui

**Comment by ryanpetrello** [comment] 2017-11-27 20:49
Should now be fixed via https://github.com/ansible/awx/pull/720
