### ISSUE TITLE
Running Job log does not follow stdout of the running job without page refresh

### ISSUE THREAD

**Issue by BenCoffeed** [ansible/awx#1831] opened 2018-05-01 15:11 UTC
Possibly a regression of issue https://github.com/ansible/awx/issues/437

ISSUE TYPE

    Bug Report

COMPONENT NAME

    UI

SUMMARY

To see the current job status, the execution steps and the real elapsed time, users must reload the webpage manually. AWX should provide these job informations update on the fly to the UI.
ENVIRONMENT

    AWX version: AWX 1.0.5.31 (current devel)
    AWX install method: docker on linux (official install instructions from github)
    Docker version: 17.12.0-ce, build c97c6d6
    Ansible version: 2.5.2
    Operating System: 
        AWX host: Ubuntu 16.04
        Client: MacOS High Sierra
    Web Browser: Mozilla Firefox Developer Edition 60.0b16 (64-bit), Google Chrome Version Version 65.0.3325.181 (Official Build) (64-bit), and  Safari Version 11.1 (13605.1.33.1.2)

STEPS TO REPRODUCE

1 - Create a job template.
2 - Go to the JOBS view.
3 - Choose it on the list.
4 - Click in the launch/Relaunch(Rocket) button.
5 - The status of the execution will modify to "PENDING" status and it will not be updated any more.
6 - Reload the webpage and verify the new job status and the tasks log.
EXPECTED RESULTS

After launch/Relaunch the Job, the job status view must load all the new job informations automatically. Users wants to see the job changes and its status on the fly. (Like Jenkins Console screen, for example).
ACTUAL RESULTS

Users must reload the JOB webpage manually to be able to see the real job status and task logs.
ADDITIONAL INFORMATION

**Comment by jakemcdermott** [comment] 2018-05-01 17:08
Hello @BenCoffeed ,

I'm not able to reproduce this on current awx devel:

![relaunch](https://user-images.githubusercontent.com/9753817/39483524-ad2f205e-4d40-11e8-96e3-a310fca7555f.gif)

Did I capture your steps correctly? Are you seeing any tracebacks or errors in the webconsole?

**Comment by jakemcdermott** [comment] 2018-05-01 17:13
@BenCoffeed 

If you're referring to relaunching from the jobs list, we intentionally do _not_ route the user to the results page from the job list. This is to facilitate the use case of relaunching multiple jobs at once.

**Comment by wenottingham** [comment] 2018-06-01 17:35
Closing, please reopen if this persists on a current release, and please see the last comment above.

**Closed as completed by wenottingham** 2018-06-01 17:35 UTC
Labels: type:bug, component:ui
