### ISSUE TITLE
Organize job templates with folders

### ISSUE THREAD

**Issue by rbagul** [ansible/awx#13800] opened 2023-04-04 22:35 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Hi,

Is it possible to add feature to add folders and then add job templates in the folders/directories. It can be huge in organizing large number of job templates. Currently we are managing it with naming conventions. Ability to organize job templates with with folders could be better organized. 

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Consider having 100+ job templates in each business unit within the organization. Each business unit would like to organize templates as per the teams or applications or modules so that each business unit admins can manage it better. 

### Current results

Currently we are not able to create folders to organize the templates. 

### Sugested feature result

Add one layer/button on the job templates tab to create folder and then ability to create templates inside that.

**Comment by shanemcd** [comment] 2023-04-06 20:32
Dupe of https://github.com/ansible/awx/issues/2058.

**Closed as completed by shanemcd** 2023-04-06 20:32 UTC
Labels: type:enhancement, component:ui, help wanted, community
