### ISSUE TITLE
UI does not show recursive workflow error

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#12245] opened 2022-05-17 15:46 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

API errors are not getting surfaced to the UI.

This particular case is easy to create manually, and the status is "failed", yet the `job_explanation` text is not shown in the UI. The user gets a failure state with no details.

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

To hit this error, create and launch a recursive workflow. This is trivial to do in the UI.

 - Create a new blank WFJT (workflow job template)
 - Follow the prompts to add a woflow node, and select the same workflow that you are editing (you had to put in the name in the first step)
 - Save the editor
 - Launch the workflow
 - The workflow job you lands on will be successful, but the 1 node inside of it will be failed - click on that failed node to see the page for the nested workflow

### Expected results

Details about failure.

The API details at `/api/v2/workflow_jobs/31/` (in this case) has this in the JSON data

```json
    "job_env": {},
    "job_explanation": "Workflow Job spawned from workflow could not start because it would result in recursion (spawn order, most recent first: <WorkflowJobTemplate - TablePicture莝-25>, <WorkflowJobTemplate - TablePicture莝-25>)",
    "result_traceback": "",
```

I expect the UI to show that message (no preference as to where)

### Actual results

There is no available information in the UI as to the nature of the failure.

![Screenshot from 2022-05-17 11-30-58](https://user-images.githubusercontent.com/1385596/168852041-d9e553c3-e48d-480c-ae0e-ca5e9c6b36d3.png)

![Screenshot from 2022-05-17 11-31-04](https://user-images.githubusercontent.com/1385596/168852043-8f42a32c-fdd0-44c4-8e4d-3b2847e3993b.png)

### Additional information

This is similar to https://github.com/ansible/awx/issues/12231. Any non-blank `job_explanation` or `result_traceback` should probably be presented to the user unconditionally, for all job types. In this particular case, the workflow job is failed, and so it seems particularly bad to miss the message here.

**Comment by nixocio** [comment] 2022-05-19 16:15
Closing as dupe of https://github.com/ansible/awx/issues/12129

**Closed as completed by nixocio** 2022-05-19 16:15 UTC
Labels: type:bug, component:ui, needs_triage
