### ISSUE TITLE
[RFE] Add description to Job Template expanded view

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#5118] opened 2019-10-25 17:14 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Feature request to add the JT description to the expanded view of Templates.

**Comment by AlanCoding** [comment] 2019-10-25 20:02
Duplicate of https://github.com/ansible/awx/issues/4359

**Closed as completed** 2019-10-25 20:09 UTC
Labels: type:enhancement, component:ui
