### ISSUE TITLE
documented ssh jump host setup does not work

### ISSUE THREAD

**Issue by chenri2006** [ansible/awx#2108] opened 2018-07-30 19:35 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

The documented method to use ssh jump host

https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#setting-up-a-jump-host-to-use-with-tower

does not work.

First of all, the recommended directive

Proxycommand ssh -W [jumphostuser]@%h:%p tampa

will not work if you specify [jumphostuser]. It should be

Proxycommand ssh -W %h:%p tampa

Even with this change, it still does not work through the awx UI. We get errors like

ssh_exchange_identification: This account is currently not available.

However, the same command, as shown by awx output:

<target_host> SSH: EXEC ssh -o ControlMaster=no -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=60 -o ControlMaster=no -v -o 'ProxyCommand=ssh -W %h:%p -q <jumphost>' <target_host> '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''

works fine when carried out from the command line as awx user on the awx server.

##### ENVIRONMENT
* AWX version: 1.0.2.0
* AWX install method: rpm on centos 7
* Ansible version: 2.6.1
* Operating System: centos 7.5
* Web Browser: firefox latest, chrome latest

##### STEPS TO REPRODUCE

set up jump host as indicated by the above awx docs url.

##### EXPECTED RESULTS

It should work the same way as from the command line.

##### ACTUAL RESULTS

We get error like

ssh_exchange_identification: This account is currently not available.

and further tests indicate that the jump host is not even contacted and some kind of cached result is used. Does awx cache failed connection data in a cache store such as memcached or postgres?

##### ADDITIONAL INFORMATION

Since the command line works, this is an issue with awx UI. No other info related with OS should be relevant. But if further info is needed, let me know.

Thanks

Richard

**Comment by matburt** [comment] 2018-10-26 02:39
dupe of https://github.com/ansible/awx/issues/2279 which contains workaround

**Closed as completed by matburt** 2018-10-26 02:39 UTC
Labels: type:bug, component:ui
