### ISSUE TITLE
Email sent to Chinese, there is a problem with garbled code

### ISSUE THREAD

**Issue by thisID** [ansible/awx#7400] opened 2020-06-22 02:50 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Where should I set it to display Chinese properly

````
Project Update #744 had status successful, view details at https://towerhost/#/jobs/project/744

{
    "id": 744,
    "name": "\u6279\u91cf\u5b89\u88c5jdk\u9879\u76ee-test3",
"url": "https://towerhost/#/jobs/project/744",
    "created_by": "None",
    "started": "2020-06-22T02:49:31.785910+00:00",
    "finished": "2020-06-22T02:49:36.336942+00:00",
    "status": "successful",
    "traceback": ""
}

````

**Comment by ryanpetrello** [comment] 2020-10-02 18:11
`批量安装jdk项目`

**Comment by ryanpetrello** [comment] 2020-10-02 18:22
@thisID good find - mind giving this PR a try?

https://github.com/ansible/awx/pull/8313

**Comment by thisID** [comment] 2020-10-15 02:45
> @thisID很好找到-介意尝试此PR吗？
> 
> [＃8313](https://github.com/ansible/awx/pull/8313)

Thank you very much. The method you provided is ok.

**Comment by wenottingham** [comment] 2020-10-15 15:22
Thanks for the verification!

**Comment by unlikelyzero** [comment] 2020-10-28 15:25
Set notification body to {"body": "很好找到-介意尝试此PR吗"}

Received webhook:
{"body": "\u5f88\u597d\u627e\u5230-\u4ecb\u610f\u5c1d\u8bd5\u6b64PR\u5417"}

**Comment by ryanpetrello** [comment] 2020-10-28 16:25
I'll take a look at this.

**Comment by ryanpetrello** [comment] 2020-10-28 16:36
@unlikelyzero I'm having trouble reproducing this:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/214912/97466890-ff1e8880-1919-11eb-9178-2ab7332c910b.png">

<img width="569" alt="image" src="https://user-images.githubusercontent.com/214912/97466963-12c9ef00-191a-11eb-8f83-77ffd8e2b462.png">
<img width="812" alt="image" src="https://user-images.githubusercontent.com/214912/97467015-22e1ce80-191a-11eb-8d4d-6bf36721fb48.png">


Can you give instructions or a test that shows it not working?  Thanks.

**Comment by ryanpetrello** [comment] 2020-10-28 16:37
(trying with an actual email server)

**Comment by ryanpetrello** [comment] 2020-10-28 16:44
@unlikelyzero it looks like it worked fine to me:

```shell
~ curl -s "https://mailtrap.io/api/v1/inboxes/REDACTED/messages/" -H "Api-Token: REDACTED" | jq | grep -B10 "rpetrell"
[
  {
    "id": 1923361532,
    "subject": "很好找到-介意尝试此PR吗",
    "sent_at": "2020-10-28T16:39:49.000Z",
```

```shell
~ curl -s "https://mailtrap.io/api/v1/inboxes/REDACTED/messages/REDACTED/body.txt" -H "Api-Token: REDACTED"
很好找到-介意尝试此PR吗
```

**Comment by unlikelyzero** [comment] 2020-10-28 16:47
@ryanpetrello tried with webhook on webhook.site. It's possible that:
1. This fix does not apply to webhooks
2. This webhook testing site cannot handle chinese characters

**Comment by unlikelyzero** [comment] 2020-10-28 16:53
wait, are you sending chinese characters without the json "body" in the message?

I'm sending "{"body": "很好找到-介意尝试此PR吗"}"

**Comment by ryanpetrello** [comment] 2020-10-28 16:55
This looks like the Python `requests` library we use for web hooks is converting the characters to unicode code points.

**Comment by ryanpetrello** [comment] 2020-10-28 16:55
<img width="746" alt="image" src="https://user-images.githubusercontent.com/214912/97469560-ecf21980-191c-11eb-924e-16b0b7366dd4.png">

**Comment by unlikelyzero** [comment] 2020-10-28 16:56
@ryanpetrello ok so close this and reopen another for webhooks for release.next?

**Comment by ryanpetrello** [comment] 2020-10-28 17:08
Okay @unlikelyzero this is ready for another look for the webhooks case.

**Comment by unlikelyzero** [comment] 2020-10-28 18:14
![asdf](https://user-images.githubusercontent.com/12446869/97478820-ddc49900-1927-11eb-9ac5-4ff6c6d691d5.jpg)

**Closed as completed** 2020-10-28 18:20 UTC
Labels: type:bug, component:api
