### ISSUE TITLE
Problem with symbolic links in ansible role to run a job

### ISSUE THREAD

**Issue by aldelsa** [ansible/awx#9952] opened 2021-04-20 13:16 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Recently I upgrade my awx version from 17.0 to 19.0 using awx-operator and migrating database such as is described on official docu. Everything is okay but when I run a job I had an error in container awx-task.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: awx-operator in k8s
* Ansible version: 2.10
* Operating System: kubernetes running on ubuntu 18

##### STEPS TO REPRODUCE
Have a broken symbolic link in an ansible role repo and update from 17.0.0 to 19.0.0 using awx-operator

##### EXPECTED RESULTS
Jobs running successful even with a broken symbolic link like in the 17.0.0 version.

##### ACTUAL RESULTS
I am getting this error in awx-task container:
```
2021-04-20 11:35:50,723 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(4)
2021-04-20 11:35:50,899 DEBUG    [fb4b1880602c4f4881d883bc995d279d] awx.analytics.job_lifecycle job-15549 running playbook
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3018, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), **self.runner_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/interface.py", line 243, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/streaming.py", line 53, in run
    self._output.write(utils.stream_dir(self.private_data_dir))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/utils.py", line 95, in stream_dir
    archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
  File "/usr/lib64/python3.8/zipfile.py", line 1740, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.8/zipfile.py", line 522, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pdd_wrapper_15549_mh85vlnt/awx_15549_luuthi79/project/core/roles/role-01/files/public_keys/XXXX/XXXXX'
```

**Comment by shanemcd** [comment] 2021-04-21 16:56
Interesting. I'm not sure what we can do here, since it seems like it's the `zipfile` module blowing up. 

Perhaps we can try to detect the broken symlink and skip adding it to the archive?

**Comment by aldelsa** [comment] 2021-04-21 18:30
I think you mean something like that:

```
# ansible-runner/ansible_runner/utils/streaming.py

def stream_dir(source_directory, stream):
    with tempfile.NamedTemporaryFile() as tmp:
        with zipfile.ZipFile(tmp.name, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=True) as archive:
            if source_directory:
                for dirpath, dirs, files in os.walk(source_directory):
                    relpath = os.path.relpath(dirpath, source_directory)
                    if relpath == ".":
                        relpath = ""
                    for fname in files:
                        if os.path.islink(fname) and not os.path.exists(fname):
                            continue
                        archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
            archive.close()
```

**Comment by sarabrajsingh** [comment] 2021-05-10 20:44
After much discussion, the happiest path forward seems to be to make sure that the runtime user of the AWX job gets notified that a broken symlink was attempted to be zipped into the archive, and subsequently, fail the job afterwards. We will leave it to the runtime user to fix their repos, or to rectify the broken symlink. Here is an example of an output from a job in AWX that leverages a project which contains a broken symlink:

```
Traceback (most recent call last):
  File "/awx_devel/awx/main/tasks.py", line 1378, in run
    res = receptor_job.run()
  File "/awx_devel/awx/main/tasks.py", line 2915, in run
    return self._run_internal(receptor_ctl)
  File "/awx_devel/awx/main/tasks.py", line 2939, in _run_internal
    raise transmitter_thread.exc[1].with_traceback(transmitter_thread.exc[2])
  File "/awx_devel/awx/main/tasks.py", line 2895, in run
    super().run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/awx_devel/awx/main/tasks.py", line 2990, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), debug=True, **self.runner_params)
  File "/awx_devel/ansible-runner/ansible_runner/interface.py", line 249, in run
    r.run()
  File "/awx_devel/ansible-runner/ansible_runner/streaming.py", line 53, in run
    stream_dir(self.private_data_dir, self._output)
  File "/awx_devel/ansible-runner/ansible_runner/utils/streaming.py", line 25, in stream_dir
    raise e
  File "/awx_devel/ansible-runner/ansible_runner/utils/streaming.py", line 22, in stream_dir
    archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
  File "/usr/lib64/python3.8/zipfile.py", line 1740, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.8/zipfile.py", line 522, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] invalid symlink detected: '/tmp/pdd_wrapper_70_weja68s9/awx_70_a_hmmrw3/project/roles/role-02/tasks/main.yml'
```

**Comment by akus062381** [comment] 2021-06-01 19:39
@AlanCoding we attempted to reproduce this bug, but we aren't getting the new error- we are still getting the old error
Was this code change in ansible runner and are we using the new released code?

```Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1382, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2898, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2922, in _run_internal
    raise transmitter_thread.exc[1].with_traceback(transmitter_thread.exc[2])
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2878, in run
    super().run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/common.py", line 1036, in wrapper_cleanup_new_process
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2973, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), **self.runner_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/interface.py", line 249, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/streaming.py", line 53, in run
    stream_dir(self.private_data_dir, self._output)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/utils/streaming.py", line 20, in stream_dir
    archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
  File "/usr/lib64/python3.8/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.8/zipfile.py", line 523, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pdd_wrapper_2_h7_jrbdc/awx_2_d0nrf6aw/project/garbagelink'```

**Comment by sarabrajsingh** [comment] 2021-06-01 20:15
@akus062381 - the code change was inside ansible-runner. we bumped up the version of ansible runner to `2.0.0a4` to encompass the changes. install that version into your awx instance and try to reproduce

**Comment by kdelee** [comment] 2021-06-01 21:57
@sarabrajsingh it would be preferable if you updated the requirements file for awx
https://github.com/ansible/awx/blob/896d8959342eccff5f103ee748d1fe246ff64ecc/requirements/requirements.in#L2

**Comment by kdelee** [comment] 2021-06-01 22:04
@sarabrajsingh I did pip install from the git tag https://github.com/ansible/ansible-runner/releases/tag/2.0.0-alpha4 in the awx venv and I'm still getting the same error that @akus062381 was seeing, not the new error
```
# source /var/lib/awx/venv/awx/bin/activate
# pip freeze | grep runner
ansible-runner==2.0.0a4
```

I see https://github.com/ansible/ansible-runner/commit/50b4ea8f745b467e66dc298676f328c1f26816a5, but not seeming to hit it when we run the job. This is a VM install launching a job into a container group

**Comment by sarabrajsingh** [comment] 2021-06-08 04:18
A new fix has been pushed by @shanemcd in the ansible-runner repo to address the symlink issue - [ansible/ansible-runner#713. ](https://github.com/ansible/ansible-runner/pull/713).

**Comment by yagomarques** [comment] 2021-06-14 20:27
**it's working**, we tested on this [issue](https://github.com/ansible/awx/issues/10302/)

check this [comment](https://github.com/ansible/awx/issues/10302/#issuecomment-860963394) for more details.

**Closed as completed by yagomarques** 2021-06-14 20:27 UTC
Labels: type:bug, component:api
