### ISSUE TITLE
Handle Ansible 2.5+ playbook host summary fields (ignore, rescued)

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#466] opened 2017-10-18 14:34 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

Ansible 2.5 will adjust the playbook stats returned via callback... AWX may need updated for this.
Filing for tracking reasons.

AFAIK, the UI does not use this event, so it's just on the API side for now.

##### ADDITIONAL INFORMATION

https://github.com/ansible/ansible/issues/31245

**Comment by AlanCoding** [comment] 2017-10-18 14:42
Looks like the new statuses are basically "rescued" and "ignored". It'll be a migration, but then they should follow the same existing pattern.

I see mention of a `v2_on_rescued` callback method, which we would have to adjust for, but it doesn't not even seem to be present in the feature branch yet.

**Comment by AlanCoding** [comment] 2018-11-01 13:33
Confirmed with @mkrizek that this is still on Ansible core's agenda, and could possibly land in 2.8.

Thus, we are keeping this issue open.

**Comment by AlanCoding** [comment] 2018-11-09 15:33
Heads up - pull request in core has been opened. If it lands, we need to land support for it here ASAP

**Comment by AlanCoding** [comment] 2018-11-12 12:21
Link active PR https://github.com/ansible/ansible/pull/48418

**Comment by jladdjr** [comment] 2019-02-13 01:40
Leaving the `blocked` label on this ticket. Asked core if there's anyone on the core team that can review / move along the corresponding ansible issue:
https://github.com/ansible/ansible/pull/48418#issuecomment-462976503

**Comment by ryanpetrello** [comment] 2019-02-13 15:13
@jladdjr looks like they've made some review progress.  Can we start developing _against_ their PR, since it's probably _close_ to what the final product will be?  Should be pretty simple to install ansible _from that branch_ in our dev env.

**Comment by jladdjr** [comment] 2019-02-13 17:03
@ryanpetrello - absolutely, that's what I've been doing in the meantime

**Comment by jladdjr** [comment] 2019-02-28 17:54
Checked with @one-t about playbook stats this morning. There are two items left for testing at this point:
* Verifying that playbook stats show up in external logging
* Verifying that nothing breaks during an upgrade

**Comment by kdelee** [comment] 2019-03-18 18:22
~@dsesami we are going to want a toggle on the jobs settings page to enable/disable stats collection~

**Comment by jladdjr** [comment] 2019-03-18 19:12
@kdelee - sounds like you're talking about https://github.com/ansible/tower/issues/3223

I re-posted a similar comment on that ticket

**Comment by kdelee** [comment] 2019-03-20 20:42
@jladdjr woopsy, you are right

**Comment by kdelee** [comment] 2019-04-23 17:39
@one-t going to close this as I think you are done. Please re-open if need be

**Closed as completed by kdelee** 2019-04-23 17:39 UTC
Labels: type:enhancement, component:api
