### ISSUE TITLE
Launching an ad-hoc command with default verbosity gives 400 error

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#12591] opened 2022-07-29 18:16 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

If I launch an ad hoc command against the Demo Inventory with default options it gives a 400 response code due to validation of the `verbosity` field. It seems that the UI is misinterpreting the API options.

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Go to the Demo Inventory, then hosts.

Click on a host and click to run command.

Go through the menu and make the most basic selections to run an echo command.

### Expected results

Runs the echo command.

### Actual results

Got a 400 Bad Request error.

![Screenshot from 2022-07-29 12-02-20](https://user-images.githubusercontent.com/1385596/181819839-6c140d32-1ec4-41d2-9520-955f4527b65b.png)

### Additional information

If you consult the API OPTIONS, you see the expectations:

```json
            "verbosity": {
                "type": "choice",
                "required": false,
                "label": "Verbosity",
                "filterable": true,
                "default": 0,
                "choices": [
                    [
                        0,
                        "0 (Normal)"
                    ],
                    [
                        1,
                        "1 (Verbose)"
                    ],
                    [
                        2,
                        "2 (More Verbose)"
                    ],
                    [
                        3,
                        "3 (Debug)"
                    ],
                    [
                        4,
                        "4 (Connection Debug)"
                    ],
                    [
                        5,
                        "5 (WinRM Debug)"
                    ]
                ]
            },
```

If you check the request data from the UI, we have this:

![Screenshot from 2022-07-29 12-02-20](https://user-images.githubusercontent.com/1385596/181819866-8a2e12bc-9343-4824-a380-0dc29712f64f.png)

So the API will accept a `0` value for verbosity, but the UI is submitting the _label_ for that option,  "0 (Normal)"

I just rebuilt the UI and did a hard refresh with commit d555093325cdd612b7f2e6aeee79e0a216fc07d2

**Comment by kurokobo** [comment] 2022-07-30 05:08
The `verbosity` is defaulted to `VERBOSITY()[0]` and this seems to point to a label `0 (Normal)`.

https://github.com/ansible/awx/blob/86a67abbce3d21ccffd61fb576398c7b471a2c23/awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.js#L58-L76

https://github.com/ansible/awx/blob/86a67abbce3d21ccffd61fb576398c7b471a2c23/awx/ui/src/components/VerbositySelectField/VerbositySelectField.js#L9-L16

**Comment by john-westcott-iv** [comment] 2022-08-03 15:56
Closing as dupe of https://github.com/ansible/awx/issues/12575

**Closed as completed by john-westcott-iv** 2022-08-03 15:56 UTC
Labels: type:bug, component:ui
