### ISSUE TITLE
Templates - Inventory: "Prompt on launch" not working correctly

### ISSUE THREAD

**Issue by stefan-wegener** [ansible/awx#1389] opened 2018-02-28 13:24 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
 "ERROR! Job Template Inventory is missing or undefined." window appears when using a template with a "Prompt on launch"-Inventory.

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Linux (Ubuntu)
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

1. Create Template with Inventory field empty and "Prompt on launch" field selected.
2. Launch Template -> Select one of your Inventories.  (It appears as selected in the upper part of the frame) -> Next button -> Prompt window correctly shows which Inventory has been selected -> Launch button -> "ERROR! Job Template inventory is missing or undefined." window appears.

<img width="820" alt="awx1" src="https://user-images.githubusercontent.com/5695658/36789723-d0c56a0c-1c92-11e8-994c-eab76583203e.png">

<img width="857" alt="awx2" src="https://user-images.githubusercontent.com/5695658/36789735-db3214c2-1c92-11e8-94e9-dd1671497bb1.png">

<img width="852" alt="awx3" src="https://user-images.githubusercontent.com/5695658/36789753-e97135d6-1c92-11e8-9493-3fc058bd619b.png">

<img width="787" alt="awx4" src="https://user-images.githubusercontent.com/5695658/36789757-ecf416c4-1c92-11e8-956a-b5159aa0e052.png">

##### EXPECTED RESULTS

Template gets launched on selected Inventories.

##### ACTUAL RESULTS

Template does not launch.

##### ADDITIONAL INFORMATION

It also seems to be another bug, that if during Template-creation I define an Inventory - but also select "Prompt on launch", that when launching the Template, it always gets launched on this Inventory, even when I deselected it during the launch-prompt.

**Comment by tidypete** [comment] 2018-03-01 10:01
Having the same issue in AWX version: 1.0.4.14

**Comment by mabashian** [comment] 2018-03-01 16:51
This looks like a duplicate of https://github.com/ansible/awx/issues/1281.  This issue should be fixed by https://github.com/ansible/awx/pull/1357 (awx version 1.0.4.17).

**Closed as completed by mabashian** 2018-03-01 16:51 UTC
