### ISSUE TITLE
Docker-Compose build 19.0.0: nginx fails

### ISSUE THREAD

**Issue by apiening** [ansible/awx#9986] opened 2021-04-22 12:21 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After following the instructions from https://github.com/ansible/awx/blob/19.0.0/tools/docker-compose/README.md the web interface is not reachable and the logs are complaining that `nginx` could not be started.

##### ENVIRONMENT
* AWX version: 19.0
* AWX install method: docker on linux
* Ansible version:  2.9.20
* Operating System: Ubuntu 18.04.4 LTS
* Web Browser: Firefox 88.0

##### STEPS TO REPRODUCE

* git clone -b 19.0.0 https://github.com/ansible/awx.git
* cd awx
* make docker-compose-build
* make docker-compose
* docker exec tools_awx_1 make clean-ui ui-devel
* docker exec -ti tools_awx_1 awx-manage createsuperuser

##### EXPECTED RESULTS

Nginx should be started, web interface should be reachable.

##### ACTUAL RESULTS

Web interface von responding with HTTPS at port 8043 and log shows `nginx` related errors.

##### ADDITIONAL INFORMATION

Output of `docker-compose logs -f | grep awx-nginx`:
```
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout |
tools_awx_1 | 2021-04-22 12:05:49,238 INFO exited: awx-nginx (exit status 2; not expected)
```

**Comment by shanemcd** [comment] 2021-04-22 12:47
Please search for existing issues before opening a new one. Dupe of https://github.com/ansible/awx/issues/9552

**Closed as completed by shanemcd** 2021-04-22 12:47 UTC
Labels: type:bug
