### ISSUE TITLE
AWX Container fail to start,  pull access denied for ansible/awx ; Error starting project 404 Client Error: Not Found (\"pull access denied for ansible/awx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by iamraj007** [ansible/awx#7252] opened 2020-06-04 15:40 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version:   11.2.0 (git clone code on 04 June 2020)
* AWX install method:  docker(Docker version 19.03.11) on Linux (AWS Centos)
* Ansible version:  2.9.9
* Operating System: CentOS Linux release 7.7.1908 (Core)
* Web Browser: N/A

##### STEPS TO REPRODUCE

Clone the AWX official repo (https://github.com/ansible/awx.git)
run:  ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

It should run with no issue and docker containers with Name: awx_task,awx_web etc 
##### ACTUAL RESULTS

It failed due to permission issue, it cant access docker image any more 
{"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"**pull access denied for ansible/awx**, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\")"}

##### ADDITIONAL INFORMATION

This was working fine till last week.

**Comment by iamraj007** [comment] 2020-06-04 15:47
For clarification i am able access docker image in question without any login and i am using compose.yml to run this.

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
redis               latest              36304d3b4540        6 days ago          104MB
postgres            10                  d92854c53ed1        2 weeks ago         200MB
memcached           alpine              35acd9837d07        3 weeks ago         9.28MB
**ansible/awx_task**    latest              24f27e19bd06        5 weeks ago         2.47GB
ansible/awx_web     latest              61c4d41939ca        5 weeks ago         2.44GB


You may try in case, you wish to verify as of now 04062020
docker pull ansible/awx_task
docker pull ansible/awx_web

**Comment by ryanpetrello** [comment] 2020-06-04 16:02
duplicate of https://github.com/ansible/awx/issues/7246

**Closed as completed by ryanpetrello** 2020-06-04 16:02 UTC
Labels: type:bug
