### ISSUE TITLE
Integrate basic search with output page

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6614] opened 2020-04-06 19:30 UTC
##### SUMMARY
Add basic search and filter to output.

**Comment by jakemcdermott** [comment] 2020-04-06 19:32
blocked label can be removed when https://github.com/ansible/awx/issues/6612 lands

**Comment by mabashian** [comment] 2021-02-03 18:07
Dupe of #5906

**Closed as completed by mabashian** 2021-02-03 18:07 UTC
Labels: component:ui, type:feature
