### ISSUE TITLE
Docker-compose pull generate : Pulling awx (/awx_devel:latest)... ERROR: invalid reference format

### ISSUE THREAD

**Issue by Gaby033** [ansible/awx#1435] opened 2018-03-05 13:37 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I had the error "internal server error" due to the pgsql being in /tmp/pgdocker (worked fine during a month), so I decided to upgrade my AWX environment from 1.0.3.29 to the latest : 1.0.4. Unfortunatly, I am now unable to start AWX because of the following error : 
```
> docker-compose pull
Pulling awx (/awx_devel:latest)...
ERROR: invalid reference format
```

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Centos 7.4
* Web Browser: Firefox
* Docker version : 17.12.1-ce

##### STEPS TO REPRODUCE
```
docker stop awx_task awx_web memcached rabbitmq postgres
cd /root/awx/
git checkout .
git reset
git pull
cd /root/awx/installer
vi inventory
# Modify :
postgres_data_dir=/root/pgdocker
project_data_dir=/var/lib/awx/projects
# End modification

vi /root/awx/installer/local_docker/tasks/standalone.yml
# Modify :
# For all containers :
restart_policy: always

# For AWX Task Container
- name: Activate AWX Task Container
    volumes:
      - "{{ project_data_dir }}:/var/lib/awx/projects:rw"
      - "/root/.ssh:/root/.ssh:rw"
# End modification

ansible-playbook -i inventory install.yml
```
There, AWX was starting correctly (lost all of my datas because of the pgdocker issue, but it's not a problem here). But when I accessed the url "api/v2/config/" the version of AWX was still 1.0.3.29.
So I remembered that I needed to do one more thing : 
```
> docker stop awx_task awx_web memcached rabbitmq postgres
> cd /root/awx/tools/
> docker-compose pull && docker-compose up --force recreate
WARNING: The DEV_DOCKER_TAG_BASE variable is not set. Defaulting to a blank string.
WARNING: The TAG variable is not set. Defaulting to a blank string.
Pulling postgres (postgres:9.6)...
9.6: Pulling from library/postgres
Digest: sha256:e20d6068f3684303383d11fb529bed49ec93fc36c018bf4f59033e0348371285
Status: Image is up to date for postgres:9.6
Pulling memcached (memcached:alpine)...
alpine: Pulling from library/memcached
Digest: sha256:6d7bde6a89491fb133d672a5834954749f8ddd31ff97653b2494f86a4189f10a
Status: Image is up to date for memcached:alpine
Pulling rabbitmq (rabbitmq:3-management)...
3-management: Pulling from library/rabbitmq
Digest: sha256:0f681f18d80b2979596e8b262d06cacf7948e924d7f3a67e89be5fdea82cd116
Status: Image is up to date for rabbitmq:3-management
Pulling awx (/awx_devel:latest)...
ERROR: invalid reference format
```

##### EXPECTED RESULTS
AWX starting normally and upgraded.

##### ACTUAL RESULTS
AWX doesn't start anymore because awx_web and awx_task containers are missing.

##### ADDITIONAL INFORMATION
I'm running all the commands as root. Also, I have already run this process for a previous upgrade of AWX and it worked fine.

Edit : I also tried to make a fresh install of the latest AWX on a new Centos 7, just like before, once I run the install.yml, AWX is working (and this time with the latest version : 1.0.4.48 which is normal because it's fresh install) but if I do the ```docker-compose pull``` I got the same error as when I tried to upgrade AWX.

**Comment by matburt** [comment] 2018-03-06 18:02
I can't reproduce this. Is it a problem with your volume?

**Comment by Gaby033** [comment] 2018-03-07 09:49
I guess that by "volume" you're refering to what I wrote inside this file : /root/awx/installer/local_docker/tasks/standalone.yml ?

I reverted the changes of that file and tried again the `docker-compose pull`, same error.
I don't know if it can be of any help, but when I run again the `ansible-playbook -i inventory install.yml` I got the following error : 
```
TASK [local_docker : Ensure directory exists] 
skipping: [localhost]

TASK [local_docker : Copy web image to docker execution] 
skipping: [localhost]

TASK [local_docker : Copy task image to docker execution] 
skipping: [localhost]

TASK [local_docker : Load web image] 
skipping: [localhost]

TASK [local_docker : Load task image] 
skipping: [localhost]

TASK [local_docker : include_role] 
skipping: [localhost]

TASK [local_docker : Set full image path for local install] 
skipping: [localhost]

TASK [local_docker : Set DockerHub Image Paths] 
ok: [localhost]

TASK [local_docker : Activate postgres container] 
changed: [localhost]

TASK [local_docker : Activate rabbitmq container] 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating container: 404 Client Error: Not Found (\"No such image: rabbitmq:3\")"}
        to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP 
localhost                  : ok=5    changed=1    unreachable=0    failed=1
```

Don't hesitate to tell me which command you would like me to execute, or which file you would like to see :) It's weird that you can't reproduce it. Because as I said, even on a fresh install on a new machine, I got the same issue. And before this pgsql problem, it was working fine with that config.

Would you know a command to manually download what the docker-compose can't retrieve ? Or to make it give more info than just `ERROR: invalid reference format` ?

Thanks for your help.

Edit : I have been able to bypass the problem by doing the following : 
```
cd /root/awx/tools/
docker pull ansible/awx_task:latest
cd /root/awx/installer
ansible-playbook -i inventory install.yml
```
And this time no error. But if I relaunch `docker-compose pull` there is still the same problem.

Would it be because of that line : https://github.com/ansible/awx/blob/2385f6231123d527514306bde8d4a0beb816cdb4/tools/docker-compose.yml#L29 ?
Because it's looking for that `Pulling awx (/awx_devel:latest)...` instead of `Pulling awx (ansible/awx_task:latest)...` (I think)

**Comment by matburt** [comment] 2018-03-07 18:10
Something is definitely strange with your setup if you run into this: `Error creating container: 404 Client Error: Not Found (\"No such image: rabbitmq:3\")`

That means your setup can't see this: https://hub.docker.com/r/library/rabbitmq/tags/3/

Which is pretty well guaranteed to be there.

**Comment by matburt** [comment] 2018-03-07 18:10
It seems like your tools have an issue contact dockerhub?

**Comment by shanemcd** [comment] 2018-03-07 18:19
I would recommend deleting everything and trying again:

```
$ docker stop -t 0 $(docker ps -qa)
$ docker rm -f $(docker ps -qa)
$ docker rmi -f $(docker images -qa)
```

Edit:

After running the commands above a `systemctl restart docker` might be a good idea.

**Comment by Gaby033** [comment] 2018-03-08 09:43
Thank you for the commands, I executed the 4 of them, and then the `ansible-playbook -i inventory install.yml` : no error and AWX started correctly.

Then I wanted to try `docker-compose pull` still the same error. After that I launched again the `install.yml` (which gave me the `No such image: rabbitmq:3` during my upgrade attempt) and this time no error, AWX started correctly.

So I don't know if it's my configuration which makes the `docker-compose pull && docker-compose up --force-recreate` to failed (which would be strange because during my first upgrade to AWX 1.0.3 it did work) or if it's a real bug.
In the INSTALL.md it's said that to upgrade AWX, it should be with that command. So I'm wondering, is the 4 commands you gave me @shanemcd are also an acceptable way to upgrade AWX (safely if possible :D) ?

**Comment by wenottingham** [comment] 2018-06-01 17:51
Closing this - this appears to be an issue with your local docker configuration. If this persists for you, you might be better off contacting us via the `awx-project` mailing list or the `#ansible-awx` IRC channel for easier debugging.

**Closed as completed by wenottingham** 2018-06-01 17:52 UTC
Labels: type:bug, component:installer
