### ISSUE TITLE
K3s issue with Operator version 0.29.0 

### ISSUE THREAD

**Issue by antuelle78** [ansible/awx#12901] opened 2022-09-17 05:01 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When deploying AWX 21.6.0 with the latest version of the operator 0.29.0 ok K3s, the awx pod get stuck in "Init:CrashLoopBackOff" status.

The same version of AWX deployed with operator 0.28.0 works as expected.

### AWX version

21.6.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13.4

### Operating system

Ubuntu 22.04

### Steps to reproduce

https://github.com/antuelle78/deploy-awx-k3s-ubuntu

Set:
**k3s_version**: v1.25.0+k3s1
I tested multiple versions as far back as 1.21, same results
**operator_version**: 0.29.0
**awx_version**: 21.6.0

in https://github.com/antuelle78/deploy-awx-k3s-ubuntu/blob/main/roles/deploy-awx-k3s-ubuntu/defaults/main.yml

Then run the deploy.yml playbook.

### Expected results

AWX gets deployed and I can access the web interface at hostIP:30080

### Actual results

AWX pod gets stuck in Init:CrashLoopBackOff state.

**Comment by antuelle78** [comment] 2022-09-17 16:59
Small update, I just noticed that even if the I set awx_version: 21.6.0 using operator 0.28.0.
The version of awx deployed is 21.5.0

**Comment by doubletwist13** [comment] 2022-09-19 13:26
I see the same issue in RHEL8.   

```
RHEL8 version: 8.6
K3S Versions:
Client Version: v1.24.4+k3s1
Kustomize Version: v4.5.4
Server Version: v1.24.4+k3s1
```


Installing `RELEASE_TAG=0.28.0` works fine, but with `RELEASE_TAG=0.29.0`, the pod gets stuck in Init:CrashLoopBackOff state.

This happens both when doing a clean install per the process from https://computingforgeeks.com/install-and-configure-ansible-awx-on-centos/  or when doing an upgrade from 0.28.0 per the process at https://computingforgeeks.com/how-to-upgrade-ansible-awx-running-in-kubernetes/

**Comment by kurokobo** [comment] 2022-09-19 21:31
It's not an issue for AWX but for AWX Operator.
This should be discussed on https://github.com/ansible/awx-operator/issues/1055

**Comment by djyasin** [comment] 2022-09-21 17:38
Duplicate of https://github.com/ansible/awx-operator/issues/1055.

**Closed as completed by djyasin** 2022-09-21 17:38 UTC
Labels: type:bug, needs_triage, community
