### ISSUE TITLE
Failed to import the required Python library (zabbix-api) on automation-job

### ISSUE THREAD

**Issue by Nitish0292** [ansible/awx#11387] opened 2021-11-24 07:11 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

community.zabbix collection is not working
it says failed to import
Failed to import the required Python library (zabbix-api) on automation-job

### AWX version

19.4

### Installation method

minikube

### Modifications

no

### Ansible version

latest

### Operating system

Oracle 8

### Web browser

Chrome

### Steps to reproduce

Add community.zabbix to requirements sync project
after that try to use zabbix module, it will always through error like below
"exception": "Traceback (most recent call last):\n  File **\"/tmp/ansible_community.zabbix.zabbix_maintenance_payload_8rwsmonj/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/wrappers.py\", line 15, in <module>\n    from zabbix_api import ZabbixAPI, Already_Exists, ZabbixAPIException\nModuleNotFoundError: No module named 'zabbix_api'\n",**

"msg": "Failed to import the required Python library (zabbix-api) on automation-job-183-sffqp's Python /usr/bin/python3. See https://pypi.org/project/zabbix-api/ for more info. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",

### Expected results

"exception": "Traceback (most recent call last):\n  File **\"/tmp/ansible_community.zabbix.zabbix_maintenance_payload_8rwsmonj/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/wrappers.py\", line 15, in <module>\n    from zabbix_api import ZabbixAPI, Already_Exists, ZabbixAPIException\nModuleNotFoundError: No module named 'zabbix_api'\n",**

"msg": "Failed to import the required Python library (zabbix-api) on automation-job-183-sffqp's Python /usr/bin/python3. See https://pypi.org/project/zabbix-api/ for more info. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",

### Actual results

"exception": "Traceback (most recent call last):\n  File **\"/tmp/ansible_community.zabbix.zabbix_maintenance_payload_8rwsmonj/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/wrappers.py\", line 15, in <module>\n    from zabbix_api import ZabbixAPI, Already_Exists, ZabbixAPIException\nModuleNotFoundError: No module named 'zabbix_api'\n",**

"msg": "Failed to import the required Python library (zabbix-api) on automation-job-183-sffqp's Python /usr/bin/python3. See https://pypi.org/project/zabbix-api/ for more info. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",

**Comment by ffirg** [comment] 2021-11-24 16:34
This is not a bug and the repo isn't a support forum. You need to build a custom EE with the required dependencies. Closing.

**Closed as completed by ffirg** 2021-11-24 16:34 UTC
