### ISSUE TITLE
No Standard Out being displayed

### ISSUE THREAD

**Issue by seansabour** [ansible/awx#1724] opened 2018-04-03 22:09 UTC
##### ISSUE TYPE
 - Bug Report
 

##### COMPONENT NAME
 - UI

##### SUMMARY
When I execute a template, ad-hoc command or even sync a project with SCM the standard out is blank with a spinning indicator saying "working...." even though the job has failed or completed successfully.  If I refresh I can download the logs, but still does not show in the UI.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Centos 7.4
* Web Browser: Firefox 59.0.2

##### STEPS TO REPRODUCE
1. Create new Projects and setup with Private Github project and don't enter any credentials
2. Sync process kicks off and fails.
3. No standard out appears
4. Refresh page and click download logs icon

##### EXPECTED RESULTS

To be able to see the standard out from the UI.

##### ACTUAL RESULTS

Blank Standard Out with no error message

##### ADDITIONAL INFORMATION

I tried to retry the job and it shows the standard out.

**Comment by jaredevantabor** [comment] 2018-04-04 18:55
likely a duplicate of 1723

**Closed as completed** 2018-04-09 17:38 UTC
Labels: type:bug, component:api, component:ui
