### ISSUE TITLE
Unable to add questions to surveys

### ISSUE THREAD

**Issue by orgito** [ansible/awx#477] opened 2017-10-20 12:39 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When adding questions to a survey the Preview pane does not work and the ADD button stays disabled preventing the user to add new questions.

##### ENVIRONMENT
* AWX version: 1.0.1.77
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: Centos 7.4
* Web Browser: Chrome 60.0.3112.78

##### STEPS TO REPRODUCE

1. On a template job, add or edit a survey.
2. Try to add a question.

##### EXPECTED RESULTS

User should be able to add a question.

##### ACTUAL RESULTS

The preview pane does not show anything and the ADD button stays disabled.

##### ADDITIONAL INFORMATION
Using Developer Tools to forcibly enable the ADD button allows the question to be added.

**Comment by gconsidine** [comment] 2017-10-20 14:13
Thanks, @orgito.

Did you fill out all the required fields before attempting to add the question? I wasn't able to reproduce this locally, but I'm working off of a feature branch and only tried to add a handful of questions.

If you're able to follow up with a screenshot and/or what type of question you're adding it'd be a big help.

**Comment by orgito** [comment] 2017-10-20 17:17
Yes, I filled out all required fields. The type of questions does not make a difference.

I'm able to update questions of existing surveys but cannot add questions either to existing or new surveys. If I forcefully enable the ADD button using chrome developer tools the question is added without errors.

![survey](https://user-images.githubusercontent.com/4852822/31833586-c0733198-b5a9-11e7-89f5-9ec976a24f6a.png)

**Comment by AlanCoding** [comment] 2017-10-20 17:28
Just to rule it out - could you tell us what user you're doing this as (system admin, JT admin, etc.)? Also, could you report what the `user_capabilities` inside of `summary_fields` gives for `edit` (navigate to `http://yourserver.com/api/v2/job_templates/N/` for your JT?

**Comment by orgito** [comment] 2017-10-20 18:54
default  admin user (SYSTEM ADMINISTRATOR)

```json
        "user_capabilities": {
            "edit": true,
            "start": true,
            "copy": true,
            "schedule": true,
            "delete": true
        },
```

I don't think it is a permission problem since I can still add the questions if I remove the `disabled` attribute from the ADD button. Looks like a bug in the UI. I just noticed after upgrading to 1.0.1.77 and I have been very busy adding playbooks, so it must be recent.

Were you able to reproduce? Is it possible that this problem is restricted to my system only?

**Comment by AlanCoding** [comment] 2017-10-20 19:11
I can't not reproduce after rebuilding the UI earlier today.

 - Chrome 61.0.3163.100
 - MacBook

**Comment by orgito** [comment] 2017-10-21 14:49
I investigated a little more and noticed that the culprit is the `default_float `input. It starts with an `ng-invalid` class and cause the form to be in an `ng-invalid ` class too.

Even when it is initially hidden it has an `ng-invalid` class. Apparently due to `ng-invalid-aw-range-max`.

If I select the type float, entering anything valid in the  `default_float ` input changes the state to valid again and the **ADD** button is enabled. I can even remove what I entered and it stays valid. When I change back to another type of question the form remains valid and the **ADD** button stays enabled.

I don't have a dev environment setup so I could not figure out why this is happening.

**Comment by orgito** [comment] 2017-10-21 16:41
So, it looks like this is caused by a very weird Chrome Bug. Here are the steps to reproduce:

1) Have a numeric login name (yes, really);
2) Remove any existing Chrome saved login/password pairs for the AWX web page;
3) Log in to the AWX web page using your numeric login;
4) When prompted save the credentials;
5) Try to add a question to a survey;
6) Look at the DEFAULT ANSWER field for the float type question;

Chrome thinks that the default_float input field is the username login field and offers your login as an option to fill in. At the same time it messes up with the form validation causing angular to mark the field as invalid.

One of the reasons Chrome is getting confuse might be because the type of the field is number. Maybe adding a name or id to the field will make Chrome stop confusing the field with the username field.

![teste](https://user-images.githubusercontent.com/4852822/31853801-d35d0c6a-b66d-11e7-98c3-7541ad95ac89.png)

Also, since my login id is greater than 100 (the default aw-range-max for the field), it makes sense that it is causing `ng-invalid-aw-range-max` violation.

**I obfuscated the login, but it is only compose by numbers.**

**Comment by matburt** [comment] 2017-11-07 02:37
This is a super narrow use case but I'm going to leave it open and see if maybe we can provide some hints for it.

**Comment by orgito** [comment] 2017-11-09 11:11
Ok. Now that I know the cause I'm just working around it and it's fine.

**Comment by matburt** [comment] 2018-03-09 18:43
Closing this issue since it doesn't have a direct solution from us.

**Closed as completed by matburt** 2018-03-09 18:43 UTC
Labels: type:bug, component:ui, help wanted, good first issue
