### ISSUE TITLE
custom Credential types with extra_vars injector not working

### ISSUE THREAD

**Issue by stanislaspiron** [ansible/awx#9771] opened 2021-03-31 15:19 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: microk8s via awx operator
* Ansible version:  version provided in AWX 18.0.0
* Operating System: ubuntu 20.04
* Web Browser: firefox

##### STEPS TO REPRODUCE

Create a simple user/ password credential type:
Input configuration
```
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
required:
  - username
  - password
```

Injector:
```
extra_vars:
  user: '{{ username }}'
  password: '{{ password }}'
```

use it in a template (I tried with my own playbooks as well as Demo Job Template) and launch it... 
##### EXPECTED RESULTS

the job may not run and use variables as defined in credential object.

##### ACTUAL RESULTS

the following error appears:

```
[WARNING]:  * Failed to parse /tmp/tmp6k8163uh/inventory/hosts with script
plugin: Unable to retrieve file contents Could not find or access
'/runner/tmp00dsouw6' on the Ansible Controller. If you are using a module and
expect the file to exist on the remote, see the remote_src option
[WARNING]:  * Failed to parse /tmp/tmp6k8163uh/inventory/hosts with yaml
plugin: Unable to retrieve file contents Could not find or access
'/runner/tmp00dsouw6' on the Ansible Controller. If you are using a module and
expect the file to exist on the remote, see the remote_src option
[WARNING]:  * Failed to parse /tmp/tmp6k8163uh/inventory/hosts with ini plugin:
Unable to retrieve file contents Could not find or access '/runner/tmp00dsouw6'
on the Ansible Controller. If you are using a module and expect the file to
exist on the remote, see the remote_src option
[WARNING]: Unable to parse /tmp/tmp6k8163uh/inventory/hosts as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```

I tried to change variable names, but the result was the same.

when changing from 'extra_vars' to 'env', the playbook run. I didn't check yet if I can access to that env variable to set ansible variable in playbook.

**Comment by shanemcd** [comment] 2021-04-07 22:55
This error looks a lot like https://github.com/ansible/awx/issues/9763 and https://github.com/ansible/awx/issues/9704. Can you try on AWX 19?

**Comment by stanislaspiron** [comment] 2021-04-09 14:39
@shanemcd I still have the same error in version 19.0.0

**Comment by ryanpetrello** [comment] 2021-04-12 19:19
@stanislaspiron is this a duplicate of https://github.com/ansible/awx/issues/7944?

Your error message above suggests you're attempting to use these in an inventory sync (which isn't supported in AWX currently)

cc @AlanCoding @wenottingham

**Comment by AlanCoding** [comment] 2021-04-12 19:28
Could you get the job number for that inventory update and look at the API browser like `/api/v2/inventory_updates/42/`, and past the JSON data from that?

Ryan's link is the most relevant, extra vars injectors can't be expected to work yet.

However, something seems off. The inventory path `/tmp/tmp6k8163uh/inventory/hosts` isn't what I expected, and the extra vars file path `/runner/tmp00dsouw6` isn't found. Paths inside the container are getting mixed with paths outside the container.

**Comment by AlanCoding** [comment] 2021-04-12 19:31
I'm learning towards a theory that our working directory might be wrong for certain job types.

**Comment by stanislaspiron** [comment] 2021-04-13 09:27
@AlanCoding this is not related to Inventory sync.. Only jobs with extra_vars injected by custom Credentials type... 
I only use locally managed Inventory. 

It should be the same cause, but it is another failing feature. 

The same credential type was working fine in version 11.2. when I moved to version 18, it stopped working.

Now, I changed all my playbooks to use ENV variables instead of extra vars.

**Comment by ryanpetrello** [comment] 2021-04-13 17:14
@stanislaspiron I'm not able to reproduce this.

Here's a custom credential type I've created:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/214912/114593163-c836f780-9c59-11eb-8dce-7a1c06363a7d.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/214912/114593062-ab9abf80-9c59-11eb-9e49-516345595d3b.png">

...and here's a playbook I've run with this credential attached:

https://github.com/ansible/test-playbooks/blob/master/debug_extra_vars.yml
<img width="408" alt="image" src="https://user-images.githubusercontent.com/214912/114593395-10eeb080-9c5a-11eb-8413-2bbaa89f933d.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/214912/114593431-19df8200-9c5a-11eb-9b63-b05683efcbd6.png">

**Comment by stanislaspiron** [comment] 2021-04-13 17:34
@ryanpetrello

I found the mistake... it is solved in version 19.0.0 with default EE...

My issue in version 19.0.0 is I created a dedicated EE to add collections and python modules.

I used this [solution](https://github.com/stanislaspiron/microk8s_awx/blob/main/EE/ansible-ee-building.md) to build it, but it seems this requires to keep following parameters to work:

```
      args:
        - ansible-runner
        - worker
```

Sorry for wasting your time.

Stanislas

**Comment by wenottingham** [comment] 2021-04-13 17:40
Closing as resolved, thanks for the feedback.

**Closed as completed by wenottingham** 2021-04-13 17:40 UTC
Labels: type:bug, component:api

**Comment by cidrbl0ck** [comment] 2023-04-20 19:37
Im encountering a problem where its either incorrect syntax in the template/playbook, or an issue with the wrong EE. I do not quite understand what @stanislaspiron was saying was his issue.

Or, possibly a third option, @ryanpetrello mentioned that Credential injectors simply do not work for Inventory source projects.
