### ISSUE TITLE
LDAP Configuration Error - Invalid key(s): "member_attr" 

### ISSUE THREAD

**Issue by glenpekarcsik** [ansible/awx#1883] opened 2018-05-15 19:39 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - API

##### SUMMARY
When trying to configure LDAP, I get the following error:

HTTP 400 Bad Request
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx-1-fgf4g
X-API-Time: 0.057s

{
    "AUTH_LDAP_GROUP_TYPE_PARAMS": [
        "Invalid key(s): \"member_attr\"."
    ]
}

As a result of this error, I can not log into AWX using LDAP credentials.  The same config works on AWX 1.0.3.

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: openshift
* Ansible version:  2.5.2
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Log into AWX
- Configured LDAP
- Logout and try to login with a LDAP user

Or 
- Log into the API - /api/v2/settings/ldap/ 
- Configured LDAP settings.
- The settings don't save unless you remove memeber_attr from AUTH_LDAP_GROUP_TYPE_PARAMS.

##### EXPECTED RESULTS
I should be able to configure LDAP and login as an LDAP user.

##### ACTUAL RESULTS
I am not able to fully configure LDAP and can't login as an LDAP user.

**Comment by wenottingham** [comment] 2018-05-15 22:34
Believe this is a duplicate of #1877 and #1855

**Comment by tumbl3w33d** [comment] 2018-06-11 15:49
It is, indeed. The workaround is described in #1855 and it's still broken in `1.0.6.15`.

**Comment by jakemcdermott** [comment] 2018-07-16 15:00
Hi glenpekarcsik,

Thanks for creating this issue. I'm closing this as it is a duplicate of the issues mentioned above: #1877 #1855. The status of this will be tracked on those issues.

**Closed as completed by jakemcdermott** 2018-07-16 15:00 UTC
Labels: type:bug, component:api, component:ui
