### ISSUE TITLE
Invoke inventory script with '--host' when '_meta' key is absent 

### ISSUE THREAD

**Issue by Cerebus** [ansible/awx#190] opened 2017-09-18 01:33 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI
 - Installer

##### SUMMARY
Ansible's scripting convention is to use the _meta key to hold host_vars when invoked with --list, but when _meta isn't present, ansible calls the inventory script for each host.  AWX does not; as a result, host_vars in the dynamic inventory are lost.

##### ENVIRONMENT
* AWX version:  1.0.0.395 
* Ansible version:  2.3.2.0
* Operating System:  CentOS 7 (AWX docker install)
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Write an inventory script that returns a vaild ansible inventory, but does not put host_vars in the _meta key.  reclass-ansible from madduck/reclass will generate an inventory like this (see also madduck/reclass#26).
2. Add the script to an AWX inventory
3. Add hosts with facts to the source inventory.
4. Sync the AWX inventory

##### EXPECTED RESULTS
Hosts should show the facts from the dynamic inventory 

##### ACTUAL RESULTS
No facts are recorded.

**Comment by Cerebus** [comment] 2017-09-18 01:48
By way of reference, see [http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#tuning-the-external-inventory-script](http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#tuning-the-external-inventory-script)

**Comment by matburt** [comment] 2017-09-18 13:34
This is how it used to work, at least. We recently moved to using `ansible-inventory` which may work differently?  What do you think @AlanCoding

**Comment by AlanCoding** [comment] 2017-09-18 13:43
`ansible-inventory` will use the `--host` option and call it repeatedly if _meta/hostvars are not given.

However, this case is not using `ansible-inventory` because Ansible version is <2.4. This is telling me that we may have a new, unanticipated, bug inside of the backport script.

Thanks for the issue, the steps to reproduce are clear, because this is a well-known legacy case with inventory importing. I will get around to testing it myself soon.

**Comment by AlanCoding** [comment] 2017-09-18 15:43
@Cerebus we have attempted to replicate this issue, but have failed to do so. Here are some details on my environment:

```
(ansible) [root@awx /]# ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

I'm using the following testing example:

https://github.com/jlaska/ansible-playbooks/blob/master/inventories/metaless_dyn_inventory.py

The expectation is that host `group_one_host_01` has the variable `group_one_host_01_has_this_var`. This variable can only be obtained by calling the script with `--host group_one_host_01`, as per this issue. After running the inventory import, I find that it is present. So it looks like this is working as it should be.

I can't easily grok what the example from `reclass` is producing. However, I would agree that you should make the change to return _meta & hostvars because of the performance arguments you noted, and just because this is the more modern way to do it.

Would you be able to produce some script contents that we could inspect for differences from our successful examples?

**Comment by Cerebus** [comment] 2017-09-19 01:31
I coded metaless_dyn_inventory.py as a reclass model.  See [https://github.com/Cerebus/reclass_metaless_dyn_inventory](https://github.com/Cerebus/reclass_metaless_dyn_inventory)

I pip install reclass on the awx_task container & copy the model directory to /home/cerebus.  I paste the contents of AWX_script.sh as a custom script (adjusting the -b path appropriately).  The inventory syncs cleanly with no errors, hosts are imported, but no facts are imported.

awx_task container environment:

ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

**Comment by Cerebus** [comment] 2017-09-19 01:59
Also pushed up reclass-ansible --list and --host group_one_host_01 output for reference.

**Comment by AlanCoding** [comment] 2017-09-19 19:24
Took me a little bit to come up to speed on all those steps, but that works for me.

![screen shot 2017-09-19 at 3 06 19 pm](https://user-images.githubusercontent.com/1385596/30610513-5cf383b8-9d4c-11e7-8f2a-2fbb3de4c6d4.png)

You can see the reclass metadata, which seems to be intended, which I confirm by testing locally to get the variables from a single host.

```
$ ./AWX_script.sh --host group_one_and_two_host_02
{
  "is_in_group_one": true,
  "inventory_vars": true,
  "complex_var": [
    {
      "something_else": [
        1,
        2,
        3
      ],
      "sourcetype": "gwaf",
      "dir": "/opt/gwaf/logs"
    }
  ],
  "__reclass__": {
    "node": "./group_one_and_two_host_02",
    "name": "group_one_and_two_host_02",
    "timestamp": "Tue Sep 19 15:09:45 2017",
    "uri": "yaml_fs:///Users/alancoding/Documents/repos/reclass_metaless_dyn_inventory/nodes/./group_one_and_two_host_02.yml",
    "environment": "",
    "applications": [],
    "classes": [
      "all",
      "group_one",
      "group_two"
    ]
  },
  "is_in_group_two": true,
  "ansible_connection": "local"
}
```

Now, I had to make a commit to the repo you shared with me, just because I needed to locate the actual directory, as well as the actual `reclass-ansible` installed on the system.

That means that I also had to shell into the container, and then install (from source) reclass inside of the Ansible virtual environment. Note that I'm using Ansible version 2.3.2.0 there (for ansible-inventory I have to use 2.4).

Here is the commit I made: https://github.com/AlanCoding/reclass_metaless_dyn_inventory/commit/e60c20139f3fe55464f6b3ae8d29ecbd97cc147a

It might also be slightly non-obvious that I had to `chmod +x` the file. Ansible needs inventory sources to be directly executable if it's a script, so if you don't have this, I don't expect that it will work (for ansible-playbook CLI or in a AWX inventory source).

**Comment by Cerebus** [comment] 2017-09-19 23:32
OK, I think I see the difference between our setup; I've *prepositioned* the inventory on the host, and used a custom script (the contents of AWX_script.sh with paths adjusted).  You've configured it as a project.

When I do that, I get an execution error:
```
2017-09-19 23:24:13,094 INFO     awx.main.commands.inventory_import Updating inventory 4: test-pull
2017-09-19 23:24:13,115 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /var/lib/awx/projects/_10__reclass_system_model_test/AWX_script.sh
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.0.395', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 107, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 955, in handle_noargs
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 210, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 179, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory backport failed (rc=1) with stdout:

stderr:
ERROR! Attempted to execute "/var/lib/awx/projects/_10__reclass_system_model_test/AWX_script.sh" as inventory script: Inventory script (/var/lib/awx/projects/_10__reclass_system_model_test/AWX_script.sh) had an execution error: No such directory: /usr/lib/python2.7/site-packages/awx/plugins/inventory/nodes
None
```
This is just an error in working directories; for whatever reason AWX_script.sh's working dir isn't being set to the project directory.

**Comment by Cerebus** [comment] 2017-09-19 23:36
My attempt to fix the $CWD error above results in `stdout capture is missing`.  Ideas?

**Comment by senorsmile** [comment] 2017-09-19 23:38
Sounds like my issue now: https://github.com/ansible/awx/issues/146  ?

**Comment by Cerebus** [comment] 2017-09-19 23:47
Personally I'm wondering why @AlanCoding 's config works, but mine doesn't.

There's still a bug in here, though--if I load the reclass model to the awx_task container filesystem by hand (rather than pull from git) and use the UI custom inventory script paste-up to invoke `reclass-ansible -b <path-to-model> $@` AWX imports the hosts but not the vars.

**Comment by AlanCoding** [comment] 2017-09-20 01:00
> use the UI custom inventory script paste-up to invoke `reclass-ansible -b <path-to-model> $@` AWX imports the hosts but not the vars.

I'm not clear about exactly what this means. Ansible takes an inventory via the `-i` option. There's no way to provide additional options (`-b <path-to-model>` in this case), but you know that, because you added the wrapper called `AWX_script.sh` in your repo, which I think exists for the purpose of adding that extra option. So when you created the inventory source in the UI, does that mean you gave the path to the file as "AWX_script.sh"? AFAIK, this won't work, but it doesn't work for me because it's not `+x`, so Ansible (via the ansible-inventory groking) will tell you that it doesn't have permission to execute the file.

If you could give more specific steps to reproduce the case where hostvars are not loaded, I think that will get us to the point of knowing what's different between how the two of us ran it.

**Comment by Cerebus** [comment] 2017-09-20 01:45
I think we keep talking past one another.  So, in more detail:

In the context of the task engine (e.g., inside the awx_task container):
1. Clone the reclass project to somewhere on the filesystem--e.g., /home/reclass
2. In the UI, create an inventory script that invokes reclass-ansible pointing at the reclass data, which passes along it's own arguments to reclass-ansible:
```
#!/bin/bash
reclass-ansible -b /home/reclass $@
```
3. Add a source to any inventory as a Custom Script, and select the script created in (2).
4. Sync the created source.

Expected results:
Host data is populated with the contents of --list, and hostvar data is populated with the contents of --hosts for each host.

Actual results:
Host data is populated, but hostvars are empty,

$@ is needed to pass --list and --host to reclass-ansible, and it seems to work, at least halfway.  Invokeing reclass-ansible *without* --list or --host returns an error, so AWX is clearly calling the custom script with --lists.  However, it never calls that script with --host (or if it does, the results are not parsed and stored).

I consider this a separate problem from the $CWD error I get when the reclass repo is added to AWX *as a Project* rather than as a custom script pointing at data outside AWX.

**Comment by AlanCoding** [comment] 2017-09-20 11:45
Sorry, I did miss that it was a custom script, as opposed to an SCM-based script.

I seem to have confirmed the bug you referenced, using the above `metaless_dyn_inventory.py` contents directly. Hosts wind up with no variables.

I will look into a fix for this.

**Comment by Cerebus** [comment] 2017-09-20 12:42
@AlanCoding Excellent, thx.

Now, any ideas on the $CWD issue w/ using reclass as a Project custom inventory?

**Comment by AlanCoding** [comment] 2017-09-20 17:33
will put up PR for the 1st bug mentioned soon.

As for the CWD, I don't have a complete answer to your question yet, but I'll put some technical notes here. The `awx-manage inventory_import` command should respect the CWD that it is called from, because we intend to allow CLI use on the AWX server. That means that the CWD for performing the import should be dictated by `awx/main/tasks.py` when it builds the context for the run. With a quick look at that, I see:

```python
    def build_cwd(self, inventory_update, **kwargs):
        return self.get_path_to('..', 'plugins', 'inventory')
```

So this looks kind of an archaic practice, where we used the best CWD for vendored scripts. Now we should probably add some logical branches to set the directory to the file's directory (inside the project folder), depending on type of `inventory_update`.

**Comment by AlanCoding** [comment] 2017-09-20 19:42
So I tried to check what the actual CWD was for the imports, and I was wrong, I believe it gets passed into the inventory import command via the private data directory. From experimentation:

 - custom: /tmp/awx_inventory_K_zoMO
 - scm: /projects/_95__inventory_cases/scripts

This is correct. The custom script is placed into a new file, inside an isolated context. The working directory of the SCM based one is inside the project folder.

> ERROR! Attempted to execute "/var/lib/awx/projects/_10__reclass_system_model_test/AWX_script.sh" as inventory script: Inventory script (/var/lib/awx/projects/_10__reclass_system_model_test/AWX_script.sh) had an execution error: No such directory: /usr/lib/python2.7/site-packages/awx/plugins/inventory/nodes

I think this is a problem with bubblewrap. We prohibit scripts reaching out to arbitrary locations in the file system as a security measure. You could try setting

```python
AWX_PROOT_ENABLED = False
```

inside of your settings file. If it works, then we know what the problem is.

**Comment by Cerebus** [comment] 2017-09-22 18:39
No dice.  Error follows:
```
2017-09-22 18:38:43,695 INFO     awx.main.commands.inventory_import Updating inventory 6: An Inventory
2017-09-22 18:38:43,707 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /var/lib/awx/projects/_14__a_project/AWX_script.sh
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.0.395', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 107, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 955, in handle_noargs
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 210, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 179, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory backport failed (rc=1) with stdout:

stderr:
Creating new namespace failed: Operation not permitted
```

**Comment by AlanCoding** [comment] 2017-09-22 19:27
That error looks like it somehow comes from bubblewrap.

https://github.com/projectatomic/bubblewrap/blob/v0.1.7/bubblewrap.c#L1832

...but you turned bubblewrap off. I think you said that for this, you were using an project-based inventory source. I don't have any explanation. I might just have to return to this later and test using an inventory source to access system resources with isolation turned off, and see if that replicates what you saw. I should also ask the standard question - you did restart the server after the setting change, right?

**Comment by matburt** [comment] 2017-09-23 01:22
Bubblewrap is disabled by default in our container configurations:

https://github.com/ansible/awx/blob/devel/installer/image_build/files/settings.py#L28-L29

By default container environments aren't super crazy about chroots and usually lack the cap for it. So if bubblewrap *is* being turned on for some reason... turn it back off.

**Comment by Cerebus** [comment] 2017-09-25 15:45
My fault; the default container config is disabled, I enabled it.  Wasn't thinking and just flipped the bit instead of paying attention to the setting.  So we're back to where we started re: $CWD.
I'll probably rebuild to start from a clean slate and try the project import method again.

**Comment by matburt** [comment] 2017-09-27 01:48
Just to be clear, are you using the awx installer and configuration applied during the installer run?

Anything else is not going to be supported and is going to make it difficult for us to help you track this down.

**Comment by matburt** [comment] 2017-10-11 03:34
It's been 14 days without a response, if you are still encountering issues or are able to provide more information then let us know.

**Closed as completed by matburt** 2017-10-11 03:34 UTC
Labels: type:bug, component:api
