### ISSUE TITLE
Auditors cannot view all Credentials

### ISSUE THREAD

**Issue by hjkatz** [ansible/awx#9178] opened 2021-01-27 19:03 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

As a User in a Team where the Team role is granted `auditor` for all Organizations in AWX, I cannot see Credentials for other Users.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: kubernetes

##### STEPS TO REPRODUCE

* As Admin:
    * Create Org Z
    * Create Org A
    * Create Team A in Org Z
    * Create Team B in Org Z
    * Add User A to Team A in Org Z
    * Grant `auditor` to Team A for Org Z
    * Grant `auditor` to Team A for Org A
    * Add User B to Team B in Org Z
* As User B: 
    * Add Credential B (Machine Type, but presumably any type would work)
    * Do _not_ grant any access, only User B should be able to see the Credential B
* As User A: (the auditor)
    * View the Credentials and attempt to see User B's credential

##### EXPECTED RESULTS

User A should be able to see User B's Credential B.

##### ACTUAL RESULTS

User A cannot see User B's Credential B.

##### ADDITIONAL INFORMATION

As I learn more about the RBAC system in AWX I get the feeling that assigning permissions to Teams is subtly broken. Here are some related issues:
* Auditors cannot view Instance Groups #9036 
* Teams cannot be granted Org Admin #9128 
* Team permissions challenges #3600

**Comment by wenottingham** [comment] 2021-01-27 19:30
That is a 'personal' credential owned by User B, and not part of any organization. It's a specific RBAC knob for credentials.

**Comment by hjkatz** [comment] 2021-01-27 20:20
How can we grant full auditor access to a Team?

**Comment by wenottingham** [comment] 2021-01-29 17:54
You want to grant system auditor to a team? It would be a singleton role mapping like system admin.

**Comment by hjkatz** [comment] 2021-01-29 18:05
Yes. We have a team of auditors and they would like to be able to audit AWX. Members of the auditor team are pulled from ldap information (SAML and Okta) so the membership to the team is flexible.

**Comment by wenottingham** [comment] 2021-01-29 18:14
You'd set that with SOCIAL_AUTH_SAML_ORGANIZATION_ATTR or AUTH_LDAP{}_USER_FLAGS_BY_GROUP today.

To do that based on teams and similar things, there is also the https://github.com/ansible/awx/issues/5303 RFE - marking as duplicate of that.

**Closed as completed by wenottingham** 2021-01-29 18:14 UTC
Labels: type:bug

**Comment by hjkatz** [comment] 2021-01-29 18:26
The use of `SOCIAL_AUTH_SAML_ORGANIZATION_ATTR` is broken, see: https://github.com/ansible/awx/issues/9128

Perhaps there are multiple issues that are reporting the same underlying problem?

**Comment by hjkatz** [comment] 2021-02-18 18:14
This is still a problem, could we reopen this ticket please? @wenottingham 

I think this same problem is related to this issue too: https://github.com/ansible/awx/issues/9036
