### ISSUE TITLE
[ui-next] Templating on empty lists and user dates when building with make ui-devel-next

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7476] opened 2020-06-29 19:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some templated strings are broken when using the command `make ui-devel-next` to build the UI.

- Notably, empty lists are broken, and "modified on date by user" strings are broken.

##### STEPS TO REPRODUCE
start your UI with `make ui-devel-next`. visit an empty list, or the details page of something like a job template.

##### EXPECTED RESULTS
normal display.
##### ACTUAL RESULTS
![Screenshot from 2020-06-29 15-29-58](https://user-images.githubusercontent.com/19942822/86049562-5f5ef580-ba20-11ea-9939-79dd94fc0e9a.png)
![Screenshot from 2020-06-29 15-26-39](https://user-images.githubusercontent.com/19942822/86049564-5f5ef580-ba20-11ea-9322-a41ccfd9ded4.png)

**Comment by jakemcdermott** [comment] 2020-06-29 19:58
duplicate of https://github.com/ansible/awx/issues/7451

**Comment by jakemcdermott** [comment] 2020-06-29 20:03
maybe not a duplicate of #7451?

**Comment by nixocio** [comment] 2020-07-06 13:06
This issue was fixed by https://github.com/ansible/awx/pull/7502.

**Closed as completed by nixocio** 2020-07-06 13:06 UTC
Labels: type:bug
