### ISSUE TITLE
Job live stream not displaying correctly

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#2378] opened 2018-10-06 04:16 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Running a playbook with roles input multiple blank lines in the live stream activity display based on number of hosts target 

##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: docker on linux
* Ansible version:  2.6.5
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Run a job with roles with several host targets in the inventory

##### EXPECTED RESULTS
<img width="790" alt="screen shot 2018-10-06 at 12 11 57 pm" src="https://user-images.githubusercontent.com/10410660/46567180-2257f300-c961-11e8-945d-46fdbe5413e1.png">

##### ACTUAL RESULTS
<img width="809" alt="screen shot 2018-10-06 at 12 14 33 pm" src="https://user-images.githubusercontent.com/10410660/46567197-74991400-c961-11e8-995b-f5e0207eb2f5.png">

**Comment by jakemcdermott** [comment] 2018-10-16 15:43
duplicate of https://github.com/ansible/tower/issues/2986

**Closed as completed by jakemcdermott** 2018-10-16 15:43 UTC
Labels: type:bug, component:ui
