### ISSUE TITLE
Possible memory leak in uwsgi ?

### ISSUE THREAD

**Issue by ewjoachim** [ansible/awx#1567] opened 2018-03-15 10:33 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
My machine running AWX has 4GB. When process start, everything is well. After a few hours/days, the web docker is filling up the RAM and random processes OOM (usually tasks because celery creates and deletes workers all the time)

If I restart the `web` docker, I'm good again for a few hours.

##### ENVIRONMENT
* AWX version: 1.0.3.58
* AWX install method: docker on linux
* Ansible version:  I guess it's irrelevant but 2.4.3.0
* Operating System: Debian
* Web Browser: N/A

##### STEPS TO REPRODUCE

From a clean instance, on a machine with 4 GB (corresponding to official recommendations)
- Define 1 organization, 2 projects, ~20 job templates
- Launch about 10 jobs per day

##### EXPECTED RESULTS

Works

##### ACTUAL RESULTS

Out of memory errors frequently, tasks marked as failed because they disappeared from the broker...

##### ADDITIONAL INFORMATION

```console
$ free -hm
              total        used        free      shared  buff/cache   available
Mem:           3,9G        3,4G        159M         97M        290M        137M
Swap:            0B          0B          0B

$ docker-compose restart web
Restarting awx_web_1 ... done
# (navigating on the website, making sure it has loaded the code)
$ free -hm                          
              total        used        free      shared  buff/cache   available
Mem:           3,9G        1,2G        2,4G         97M        324M        2,4G
Swap:            0B          0B          0B
```

I'll try to find OOM output, but, as you guess, they're exceptions when allocating stuff.

**EDIT** Forgot to mention: I've used `top` in the docker to verify that it's actually uwsgi and not daphne or nginx that's taking all the space.

**Comment by ryanpetrello** [comment] 2018-03-16 12:42
Thanks for reporting this; could we see the `top` output?

**Comment by ewjoachim** [comment] 2018-03-16 12:46
Yep. In the meantime, I've modified the supervisor configuration to only spawn 3 processes instead of 5 and limit their max requests to 100 instead of 1000 so the problem may be harder to see, but I'll let you know.

**Comment by ryanpetrello** [comment] 2018-03-16 13:12
@ewjoachim could you share what you specifically changed in the supervisord config file?  Thanks!

**Comment by ewjoachim** [comment] 2018-03-16 14:34
Yep. I'm deploying with (ansible and) Docker Compose.
I've written a copy of `supervisor.conf` as a template in my deployment script, which I've modified this way:

```jinja2
[program:uwsgi]
command = /var/lib/awx/venv/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --vacuum --processes={{ supervisor_uwsgi_processes|default(5) }} --harakiri=120 --no-orphans --master --max-requests={{ supervisor_uwsgi_max_requests|default(1000) }} --master-fifo=/var/lib/awx/awxfifo --lazy-apps -b 32768
```

I've added
```yaml
- name: deploy supervisor config file
  template:
    src: supervisor.conf.j2
    dest: "{{ docker_compose_dir }}/supervisor.conf"
```

And in my inventory:
```ini
# Supervisor configuration
supervisor_uwsgi_processes=3
supervisor_uwsgi_max_requests=100
```

And finally, in my docker-compose.yml.j2
```jinja2
  web:
  # ...
  volumes:
  - "./supervisor.conf:/supervisor.conf:ro"
  # ...
```

**Comment by ryanpetrello** [comment] 2018-03-16 15:39
Perfect - thanks!  Some folks on the awx core team are attempting to reproduce this.

**Comment by ewjoachim** [comment] 2018-03-16 17:22
Just to be clear, the OOM problem was *before* I changed the `supervisor.conf`. Now that it's changed, the problem is most probably still there, but less visible (of course, the server is capable of handling a lot less requests now)

**Comment by ryanpetrello** [comment] 2018-03-22 15:32
@ewjoachim outside of:

> Define 1 organization, 2 projects, ~20 job templates
> Launch about 10 jobs per day

...what sort of usage do you have with this install?  Would you be willing to share some of your nginx request logs before/around the time of an OOM?

I tried to reproduce this by **raising** `--max-requests=1000000` and throwing lots of requests at it, launching scores of jobs, etc... but haven't had much luck observing memory footprint growth in the uwsgi processes - I wonder if you've uncovered a certain pattern of *awx* requests that are particularly leaky.

Are your job launches doing anything interesting with _inventory_ (custom inventory scripts, inventory from a third party source, notably large inventory?)

**Comment by ewjoachim** [comment] 2018-03-22 17:41
Hm, no, ~10 inventories, all sourced from the project...

I've reset values to the original ones, and I4ll try to reproduce and get you data.

**Comment by ewjoachim** [comment] 2018-03-26 10:34
Output from `ps auxf`
[top.txt](https://github.com/ansible/awx/files/1847407/top.txt)

Nginx logs
[nginx.txt](https://github.com/ansible/awx/files/1847430/nginx.txt)

**Comment by ryanpetrello** [comment] 2018-03-26 18:43
```
~ grep -v static nginx.txt | cut -d' ' -f6-7 | sort -u

"DELETE /api/v2/authtoken/
"GET /
"GET /api/
"GET /api/v2/
"GET /api/v2/auth/
"GET /api/v2/config/
"GET /api/v2/credential_types/
"GET /api/v2/instance_groups/
"GET /api/v2/inventories/8/
"GET /api/v2/inventories/8/access_list/?page_size=20&order_by=username
"GET /api/v2/inventories/8/instance_groups/
"GET /api/v2/inventories/?page_size=20&order_by=name
"GET /api/v2/job_templates/12/launch/
"GET /api/v2/job_templates/12/survey_spec/
"GET /api/v2/job_templates/18/
"GET /api/v2/job_templates/18/launch/
"GET /api/v2/job_templates/44/launch/
"GET /api/v2/job_templates/44/survey_spec/
"GET /api/v2/job_templates/45/launch/
"GET /api/v2/job_templates/45/survey_spec/
"GET /api/v2/job_templates/?page_size=20&order_by=name
"GET /api/v2/job_templates/?page_size=20&order_by=name&search=upgrade
"GET /api/v2/jobs/1129/
"GET /api/v2/jobs/1129/extra_credentials/
"GET /api/v2/jobs/1129/job_events/?event=playbook_on_stats
"GET /api/v2/jobs/1129/job_events/?not__event__in=playbook_on_start%2Cplaybook_on_play_start%2Cplaybook_on_task_start%2Cplaybook_on_stats&order_by=start_line&page=2&page_size=200
"GET /api/v2/jobs/1129/job_events/?or__event__in=playbook_on_start%2Cplaybook_on_play_start%2Cplaybook_on_task_start%2Cplaybook_on_stats&order_by=start_line&page=2
"GET /api/v2/jobs/1129/job_events/?or__event__in=playbook_on_start%2Cplaybook_on_play_start%2Cplaybook_on_task_start%2Cplaybook_on_stats&order_by=start_line&page=3
"GET /api/v2/jobs/1129/job_events/?or__event__in=playbook_on_start%2Cplaybook_on_play_start%2Cplaybook_on_task_start%2Cplaybook_on_stats&order_by=start_line&page=4
"GET /api/v2/jobs/1129/job_events/?or__event__in=playbook_on_start%2Cplaybook_on_play_start%2Cplaybook_on_task_start%2Cplaybook_on_stats&order_by=start_line&page=5
"GET /api/v2/jobs/1129/job_events/?order_by=start_line&or__event__in=playbook_on_start,playbook_on_play_start,playbook_on_task_start,playbook_on_stats
"GET /api/v2/jobs/1129/job_events/?page_size=200&order_by=start_line&not__event__in=playbook_on_start,playbook_on_play_start,playbook_on_task_start,playbook_on_stats
"GET /api/v2/jobs/1129/labels/
"GET /api/v2/jobs/1134/
"GET /api/v2/jobs/1137/
"GET /api/v2/jobs/1140/
"GET /api/v2/jobs/1143/
"GET /api/v2/jobs/1153/
"GET /api/v2/jobs/1156/
"GET /api/v2/jobs/1160/
"GET /api/v2/jobs/1163/
"GET /api/v2/jobs/1166/
"GET /api/v2/jobs/?page_size=20&order_by=-finished&created_by=2
"GET /api/v2/users/17/admin_of_organizations/?id=2
"GET /sso/complete/
"GET /sso/complete/github-org/?redirect<redacted>&code=<redacted>&state=<redacted>
"GET /sso/login/github-org/
"GET /websocket/
"OPTIONS /api/v2/inventories/
"OPTIONS /api/v2/inventories/8/access_list/
"OPTIONS /api/v2/job_templates/
"OPTIONS /api/v2/jobs/
"OPTIONS /api/v2/jobs/1129/
"OPTIONS /api/v2/jobs/1129/job_events/
"POST /api/v2/job_templates/12/launch/
"POST /api/v2/job_templates/18/launch/
"POST /api/v2/job_templates/44/launch/
"POST /api/v2/job_templates/45/launch/
```

This seems like a _surprisingly_ low number of API requests to trigger the type of memory consumption you're seeing (I count 58).

Even less of them are actually non-`GET`:

```
~ grep -v static nginx.txt | cut -d' ' -f6-7 | sort -u | grep -iv GET
"DELETE /api/v2/authtoken/
"OPTIONS /api/v2/inventories/
"OPTIONS /api/v2/inventories/8/access_list/
"OPTIONS /api/v2/job_templates/
"OPTIONS /api/v2/jobs/
"OPTIONS /api/v2/jobs/1129/
"OPTIONS /api/v2/jobs/1129/job_events/
"POST /api/v2/job_templates/12/launch/
"POST /api/v2/job_templates/18/launch/
"POST /api/v2/job_templates/44/launch/
"POST /api/v2/job_templates/45/launch/
```

**Comment by ryanpetrello** [comment] 2018-03-26 18:47
It looks like there's a noticeable gap in usage over the weekend:

```
[23/Mar/2018:16:33:44 +0000] "GET /api/v2/jobs/1156/ HTTP/1.1" 200 3200 "-" "python-requests/2.18.4" "-"
[26/Mar/2018:07:28:30 +0000] "GET /api/v2/job_templates/18/ HTTP/1.1" 200 4553 "-" "python-requests/2.18.4" "-"
```

Do you have any evidence that suggests memory footprint growth over _that_ time period (a leak, as you've suggested)?  Or did you just notice high growth e.g., once the install was used on Monday the 26th?

**Comment by ryanpetrello** [comment] 2018-03-26 18:49
Also, do you have an idea of the scope/total count of job events for these playbooks you're running?  For example, what is the `count` value if you visit:

`/api/v2/jobs/1129/job_events/`

**Comment by ryanpetrello** [comment] 2018-03-26 18:57
@ewjoachim thanks for all your help diagnosing this; would you be willing to run uwsgi behind valgrind over a period of low usage (because it will negatively affect awx performance) to see if we can detect a slow leak?  Something like this should work if you install valgrind first:

```
[program:uwsgi]
command = valgrind --leak-check=full --log-file=/tmp/valgrind.out /var/lib/awx/venv/awx/bin/uwsgi
```

**Comment by ewjoachim** [comment] 2018-03-28 16:57
If I'm not mistaken, valgrind would also work with the modified 3 uwsgi workers ? If so, I'll try to add it :) It's ok if AWX is slow as long as it works :)

**Comment by ewjoachim** [comment] 2018-03-28 16:58
![screenshot from 2018-03-28 18-58-02](https://user-images.githubusercontent.com/1457576/38044422-fbfebbaa-32b9-11e8-9a8b-86b8d5de683c.png)

**Comment by ewjoachim** [comment] 2018-03-28 17:03
> Do you have any evidence that suggests memory footprint growth over that time period (a leak, as you've suggested)? Or did you just notice high growth e.g., once the install was used on Monday the 26th?

I have limited evidence whatsoever :/ I just noticed that after starting and warming it by logging in visiting views throughout the site, launching jobs etc, the RAM was significantly lower than what I got the next day (or there were OOMs). That lead me to **think** there is a possible memory leak, and looking at processes in htop **seems** toin point towards uwsgi as one of the most growing processes. Besides, no clues :/

Maybe 4GB is just not enough for AWX ?

I'll run valgrind and let you know.

**Comment by ryanpetrello** [comment] 2018-03-28 17:08
4GB _is_ within the bounds of what we regularly test for awx installs; it should run just fine within a server of that size.  At least, if things were OOM'ing, I wouldn't expect it to be in the uwsgi workers; we've had issues recently where the celery workers were auto-scaling past system capacity and causing OOM, but that's different than what you're describing.

Let me know if you see any meaningful valgrind results that suggest a memory leak - I took a look at uwsgi's issue list and didn't see anything promising there, but there _could_ be a latent bug you've uncovered.

**Comment by ryanpetrello** [comment] 2018-04-19 12:19
I haven't seen any other reports of evidence of this, so I'm closing it for now.  @ewjoachim let me know if you see anything else promising.

**Closed as completed by ryanpetrello** 2018-04-19 12:19 UTC
Labels: type:bug, component:api

**Comment by ewjoachim** [comment] 2018-04-19 14:14
OK.
