### ISSUE TITLE
Pg_notify / Psycop : InvalidParameterValue: payload string too long

### ISSUE THREAD

**Issue by Ghost0shell** [ansible/awx#12999] opened 2022-10-04 08:25 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I there,

We faced an issue on morning when having a huge amount of jobs pending in queue (next to a pending project update who has never started) . 

We noticed that when there are more than 500+ jobs in queue, Pg_notify is unable to push the payload in the database SELECT query because it's capped to 8000 bytes and we are over . 

Error log:
```
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 102, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 77, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/tasks.py", line 25, in task_manager
    run_manager(TaskManager, "task")
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/tasks.py", line 20, in run_manager
    manager().schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 132, in schedule
    self._schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 58, in inner
    result = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 745, in _schedule
    self.process_tasks()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 714, in process_tasks
    self.process_pending_tasks(pending_tasks)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 58, in inner
    result = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 635, in process_pending_tasks
    self.start_task(task, self.controlplane_ig, task.get_jobs_fail_chain(), execution_instance)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 58, in inner
    result = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 563, in start_task
    task_cls.apply_async(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/publish.py", line 98, in apply_async
    conn.notify(queue, json.dumps(obj))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/__init__.py", line 31, in notify
    cur.execute('SELECT pg_notify(%s, %s);', (channel, payload))
psycopg2.errors.InvalidParameterValue: payload string too long
```

An improvement to fix this problem would be to insert the payload in a specific table, and then push the key in the select function, as described in the postgres documentation : https://www.postgresql.org/docs/current/sql-notify.html#id-1.9.3.157.7.5

### AWX version

21.5.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.9.4

### Steps to reproduce

have a job queue with 500+ jobs without any running

### Expected results

Awx task manager should succeed to assign job to new automation pod .

### Actual results

nothing goes to automation pod, and psycop errors are raised in task container.

**Comment by AlanCoding** [comment] 2022-10-04 16:09
Thanks, this is a fantastic issue report. I was able to reproduce this behavior by the following steps:

 - Create a job template that allowed concurrent jobs, and had a related project with `update_on_launch` set
 - disabled all instances in my cluster
 - launched approx 242 jobs from that JT
 - re-enabled a control node

In my case the payload string was 8513 characters long. Here's what it looks like if you want to know:

```
tools_awx_1     | {"uuid": "61e6f486-e6a7-4605-a573-4466a30b8e06", "args": [54], "kwargs": {}, "task": "awx.main.tasks.jobs.RunProjectUpdate", "time_pub": 1664899614.6416256, "guid": "cd1b56799bca4535880037374acb5776", "callbacks": [{"task": "awx.main.tasks.system.handle_work_success", "kwargs": {"task_actual": {"type": "project_update", "id": 54}}}], "errbacks": [{"task": "awx.main.tasks.system.handle_work_error", "args": ["61e6f486-e6a7-4605-a573-4466a30b8e06"], "kwargs": {"subtasks": [{"type": "project_update", "id": 54}, {"type": "job", "id": 53}, {"type": "job", "id": 55}, {"type": "job", "id": 56}, {"type": "job", "id": 57}, {"type": "job", "id": 58}, {"type": "job", "id": 59}, {"type": "job", "id": 60}, {"type": "job", "id": 61}, {"type": "job", "id": 62}, {"type": "job", "id": 63}, {"type": "job", "id": 64}, {"type": "job", "id": 65}, {"type": "job", "id": 66}, {"type": "job", "id": 67}, {"type": "job", "id": 68}, {"type": "job", "id": 69}, {"type": "job", "id": 70}, {"type": "job", "id": 71}, {"type": "job", "id": 72}, {"type": "job", "id": 73}, {"
...continues...
```

**Comment by AlanCoding** [comment] 2022-10-04 21:04
I'm not going to start working on this issue, because it doesn't appear to be a new regression, and I've love to see someone else take a stab at it.

In the general, it's hazardous to submit tasks through to the dispatcher with very large (or unbounded) data in kwargs. You can see that large list under `subtasks` included in the payload. Anyway we remove that from the call pattern (even to just run the same query inside the method itself) should fix this bug just fine.

**Comment by Ghost0shell** [comment] 2022-10-05 06:37
Hi @AlanCoding , 

Thanks for having worked on my report :) . It's a particular case who's happen in specific condition, but I hope a fix will come in a future release :)

**Comment by AlanCoding** [comment] 2022-10-19 14:02
This should be fixed by https://github.com/ansible/awx/pull/13061, although it does a whole lot more than necessary for just this particular issue. Still, I'd prefer to just try and get that in.

**Comment by Cl0udius** [comment] 2022-11-29 13:04
Hi,

we also ran into this issue lately. If there is high pressure on the AWX instance, this can happen on a regular basis.
We expect our job count the rise in the future. 
So it would be good to know if  https://github.com/ansible/awx/pull/13061 is the only way which will fix the issue or if there is some workaround here.
If there is just https://github.com/ansible/awx/pull/13061, the question which came to my mind was: is it realistic that it will be introduced in 21.10 or 21.11?

BR

**Comment by AlanCoding** [comment] 2022-11-29 15:04
No, I'm abandoning https://github.com/ansible/awx/pull/13061

We need a simple, targeted, fix. It's not a difficult fix, and I consider this medium/high priority.

**Comment by Cl0udius** [comment] 2022-12-19 11:56
Hi. Is there a dedicated PR for this? And what will be the approach here? Will there be a split into multiple chunks which will then be queried in more than one query?

**Comment by AlanCoding** [comment] 2022-12-19 14:03
I'll get back to this soon. The parameter that's too long are `errbacks`. There's no reason to pass that in the method parameters, because it comes from the database we can obtain it inside the method, and axe the parameter entirely.

**Closed as completed** 2023-01-13 12:06 UTC
Labels: type:bug, component:api, community
