### ISSUE TITLE
Grouping Templates

### ISSUE THREAD

**Issue by tonysymbox** [ansible/awx#11293] opened 2021-10-29 14:48 UTC
##### ISSUE TYPE
 - Group templates into folders

##### SUMMARY

It would be nice if we could group templates into "folders" to help from an organization point of view.

An example is we have multiple customers in one organization, grouping specific templates in a customer folder would really help us organize things better.

Thanks

**Comment by shanemcd** [comment] 2021-10-29 17:08
This is a duplicate of https://github.com/ansible/awx/issues/2058

**Closed as completed by shanemcd** 2021-10-29 17:08 UTC
