### ISSUE TITLE
Workflow Editor does not save.

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1480] opened 2018-03-08 20:36 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- UI

##### SUMMARY
Workflow editor traceback when doing normal things to the workflow editor.

##### STEPS TO REPRODUCE

* Create a workflow
* Add a Job Template as the first node
* save

##### EXPECTED RESULTS

* To save and close the workflow editor

##### ACTUAL RESULTS

* Traceback

##### ADDITIONAL INFORMATION

*  Seems to be related to the JT Inventory Prompt on Launch setting.
* Also, when I have Credential prompt on launch and I set a default Cred (in the JT) should the workflow Credential box be auto-filled by the default set cred? That seems to be how the inventory logic works.

```
TypeError: Cannot read property 'id' of undefined
    at buildSendableNodeData (workflow-maker.controller.js:123)
    at recursiveNodeUpdates (workflow-maker.controller.js:182)
    at workflow-maker.controller.js:321
    at arrayEach (index.js:1361)
    at Function.<anonymous> (index.js:3405)
    at Scope.$scope.saveWorkflowMaker (workflow-maker.controller.js:320)
    at fn (eval at compile (angular.js:15651), <anonymous>:4:171)
    at callback (angular.js:27475)
    at Scope.$eval (angular.js:18542)
    at Scope.$apply (angular.js:18641)
```

**Comment by mabashian** [comment] 2018-03-28 18:20
I'm not able to reproduce this currently.  I suspect that one of my workflow-related PRs over the past couple weeks addressed this issue.

**Comment by jaredevantabor** [comment] 2018-05-17 20:50
This is fixed now in devel.

**Closed as completed by jaredevantabor** 2018-05-17 20:50 UTC
Labels: type:bug, component:ui
