### ISSUE TITLE
RFE: Allow one to label nodes in the Workflow Visualizer

### ISSUE THREAD

**Issue by Spredzy** [ansible/awx#5824] opened 2020-02-05 15:11 UTC
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

![Screenshot_2020-02-05 Ansible Tower templates editWorkflowJobTemplate workflowMaker(2)](https://user-images.githubusercontent.com/1191411/73853830-c8f02480-4831-11ea-9301-eca918a4b709.png)

Current behavior is for node to display the Job Template name. Job Template can be generic enough to be used with different parameters. The current behavior leads to unclear workflow meaning.

For example in the above use case the "Create Github Branch" as a survey spec with a string where one can specify a repository. With current behavior the Workflow Visuzalizer offer 4 times the same representation. It would benefit user to be able to label node with value they want. In the case above we could have specified in the label the repository we are talking about, making the intent and lecture of the workflow straight forward.

**Comment by AlanCoding** [comment] 2020-03-24 18:52
I'm going to close this as a duplicate of https://github.com/ansible/awx/issues/2032, because it does say the same thing, and there's more history there.

**Closed as completed by AlanCoding** 2020-03-24 18:52 UTC
Labels: component:api
