### ISSUE TITLE
Failed to resolve broker hostname

### ISSUE THREAD

**Issue by ghost** [ansible/awx#6456] opened 2020-03-27 05:33 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After installing AWX using docker-compose and the provided installer, I am getting an error when trying to run a job.

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker-compose for mac
* Ansible version:  2.9.5
* Operating System: macOS Catalina
* Web Browser: Safari

##### STEPS TO REPRODUCE

1. Install AWX using docker-compose for mac
2. Login web interface (http://localhost)
3. Add inventory, Project, Credential, Job Template
4. Launch Job Template 

##### EXPECTED RESULTS

Successfully finish Job

##### ACTUAL RESULTS

Getting the following error on Safari: "Call to /api/v2/jobs/10/relaunch/ failed. returned status: 504."

Seeing the following error on awx_task:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 148, in _connect
    "failed to resolve broker hostname"))
OSError: failed to resolve broker hostname

**Comment by jakemcdermott** [comment] 2020-03-27 13:05
Hello. 

Duplicate of https://github.com/ansible/awx/issues/6376 - have a look for more details on this. Thanks!

**Closed as completed by jakemcdermott** 2020-03-27 13:05 UTC
Labels: type:bug
