### ISSUE TITLE
Insights tab through HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/awx#3103] opened 2019-01-30 04:54 UTC
##### ISSUE TYPE
 - The Insights tab in Tower doesn't use the proxy configuration set through AWX_TASK_ENV. Adding it to the supervisord.conf works. 

##### COMPONENT NAME

 - UI

##### SUMMARY

We need a general approach for proxy configuration in Tower. Currently adding it to the supervisord.conf works for UI elements of Tower like the Insights Tab.

For example:
~~~
[supervisord]
environment=http_proxy=http://172.31.22.144:8080,HTTP_PROXY=http://172.31.22.144:8080,https_proxy=http://172.31.22.144:8080,HTTPS_PROXY=http://172.31.22.144:8080,no_proxy=127.0.0.1,NO_PROXY=127.0.0.1
~~~

Also related #3072 #2818

**Comment by wenottingham** [comment] 2020-02-10 17:19
See https://github.com/ansible/awx/pull/5846, this should respect AWX_TASK_ENV now.

**Comment by kdelee** [comment] 2020-03-05 21:40
@ryanpetrello @wenottingham @one-t @elyezer 

I'm not quite sure where to start on verifying this one. Can any of y'all flesh out some reproducer steps for what expected behavior and actual behavior was? 

linking https://docs.ansible.com/ansible-tower/latest/html/userguide/insights.html here because I know at least that we will have to set up an insights credential, project, inventory and perhaps a scan job to get the hosts that end up with the insights tab

**Comment by wenottingham** [comment] 2020-03-05 22:07
1) set up the insights integration on a tower
2) disconnect it from the public internet, make it use a proxy for that
3) see if adding the proxy definition to AWX_TASK_ENV makes it work

**Comment by kdelee** [comment] 2020-03-18 20:19
@one-t @nixocio and I did this
1. set up squid proxy (see http://www.squid-cache.org/ )
2. Configured tower to use the squid proxy
3. set up insights rigamarole :expressionless: 
4. test insights tab on hosts, show we get expected response from insights
5. turn off proxy, confirm we get error because can't reach out to it
6. turn it back on, confirm still works.

Closing!

**Closed as completed by kdelee** 2020-03-18 20:19 UTC
Labels: type:enhancement, component:api
