### ISSUE TITLE
Error starting pods in installation openshift

### ISSUE THREAD

**Issue by dmaleno** [ansible/awx#3312] opened 2019-02-26 07:37 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: openshift
* Ansible version:  2.6.4
* Operating System: CENTOS 7.5
* Web Browser:

##### STEPS TO REPRODUCE

ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS
awx-manage migrate command works correctly

##### ACTUAL RESULTS
django.core.exceptions.ImproperlyConfigured: 'awx.main.db.profiled_pg' isn't an available database backend.

##### ADDITIONAL INFORMATION

This module is not present in awx_task image 3.0.1 from docker hub.
/etc/tower/conf.d/..2019_02_25_21_07_02.256334588/secrets.py conatains reference to this module 'ENGINE': 'awx.main.db.profiled_pg'

**Comment by ryanpetrello** [comment] 2019-02-26 13:01
If you're installing from `devel`, you need to build your own image.  See: https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images

Duplicate of https://github.com/ansible/awx/issues/3250

**Closed as completed by ryanpetrello** 2019-02-26 13:01 UTC
Labels: type:bug, component:installer
