### ISSUE TITLE
Unable to login when password contains an ampersand

### ISSUE THREAD

**Issue by pandino** [ansible/awx#1553] opened 2018-03-14 10:49 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

  - UI
 

##### SUMMARY

When creating an user, her password can contain any character. However if it contains an ampersand (&) she is unable to login. I initially found this problem because I had LDAP login issues but I think the issue is in the login form that sends the password unescaped:
    
`username=test&password=change&me&csrfmiddlewaretoken=mgD3vBr2EqlJ3eH4jxOavMoItFL02PE8Jd9bl5aR1ey7mHo1GM6Vft9eBKQqnfq6&next=%2fapi%2f`

In this example the user was created with password `change&me`. 

##### ENVIRONMENT
* AWX version: 1.0.4.48
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System:
* Web Browser: Chrome 64.0.3282.186

##### STEPS TO REPRODUCE

- Create a new user with username `test` and set her password `change&me`
- Go to the AWX login page and try to login with these credentials.

##### EXPECTED RESULTS

The login succeeds.

##### ACTUAL RESULTS

The login fails with the error: `Invalid username and/or password. Please try again.`

**Comment by mkempster22** [comment] 2018-03-14 12:45
I think this may be apparent with other characters as well. I had set a user password with these characters in it:  ,#];[  And one of these caused the same issue you were having, interestingly the same user on my production awx server, which is on an older version of awx, had that password and could log in

**Comment by ryanpetrello** [comment] 2018-03-14 14:55
I'm able to reproduce this in the UI login, but not with basic auth.

```
curl -sik "https://joe:joe&joe@<awx-host>/api/v2/jobs/" | head
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Wed, 14 Mar 2018 14:54:22 GMT
Content-Type: application/json
Content-Length: 2871
...
```

OAuth2 personal token acquisition also seems to work fine; this looks like it's strictly a UI issue to me.

**Comment by ryanpetrello** [comment] 2018-03-14 14:56
![screen shot 2018-03-14 at 10 56 19 am](https://user-images.githubusercontent.com/214912/37410143-56e8b416-2776-11e8-9939-fc19eb689086.png)

The request sent by the UI is building the form-encoded data string unescaped.

**Comment by jlmitch5** [comment] 2018-03-14 15:30
@Pandino fixed in devel, thanks for bringing to our attention!

**Closed as completed** 2018-03-14 15:29 UTC
Labels: type:bug, component:ui
