### ISSUE TITLE
Error when deleting multiple inventory source sync jobs at one time

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10272] opened 2021-05-25 21:33 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This must be done with a jobs list that has data already populated. 
When syncing a source inside of an inventory multiple times (I did 4 in my manual test), and going to the Jobs List page, after waiting for them to finish syncing, click the check mark next to all 4 jobs and click delete. Instead of returning the remaining job list history, it returns a page saying No Jobs Found

##### STEPS TO REPRODUCE
![inventory-source-issue](https://user-images.githubusercontent.com/63685497/119571303-330e3f00-bd7f-11eb-8009-2d4f6552fe64.gif)

##### EXPECTED RESULTS

After deleting the sync jobs, the UI would return the remaining list of jobs

##### ACTUAL RESULTS

the UI returns a message saying No Jobs Found. Upon refresh, the jobs then appear.

**Comment by AlexSCorey** [comment] 2021-06-28 15:40
I wasn't able to reproduce this consistently.  I did get this error on occasion when deleting inventory source sync jobs, but also a when deleting a mixture of different kinds of jobs.

**Comment by nixocio** [comment] 2021-08-11 19:03
~Possible related to: https://github.com/ansible/awx/issues/9013~

**Comment by nixocio** [comment] 2021-09-21 14:25
The issue here seems to be a performance issue. Once the Job list has several jobs running/pending/successful attempt to delete several jobs. The list does not re-render to the initial amount of jobs.

1  - Create a Workflow with several nodes, 10 nodes - job templates.
2  - Trigger this Workflow run
3 - Trigger other jobs, inventory source, for example.
4 - Attempt to delete a few successful jobs.
5 - List should render back displaying all remaining jobs, sometimes this does not happen.

![Job](https://user-images.githubusercontent.com/9053044/134189117-e74b8f60-d44e-4b2e-8aa9-43966c60fac4.gif)

**Comment by InnocentK** [comment] 2021-10-08 17:25
Resolved in #11209

**Closed as completed by InnocentK** 2021-10-08 17:25 UTC
Labels: type:bug, component:ui
