### ISSUE TITLE
Permissioning System Broken

### ISSUE THREAD

**Issue by KyleTheAutomator** [ansible/awx#1856] opened 2018-05-07 19:57 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API?
 - UI

##### SUMMARY

I initially thought this might be something related to the ldap implementation but I created a local test user, test team, test project.  I am unable to assign the test user to the team or permission the test user to the project (UI accepts inputs but changes don't result in the user being added/permissioned to the object).  Same holds true for users/teams created from ldap.

Update: It appears I'm getting a 403 on the POST even though I'm logged into a super user account.
`{"detail":"You do not have permission to perform this action."}`

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System:  Ubuntu 16.04
* Web Browser:  Chrome

##### STEPS TO REPRODUCE
Create a local user.  Create a test org, project, team, and template.  Attempt to add user to team (UI accepts inputs as normal but no changes are made to perms).  Attempt to add user perms to the test template (UI accepts inputs as normal but no changes are made to perms).

##### EXPECTED RESULTS
The desired permission assignment should be revealed through the UI or throw an exception.

##### ACTUAL RESULTS
Permission assignments don't persist.

##### ADDITIONAL INFORMATION
I first noticed this behavior after I had configured ldap.  Unsure if this is a prereq to reproducing this issue.

**Comment by jaevans** [comment] 2018-05-09 20:06
We are noticing this in our environment too, also AWX 1.0.6.5, using LDAP. It appears that granting individual users sticks, but teams does not. 

What's interesting is that teams can see the object (such as a Job Template) until they try to launch the job, then they get a permission denied error, and lose visibility. As far as I can tell, the role object still exists, and is still referenced from the job_template. That's from digging around in the API browser.

**Comment by wenottingham** [comment] 2018-05-15 16:52
Likely a duplicate of https://github.com/ansible/awx/issues/1868

**Comment by wenottingham** [comment] 2018-05-17 13:47
Closing as duplicate.

**Closed as completed by wenottingham** 2018-05-17 13:47 UTC
Labels: type:bug, component:api

**Comment by madeinoz67** [comment] 2018-05-21 12:51
As mentioned in #1868 I'm still seeing permission errors when trying to add any type of object to a team under any group, LDAP or manually managed.

Only error reported in JSConsole is permission error as screenshot below

![2018-05-21_20-06-29](https://user-images.githubusercontent.com/4160293/40308392-b633c378-5d38-11e8-80bd-5648278896b3.png)
