### ISSUE TITLE
docker-compose upgrading from previous versions to 14.0.0 is broken (awx_postgres container)

### ISSUE THREAD

**Issue by JoelKle** [ansible/awx#7906] opened 2020-08-14 07:37 UTC
The PR #7698 broke the ability to do a seamless upgrade. I've tried to upgrade from AWX version 13.0.0 to 14.0.0 following the docs:
https://github.com/ansible/awx/blob/devel/INSTALL.md#upgrading-from-previous-versions

After I rerun the installer playbook in version 14.0.0, my `awx_postgres` Container reported the following error:
```
initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".
```

Looks like the `docker-compose` command don't use to the new volume?
Got the following warning when I tried to manually stop and start the `awx_postgres` container:
```
$ docker-compose stop postgres
$ docker-compose up -d postgres
Recreating awx_postgres ... 
WARNING: Service "postgres" is using volume "/var/lib/postgresql/data" from the previous container. Host mapping "/var/lib/docker-shared/awx/postgres_pg_data/10/data" has no effect. RemoRecreating awx_postgres ... done
```

I could only solve this problem using the following commands:
```
$ docker-compose stop
$ docker-compose up -d --renew-anon-volumes
```
But this is currently not part of the installer playbook.

If this bug is not solved maybe this will help other to do a upgrade.

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
docker-compose upgrading from previous versions to 14.0.0 is broken (awx_postgres container)

##### ENVIRONMENT
* AWX version: from 13.0.0 to 14.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.11
* Operating System: Debian
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Do a upgrade from AWX version 13.0.0 to version 14.0.0 using the docker installer variant.

##### EXPECTED RESULTS

Seamless upgrade without manually investigation.

##### ACTUAL RESULTS

Container `awx_postgres` did not start at all.

**Comment by Scorpslay** [comment] 2020-08-14 12:29
I too have been getting this error.  I tried changing my `postgres_data_dir` to a clean directory and I get the same issue.  The `awx_postgres` container is in a continual loop restarting itself with the error mentioned in this issue.

**Comment by jmaughmer** [comment] 2020-08-14 15:10
I also had the same issue.

This was addressed under the following thread:  https://github.com/ansible/awx/issues/7854

**Comment by ryanpetrello** [comment] 2020-08-17 13:47
Duplicate of https://github.com/ansible/awx/issues/7854

**Closed as completed by ryanpetrello** 2020-08-17 13:47 UTC
Labels: type:bug
