### ISSUE TITLE
AWX throwing a 502 and job details not loading

### ISSUE THREAD

**Issue by josemgom** [ansible/awx#2386] opened 2018-10-09 10:19 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Job details are not showed in the UI. When trying to access to the job details, the browser starts to throw a 502 error when trying to access websocket.

##### ENVIRONMENT
* AWX version: 1.0.6.11
* AWX install method: Docker on Linux
* Ansible version:  2.5.3
* Operating System: CentOS 7
* Web Browser: Firefox / Chrome / Edge 

##### STEPS TO REPRODUCE

Run any playbook, failed and succeeded jobs are present but not showing any details.

##### EXPECTED RESULTS

Job status view should load with all details.

##### ACTUAL RESULTS

AWX is not showing anything. If you open the developer tools, you can see a 502 error when trying to access websocket.

**Comment by ryanpetrello** [comment] 2018-10-09 13:12
Likely a duplicate of https://github.com/ansible/awx/issues/1861

**Comment by josemgom** [comment] 2018-10-09 13:16
> Likely a duplicate of #1861

Yeah, looks similar, but the "solution" proposed by one of the users, is not working for me. My container is not bound to 127.0.0.1, in my case is to 0.0.0.0. The only solution that works for me, is restarting all the containers.

**Comment by ryanpetrello** [comment] 2018-10-09 13:24
Understood - this is an issue that we're still hearing about periodically, and currently looking for more data on.  Can you share any details about your usage of awx when this occurs?  How many active users?  Any notable errors in the files in `/var/log/tower/*.log` around the time you see failures?

**Comment by josemgom** [comment] 2018-10-09 13:38
Of course.

There is no log in /var/log/tower/*.log. But I cannot see something relevant in docker logs.

Active users(concurrent): No more than 2-3 users.
Usage: We are using AWX to restart services, run puppet or upgrade packages.  

This can happen with small and big inventories and running a single job template.

**Comment by ryanpetrello** [comment] 2018-10-09 17:06
Thanks for the feedback.  Would you mind taking a look at this comment and giving it a try?

https://github.com/ansible/awx/issues/1861#issuecomment-428268360

**Comment by ryanpetrello** [comment] 2018-10-11 16:55
Closing as a duplicate: 
https://github.com/ansible/awx/issues/1861#issuecomment-429033776

**Closed as completed by ryanpetrello** 2018-10-11 16:55 UTC
Labels: type:bug, component:ui
