### ISSUE TITLE
Playbooks terminated unexpectedly after 4 hours

### ISSUE THREAD

**Issue by spireob** [ansible/awx#11805] opened 2022-02-24 12:29 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Playbooks running longer than 4 hours are terminated unexpectedly. The Jobs finish with error state in GUI.
The exit code "137"
Same issue : [closed](https://github.com/ansible/awx/issues/11594) without resolution.
Tested on versions: AWX 19.4.0  and AWX 20.0.0  

### AWX version

20.0.0

### Select the relevant components

- [ ] UI
- [x] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

yes

### Ansible version

core 2.13.0.dev0

### Operating system

CentOS8

### Web browser

Chrome

### Steps to reproduce

---
- hosts: all
  gather_facts: no

  tasks:

  - name: Run Job
    shell: | 
          while(1){
            Write-Output "."
            start-sleep -seconds 1800
          }
    args:
      executable: /usr/bin/pwsh
    async: 43200
    poll: 900
    register: pwsh_output_job
    ignore_errors: true

### Expected results

Playbook completes successfully

### Actual results

Container running the job is terminated after running for 4 hours

### Additional information

exitCode: 137

**Comment by spireob** [comment] 2022-03-17 08:53
Anything new in this topic?

**Comment by meis4h** [comment] 2022-04-28 13:01
Hi, we are also seeing this issue on K3s using AWX 19.5.0 and 21.0.0.
A few things we observed looking at this:
- Jobs fail after the last task over the 4 hour mark has completed
  - for example a wait_for task with a timeout of 8 hours causes the job to fail with error after 8 hours, a 5 hour task fails after 5 hours
- The limit seems to be pretty much exactly 4 hours as jobs running 3h 50min complete successfully
- Jobs are not continued in the background as the Pod is deleted instantly after the job errors
- Also happens with job timeout set in the job template

**Comment by kladiv** [comment] 2022-04-28 18:59
@spireob maybe you can check below
- https://github.com/ansible/awx/issues/9961
- https://github.com/ansible/awx/issues/11338
it could be related to that issues.

I've the same issue of 4hrs jobs end with errors (in k3s)

**Comment by d-rupp** [comment] 2022-05-19 14:01
We also encounter an issue like this regularly. It seems awx-task just decides that the job is done and kills the pod.

This is what i find in the awx-task log:
```
2022-05-19 13:20:17,503 INFO     [3abf5855276042c595518de57f670161] awx.main.commands.run_callback_receiver Event processing is finished for Job 15161, sending notifications
2022-05-19 13:20:17,503 INFO     [3abf5855276042c595518de57f670161] awx.main.commands.run_callback_receiver Event processing is finished for Job 15161, sending notifications
2022-05-19 13:20:18,107 DEBUG    [3abf5855276042c595518de57f670161] awx.main.tasks.jobs job 15161 (running) finished running, producing 382 events.
2022-05-19 13:20:18,107 DEBUG    [3abf5855276042c595518de57f670161] awx.main.dispatch task c950003b-4c05-49d1-9b45-43e671098931 starting awx.main.tasks.system.handle_success_and_failure_notifications(*[15161])
2022-05-19 13:20:18,109 DEBUG    [3abf5855276042c595518de57f670161] awx.analytics.job_lifecycle job-15161 post run
2022-05-19 13:20:18,238 DEBUG    [3abf5855276042c595518de57f670161] awx.analytics.job_lifecycle job-15161 finalize run
2022-05-19 13:20:18,342 WARNING  [3abf5855276042c595518de57f670161] awx.main.dispatch job 15161 (error) encountered an error (rc=None), please see task stdout for details.
2022-05-19 13:20:18,345 DEBUG    [3abf5855276042c595518de57f670161] awx.main.tasks.system Executing error task id ecbb37f9-809d-4317-9d01-af93846de8d6, subtasks: [{'type': 'job', 'id': 15161}]
```

All the while the task output just says "canceled". 
If there is anything i can help analyse this please tell me what to do. 

It is not related to the linked issues above.

*edit: sorry, missing data about the system

AWX: 21.0.0 running on K3S v1.23.6

**Comment by adpavlov** [comment] 2022-06-02 10:04
exactly same issue

**Comment by meis4h** [comment] 2022-06-02 12:34
can confirm that this also happens on RedHat Ansible Automation Platform 2.1 on OpenShift 4.8

**Comment by adpavlov** [comment] 2022-06-02 12:47
> can confirm that this also happens on RedHat Ansible Automation Platform 2.1 on OpenShift 4.8

Have you opened a case to RedHat?

**Comment by meis4h** [comment] 2022-06-02 12:48
> > can confirm that this also happens on RedHat Ansible Automation Platform 2.1 on OpenShift 4.8
> 
> Have you opened a case to RedHat?

yes but no news yet

**Comment by adpavlov** [comment] 2022-06-02 12:56
> > > can confirm that this also happens on RedHat Ansible Automation Platform 2.1 on OpenShift 4.8
> 
> > 
> 
> > Have you opened a case to RedHat?
> 
> 
> 
> yes but no news yet

Okay, could you please keep us posted on this case status? Also there should be SLA for paid subscription. Issue is quite critical as for me.

**Comment by meis4h** [comment] 2022-06-02 13:04
> Okay, could you please keep us posted on this case status? Also there should be SLA for paid subscription. Issue is quite critical as for me.

Will do.
In the meantime we could largely work around the issue by splitting the job into multiple separate jobs connected via workflow.

**Comment by kiril18** [comment] 2022-06-02 13:09
I got a similar problem today, after four hours the task fell.

**Comment by adpavlov** [comment] 2022-06-02 13:15
> @spireob maybe you can check below
> 
> - https://github.com/ansible/awx/issues/9961
> 
> - https://github.com/ansible/awx/issues/11338
> 
> it could be related to that issues.
> 
> 
> 
> I've the same issue of 4hrs jobs end with errors (in k3s)

For my installation I don't believe it's k3s related as I have a 500 Mb limit for logs. More than that I don't even see log files created under /var/log/pods/, just empty folders.

Also I'm using custom EE built with ansible 2.9 as suggested in some @AlanCoding repo, so I believe the issue is not related to ansible-runner, but related to awx-task that seems like have some timeout for waiting output from a task.

**Comment by cmatsis** [comment] 2022-06-08 07:24
Same issue on AWX: 21.0.0 running on K3S v1.23.6 :( 
any workaround to this problem?

**Comment by stefanpinter** [comment] 2022-06-17 06:36
same problem with awx 21.1.0 & k3s v1.21.7+k3s1
for now, where I "know" that the last task ends like it should, I re-run the playbook with the remaining tags only

well, I can only assume that the last task ended without error, as I don't see an "ok", "changed" or "failed"....

**Comment by adpavlov** [comment] 2022-06-17 10:03
> > Okay, could you please keep us posted on this case status? Also there should be SLA for paid subscription. Issue is quite critical as for me.
> 
> Will do. In the meantime we could largely work around the issue by splitting the job into multiple separate jobs connected via workflow.

@meis4h Is there any news from support?

**Comment by cmatsis** [comment] 2022-07-06 08:11
Does this problem occur in the paid version and there is no solution?
There are few people working more than 4 hours?

**Comment by 3zAlb** [comment] 2022-08-01 14:28
We are also having this issue running the latest AWX, k3s, and docker backend.  Container log size is set to 500mb and allowed to have 4 files.  (Single log file is generated and gets nowhere near 500mb)

This is a pretty big show stopper for long running maintenance playbooks. 

Can we get an update on this?  This issue has been open since February and i've seen numerous closed issues with the same problem.

**Comment by NadavShani** [comment] 2022-08-01 16:03
> We are also having this issue running the latest AWX, k3s, and docker backend. Container log size is set to 500mb and allowed to have 4 files. (Single log file is generated and gets nowhere near 500mb)
> 
> This is a pretty big show stopper for long running maintenance playbooks.
> 
> Can we get an update on this? This issue has been open since February and i've seen numerous closed issues with the same problem.

same here

**Comment by StefanSpecht** [comment] 2022-08-01 16:15
We have exactly the same issue.

**Comment by adpavlov** [comment] 2022-08-03 21:27
> > > Okay, could you please keep us posted on this case status? Also there should be SLA for paid subscription. Issue is quite critical as for me.
> > 
> > 
> > Will do. In the meantime we could largely work around the issue by splitting the job into multiple separate jobs connected via workflow.
> 
> @meis4h Is there any news from support?

@meis4h could you please update?


Also lets probably call active developers like @AlanCoding 😅

**Comment by meis4h** [comment] 2022-08-04 05:38
@adpavlov sadly there is nothing new to report 😕​

**Comment by lals1** [comment] 2022-08-08 11:06
exactly same issue

**Comment by auracz** [comment] 2022-08-22 11:07
exactly same issue
![image](https://user-images.githubusercontent.com/77057370/185906995-121fe62f-6c8e-4109-852e-3993007ab4c1.png)

**Comment by backaf** [comment] 2022-08-26 12:16
Same issue here. Upgraded to the latest AWX version this morning but it still occurs. Use case is running restic prune commands which take a long time to complete.

Env:
* on-prem k8s 1.23.5
* awx operator 0.28.0
* awx 21.5.0

**Comment by bartowl** [comment] 2022-09-08 06:47
Same here. Does the apparent 4h limit affect the entire job template, or just a single task? Maybe using async tasks would be a way around here? What is bad is that the automation pod gets removed with all information what has happened, and the task container just throws EOF handler like with normal job end:
```
2022-09-07 17:14:27,661 INFO     [3c69d3938c974b689cc1cdb49acadf04] awx.main.commands.run_callback_receiver Starting EOF event processing for Job 2076
2022-09-07 17:14:27,661 INFO     [3c69d3938c974b689cc1cdb49acadf04] awx.main.commands.run_callback_receiver Starting EOF event processing for Job 2076
2022-09-07 17:14:28,591 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.tasks.jobs job 2076 (running) finished running, producing 80 events.
2022-09-07 17:14:28,595 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.analytics.job_lifecycle job-2076 post run
2022-09-07 17:14:28,937 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.analytics.job_lifecycle job-2076 finalize run
2022-09-07 17:14:28,957 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.dispatch task f1c62c03-fdca-45d8-8363-a66710f19910 starting awx.main.tasks.system.update_inventory_computed_fields(*[3])
2022-09-07 17:14:28,977 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.models.inventory Going to update inventory computed fields, pk=3
2022-09-07 17:14:28,999 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.models.inventory Finished updating inventory computed fields, pk=3, in 0.022 seconds
2022-09-07 17:14:29,144 WARNING  [3c69d3938c974b689cc1cdb49acadf04] awx.main.dispatch job 2076 (error) encountered an error (rc=None), please see task stdout for details.
2022-09-07 17:14:29,200 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.dispatch task 4671db40-b07f-47e5-8810-bfb76ee45d8d starting awx.main.tasks.system.handle_work_error(*['4671db40-b07f-47e5-8810-bfb76ee45d8d'])
2022-09-07 17:14:29,201 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.tasks.system Executing error task id 4671db40-b07f-47e5-8810-bfb76ee45d8d, subtasks: [{'type': 'job', 'id': 2076}]
2022-09-07 17:14:29,224 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.dispatch task 4671db40-b07f-47e5-8810-bfb76ee45d8d starting awx.main.tasks.system.handle_work_success(*[])
2022-09-07 17:14:29,224 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.dispatch task aefe7820-cf95-4baf-9cfe-f25cf5d5cde4 starting awx.main.scheduler.tasks.run_task_manager(*[])
2022-09-07 17:14:29,224 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.scheduler Running task manager.
2022-09-07 17:14:29,238 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.scheduler Starting Scheduler
2022-09-07 17:14:29,248 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.dispatch task 83ec5dcb-f7c1-4fdc-829e-2bfb1c72e34b starting awx.main.scheduler.tasks.run_task_manager(*[])
2022-09-07 17:14:29,248 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.scheduler Running task manager.
2022-09-07 17:14:29,262 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.scheduler Not running scheduler, another task holds lock
2022-09-07 17:14:29,272 DEBUG    [3c69d3938c974b689cc1cdb49acadf04] awx.main.scheduler Finishing Scheduler
```
This does not differ from normal job termination due to task error. The thing is, that last task that took so long has no json nor output available.
What is weird though, the long running task performed its action and AWX could just run next task. So startint with start-at-task would allow to continue here. I wonder where does the time limit hit.

**Comment by bartowl** [comment] 2022-09-12 11:46
Well, async tasks did not help at all... 4:01 and job template fails. Seems that the automation container gets just terminated, but I would not blame k8s for that, since there are many different distributions (i use k3d) and all fail precisely after 4h. My last job with async_status poll every 5 minutes terminated at exact 4:01:22 after 7 retries - could not perform next retry.... I will try to trace that from inside automation pod as well as from k8s perspective... check also source code for that... this is really weird.

**Comment by bartowl** [comment] 2022-09-12 13:14
Hmm - I quess I found the reason - kubelet by default terminates streaming connections after 4h. Streaming automation pod logs is a streaming connection. See https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ and search for "--streaming-connection-idle-timeout". I once again checked all messages in this Issue, and everyone has a variant of k3s / k3d. This options seems to only work for docker backend. K3d uses containerd-shim-runc-v2 and I have found an Issue for containerd exactly regarding this https://github.com/containerd/cri/issues/1057
One might try to increase this timeout somehow... maybe this will be a workaround... But a permanent solution would be to reimplement AWX part that uses those streaming connections to re-try closed ones instead of assuming that the connection got closed == container finished its work. I cannot track that part in the source code :/

**Comment by adpavlov** [comment] 2022-09-12 23:15
I would call you a genius:)
However, I set this timeout of k8s to 0 (meaning no timeout) in my k3s installation and pod survived 4 hours 27 minutes! But still resulted in Error...

**Comment by bartowl** [comment] 2022-09-14 08:56
Sadly yes, as k3s with containerio backend seems to ignore this parameter and you would need to switch to docker backend somehow. I would also if I only knew how, and adding `--docker` to kubelet arguments what should do the trick does not give any usefull effect besides log entries that this is legacy and will be ignored (used `--kubelet-arg=docker@server:0` actually)
See also https://github.com/k3s-io/k3s/issues/1936 ...
But as already written - the problem is not that kubelet/k3s do not support removing this timeout, the main Problem is, that AWX does not try to re-connect to logs output after the stream gets closed. There should be for sure a retry mechanism and proper verification if the pod just disconnected or is really done and closed. I hope this will be fixed with this Issue. All other options are just vague workarounds... Interestingly this seems also to be the problem with the commercial AWX version, or can it handle jobs running longer than 4h on k3s/k3d with crio backend?

**Comment by adpavlov** [comment] 2022-09-14 09:03
I'm using docker backend actually and passed `--kubelet-arg=streaming-connection-idle-timeout=0` to k3s, but still no luck

**Comment by bartowl** [comment] 2022-09-14 09:40
@adpavlov I hope you do not confuse running k3s under docker as k3d, and docker backend mode for k3s. From what I have seen, when k3s is running in docker mode, all pods are created as docker containers and can be directly seen in docker ps output. I could not manage to get it to that point with k3d even after mounting docker socket in the k3d server container :/ But will keep trying :)

**Comment by adpavlov** [comment] 2022-09-14 09:57
for sure I'm using k3s with `--docker` flag.  

```
kubectl get no -o wide | awk '{print $5, $NF}'
VERSION CONTAINER-RUNTIME
v1.24.4+k3s1 docker://20.10.12
v1.24.4+k3s1 docker://20.10.12
```

And snippet from `k3s.service`:

```
ExecStart=/usr/local/bin/k3s \
    server \
	'--docker' \
	'--disable=traefik' \
	'--write-kubeconfig-mode' \
	'--kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%' \
	'--kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%' \
	'--kubelet-arg=image-gc-high-threshold=97' \
	'--kubelet-arg=image-gc-low-threshold=95' \
	'--kubelet-arg=image-gc-low-threshold=95' \
	'--kubelet-arg=container-log-max-size=100Mi' \
	'--kubelet-arg=container-log-max-files=5' \
	'--kubelet-arg=streaming-connection-idle-timeout=0' \
```

**Comment by bartowl** [comment] 2022-09-14 10:32
that is bad, i hoped this will help as in https://github.com/containerd/cri/issues/1057#issue-414329803 but this post references actually kubernetes from version v1.10.13 which is looong time not valid anymore. The entire mentioned section seems to got rid, as in current version the kubelet.go looks totally different. Will look for other possible reasons.

**Comment by bartowl** [comment] 2022-09-14 10:40
kowever in the current version i find mentions of `streamingConnectionIdleTimeout` at many places, so this timeout should be configurable and not only docker-backend-specific, as this block vanished... (see https://github.com/kubernetes/kubernetes/blob/release-1.25/pkg/kubelet/kubelet.go#L499) and search for other occurences...
Will try instead of disabling it to double it. running now with streaming-connection-idle-timeout=28800**s** (without unit it thrown errors:

> WARN[0013] warning: encountered fatal log from node k3d-awx-server-0 (retrying 0/10): ▒time="2022-09-13T21:07:14Z" level=fatal msg="kubelet exited: failed to parse kubelet flag: invalid argument \"28800\" for \"--streaming-connection-idle-timeout\" flag: **time: missing unit in duration** \"28800\""

will see in 4h...

**Comment by bartowl** [comment] 2022-09-14 10:51
Setting the timeout higher might however have a chance to work, as setting it to 0 causes it to be set to default 4h again: see https://github.com/kubernetes/kubernetes/blob/release-1.25/pkg/kubelet/apis/config/v1beta1/defaults.go#L116

**Comment by kladiv** [comment] 2022-09-14 12:32
@bartowl thanks for you tests.  
Please keep us informed if `--kubelet-arg=streaming-connection-idle-timeout=<VERY_HIGH_VALUE>s` works

**Comment by adpavlov** [comment] 2022-09-14 14:07
I have weird results with `--kubelet-arg=streaming-connection-idle-timeout=0`  

Following task checks date every 30 minutes and playbook resulted in error right after 4 hours

```
    - name: Test
      ansible.builtin.shell: |
        date
      retries: 48
      delay: 1800
```

However, just `wait_for` task with 5 hours timeout was running exactly 5 hours, but again exited with error state

```
    - name:Test
      ansible.builtin.wait_for:
        timeout: 18000
```

**Comment by bartowl** [comment] 2022-09-14 14:51
![image](https://user-images.githubusercontent.com/12292174/190188215-3b877e88-cd65-4cc4-ab9d-9c17b0eb373f.png)
extending this to 28800s did not help, first interaction after 4h breaks the job. The 5 hours is just the first that happened after 4h...

**Comment by kurokobo** [comment] 2022-09-14 22:16
I have no idea if this is helpful since this issue can't be reproduced on my side and have not digged into deeper, but the containerd also has `stream_idle_timeout` with 4 hours as default: https://github.com/containerd/containerd/blob/main/docs/cri/config.md#full-configuration

```toml
  # stream_idle_timeout is the maximum time a streaming connection can be
  # idle before the connection is automatically closed.
  # The string is in the golang duration format, see:
  #   https://golang.org/pkg/time/#ParseDuration
  stream_idle_timeout = "4h"
```

If you're on K3s, you can see this:

```bash
$ sudo $(which k3s) crictl info | jq '.config.streamIdleTimeout'
"4h0m0s"
```

You can modify this value by:

```bash
# Copy existing config.toml as config.toml.tmpl
sudo cp /var/lib/rancher/k3s/agent/etc/containerd/{config.toml,config.toml.tmpl}

# Append 'stream_idle_timeout = "<value>"' under '[plugins.cri]'
sudo vi /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
# [plugins.cri]
#   stream_server_address = "127.0.0.1"
#   stream_server_port = "10010"
#   stream_idle_timeout = "10h"     👈👈👈

# Restart K3s
sudo systemctl restart k3s
```

```bash
$ sudo $(which k3s) crictl info | jq '.config.streamIdleTimeout'
"10h"
```

F.Y.I., In not K3s but AKS, the default idle timeout is extremely short (4min), so I made a dirty workaround: https://github.com/ansible/awx/issues/12530#issuecomment-1192616101

If this issue occurs with long idling for log stream (means no logs sent from ee for a long time), the same workaround could be used I guess. I think this issue should be solved by the Ansible Runner or Receptor.

**Comment by bartowl** [comment] 2022-09-15 06:52
Thanks @kurokobo for sharing this information. In my setup indeed, despite running k3s server with `--kubelet-arg=streaming-connection-idle-timeout=28800s`, this value also is set to 4h:
```
/ # crictl info | grep Idle
    "streamIdleTimeout": "4h0m0s",
```
But as far as I understand, this is a timeout, when no new line in pod logs is generated over a certain time.
My playbook uses either async_status to periodically poll for progress (therefore generates log lines) or `pause: minutes=10` that is just repeated with `with_sequence: count=300`... So I guess this is not the case. Nevertheless I will try to increase this one as well and see when something changes...

What makes me unhappy is the comment in this like: https://github.com/kubernetes/kubernetes/blob/v1.25.0/cmd/kubelet/app/options/options.go#L451
saying:
> Maximum time a streaming connection can be idle before the connection is automatically closed. 0 indicates no timeout. Example: '5m'. Note: **All connections to the kubelet server have a maximum duration of 4 hours**.

Does this mean, that despite setting of this parameter there is another hardcoded maximum duration of 4h?

I guess it is time to focus on the AWX part and implementing a retry mechanism instead of increasing timeouts, which is from security perspective also not recommended...

**Comment by bartowl** [comment] 2022-09-16 09:56
Ok, I have bad news - the 4h timeout is really hardcoded in kubelet. There is no way around it:
See: https://github.com/kubernetes/kubernetes/blob/v1.25.1/pkg/kubelet/server/server.go#L161
and https://github.com/kubernetes/kubernetes/issues/104595 and https://github.com/kubernetes/kubernetes/pull/104735/files

The only way to get over 4h is to implement retry mechanism in AWX. My python knowledge is way too little to do that :( I Tried to find the spot in code where it spawns the container and how it fetches its output, but got lost with the receptor, callbacks and stuff. This might be not so easy to implement, but I cannot imagine that such product as AWX does not allow a job to run over 4 hours.

**Comment by nicolasbouchard-ubi** [comment] 2022-09-16 12:39
Just to weight in, we have the exact same problem. We have a long-running task that poll an API to fetch the status of builds that can take more than 4 hours to complete.
![image](https://user-images.githubusercontent.com/112958784/190638669-593f4da6-0767-4607-892b-d854929e21c4.png)
![image](https://user-images.githubusercontent.com/112958784/190639554-52ce0f05-e038-4068-8e33-d83ed6fff7a4.png)

This is a big disapointment for us and makes AWX unusable for our use cases. Any workaround on how to implement such task would be greatly appreciated. I would be willing to contribute to solve the problem in AWX, but would need help to start off.

**Comment by adpavlov** [comment] 2022-09-16 20:18
> so I made a dirty workaround: [#12530 (comment)](https://github.com/ansible/awx/issues/12530#issuecomment-1192616101)

This didn't help in k3s...

**Comment by sylvain-de-fuster-maif** [comment] 2022-10-03 17:19
Hello,

As many here, we have the same behaviour on our side. (AWX 21.5.0 with k3s)
The informations given before don't give a good perspective for a quick resolution.

We have some issues in our migration tests but this one is on top.
We don't have a lot of long duration jobs but they are very important.

Is there anybody with a workaround for long duration tasks ? How do you proceed in the meantime ?

Thank you all.

**Comment by bartowl** [comment] 2022-10-04 11:02
The only workaround that worked for me was to create a workflow, and split the task in multiple jobs. It does not even require multiple job templates if you work smart with tags, marking some tasks with tag like step1, next with step2 and so on, and than include the same job template in workflow multiple times, each time with different tag. Passing variables between different steps can be realised with ansible.builtin.set_stats, yet this is still cumbersome and problematic with single task that might run longer than 4h. For such a single task you have to use poll: 0, async: xxx, pass registered variable via set_stats and from optionally next step in workflow query the progress with async_status...

This is doable, but the only way to get around this is to redesign the part where the automation container is started. Instead reading its output as it is now, it has to be read in a kind of while true loop, until the container really finishes. Now, the container gets aborted when the https connection to kubectl gets disconnected.

**Comment by sylvain-de-fuster-maif** [comment] 2022-10-04 11:23
> The only workaround that worked for me was to create a workflow, and split the task in multiple jobs. It does not even require multiple job templates if you work smart with tags, marking some tasks with tag like step1, next with step2 and so on, and than include the same job template in workflow multiple times, each time with different tag. Passing variables between different steps can be realised with ansible.builtin.set_stats, yet this is still cumbersome and problematic with single task that might run longer than 4h. For such a single task you have to use poll: 0, async: xxx, pass registered variable via set_stats and from optionally next step in workflow query the progress with async_status...
> 
> This is doable, but the only way to get around this is to redesign the part where the automation container is started. Instead reading its output as it is now, it has to be read in a kind of while true loop, until the container really finishes. Now, the container gets aborted when the https connection to kubectl gets disconnected.

Thanks for your reply.
This is a very interesting workaround. We will experiment with that way and see if this is compatible and not too painful for our users's workcases.

**Comment by arcsurf** [comment] 2022-10-10 10:14
> @adpavlov sadly there is nothing new to report 😕​

Hi adpavlov, before all, thank you for sharing your experience. I was wondering if maybe you get any workaround or answer. I keep trying but I can't find the solution. Now I'm using CRIO-O as container runtime, I see on other post that somebody tried with Docker runtime too and it didn't work. Thank you.

**Comment by adpavlov** [comment] 2022-10-10 10:28
Unfortunately not. All proposed workarounds simply have no positive effect.
Probably @meis4h got some response from redhat support? I bet that SLA already violated:)

**Comment by arcsurf** [comment] 2022-10-10 11:18
I'm sorry @adpavlov, Yes I was trying to ask to @meis4h. Maybe @meis4h got some from Redhat. 

Thank you everyone.

**Comment by bartowl** [comment] 2022-10-10 12:59
after looking more deeply into this issue, AWX uses [receptor](https://github.com/ansible/receptor)  to handle running k8s pods. It might be, that the fix that we need is either by calling receptor in a different way, or even the issue should be reported against receptor. In particular, receptor is being called from [run_until_complete](https://github.com/ansible/awx/blob/21.7.0/awx/main/tasks/receptor.py#L158) method, which submits the work request to receptor, and queries for status. It also allocates some sockets for bidirectional communication in [_run_internal](https://github.com/ansible/awx/blob/21.7.0/awx/main/tasks/receptor.py#L320) and this is what I'm afraid is running into timeout.

So basically, AWX uses external projects like receptor or kubernetes, kubernetes declared static 4h hardcoded timeouts, and receptor seems to be breaking off after this time. Now the big question is - who should fix this issue and in which part of code? Is it receptor that needs fixing, or maybe the way AWX uses it?

One has to consider, that AWX needs bi-directional communication with running automation pod for example in order to interactively pass passwords and so on. On the other hand, it should implement some re-attach mechanism after the connection breakes, the pod has to run even if the connection brakes. This addresses the reaper not to reap such detached pods. Also, once AWX re-connects to running pod, it needs to figure out till when it read the output previously, and continue from that moment in order to update web pages looking at the progress without skipping/doubling tasks... This is way beyond trivial task, at least for what it looks to me.

**Comment by meis4h** [comment] 2022-10-10 12:59
@adpavlov @arcsurf sadly I don't have anything new to report from Red Hat. They said they also are tracking this internally and are working on a fix but there is no ETA since there is no SLA on bugs like this.

**Comment by arcsurf** [comment] 2022-10-10 13:44
@meis4h :( Thank you for your answer. Let's keep looking for the solution. :)

**Comment by nicolasbouchard-ubi** [comment] 2022-10-14 14:36
@bartowl 
 Thanks for your workaround suggestion! 
 
I already was aware of the polling feature in Ansible but I'm not sure if it can be used in my case, same for the workflow. Maybe other people are in the same situation, so I would like to dig for a workaround.

At the moment, I have a task which is using an until loop to query a REST API until the API return "state: finished". 
 ```
- name: Wait for agent to finish running build
            ansible.windows.win_uri:
              url: "REDACTED"
              method: GET
              url_username: "REDACTED"
              url_password: "REDACTED"
              return_content: yes
              content_type: application/json
              headers:
                accept: application/json
            throttle: 25
            register: build_info
            until: build_info.json is defined and build_info.json.state == "finished"
            retries: 120
            delay: 60 #Check build status every minutes for 2h to try prevent 4h entire playbook disconnection (not really working because I have multiple plays)
```
How could such a task use poll: 0, async: xxx like you suggested since it's not really a one operation long running task, but instead a task that execute multiple times for a long time? 

Any suggestion is welcome 😃 

Thanks

**Comment by bartowl** [comment] 2022-10-14 14:43
@nicolasbouchard-ubi here it is not the task that takes long, as the task it self is retried multiple times. The same way with a long running task you would use async_status. The task itself finishes rather quickly but the until: condition is not met.
What you could do is - when you know, that this task will take at least 1h, split the job template at this place marking all tasks until this one with tag: stage1 for example. Starting from this task mark everything else stage2.
You will have to propagate all variables defined/changed by tasks in stage1, that will be needed in stage2 via set_stats module.
Then, create a workflow template, with 3 elements.
1. this job template with tags: stage1
2. approval step with 1h timeout and default Accept approval (this will give you 1h delay before first status check
3. this job template with tags: stage2

What this will do is - it will execute all tasks until querying the agent for build status, then wait 1h (or shorter if you manually approve the step), and then continue from the moment it checks for the status. Now 4h limit applies to step 1 and 3 separately, effectively 4h for each one run. This should help you.

**Comment by rooftopcellist** [comment] 2022-11-16 22:47
I think this issue and the following issue are talking about the same bug:
* https://github.com/ansible/awx-operator/issues/622

@TheRealHaoLiu left a comment that may be of interest to those on this thread:
* https://github.com/ansible/awx-operator/issues/622#issuecomment-1317731544

**Comment by fosterseth** [comment] 2022-12-02 17:15
### Update

#### Fix
PR https://github.com/ansible/receptor/pull/683

This should address the 4 hour timeout limit as well as the log rotation issue

The fix applies to both K8S and OCP users

#### How to get this change
- The fix is already in quay.io/ansible/awx-ee:latest
- custom EEs to run jobs based on awx-ee **do not** need to be updated
- only the awx-ee container running the AWX pod needs to be `latest`
- Redeploying AWX should trigger awx-operator to re-pull awx-ee:latest to use as the `control_plane_ee_image`. This is all that most users should need to do to get the change.

#### Requirements for K8S
- K8S server should be >= one of the following,
  - 1.23.14
  - 1.24.8
  - 1.25.4
- use `kubectl version` to check your K8S server version
- Receptor will auto detect the K8S server and enable the reconnect support feature if on a compatible version
- if the cluster is _not_ running at least those versions, receptor will fallback to the older method and the 4 hour timeout issue will persist.

#### Requirements for OpenShift
- Currently Receptor does not auto detect OCP versions, so enabling the fix must be _manual_
- OCP server should be >= one of the following:
  - 4.10.42
  - 4.11.16
  - 4.12.0
- To enable the fix on OCP, you should set the following variable in the AWX resource
```
  ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: enabled
```
- it is **critical** that you only enable this if you are on a compatible version of OCP, otherwise jobs may fail unexpectedly.

**Comment by bartowl** [comment] 2022-12-06 11:46
Great news! Hope this will fix the problem permanently. If you cannot update to the fixed version for any reason possible, you might want to read a detailed description on how to workaround this limitation here https://thecattlecrew.net/2022/12/06/overcome-4h-runtime-problem-with-ansible-awx/

**Comment by TheRealHaoLiu** [comment] 2022-12-06 14:11
couple of potential gotchas with our current fix

1) using the flag RECEPTOR_KUBE_SUPPORT_RECONNECT = "enable" will completely skip the kube version check ALL container groups (including external container group that's added by user) if any of the cluster in the container group does not include the kube fix we rely on it will cause job execution on that container group to fail

NOTE: the default mode auto mode (which currently is not able to detect openshift version and enable the fix correctly) will detect the kube version case by case basis

2) the "auto" detection rely on kubernetes apiserver version. The fix from kube that we need is in the kubelet. it is possible that individual worker node have kubelet out of sync with kube-apiserver's version. In this case we will incorrectly detect and enable the fix which will cause job failure when running on the out of date worker node

**Comment by TheRealHaoLiu** [comment] 2022-12-14 16:18
fixed in https://github.com/ansible/receptor/pull/683

**Closed as completed by TheRealHaoLiu** 2022-12-14 16:18 UTC
Labels: type:bug, component:api

**Comment by kzinas-adv** [comment] 2022-12-22 12:34
We found issue using this fix. We get huge cuts in awx job output, fox example  ~2 hours are missing, only small part of start and small part of end:

k8s 1.25.4-do.0
AWX 21.10.1
receptor 1.3.0
Fix enabled

Time:                 22:04:32  -> 00:11:31 
Playbook run:  0:01:40.151  ->  2:08:39.984

```
Wednesday 21 December 2022  22:04:32 +0000 (0:00:29.791)       0:01:40.151 ****

TASK [create : Create var volume] ***************************************
ok: [db02.host.ge -> localhost]
ok: [db01.host.ge -> localhost]

changed: [localhost] => (item=www.random.org)
Thursday 22 December 2022  00:11:31 +0000 (0:00:03.724)       2:08:39.984 *****
```
Time:                   01:39:55  ->  01:59:38 
Playbook run:    0:08:04.813  ->  0:27:48.142

```
Thursday 22 December 2022  01:39:55 +0000 (0:00:00.186)       0:08:04.813 ***** 

TASK [generic-backend : Copy files to /opt/ab-reports] *************************
ok: [srv02.host.ge] => (item=/runner/project/private/nats/nats.ca.pem)
ok: [srv02.host.ge] => (item=/runner/project/private/nats/nats.client.pem)
ok: [srv02.host.ge] => (item=/runner/project/private/nats/nats.client.key)
Thursday 22 December 2022  01:59:38 +0000 (0:00:00.498)       0:27:48.142 ***** 
```

Looks awx pick first log and last and skips everything in between

**Comment by kzinas-adv** [comment] 2022-12-23 15:23
Raised new issue https://github.com/ansible/awx/issues/13376

**Comment by MaciejLeszczynski** [comment] 2023-11-29 01:10
> ### Update
> #### Fix
> PR [ansible/receptor#683](https://github.com/ansible/receptor/pull/683)
> 
> This should address the 4 hour timeout limit as well as the log rotation issue
> 
> The fix applies to both K8S and OCP users
> 
> #### How to get this change
> * The fix is already in quay.io/ansible/awx-ee:latest
> * custom EEs to run jobs based on awx-ee **do not** need to be updated
> * only the awx-ee container running the AWX pod needs to be `latest`
> * Redeploying AWX should trigger awx-operator to re-pull awx-ee:latest to use as the `control_plane_ee_image`. This is all that most users should need to do to get the change.
> 
> #### Requirements for K8S
> * K8S server should be >= one of the following,
>   
>   * 1.23.14
>   * 1.24.8
>   * 1.25.4
> * use `kubectl version` to check your K8S server version
> * Receptor will auto detect the K8S server and enable the reconnect support feature if on a compatible version
> * if the cluster is _not_ running at least those versions, receptor will fallback to the older method and the 4 hour timeout issue will persist.
> 
> #### Requirements for OpenShift
> * Currently Receptor does not auto detect OCP versions, so enabling the fix must be _manual_
> * OCP server should be >= one of the following:
>   
>   * 4.10.42
>   * 4.11.16
>   * 4.12.0
> * To enable the fix on OCP, you should set the following variable in the AWX resource
> 
> ```
>   ee_extra_env: |
>     - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
>       value: enabled
> ```
> 
> * it is **critical** that you only enable this if you are on a compatible version of OCP, otherwise jobs may fail unexpectedly.
