### ISSUE TITLE
9.1.0 installation error (awx-celery) : relation "main_instance" does not exist

### ISSUE THREAD

**Issue by alanbchristie** [ansible/awx#5578] opened 2019-12-31 09:18 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A clean installation on `kubernetes` (1.16.4/minikube) with `postgres` (10.11) with, what I believe to be a correctly edited inventory file the installation does not get past the **Migrate database** task, locking-up at...

`TASK [kubernetes : Migrate database]`

AWX is installed into a pre-existing namespace and with a pre-installed postgres with a pre-existing AWX user (`awx`), password and pre-created database (`awx`).

When the pod logs are inspected I see...

in **awx-celery**: -

```
2019-12-30 11:36:45,977 INFO exited: dispatcher (exit status 1; not expected)
2019-12-30 11:36:46,981 INFO spawned: 'dispatcher' with pid 670
2019-12-30 11:36:47,982 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.1.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 165, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 123, in handle
    reaper.reap()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/reaper.py", line 38, in reap
    (changed, me) = Instance.objects.get_or_register()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/managers.py", line 132, in get_or_register
    return self.register()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/managers.py", line 125, in register
    if instance.exists():
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
```

In **awx-web**: -

```
WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0x192f100 pid: 131 (default app)
WSGI app 0 (mountpoint='') ready in 9 seconds on interpreter 0x192f100 pid: 129 (default app)
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
```

In the **postgres** Pod: -

```
2019-12-30 11:49:48.525 UTC [417] ERROR:  relation "django_migrations" does not exist at character 124
2019-12-30 11:49:48.525 UTC [417] STATEMENT:  SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE ("django_migrations"."app" = 'main' AND "django_migrations"."name" IN ('0005a_squashed_v310_v313_updates', '0005b_squashed_v310_v313_updates'))
2019-12-30 11:49:48.550 UTC [417] ERROR:  relation "conf_setting" does not exist at character 158
2019-12-30 11:49:48.550 UTC [417] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'LOG_AGGREGATOR_LEVEL' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
```

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: kubernetes (minikube)
* Ansible version:  2.9.2
* Operating System: OSX 10.15.2
* Web Browser: Safari 13.0.4

##### STEPS TO REPRODUCE

Python 3.7 virtualenv with: -

- ansible == 2.9.2
- ansible-tower-cli == 3.3.7
- jmespath == 0.9.4
- openshift == 0.10.1

Configure a minikube system with a postgres installation (with service name `database`) and create user and database (in this case user is `awx` and database is `awx`). Clone the awx repo and move to tag `9.1.0` and edit the inventory accordingly and then run the installation: -

Here the AWX installation goes into the same namespace as the Postgres database, with key variables shown below (passwords don't matter this is a local test installation). basically there is a postgres service behind the hostname `database` with an `awx` user, password of `zDHX8dOFf9` and an existing database that is `awx`: -

```
kubernetes_context=minikube
kubernetes_namespace=im-infra
pg_hostname=database
pg_username=awx
pg_password=zDHX8dOFf9
pg_database=awx
pg_port=5432
create_preload_data=False
```

Then install with...

`ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

Migration task should complete

##### ACTUAL RESULTS

Migration task does not complete

**Comment by MrBones757** [comment] 2020-01-02 02:29
I believe you may be experiencing this issue (or similar): https://github.com/ansible/awx/issues/5530

For me, the issue was resolved using the suggestion here: https://github.com/ansible/awx/issues/5530#issuecomment-569150880    
I chose to manually run the upgrade using point 1 and comment out the migrate in the deploy tasks, which worked for me (so, deploy -> cancel at migrate -> manual migrate using command -> run deploy script again)
I am using an externally managed postgres instance though so just double check that this will work for you as i'm not 100% sure of the default installers behavior with an installer managed postgres instance :)

**Comment by alanbchristie** [comment] 2020-01-02 09:48
Thanks @MrBones757 .

Its a clean install (i.e. no prior AWX to upgrade/migrate) so, after setting the variables in the inventory accordingly, and prior to running the awx playbook (for minikube/kubernetes in my case), edit the awx clone's `roles/kubernetes/templates/credentials.py.j2` template to add a better qualified `BROKER_URL`. i.e. change...

`localhost`

to...

`rabbitmq.{{ kubernetes_namespace }}.svc`

...does indeed avoid the Migrate lock-up and leaves the Pods without any start-up errors.

**Comment by AlanCoding** [comment] 2020-01-02 13:26
Closing as duplicate of #5530

**Closed as completed by AlanCoding** 2020-01-02 13:26 UTC
Labels: type:bug
