### ISSUE TITLE
Modification to the credential plugin system to get an external credential for each host in the play

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#10924] opened 2021-08-23 14:25 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Similar/add-on request to #286 

Users can use Cyberark to manage and rotate ssh keys on a per-host basis.
This means all hosts have different ssh keys and therefore require an external lookup on a per-host basis.

**Comment by wenottingham** [comment] 2021-08-23 16:15
Closing as a duplicate of #286.

**Closed as completed by wenottingham** 2021-08-23 16:15 UTC
