### ISSUE TITLE
User from LDAP with superuser flag treated as auditor in config section

### ISSUE THREAD

**Issue by bkmeneguello** [ansible/awx#4402] opened 2019-07-31 13:30 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have an user from LDAP properly configured with "is_superuser" (from LDAP group). In the user page it's displayed as "User type: System Adminstrator" but when I access the configuration pages there is a banner saying: "System auditors have read-only permissions in this section." and everything is read-only.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.3
* Operating System: CentOS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

* Configure authentication from LDAP
* Add to "LDAP USER FLAGS BY GROUP":
  ```
  {
   "is_superuser": [
      "CN=AWX Admins,OU=..."
   ],
   "is_system_auditor": [
      "CN=AWX Auditors,OU=..."
    ]
  }
  ```
* Add the user to both groups
* Login ad this user
* Access any configuration page

##### EXPECTED RESULTS

User should be system administrator and should be able to edit any configuration

##### ACTUAL RESULTS

Is displayed the following banner: "System auditors have read-only permissions in this section." and all fields are blocked.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/1322552/62215829-0c973c80-b37e-11e9-8c12-b832e874de5a.png)

**Comment by wenottingham** [comment] 2019-07-31 14:44
Can you try a build with https://github.com/ansible/awx/pull/4396 merged? (There isn't a container on dockerhub built with this yet, you may need to build your own.)

**Comment by awithrow9** [comment] 2019-08-09 17:33
@bkmeneguello have you had a chance to give this a try?

**Comment by bkmeneguello** [comment] 2019-08-09 20:32
Sorry, I did not. I just have a production server and had no time to setup a test one. I pretend to do this soon.

**Comment by ryanpetrello** [comment] 2019-08-23 17:19
@bkmeneguello in my private testing, I'm unable to reproduce what you're describing.  If you're still encountering this problem after trying the latest code from `devel`, let us know, and I'll reopen this issue.

**Closed as completed by ryanpetrello** 2019-08-23 17:19 UTC
Labels: type:bug
