### ISSUE TITLE
Raise "Field is not allowed for use in workflows" error when creating workflow schedule

### ISSUE THREAD

**Issue by ElliotGo** [ansible/awx#1131] opened 2018-02-05 02:55 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Raise "Field is not allowed for use in workflows" error when creating workflow schedule

##### ENVIRONMENT
* AWX version: 1.0.3.5
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: WIN10
* Web Browser: Chrome  63.0.3239.132（64 bits）

##### STEPS TO REPRODUCE

1. Create a workflow template, add jobs into it by workflow editor
2. Click schedule button in this new workflow template
3. Fill the form and click Save
4. Failed to save, web throw a error:
ERROR!
Field is not allowed for use in workflows.

##### EXPECTED RESULTS

Create schedule for workflow template normally

##### ACTUAL RESULTS

Raise "Field is not allowed for use in workflows" error when creating workflow schedule
![image](https://user-images.githubusercontent.com/28291313/35786590-33fe658e-0a63-11e8-8b1c-5c6ed3d004b2.png)

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/28291313/35786558-f51ef8ec-0a62-11e8-86fa-509a1928f39d.png)

**Comment by ryanpetrello** [comment] 2018-02-08 19:13
@AlanCoding this seems in your wheelhouse.

**Comment by ryanpetrello** [comment] 2018-02-08 19:15
@mabashian @jaredevantabor looks like https://github.com/ansible/awx/pull/979 maybe didn't resolve this?

**Comment by jaredevantabor** [comment] 2018-02-08 19:50
@ryanpetrello negative, the issue in #979 was that the user couldn't get to the schedules page. The issue in this ticket is that issuing a POST to `workflow_job_templates/N/schedules` gets rejected by the API

**Comment by AlanCoding** [comment] 2018-02-08 20:10
> The issue in this ticket is that issuing a POST to workflow_job_templates/N/schedules gets rejected by the API

That sounds like it might have been fixed by #1153, which landed a day ago, since the issue is 4 days old, this is plausible.

**Comment by ryanpetrello** [comment] 2018-02-08 20:53
@ElliotGo you mind giving `devel` of awx a shot and seeing if you're still encountering this?

**Comment by ryanpetrello** [comment] 2018-03-28 18:27
@ElliotGo let us know if you're still having issues and I'll re-open this for investigation.

**Closed as completed** 2018-03-28 18:27 UTC
Labels: type:bug, component:api, component:ui
