### ISSUE TITLE
no notification (email) when launched job finished

### ISSUE THREAD

**Issue by gripenk** [ansible/awx#944] opened 2018-01-10 04:10 UTC
##### ISSUE TYPE

 - Bug Report

##### ENVIRONMENT
* AWX version: 1.0.2.335
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System: CentOS 6.9
* Web Browser:

##### STEPS TO REPRODUCE

Created an "email" notification, "test notification" will show "notification sent" and I got the email
created a job template, witch that email notification on both "success" and "failure", and then launch, no email is received after finished, no matter success nor failed.

##### EXPECTED RESULTS

Get the email notification

##### ACTUAL RESULTS

no  email notification

**Comment by shortsteps** [comment] 2018-01-10 11:40
Duplicate of #935

**Closed as completed** 2018-01-10 15:46 UTC
Labels: type:bug
