### ISSUE TITLE
504 upstream uwsgi timeout - Testing external credential - Cyberark AIM

### ISSUE THREAD

**Issue by spisakni** [ansible/awx#7295] opened 2020-06-09 13:29 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Receiving 504 upstream uwsgi timeout when testing a CyberArk AIM external credential. The web pod has connectivity to the CCP infrastructure and validated from the web pod via curl with the client cert, key, and REST endpoint. When running from the AWX UI I see the following in the web log after the nginx timeout expires. Left all defaults as installed by the 11.2 tagged version. 

2020/06/09 03:17:06 [error] 82#0: *198 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST
 /api/v2/credentials/11/test/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "localhost:1080", referrer: "http://localhost:1080/"
127.0.0.1 - - [09/Jun/2020:03:17:06 +0000] "POST /api/v2/credentials/11/test/ HTTP/1.1" 504 578 "http://localhost:1080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) Apple
WebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36" "-"
Tue Jun  9 03:17:07 2020 - *** HARAKIRI ON WORKER 1 (pid: 83, try: 1) ***
Tue Jun  9 03:17:07 2020 - HARAKIRI !!! worker 1 status !!!
Tue Jun  9 03:17:07 2020 - HARAKIRI [core 0] 127.0.0.1 - POST /api/v2/credentials/11/test/ since 1591672506
Tue Jun  9 03:17:07 2020 - HARAKIRI !!! end of worker 1 status !!!
DAMN ! worker 1 (pid: 83) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 149)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2185a50 pid: 149 (default app)

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: Kubernetes
* Ansible version:  2.9.7
* Operating System: awx_web and awx_task containers for 11.2.0
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Navigate to 'Credentials' > '+' > add a new 'CyberArk AIM Central Credential Provider Lookup' > Add the required inputs > Click on 'Test' > Add the 'Object Query' details

- The request will clock until the uwsgi_read_timeout of 120s is reached and than throws the 504 gateway error documented above. 

##### EXPECTED RESULTS

* The test should work. We validated the setup in a working Tower environment (3.7) that is running on virtual machines and not K8s pods to ensure the AIM credential setup is correct. 

##### ACTUAL RESULTS
* 504 gateway error

**Comment by ryanpetrello** [comment] 2020-06-09 14:43
Hey @spisakni,

I think what you're encountering is a duplicate of https://github.com/ansible/awx/issues/6986

It should be resolved in the next version of awx (which we intend to release in the next day or so).

**Closed as completed by ryanpetrello** 2020-06-09 14:43 UTC
Labels: type:bug
