### ISSUE TITLE
Disable cancel button when job is complete

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8207] opened 2020-09-22 20:26 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This code is reused in a few places. One example is Job Template -> Completed Jobs
![Screenshot from 2020-09-22 16-25-12](https://user-images.githubusercontent.com/19942822/93933804-33d26b00-fcf0-11ea-9e70-1217d192be1d.png)

The `Cancel Job` button is enabled even when jobs are complete. Also, this flow seems a bit unintuitive. Should this be a one-button click cancel button that switches out with the launch job button, like the other UI?

**Comment by mabashian** [comment] 2020-09-28 21:04
> The Cancel Job button is enabled even when jobs are complete

We can fix this.

It was a conscious decision to make this a multi-select thing.  Of course we could go back to individual buttons if needed.

**Comment by unlikelyzero** [comment] 2021-02-14 19:10
this is a dupe of https://github.com/ansible/awx/issues/8207

**Closed as completed** 2021-02-14 19:09 UTC
Labels: type:bug, component:ui
