### ISSUE TITLE
Most of output is greyed out since upgrading to 20.0.0

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#11818] opened 2022-02-28 07:43 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Output not showing full result since upgrading from 19.4 to 20.0. Browser windows also becomes unresponsive sometimes. 

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Ansible version

quay.io/ansible/awx-ee:0.6.0

### Operating system

Centos

### Web browser

Chrome, Edge

### Steps to reproduce

I don't know

### Expected results

Output scrolling should show all output

### Actual results

Most of the lines grayed out

**Comment by stanislav-zaprudskiy** [comment] 2022-02-28 08:52
Is this a duplicate of https://github.com/ansible/awx/issues/11765?

**Comment by nicolaibaralmueller** [comment] 2022-02-28 09:02
> Is this a duplicate of #11765?

Somewhat, yes. But in my output is completely greyed out after a certain point.

**Comment by radek-sprta** [comment] 2022-02-28 15:28
I have the same issue. But I am actually on 19.5.1.

**Comment by MrBones757** [comment] 2022-03-03 07:32
Its actually a duplicate of this :) https://github.com/ansible/awx/issues/11647
We had the same symptoms and did some digging and this is what we came up with.

**Comment by kimbernator** [comment] 2022-03-03 19:05
Seeing the same issue on version 20

**Comment by nicolaibaralmueller** [comment] 2022-03-04 06:48
> Its actually a duplicate of this :) #11647 We had the same symptoms and did some digging and this is what we came up with.

Thanks. This makes sense. We are hosting AWX in Azure and the VM (4vCores/16GiB) crashes periodically when many jobs are executed at the same time. Might need to downgrade to 19.4 again if this is not resolved asap.

**Comment by chris93111** [comment] 2022-03-07 20:50
hi same issue on 20.0.0 

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/27526373/157115614-685102db-e37e-4de5-8660-61d53e4928b3.png">

download output is complete is only on UI

with ?job_output.not__stdout__startswith=[WARNING] all output is appear

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/27526373/157117104-adc05224-1d4a-4715-9d3d-916caffc0956.png">

**Comment by ryanmerolle** [comment] 2022-03-08 19:29
same here on 20.0.0

**Comment by nicolaibaralmueller** [comment] 2022-03-09 07:12
Downgrading to AWX 19.4 resolved the AWX bug and Azure VM issue where the VM became unresponsive. This is a highly critical error.

**Comment by mabashian** [comment] 2022-03-11 18:37
Are there any errors reported in the browser console?  That would be helpful for troubleshooting if there is a bug client-side.

**Comment by ryanmerolle** [comment] 2022-03-11 21:32
MS Edge (Version 98.0.1108.43 (Official build) (64-bit)) browser console logs:
```
index.js:9 I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.
useWebsocket.js:8 
        
       WebSocket connection to 'wss://awx.test.com/websocket/' failed: 
(anonymous) @ useWebsocket.js:8
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Nl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:34
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
i @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
useWebsocket.js:8 
        
       WebSocket connection to 'wss://awx.test.com/websocket/' failed: 
(anonymous) @ useWebsocket.js:8
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Nl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:34
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
i @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
useWebsocket.js:20 
        
       WebSocket is already in CLOSING or CLOSED state.
e @ useWebsocket.js:20
(anonymous) @ useWebsocket.js:38
setTimeout (async)
Rd.a.current.onclose @ useWebsocket.js:37
useWebsocket.js:20 
        
       WebSocket is already in CLOSING or CLOSED state.
e @ useWebsocket.js:20
(anonymous) @ useWebsocket.js:38
setTimeout (async)
Rd.a.current.onclose @ useWebsocket.js:37
```

**Comment by ryanmerolle** [comment] 2022-03-23 21:08
> Downgrading to AWX 19.4 resolved the AWX bug and Azure VM issue where the VM became unresponsive. This is a highly critical error.

@nicolaibaralmueller Any reason why you tried 19.4 and not 19.5?

**Comment by nicolaibaralmueller** [comment] 2022-03-24 07:31
@ryanmerolle  19.4 was the last version I used which was ok.

**Comment by keithjgrant** [comment] 2022-03-29 17:18
closing as duplicate of #11765

**Closed as completed by keithjgrant** 2022-03-29 17:18 UTC
Labels: type:bug, component:ui
