### ISSUE TITLE
Job output not updating (requires page refresh) 

### ISSUE THREAD

**Issue by silverscreen** [ansible/awx#9112] opened 2021-01-19 17:50 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job output fails to display in real time. The job output only appears with a page refresh. 

I have tried the following:
* kubernetes deployment with external postgres db
* default docker installation via ec2 instance
* default docker installation via localhost

I can see the websocket GET requests being repeatedly made with no response. All three environments suffer with the same problem. 

I'm raising this as a BUG as I had recently deployed a previous version of AWX several months ago (sorry, I do not recall which version) and I did not experience this issue at all with any of my deployments.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux, kubernetes (EKS)
* Ansible version:  2.9.15
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

Run any job within AWX.

##### EXPECTED RESULTS

Job output should update in real time.

##### ACTUAL RESULTS

Job output remains empty until page is refreshed.

##### ADDITIONAL INFORMATION

More than happy to help diagnose if someone can point me in the right direction to look.
Thanks

![no-job-output01](https://user-images.githubusercontent.com/34809422/105073196-aaa12a00-5a7e-11eb-8adf-2e0ccb62fbd1.png)

![no-job-output02](https://user-images.githubusercontent.com/34809422/105073195-aa089380-5a7e-11eb-8ae5-0bcb40fb3c67.png)

**Comment by jakemcdermott** [comment] 2021-01-19 18:01
:wave: hello @silverscreen . 

Thanks for creating this issue.

The job output update bug you described is caused by a combination of https://github.com/ansible/awx/issues/8596 and possibly https://github.com/ansible/awx/issues/9085.

We'll have a fix for these bugs in one of the upcoming awx releases.

I'm closing this issue for now - we're tracking the work for this in the issues linked above. 

also see: 
  - https://github.com/ansible/awx/issues/8930
  - https://github.com/ansible/awx/issues/8973
  - https://github.com/ansible/awx/issues/9105

**Closed as completed** 2021-01-19 18:02 UTC
Labels: type:bug, flag:community
