### ISSUE TITLE
Availibility to specify roles install destination path to preserve after template execution

### ISSUE THREAD

**Issue by sbarbo01** [ansible/awx#6439] opened 2020-03-26 16:07 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Availibility to specify roles install destination path to preserve after template execution

##### ENVIRONMENT
* AWX version: 9.30.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: CentOs
* Web Browser:

An unique project in one git repository. Project tree:
 ```
   - groups_vars
   - playbook
         - playbook1.yml (that call Role1)
         - playbook2yml (that call Role2)
   - roles
         - requirements.yml (included all roles available)
   - hosts

```
For each role, a independant git repository. Roles tree:
```
   - defaults
   - handlers
   - meta
   - tasks
         - main.yml
   - tests
   - vars
```

Content of requirements.yml:
```
- src: https://UrlOfGitRepo/Role1.git
  name: Role1
  path: /etc/ansible/roles
  scm: git

- src: https://UrlOfGitRepo/Role2.git
  name: Role2
  path: /etc/ansible/roles
  scm: git
```

In Awx, 1 template create for each playbook, all attached to the unique project 

##### STEPS TO REPRODUCE

Execute template related to playbook1. Execution succes but Role1 and Role2 are all downloded at the project_update step in /tmp of execution due to there presence in requirements.yml 
(eg:`"ansible-galaxy install -r requirements.yml -p /tmp/awx_233_g5v9ht15/requirements_roles -vvv",`)
With just 2 roles it not a problem, but with lots, size to download can become huge

##### EXPECTED RESULTS

Roles are store in a directory specified like /etc/ansible/roles or other. At the end of execution, roles are not deleted
At each execution, requirements.yml is used to download only roles that have not been yet install by ansible-galaxy during previous project_update.yml. 

##### ACTUAL RESULTS

For now, at each execution of project_update.yml, requirements.yml is used to download all roles into the tmp directory of the execution (requirements_roles) and at the end deleted.

Perhaps i'm wrong but i did not find how to preserve roles installed with ansible-galaxy/requirements.yml by project_update.yml affter execeuting ended.
I already try to specify roles_path variable  in ansible.cfg with no success

Regards

**Comment by AlanCoding** [comment] 2020-03-26 19:52
I would mark this as a duplicate of https://github.com/ansible/awx/issues/5518

We know this is a big pain point right now.

**Closed as completed** 2020-03-26 19:56 UTC
Labels: type:bug
