### ISSUE TITLE
Environment variables set in UI ignored

### ISSUE THREAD

**Issue by Joffrey54** [ansible/awx#6627] opened 2020-04-07 09:10 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I set a environment variables in my UI a long time ago...
`"ANSIBLE_SSH_ARGS": "-C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"`
But after migration on 10.0.0 (was 9.3.0 before), my playbook hangs in UI and in logs, I found ssh asking for host key register **when downloading my requirements roles from my gitlab**.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker
* Ansible version:  2.9.5
* Operating System: Debian 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Don't use any ansible.cfg in your projet, set in AWX ui the ANSIBLE_SSH_ARGS environ.
Start a a playbook on Linux/Unix host

##### EXPECTED RESULTS
No errors

##### ACTUAL RESULTS
Jobs in AWX are 'running' with no logs. In tmp of the running playbook, in stdout file, I see message asking to register host key **when downloading my requirements roles from my gitlab**.

**Comment by ryanpetrello** [comment] 2020-04-07 12:43
@nORKy54 what you're encountering sounds this sounds like a duplicate of:

https://github.com/ansible/awx/issues/6045

We haven't addressed the underlying issue yet, _but_ we have recently fixed the `StrictHostKeyChecking=no` for roles here: https://github.com/ansible/awx/pull/6488

**Closed as completed by ryanpetrello** 2020-04-07 12:43 UTC
Labels: type:bug
