### ISSUE TITLE
AWX Github(private github) Organization Integration Issue for authentication

### ISSUE THREAD

**Issue by devopsdata** [ansible/awx#925] opened 2018-01-05 18:23 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI /API
 
##### SUMMARY
AWX Github Organization Integration Issue
We have private github (enterprise version) - (not public github) . I am trying to integrate with private github orgazniation auth to login to awx.  i have followed the documentation to setup auth, but when i tried to login , (Sign in with github) - takes to github.com - instead of our own private repo. where should i configure private github org. Please help

##### ENVIRONMENT
* AWX version:  AWX 1.0.1.81 
* AWX install method:  docker on linux 
* Ansible version:   AWX 1.0.1.81 
* Operating System: Centos
* Web Browser:  Chrome/ Safari

**Comment by matburt** [comment] 2018-01-16 02:17
This is a dupe of: https://github.com/ansible/awx/issues/443

**Closed as completed by matburt** 2018-01-16 02:17 UTC
Labels: type:bug
