### ISSUE TITLE
Cannot save LDAP Group Type

### ISSUE THREAD

**Issue by earchibald-lv** [ansible/awx#1877] opened 2018-05-14 22:56 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Attempting to change and save the LDAP Group Type (for instance, to PosixGroupType) is a no-op. A 'saving' graphic pops up, but no activity takes place in the AWX log and behind the scenes the PATCH request receives a 400.

All other fields appear to save normally, but in order to make my LDAP logins function I must go manually patch this in Postgres.

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: CentOS7
* Web Browser: Safari for macOS, Chrome for macOS

##### STEPS TO REPRODUCE

- go to LDAP config
- change LDAP Group Type to 'PosixGroupType'.
- Save.

Navigate away and return and it will be shown that the LDAP Group Type has not been saved

##### EXPECTED RESULTS

LDAP Group Type should save

##### ACTUAL RESULTS
LDAP Group Type did not save.

**Comment by wenottingham** [comment] 2018-05-15 15:43
closing as a duplicate of https://github.com/ansible/awx/issues/1855

**Closed as completed by wenottingham** 2018-05-15 15:43 UTC
Labels: type:bug, component:ui
