### ISSUE TITLE
[RFE] Add a warning/confirmation when launching a job template against a large inventory

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#8161] opened 2020-09-16 21:23 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When running a job template against a large inventory, there is currently no warning or confirmation to ensure the user wants to do this. Adding a warning/confirmation like this would prevent consequential jobs (i.e. potentially impactful playbooks that shutdown hosts or could do other harmful things if targeting the wrong host) from being ran against an entire inventory of 10k+ hosts. This feature could be turned on through system settings that would have a message pop-up when running against an inventory that has a certain number of hosts in it.

**Comment by wenottingham** [comment] 2020-09-17 18:33
Warnings in the user interface are generally for destructive operations (deletion, unsaved changes, etc).
Any warnings added here wouldn't be carried over into the service catalog, the CLI, or anything else that uses the API.

If the goal is to gate automation, something like a approval node should be used. 

Closing as a duplicate of #2151.

**Closed as completed by wenottingham** 2020-09-17 18:33 UTC
