### ISSUE TITLE
AWX 19.0.0 make docker-compose 

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#9866] opened 2021-04-09 09:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

We have two AWX installations. Production AWX on IP 192.168.1.86 and Test AWX on IP 192.168.1.87. 

I am upgrading AWX on the test environment, but executing `make docker-compose` results in awx-wsbroadcast attempting to connect to production host.  

Variable for fqdn/hostname is nowhere to be found. Unsure why it is tryng to connect to production env as localhost hostnames are different.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.19
* Operating System: Centos 8.3

##### ACTUAL RESULTS

```
docker-compose -f tools/docker-compose/_sources/docker-compose.yml up 
tools_redis_1 is up-to-date
Creating tools_postgres_1 ... done
Creating tools_awx_1      ... done
Attaching to tools_redis_1, tools_postgres_1, tools_awx_1
tools_postgres_1 | 
tools_postgres_1 | PostgreSQL Database directory appears to contain a database; Skipping initialization
tools_postgres_1 | 
tools_postgres_1 | 2021-04-09 09:38:22.555 UTC [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
tools_postgres_1 | 2021-04-09 09:38:22.565 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
tools_postgres_1 | 2021-04-09 09:38:22.565 UTC [1] LOG:  listening on IPv6 address "::", port 5432
tools_postgres_1 | 2021-04-09 09:38:22.568 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
tools_postgres_1 | 2021-04-09 09:38:22.606 UTC [26] LOG:  database system was shut down at 2021-04-09 09:36:11 UTC
tools_postgres_1 | 2021-04-09 09:38:22.635 UTC [1] LOG:  database system is ready to accept connections
tools_redis_1 | 1:C 09 Apr 2021 09:20:49.873 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
tools_redis_1 | 1:C 09 Apr 2021 09:20:49.873 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
tools_redis_1 | 1:C 09 Apr 2021 09:20:49.873 # Configuration loaded
tools_redis_1 | 1:M 09 Apr 2021 09:20:49.874 * monotonic clock: POSIX clock_gettime
tools_redis_1 | 1:M 09 Apr 2021 09:20:49.876 * Running mode=standalone, port=0.
tools_redis_1 | 1:M 09 Apr 2021 09:20:49.876 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
tools_redis_1 | 1:M 09 Apr 2021 09:20:49.876 # Server initialized
tools_redis_1 | 1:M 09 Apr 2021 09:20:49.876 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
tools_redis_1 | 1:M 09 Apr 2021 09:20:49.876 * The server is now ready to accept connections at /var/run/redis/redis.sock
tools_awx_1 | WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
tools_awx_1 | WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
tools_awx_1 | Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
tools_awx_1 | [ -d "/awx_devel/awx.egg-info" ] || python3.8 /awx_devel/setup.py egg_info_dev
tools_awx_1 | running egg_info_dev
tools_awx_1 | creating awx.egg-info
tools_awx_1 | writing awx.egg-info/PKG-INFO
tools_awx_1 | writing dependency_links to awx.egg-info/dependency_links.txt
tools_awx_1 | writing entry points to awx.egg-info/entry_points.txt
tools_awx_1 | writing top-level names to awx.egg-info/top_level.txt
tools_awx_1 | cp -f /tmp/awx.egg-link /var/lib/awx/venv/awx/lib/python3.8/site-packages/awx.egg-link
tools_awx_1 | mkdir -p /var/lib/awx/; \
tools_awx_1 | if [ "/var/lib/awx/venv/" ]; then \
tools_awx_1 | 	. /var/lib/awx/venv//awx/bin/activate; \
tools_awx_1 | fi; \
tools_awx_1 | python3.8 -c "import awx; print(awx.__version__)" > /var/lib/awx/.awx_version; \
tools_awx_1 | 
tools_awx_1 | if [ "/var/lib/awx/venv/" ]; then \
tools_awx_1 | 	. /var/lib/awx/venv//awx/bin/activate; \
tools_awx_1 | fi; \
tools_awx_1 | awx-manage migrate --noinput
tools_redis_1 | 1:M 09 Apr 2021 09:38:38.903 * 100 changes in 300 seconds. Saving...
tools_redis_1 | 1:M 09 Apr 2021 09:38:38.905 * Background saving started by pid 12
tools_redis_1 | 12:C 09 Apr 2021 09:38:38.910 * DB saved on disk
tools_redis_1 | 12:C 09 Apr 2021 09:38:38.911 * RDB: 2 MB of memory used by copy-on-write
tools_redis_1 | 1:M 09 Apr 2021 09:38:39.005 * Background saving terminated with success
tools_awx_1 | Operations to perform:
tools_awx_1 |   Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
tools_awx_1 | Running migrations:
tools_awx_1 |   Applying conf.0008_subscriptions... OK
tools_awx_1 |   Applying conf.0009_rename_proot_settings... OK
tools_awx_1 |   Applying main.0122_really_remove_cloudforms_inventory... OK
tools_awx_1 |   Applying main.0123_drop_hg_support... OK
tools_awx_1 |   Applying main.0124_execution_environments... OK
tools_awx_1 |   Applying main.0125_more_ee_modeling_changes... OK
tools_awx_1 |   Applying main.0126_executionenvironment_container_options... OK
tools_awx_1 |   Applying main.0127_reset_pod_spec_override... OK
tools_awx_1 |   Applying main.0128_organiaztion_read_roles_ee_admin... OK
tools_awx_1 |   Applying main.0129_unifiedjob_installed_collections... OK
tools_awx_1 |   Applying main.0130_ee_polymorphic_set_null... OK
tools_awx_1 |   Applying main.0131_undo_org_polymorphic_ee... OK
tools_awx_1 |   Applying main.0132_instancegroup_is_container_group... OK
tools_awx_1 |   Applying main.0133_centrify_vault_credtype... OK
tools_awx_1 |   Applying main.0134_unifiedjob_ansible_version... OK
tools_awx_1 |   Applying main.0135_schedule_sort_fallback_to_id... OK
tools_awx_1 | if [ "/var/lib/awx/venv/" ]; then \
tools_awx_1 | 	. /var/lib/awx/venv//awx/bin/activate; \
tools_awx_1 | fi; \
tools_awx_1 | awx-manage provision_instance --hostname=awx_1; \
tools_awx_1 | awx-manage register_queue --queuename=tower --instance_percent=100;\
tools_awx_1 | if [ "tower" == "tower,thepentagon" ]; then \
tools_awx_1 | 	awx-manage provision_instance --hostname=isolated; \
tools_awx_1 | 	awx-manage register_queue --queuename='thepentagon' --hostnames=isolated --controller=tower; \
tools_awx_1 | 	awx-manage generate_isolated_key > /awx_devel/awx/main/isolated/authorized_keys; \
tools_awx_1 | fi;
tools_awx_1 | Successfully registered instance awx_1
tools_awx_1 | (changed: True)
tools_awx_1 | Instance Group already registered tower
tools_awx_1 | 2021-04-09 09:39:07 ERROR rsyslogd was unresponsive: FileNotFoundError: [Errno 2] No such file or directory
tools_awx_1 | Activity Stream update entry for execution_environment
tools_awx_1 | Default Execution Environment(s) registered.
tools_awx_1 | (changed: True)
tools_awx_1 | /usr/local/lib/python3.6/site-packages/supervisor/options.py:475: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
tools_awx_1 |   'Supervisord is running as root and it is searching '
tools_awx_1 | 2021-04-09 09:39:10,166 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
tools_awx_1 | 2021-04-09 09:39:10,198 INFO RPC interface 'supervisor' initialized
tools_awx_1 | 2021-04-09 09:39:10,198 CRIT Server 'unix_http_server' running without any HTTP authentication checking
tools_awx_1 | 2021-04-09 09:39:10,198 INFO supervisord started with pid 105
tools_awx_1 | 2021-04-09 09:39:11,202 INFO spawned: 'stdout' with pid 108
tools_awx_1 | 2021-04-09 09:39:11,204 INFO spawned: 'awx-dispatcher' with pid 109
tools_awx_1 | 2021-04-09 09:39:11,207 INFO spawned: 'awx-receiver' with pid 110
tools_awx_1 | 2021-04-09 09:39:11,210 INFO spawned: 'awx-uwsgi' with pid 111
tools_awx_1 | 2021-04-09 09:39:11,213 INFO spawned: 'awx-daphne' with pid 112
tools_awx_1 | 2021-04-09 09:39:11,217 INFO spawned: 'awx-nginx' with pid 113
tools_awx_1 | 2021-04-09 09:39:11,220 INFO spawned: 'awx-wsbroadcast' with pid 114
tools_awx_1 | 2021-04-09 09:39:11,235 INFO spawned: 'awx-rsyslogd' with pid 115
tools_awx_1 | 2021-04-09 09:39:11,249 INFO spawned: 'awx-receptor' with pid 119
tools_awx_1 | 2021-04-09 09:39:11,429 INFO exited: awx-nginx (exit status 2; not expected)
tools_awx_1 | 2021-04-09 09:39:12,525 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,525 INFO success: awx-dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,525 INFO success: awx-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,526 INFO success: awx-uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,526 INFO success: awx-daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,528 INFO spawned: 'awx-nginx' with pid 164
tools_awx_1 | 2021-04-09 09:39:12,528 INFO success: awx-wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,528 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:12,529 INFO success: awx-receptor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | awx-dispatcher stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-dispatcher stdout | 
tools_awx_1 | awx-receiver stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-daphne stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-daphne stdout | 
tools_awx_1 | awx-uwsgi stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-wsbroadcast stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
tools_awx_1 | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-receptor stdout | INFO 2021/04/09 09:39:12 Running control service control
tools_awx_1 | awx-receptor stdout | 
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | 2021-04-09 09:39:12,611 INFO exited: awx-nginx (exit status 2; not expected)
tools_awx_1 | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
tools_awx_1 | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-receptor stdout | INFO 2021/04/09 09:39:12 Initialization complete
tools_awx_1 | awx-receptor stdout | 
tools_awx_1 | 2021-04-09 09:39:14,643 INFO spawned: 'awx-nginx' with pid 174
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | 2021-04-09 09:39:14,884 INFO exited: awx-nginx (exit status 2; not expected)
tools_awx_1 | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
tools_awx_1 | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,845 INFO     [-] daphne.cli Starting server at tcp:port=8051:interface=127.0.0.1
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,845 INFO     Starting server at tcp:port=8051:interface=127.0.0.1
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,846 INFO     [-] daphne.server HTTP/2 support not enabled (install the http2 and tls Twisted extras)
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,846 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
tools_awx_1 | awx-daphne stdout | 
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,847 INFO     [-] daphne.server Configuring endpoint tcp:port=8051:interface=127.0.0.1
tools_awx_1 | awx-daphne stdout | 
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,847 INFO     Configuring endpoint tcp:port=8051:interface=127.0.0.1
tools_awx_1 | awx-daphne stdout | 
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,849 INFO     [-] daphne.server Listening on TCP address 127.0.0.1:8051
tools_awx_1 | awx-daphne stdout | 2021-04-09 09:39:15,849 INFO     Listening on TCP address 127.0.0.1:8051
tools_awx_1 | awx-daphne stdout | 
tools_awx_1 | awx-uwsgi stdout | *** Starting uWSGI 2.0.18 (64bit) on [Fri Apr  9 09:39:16 2021] ***
tools_awx_1 | awx-uwsgi stdout | compiled with version: 8.3.1 20191121 (Red Hat 8.3.1-5) on 08 April 2021 13:09:36
tools_awx_1 | awx-uwsgi stdout | os: Linux-4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020
tools_awx_1 | awx-uwsgi stdout | nodename: awx_1
tools_awx_1 | awx-uwsgi stdout | machine: x86_64
tools_awx_1 | awx-uwsgi stdout | clock source: unix
tools_awx_1 | awx-uwsgi stdout | detected number of CPU cores: 4
tools_awx_1 | awx-uwsgi stdout | current working directory: /awx_devel
tools_awx_1 | awx-uwsgi stdout | detected binary path: /var/lib/awx/venv/awx/bin/uwsgi
tools_awx_1 | awx-uwsgi stdout | !!! no internal routing support, rebuild with pcre support !!!
tools_awx_1 | awx-uwsgi stdout | uWSGI running as root, you can use --uid/--gid/--chroot options
tools_awx_1 | awx-uwsgi stdout | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tools_awx_1 | awx-uwsgi stdout | chdir() to /awx_devel/
tools_awx_1 | awx-uwsgi stdout | your memory page size is 4096 bytes
tools_awx_1 | awx-uwsgi stdout |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
tools_awx_1 | awx-uwsgi stdout | detected max file descriptor number: 1048576
tools_awx_1 | awx-uwsgi stdout | lock engine: pthread robust mutexes
tools_awx_1 | awx-uwsgi stdout | thunder lock: disabled (you can enable it with --thunder-lock)
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | uwsgi socket 0 bound to TCP address 127.0.0.1:8050 fd 3
tools_awx_1 | awx-uwsgi stdout | uWSGI running as root, you can use --uid/--gid/--chroot options
tools_awx_1 | awx-uwsgi stdout | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tools_awx_1 | awx-uwsgi stdout | Python version: 3.8.3 (default, Aug 31 2020, 16:03:14)  [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
tools_awx_1 | awx-uwsgi stdout | PEP 405 virtualenv detected: /var/lib/awx/venv/awx
tools_awx_1 | awx-uwsgi stdout | Set PythonHome to /var/lib/awx/venv/awx
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | Python main interpreter initialized at 0x882240
tools_awx_1 | awx-uwsgi stdout | uWSGI running as root, you can use --uid/--gid/--chroot options
tools_awx_1 | awx-uwsgi stdout | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tools_awx_1 | awx-uwsgi stdout | python threads support enabled
tools_awx_1 | awx-uwsgi stdout | your server socket listen backlog is limited to 100 connections
tools_awx_1 | awx-uwsgi stdout | your mercy for graceful operations on workers is 60 seconds
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | mapped 609552 bytes (595 KB) for 5 cores
tools_awx_1 | awx-uwsgi stdout | *** Operational MODE: preforking ***
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | uWSGI running as root, you can use --uid/--gid/--chroot options
tools_awx_1 | awx-uwsgi stdout | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tools_awx_1 | awx-uwsgi stdout | *** uWSGI is running in multiple interpreter mode ***
tools_awx_1 | awx-uwsgi stdout | spawned uWSGI master process (pid: 203)
tools_awx_1 | awx-uwsgi stdout | spawned uWSGI worker 1 (pid: 204, cores: 1)
tools_awx_1 | awx-uwsgi stdout | spawned uWSGI worker 2 (pid: 205, cores: 1)
tools_awx_1 | awx-uwsgi stdout | spawned uWSGI worker 3 (pid: 206, cores: 1)
tools_awx_1 | awx-uwsgi stdout | spawned uWSGI worker 4 (pid: 207, cores: 1)
tools_awx_1 | awx-uwsgi stdout | spawned uWSGI worker 5 (pid: 208, cores: 1)
tools_awx_1 | awx-uwsgi stdout | *** Stats server enabled on /tmp/stats.socket fd: 17 ***
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | Python auto-reloader enabled
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:17,713 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:217
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:17,750 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:219
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:17,759 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:221
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:17,768 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:222
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:17,824 WARNING  [-] awx.main.wsbroadcast Adding {'awx'} to websocket broadcast list
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | 2021-04-09 09:39:18,569 INFO spawned: 'awx-nginx' with pid 230
tools_awx_1 | awx-dispatcher stdout | 2021-04-09 09:39:18,565 ERROR    [-] awx.main.tasks Host awx last checked in at 2021-04-08 12:56:25.080210+00:00, marked as lost.
tools_awx_1 | awx-dispatcher stdout | 
tools_awx_1 | awx-nginx stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx -g "daemon off;"
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | 2021-04-09 09:39:18,855 INFO exited: awx-nginx (exit status 2; not expected)
tools_awx_1 | 2021-04-09 09:39:18,855 INFO gave up: awx-nginx entered FATAL state, too many start retries too quickly
tools_awx_1 | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
tools_awx_1 | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'
tools_awx_1 | awx-nginx stdout | 
tools_awx_1 | 2021-04-09 09:39:19,450 INFO waiting for awx-rsyslogd to stop
tools_awx_1 | 2021-04-09 09:39:19,471 INFO stopped: awx-rsyslogd (exit status 0)
tools_awx_1 | 2021-04-09 09:39:19,511 INFO spawned: 'awx-rsyslogd' with pid 237
tools_awx_1 | 2021-04-09 09:39:20,515 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | awx-uwsgi stdout | WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x882240 pid: 208 (default app)
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x882240 pid: 205 (default app)
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x882240 pid: 204 (default app)
tools_awx_1 | awx-uwsgi stdout | running "exec: supervisorctl restart tower-processes:awx-dispatcher tower-processes:awx-receiver" (accepting1)...
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x882240 pid: 207 (default app)
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | awx-uwsgi stdout | WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x882240 pid: 206 (default app)
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | 2021-04-09 09:39:21,838 INFO waiting for awx-dispatcher to stop
tools_awx_1 | 2021-04-09 09:39:21,844 INFO stopped: awx-dispatcher (terminated by SIGKILL)
tools_awx_1 | 2021-04-09 09:39:21,846 INFO waiting for awx-receiver to stop
tools_awx_1 | 2021-04-09 09:39:21,856 INFO stopped: awx-receiver (terminated by SIGKILL)
tools_awx_1 | 2021-04-09 09:39:21,864 INFO spawned: 'awx-dispatcher' with pid 265
tools_awx_1 | awx-dispatcher stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-dispatcher stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:21,917 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | 2021-04-09 09:39:22,918 INFO success: awx-dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | 2021-04-09 09:39:22,922 INFO spawned: 'awx-receiver' with pid 274
tools_awx_1 | awx-receiver stdout | make[1]: Entering directory '/awx_devel'
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | 2021-04-09 09:39:23,978 INFO success: awx-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | awx-uwsgi stdout | tower-processes:awx-dispatcher: stopped
tools_awx_1 | awx-uwsgi stdout | tower-processes:awx-receiver: stopped
tools_awx_1 | awx-uwsgi stdout | tower-processes:awx-dispatcher: started
tools_awx_1 | awx-uwsgi stdout | tower-processes:awx-receiver: started
tools_awx_1 | awx-uwsgi stdout | 
tools_awx_1 | 2021-04-09 09:39:26,395 INFO waiting for awx-rsyslogd to stop
tools_awx_1 | 2021-04-09 09:39:26,398 INFO stopped: awx-rsyslogd (exit status 0)
tools_awx_1 | 2021-04-09 09:39:26,403 INFO spawned: 'awx-rsyslogd' with pid 298
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:26,713 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:300
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:26,725 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:302
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:26,733 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:303
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-receiver stdout | 2021-04-09 09:39:26,741 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:304
tools_awx_1 | awx-receiver stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:26,928 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | 2021-04-09 09:39:27,931 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:31,943 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:36,959 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:41,975 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:47,009 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:52,023 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:39:57,034 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:40:02,049 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
tools_awx_1 | awx-wsbroadcast stdout | 2021-04-09 09:40:07,063 WARNING  [-] awx.main.wsbroadcast Connection from awx_1 to awx failed: 'Cannot connect to host awx:8013 ssl:False [Connect call failed ('192.168.1.86', 8013)]'.
tools_awx_1 | awx-wsbroadcast stdout | 
^CGracefully stopping... (press Ctrl+C again to force)
Stopping tools_awx_1      ... done
Stopping tools_postgres_1 ... done
Stopping tools_redis_1    ... done
```

**Comment by shanemcd** [comment] 2021-04-09 12:34
Dupe of https://github.com/ansible/awx/issues/9552

**Closed as completed by shanemcd** 2021-04-09 12:34 UTC
Labels: type:bug

**Comment by nicolaibaralmueller** [comment] 2021-04-15 11:35
> Dupe of #9552

No. That is not the same issue. I tried adding the following workaround and it did not solve the issue:

https://github.com/ansible/awx/issues/9552#issuecomment-816710547

**Comment by garnser** [comment] 2021-05-04 10:57
I've been testing to run a docker install since the 18.0.0 release and are seeing the same issues as well on a vanilla installation. 

Combining #9552 with `docker rename awx_tools_1 awx` seams to do the trick however
