### ISSUE TITLE
Editing user switcharoo

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1022] opened 2018-01-19 16:26 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- UI

##### ENVIRONMENT
* AWX version: devel

##### SUMMARY
A short time after clicking to edit a user in the UI; the UI switches what user I am editing.

![r4fzgpcwsv](https://user-images.githubusercontent.com/722880/35160588-918fc388-fd0b-11e7-92b3-5d847b28ac9e.gif)

Might be related/duplicate #1025

**Comment by ryanpetrello** [comment] 2018-08-13 18:09
This is caused by your usage of LastPass.  `wontfix`

**Closed as completed by ryanpetrello** 2018-08-13 18:09 UTC
Labels: type:bug, component:ui
