### ISSUE TITLE
Dropdown input for the inventory section does not allow typing anything.

### ISSUE THREAD

**Issue by ndelaossar** [ansible/awx#9545] opened 2021-03-10 18:24 UTC
##### ISSUE TYPE
 - Bug Report: UI Issue

##### SUMMARY
Starting version 16.0.0 I'm having some issues with the dropdown inputs located in the inventory section.
Basically, when I'm trying to input a file path for my inventory the dropdown doesn't allow me to write any text.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method:  docker on linux
* Ansible version:  2.10.6
* Operating System: Centos 8
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

Inventories > Inventory_name > Sources > Source_name > Inventory file

##### EXPECTED RESULTS

Version 15.0.1
![image](https://user-images.githubusercontent.com/22649727/110677691-72c38280-81a3-11eb-8088-59181dddb5f9.png)

##### ACTUAL RESULTS

Version 17.0.1
![image](https://user-images.githubusercontent.com/22649727/110677842-a1415d80-81a3-11eb-82c6-e26c4f4dbbd1.png)

**Comment by AndreasFrangopoulos** [comment] 2021-03-11 17:36
Anyone know a way to hack in the filename with the cli or API?

**Comment by jakemcdermott** [comment] 2021-03-12 17:54
:wave: This should be address in the next awx release. 

(duplicate of https://github.com/ansible/awx/issues/9043, closing)

**Closed as completed by jakemcdermott** 2021-03-12 17:54 UTC
Labels: type:bug
