### ISSUE TITLE
AWX 9.2 stops processing jobs

### ISSUE THREAD

**Issue by wbieniek** [ansible/awx#6132] opened 2020-03-02 14:16 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX stops processing/accepting new callback jobs,pending jobs grown to 5K in few hours. There is no running jobs.
We have 6K servers in AWX with callbacks configured to check back every 6 hours.
Only way to fix it is to delete all pending jobs and processing will start again for few hours, then stops again.

##### ENVIRONMENT
* AWX version: 9.2
* AWX install method: openshift with 15 pods
 Ansible version:  X.Y.Z
* Operating System:RH7
* Web Browser:

##### STEPS TO REPRODUCE

Upgrade to 9.2 from 9.1 

##### ACTUAL RESULTS

Upgraded to 9.2 from 9.1 and within hours AWX stopped processing new requests

##### ADDITIONAL INFORMATION

Reverted to 9.1 and all is good again.

**Comment by wbieniek** [comment] 2020-03-02 14:21
We also have stage AWX 9.2 deployment on OpenShift with 2 pods and 60 hosts under management and we never experience any issues there.

**Comment by ryanpetrello** [comment] 2020-03-02 14:21
Duplicate of https://github.com/ansible/awx/issues/5617

**Comment by ryanpetrello** [comment] 2020-03-02 14:22
@wbieniek,

If you're interested, I'm looking for people to check if https://github.com/ansible/awx/pull/6093 resolves the issue for them (a few people - including one in issue #5617 - have reported promising results).

**Closed as completed by ryanpetrello** 2020-03-02 14:21 UTC
