### ISSUE TITLE
Encrypted value throws callback error

### ISSUE THREAD

**Issue by marshyonline** [ansible/awx#4478] opened 2019-08-14 06:50 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When setting an encrypted fact via Set_facts, a call back error is thrown.
This behaviour is not present on AWX 2.1.2.0 (We just upgraded)

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker
* Ansible version:  2.8.3
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

```---
- hosts: localhost
  gather_facts: yes
  tasks:
  - set_fact:
      password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38343532363661666437303861616639373964643366626266613233663631656430303136366366
          3037663963356531623037663362353639316437333330380a633839343233396266353863343263
          65373638613332626534373166373864623639363364306435346662656438346332313763323165
          6464353231386336330a363837393937656635326536646434313864393162383831393336386235
          3535
  
  - debug: msg="My password value is {{ password }}"
```

##### EXPECTED RESULTS

For a callback error not to be thrown

##### ACTUAL RESULTS

```PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.awx_display.CallbackModule object at
0x7fe7177839d0>): u'123456789' is not JSON serializable

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "My password value is 123456789"
}
```

##### ADDITIONAL INFORMATION

The string is decrypted correctly and the play will finish successfully

**Comment by AlanCoding** [comment] 2019-08-14 12:47
I'm going to try to reproduce this, but first I want to clarify - before running the job template in this case, I am assuming you applied a vault credential containing the secret?

**Comment by marshyonline** [comment] 2019-08-14 13:13
That's correct, AWX is decrypting the string successfully as shown the in output but throwing the callback error in the process

**Comment by AlanCoding** [comment] 2019-08-14 13:15
Thanks, I was able to reproduce:

https://github.com/AlanCoding/utility-playbooks/blob/master/set_vault_var.yml

```
Callback Exception: 
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 323, in send_callback
    method(*new_args, **kwargs)
   File "/venv/awx/lib/python3.6/site-packages/ansible_runner/display_callback/module.py", line 362, in v2_runner_on_ok
    with self.capture_event_data('runner_on_ok', **event_data):
   File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
   File "/venv/awx/lib/python3.6/site-packages/ansible_runner/display_callback/module.py", line 94, in capture_event_data
    event_context.dump_begin(sys.stdout)
   File "/venv/awx/lib/python3.6/site-packages/ansible_runner/display_callback/events.py", line 171, in dump_begin
    self.cache.set(":1:ev-{}".format(begin_dict['uuid']), begin_dict)
   File "/venv/awx/lib/python3.6/site-packages/ansible_runner/display_callback/events.py", line 51, in set
    partial_data = json.dumps(value)
   File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
   File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
   File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
   File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

Ansible development version.

**Comment by kdelee** [comment] 2019-09-03 21:02
works for me!

**Comment by kdelee** [comment] 2019-09-04 13:19
well, I'm confused. Closed this because I tried it out on devel with your playbook @AlanCoding and it worked fo rme. I am not sure why this is in needs_test if nothing was merged.

**Comment by AlanCoding** [comment] 2019-09-04 13:25
Oh sorry, the fix was https://github.com/ansible/ansible-runner/pull/331, which was merged 16 days ago... but the last release was April 25th.

So if you used any sort of default AWX install, you should still be seeing the bug, but then you should be able to install development ansible-runner to see it fixed. If you are not seeing the bug then that's problematic.

This is also highly dependent on Ansible version, but I thought the bug existed in 2.8 and 2.9 versions.

**Comment by elyezer** [comment] 2019-10-02 19:35
Did the following to verify this:

1) Created a project to sync https://github.com/AlanCoding/utility-playbooks.git
2) Created a Vault credential with the password for the vault value
3) Created a job template to run https://github.com/AlanCoding/utility-playbooks/blob/master/set_vault_var.yml. Also added the Vault credential to the job template.
4) Ran the job template and no callback error was thrown. Instead the job passed and the vault value was shown as expected.

**Closed as completed** 2019-10-02 19:35 UTC
Labels: type:bug, component:api
