### ISSUE TITLE
Cluster HostID on docker

### ISSUE THREAD

**Issue by Yoiro** [ansible/awx#2650] opened 2018-11-09 15:26 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Whenever I try to add new values into AWX through the UI I get the message "Failed to create new project. POST returner status: 500 A server error has occured.". awx_web logs are in pastebin link below.

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method:  docker on linux 
* Ansible version:  
       - awx_* container: 2.7.1
       - host os: 2.7.0
* Operating System: 
       - awx_* container: Centos 7
       - host os: RHEL7
* Web Browser: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

I just reinstalled the new version (I was in 1.0.6 before): 
  - Created a new DB on a remote Postgres host
  (- I may have forgotten to shutdown old containers before relaunching install.yaml)
  - Log in AWX with freshly created system admin
  - Perform data_migration through tower-cli
  - Notice that a lot of data weren't written in database
  - Try to manually insert a new project in AWX from the UI.

##### EXPECTED RESULTS

A new project is created

##### ACTUAL RESULTS

Got a popup containing following message : "Failed to create new project. POST returned status: 500 A server error has occured.".

##### ADDITIONAL INFORMATION

awx_web logs: https://pastebin.com/jL1b5K4u

**Comment by wenottingham** [comment] 2018-11-09 15:40
This appears to be a duplicate of #2482

**Closed as completed by wenottingham** 2018-11-09 15:40 UTC

**Comment by Yoiro** [comment] 2018-11-09 15:48
It is indeed, sorry I haven't found it before.
