### ISSUE TITLE
Container dont share /var/lib/awx problem with local files

### ISSUE THREAD

**Issue by mkayontour** [ansible/awx#778] opened 2017-12-08 13:31 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
The container Tasks and Web can't access the same /var/lib/awx directory. This gives troubles if you wan't to use local playbooks without a remote source or remote version control system. 

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.x
* Operating System: Debian Jessie
* Web Browser: Chrome

##### STEPS TO REPRODUCE
create some playbooks at the projects directory of AWX -> /var/lib/awx/projects
create a new project with local source pointing to your playbooks. 
run a template with one of your playbooks which are part of that local project and the playbook can't be found on the tasks container. 

##### EXPECTED RESULTS
Have the ability to use also local playbooks on both container. When I'm not able to use a remote source.

##### ADDITIONAL INFORMATION
The manual fix would be mounting both container on the same local lib directory. But as it's a poor workaround I would be happy if would try to support that method so I can safely upgrade my AWX installation on further releases: 

```
--- a/installer/local_docker/tasks/main.yml
+++ b/installer/local_docker/tasks/main.yml
@@ -162,6 +162,8 @@
     name: awx_web
     state: started
     restart_policy: unless-stopped
     image: "{{ awx_web_docker_actual_image }}"
+    volumes:
+      - "{{ awx_lib_dir }}:/var/lib/awx/projects/"
     user: root
     ports:
       - "{{ host_port }}:8052"
@@ -191,8 +193,12 @@
   docker_container:
     name: awx_task
     state: started
     restart_policy: unless-stopped
     image: "{{ awx_task_docker_actual_image }}"
+    volumes:
+      - "{{ awx_lib_dir }}:/var/lib/awx/projects/"
     links: "{{ awx_task_container_links|list }}"
     user: root
     hostname: awx
```

**Comment by tchia04** [comment] 2017-12-08 22:24
duplicate of https://github.com/ansible/awx/issues/675

**Closed as completed** 2017-12-08 22:28 UTC

**Comment by mkayontour** [comment] 2017-12-13 19:43
Sorry, please don't close the issue yet without additional information, I know how to manually fix the problem. But we need to know if the AWX Team will do something about this issue in future? 

I don't want to fix this issue with every update, any thoughts?

**Comment by fredt34** [comment] 2019-04-12 05:56
Fixed, but the documentation is quite poor...

Now we just have to uncomment ````;project_data_dir=/var/lib/awx/projects```` in ````inventory```` and run ````ansible-playbook -i inventory install.yml```` again.

_This is probably obvious for those-who-know, but helpful for newcomers to Docker:_
If your system is already up and running, go to your docker_compose_dir, run ````docker-compose stop```` to stop your containers, switch back to your awx/installer and re-run the playbook.
