### ISSUE TITLE
Postgres regularly corrupts data

### ISSUE THREAD

**Issue by b-t-927** [ansible/awx#3473] opened 2019-03-21 22:56 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Postgres

##### SUMMARY
Postgres regularly (every week or so) corrupts its database, causing an internal server error in AWX frontend

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.6
* Operating System: Centos 7.5
* Web Browser: Google Chrome
* Docker version: 18.09.3

##### ACTUAL RESULTS
Postgres container logs full of:
```
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
ERROR:  could not open file "base/12407/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
ERROR:  could not open file "base/12407/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
FATAL:  could not open file "base/16384/2601": No such file or directory
```
necessitating a restore from backup. Nothing before the corruption indicates any issues.

##### ADDITIONAL INFORMATION
Postgres' data volume is in /tmp/pgdocker

Seems to be related to: https://github.com/ansible/awx/issues/1212

**Comment by ryanpetrello** [comment] 2019-04-26 20:09
Duplicate of https://github.com/ansible/awx/issues/1212

**Closed as completed by ryanpetrello** 2019-04-26 20:09 UTC
Labels: type:bug
