### ISSUE TITLE
Error message for Inventory lookup on job templates appear in wrong place

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8175] opened 2020-09-18 13:15 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The error message for inventory lookup inside Job templates form appears in wrong place

##### ENVIRONMENT
* AWX version: 2.9.11
* AWX install method: docker for mac
* Ansible version:  14.1.0
* Operating System: Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Job Templates
2. Click on Inventory lookup field
3. Close the Inventory modal

##### EXPECTED RESULTS

The message "Please select an Inventory or check the Prompt on Launch option." should appear below the lookup field

##### ACTUAL RESULTS

The message appears on the right side of the field

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/12464858/93601572-c47b1500-f997-11ea-8223-b4c50b0c6d80.png)

**Comment by marshmalien** [comment] 2020-11-05 19:02
Duplicate of https://github.com/ansible/awx/issues/8283

**Closed as completed** 2020-11-05 19:03 UTC
Labels: type:bug
