### ISSUE TITLE
 => ERROR importing cache manifest from quay.io/awx/awx_devel:devel  

### ISSUE THREAD

**Issue by yeranosyanvahan** [ansible/awx#9935] opened 2021-04-17 20:45 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I am having issue at the installation phase

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: github, from here 
* Ansible version:  2.7.7
* Operating System: debian 10 buster
* Web Browser:

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/awx.git
cd awx
make docker-compose-build

##### EXPECTED RESULTS

I expect it the error to disappear
##### ACTUAL RESULTS

`
DOCKER_BUILDKIT=1 docker build -t quay.io/awx/awx_devel:devel \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --cache-from=quay.io/awx/awx_devel:devel .
[+] Building 2.1s (9/46)                                                                                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                                                                        0.1s
 => => transferring dockerfile: 38B                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                           0.1s
 => => transferring context: 34B                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/centos:8                                                                                                                                 0.0s
 => ERROR importing cache manifest from quay.io/awx/awx_devel:devel                                                                                                                         1.0s
 => [internal] helper image for file operations                                                                                                                                             0.1s
 => => resolve docker.io/docker/dockerfile-copy:v0.1.9@sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e61ca5788f6a6e9d304061                                                              0.0s
 => => sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e61ca5788f6a6e9d304061 2.03kB / 2.03kB                                                                                              0.0s
 => => sha256:a546a4352bcaa6512f885d24fef3d9819e70551b98535ed1995e4b567ac6d05b 736B / 736B                                                                                                  0.0s
 => => sha256:494e63343c3f0d392e7af8d718979262baec9496a23e97ad110d62b9c90d6182 766B / 766B                                                                                                  0.0s
 => [internal] load build context                                                                                                                                                           0.1s
 => => transferring context: 1.19kB                                                                                                                                                         0.0s
 => CANCELED FROM quay.io/project-receptor/receptor:0.9.7                                                                                                                                   0.1s
 => => resolve quay.io/project-receptor/receptor:0.9.7                                                                                                                                      0.1s
 => [stage-1 1/31] FROM docker.io/library/centos:8                                                                                                                                          0.0s
 => => resolve docker.io/library/centos:8                                                                                                                                                   0.0s
 => CANCELED [stage-1 2/31] RUN dnf -y module enable 'postgresql:12'                                                                                                                        0.9s
------
 > importing cache manifest from quay.io/awx/awx_devel:devel:
------
error on cache query: invalid build cache from {MediaType:application/vnd.docker.distribution.manifest.v2+json Digest:sha256:a5bbfc34d4ccacad34a90fb776527243ad71d2f0527a08361488153f9bfcdb7e Size:6806 URLs:[] Annotations:map[] Platform:<nil>}
make: *** [Makefile:503: docker-compose-build] Error 1
`

**Comment by shanemcd** [comment] 2021-04-18 14:44
Did you try searching for existing issues before opening this? Dupe of https://github.com/ansible/awx/issues/9881

**Closed as completed by shanemcd** 2021-04-18 14:44 UTC
Labels: type:bug
