### ISSUE TITLE
awx.awx.tower_notification_template drops custom messages to defaults for non slack type templates

### ISSUE THREAD

**Issue by bankinobi** [ansible/awx#9603] opened 2021-03-17 11:56 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Module updates custom messages only for "Slack" notification type. When any other type chosen (e.g. webhook), module drops custom messages to default values.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.10.6

##### STEPS TO REPRODUCE

My task for notification templates:
```
- name: "Notification template {{ notification.name }}"
  awx.awx.tower_notification_template:
    name: "{{ notification.name }}"
    organization: "{{ notification.organization }}"
    notification_type: "{{ notification.type }}"
    notification_configuration: "{{ notification.configuration }}"
    messages:
      started:
        message: "{{ notification.messages.started | default(omit) }}"
      success:
        message: "{{ notification.messages.success | default(omit) }}"
      error:
        message: "{{ notification.messages.error | default(omit) }}"
    tower_host: "{{ awx_tower_host }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: "{{ awx_tower_verify_ssl }}"
  connection: local
  register: notifications
  until: notifications is succeeded
```

Input data:
```
awx_notifications:
  - name: discord
    organization: Testorg
    type: webhook
    configuration:
      url: https://test.url.com
      headers:
        Content-Type: application/json
    messages:
      started: "{{ '{{ job_friendly_name }}{{ job.id }} started' }}"
      success: "{{ '{{ job_friendly_name }} completed in {{ job.elapsed }} seconds' }}"
      error: "{{ '{{ job_friendly_name }} FAILED! Please look at {{ job.url }}' }}"
```

##### EXPECTED RESULTS

Custom messages updated regarding to my config

##### ACTUAL RESULTS

All affected message types dropped to default value "{{ job_metadata }}"

**Comment by ryanpetrello** [comment] 2021-03-19 17:23
@beeankha @john-westcott-iv @sean-m-sullivan any of you able to reproduce this, or have any ideas about what might be up?

**Comment by sean-m-sullivan** [comment] 2021-03-24 14:21
So Notifications are counterintuitive and require trial and error to get them working. Add to that ansible doesn't like passing strings with double curly brackets in them because they think they are variables. AND tower wants the messages to be in a json dict format. So this is what I found works, what it looks like is that tower is rejecting your values and then just not giving an error message, It should give an error but if the tower api responds 201, then the modules just assume everything was posted correctly. 

Here is the playbook where I made it work, note the regex replace, and the double spaces in the first curlies to avoid the variable substitution. I and the tower configuration collection have been using that to use this module for over a year now, and it would be a problem with any other ansible code for any other api. 

```
- name: Test omit
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    notification:
      messages:
        started:
          body: '{"body": "{  { job_friendly_name }}{  { job.id }} started"}'
        success:
          body: '{"body": "{  { job_friendly_name }} completed in {  { job.elapsed }} seconds"}'
        error:
          body: '{"body": "{  { job_friendly_name }} FAILED! Please look at {  { job.url }}"}'


  tasks:
    - name: "Notification template {{ notification.name }}"
      awx.awx.tower_notification_template:
        name: Test-omit
        organization: Default 
        notification_type: webhook
        notification_configuration:
          url: http://www.example.com/hook
          headers:
            X-Custom-Header: value123
          http_method: POST
          disable_ssl_verification: false
          username: ''
          password: ''
        messages: "{{ notification.messages | default(omit, true) | regex_replace('[ ]{2,}','') }}"
        tower_host: https://10.42.42.239
        tower_username: admin
        tower_password: password
        tower_verify_ssl: false
      register: notifications
    
    - debug:
        var: notifications
 ```

**Comment by beeankha** [comment] 2021-04-27 20:03
@bankinobi have you tried the solution suggested by @sean-m-sullivan above?

**Comment by beeankha** [comment] 2021-05-04 15:37
@bankinobi I'm gonna go ahead and close this issue, please re-open if what was suggested by @sean-m-sullivan doesn't work for you.

**Closed as completed by beeankha** 2021-05-04 15:37 UTC
Labels: type:bug, component:awx_collection
