### ISSUE TITLE
Demo Job Template run fails; source control update error: 'overlay' is not supported over overlayfs

### ISSUE THREAD

**Issue by lo78cn** [ansible/awx#10099] opened 2021-05-04 11:26 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Demo Job Template run fails; source control update error: 'overlay' is not supported over overlayfs 

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Debian 10.9
* Web Browser: Brave version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (x86_64)

##### STEPS TO REPRODUCE
* git clone repo
* apply fix #9552 (nginx user missing)
* make docker-compose-build
* control + c
* start Docker containers
* make docker-compose
* docker exec tools_awx_1 make clean-ui ui-devel
* GUI: login: admin user
* GUI: resources > templates > Demo Job Template > launch
* GUI: views > jobs > 3 — Demo Project

##### EXPECTED RESULTS

successful job

##### ACTUAL RESULTS

job status failed

```
WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
```

##### ADDITIONAL INFORMATION

**Comment by Valvos420** [comment] 2021-05-05 08:26
Hello, which version of docker do you use ?

**Comment by lo78cn** [comment] 2021-05-05 08:31
```
docker version
Client: Docker Engine - Community
Version:           20.10.6

docker-compose version
docker-compose version 1.29.1, build c34c88b2

**Comment by garnser** [comment] 2021-05-05 13:13
Running into the same issue, using the following versions

```
docker-ce-20.10.1-3.el8.x86_64
docker-compose==1.27.4
```

**Comment by benapetr** [comment] 2021-05-17 09:57
this issue can be worked over by uncommenting mount_program in /etc/containers/containers.conf

**Comment by noesberger** [comment] 2021-05-18 17:51
> this issue can be worked over by uncommenting mount_program in /etc/containers/containers.conf

I'm running Centos 8.3 (CentOS Linux release 8.3.2011)
With Docker (Docker version 20.10.6, build 370c289)

I have the overlay error, but I don't have a folder /etc/containers. So how I can fix the issue on my centos system?

**Comment by benapetr** [comment] 2021-05-18 18:34
that folder is in your container, you need to `docker exec -it <container> bash` inside there ;)

**Comment by garnser** [comment] 2021-05-18 18:59
> that folder is in your container, you need to `docker exec -it <container> bash` inside there ;)

If so shouldn't the build exclude the mount_program option, or have an option to have it?

**Comment by benapetr** [comment] 2021-05-19 13:40
of course it should, I am not saying this is not a bug, AWX is full of bugs, I am just telling you a workaround for it.

**Comment by razgrim** [comment] 2021-06-07 15:48
Replicated issue. 
AWX version: 19.2.0
AWX install method: docker on linux
Ansible version: 2.9.21
Operating System: Centos Stream 8
Web Browser: Chrome Version 91.0.4472.77 (Official Build) (64-bit)

Same repro steps. 
```
[root@corp-util03 localadmin]# docker exec -it tools_awx_1 bash
bash-4.4# dir /etc/containers/
certs.d  libpod.conf  oci  policy.json  registries.conf  registries.conf.d  registries.d  storage.conf
```
I found and uncommented "mount_program" in /etc/containers/storage.conf. Re-running job presented with a new error
```
WARN[0001] Failed to add conmon to systemd sandbox cgroup: dial unix /run/systemd/private: connect: no such file or directory
Error: OCI runtime error: systemd cgroup flag passed, but systemd support for managing cgroups is not available
```

**Comment by Mr-Philipp** [comment] 2021-06-30 08:58
i cherrypicked the bugfix (https://github.com/ansible/awx/pull/10463) but the same problem still occurs.
tested systems:
- debian10
- centos7
- centos8

tetsted version of AWX: 19.2.1 

> this issue can be worked over by uncommenting mount_program in /etc/containers/containers.conf

i do not see this line of code after applying the fix so i can not confirm this workaround.

EDIT: Found a "fix":

enter the main container and edit /etc/containers/storage.conf to

```
[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
```
restart container. profit.

**Comment by silkofix** [comment] 2021-07-29 05:18
> 
> 
> i cherrypicked the bugfix (#10463) but the same problem still occurs.
> tested systems:
> 
>     * debian10
> 
>     * centos7
> 
>     * centos8
> 
> 
> tetsted version of AWX: 19.2.1
> 
> > this issue can be worked over by uncommenting mount_program in /etc/containers/containers.conf
> 
> i do not see this line of code after applying the fix so i can not confirm this workaround.
> 
> EDIT: Found a "fix":
> 
> enter the main container and edit /etc/containers/storage.conf to
> 
> ```
> [storage.options]
> mount_program = "/usr/bin/fuse-overlayfs"
> ```
> 
> restart container. profit.

Yep, it's worked for me. Thx.

**Comment by njtwiseman** [comment] 2021-09-14 20:11
### Update:
Re-spun up a legit Rocky Linux VM (qemu)
uncommenting line 74 does resume expected operation.

### Original: 
"Fix" isn't working for me
Attempting to sync a git project with the development container
Could, potentially, be my setup (running docker in a proxmox lxc debian 10 container)

```
     63 [storage.options.overlay]
     72 # Path to an helper program to use for mounting the file system instead of mounting it
     73 # directly.
     74 #mount_program = "/usr/bin/fuse-overlayfs"
```
Uncommenting line 74 causes:
```
ERRO[0000] error unmounting /var/lib/containers/storage/overlay/db96339afddb243191cf08f618e398977f5cef62e70a6231e14a7e9214ba6160/merged: invalid argument
Error: error mounting storage for container 3c563200514672f8355c2972b0086dcaa193392bb6d33a2863d0ec694f70ac3e: error creating overlay mount to /var/lib/containers/storage/overlay/db96339afddb243191cf08f618e398977f5cef62e70a6231e14a7e9214ba6160/merged, mount_data="nodev,metacopy=on,lowerdir=/var/lib/containers/storage/overlay/l/ENOZFIOSKZMH4SXJV5VTGXM2G3:/var/lib/containers/storage/overlay/l/EDRRUIQZQXB7MXB73HUWLN7LXZ:/var/lib/containers/storage/overlay/l/VURXQYPMM44J3GT7HB35VSCTCF:/var/lib/containers/storage/overlay/l/FD4PIM6A7VAV43RC5V6UMOFTHJ:/var/lib/containers/storage/overlay/l/3QNWUOF2SQQJLBWV2YJ37GAU6C:/var/lib/containers/storage/overlay/l/J2UP34I2ZUKEE5ZKKPOCVS2R55:/var/lib/containers/storage/overlay/l/YTAEYWWZG4BARP7R72UF55E2QF:/var/lib/containers/storage/overlay/l/5FI2FOYFL4Z2WL4JFR2SKQ2TTT:/var/lib/containers/storage/overlay/l/RXPN5XF5WRJP7RDCBK4LBV4SA5:/var/lib/containers/storage/overlay/l/7F7XY7IVJ6UFLH5NDTOT6ZNTBS:/var/lib/containers/storage/overlay/l/OJBXKQMFCFBA6XBKO3VIQIRZM5:/var/lib/container…
fuse-overlayfs: cannot mount: No such file or directory
: exit status 1
```
I checked in container tools_awx_1 /usr/bin/fuse-overlayfs does in fact exist

EDIT: The following is probably irrelevant
For S&Gs I also changed line 8 to read "overlayfs" in stead of "overlay"
```
      5 [storage]
      6 
      7 # Default Storage Driver, Must be set for proper operation.
      8 driver = "overlayfs"
```
which results in a different-ish error
```
ERRO[0000] User-selected graph driver "overlayfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve 
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
```
Which makes me think if I were to change from `overlay` to `overlayfs` I'm not doing it in the right place.

**Closed as completed** 2021-10-28 16:54 UTC
Labels: type:bug
