### ISSUE TITLE
AWX Office Hours Agenda - Dec 13 2022

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#13240] opened 2022-11-28 20:41 UTC
# AWX Office Hours

## Proposed agenda based on topics
* Welcome @john-westcott-iv 
* Gundalow monolog - Quick overview AAP moving to a central (shared) UI component. @gundalow 
* Discussion: Helm development for AWX-Operator @miles-w-3 
* Discussion: Solution for injecting complex extra vars @philipsd6 
* Update: Add retry mechanism to handle intermittent connection issues with Kubernetes logging stream @TheRealHaoLiu 
* Discussion: Issue label for incompliance with Ansible @ng-bsy
* Call to actions @TheRealHaoLiu 
    * Receptor PR, please try
    * Youtube suggestions
    * RDU Ansible Meetups Resuming Jan 2023

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our second meeting will be held on Tuesday, December 13th, 2022 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/13155)
[Meeting recording](https://www.youtube.com/watch?v=xG58czmXPxY)
[Next Meeting](https://github.com/ansible/awx/issues/13325)

See you soon!

**Comment by TheRealHaoLiu** [comment] 2022-11-28 20:43
## Add retry mechanism to handle intermittent connection issues with Kubernetes logging stream
https://github.com/ansible/receptor/pull/683

**Comment by TheRealHaoLiu** [comment] 2022-11-28 20:47
## Proposal: Decouple Rsyslog from web and task subsystem
https://github.com/ansible/awx/issues/13183

**Comment by TheRealHaoLiu** [comment] 2022-11-28 21:09
## Call to action: AWX YouTube Channel Content Request
https://github.com/ansible/awx/issues/13242

**Comment by AlanCoding** [comment] 2022-11-29 21:17
## Discussion: solution for smart inventory hostvars issue

https://github.com/ansible/awx/issues/371

https://github.com/ansible/awx/issues/1999

There are major technical reasons it's unlikely we'll fix both of those issues with updates to smart inventory. I am working on a proposal that we solve the problem via a new inventory type, https://github.com/ansible/awx/pull/13214, combined with a new inventory source type that allows using the constructed inventory plugin. Since so many users reported that the problem is a blocker for using smart inventory, I thought we could get meaningful feedback on the solution approach.

**Comment by philipsd6** [comment] 2022-12-02 16:40
## Discussion: solution for injecting complex extra vars
#1965 opened Jun 6, 2018
#13070 opened after recent Ansible Summit discussion

The original issue was opened 3.5 years ago and @ryanpetrello suggested that:
> &hellip;if we wanted to do this, we'd probably have to write something that crawled the data structure and did replacement on strings nested inside, which _could_ get hairy.

I've opened PR #13267 resolving both issues, and I thought we could get some feedback on the hairiness, before I continue with adjusting the JSON validator and adding tests.

**Comment by miles-w-3** [comment] 2022-12-05 00:02
### Discussion: Helm development for AWX-Operator

Since last spring, work has been done to add

Currently, the main limitation of the chart is that it’s compiled from the kustomize resources, and the operator handles most resource creation while it is running. These items lead to confusion about elements of chart development
- Adding “support” for resources, such as this issue: https://github.com/ansible/awx-operator/pull/1049#event-7935442132
  - The chart just feeds directly into the values file for most resources, so it’s rare that features will be developed back inb the chart
- More sophisticated “templating”/customizing the helm chart: https://github.com/ansible/awx-operator/issues/1131
  - Currently not possible because the files live in kustomize rather than helm - part of the helm chart build is building and pulling over the kustomize files 
- Streamlining the chart build process/ironing out bugs:  
  - https://github.com/ansible/awx-operator/issues/1053
  - newer clone: https://github.com/ansible/awx-operator/issues/1136
  - Other open source helm charts directly use the chart-releaser pipeline to automatically build the chart as part of a release and keep the github pages index file up to date. This is not an option for the current structure because the chart is not stored live in the repo-it is built when needed

Possible considerations:
- Should the helm chart live in its own repo? That would allow chart-releaser to be used, might clean up versioning
- Should resources be managed in helm rather than kustomize? Likely a workflow adjustment for some people, but would make the chart more full-featured - what is the impact of a change like this?

**Comment by john-westcott-iv** [comment] 2022-12-07 16:56
Discuss idea in https://github.com/ansible/awx/issues/13272

**Comment by gundalow** [comment] 2022-12-08 16:24
Quick overview AAP moving to a central (shared) UI component.

**Closed as completed** 2022-12-16 00:25 UTC
