### ISSUE TITLE
When using workflows if a template has a survey should be able to pre-fill out that survey as part of including that template in the workflow

### ISSUE THREAD

**Issue by itewk** [ansible/awx#1684] opened 2018-03-27 15:24 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When using workflows if a template has a survey should be able to pre-fill out that survey as part of including that template in the workflow

##### ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
1. create a template with a survey
2. create a workflow
3. add the template with the survey to the workflow

##### EXPECTED RESULTS
Should be able to fill out the survey when adding the template to the workflow.

##### ACTUAL RESULTS
No option to fill out the survey when adding the template to the workflow.

##### ADDITIONAL INFORMATION
If you mark the inventory or credential as "prompt on launch" then when adding the template to the workflow you can pre-select the correct inventory and credential, the same should hold true for the survey.

**Comment by mabashian** [comment] 2018-03-28 21:18
See https://github.com/ansible/awx/issues/1686#issuecomment-377040089 - I think this is also a duplicate of https://github.com/ansible/awx/issues/169

**Closed as completed by mabashian** 2018-03-28 21:18 UTC
Labels: component:ui
