### ISSUE TITLE
[ui_next] Notification Template Custom messages form validation is not displayed but is applied

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8816] opened 2020-12-10 16:18 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Notification Template Custom messages form validation is not displayed but is applied

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. create or edit a Notification Template
2. Modify with an incorrectly formatted message body in Custom Messages

##### EXPECTED RESULTS
Inline form validation 
OR
Popup with error

##### ACTUAL RESULTS
Inert action

##### ADDITIONAL INFORMATION
![Screen Shot 2020-12-10 at 11 15 01 AM](https://user-images.githubusercontent.com/12446869/101798667-58610680-3ad9-11eb-9399-7d28b9ddb770.png)

**Comment by unlikelyzero** [comment] 2020-12-10 16:18
Filing as medium because it's just bad UX -- not broken functionality. Great opportunity to fix after feature parity.

**Comment by mabashian** [comment] 2021-02-03 20:43
I'm fairly confident this is a dupe of https://github.com/ansible/awx/issues/8898

**Closed as completed by mabashian** 2021-02-03 20:43 UTC
Labels: type:bug, component:ui
