### ISSUE TITLE
AWX 9.0.0 bubblewrap needs setuid permission 

### ISSUE THREAD

**Issue by dmaple-gci** [ansible/awx#5224] opened 2019-11-04 13:59 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Error when running jobs.  "bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems."

##### ENVIRONMENT
* AWX version: 9.0.0
* AWX install method: openshift
* Ansible version:  2.8.5
* Operating System: CentOS 8.0.1905
* Web Browser: Any

##### STEPS TO REPRODUCE

Run SCM Update or Inventory Sync jobs.  No other jobs could be tried because they depend on these two.

##### EXPECTED RESULTS

Jobs complete without error.

##### ACTUAL RESULTS

bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.

##### ADDITIONAL INFORMATION

Worked around error by running `chmod u+s /usr/bin/bwrap` in Dockerfile.j2 template.  Here's a patch that applies the change:

```
diff --git a/installer/roles/image_build/templates/Dockerfile.j2 b/installer/roles/image_build/templates/Dockerfile.j2
index 64d7125..da16a47 100644
--- a/installer/roles/image_build/templates/Dockerfile.j2
+++ b/installer/roles/image_build/templates/Dockerfile.j2
@@ -49,6 +49,8 @@ RUN dnf -y update && \
   xmlsec1-openssl-devel \
   dnf-utils

+RUN chmod u+s /usr/bin/bwrap
+
 ADD https://github.com/krallin/tini/releases/download/v0.14.0/tini /tini
 RUN chmod +x /tini
```

**Comment by shanemcd** [comment] 2019-11-04 15:14
Thanks for reporting this. I am not sure what changed that would have broken this. Perhaps something upstream with bwrap itself. I've reproduced the error, and I am going to apply and test your patch now.

**Comment by dmaple-gci** [comment] 2019-11-04 15:22
It does appear to be a change in the way the bubblewrap package installs on CentOS 8 and RHEL 8.

**Comment by shanemcd** [comment] 2019-11-04 16:56
Fix will be included in AWX 9.0.1 which I'm pushing out now.

**Closed as completed by shanemcd** 2019-11-04 16:56 UTC
Labels: type:bug

**Comment by philipsd6** [comment] 2020-02-25 20:17
This problem also occurs when building the development image ([CONTRIBUTING.md#build-the-base-image](https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#build-the-base-image))

I will submit a PR to resolve the issue in the development Dockerfile as well.

**Comment by kaushik4r** [comment] 2020-06-05 21:32
I still come across this issue while using AWX 11.2.0.

I'm trying to run the pod not using privileged SCC and setting the below within the deployment config of the awx pod -
`      securityContext:
        allowPrivilegeEscalation: false`

The pod comes up just fine, however the SCM update job fails with the below error -

`bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.` 

When i try granting it privileged SCC and set the securityContext to true for privileged access, the SCM update job works just fine. But, I looking to avoid this due to security constraints.

Any suggestions?
