### ISSUE TITLE
Allow selection of project subdirectory

### ISSUE THREAD

**Issue by Weilbyte** [ansible/awx#8791] opened 2020-12-09 07:35 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I have a Git repository that has multiple folders in the root (`ansible`, `packer`, `terraform`) and importing it as a project in AWX works, sort of. But the issue comes in with installing `requirements.yml`, because the file is in `ansible/roles/requirements.yml` it does not seem to get picked up by AWX. 

It would be very nice if there was an option to select a path/directory in the project from which AWX can operate. For example if path is given as `ansible` then all of AWX's future operations will be done from `ansible/` instead of the root of the repository. 

Alternatively, the search for the `requirements.yml` should respect the `roles_path` ansible setting so it can look in the right directory.

**Comment by Weilbyte** [comment] 2020-12-09 09:25
The `requirements.yml` issue: https://github.com/ansible/awx/issues/106

**Comment by wenottingham** [comment] 2020-12-09 18:25
Closing as a duplicate of #106

**Closed as completed by wenottingham** 2020-12-09 18:25 UTC
