### ISSUE TITLE
Better handling of symlinks in project directory

### ISSUE THREAD

**Issue by ghost** [ansible/awx#3450] opened 2019-03-19 22:22 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
We have a project that's shared between all facets of our organization, and looks somewhat like the following

```
.
├── _datacenter
│   ├── network_fabric
│   │   ├── build_arista.yml
│   │   ├── group_vars
│   │   ├── host_vars
│   │   ├── roles
│   │   ├── shared -> /shared/playbooks/
├── _firewalls
│   ├── paloalto
│   │   ├── group_vars
│   │   ├── host_vars
│   │   ├── pb.all.yml
│   │   ├── roles
│   │   └── shared -> /shared/playbooks/
├── _campus
│   ├── group_vars
│   ├── host_vars
│   ├── pb.all.yml
│   ├── roles
│   └── shared -> /shared/playbooks/
├── _mpls
│   ├── group_vars
│   ├── host_vars
│   ├── pb.all.yml
│   ├── roles
│   └── shared -> /shared/playbooks/
└── shared
    └── playbooks
       ├── pb.provision.yml
       ├── pb.reboot.yml
       ├── pb.test.yml
       └── pb.unprovision.yml
```

Ansible core will be able to safely call `ansible-playbook _mpls/shared/pb.provision.yml`, but Ansible AWX does not handle the project's symlink in the same manner, leaving us with the shared playbooks only in the /shared/ directory

this situation leaves us with many broken playbooks that leverage the `import_playbook` functionality to call in a shared playbook, such as `_datacenter/shared/pb.test.yml`

```
ERROR! Unable to retrieve file contents
Could not find or access '/var/lib/awx/projects/_14__network_automation/_datacenter/shared/pb.test.yml' on the Ansible Controller.
```

##### ADDITIONAL INFORMATION

example shows that the shared directory does not exist under a team's directory, but rather only lives at the project's root:

no `_datacenter/shared/` directory is found
<img width="477" alt="Screenshot 2019-03-19 17 20 41" src="https://user-images.githubusercontent.com/14945711/54645911-7b2ccb00-4a6b-11e9-8f16-086521bbae73.png">

playbooks are found in `/shared/playbooks/` though
![image](https://user-images.githubusercontent.com/14945711/54644711-fc825e80-4a67-11e9-98be-6d8c64813b97.png)

**Comment by MrGitBlob** [comment] 2020-10-26 06:07
come on.
This inability of AWX to handle symlinks is a joke.

"/usr/lib64/python3.6/distutils/dir_util.py", line 163, in copy_tree dry_run=dry_run) File "/usr/lib64/python3.6/distutils/file_util.py", line 105, in copy_file "can't copy '%s': doesn't exist or not a regular file" % src) distutils.errors.DistutilsFileError: can't copy '/var/lib/awx/projects/path/to/somefilewhichisactuallyasymlink.yml': doesn't exist or not a regular file

Not good enough.

**Comment by Adrixop95** [comment] 2022-10-18 12:22
Bump. Do you have any plans to implement better symlink support?

**Comment by shanemcd** [comment] 2023-04-11 18:16
A lot of stuff has changed in this area since this issue was opened. Given the original author's account has been deleted I'm going to close this but please open up a new issue with a clear reproducer if this is still a problem.

**Closed as completed by shanemcd** 2023-04-11 18:16 UTC
Labels: type:enhancement, component:api, component:ui
