### ISSUE TITLE
Finished date before started date on API

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#12395] opened 2022-06-17 12:29 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello, 
We have a strange behavior in our instance of AWX. 
In fact, the finished time is before the started time.
![image](https://user-images.githubusercontent.com/29703972/174297318-426eaf8a-e58a-41f1-93ee-040a856cfb60.png)

```json
{
    "id": 2432183,
    "type": "job",
    "created": "2022-06-17T05:05:33.384110Z",
    "modified": "2022-06-17T05:15:26.060723Z",
    "name": "play-inetum-adeo|postgresql|downtime_query",
    "description": "",
    "unified_job_template": 4589,
    "launch_type": "workflow",
    "status": "successful",
    "execution_environment": 6,
    "failed": false,
    "started": "2022-06-17T05:16:51.745286Z",
    "finished": "2022-06-17T05:16:36.023827Z",
    "canceled_on": null,
    "elapsed": -15.721,
    "job_explanation": "Task was marked as running but was not present in the job queue, so it has been marked as failed.",
    "execution_node": "",
    "controller_node": "awx-59fbdffddd-znl49",
    "work_unit_id": "7TxYhUvg",
    "verbosity": 0,
    "extra_vars": "...",
    "job_tags": "",
    "force_handlers": false,
    "skip_tags": "",
    "start_at_task": "",
    "timeout": 0,
    "use_fact_cache": false,
    "organization": 8,
    "job_template": 4589,
    "passwords_needed_to_start": [],
    "allow_simultaneous": true,
    "artifacts": {
        "query_rowcount": [
            0
        ],
        "full_query_output": {}
    },
    "scm_revision": "f64d0b46a5cd9291077ca13860d712b4444f0efc",
    "instance_group": 4,
}
```

### AWX version

21.1.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Steps to reproduce

Any idea on how to reproduce it

### Expected results

Finish time after start time

### Actual results

Finish time before start time

**Comment by Tioborto** [comment] 2022-06-17 12:42
Other problem in UI, when the time is negative
![image](https://user-images.githubusercontent.com/29703972/174300425-e1cda597-9996-42e2-aa57-ea229f1af443.png)

**Comment by fosterseth** [comment] 2022-06-22 15:42
This has a deeper underlying cause and is a known issue, has to do with reaping jobs that have a waiting status but are in a dispatch queue ready to run. 

The team is currently tracking this issue

**Comment by AlexSCorey** [comment] 2022-06-24 15:23
@keithjgrant FYI

**Comment by AlanCoding** [comment] 2022-07-20 12:16
I can explain what happens in this case, because I looked at it fairly deeply.

We have two events, one where the job is reaped, and another that the job is picked up an ran anyway. The reaper code runs first and sets the `finished` time. This is a false-positive reaper case. Then the actual process which runs the job goes and runs the job. At the end of the run, it saves the "successful" status, but it was changing it from "failed" to "successful". While doing that, it is designed to set the `finished` time, but it will not do this if it is already set. This behavior isn't unreasonable, logically you shouldn't ever _update_ the finished time, because that makes no sense. It should only finish once, and expected behavior is kind of undefined.

In https://github.com/ansible/awx/pull/12442 we avoid running failed jobs in the first place, but there are other issues connected to that, so I will go ahead and close this one.

**Closed as completed by AlanCoding** 2022-07-20 12:16 UTC
Labels: type:bug, component:api, component:ui
