### ISSUE TITLE
All items checkbox gets selected after deleting an item from Project's JT list

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5884] opened 2020-02-11 15:49 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![project_jt_delete](https://user-images.githubusercontent.com/9889020/74252682-fb7ba080-4cbb-11ea-812f-38fb6495280d.gif)

##### STEPS TO REPRODUCE
Have two JT's in the Project -> JT's list
Delete one of the JT's

##### EXPECTED RESULTS
No checkboxes checked

##### ACTUAL RESULTS
All items checkbox checked

**Comment by mabashian** [comment] 2020-02-11 15:50
This is an extremely low priority bug.  Let's not work on it until we get closer to a general release of UI Next

**Comment by mabashian** [comment] 2020-11-23 19:48
@unlikelyzero @tiagodread I think must have been fixed at some point.  Unable to reproduce.

![jt_delete](https://user-images.githubusercontent.com/9889020/100008083-f8f5bd80-2d9a-11eb-8097-81b054272905.gif)

**Comment by tiagodread** [comment] 2020-11-25 13:56
> @unlikelyzero @tiagodread I think must have been fixed at some point. Unable to reproduce.
> 
> ![jt_delete](https://user-images.githubusercontent.com/9889020/100008083-f8f5bd80-2d9a-11eb-8097-81b054272905.gif)

Yeah, I also was unable to reproduce it, I think we can safely close it.

**Closed as completed** 2020-11-25 17:46 UTC
Labels: type:bug

**Comment by unlikelyzero** [comment] 2020-11-25 19:55
Covered by 5741
