### ISSUE TITLE
Inventory -> Hosts overview: Groups not displayed correctly

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#3287] opened 2019-02-22 10:55 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

At the hosts overview page, the groups are not displayed correctly.

![unbenannt](https://user-images.githubusercontent.com/87267/53238098-ba4c4400-3698-11e9-8c83-6300e5bea950.JPG)

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Ubuntu 18.04
* Web Browser: Firefox 65

**Comment by Commifreak** [comment] 2019-02-25 07:25
Google Chrome does the same.

**Comment by mabashian** [comment] 2019-03-04 18:07
This is a duplicate of https://github.com/ansible/awx/issues/3158 and should be fixed in the next release.

**Closed as completed by mabashian** 2019-03-04 18:07 UTC
Labels: type:bug, component:ui
