### ISSUE TITLE
Workflow template with survey throwing error.

### ISSUE THREAD

**Issue by seansabour** [ansible/awx#1732] opened 2018-04-05 00:50 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Adding a Survey to a Workflow throws an undefined error 

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method:  docker on linux, 
* Ansible version:  2.5.0
* Operating System: Centos 7.4
* Web Browser: Firefox 59.0.2

##### STEPS TO REPRODUCE

1. Create a workflow template with > 1 job template.
2. Add survey
3. Add Multiple choice(single select)
4. Save
5. Launch

##### EXPECTED RESULTS

Survey to be prompted when launched 

##### ACTUAL RESULTS

Failed to get credential types. GET status: undefined

##### ADDITIONAL INFORMATION
When I delete the survey and re-run, I get no issues.

![screen shot 2018-04-04 at 5 49 44 pm](https://user-images.githubusercontent.com/9244813/38342036-a0bf7b68-3830-11e8-82df-c3233cc50147.png)

**Comment by ryanpetrello** [comment] 2018-04-10 13:57
Hi @seansabour,

Does your web browser's developer console provide any clues about the request that's failing (I'm assuming you're getting an `HTTP 404` based on this error message).

Any Javascript errors in the console?
If you `~ docker log awx_web` do you see any tracebacks/HTTP errors that might point at a culprit?

**Comment by seansabour** [comment] 2018-04-10 17:17
@ryanpetrello.
Only get a vague warning from console, might help you though.:
```
Empty string passed to getElementById().
```

this is from docker log awx_web:
```
[pid: 29|app: 0|req: 399/4949] <IP> () {42 vars in 2286 bytes} [Tue Apr 10 17:10:09 2018] OPTIONS /api/v2/workflow_job_templates/12/launch/ => generated 2678 bytes in 69 msecs (HTTP/1.1 200) 8 headers in 230 bytes (1 switches on core 0)
<IP> - - [10/Apr/2018:17:10:10 +0000] "OPTIONS /api/v2/workflow_job_templates/12/launch/ HTTP/1.1" 200 2678 "http://<IP>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0"
[pid: 276|app: 0|req: 334/4950]<IP> () {42 vars in 2282 bytes} [Tue Apr 10 17:10:09 2018] GET /api/v2/workflow_job_templates/12/launch/ => generated 266 bytes in 91 msecs (HTTP/1.1 200) 8 headers in 229 bytes (1 switches on core 0)
<IP> - - [10/Apr/2018:17:10:10 +0000] "GET /api/v2/workflow_job_templates/12/launch/ HTTP/1.1" 200 266 "http://<IP>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0"
[pid: 29|app: 0|req: 400/4951] <IP> () {42 vars in 2292 bytes} [Tue Apr 10 17:10:10 2018] GET /api/v2/workflow_job_templates/12/survey_spec/ => generated 227 bytes in 54 msecs (HTTP/1.1 200) 8 headers in 237 bytes (1 switches on core 0)
<IP> - - [10/Apr/2018:17:10:10 +0000] "GET /api/v2/workflow_job_templates/12/survey_spec/ HTTP/1.1" 200 227 "http://<IP>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0"
````

**Comment by khelkun** [comment] 2018-04-27 10:43
Duplicate of #1672

**Comment by ryanpetrello** [comment] 2018-04-27 16:37
@seansabour this should be resolved now via https://github.com/ansible/awx/commit/3dd9ca3fb67dd0a40eabc0af5d73841515d8d8b3

**Closed as completed by ryanpetrello** 2018-04-27 16:37 UTC
Labels: type:bug, component:ui

**Comment by seansabour** [comment] 2018-04-27 18:52
great news :) @ryanpetrello
