### ISSUE TITLE
Unable to add or edit some credential types following upgrade to v16.0.0

### ISSUE THREAD

**Issue by GizmoNilpferd** [ansible/awx#9091] opened 2021-01-15 11:33 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Following an upgrade from version 15.0.1 to 16.0.0 we are unable to either add or edit some credential types such as, for example, 'machine' or 'source control'.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Red Hat Enterprise Linux release 8.1 
* Web Browser: Chrome 87.0.4280.141

##### STEPS TO REPRODUCE

1. **Add Credential:**

- On the Credentials Resource page click on 'ADD' and then click on the 'Credential Type' drop-down list.

2. **Edit Credential:**

- On the Credentials Resource page click the Edit icon for a credential of a type which is missing from the 'Add Credential' list.

##### EXPECTED RESULTS

1. **Add Credential:**

-  The drop down list should be populated with all available Credential Types

2. **Edit Credential:**

-  The Edit Credential page should be displayed

##### ACTUAL RESULTS

1. **Add Credential:**

-  Several Credential Types are missing from the list and cannot therefore be added. EG there is no 'Machine' type (amongst others) in the list.

2. **Edit Credential:**

-  A blank page is displayed. In addition the Developer Console shows the following errors:

![image](https://user-images.githubusercontent.com/42178852/104718993-afcf4380-5723-11eb-99e9-49b2cfeeb4f6.png)

##### ADDITIONAL INFORMATION

As a test we've deployed fresh install of awx version 16.0.0 and this works as expected so it would appear that the issue is related to the upgrade of our existing installation.

**Comment by tiagodread** [comment] 2021-01-15 18:15
@mabashian I think this problem can be the same as reported here: https://github.com/ansible/awx/issues/8944

**Comment by mabashian** [comment] 2021-01-15 18:37
Closing this as a dupe of #8944

**Closed as completed by mabashian** 2021-01-15 18:37 UTC
Labels: type:bug
