### ISSUE TITLE
Long running queries to DB

### ISSUE THREAD

**Issue by ThomasRasmussen** [ansible/awx#4358] opened 2019-07-22 06:59 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We are running AWX towards an external PostgreSQL database. We have noticed that AWX keeps a number of queries running forever, which seems to be odd. 

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Ubuntu 18.04
* Web Browser:

##### STEPS TO REPRODUCE

Start ansible and let it run for a number of days. 
Run Query on PSQL:
    SELECT pid, left(query, 60), now() - pg_stat_activity.query_start AS duration, state, pg_stat_activity.query_start FROM pg_stat_activity WHERE (now() - pg_stat_activity.query_start) > interval '30 seconds' and usename='AWXDBUSER';

##### EXPECTED RESULTS

No queries should be running for a very long time

##### ACTUAL RESULTS
```
  pid  |                             left                             |        duration         | state |          query_start
-------+--------------------------------------------------------------+-------------------------+-------+-------------------------------
 16175 | SELECT "main_channelgroup"."id", "main_channelgroup"."group" | 17:56:37.588698         | idle  | 2019-07-21 15:00:03.494981+02
 14490 | SELECT pg_advisory_unlock(-756382330)                        | 00:01:13.085847         | idle  | 2019-07-22 08:55:27.997832+02
 16174 | SELECT "main_channelgroup"."id", "main_channelgroup"."group" | 17:56:37.613062         | idle  | 2019-07-21 15:00:03.470617+02
 14513 | SELECT pg_advisory_unlock(1226251610)                        | 00:00:41.099621         | idle  | 2019-07-22 08:55:59.984058+02
 16190 | SELECT "main_notificationtemplate"."id", "main_notificationt | 17:56:35.550032         | idle  | 2019-07-21 15:00:05.533647+02
 16176 | SELECT "main_channelgroup"."id", "main_channelgroup"."group" | 17:56:37.592159         | idle  | 2019-07-21 15:00:03.49152+02
 26419 | SELECT "conf_setting"."id", "conf_setting"."created", "conf_ | 11 days 22:21:29.099607 | idle  | 2019-07-10 10:35:11.984072+02
```

Also we have noticed that sometime a COMMIT query is running for about 1 minute

**Comment by ryanpetrello** [comment] 2019-07-26 17:29
@ThomasRasmussen,

Can you provide some additional info about how to reproduce this?  It's not something I've seen in any of my installs.  Can you provide some information about the sizing/hardware of your install?

**Comment by ThomasRasmussen** [comment] 2019-07-29 08:06
Our setup is as follows:
* VM running Ubuntu 18.04 LTS 2 CPU 4GB RAM
** VM running docker.io 18.09.5
** AWX version 3.0.1 installed via docker-compose (modified i believe)
```
a4aa8848d66c        ansible/awx_task:3.0.1       "/tini -- /bin/sh -c…"   2 weeks ago         Up 7 days           8052/tcp                                              awx_task
e0eeb0a24a75        ansible/awx_web:3.0.1        "/tini -- /bin/sh -c…"   2 weeks ago         Up 2 weeks          0.0.0.0:80->8052/tcp                                  awx_web
9b3a414be565        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   2 weeks ago         Up 2 weeks          4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   awx_rabbitmq
ae6ee08bc67b        memcached:alpine             "docker-entrypoint.s…"   2 weeks ago         Up 2 weeks          11211/tcp                                             awx_memcached
```

PostgreSQL database is externally from AWX and running on separate non-dockerized VM.

PostgreSQL version 9.5

**Comment by ryanpetrello** [comment] 2019-07-29 14:42
@ThomasRasmussen,

I missed a key detail when I read your initial `pg_stat_activity` paste.

The queries in your example are all `idle` queries, not `active` queries.  Do you have any long running queries that are marked as `active`?

From the postgres docs:

https://www.postgresql.org/docs/9.2/monitoring-stats.html

```
Current overall state of this backend. Possible values are:
active: The backend is executing a query.
idle: The backend is waiting for a new client command.
(...others)
```

As for your calculated duration, it's not really measuring what you think it's measuring:

`now() - pg_stat_activity.query_start`

Again, from the postgres docs:
> query_start  - Time when the currently active query was started, or if state is not active, when the last query was started

So in your example, the calculated duration is just showing how long it's been since those idle connections last _executed_ a query.

AWX is composed of many long-running background processes that keep pools of connections open, but these queries you're seeing aren't _actively_ running - they're just the last queries that _ran_.

This isn't really a cause for concern unless you're using more RAM than you can afford. It's generally desirable to have a few idle connections like this so you don't constantly pay the cost of establishing a new connection.

**Closed as completed by ryanpetrello** 2019-07-29 14:42 UTC
Labels: type:bug
