### ISSUE TITLE
Not able to install AWX

### ISSUE THREAD

**Issue by akai257** [ansible/awx#7422] opened 2020-06-23 17:22 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.10
* Operating System: Centos 8.0
* Web Browser:

##### STEPS TO REPRODUCE

fatal: [localhost]: FAILED! => {
"assertion": "postgres_data_dir is defined and postgres_data_dir != ''",
"changed": false,
"evaluated_to": false,
"msg": "Set the value of 'postgres_data_dir' in the inventory file."
}

##### EXPECTED RESULTS

The config of inventory 
postgres_data_dir="/lab/pgdata"
host_port=80
host_port_ssl=443
#ssl_certificate=
# Optional key file
#ssl_certificate_key=
docker_compose_dir="~/.awx/awxcompose"

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/23319383/85434739-81560500-b554-11ea-9330-340eb2692f06.png)

**Comment by ryanpetrello** [comment] 2020-06-23 17:27
Duplicate of https://github.com/ansible/awx/issues/7421

Have you tried setting `postgres_data_dir` in your inventory file (as the error you pasted suggests)?

Again, If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Closed as completed by ryanpetrello** 2020-06-23 17:27 UTC

**Comment by ryanpetrello** [comment] 2020-06-23 17:33
Just to confirm, following the instructions in our install docs, I'm unable to reproduce what you're describing:

```
(tags/12.0.0:●●) ~/dev/awx/installer grep postgres_data_dir inventory
postgres_data_dir="~/.awx/testing-123"
(tags/12.0.0:●●) ~/dev/awx/installer ansible-playbook -i inventory install.yml
```

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/214912/85435854-17d6f600-b556-11ea-8657-982a6b9799b8.png">

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/214912/85435866-1c031380-b556-11ea-8667-9536b0f024fb.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/214912/85435885-232a2180-b556-11ea-8604-f9a30045ddcb.png">

**Comment by akai257** [comment] 2020-06-23 18:34
This is on Kubernetes not on docker

**Comment by ryanpetrello** [comment] 2020-06-23 19:13
@akai257,

Please read the instructions for installing in Kubernetes, then (https://github.com/ansible/awx/blob/devel/INSTALL.md#kubernetes).  The error you've reported here is specific to the Docker installer:

```shell
grep "postgres_data_dir is defined"
roles/local_docker/tasks/main.yml
10:    - postgres_data_dir is defined

roles/check_vars/tasks/check_docker.yml
6:      - postgres_data_dir is defined and postgres_data_dir != ''
```

**Comment by rdzielicki** [comment] 2021-03-10 09:17
Got same problem with K8s cluster, cat inventory |grep postgres_data_dir with awx 14.0.1
postgres_data_dir="~/.awx/pgdocker"
probably installer tries Docker event if K8s section are uncommented

**Comment by rdzielicki** [comment] 2021-03-10 11:25
corrected, make sure you are using the right context with the right role now troubleshooting FAILED! => {"changed": true, "cmd": "kubectl get deployment awx -n default -o=jsonpath='{.status.replicas}'", "delta": "0:00:00.136495", "end": "2021-03-10 12:22:55.604525", "msg": "non-zero return code", "rc": 1, "start": "2021-03-10 12:22:55.468030", "stderr": "Error from server (N
