### ISSUE TITLE
Schedule page still broken

### ISSUE THREAD

**Issue by arnarg** [ansible/awx#1648] opened 2018-03-21 21:35 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When I try to create a schedule the page renders incorrectly.
I have seen this issue numerous times before (#204, #164, #123, #401) and the conclusion is always that it's fixed but it has never worked in my attempts.

##### ENVIRONMENT
* AWX version: 1.0.4.114
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: CentOS Linux release 7.3.1611
* Web Browser: Firefox 58.0.2, Chrome 63.0.3239.132

##### STEPS TO REPRODUCE

1. Clone repo
2. cd into installer folder
3. `ansible-playbook -i inventory install.yml`

I first deployed it with tag 1.0.4 and set awx_secret_key to random string. I also tried keeping the inventory file completely unchanged (on a clean different vm). I've tried it on ec2 and also KVM (not that it should matter).

Projects -> Schedule SCM revision updates -> Add
Templates -> Calendar icon -> Add

##### EXPECTED RESULTS

Working schedule page.

##### ACTUAL RESULTS

![Schedule page](https://i.imgur.com/Rtayfy8.png)

##### ADDITIONAL INFORMATION

```
ReferenceError: event is not defined
Stack trace:
$rootScope.removeConfigReady</</<@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:29:192069
processQueue@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:134252
scheduleProcessQueue/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:135201
$digest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:146077
$apply@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:148845
compile/</<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:264153
dispatch@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:29:50457
add/elemData.handle@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:29:47390
 Possibly unhandled rejection: {}
vendor.747e0213ca95621eb37b.js:570:122052
Empty string passed to getElementById().
vendor.747e0213ca95621eb37b.js:29:32327

TypeError: name.split(...)[1] is undefined
Stack trace:
resolve@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:124542
getLocal@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:125567
scope.setDefaults@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:46786
scope.removeZonesReady<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:50912
$emit@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:150022
getZoneList@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:126121
@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:50946
exports.default<@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:29:98399
instantiate@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:33569
$ControllerProvider/this.$get</<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:92839
compile/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:6831
bind/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:9425
invokeLinkFn@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:82133
nodeLinkFn@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:64014
compositeLinkFn@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:52826
compile/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:51482
compilationGenerator/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:58586
updateView@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:29513
configUpdatedCallback@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:28684
configureUIView@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:443:48587
ViewService</ViewService.prototype.sync@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:443:48984
activateViews@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:38663
TransitionHook</TransitionHook.prototype.invokeHook/result<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:581589
TransitionHook</TransitionHook.prototype.invokeHook@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:581571
TransitionHook</TransitionHook.runAllHooks/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:580892
TransitionHook</TransitionHook.runAllHooks@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:580856
transitionSuccess@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:53:12462
processQueue@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:134252
scheduleProcessQueue/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:135201
$digest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:146077
$apply@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:148845
done@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:101113
completeRequest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:106024
createHttpBackend/</xhr.onload@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:106783
vendor.747e0213ca95621eb37b.js:570:122052

TypeError: name.split(...)[1] is undefined
Stack trace:
resolve@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:124542
getLocal@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:125567
scope.setDefaults@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:46786
this.clear@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:583:57741
exports.default<@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:29:99522
instantiate@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:33569
$ControllerProvider/this.$get</<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:92839
compile/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:6831
bind/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:9425
invokeLinkFn@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:82133
nodeLinkFn@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:64014
compositeLinkFn@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:52826
compile/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:51482
compilationGenerator/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:58586
updateView@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:29513
configUpdatedCallback@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:28684
configureUIView@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:443:48587
ViewService</ViewService.prototype.sync@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:443:48984
activateViews@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:603:38663
TransitionHook</TransitionHook.prototype.invokeHook/result<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:581589
TransitionHook</TransitionHook.prototype.invokeHook@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:581571
TransitionHook</TransitionHook.runAllHooks/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:580892
TransitionHook</TransitionHook.runAllHooks@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:37:580856
transitionSuccess@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:53:12462
processQueue@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:134252
scheduleProcessQueue/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:135201
$digest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:146077
$apply@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:148845
done@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:101113
completeRequest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:106024
createHttpBackend/</xhr.onload@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:106783
 <div ui-view="form" class="ng-scope">
vendor.747e0213ca95621eb37b.js:570:122052
$onSuccess projectSchedules.add
app.c57ee90824817e08bf77.js:29:192492

TypeError: scheduler.scope.current_timezone is undefined
Stack trace:
exports.default</</scheduler.scope.schedulerTimeZone<@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:29:98651
baseFindIndex@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:24:389563
createFind/<@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:24:416568
exports.default</<@http://10.10.10.3/static/js/app.c57ee90824817e08bf77.js:29:98624
processQueue@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:134252
scheduleProcessQueue/<@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:135201
$digest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:146077
$apply@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:148845
done@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:101113
completeRequest@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:106024
createHttpBackend/</xhr.onload@http://10.10.10.3/static/js/vendor.747e0213ca95621eb37b.js:570:106783
 Possibly unhandled rejection: {}
```

**Comment by jaredevantabor** [comment] 2018-03-28 20:52
@arnarg I am not able to reproduce this on `AWX 1.0.5.18`, could you try again after upgrading?

**Comment by arnarg** [comment] 2018-03-29 12:13
@jaredevantabor It's still happening to me on `1.0.5.18` and `latest` as of today. I'm still using the default inventory file. Do you have any idea where I should look to find out what's happening?

**Comment by jaredevantabor** [comment] 2018-04-02 17:33
@arnarg has this page ever worked for you? I'm curious, what timezone are you in?

**Comment by jlmitch5** [comment] 2018-04-02 17:37
also @arnarg do you have selinux or any sort of special file permissions-type stuff for docker?  I can't really think of a specific scenario in which you would have an issue just with the schedules page, but figured I'd mention it.

**Comment by arnarg** [comment] 2018-04-03 12:55
@jaredevantabor No it hasn't. I also get the same results in Safari so I can't blame it on a browser extension either. The server is in UTC.
`/etc/localtime -> ../usr/share/zoneinfo/UTC`

**Comment by arnarg** [comment] 2018-04-03 12:56
@jlmitch5 I tried setting selinux in permissive mode and it still happens.

**Comment by arnarg** [comment] 2018-04-03 13:25
I tried setting it up on a Ubuntu ec2 instance and got the same thing in Firefox, Chrome and Safari so I thought it might be client side. I tried setting my time zone to New York time and it worked fine.
I live in Iceland and we don't have daylight savings so we have a pretty special time zone file.
On Mac OS: `/etc/localtime -> /var/db/timezone/zoneinfo/Atlantic/Reykjavik`
On my Linux desktop (iirc): `/usr/share/zoneinfo/Iceland`

I couldn't see these in the local time zone dropdown.

**Comment by ryanpetrello** [comment] 2018-04-03 17:00
@arnarg if you visit `https://your-tower.example.org/api/v2/schedules/zoneinfo/` do you see an entry with:

```json
{
    "name": "UTC"
}
```

The UI _should be_ composing the dropdown list from the zoneinfo provided by that API endpoint (which is based on zoneinfo configured **on the server** where AWX is running, _not_ the client/browser).

**Comment by arnarg** [comment] 2018-04-03 17:27
@ryanpetrello The array does include UTC. I can even see `Iceland` and `Atlantic/Reykjavik` in that list.

**Comment by jaredevantabor** [comment] 2018-04-03 23:00
@arnarg I think I was able to figure out what was happening here. We added UTC as an option on the front end in Tower 3.2.2 and that change hadn't been ported over to AWX yet. My PR should hopefully do the trick. If you're on a dev environment, you'll likely need to blow away your UI deps using `make clean-ui` and then rebuild the UI (using `make ui` or `make ui-docker`).

**Comment by jaredevantabor** [comment] 2018-04-03 23:01
I'm going to close this, but please let me know if you still experience issues and I'll reopen it

**Closed as completed by jaredevantabor** 2018-04-03 23:01 UTC
Labels: type:bug, component:ui

**Comment by ykisialevich** [comment] 2018-04-04 10:34
I had similar issue (Schedule page was broken), but in my case this fix helped me:
1. set SELINUX=disabled in /etc/selinux/config
2. setenforce 0
3. reboot
