### ISSUE TITLE
A server error has occurred (/migrations_notran)

### ISSUE THREAD

**Issue by lunarthegrey** [ansible/awx#4852] opened 2019-09-30 17:30 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After installing AWX from devel when you visit the AWX web page it displays `Server Error` and `A server error has occurred.`

##### ENVIRONMENT
* AWX version: devel (7.0.0)
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Debian 10 (Buster)
* Web Browser: Firefox 69.0.1

##### STEPS TO REPRODUCE

Run the installer freshly after modifying inventory file, when it finishes without error, AWX containers come up. When you try visiting the AWX web page it presents the internal error.

##### EXPECTED RESULTS

That it works perfectly as it did on 6.1.0.

##### ACTUAL RESULTS

AWX seems to be in a broken state.

##### ADDITIONAL INFORMATION

Logs from the `awx_task` container:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 123, in handle
    reaper.reap()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/reaper.py", line 36, in reap
    me = instance or Instance.objects.me()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/managers.py", line 114, in me
    if node.exists():
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
```

Logs from the `awx_web` container:

```
2019-09-30 17:21:04,972 ERROR    django.request Internal Server Error: /migrations_notran/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/middleware/locale.py", line 21, in process_request
    language = translation.get_language_from_request(request, check_path=i18n_patterns_used)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/translation/__init__.py", line 236, in get_language_from_request
    return _trans.get_language_from_request(request, check_path)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 463, in get_language_from_request
    lang_code = request.session.get(LANGUAGE_SESSION_KEY)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in get
    return self._session.get(key, default)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
```

Logs from the `postgres` container:

```
2019-09-30 17:29:34.772 UTC [388] ERROR:  relation "main_instance" does not exist at character 24
2019-09-30 17:29:34.772 UTC [388] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"."hostname" = 'awx'  LIMIT 1
2019-09-30 17:29:37.764 UTC [389] ERROR:  relation "conf_setting" does not exist at character 158
```

**Comment by ryanpetrello** [comment] 2019-09-30 18:28
@lunarthegrey it looks to me like you're potentially using an image with an older version of Django (likely, you have an out of date container image with the wrong dependencies).  Likely you have a mismatch between that and the version of code you're deploying (see: https://github.com/ansible/awx/issues/3032, https://github.com/ansible/awx/issues/2967)

In any event, this issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by lunarthegrey** [comment] 2019-09-30 20:27
@ryanpetrello this is from a fresh install with no docker containers, images or volumes so it's not a migration. I did a `git clone` of the AWX repo and followed the install instructions. Can this be re-opened?

**Comment by lunarthegrey** [comment] 2019-09-30 20:34
@ryanpetrello I read about those issues as well, unfortunately they're not relevant to the issue I'm running into. Since it's a clean install and I'm not using any strange variables in the inventory file.

**Comment by lunarthegrey** [comment] 2019-09-30 20:41
To be more specific, I'm using exactly what https://github.com/ansible/awx/blob/devel/installer/inventory has, but I've changed passwords and the `postgres_data_dir` and `docker_compose_dir` directories. This tells me there may be something wrong with new and fresh AWX installs.

**Comment by lunarthegrey** [comment] 2019-09-30 21:03
This is the full play.

```
root@awx:~/awx/installer# ansible-playbook -i inventory install.yml

PLAY [Build and deploy AWX] ****************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************
ok: [localhost]

TASK [check_vars : include_tasks] **********************************************************************************************************************************************
skipping: [localhost]

TASK [check_vars : include_tasks] **********************************************************************************************************************************************
included: /root/awx/installer/roles/check_vars/tasks/check_docker.yml for localhost

TASK [check_vars : postgres_data_dir should be defined] ************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [check_vars : host_port should be defined] ********************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [image_build : Set global version if not provided] ************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Verify awx-logos directory exists for official install] ****************************************************************************************************
skipping: [localhost]

TASK [image_build : Copy logos for inclusion in sdist] *************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set sdist file name] ***************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : AWX Distribution] ******************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stat distribution file] ************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Clean distribution] ****************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build sdist builder image] *********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build AWX distribution using container] ********************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build AWX distribution locally] ****************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set docker build base path] ********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set awx_web image name] ************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set awx_task image name] ***********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Ensure directory exists] ***********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage sdist] ***********************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Template web Dockerfile] ***********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Template task Dockerfile] **********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx] ******************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx_task] *************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage nginx.conf] ******************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage supervisor.conf] *************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage supervisor_task.conf] ********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage settings.py] *****************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage requirements] ****************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage config watcher] **************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage Makefile] ********************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo] ****************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo key] ************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build base web image] **************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build base task image] *************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Tag task and web images as latest] *************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Clean docker base directory] *******************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Authenticate with Docker registry if registry password given] ***********************************************************************************************
skipping: [localhost]

TASK [image_push : Remove web image] *******************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Remove task image] ******************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Tag and push web image to registry] *************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Tag and push task image to registry] ************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Set full image path for Registry] ***************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : fail] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : include_tasks] **********************************************************************************************************************************************
skipping: [localhost] => (item=openshift_auth.yml) 
skipping: [localhost] => (item=openshift.yml) 

TASK [kubernetes : include_tasks] **********************************************************************************************************************************************
skipping: [localhost] => (item=kubernetes_auth.yml) 
skipping: [localhost] => (item=kubernetes.yml) 

TASK [kubernetes : Use kubectl or oc] ******************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : set_fact] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Record deployment size] *************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set expected post-deployment Replicas value] ****************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete existing Deployment] *********************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Get Postgres Service Detail] ********************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Template PostgreSQL Deployment (OpenShift)] *****************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (OpenShift)] *******************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Template PostgreSQL Deployment (Kubernetes)] ****************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] ******************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set postgresql hostname to helm package service (Kubernetes)] ***********************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for Postgres to activate] ******************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set task image name] ****************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set web image name] *****************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Render deployment templates] ********************************************************************************************************************************
skipping: [localhost] => (item=None) 
skipping: [localhost] => (item=None) 
skipping: [localhost] => (item=None) 
skipping: [localhost]

TASK [kubernetes : Apply Deployment] *******************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete any existing management pod] *************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Template management pod] ************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Create management pod] **************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for management pod to start] ***************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Migrate database] *******************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Check for Tower Super users] ********************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : create django super user if it does not exist] **************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : update django super user password] **************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Create the default organization if it is needed.] ***********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete management pod] **************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Scale up deployment] ****************************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Check for existing Postgres data] *************************************************************************************************************************
ok: [localhost]

TASK [local_docker : Record Postgres version] **********************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Determine whether to upgrade postgres] ********************************************************************************************************************
ok: [localhost]

TASK [local_docker : Set up new postgres paths pre-upgrade] ********************************************************************************************************************
skipping: [localhost] => (item=/var/lib/pgdocker/10/data) 

TASK [local_docker : Stop AWX before upgrading postgres] ***********************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Upgrade Postgres] *****************************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Copy old pg_hba.conf] *************************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Remove old data directory] ********************************************************************************************************************************
ok: [localhost]

TASK [local_docker : Export Docker web image if it isnt local and there isnt a registry defined] *******************************************************************************
skipping: [localhost]

TASK [local_docker : Export Docker task image if it isnt local and there isnt a registry defined] ******************************************************************************
skipping: [localhost]

TASK [local_docker : Set docker base path] *************************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Ensure directory exists] **********************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Copy web image to docker execution] ***********************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Copy task image to docker execution] **********************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Load web image] *******************************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Load task image] ******************************************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Set full image path for local install] ********************************************************************************************************************
skipping: [localhost]

TASK [local_docker : Set DockerHub Image Paths] ********************************************************************************************************************************
ok: [localhost]

TASK [local_docker : Create /var/lib/awxcompose directory] *********************************************************************************************************************
changed: [localhost]

TASK [local_docker : Create Docker Compose Configuration] **********************************************************************************************************************
changed: [localhost] => (item=environment.sh)
changed: [localhost] => (item=credentials.py)
changed: [localhost] => (item=docker-compose.yml)

TASK [local_docker : Render SECRET_KEY file] ***********************************************************************************************************************************
changed: [localhost]

TASK [local_docker : Start the containers] *************************************************************************************************************************************
[DEPRECATION WARNING]: The 'docker_service' module has been renamed to 'docker_compose'.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by
 setting deprecation_warnings=False in ansible.cfg.
changed: [localhost]

TASK [local_docker : Update CA trust in awx_web container] *********************************************************************************************************************
changed: [localhost]

TASK [local_docker : Update CA trust in awx_task container] ********************************************************************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************************************************************************************************************
localhost                  : ok=14   changed=6    unreachable=0    failed=0    skipped=83   rescued=0    ignored=0
```

This is my full inventory file, I've just replaced the passwords with `test`.

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

# Remove these lines if you want to run a local image build
# Otherwise the setup playbook will install the official Ansible images. Versions may
# be selected based on: latest, 1, 1.0, 1.0.0, 1.0.0.123
# by default the base will be used to search for ansible/awx_web and ansible/awx_task
dockerhub_base=ansible

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
#           or set -e openshift_token=TOKEN
# openshift_host=127.0.0.1:8443
# openshift_project=awx
# openshift_user=developer
# openshift_skip_tls_verify=False
# openshift_pg_emptydir=True

# Kubernetes Install
# kubernetes_context=test-cluster
# kubernetes_namespace=awx
# tiller_namespace=kube-system
# Optional Kubernetes Variables
# pg_persistence_storageClass=StorageClassName
# pg_cpu_limit=1000
# pg_mem_limit=2

# Kubernetes Ingress Annotations
# You can use the variables below to pass annotations to Kubernetes Ingress
# The example below shows an annotation to be used with Traefik but other Ingress controllers are also supported.
#kubernetes_ingress_hostname=awx.example.org
#kubernetes_ingress_annotations={'kubernetes.io/ingress.class': 'traefik', 'traefik.ingress.kubernetes.io/redirect-entry-point': 'https'}

# Kubernetes and Openshift Install Resource Requests
# These are the request and limit values for a pod's container for task/web/rabbitmq/memcached/management.
# The total amount of requested resources for a pod is the sum of all
# resources requested by all containers in the pod
# A cpu_request of 1500 is 1.5 cores for the container to start out with.
# A cpu_limit defines the maximum cores that that container can reserve.
# A mem_request of 2 is for 2 gigabytes of memory for the container
# A mem_limit defines the maximum memory that that container can reserve.
# Default values for these entries can be found in ./roles/kubernetes/defaults/main.yml
# task_cpu_request=1500
# task_mem_request=2
# task_cpu_limit=2000
# task_mem_limit=4
# web_cpu_limit=1000
# web_mem_limit=2
# rabbitmq_cpu_limit=1000
# rabbitmq_mem_limit=3
# memcached_cpu_limit=1000
# memcached_mem_limit=2
# management_cpu_limit=2000
# management_mem_limit=2

# Common Docker parameters
awx_task_hostname=awx
awx_web_hostname=awxweb
postgres_data_dir=/var/lib/pgdocker
host_port=80
host_port_ssl=443
#ssl_certificate=
docker_compose_dir=/var/lib/awxcompose

# Required for Openshift when building the image on your own
# Optional for Openshift if using Dockerhub or another prebuilt registry
# Required for Docker Compose Install if building the image on your own
# Optional for Docker Compose Install if using Dockerhub or another prebuilt registry
# Define if you want the image pushed to a registry. The container definition will also use these images
# docker_registry=172.30.1.1:5000
# docker_registry_repository=awx
# docker_registry_username=developer


# Docker_image will not attempt to push to remote if the image already exists locally
# Set this to true to delete images from docker on the build host so that they are pushed to the remote repository
# docker_remove_local_images=False

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
# pg_hostname=postgresql
pg_username=awx
# pg_password should be random 10 character alphanumeric string, when postgresql is running on kubernetes
# NB: it's a limitation of the "official" postgres helm chart
pg_password=test
pg_admin_password=test
pg_database=awx
pg_port=5432
#pg_sslmode=require

# RabbitMQ Configuration
rabbitmq_password=test
rabbitmq_erlang_cookie=cookiemonster

# Use a local distribution build container image for building the AWX package
# This is helpful if you don't want to bother installing the build-time dependencies as
# it is taken care of already.
# NOTE: IMPORTANT: If you are running a mininshift install, using this container might not work
#                  if you are using certain drivers like KVM where the source tree can't be mapped
#                  into the build container.
#                  Thus this setting must be set to False which will trigger a local build. To view the
#                  typical dependencies that you might need to install see:
#                  installer/image_build/files/Dockerfile.sdist
# use_container_for_build=true

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
admin_user=admin
admin_password=test

# Whether or not to create preload data for demonstration purposes
create_preload_data=True

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
secret_key=test

# Build AWX with official logos
# Requires cloning awx-logos repo as a sibling of this project.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
# awx_official=false

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org

# Container networking configuration
# Set the awx_task and awx_web containers' search domain(s)
#awx_container_search_domains=example.com,ansible.com
# Alternate DNS servers
#awx_alternate_dns_servers="10.1.2.3,10.2.3.4"

# AWX project data folder. If you need access to the location where AWX stores the projects
# it manages from the docker host, you can set this to turn it into a volume for the container.
#project_data_dir=/var/lib/awx/projects

# CA Trust directory. If you need to provide custom CA certificates, supplying
# this variable causes this directory on the host to be bind mounted over
# /etc/pki/ca-trust in the awx_task and awx_web containers.
#ca_trust_dir=/etc/pki/ca-trust/source/anchors

# Include /etc/nginx/awx_extra.conf
# Note the use of glob pattern for nginx
# which makes include "optional" - i.e. not fail
# if file is absent
#extra_nginx_include="/etc/nginx/awx_extra[.]conf"
dockerhub_version=latest
```

**Comment by puppetninja** [comment] 2019-10-09 21:26
I am running into this issue as well

**Comment by puppetninja** [comment] 2019-10-09 21:27
And similarly, I installed it in a fresh environment using local_docker

**Comment by puppetninja** [comment] 2019-10-09 21:37
I downgraded to the 4.0.0  release(also with a clean environment), and it worked again, so it should be something not right in the docker image distributed by ansible on dockerhub as the error is from the virtualenv inside the container

**Comment by lunarthegrey** [comment] 2019-10-09 22:07
Thanks for reporting @PuppetNinja. I would like @ryanpetrello or someone on the Ansible team to reopen this issue.

**Comment by rooftopcellist** [comment] 2019-10-25 14:40
@lunarthegrey @PuppetNinja I was able to reproduce this on 7.0.0, but cannot reproduce on 8.0.0.  As far as I can tell, this has been fixed.  I installed with the `install.yml` playbook as shown below with the inventory file unchanged (so it was using the Dockerhub provided images).  

```
ansible-playbook -i inventory install.yml
```

Thank you for all of the information you have provided.  Do you mind trying a fresh install with the latest code/image and seeing if this is fixed for you as well?  Building your own image locally or pulling from the Dockerhub images should both work now.

**Comment by lunarthegrey** [comment] 2019-10-25 14:44
Thanks for looking into this @rooftopcellist. I will give it another try via my Ansible role which runs the `install.yml` when I get a chance. Didn't see 8.0.0 was released.

**Comment by rooftopcellist** [comment] 2019-10-28 14:06
I am going to close this out, but if you are able to reproduce this, drop a comment here and I'll open it again.

**Closed as completed by rooftopcellist** 2019-10-28 14:06 UTC
Labels: type:bug, help wanted

**Comment by JustDevZero** [comment] 2020-10-27 12:18
> I am going to close this out, but if you are able to reproduce this, drop a comment here and I'll open it again.

Unluckly I'm able to reproduce it with a brand new installation, no ugprade as #5214 but fresh.

**Comment by JacBra** [comment] 2020-11-26 12:44
When I run "ansible-playbook -i inventory install.yml" twice, it works.
