### ISSUE TITLE
wait option on tower_project does not work if project already exists

### ISSUE THREAD

**Issue by Tompage1994** [ansible/awx#6875] opened 2020-04-29 15:37 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running the `tower_project` module in the awx_collection, if the project already exists then having the `wait` option set to true (or simply not set as this is default) will not cause a project update (and also will not wait for the project to have updated, or show anything to say it has not updated)

##### ENVIRONMENT
* AWX version: 11.1.0 and awx_collection version 11.1.0
* AWX install method: N/A
* Ansible version:  2.9.6
* Operating System: RHEL 8
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE
1. Have the project `test` already existing and updated on AWX
1. Add a new playbook `playbooks/new_play.yml`
1. Run the tower_project module
```yaml
awx.awx.tower_project:
  name: test
  organization: Default
  scm_url: "{{ scm_url }}"
  scm_type: git
  scm_update_cache_timeout: 60
  scm_credential: "{{ scm_credential }}"
  scm_branch: master
  state: present
  wait: true
```
1. Attempt to add a new job template of playbook `playbooks/new_play.yml` we cannot.

##### EXPECTED RESULTS

The playbook can be added and run as the project has been updated

##### ACTUAL RESULTS

See that the project has not been updated as when trying to add a new job template of playbook `playbooks/new_play.yml` we cannot. This is because a project update has not been initiated.

##### ADDITIONAL INFORMATION

The wait functionality works when the project does not exist yet in AWX.

**Comment by ryanpetrello** [comment] 2020-04-29 21:28
@beeankha @AlanCoding @john-westcott-iv any of you have any time to peek at this?

**Comment by john-westcott-iv** [comment] 2020-05-04 12:26
This particular module is currently working as expected it is not currently designed to allow for project updates. So the wait option is only for waiting for an update if a change to the project itself causes an update. In the future we hope to provide another module or modify this one to allow for project updates specifically.

**Comment by AlanCoding** [comment] 2020-05-04 13:49
Yeah, that should be a part of https://github.com/ansible/awx/issues/6367. We are still not committed to a particular solution, but I do like the `state=updated` idea, in which case the wait flag is kind like a of modifier on the updated state.

Project and inventory updates should be idempotent, so it makes sense to use things in the way this issue describes. But there's still a cost associated with updating, so I think it makes sense to _not_ do things that way too. If you set the branch to a commit or a tag, thing any subsequent updates are wasted effort.

**Comment by wenottingham** [comment] 2020-06-16 21:16
@AlanCoding should this just be a duplicate of #6367 and therefore closed?

**Comment by AlanCoding** [comment] 2020-06-17 02:43
Likely, but depends on implementation

**Comment by sean-m-sullivan** [comment] 2020-08-27 12:51
If the on_continue function is approved for #7491 , we can implement it here. 
Idea would be to add these 3 paramaters to the module
project update - bool - update project if this is true. 
interval - int - interval time to wait between checks
timeout - int - time to wait to timeout update. 

Then when project update is true, on_continue would be true, and we could invoke the project update, and the wait function from #8022
when project_update is not ture, the module will then behave as it does today.

**Comment by sean-m-sullivan** [comment] 2020-09-08 15:21
This module should now provide what was desired 
https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_project_update.py

**Comment by squidboylan** [comment] 2020-09-16 16:41
I dont think we've actually fixed this, when i tested manually, changing a project does not cause an update, which seems to be the expected behavior

**Comment by beeankha** [comment] 2020-09-30 18:31
@Tompage1994 this problem _should_ be resolved with the addition of the `tower_project_update` module.  If you add a new task like:
```
awx.awx.tower_project_update:
  name: test
  organization: Default
  wait: true
```
... then the project should successfully update with all changes made, and the associated job template should be able to access those changes as well.  Without the use of this `tower_project_update` module, then the job template will not be able to access the correct playbook, since the project update will not have been started/finished.

**Comment by ryanpetrello** [comment] 2020-10-01 22:17
@rebeccahhh @squidboylan @beeankha @john-westcott-iv is there any work to do here, or is @beeankha's suggestion enough?  What's the status of this one?

**Comment by AlanCoding** [comment] 2020-10-02 01:40
The `tower_project` module doesn't fully gracefully handle the auto-update scenario where someone changes, say, `scm_url`. A lot of what I was saying was directed to that scenario.

But closer reading of this shows:

> See that the project has not been updated as when trying to add a new job template

The problem here isn't that an update wasn't being waited for, it's that an update wasn't done to begin with. The canonical solution is what @beeankha gave.

Given that no one has complained about the behavior I was thinking about, I am assuming it's not a problem.

**Closed as completed by AlanCoding** 2020-10-02 01:40 UTC
Labels: type:enhancement, component:awx_collection
