### ISSUE TITLE
multiple vault credentials with a "period" don't work

### ISSUE THREAD

**Issue by abedwardsw** [ansible/awx#4009] opened 2019-06-05 16:00 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using multiple vault credentials with a "period" (.) in the vault-id name AWX fails to find the matching vault to decrypt.

##### ENVIRONMENT
* AWX version: 2.1.2.0
* AWX install method: docker on linux
* Ansible version:  2.7.4
* Operating System: Centos
* Web Browser: chrome

##### STEPS TO REPRODUCE

Using the same playbook [here](https://github.com/ansible/test-playbooks/blob/master/multivault.yml) , just change the vault id's to linux.first and linux.second

##### EXPECTED RESULTS

Playbook should work and able to decrypt the vars

##### ACTUAL RESULTS

The first one succeeds, but the second one does not.

##### ADDITIONAL INFORMATION

- I will attach full logs from a failed and a successful run in AWX where all I did was change the names to not include a period
- Using periods in the name works fine in Ansible CLI via ansible-playbook, so I believe the issue must be with AWX itself
- alternate fix would be to disable the ability to enter a vault-id with a period in it (and whatever other chars cause this issue) from the api
- below are the highlight of the issue.  You can see that although the vault is found it seems to truncate it and remove the period and anything following from the name.  (Note my example uses linux.common and linux.nonprod as the vault ids)

```
#### FIRST PASSWORD
Found a vault_id (linux.nonprod) in the vaulttext
Found a vault_id (linux.nonprod) in the vault text, but we do not have a associated secret (--vault-id)
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32110>) id=linux to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32110> for vault_id=linux
Decrypt successful with secret=<ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32110> and vault_id=linux

### second password
Found a vault_id (linux.common) in the vaulttext
Found a vault_id (linux.common) in the vault text, but we do not have a associated secret (--vault-id)
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32110>) id=linux to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32110> for vault_id=linux
Tried to use the vault secret (linux) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32190>) id=linux to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f957ee32190> for vault_id=linux
Tried to use the vault secret (linux) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.
```

**Comment by abedwardsw** [comment] 2019-06-05 16:23
[vault-success.txt](https://github.com/ansible/awx/files/3258060/vault-success.txt)
[vault-fail.txt](https://github.com/ansible/awx/files/3258061/vault-fail.txt)

**Comment by ryanpetrello** [comment] 2019-06-06 16:41
I'm able to reproduce this.

**Comment by ryanpetrello** [comment] 2019-06-06 19:18
@abedwardsw thanks for reporting this, it should be resolved in `devel` now.

**Comment by abedwardsw** [comment] 2019-06-07 15:50
thanks @ryanpetrello , not sure of the process.  Do I close the ticket or you?

**Comment by ryanpetrello** [comment] 2019-06-07 15:55
@abedwardsw let's leave it open for now - if you want to try the patch, though, I'd appreciate a 👍 from you on your end if it seems to be working.

**Comment by kdelee** [comment] 2019-06-10 20:19
Works for me, thanks @ryanpetrello

**Closed as completed by kdelee** 2019-06-10 20:19 UTC
Labels: type:bug, component:api
