### ISSUE TITLE
Nested group list name link throws error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#635] opened 2017-11-14 15:19 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
1. Create inventory
2. Create group inside of inventory
3. Click groups tab from group edit screen to see associated groups
4. Create new associated group

The links in the associated groups list view don't work:

<img width="1437" alt="screen shot 2017-11-14 at 10 16 29 am" src="https://user-images.githubusercontent.com/9889020/32787643-0bba4b44-c925-11e7-89ef-08b595173483.png">

Clicking the edit icon (pencil) will still let the user edit the group.

**Comment by aperigault** [comment] 2018-03-09 10:47
Hi,
We have the same bug. Any idea to quick fix that ?

**Comment by aperigault** [comment] 2018-03-27 14:31
The issue is still present in AWX 1.0.5.
Nobody available to fix this old bug ?

**Comment by jaredevantabor** [comment] 2018-05-17 22:05
This has been fixed in devel.

**Closed as completed by jaredevantabor** 2018-05-17 22:05 UTC
Labels: type:bug, component:ui
