### ISSUE TITLE
RFE : Failed SCM update job with it's id should have hyperlink

### ISSUE THREAD

**Issue by pravindmali** [ansible/awx#1907] opened 2018-05-24 09:18 UTC
##### ISSUE TYPE

  - Feature Idea

##### COMPONENT NAME

  - UI

##### SUMMARY

When playbook task fails it points to a failed SCM update job with it's id.  To see that ID details, First need to check API output as api/v2/jobs/<job-id> and then further project_update endpoint. 
This process is not user friendly. To make it user friendly, Can we make that Job ID hyperlink to the failed SCM update ?

##### ENVIRONMENT
* AWX version: 1.0

##### EXPECTED RESULTS

It should show EXPLANATION as `SCM Update failed for <xyz> with ID <x>]`  as hyperlink to the failed SCM update.

##### ACTUAL RESULTS

It shows EXPLANATION as `SCM Update failed for <xyz> with ID <x>` (without hyperlink)
![screenshot from 2018-05-24 14-45-36](https://user-images.githubusercontent.com/5475858/40476373-7f82085a-5f61-11e8-86c4-3fffe0e641aa.png)

**Comment by AlanCoding** [comment] 2018-05-24 12:32
If you click on the red `!` in the image you posted that should take you to the related project update. Does that solve your problem?

**Comment by pravindmali** [comment] 2018-05-29 11:47
Thank you ! Yes, Thats helpful.

**Comment by AlanCoding** [comment] 2018-05-29 12:11
Sounds good. Closing ticket for now, @trahman73 and @jaredevantabor are relevant engineers, and are aware this is slightly hard to find visually.

**Comment by jaredevantabor** [comment] 2018-05-29 20:10
I totally agree with the sentiment here. Spoke with @trahman73 and we agree that we should keep the STATUS functionality the same, but make the EXPLANATION a link to the related project update. I'm going to reopen this ticket for that enhancement.

**Comment by mabashian** [comment] 2021-07-01 21:18
Dupe of https://github.com/ansible/awx/issues/10216 which has been addressed in the new UI

**Closed as completed by mabashian** 2021-07-01 21:18 UTC
Labels: type:enhancement, component:ui, help wanted, good first issue
