### ISSUE TITLE
Associate User to Team by API

### ISSUE THREAD

**Issue by defrancesco** [ansible/awx#529] opened 2017-10-30 17:12 UTC
I am not able to add an user to one team using the API, this is possible?
in case can you help me because I don't understand which parameters and which API have to use?

Thanks
Giuseppe

**Comment by wenottingham** [comment] 2017-10-30 17:22
See https://github.com/ansible/tower-cli for examples; you associate users into teams.

Closing, not a bug.

**Closed as completed by wenottingham** 2017-10-30 17:22 UTC
