### ISSUE TITLE
Workflow Run On "Change"

### ISSUE THREAD

**Issue by hs-hub-world** [ansible/awx#5653] opened 2020-01-14 16:04 UTC
We are still evaluating Ansible/AWX and we are noticing some limitations we thought it would be great to have. 

##### ISSUE TYPE
When setting up Workflow we think Run On Change should be an option. For example, Whenever a change is detected we would want the same Template to run again x number of times until no more change is detected. For example - if a change keeps occurring that means something is wrong with the Env and requires human intervention.

Also, it would be great to be able to send an Email whenever there is a change detected.

![image](https://user-images.githubusercontent.com/20629911/72360079-4944bf00-36a4-11ea-85cd-e7a8803149a8.png)

Thank you,

**Comment by wenottingham** [comment] 2020-01-14 16:43
See #5564 . There is no 'changed' job status.

Marking as duplicate of that.

**Closed as completed by wenottingham** 2020-01-14 16:43 UTC
