### ISSUE TITLE
Can't see stdout output of a job

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#8973] opened 2020-12-22 22:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
unable to see stdout output of a running job

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: containers run on openSUSE Leap 15.2
* Web Browser: Firefox on Windows, Linux, Android

##### STEPS TO REPRODUCE

- While a job is running, try opening its output details
- 
##### EXPECTED RESULTS

I expect to see the normal output of a running play

##### ACTUAL RESULTS

I get a page telling me that something went wrong, with a link to the dashboard.

##### ADDITIONAL INFORMATION

This happens mostly with jobs that are still running and part of a bigger workflow.
Sometimes it happens on standalone jobs, and sometimes, very rarely, happens on finished jobs as well.

**Comment by jakemcdermott** [comment] 2020-12-23 02:05
:wave: hello @lemmy04. 

Thanks for creating this issue.

The job output update bug you described is caused by https://github.com/ansible/awx/issues/8596. 

We'll have a fix for this in one of the upcoming awx releases.

Closing for now - we're tracking the work for this in the one linked above. 

also see: https://github.com/ansible/awx/issues/8930

**Closed as completed by jakemcdermott** 2020-12-23 02:05 UTC
Labels: type:bug, flag:community
