### ISSUE TITLE
401 in add user roles modal goes unsurfaced

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7520] opened 2020-07-01 19:11 UTC
##### SUMMARY
401 responses gotten when clicking `save` in the roles modal go unnoticed.

##### STEPS TO REPRODUCE

* add a "normal user"
* org -> access -> add -> users
* check the user you added -> next
* select a role (I selected Member)
* open a new tab and click logout
* go back to your tab and hit save

##### EXPECTED RESULTS

* Redirected to login screen

##### ACTUAL RESULTS

* Nothing

![image](https://user-images.githubusercontent.com/722880/86282345-0c667900-bbad-11ea-8163-2a3e32d3d99f.png)

**Comment by AlexSCorey** [comment] 2020-07-01 21:21
This may also be a problem in Users/Teams -> Access.  Whoever picks this up should check those areas too.

**Comment by unlikelyzero** [comment] 2020-07-02 21:48
During `needs_test` verification, please add testcase (or stub)

**Comment by mabashian** [comment] 2020-09-28 18:17
link https://github.com/ansible/awx/issues/6462

**Comment by mabashian** [comment] 2021-02-03 17:44
Duplicate of https://github.com/ansible/awx/issues/8840

**Closed as completed by mabashian** 2021-02-03 17:44 UTC
Labels: type:bug, component:ui

**Comment by AlexSCorey** [comment] 2021-06-01 16:53
I just tested this and the behavior I see now is that the original tab logs out as expected and for other errors we are surfacing API errors via alter modal since https://github.com/ansible/awx/pull/10203
