### ISSUE TITLE
Pull access denied for ansible/awx, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by ghost** [ansible/awx#7299] opened 2020-06-09 15:05 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When installing AWX following the manual I get this issue: pull access denied for ansible/awx, repository does not exist or may require 'docker login'. The installer want's to pull from ansible/awx on hub.docker.com but this doesn't exist. 

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker
* Ansible version:  latest
* Operating System: Ubuntu 20.04
* Web Browser: Safari

##### STEPS TO REPRODUCE

Followed all the steps in the manual.

##### EXPECTED RESULTS

AWX to be installed

##### ACTUAL RESULTS

TASK [local_docker : Start the containers] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"b\"pull access denied for ansible/awx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\"\")"}

**Comment by ryanpetrello** [comment] 2020-06-09 15:30
duplicate of https://github.com/ansible/awx/issues/7246

**Closed as completed by ryanpetrello** 2020-06-09 15:30 UTC
Labels: type:bug
