### ISSUE TITLE
Can't create survey questions

### ISSUE THREAD

**Issue by hjkatz** [ansible/awx#9370] opened 2021-02-19 20:57 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: kubernetes
* Operating System: macOS Catalina 10.15.7
* Web Browser: Versión 88.0.4324.182 (Build oficial) (x86_64)

##### STEPS TO REPRODUCE

* Create a Job Template
* Add a new Survey question
* Try to save

##### EXPECTED RESULTS

The survey question is saved.

##### ACTUAL RESULTS

Javascript console logs the following error:

```
sortErrorMessages.js:20 TypeError: Cannot read property 'spec' of null
    at SurveyQuestionAdd.jsx:13
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at SurveyQuestionAdd.jsx:11
```

![image](https://user-images.githubusercontent.com/2234516/108560611-04d61a80-72cb-11eb-9a38-754f93d0f05d.png)

##### ADDITIONAL INFORMATION

I'm not the original author of the Job Template. Rather, I have been granted the `admin` permission over this Template via my Team membership.

![image](https://user-images.githubusercontent.com/2234516/108560683-1f0ff880-72cb-11eb-88ae-cef140679da2.png)

Somehow I think this is likely related...

Yep, when I grant my User the `admin` role over the Job Template and not via my Team's `admin` role, then everything works just fine: 
![image](https://user-images.githubusercontent.com/2234516/108560852-5b435900-72cb-11eb-8752-9ec854270678.png)

Side question... why are Team roles and permissions so broken?

**Comment by AlexSCorey** [comment] 2021-04-19 18:32
This seems to be working just fine.  My steps:
1) Create JT
2) Create team
3) Add a normal user to that team.  Their role on the team is `Member`
4) Give the team admin roles on the job template
5) Successfully create a survey question

Can you ensure I did all the steps right?

**Comment by hjkatz** [comment] 2021-04-19 19:05
For 5. Are you creating the template as the user that is a member of the Team?

**Comment by AlexSCorey** [comment] 2021-04-19 20:14
For 5 I was able to create a survey question as the user that is a member of the team, the Job Template was created by a Super User. Is that what you are asking?

**Comment by hjkatz** [comment] 2021-04-19 20:16
Could you try the same steps but have the Job Template created by a Team `member` of a different Team?

**Comment by tiagodread** [comment] 2021-04-23 14:53
@AlexSCorey @mabashian I ran into this problem while verifying https://github.com/ansible/awx/pull/9995

Steps to reproduce:

1. Create a survey for a job_template
2. Delete this survey
3. Attempt to create a new survey

Note: this is only happening for job templates

![chrome-capture (3)](https://user-images.githubusercontent.com/12464858/115889572-7137dc00-a42a-11eb-9697-687df18b02b7.gif)

![image](https://user-images.githubusercontent.com/12464858/115889676-86ad0600-a42a-11eb-9fbc-6091ec465293.png)

**Comment by AlexSCorey** [comment] 2021-04-23 15:09
@hjkatz 
> Could you try the same steps but have the Job Template created by a Team `member` of a different Team?

I think I'm a bit confused. Following the steps I mentioned above, but create a job template via a user on a different team.....a `normal user` who is a `member` on a team cannot create a job template. They can edit some portions of the job templates, but they cannot create it from scratch. 

I also tried creating a JT via is a super user, but is also on another (call it team 1) and then giving admin permissions on that JT in question to (team 2) and the normal user on that team can create a survey question

**Comment by akus062381** [comment] 2021-05-10 15:12
fixed. closing

**Closed as completed by akus062381** 2021-05-10 15:12 UTC
Labels: type:bug, component:ui
