### ISSUE TITLE
Custom Credential Types are not displayed

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9166] opened 2021-01-26 14:27 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX 17.0.0

Custom credential types are not displaying in list when clicking 'Add' in credentials. I have also seen that if a credential is not displayed in list, any previously created credential is not editable

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on linux, kubernetes
* Ansible version:  2.9
* Operating System: Centos
* Web Browser:

##### STEPS TO REPRODUCE

- Create 6+ custom credential types. 
- Go to Credentials and click 'Add'.
- Some of the credential types will be missing

##### EXPECTED RESULTS

All credential types should be displayed and available

##### ACTUAL RESULTS

Only 25 credential types are avialable.  It appears be a defect with the new UI.  The UI makes a AJAX call to https:/hostname/api/v2/credential_types , but the API is only displaying the first 25 results.  Therefore, anything on page 2 does not work.

It appears in the old UI, there was pagination of credential types going to URI https://hostname/api/v2/credential_types/?page_size=5&order_by=name&page=X

**Comment by AlexSCorey** [comment] 2021-01-26 15:06
@csdozier This PR should fix this issue https://github.com/ansible/awx/pull/9116.  

This seems to be duplicate of https://github.com/ansible/awx/issues/8944

**Closed as completed by AlexSCorey** 2021-01-26 15:06 UTC
Labels: type:bug
