### ISSUE TITLE
Workflow creation gui has text field disabled.

### ISSUE THREAD

**Issue by lordraw77** [ansible/awx#4161] opened 2019-06-25 13:14 UTC
##### ISSUE TYPE
 
 - Bug Report
 

##### COMPONENT NAME
 
 - UI
 
##### ENVIRONMENT
* AWX version: 5.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: centos 7.6.1810
* Web Browser: Google Chrome Versione 75.0.3770.100

##### STEPS TO REPRODUCE
![Cattura](https://user-images.githubusercontent.com/52206027/60101339-df8eb300-975b-11e9-8385-8d15f1d3019b.PNG)

open TEMPLATES   ->  CREATE WORKFLOW

##### EXPECTED RESULTS

fields are editable 

##### ACTUAL RESULTS

fields are disabled 

##### ADDITIONAL INFORMATION
 If i create a workflow using  tower-cli and then go on ui, i can edit the workflow

**Comment by Mvii7** [comment] 2019-06-25 14:20
I have the same issue. Using system admin account. 
Created` another user and added all permissions, didn't change anything. 

This ngDisabled is used on the form:
`ngDisabled: '!(workflow_job_template_obj.summary_fields.user_capabilities.edit || canAddWorkflowJobTemplate)'`

I'm using AWX v4.0.0

**Comment by sxnwlfkk** [comment] 2019-06-26 11:23
I too have this problem, with the same inputs and outcomes. Fresh install via docker-compose leads to this bug (tested 5 minutes ago), with fresh git clone and docker images purged before install (deleted all docker images and all containers). Running on Ubuntu 18.04.

**Comment by m4logs** [comment] 2019-06-26 11:50
> I too have this problem, with the same inputs and outcomes. Fresh install via docker-compose leads to this bug (tested 5 minutes ago), with fresh git clone and docker images purged before install (deleted all docker images and all containers). Running on Ubuntu 18.04.

Yes, the behaviour can be confirmed. Have you tried to create the "workflow job template" via tower-cli?
It seems to work. After that, the workflow jt is also editidable via GUI.

Anyway this not solve the initial issue.

**Comment by sxnwlfkk** [comment] 2019-06-26 15:06
> > I too have this problem, with the same inputs and outcomes. Fresh install via docker-compose leads to this bug (tested 5 minutes ago), with fresh git clone and docker images purged before install (deleted all docker images and all containers). Running on Ubuntu 18.04.
> 
> Yes, the behaviour can be confirmed. Have you tried to create the "workflow job template" via tower-cli?
> It seems to work. After that, the workflow jt is also editidable via GUI.
> 
> Anyway this not solve the initial issue.

 I can confirm, that when creating a workflow with tower-cli, that specific workflow is editable. When trying to add a new one from the browser, it's still greyed out.

**Comment by rooftopcellist** [comment] 2019-06-27 15:03
This is a duplicate of this issue: https://github.com/ansible/awx/issues/4091
This is fixed in devel by this PR: https://github.com/ansible/awx/pull/4096

Please let me know if you are able to reproduce on the devel branch.  Thanks!

**Closed as completed by rooftopcellist** 2019-06-27 15:03 UTC
Labels: type:bug, component:ui

**Comment by sxnwlfkk** [comment] 2019-06-29 09:54
> This is a duplicate of this issue: #4091
> This is fixed in devel by this PR: #4096
> 
> Please let me know if you are able to reproduce on the devel branch. Thanks!

I'm on devel branch.

**Comment by giovannifl** [comment] 2019-07-02 17:02
Just upgraded from AWX 5.0.0 to AWX 6.0.0 and now Workflow templates fields are editable.

**Comment by lordraw77** [comment] 2019-07-05 10:03
i just install AWX 6.0.0 and now Workflow templates fields are editable tnx

**Comment by rooftopcellist** [comment] 2019-07-05 22:02
@sxnwlfkk  What was the last commit on your AWX installation?  

I just pulled the latest code and built it and am not able to reproduce this bug.  

```
[chadams@rooftopcellist awx]$ git describe
6.0.0-618-g9b6644bc7
```
