### ISSUE TITLE
winrm connection fails awx2.1.0

### ISSUE THREAD

**Issue by TwoTwenty** [ansible/awx#2689] opened 2018-11-14 18:35 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

We could connect to our windows stations on 2.0.1 fine
as soon as we upgraded to 2.1.0 ansible could no longer connect to windows winrm 
even though winrm was specified awx tried to connect to these servers with ssh 

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.1

##### STEPS TO REPRODUCE

use awx2.1.0 with domain connected windows systems using winrm

these are the host variables applied at the top level of our windows invenotry:
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985
ansible_winrm_transport: kerberos
ansible_winrm_kerberos_delegation: true

**Comment by wenottingham** [comment] 2018-11-14 19:42
Can you debug whether those vars are properly set on the host when the playbook runs?

**Comment by wenottingham** [comment] 2018-11-14 19:47
I believe this is a duplicate of #2574 - the variables are not properly being assigned to the hosts (a known issue in 2.1.0).

**Closed as completed by wenottingham** 2018-11-14 19:47 UTC

**Comment by TwoTwenty** [comment] 2018-12-05 21:21
Thanks!
