### ISSUE TITLE
Can not disable/enable a schedule with a job survey that has required variables

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7521] opened 2020-07-01 19:27 UTC
##### STEPS TO REPRODUCE

* Create a job template that has a survey with required variables
* Create a schedule for that job
* disable the schedule

##### EXPECTED RESULTS

* To be able to disable the schedule

##### ACTUAL RESULTS

`{"variables_needed_to_start":["'no_spaces' value missing"]}` where `no_spaces` is the name of the job template survey required variable.

##### ADDITIONAL INFORMATION

PATCH

`{"enabled":false}`

**Comment by AlanCoding** [comment] 2020-11-19 16:28
> To be able to disable the schedule

Later on in the issue, you give a payload `{"enabled":true}`, so I'm not clear what the exact intention is here - enable or disable?

**Comment by chrismeyersfsu** [comment] 2021-02-01 20:40
Sorry @AlanCoding , fixed.

**Comment by vieiradaniel92** [comment] 2021-02-12 09:14
I'm also hitting this issue, running AWX 14.0.0.

**Comment by ghost** [comment] 2021-03-15 18:41
Having this same issue on AWX 17.1.0 - I just can't schedule a template that has a survey with required variables. The scheduler should let you specify the survey variables for that specific schedule.

**Comment by AlanCoding** [comment] 2021-04-19 18:33
I'd presume this was fixed with https://github.com/ansible/awx/pull/9890

**Comment by Raghavsfeb03** [comment] 2021-06-01 15:11
> Having this same issue on AWX 17.1.0 - I just can't schedule a template that has a survey with required variables. The scheduler should let you specify the survey variables for that specific schedule.

I am facing the same issue with AWX 17.1.0, unable to schedule a job, the specified survey variables don't show in the template 
to make an entry of the variables. But it throws error saying its missing the values !!!

**Comment by yagomarques** [comment] 2021-06-22 17:56
Closing this issue:

It's working on devel, it's was fixed on the https://github.com/ansible/awx/pull/9890. 

**survey**
![image](https://user-images.githubusercontent.com/18562328/122975149-6eddf980-d369-11eb-9d9a-fb66a997ad27.png)

**schedules**
![image](https://user-images.githubusercontent.com/18562328/122975290-946b0300-d369-11eb-9d0e-a6a0349223e7.png)

**job running just with the enabled schedule**
![image](https://user-images.githubusercontent.com/18562328/122975469-c0868400-d369-11eb-880f-6e929865bc2d.png)

**Closed as completed by yagomarques** 2021-06-22 17:56 UTC
Labels: type:bug, component:api

**Comment by Raghavsfeb03** [comment] 2021-06-23 05:52
The Issue is not still clear for you all.
In the Survey Tab we define a set of values, for example :
Datacenter: xyz
Team name: abc
Environment: QA/DEV
etc...

After you save these in Survey Tab, and now you come to Schedule, it shows only the defined values, and once you try to save it, Error is Thrown saying that you are missing the values for defined set of variables like:
Datacenter,..Team name,...etc 

Below is the case where: offering value, category value & Metro is defined in Survey Tab. 

But here is the error which can be seen : "It says offering value missing, category value missing  and Metro value missing" but there is no Tab which pulls these arguments from Survey Tab and shows to fill up, but it Throws error saying its missing !!!

![image](https://user-images.githubusercontent.com/77500204/123042808-fcc2ee80-d414-11eb-8cfb-d9a2a1414a42.png)


issue on AWX 17.1.0 - I just can't schedule a template that has a survey with required variables. The scheduler should let you specify the survey variables for that specific schedule right..??

**Comment by snehalpdev** [comment] 2022-08-22 23:39
@Raghavsfeb03  I have the same issue with scheduling the job for the job templates that has survey questions enabled. I am using AWX 17.1.0. Is your issue resolved? if yes, can you share details please.

**Comment by Raghavsfeb03** [comment] 2022-08-23 01:03
Hi,
this bug is not fixed at all.
Try developing your own scripts to get the schedule enabled.

**Comment by AlanCoding** [comment] 2022-10-20 18:45
There was another issue filed on this, and an updated fix landed in https://github.com/ansible/awx/pull/13035

Ping @mabashian FYI. I don't think we need to re-open this because it's solved now.
