### ISSUE TITLE
Single select Survey Question should allow for no answer

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10128] opened 2021-05-06 14:39 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When answering survey questions on a launched job template, a single select question should have an empty string as an answer choice, if the question is not required.

##### ENVIRONMENT
* AWX version: 18
* AWX install method:  docker for mac
* Operating System: Big Sur
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a survey with a single select question which is not required, and does not have a default value. Launch the job template

##### EXPECTED RESULTS

 The user should be able to submit the survey with no answer choice.  

##### ACTUAL RESULTS

The user is forced to select a choice.

##### ADDITIONAL INFORMATION
![choice](https://user-images.githubusercontent.com/39280967/117317103-35a00780-ae57-11eb-8ddf-4375575881ad.gif)

**Comment by mabashian** [comment] 2021-05-20 20:34
Dupe of https://github.com/ansible/awx/issues/9694

**Closed as completed by mabashian** 2021-05-20 20:34 UTC
Labels: type:bug, component:ui
