### ISSUE TITLE
Add Metrics For Monitoring Redis

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/awx#7704] opened 2020-07-22 10:58 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Can we add better metrics around redis on Ansible Tower metrics API endpoints ?

Above RFE will help the users to have more checks on redis.

**Comment by swiedernix** [comment] 2020-10-12 06:31
Hello @matburt ,
this ticket would be a good start for enhancing the tower metrics, we talked about that on thursday.
Made a similar internal RFE 
,
Thx Stefan Wiederoder

**Comment by swiedernix** [comment] 2020-10-12 06:37
redis for example:  how many callback tasks
1. redis: /opt/rh/rh-redis5/root/usr/bin/redis-cli -s /var/run/redis/redis.sock
redis /var/run/redis/redis.sock> llen callback_tasks
(integer) 28743

2. how many callback_receiver are running?   maybe someone dared to run more than standart ...   JOB_EVENT_WORKERS = 12

**Comment by ryanpetrello** [comment] 2020-10-12 17:57
@wenottingham are you still against the idea of adding per-node redis and callback statistics to `/api/v2/metrics/`?  We _could_ provide something like this, but it wouldn't be possible with the current architectural to show a composed view of "all nodes" (only the current node servicing the HTTP request).

**Comment by wenottingham** [comment] 2020-10-12 19:01
It just seems that per-node stats showing up on all nodes is more complex than we'd want to do (and risks showing out of date data)

**Comment by ryanpetrello** [comment] 2020-10-12 19:26
Per-node statistics would *probably* be something mostly useful for debugging and supportability; and having it at-a-glance in the API *would* be notably less effort in terms of quickly analyzing and diagnosing problem spots.

**Comment by ryanpetrello** [comment] 2020-10-12 19:39
> and risks showing out of date data

Spitballing implementation-wise, I'd expect this to be *at least* as up-to-date as the current heartbeat and capacity tracking mechanism, which is a periodic background task.  Maybe that's too infrequent, but I wouldn't imagine that the goal here is track *immediate* issues, but rather endemic callback issues that point to an overall throughput issue.

**Comment by ryanpetrello** [comment] 2020-11-25 19:52
@wenottingham is this a near-term priority that we should track more closely as an enhancement in the next major release?

**Comment by wenottingham** [comment] 2020-11-30 21:34
This reads as a subset of stats to track in https://github.com/ansible/awx/issues/8629, not just "redis stats"?

**Comment by wenottingham** [comment] 2021-02-01 22:13
Closing as duplicate of #8629

**Closed as completed by wenottingham** 2021-02-01 22:13 UTC
Labels: type:enhancement, component:api
