### ISSUE TITLE
Create a tower_instance_group module

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#8011] opened 2020-08-26 17:35 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per PR #7963 we are missing a module to interact with the instance_groups endpoint

**Comment by appuk** [comment] 2020-10-28 15:54
@beeankha I was able to create and edit an instance group using this module, but when I tried to delete the object using `state: absent`, it did not delete the instance group, and the task passed as ok

**Comment by ryanpetrello** [comment] 2020-10-28 16:27
@beeankha or @john-westcott-iv can one of you take a peek at this as you have available time?

**Comment by jbradberry** [comment] 2020-10-28 18:16
After taking a quick look at the merged PR, it looks to me as if the problem is a minor typo, `if state is 'absent'` instead of `if state == 'absent'`.

**Comment by ryanpetrello** [comment] 2020-10-28 18:38
@appuk can you give this another try?

**Comment by appuk** [comment] 2020-10-28 21:17
The instance group is deleted on stating `state: absent`, Hence closing!

**Closed as completed by appuk** 2020-10-28 21:17 UTC
Labels: type:enhancement, component:awx_collection
