### ISSUE TITLE
AWX 18.0 cannot process Collections

### ISSUE THREAD

**Issue by OneHappyForever** [ansible/awx#9801] opened 2021-04-03 13:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm running a playbook that requires community.general. I've added it in the collections/requirements.yml, and when pulling from the github image, it successfully downloads the collection. However, when running the template, it fails:

 ERROR! couldn't resolve module/action 'community.general.make'. This often indicates a misspelling, missing collection, or incorrect module path.

Successfully updates when pulling from github:
 "stdout": "Starting galaxy collection install process\nProcess install dependency map\nStarting collection install process\nDownloading https://galaxy.ansible.com/download/community-general-2.4.0.tar.gz to /var/lib/awx/projects/.__awx_cache/_8_[redacted]/stage/tmp/ansible-local-13665faiuim3c/tmpdzlqu4hb/community-general-2.4.0-x0ire3_5\nInstalling 'community.general:2.4.0' to '/var/lib/awx/projects/.__awx_cache/_8_[redacted]/stage/requirements_collections/ansible_collections/community/general'\ncommunity.general:2.4.0 was installed successfully",

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: awx via minikube
* Ansible version: 2.11
* Operating System: Centos7
* Web Browser:

##### STEPS TO REPRODUCE

- Try to use a galaxy package that is not prebuilt into execution environment. Adding it via collections/requirements.yml also fails

##### EXPECTED RESULTS

- It should have downloaded the package correctly and have recognized it when running the play

##### ACTUAL RESULTS

- It cannot find the package

**Comment by banshee091** [comment] 2021-04-03 17:25
Have the same problem. Tried already building a custom execution enviroment, still failed while running.

**Comment by lerminou** [comment] 2021-04-03 19:54
Workaround available here: https://github.com/ansible/awx/issues/9768

**Comment by shanemcd** [comment] 2021-04-03 20:58
This should be fixed in a release sometime early-mid next week.

**Comment by shanemcd** [comment] 2021-04-07 13:13
Seems like a dupe of https://github.com/ansible/awx/issues/9768.

**Closed as completed by shanemcd** 2021-04-07 13:13 UTC
Labels: type:bug
