### ISSUE TITLE
UI issue project add SCM schedule

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#258] opened 2017-09-22 19:01 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

PROJECTS "proj name" SCHEDULES  CREATE SCHEDULE do not work.
start date, local time zone, repeat frequency is manatory but is not possible to change.

##### STEPS TO REPRODUCE

add project with git scm., add  schedule of the project.

##### EXPECTED RESULTS

add option for schedule and save

##### ACTUAL RESULTS

No option in dropdowns list and start date do not work to add text or link/button.

**Comment by gconsidine** [comment] 2017-09-22 19:37
Thanks, @hemskgren.

This one looks like a duplicate of https://github.com/ansible/awx/issues/164. A fix is about getting ready for a merge soon here: https://github.com/ansible/awx/pull/244.

I'm closing this one for now, but feel free to reopen if I've misinterpreted your issue.

**Closed as completed by gconsidine** 2017-09-22 19:37 UTC
