### ISSUE TITLE
Webhook not triggering when playbook fails or  on success

### ISSUE THREAD

**Issue by bhismnarayan** [ansible/awx#1780] opened 2018-04-18 18:32 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
I have created a webhook notification I am able to test run it.But When I bind that notification to a template it does not trigger on success or failure.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: 
* Ansible version:  2.4.2.0
* Operating System:centos
* Web Browser:

##### STEPS TO REPRODUCE

Create a webhook  and bind it to a template for failure or success
##### EXPECTED RESULTS

I want webhook to get triggerred

##### ACTUAL RESULTS
Notification does not trigger

**Comment by hareld21** [comment] 2018-04-22 17:15
We are also interested in an answer to this case.

**Comment by ryanpetrello** [comment] 2018-04-23 15:44
I'm having a hard time reproducing this on a recent awx openshift install (`"version": "1.0.5.23",`):

![screen shot 2018-04-23 at 11 41 52 am](https://user-images.githubusercontent.com/214912/39137345-56d8b7de-46eb-11e8-9ead-e3a6f486e20d.png)

![screen shot 2018-04-23 at 11 42 25 am](https://user-images.githubusercontent.com/214912/39137389-6a82dfa8-46eb-11e8-9e6a-0ec5d10cee8a.png)

![screen shot 2018-04-23 at 11 43 32 am](https://user-images.githubusercontent.com/214912/39137445-90df0104-46eb-11e8-8af5-86610b46da44.png)

Are you sure that your `awx-celery` container has outbound internet connectivity?  Could you share your web hook configuration?

**Comment by hareld21** [comment] 2018-04-25 09:26
@ryanpetrello 
We're having this issue when trying to use production, not TESTING.

**Comment by bhismnarayan** [comment] 2018-04-25 09:54
Hi Ryan,
Below is the webtrigger url 
https://alphabhis123.azurewebsites.net/api/values
It works fine in postman for the post request .But the same stuff does not get triggered when added as webhook in awx

**Comment by ryanpetrello** [comment] 2018-04-25 13:00
@hareld21,

> We're having this issue when trying to use production, not TESTING.

Is there some tangible difference in your awx version between production and testing?  I deployed a recent awx image and pointed a web hook at `localhost:8000`, where I was running a local Python echo server via:

`python -m SimpleHTTPServer`

...and upon launching a Job Template, I was able to see a log line for my successful outbound webhook notification.

@bhismnarayan 

Are you able to confirm that https://alphabhis123.azurewebsites.net/api/values is _reachable_ from within your `awx-celery` container, e.g.,

`curl -X POST https://alphabhis123.azurewebsites.net/api/values`

What version of awx are you both using?

**Comment by bhismnarayan** [comment] 2018-04-25 17:24
Hi,
I get this message message on running the command
 curl -X POST https://alphabhis123.azurewebsites.net/api/values
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>

**Comment by ryanpetrello** [comment] 2018-04-25 18:00
@bhismnarayan which version of awx are you running?

**Comment by bhismnarayan** [comment] 2018-04-25 18:19
how do I get that?

**Comment by ryanpetrello** [comment] 2018-04-25 18:31
`awx-manage --version`

**Comment by ryanpetrello** [comment] 2018-04-25 18:40
Also, do you see any logs or error messages in the `awx-celery` container that suggest the web hook failed for some reason?

**Comment by bhismnarayan** [comment] 2018-04-26 03:41
I get command not found .when i run that comman

**Comment by ryanpetrello** [comment] 2018-04-26 13:05
@bhismnarayan,

You'll have to run the command from _within_ whatever environment awx is installed (i.e., from _within_ a Docker container, or one of your OpenShift pods) - I'm not sure which that is for you since the questions we ask for in the new issue template aren't answered in the issue description you created.

Can you update the ticket description with _all_ of the information requested in the New Issue template?

```
##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:
```

If you need additional help gathering this information, you might get quicker feedback in our IRC room (`#ansible-awx` on Freenode); conversation on Github issues like this can be slow and asynchronous, and are usually only answered by maintainers during EST business hours.

**Comment by wenottingham** [comment] 2018-06-01 17:39
Closing this - we still need more information on the version to properly debug, and this does appear to be a configuration issue at this time. Please reopen if you have the needed information.

**Closed as completed by wenottingham** 2018-06-01 17:39 UTC
Labels: type:bug, component:api
