### ISSUE TITLE
Expired OAuth2 tokens are not automatically removed

### ISSUE THREAD

**Issue by kruge002** [ansible/awx#2277] opened 2018-09-19 08:20 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
OAuth2 tokens having an expiration date in the past should be automatically deleted. 
A token listing can be retrieved by a GET request for /api/v2/tokens/
The list of tokens currently contains active and expired tokens but should show active tokens only.

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: docker
* Ansible version:  2.5.4
* Operating System: CentOS Linux 7.5.2804
* Web Browser: Google Chrome 68.0.3440.106

##### STEPS TO REPRODUCE
1. Update the value of ACCESS_TOKEN_EXPIRE_SECONDS from 31536000000 to 1200 by sending a PATCH request to /api/v2/settings/authentication/ (body: updated result of the GET request to /api/v2/settings/authentication/).
2. Create a token by sending a POST request to /api/v2/tokens/ having the following body: {"description": "My Access Token","scope": "write"}
3. Wait half an hour or more.
4. List all tokens by sending a GET request to /api/v2/tokens/
5. The expired token is present in the list of tokens.

##### EXPECTED RESULTS
I would expect the list of tokens to show active (non-expired) tokens only. Expired tokens should be removed automatically.

##### ACTUAL RESULTS
The list of tokens shows all tokens (active and expired). Expired tokens are never deleted.

##### ADDITIONAL INFORMATION
I can delete the expired token by sending a DELETE request to /api/v2/tokens/{id}/ but this should not be necessary in my opinion.

**Comment by rooftopcellist** [comment] 2018-10-30 21:04
@kruge002 some users may want the expired oauth2 tokens to persist after expiration for audit purposes.  

To selectively see just the active oauth2 tokens, you can filter that endpoint like this:

```
https://<awx-url>/api/v2/tokens/?expires__lt=<current-datetime>
```
I am looking into changing the filters so that you could filter with something like the follow, and not have to manually enter the current datetime.

```
https://<awx-url>/api/v2/tokens/?expires__lt=now
```

I agree that there should be a better way to delete the expired oauth2 tokens though.  I think there are two changes that should be made here:
1. Create an awx-manage command to clear all expired oauth2 tokens, and also selectively clear all oauth2 tokens for a specific user.  
2. Add a step to the tower cleanup job to clear oauth2 tokens that are older than a month old.

**Comment by rooftopcellist** [comment] 2019-01-18 16:24
There _is_ a management command to clear expired oauth2 tokens:

```
awx-manage cleartokens
```

Still need to:
- [x] make a schedule job to periodically `cleartokens`
- [ ] fix token filters

**Comment by ryanpetrello** [comment] 2019-05-23 14:08
@rooftopcellist is this a distinct issue, or just a duplicate of https://github.com/ansible/awx/issues/2701 at this point?

**Comment by rooftopcellist** [comment] 2019-05-23 15:13
@ryanpetrello The difference is this issue also tracks better filtering for expired tokens.  This is not as much of an issue now that expired tokens will be cleaned up periodically with the system job, but we could potentially add a filter here so that users can more easily query for only _valid_ tokens, i.e.: 

``` 
https://<awx-url>/api/v2/tokens/?expired=true
```

**Comment by gamuniz** [comment] 2023-04-10 19:06
There is a systemjob that cleans up expired tokens. Closing this as done

**Closed as completed by gamuniz** 2023-04-10 19:06 UTC
Labels: type:enhancement, component:api
