### ISSUE TITLE
Inventory Groups Columns Aren't Readable

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#3421] opened 2019-03-14 16:21 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Columns all messed up.  Can't read their contents

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker for mac
* Ansible version:  2.7.5
* Operating System:Mac OS
* Web Browser:Chrome

##### STEPS TO REPRODUCE

In inventories --> click on an inventory then --> Groups.  The columns with the actions, and group name are all jumbled.

##### EXPECTED RESULTS

To be able to read the contents of the column.

##### ACTUAL RESULTS

Can't read them

##### ADDITIONAL INFORMATION

Screenshot!
<img width="921" alt="Screen Shot 2019-03-14 at 12 17 27 PM" src="https://user-images.githubusercontent.com/39280967/54373436-9f477100-4653-11e9-826f-f3b62e5171f4.png">

**Comment by sumkincpp** [comment] 2019-03-14 16:31
Isn't this the same as #3158? 
The corresponding fix was merged after 3.0.1 release.

**Comment by AlexSCorey** [comment] 2019-03-15 14:04
Updating awx version for this issue as I'm still seeing it.  
```
3.0.1-236-ga63a204a2
```

**Comment by unlikelyzero** [comment] 2019-03-15 14:06
I spoke with @AlexSCorey and I think this is either directly caused by #3158 or is another symptom of the root cause (bootstrap upgrade).

@mabashian if you don't mind, could we do a root cause? I'm curious to know if it was a regression caused by #3158 or by the bootstrap upgrade itself

**Comment by unlikelyzero** [comment] 2019-03-27 15:00
Verified:
Group can be added
Group can be edited
Group can be sorted
No visual artifacts.
Found this defect: https://github.com/ansible/awx/issues/3522

**Closed as completed** 2019-03-27 15:56 UTC
Labels: type:bug, component:ui, good first issue, qe:regression, qe:visual
