### ISSUE TITLE
Job distribution on awx-task is not even

### ISSUE THREAD

**Issue by sbenita** [ansible/awx#9211] opened 2021-02-02 20:00 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using K8S container group only, the process of the pending tasks assigns the task mostly to the first host in the tower group.
https://github.com/ansible/awx/blob/7d432e484cbdc6393d0b04e65bd8beef30a75ed6/awx/main/scheduler/task_manager.py#L288
The selection of a host as controller node does not "cost" it with capacity even it have impact on the node

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.9
* Operating System: ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Configure AWX to work with container group, scale the awx pod to 3.
Lunch multiple jobs on the container group

##### EXPECTED RESULTS

The load should spread evenly on the awx-task containers

##### ACTUAL RESULTS

The first awx-task container (order by name) gets 90% of the load.
Lot of jobs are pending in his queue

**Comment by blomquisg** [comment] 2021-02-08 20:17
Good issue for a spike for someone to deep dive on the scheduler

**Comment by sbenita** [comment] 2021-02-09 05:28
We currently changed the code to use random choice, it solved the issue for us.
It should be different solution, utilizing the capacity of each node.

**Comment by kdelee** [comment] 2022-01-28 22:31
@sbenita fwiw, I'm working on this now.
Other issue:
https://github.com/ansible/awx/issues/10694
PR: https://github.com/ansible/awx/pull/11620

I'm going to close this as a duplicate of https://github.com/ansible/awx/issues/10694, please put any updates over there or on the PR.

Also, happy to hear any other observations you have. I'm working a number of issues around container group jobs and the k8s deployment general

**Closed as completed by kdelee** 2022-01-28 22:31 UTC
Labels: type:bug, component:api
