### ISSUE TITLE
Run AWX in non-privileged mode in Kubernetes

### ISSUE THREAD

**Issue by Vacant0mens** [ansible/awx#7916] opened 2020-08-17 16:11 UTC
##### ISSUE TYPE

 - Feature Request

##### COMPONENT NAME

 - Installer

##### SUMMARY

The kubernetes environment I'm working with doesn't allow privileged pods/containers, so I'm trying to find a way to make the AWX installer work. I have tried different configuration changes. ~~but hit a wall with the Postgres server/service (I assume it's there for Django?). It was suggested in other issues to map a pg_hba.conf file from my local machine, but the cluster is remote, so that won't work. It was also suggested that I disable BubbleWrap, which could work, but the AWX system has to be started for that to work. Kubernetes doesn't recognize that the pods are started because of the error I'm getting with Postgres.~~

##### ENVIRONMENT
* AWX version: latest/master
* AWX install method: kubernetes
* Ansible version:  2.9.12
* Operating System: Ubuntu 18.04 (installing to kubernetes 1.17)
* Web Browser:

##### EXPECTED RESULTS
An easy/easier way to change the kubernetes installer playbook/helm chart to run AWX in non-privileged pods/containers.

##### ACTUAL RESULTS
~~After many configuration changes and tests (including reading [this](https://github.com/ansible/awx/issues/4286) issue), Postgres wouldn't allow the task container to connect (error said that the IP for the container/pod and/or username wasn't allowed in the pg_hba.conf file.)~~ See changes/updates below.
In  [this](https://github.com/ansible/awx/issues/4286) issue, it was suggested that I turn off BubbleWrap _after_ the initial setup. If it's running in an un-privileged environment, that should be something that comes already-disabled.

##### ADDITIONAL INFORMATION
~~All of the instructions I've found about running non-privileged are for DockerCompose, and aren't very helpful in a Kubernetes system since I can't share host volumes to the pod (this is a remote cluster), and everything is abstracted through templates.~~

Also, is there a way to just do the Helm install by itself without having to go through ansible-playbook? seems a bit counter-intuitive to have ansible install ansible, at least for kubernetes.

**Comment by ryanpetrello** [comment] 2020-08-17 16:12
related: https://github.com/ansible/awx/issues/7060

**Comment by Vacant0mens** [comment] 2020-08-19 17:38
Things that need to change for un-privileged to work properly:
```
./installer/roles/kubernetes/templates/configmap.yml.j2: 
    AWX_PROOT_ENABLE -> False
./installer/roles/kubernetes/defaults/main.yml (unsure if these are needed, seems like it):
    awx_psp_privileged -> false
    task_security_context_privileged -> false 
```

I was mistaken about postgres being the problem. I had it running on an external server and forgot where it was. I will update the initial post.


I wonder if instead of changing these settings, we could add a variable to the inventory that would make those changes for you?

**Comment by wenottingham** [comment] 2020-08-19 19:23
This shouldn't be an installer variable because it's wildly insecure until work such as https://github.com/ansible/awx/issues/7060 is done.

**Comment by ryanpetrello** [comment] 2020-08-19 19:29
Yep - the main reason we disabled this is because running without some form of process isolation (what bubblewrap currently provides) is woefully insecure.

**Comment by wenottingham** [comment] 2020-08-21 17:08
Closing as a duplicate of #7060

**Closed as completed by wenottingham** 2020-08-21 17:08 UTC
Labels: component:installer

**Comment by Vacant0mens** [comment] 2020-08-21 17:35
@wenottingham This is not a duplicate. This feature request is for being able to run AWX in non-privileged containers. Issue 7060 is about changing from BubbleWrap to Container-based execution. While the two are related, they are not the same.

**Comment by wenottingham** [comment] 2020-08-21 18:48
We have no plans to tackle this outside of that.
