### ISSUE TITLE
[CLI] RFE: associate/dissociate instance groups to objects that use them.

### ISSUE THREAD

**Issue by swatinarvekar** [ansible/awx#9622] opened 2021-03-19 11:05 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently we have associate/dissociate for notifications and credentials on organizations.
Do not have this for instance groups.

**awx organizations associate**
```
usage: awx organizations associate [-h]
                                   (--start_notification  | --success_notification  | --failure_notification  | --approval_notification  | --galaxy_credential )
                                   id
id
-h, --help
show this help message and exit

--start_notification <start_notification>
The ID (or name) of the notification_template to associate

--success_notification <success_notification>
The ID (or name) of the notification_template to associate

--failure_notification <failure_notification>
The ID (or name) of the notification_template to associate

--approval_notification <approval_notification>
The ID (or name) of the notification_template to associate

--galaxy_credential <galaxy_credential>
The ID (or name) of the credential to associate
```
(Similar to https://tower-cli.readthedocs.io/en/latest/api_ref/resources/organization.html#tower_cli.resources.organization.Resource.associate_ig)

**Comment by ryanpetrello** [comment] 2021-03-19 13:45
duplicate of https://github.com/ansible/awx/issues/4698

**Closed as completed by ryanpetrello** 2021-03-19 13:45 UTC
