### ISSUE TITLE
In Workflow Viz, cannot replace a missing JT

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4524] opened 2019-08-20 14:55 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In Workflow Viz, cannot replace a missing JT in WFJT. The scenario being: a Workflow JT contained a JT and that JT was deleted and a user wants to replace the missing JT.

##### ENVIRONMENT
* AWX version: 6.0.0 (may go back further than 5.0.0
* Web Browser: Firefox and Chrome

##### STEPS TO REPRODUCE
1. Create a WFJT with JT A
2. Delete JT A
3. Navigate back to WFJT and attempt to replace missing JT node
Note: cannot replace missing JT node

##### EXPECTED RESULTS

A user should be able to replace a missing JT node on the WFViz

##### ACTUAL RESULTS

No option available to select a new node to replace missing JT

##### ADDITIONAL INFORMATION

HAR File
[Archive 19-08-20 10-54-02.har.zip](https://github.com/ansible/awx/files/3521245/Archive.19-08-20.10-54-02.har.zip)

<img width="1496" alt="Screen Shot 2019-08-20 at 10 50 21 AM" src="https://user-images.githubusercontent.com/12446869/63358170-99f3fe00-c338-11e9-9650-fc99713970e6.png">

```
TypeError: $scope.nodeConfig.node.originalNodeObject.summary_fields.unified_job_template is undefined
Stack trace:
setupNodeForm/<@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/app.ce6c9b917f2711539ae9.js:29:1209569
processQueue@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:134656
scheduleProcessQueue/<@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:135605
$digest@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:146521
$apply@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:149463
done@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:101267
completeRequest@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:106296
createHttpBackend/</xhr.onload@https://ec2-52-91-194-47.compute-1.amazonaws.com/static/js/vendor.0ea93a32277ab6533bcc.js:575:107075
Possibly unhandled rejection: {}
```

**Comment by mabashian** [comment] 2019-08-30 17:55
This _could_ still be a bug but it might have been fixed when the wf pause/approve branch was merged.  Lets double check the reproduction on this one - we may be able to move to needs_test if it's been addressed.

**Comment by AlexSCorey** [comment] 2019-09-10 14:48
Looks like this bug is fixed in devel.

**Comment by dsesami** [comment] 2019-09-13 19:01
I've attempted to delete + reintroduce a new JT on workflows. This appears to function normally now, with differing types of workflows (converged, recursive). closing and marking as fixed.

**Closed as completed by dsesami** 2019-09-13 19:01 UTC
Labels: type:bug, component:api, component:ui
