### ISSUE TITLE
AWX not started after reboot

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#227] opened 2017-09-20 19:40 UTC
##### ISSUE TYPE

 - Documentation Report?

##### COMPONENT NAME

 - Installer

##### SUMMARY

AWX starts after it's built. But after restarting the server, AWX is not started; there are no docker containers running

Is there documentation how to start AWX?

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by sparkacus** [comment] 2017-09-20 19:45
Not sure if this is the right way to do it, but I just run the install.yml and it'll start everything for you. You may need to make sure services like docker are enabled to start on boot.

**Comment by naisanza** [comment] 2017-09-20 20:52
@sparkacus you mean rebuild AWX each time?

**Comment by mwasilew2** [comment] 2017-09-20 21:01
I believe this is a duplicate of #210

**Comment by naisanza** [comment] 2017-09-20 21:12
@mwasilew2 oh look at that timing. I guess AWX is still early in its development?

**Comment by LukeShortCloud** [comment] 2017-09-20 22:11
@naisanza For clarification, AWX is the upstream version of the Red Hat Ansible Tower. Ansible Tower itself is the tried, tested, and trusted downstream version that is recommended for production workloads. AWX serves as Red Hat's way to push out and test updates quicker before eventually making their way into Ansible Tower. As part of the continual development, running this product in containers is indeed a relatively new feature that is still being worked and improved on.

You can find some information about this here: https://www.ansible.com/awx-project-faq

This issue can be closed as a duplicate.

**Closed as completed** 2017-09-20 23:16 UTC

**Comment by naisanza** [comment] 2017-09-20 23:48
@ekultails I'm usually pretty late to the game with things, and usually assume I'm doing something wrong when something doesn't work as expected. But glad to be a part of seeing what's coming out
