### ISSUE TITLE
Cannot create Azure Storage Account. Version Error. 

### ISSUE THREAD

**Issue by thevman** [ansible/awx#1428] opened 2018-03-02 18:28 UTC
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME

 - API
 - UI
 ##### SUMMARY
Cannot create an Azure storage account because of a version mis-match.
##### ENVIRONMENT
* AWX version: 1.0.4.38
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Ubuntu
* Web Browser:
Chrome
##### STEPS TO REPRODUCE
Create a Playbook to create a Storage Account in Azure. 
```
# Playbook.yml
---
# Create Storage Account
hosts: localhost
---
- name: Create Infrastructure
  hosts: localhost
  tasks: 
   - name: Create storage account
      azure_rm_storageaccount:
        resource_group: "{{ azurevm_resource_group }}"
        name: " {{ azurevm_storage_name }}"
        account_type: "{{ azurevm_storage_type }}"
```
Then Use this within a template in AWX to Create the account. 

##### EXPECTED RESULTS
 Storage Account Created

##### ACTUAL RESULTS

You will get the following error: 
"msg": "Installed storage client version is 1.2.1. The supported version is 1.5.0. Try `pip install ansible[azure]`"
##### ADDITIONAL INFORMATION

I believe this may be linked to the "azure" entry in "requirements.txt". The Azure cli is at version 3.0.0 and we're still using 2.0. Can this be upgraded? I tried building the images myself but ran into a host of other problems.

**Comment by wenottingham** [comment] 2018-03-02 18:37
Marking as a duplicate of https://github.com/ansible/awx/pull/1415

**Closed as completed by wenottingham** 2018-03-02 18:37 UTC

**Comment by AlanCoding** [comment] 2018-03-02 18:38
Looks consistent with being fixed by this change

https://github.com/ansible/awx/pull/1415/files#diff-8dd294ec5d9417d0b6c37b06f3a78428L5
