### ISSUE TITLE
Fact Caching breaks dynamic source inventory variables

### ISSUE THREAD

**Issue by joshbenner** [ansible/awx#422] opened 2017-10-12 22:58 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API ?

##### SUMMARY
I have a dynamic inventory whose script is in a Git repo. AWX successfully runs it via a "Sourced from a project" source configuration, and all the hosts and variables get imported.

If I add a variable to the inventory's group_vars, on the next import, the new variable is correctly added to the appropriate hosts, confirmed by viewing the host variables in the inventory in AWX.

However, when I run a job with fact caching that tries to use that new variable, the variable is not found. Repeated re-syncs of the source do not resolve the issue.

##### ENVIRONMENT
* AWX version: 1.0.1.14
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: ubuntu 16.04
* Web Browser: Chrome

##### EXPECTED RESULTS

New variable is visible to playbook runs.

##### ACTUAL RESULTS

Variable is not found.

##### ADDITIONAL INFORMATION

If I turn Fact Caching off, the job succeeds (the variable is found).

**Comment by wenottingham** [comment] 2017-10-13 02:05
What happens if you use Ansible 2.3? This sounds like a known issue with AWX + 2.4.0.

**Comment by stokkie90** [comment] 2017-10-13 07:07
Having a similar problem. Also when enabling fact caching and using a inventory script, it can't find any hosts. 

When running ansible 2.3.2.0 It's working again. 

Although i'm not running it inside docker or openshift.

**Comment by mkempster22** [comment] 2017-10-13 10:31
Wow just came on here to have a look, been spending the last 4 hours trying to fix a 'No hosts matched' issue with my sourced inventory file

I got it to work by using a smart filter inventory, But if I disable Fast Caching like you say the main inventory now works

I am on ansible 2.3.2.0 using an inventory from a Satellite 6 server

**Comment by mkempster22** [comment] 2017-10-13 10:35
Here is what I get if I run a job with fast caching against my main inventory:

Enter passphrase for /tmp/awx_60_cLD8If/credential_4: 

Identity added: /tmp/awx_60_cLD8If/credential_4 (/tmp/awx_60_cLD8If/credential_4)

Using /etc/ansible/ansible.cfg as config file

 [WARNING]:  * Failed to parse /usr/lib/python2.7/site-

packages/awx/plugins/inventory/awxrest.py with script plugin:


 [WARNING]:  * Failed to parse /usr/lib/python2.7/site-

packages/awx/plugins/inventory/awxrest.py with ini plugin: /usr/lib/python2.7

/site-packages/awx/plugins/inventory/awxrest.py:35: Expected key=value host

variable assignment, got: json

 [WARNING]: Unable to parse /usr/lib/python2.7/site-

packages/awx/plugins/inventory/awxrest.py as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: _REDACTED_


PLAY [all] *********************************************************************11:25:17

skipping: no hosts matched

PLAY RECAP *********************************************************************11:25:17

**Comment by wenottingham** [comment] 2017-10-13 13:07
Closing as a duplicate of #246 - use 2.3.2 or wait for 2.4.1, and we may merge a workaround in AWX for the short term.

**Closed as completed by wenottingham** 2017-10-13 13:07 UTC
Labels: type:bug

**Comment by mkempster22** [comment] 2017-10-13 14:00
My current ansible version whilst getting that issue, Doesn't look like downgrading is a fix
ansible --version
ansible 2.3.2.0
