### ISSUE TITLE
Project Sync Never Finishes

### ISSUE THREAD

**Issue by bandwiches** [ansible/awx#11496] opened 2021-12-30 15:54 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Initial project setup worked fine and took ~30 seconds.  Additional sync of that same project sits in a "running" state indefinitely.  I'm not entirely sure how to go about finding more details other than this.  STDOUT for the job itself is just blank.  The job itself can be cancelled.

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.11.7.post0]

### Operating system

Ubuntu

### Steps to reproduce

Create a project (Git/SCM) and sync it.

### Expected results

Expected a pretty quick sync, but just see the job sitting in a running state indefinitely.

### Actual results

Job never completed.

**Comment by bandwiches** [comment] 2021-12-30 18:09
After further testing, I've found that this only happens when using the SSH method versus HTTPS method.

Did you test SSH from the node? Yes, it worked.
Did you test cloning from the node via SSH? Yes, it worked.
Is the same private key used for an AWX credential? Yes
Did sync work? No, spun indefinitely (running)

Creating a credential using username/password and creating a project using the HTTPS URL for the repo, everything worked fine.  Please note that both methods (SSH & HTTPS) work fine on the host outside of AWX.

**Comment by AlanCoding** [comment] 2022-01-06 15:28
I'm wondering if this might be the same as #11453, because for these SCM SSH credentials, I believe it uses the same logic as job SSH credentials. There might be some helpful hints to asses this in that issue or others linked from it.

**Comment by craph** [comment] 2022-01-11 08:21
@bandwiches Hi,
I have the same issue like you. you can find my issue here #11518 
I did all the same test like you.

It's a very weird behavior...

**Comment by bandwiches** [comment] 2022-01-12 17:24
@craph looks to be the same to me.  I haven't had the cycles to investigate any further, I just decided to use HTTPS for now instead of SSH and will swap back once it's fixed.  I'm also unable to view any additional logs, the jobs are just blank.

@AlanCoding not sure on that one, that's over my head at the moment.

**Crowdstrike** - this is a recurring noun in all of these tickets, we also have Crowdstrike running at the host level.  If I can find the time today, I'll investigate if the SSH Sync works when that's turned off.

**Comment by craph** [comment] 2022-01-12 20:18
@bandwiches as you can see in my issue #11518 I have added extra info and some tests. 

I can confirm that when I turn off the service falcon-sensor (crowdstrike) all is working fine.

Moreover, when I ran the command `ps -ef | cat` in the ˋawx-eeˋ I can see the process "ssh-add..." stuck. This process try to create the pipe file to store the ssh credential. Then if you try to echo your credential private key in the pipe file you will be able to see that the process is running well.

So something seems wrong with crowdstrike and pipe file from awx

**Comment by shanemcd** [comment] 2022-01-31 18:29
Closing this in favor of https://github.com/ansible/awx/issues/11518 since the problem has been pinpointed in that issue.

**Closed as completed by shanemcd** 2022-01-31 18:29 UTC
Labels: needs_triage
