### ISSUE TITLE
Inventory sync seems to be treating python script as yaml file instead of actually running the script

### ISSUE THREAD

**Issue by mattthehearn** [ansible/awx#878] opened 2017-12-21 16:38 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
I wrote a simple python script to talk to Spacewalk's API and generate an inventory.  However, it seems like AWX is treating the script as a yaml file instead of actually running the script and generating the output, because I get a bunch of errors like these:

ERROR! Could not parse inventory source /tmp/awx_inventory_Glhd_l/tmpRLGNU9 with available plugins:
Plugin script failed: failed to parse executable inventory script results from /tmp/awx_inventory_Glhd_l/tmpRLGNU9: Syntax Error while loading YAML.

The error appears to have been in '/tmp/awx_inventory_Glhd_l/tmpRLGNU9': line 5, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

import sys

The script itself runs fine from a command line and produces expected JSON output.  It's more than likely I'm screwing something up here, but I can't figure out what it might be.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Centos 7.4
* Web Browser: Chrome 

##### STEPS TO REPRODUCE
Create a new inventory script with the attached script.  Create an inventory that uses the script as the source.  Attempt to sync.

##### EXPECTED RESULTS
It should populate the inventory with the hosts it pulls from Spacewalk.

##### ACTUAL RESULTS
It throws a bunch of errors about YAML parsing.  (I'll attach the full stdout/stderr.)

##### ADDITIONAL INFORMATION
The script:
---------------------------------------------------------------------
#!/usr/bin/python
import xmlrpclib
import json
import sys

if len(sys.argv) != 2:
  print "Usage: " + sys.argv[0] + "[--host | --list]"
  exit(1)

if sys.argv[1] == "--host":
  print "{}"

if sys.argv[1] == "--list":
  SATELLITE_URL = "http://fake.api.url.here/"
  SATELLITE_LOGIN = "auserofsomesort"
  SATELLITE_PASSWORD = "this is not my actual password"

  client = xmlrpclib.Server(SATELLITE_URL, verbose=0)

  key = client.auth.login(SATELLITE_LOGIN, SATELLITE_PASSWORD)
  grouplist = client.systemgroup.listAllGroups(key)

  print "{"
  print " \"_meta\": {"
  print "         \"hostvars\": {}"
  print " }"

  for group in grouplist:
    groupname=group.get('name')
    print "       \"" + groupname + "\": {"
    #print "[" + groupname.lower() + "]"
    systemlist = client.systemgroup.listSystems(key, groupname)
    print "               \"hosts\":"
    systemnames=[]
    for system in systemlist:
      systemnames.append(system.get('profile_name'))
      #print system.get('profile_name')
    print json.dumps(systemnames)
    print "       },"

  print " \"Ungrouped\": {"
  systemlist = client.system.listUngroupedSystems(key)
  systemnames=[]
  for system in systemlist:
    systemnames.append(system.get('name'))

  print json.dumps(systemnames)
  print " }"

  print "}"
  client.auth.logout(key)

---------------------------------------------------------------------

The full output in AWX:
---------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.1.295', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1000, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 178, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 162, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=4) with stdout:

stderr:
ERROR! Could not parse inventory source /tmp/awx_inventory_Glhd_l/tmpRLGNU9 with available plugins:
Plugin script failed: failed to parse executable inventory script results from /tmp/awx_inventory_Glhd_l/tmpRLGNU9: Syntax Error while loading YAML.

The error appears to have been in '/tmp/awx_inventory_Glhd_l/tmpRLGNU9': line 5, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

import sys

       ^ here

exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a flow mapping
  in "<unicode string>", line 1, column 1
did not find expected ',' or '}'
  in "<unicode string>", line 5, column 8

Plugin yaml failed: Syntax Error while loading YAML.

The error appears to have been in '/tmp/awx_inventory_Glhd_l/tmpRLGNU9': line 6, column 22, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

if len(sys.argv) != 2:
                     ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: mapping values are not allowed in this context
  in "<unicode string>", line 6, column 22
Plugin ini failed: /tmp/awx_inventory_Glhd_l/tmpRLGNU9:2: Expected key=value host variable assignment, got: xmlrpclib

---------------------------------------------------------------------

**Comment by AlanCoding** [comment] 2017-12-21 20:41
Ansible doesn't know what format of inventory you're providing it in advance. It tries enabled plugins one-by-one, and uses the first one that is successful.

The script plugin doesn't _just_ execute the script. It also parses the output. It looks like it's parsing it as YAML (which is a superset of JSON, so okay).

> The offending line appears to be:
> 
> import sys

Looks like you discovered a new Ansible bug!

I have reproduced a similar situation with https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/scripts/incorrect/bad_format.py

It gives

```
[WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/ansible-inventory-file-examples/scripts/incorrect/bad_format.py with script plugin: failed to parse executable
inventory script results from /Users/alancoding/Documents/repos/ansible-inventory-file-examples/scripts/incorrect/bad_format.py: Syntax Error while loading YAML.   expected ',' or
'}', but got '<stream end>'  The error appears to have been in '/Users/alancoding/Documents/repos/ansible-inventory-file-examples/scripts/incorrect/bad_format.py': line 2, column
1, but may be elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:  #!/usr/bin/env python # -*- coding: utf-8 -*- ^ here
```

note

> The offending line appears to be:  #!/usr/bin/env python # -*- coding: utf-8 -*- ^ here

This is confusing and wrong. The script output is

```json
{"_meta": {"hostvars": {}}
```

But the message refers to content from the script file. It never parsed the script file, it _executed_ it. It failed to parse the _output_ of the script.

This _is_ a bug, but it's not an AWX bug so I'm closing this issue.

**Closed as completed by AlanCoding** 2017-12-21 20:41 UTC

**Comment by AlanCoding** [comment] 2017-12-21 20:54
issue filed in Ansible core (linked)
