### ISSUE TITLE
Job templates do not respect the inventory prompt

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#1302] opened 2018-02-20 14:47 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Job templates do not respect the inventory prompt they always fall back to whatever is saved in the job template. 

##### ENVIRONMENT
* AWX version: 1.0.3.58
* AWX install method: docker on linux
* Ansible version:  2.4.0.3

##### STEPS TO REPRODUCE

1) create a job template and make Inventory prompt at launch - you'll also have to specify something in the inventory field otherwise you can't save it.
2) attempt to launch the box and fill in the inventory prompt

##### EXPECTED RESULTS

Job template runs against inventory selected at the prompt

##### ACTUAL RESULTS

Job template runs against the saved inventory in the template

##### ADDITIONAL INFORMATION

This was fine on 1.0.3.38. Even though you still had to have something in the inventory field on the template, you could still tick the prompt on launch field and it would run against what ever was chosen at launch.

**Comment by AlanCoding** [comment] 2018-02-20 15:11
Confirmed bug. New inventory is shown in the preview screen, but does not get submitted in the POST data.

**Comment by AlanCoding** [comment] 2018-02-26 20:05
Closing as this is a duplicate of #1281

**Closed as completed by AlanCoding** 2018-02-26 20:05 UTC
Labels: type:bug, component:ui
