### ISSUE TITLE
ansible tower is not maintaining order in which inventory files gets played

### ISSUE THREAD

**Issue by madhan-dc** [ansible/awx#5370] opened 2019-11-21 14:01 UTC
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

 - API
 
##### SUMMARY

I have a playbook that has a task like this
  ` - template:
        src: ../files/kfhost.j2
        dest: /app/bin/kafka/server.properties
        owner: kafka
        group: kafka
        mode: 0755
   `
the jinga file has a line like this
`broker.id={{ play_hosts.index(inventory_hostname)+1 }}`

I have an inventory file like this

[all]
server1
server2
server3

when i run this playbook from command line, 
server1 gets broker.id=1, server2 gets broker.id=2 and server3 gets broker.id=3 as expected and always

when i run the same playbook in tower, sometimes
server1 gets broker.id=2 and server2 gets broker.id=1

just fyi. there are a few tasks before this as well but very simple tasks that just do set_fact.

the mismatch in order never happens when i run the playbook from ansbile-playbook command line

##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: openshift
* Ansible version:  2.6.4
* Operating System: linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

Description shows the task i am trying to run. you can create a playbook with similar task and inga file.
##### EXPECTED RESULTS

i would like the behavior to be the same when i run the playbook from command line 
##### ACTUAL RESULTS

the order as explained seems to be mismatched when running the playbook in tower

**Comment by shanemcd** [comment] 2019-11-21 14:05
Are you using Tower or AWX? If you are using Tower, please contact support. If you are on AWX, version 1.0.8 is over a year old at this point. Are you able to reproduce on a more recent version?

**Comment by AlanCoding** [comment] 2019-11-21 19:25
Looks like a duplicate of https://github.com/ansible/awx/issues/2240, let me know if I have that wrong.

**Closed as completed by AlanCoding** 2019-11-21 19:25 UTC
Labels: type:bug, component:api
