### ISSUE TITLE
plugin: inventory config specifies unknown plugin 'amazon.aws.aws_ec2'

### ISSUE THREAD

**Issue by thedavidwhiteside** [ansible/awx#8481] opened 2020-10-28 19:15 UTC
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: AWX 15.0.0  
* AWX install method: docker on linux (k8)
* Ansible version:  2.9.13
* Operating System: CentOS8
* Web Browser: Any

##### STEPS TO REPRODUCE

I installed AWX using awx-operator (https://github.com/ansible/awx-operator) on a k8 cluster.  Tried to setup an inventory source from AWS EC2.  The sync resulted in below error where awx was unable to find the aws inventory plugin.

##### EXPECTED RESULTS

Expected sync to work.

##### ACTUAL RESULTS

`
    1.828 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_24_icp36wy7/aws_ec2.yml --playbook-dir /tmp/awx_24_icp36wy7 -vvvvv
    1.828 INFO     Reading Ansible inventory source: /tmp/awx_24_icp36wy7/aws_ec2.yml
    1.829 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    1.829 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    1.829 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1142, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1032, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 208, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 191, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
[WARNING]:  * Failed to parse /tmp/awx_24_icp36wy7/aws_ec2.yml with auto
plugin: inventory config '/tmp/awx_24_icp36wy7/aws_ec2.yml' specifies unknown
plugin 'amazon.aws.aws_ec2'
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 53, in parse
    raise AnsibleParserError("inventory config '{0}' specifies unknown plugin '{1}'".format(path, plugin_name))
[WARNING]: Unable to parse /tmp/awx_24_icp36wy7/aws_ec2.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.`

**Comment by wenottingham** [comment] 2020-10-28 19:37
Are you able to reproduce this with the standard k8s installation? It may be a bug in the operator.

**Comment by thedavidwhiteside** [comment] 2020-10-28 21:07
I haven't tested a standard k8 install.  I believe your correct and this may be the operator bug https://github.com/ansible/awx-operator/issues/36

- David

**Comment by wenottingham** [comment] 2020-10-28 22:37
Yes, https://github.com/ansible/awx-operator/issues/36 looks like it would cause this exact error. Closing this issue.

**Closed as completed by wenottingham** 2020-10-28 22:37 UTC
Labels: type:bug
