### ISSUE TITLE
User details

### ISSUE THREAD

**Issue by oguzhansrky** [ansible/awx#8879] opened 2020-12-13 15:46 UTC
Hi,

ansible docker installed.

is this screen correct? it was not like this before.
![image](https://user-images.githubusercontent.com/52497227/102016733-5e721400-3d73-11eb-980c-dbf91fddfc1e.png)

user details...
![image](https://user-images.githubusercontent.com/52497227/102016741-6762e580-3d73-11eb-877f-04b85fa46829.png)

**Comment by unlikelyzero** [comment] 2020-12-13 16:20
@oguzhansrky, thank you for filing this bug. It is a currently known issue, so I'll file this as a duplicate of https://github.com/ansible/awx/issues/8478

Please follow that issue to see when will make it's way into an awx release

**Closed as completed** 2020-12-13 16:21 UTC
Labels: type:bug
