### ISSUE TITLE
Editing workflow breaks extra_vars

### ISSUE THREAD

**Issue by blindrood** [ansible/awx#4293] opened 2019-07-09 07:42 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Editing workflow generates lots of issues with extra vars on job templates

##### ENVIRONMENT
* AWX version:6.0.0
* AWX install method: docker
* Ansible version:  2.8.1
* Operating System: Win
* Web Browser: FF/Chrome

##### STEPS TO REPRODUCE

Edit existing workflow template.

##### EXPECTED RESULTS

Everything is working as on v3 

##### ACTUAL RESULTS

Workflow designer to some jobs adds pipe to extra vars, like this:
```
|
  {}
```
Causing error: Failed to parse variables. Attempted to parse yaml. Parser did not return an object.

On other jobs it splits extra vars content char by char generating list of numbered, one char vars, like this:
https://gist.github.com/blindrood/156a73d31654114508bff7307ef2fdd1

**Comment by ghjm** [comment] 2019-07-12 17:26
Possible duplicate of #4303

**Comment by mabashian** [comment] 2019-07-12 18:31
@blindrood you'll have to provide some more information to help us reproduce this issue.  Can you describe the setup of the job template being referenced in the workflow?  What fields are promptable?  Does it have a survey?  If possible can you provide a gif or screenshot of the error being reproduced?

**Comment by blindrood** [comment] 2019-07-15 05:57
Some templates have survey, some doesn't. Seems like, if there's no extra_var then a pipe is added. If there's something, then it's splitted
![Adnotacja 2019-07-15 075225](https://user-images.githubusercontent.com/48821393/61197546-d5fec800-a6d5-11e9-90e6-4f064a52b15f.jpg)
![Adnotacja 2019-07-15 075808](https://user-images.githubusercontent.com/48821393/61197625-57565a80-a6d6-11e9-805d-0be2fd7b5456.jpg)
![Adnotacja 2019-07-15 075405](https://user-images.githubusercontent.com/48821393/61197551-d8f9b880-a6d5-11e9-9c8a-dda89ac30c99.jpg)

**Comment by blindrood** [comment] 2019-08-01 08:54
We've upgraded awx to 6.1. Extra pipe no longer appears. 
Extra variables are still splitted char by char

**Comment by kfattig** [comment] 2019-08-12 17:55
We're also seeing this.  I'm recording here since there was already a public issue, but we do have Tower support.  If you'd like me to file a vendor ticket LMK.

When creating the 'node' in the workflow, things are normal:
![image](https://user-images.githubusercontent.com/23063964/62885057-87a50f00-bcfd-11e9-8677-dcd368e423c3.png)

The confirmation screen is also normal:
![image](https://user-images.githubusercontent.com/23063964/62885428-86281680-bcfe-11e9-9d0d-20ce133e299d.png)

After hitting 'Save', it seems that the extra_variables are written incorrectly to the workflow_node's entry in the database:

``` sql 
select extra_data from main_workflowjobnode where id=31770;
```
Returns:
``` json
{"0": "j", "1": "t", "2": "_", "3": "v", "4": "a", "5": "r", "6": "1", "7": ":", "8": " ", "9": "j", "10": "t", "11": "_", "12": "v", "13": "a", "14": "l", "15": "1", "16": "\n", "17": "j", "18": "t", "19": "_", "20": "v", "21": "a", "22": "r", "23": "2", "24": ":", "25": " ", "26": "j", "27": "t", "28": "_", "29": "v", "30": "a", "31": "l", "32": "2"}
```

If you re-open the workflow visualizer, each character in extra_vars has become its own var:
![image](https://user-images.githubusercontent.com/23063964/62885504-ad7ee380-bcfe-11e9-98cc-46dec8ce9c6d.png)

They are then passed onto the job at exeuction:
```sql 
select extra_vars from main_job where unifiedjob_ptr_id=161395; 
```
Returns:

```json
{"jt_var1": "jt_val1", "jt_var2": "jt_val2", "0": "j", "1": "t", "2": "_", "3": "v", "4": "a", "5": "r", "6": "1", "7": ":", "8": " ", "9": "j", "10": "t", "11": "_", "12": "v", "13": "a", "14": "l", "15": "1", "16": "\n", "17": "j", "18": "t", "19": "_", "20": "v", "21": "a", "22": "r", "23": "2", "24": ":", "25": " ", "26": "j", "27": "t", "28": "_", "29": "v", "30": "a", "31": "l", "32": "2", "wf_var1": "wf_val1", "wf_var2": "wf_val2"}
```

![image](https://user-images.githubusercontent.com/23063964/62885589-ddc68200-bcfe-11e9-86a4-7ea382d7ccd5.png)

**Comment by mabashian** [comment] 2019-08-19 20:07
Pretty sure this is related to https://github.com/ansible/awx/pull/3669 https://github.com/ansible/awx/issues/3567 https://github.com/ansible/awx/pull/3359

**Comment by dsesami** [comment] 2019-08-29 14:24
Manipulated a workflow with both JSON and YAML formatted extra vars. Created and edited the workflow with different variables. There does not appear to be any strange output by the application anymore. :+1:

**Closed as completed by dsesami** 2019-08-29 14:24 UTC
Labels: type:bug, component:ui
