### ISSUE TITLE
Job output Host Details error

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx#12617] opened 2022-08-02 22:59 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When following job output and clicking on Host Details getting  exception.
Once page reloaded everything works fine.

### AWX version

21.4.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Web browser

Firefox

### Steps to reproduce

Follow job output and click on any field in log

### Expected results

Host Detail opened

### Actual results

Exception:

![Снимок экрана 2022-08-03 в 01 55 27](https://user-images.githubusercontent.com/51116816/182487655-f1d5660d-23e1-4970-9f59-dcb315d71f83.jpg)

Full log:

```
ale@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:3221315
oo@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:913504
Ks@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:965804
Al@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:953047
Tl@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:952975
El@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:952836
yl@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:949802
Yi/<@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:899296
6813/t.unstable_runWithPriority@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:995558
Vi@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:899073
Yi@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:899243
Ki@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:899176
Ne@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:970343
Jt@https://10.50.78.37/awx/static/js/main.f45a71ae.js:2:877796
```

### Additional information

AWX is running under subpath SERVER_IP/awx

**Comment by adpavlov** [comment] 2022-08-02 23:01
seems like similar to #12443

**Comment by akus062381** [comment] 2022-08-03 15:06
closing as a duplicate of https://github.com/ansible/awx/issues/12443

**Closed as completed by akus062381** 2022-08-03 15:06 UTC
Labels: type:bug, component:api, component:ui
