### ISSUE TITLE
No feedback when launching sync from details screen

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#9872] opened 2021-04-09 21:37 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. Create an inventory source, or a project
2. Go to the 'Details' view
3. See the 'Sync' button

![Screenshot from 2021-04-09 17-35-43](https://user-images.githubusercontent.com/5208768/114243196-2c0ba880-995a-11eb-93e6-859e4b4844a9.png)

Click it to start a sync.

There is no visible indicator that the sync was launched - no toast notification, no redirection to a view of the job, etc.

A user may click multiple times thinking nothing is happening, launching multiple syncs.

##### ENVIRONMENT
* AWX version: devel 12/10

**Comment by jakemcdermott** [comment] 2021-04-09 21:48
I'm thinking redirect would be the expected behavior here (given how our other views handle this).

> no toast notification, no redirection to a view of the job, etc.

But yeah any of these should be fine.

**Comment by unlikelyzero** [comment] 2021-04-11 22:45
@wenottingham @jakemcdermott is this a dupe of https://github.com/ansible/awx/issues/8837 and https://github.com/ansible/awx/issues/9013 (with some cross-over in https://github.com/ansible/awx/issues/2357 ) ?

**Comment by wenottingham** [comment] 2021-04-12 15:15
Yes.

**Comment by unlikelyzero** [comment] 2021-04-12 17:02
```
Also, the old UI would give me live updates about when the sync finished.
```
@wenottingham may be considered feature parity. Would we want to navigate the user to the run output?

**Comment by wenottingham** [comment] 2021-04-12 17:30
I would consider "feedback that the sync was launched" a feature parity item, even if we provide it somewhat differently than before.

**Comment by kdelee** [comment] 2021-04-13 17:03
I agree that this is confusing, and does not match the pattern of what happens when you press the "launch" button on job templates

**Closed as completed** 2021-05-03 13:28 UTC
Labels: type:bug, component:ui, type:feature
