### ISSUE TITLE
If a Job is Relaunched, Add The Origin Job to /api/v2/jobs/<JOB_ID>/

### ISSUE THREAD

**Issue by imareporter** [ansible/awx#6029] opened 2020-02-21 14:24 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Seeing as `/api/v2/jobs/<JOB_ID>/relaunch/` relaunches the job by creating another job with the same _user_ prompts, I think it may be a good idea to add a `/api/v2/jobs/<JOB_ID>/parent/` endpoint.

The `/api/v2/jobs/<JOB_ID>/parent/` endpoint would only be valid on jobs that were "relaunched" via the API or UI. This would be exceptionally useful, especially in cases where the user may question the environment that was relaunched and its origin (e.g. job auditing).

**EXAMPLE:**

ORIGIN JOB:

~~~
{
    "id": 1,
    "type": "job",
    "url": "/api/v2/jobs/1/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "labels": "/api/v2/jobs/1/labels/",
        "inventory": "/api/v2/inventories/1/",
        "project": "/api/v2/projects/6/",
        "extra_credentials": "/api/v2/jobs/1/extra_credentials/",
        "credentials": "/api/v2/jobs/1/credentials/",
        "unified_job_template": "/api/v2/job_templates/7/",
        "stdout": "/api/v2/jobs/1/stdout/",
        "job_events": "/api/v2/jobs/1/job_events/",
        "job_host_summaries": "/api/v2/jobs/1/job_host_summaries/",
        "activity_stream": "/api/v2/jobs/1/activity_stream/",
        "notifications": "/api/v2/jobs/1/notifications/",
        "create_schedule": "/api/v2/jobs/1/create_schedule/",
        "job_template": "/api/v2/job_templates/7/",
        "cancel": "/api/v2/jobs/1/cancel/",
        "relaunch": "/api/v2/jobs/1/relaunch/"
    }
~~~

RELAUNCH JOB:

~~~
{
    "id": 92,
    "type": "job",
    "url": "/api/v2/jobs/92/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "labels": "/api/v2/jobs/92/labels/",
        "inventory": "/api/v2/inventories/1/",
        "project": "/api/v2/projects/36/",
        "extra_credentials": "/api/v2/jobs/92/extra_credentials/",
        "credentials": "/api/v2/jobs/92/credentials/",
        "stdout": "/api/v2/jobs/92/stdout/",
        "job_events": "/api/v2/jobs/92/job_events/",
        "job_host_summaries": "/api/v2/jobs/92/job_host_summaries/",
        "activity_stream": "/api/v2/jobs/92/activity_stream/",
        "notifications": "/api/v2/jobs/92/notifications/",
        "create_schedule": "/api/v2/jobs/92/create_schedule/",
        "cancel": "/api/v2/jobs/92/cancel/",
        "parent": "/api/v2/jobs/3/",
        "relaunch": "/api/v2/jobs/92/relaunch/"
    }
~~~

**Comment by AlanCoding** [comment] 2020-02-21 20:23
https://github.com/ansible/awx/issues/2399

**Comment by ryanpetrello** [comment] 2020-02-21 21:25
Duplicate of https://github.com/ansible/awx/issues/2399

**Closed as completed by ryanpetrello** 2020-02-21 21:25 UTC
Labels: type:enhancement, component:api
