### ISSUE TITLE
AWX 18.0 Installation 

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9760] opened 2021-03-30 21:26 UTC
##### COMPONENT NAME

 - Installer

##### ENVIRONMENT
* AWX version: 18.0
* AWX install method: mnikube
* Ansible version:  2.9.18
* Operating System: Centos 7
* Web Browser: --

##### STEPS TO REPRODUCE
I have never used minikube.
Deployment hangs on "ImagePullBackOff" after following the installation guide.

##### ADDITIONAL INFORMATION

My server had AWX 16.0 on it, and I removed it completely in preparation for setting up 18.0.

Attached minikube log:

[log.txt](https://github.com/ansible/awx/files/6232284/log.txt)

Issue : 

<img width="561" alt="Capture" src="https://user-images.githubusercontent.com/8328746/113058811-49e94880-91b7-11eb-8632-a2a05ec14d51.PNG">

**Comment by shanemcd** [comment] 2021-03-31 13:12
@ILDev Can you provide the output of:

```
$ minikube kubectl describe pod awx-6f7bd969db-5ncjs
```

**Comment by ghost** [comment] 2021-03-31 13:28
@shanemcd , Thanks for responding.
Attaching the output :
[log.txt](https://github.com/ansible/awx/files/6236866/log.txt)

Additionally, I tried to deploy AWX on a new virtual machine, the installation worked out great, but minikube's IP address is inaccessible from other hosts (Makes sense) , How can I get access from other hosts to AWX's UI?

**Comment by shanemcd** [comment] 2021-03-31 14:00
@ILDev that looks like the logs for the operator itself. Did you attach the wrong thing?

**Comment by ghost** [comment] 2021-03-31 14:07
@shanemcd  , Sorry about that, attaching the right one:

[log .txt](https://github.com/ansible/awx/files/6237160/log.txt)

**Comment by shanemcd** [comment] 2021-03-31 15:04
Hmm... 

```  Warning  Failed          3h45m (x13 over 4h49m)   kubelet  Failed to pull image "quay.io/ansible/awx-ee": rpc error: code = Unknown desc = context canceled
  Warning  Failed          3h40m (x102 over 4h49m)  kubelet  Error: ImagePullBackOff
  Warning  Failed          3h29m (x15 over 4h49m)   kubelet  Error: ErrImagePull
```

Maybe it was a blip, either with Quay or Kubernetes itself? Can you try

```
$ minikube kubectl delete pod awx-6f7bd969db-5ncjs
```

and see if it sorts itself out?

**Comment by ghost** [comment] 2021-03-31 16:58
Still getting errors :
  **Warning  Failed     69s (x2 over 6m31s)  kubelet            Failed to pull image "quay.io/ansible/awx-ee": rpc error: code = Unknown desc = context canceled
  **Warning  Failed     69s (x2 over 6m31s)  kubelet            Error: ErrImagePull**
  **Warning  Failed     53s (x2 over 68s)    kubelet            Error: ImagePullBackOff****
  Normal   BackOff    53s (x2 over 68s)    kubelet            Back-off pulling image "quay.io/ansible/awx-ee"
  Normal   Pulling    40s (x3 over 11m)    kubelet            Pulling image "quay.io/ansible/awx-ee"


My opinion is that it's a VM-related issue, because it works fine on the new VM. 
Can you please tell me how to access the AWX Web UI from different hosts on the same vlan? Should I use a proxy?

**Comment by shanemcd** [comment] 2021-03-31 17:40
It might be a little tricky using Minikube but you could do it. I sometimes use SSH port forwarding too. 

But those solutions are rather hacky. I would recommend following the instructions at https://github.com/ansible/awx-operator and deploying the AWX Operator into a real Kubernetes / OpenShift cluster with proper ingress configured.

To continue debugging your current issue, maybe try running `$ minikube delete --purge` and trying from scratch. I am not able to reproduce this on my end.

**Comment by shanemcd** [comment] 2021-03-31 17:40
I am going to close this since it doesn't seem like a bug in AWX itself. If you need more help or just want to chat, feel free to join us on IRC or on our mailing list:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Closed as completed by shanemcd** 2021-03-31 17:40 UTC
Labels: component:installer
