### ISSUE TITLE
Jobs stuck Pending. DB Connection Error.

### ISSUE THREAD

**Issue by Posti90** [ansible/awx#11549] opened 2022-01-17 11:13 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

We are running an AWX installation on Kubernetes. Sometimes all jobs get stuck in the Pending state. We found out that at this time the database pod was stopped and restarted because the node was updated and rebooted. AWX does not survive the temporary interruption of the DB: "django.db.utils.InterfaceError: connection already closed". Furthermore, the "tower-processes:wsbroadcast" was in the "fatal" state. Even restarting the process did not make AWX run again.

To fix this, we set up a second DB to reduce downtime/failover time. But even with two DBs the problem was not solved. Although "tower-processes:wsbroadcast" now remains "running", all jobs remain in the "pending" state again. Our workaround is to redeploy the entire AWX pod.

How can we make AWX more stable for temporary DB interruptions? With a Kubernetes installation we always have to expect that a DB is not available for a few minutes.

AWX-TASK LOG:
```
2022-01-17 06:09:03,243 ERROR    [-] awx.conf.settings Database settings are not available, using defaults.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 82, in _ctit_db_wrapper
    yield
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 412, in __getattr__
    value = self._get_local(name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 334, in _get_local
    self._preload_cache()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 297, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

### AWX version

19.2.1

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.0.dev

### Operating system

CentOS Linux 8

### Web browser

Chrome

### Steps to reproduce

Disconnect the database connection for a few minutes.

### Expected results

AWX starts jobs after the database connection is restored.

### Actual results

- Maybe "tower-processes:wsbroadcast" in fatal state.
- AWX Jobs stuck Pending.
- AWX Logs:   
```
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

**Comment by shanemcd** [comment] 2022-01-31 17:11
Dupe of https://github.com/ansible/awx/issues/11391

**Closed as completed by shanemcd** 2022-01-31 17:11 UTC
Labels: needs_triage
