### ISSUE TITLE
Help text for "Paths to expose to isolated jobs" incomplete

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#6226] opened 2020-03-09 12:30 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The help text for "PATHS TO EXPOSE TO ISOLATED JOBS" not mention that lines must be comma-separated.

##### ENVIRONMENT
*Every AWX versions

##### STEPS TO REPRODUCE

Click on the interrogation icon of "PATHS TO EXPOSE TO ISOLATED JOBS"

##### EXPECTED RESULTS
Text should be:

> Whitelist of paths that would otherwise be hidden to expose to isolated jobs. 
Enter one comma-separated path per line.

##### ACTUAL RESULTS

Text actually saiys

> Whitelist of paths that would otherwise be hidden to expose to isolated jobs. Enter one path per line.

**Comment by ryanpetrello** [comment] 2020-03-13 18:27
This confused me a bit, because it's not *actually* about "isolated jobs" (the feature where we execute jobs over SSH).  It means "paths exposed to *bwrap*".  That said, I don't really see what's wrong here.

In the 3.7 UI, it reads:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/214912/76649083-4f390e00-6536-11ea-8984-fd5cd597060d.png">

If you save, it sends this in the payload, which is correct.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/214912/76649148-637d0b00-6536-11ea-9584-7e010be4cfbe.png">

If you use commas in the text field, it sends the same payload:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/214912/76649327-ce2e4680-6536-11ea-8703-9c86719d1c9c.png">

Either way, both seem fine to me, and they look like they save the value properly.  @mabashian or @jakemcdermott either of you have anything to add?

**Comment by kdelee** [comment] 2020-03-16 17:13
@ryanpetrello @jakemcdermott are y'all saying this is a "NOTABUG"

**Comment by ryanpetrello** [comment] 2020-03-16 17:38
That's my stance.  If somebody can come up with an explanation or reproducer of what I've got wrong, though, feel free to elaborate (cc @zaskan).

**Comment by zaskan** [comment] 2020-03-17 15:25
Hi guys. Thanks so much for your help. I will try a call with the customer because I want to check it with him. I'll keep you updated.

**Comment by dsesami** [comment] 2020-03-17 17:55
based on the comments above, unassigning + moving to needs_info @ryanpetrello

**Comment by zaskan** [comment] 2020-03-18 15:30
Hi @dsesami @ryanpetrello. I just was in a call with the customer and I'm able to reproduce the problem. 

As I can see, if you don't add the commas, Tower add them but put all the paths in the same line in the field. You need to refresh the browser to see it after save the changes.

**Comment by ryanpetrello** [comment] 2020-03-19 03:03
@zaskan,

Yea, based on https://github.com/ansible/awx/issues/6226#issuecomment-598856900, I'm not seeing an actual issue here, so I'm inclined to close this as `notabug`.  If you've got some evidence of a bug the customer is encountering, let us know and we can try to reproduce.

**Closed as completed by ryanpetrello** 2020-03-19 03:03 UTC
Labels: type:bug, component:api, component:ui
