### ISSUE TITLE
Get Kubernetes API version fails on oc 3.11, 'unknown shorthand flag'

### ISSUE THREAD

**Issue by src386** [ansible/awx#5388] opened 2019-11-25 11:58 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Installation on Openshift fails on the "Get Kubernetes API version".

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: openshift
* Ansible version:  2.8.3
* Operating System: Debian Buster
* oc version: v3.11.0+0cbc58b

##### STEPS TO REPRODUCE

- oc v3.11.0+0cbc58b
- Run the installer

##### EXPECTED RESULTS

- Installation success ?

##### ACTUAL RESULTS

```
TASK [kubernetes : Get Kubernetes API version] ****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "--config=/tmp/awx-config/.kube/config", "version", "-o", "json"], "delta": "0:00:00.281032", "end": "2019-11-25 10:57:37.835706", "msg": "non-zero return code", "rc": 1, "start": "2019-11-25 10:57:37.554674", "stderr": "Error: unknown shorthand flag: 'o' in -o\n\n\nUsage:\n  oc version [flags]\n\nUse \"oc options\" for a list of global command-line options (applies to all commands).", "stderr_lines": ["Error: unknown shorthand flag: 'o' in -o", "", "", "Usage:", "  oc version [flags]", "", "Use \"oc options\" for a list of global command-line options (applies to all commands)."], "stdout": "", "stdout_lines": []}

PLAY RECAP ****************************************************************************************************************************************************************
localhost                  : ok=16   changed=4    unreachable=0    failed=1    skipped=74   rescued=0    ignored=2 
```

##### ADDITIONAL INFORMATION

Executing the command manually:

```
$ oc version -o json
Error: unknown shorthand flag: 'o' in -o


Usage:
  oc version [flags]

Use "oc options" for a list of global command-line options (applies to all commands).
```

The output json is mentionned in [oc 3.9 documentation](https://docs.openshift.com/container-platform/3.9/cli_reference/basic_cli_operations.html#version) but not in [3.11](https://docs.openshift.com/container-platform/3.11/cli_reference/basic_cli_operations.html).

**Comment by ryanpetrello** [comment] 2019-11-26 19:53
@src386 does changing it to `--output` work?

**Comment by src386** [comment] 2019-11-28 17:27
@ryanpetrello it does not:

```
oc version --output json
Error: unknown flag: --output


Usage:
  oc version [flags]

Use "oc options" for a list of global command-line options (applies to all commands).
```

As a workarround, I have edited `installer/roles/kubernetes/tasks/main.yml` and commented these steps:

```
#- name: Get Kubernetes API version
#  command: |
#    {{ kubectl_or_oc }} version -o json
#  register: kube_version

#- name: Extract server version from command output
#  set_fact:
#    kube_api_version: "{{ (kube_version.stdout | from_json).serverVersion.gitVersion[1:] }}"
```

Then I ran the playbook with an additional argument to manually specify the kubernetes version : `-e "kube_api_version=1.11"`

**Comment by megabreit** [comment] 2019-11-29 13:34
The problem is that kubectl can deal with "version -o json" but oc can't... at least in Openshift 3.11.
My hotfix is to hardcode the variable:
```
- name: Get Kubernetes API version
  command: |
    kubectl version -o json
  register: kube_version
```
Another hotfix would be to use oc 4.x (tested with 4.2.9)

**Comment by shanemcd** [comment] 2019-11-29 15:32
Oops. Thank you for reporting this. I'll work on getting a fix in place on Monday.

**Comment by shanemcd** [comment] 2019-12-02 17:52
Resolved by #5422.

**Closed as completed by shanemcd** 2019-12-02 17:52 UTC
Labels: type:bug

**Comment by megabreit** [comment] 2019-12-12 16:18
In my Openshift 3.11 environment this fails with the following error:
```
TASK [kubernetes : Find cluster for current context] ********************************************************************************************************************
task path: /home/XXXX/src/awx/installer/roles/kubernetes/tasks/main.yml:203
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 592, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 268, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 435, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 584, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 539, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 804, in do_template
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 740, in do_list
    return list(value)
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 931, in _select_or_reject
    if modfunc(func(transfunc(item))):
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 925, in <lambda>
    name, item, args, kwargs)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 438, in call_test
    raise TemplateRuntimeError('no test named %r' % name)
TemplateRuntimeError: no test named 'equalto'

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```
$ ansible --version
ansible 2.8.7
  config file = /home/XXXX/.ansible.cfg
  configured module search path = [u'/home/XXXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

RHEL 7.7 with current patchlevel.

**Comment by wenottingham** [comment] 2019-12-12 16:21
```  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 438, in call_test
    raise TemplateRuntimeError('no test named %r' % name)
TemplateRuntimeError: no test named 'equalto'
```
Your content is using jinja filters not in the system jinja; this is not an AWX bug.

**Comment by megabreit** [comment] 2019-12-12 16:32
Technically you are right. RHEL 7 is delivering a quite old Jinja 2 version:
python-jinja2-2.7.2-4.el7.noarch
which is not easily updated and creates a non-supported environment.
This change means that you exclude RHEL 7 users from installing AWX in any version of Openshift.
The actual bug (before the fix) just excluded Openshift 3.11 users from installing AWX.

**Comment by wenottingham** [comment] 2019-12-12 17:42
Oh, sorry, I missed that that was the installer. Can you file that as a new bug?

**Comment by megabreit** [comment] 2019-12-13 16:46
Done. #5501

**Comment by smuth4** [comment] 2019-12-24 03:54
Unfortunately this fix breaks the installation for my vanilla k8s, since kubectl handles loading the user token to authenticate with the cluster's API server. Does oc implement `get --raw`? That'd probably be the cleanest compromise, although there are other options if need be.
