### ISSUE TITLE
AWX 19+: Schedule datepicker (calendar) strange behaviour: one day before

### ISSUE THREAD

**Issue by kladiv** [ansible/awx#11978] opened 2022-03-30 15:49 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello,
during creation/edit of a Job Schedule, we select a specific date/time for Run Once using the datepicker calendar and, when saving, the schedulation is added "one day before"

### AWX version

19.4.0, 20.0.1

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11

### Operating system

CentOS 8 + k3s

### Web browser

Firefox, Chrome

### Steps to reproduce

- Create/Edit a Schedule of a Job
- Select a Date and Time using datepicker (first time you click in the datepicker just choose a wrong date)

![awx-schedule-img1](https://user-images.githubusercontent.com/1803926/160875825-952ab1d5-5d5c-4f70-a192-31ceacaef495.png)

![awx-schedule-img2](https://user-images.githubusercontent.com/1803926/160875907-dfe4a09c-2d21-4e4d-83c4-980c7e2d692e.png)

- Select a Date and Time using datepicker again (to ensure the date is correct)

![awx-schedule-img3](https://user-images.githubusercontent.com/1803926/160876149-63d7f973-1902-4862-93ac-25c6ab97850c.png)

- Save
- Check the First Run / Next Run values, that are one day before

![awx-schedule-img4](https://user-images.githubusercontent.com/1803926/160876211-fa4e2142-f520-4ff1-be02-bf1f8a8bb84b.png)

### Expected results

First Run / Next Run values of the job Schedule should match what user filled in the Edit/Add page of the schedule.

### Actual results

First Run / Next Run values of the job Schedule are "one day before" the date user filled in the Edit/Add page of the schedule

**Comment by fosterseth** [comment] 2022-04-01 17:35
Is the timezone of your local machine different from the one you are selecting (Europe/Rome)?

The detail page after saving may be converting the Rome time to your local time.

**Comment by kladiv** [comment] 2022-04-01 19:48
Hi @fosterseth,
no it's not different.

Btw when a user select a Schedule date/time and a timezone, that selections should persist (and Detail page shows both timezone and date/time)

**Comment by ffirg** [comment] 2022-04-12 12:31
Affects AAP 2.1.1 as well. placed into Needs Refinement for further triage.

**Comment by mabashian** [comment] 2022-04-28 14:46
@kladiv any idea if this was functioning correctly prior to v19?

**Comment by kladiv** [comment] 2022-04-28 18:34
Hi @mabashian i can't remember that.
Lots of time passed and i've no old installations anymore

**Comment by d-rupp** [comment] 2022-05-03 06:26
I can confirm this issue with our installation. All users that try to schedule a job have this issue.

It was working correctly in 10.0.0

**Comment by akus062381** [comment] 2022-05-05 13:19
Fix has been merged and will be included in the upcoming release.

**Comment by kialam** [comment] 2022-05-05 16:17
@akus062381 this is a different issue with the date picker selection showing a 1 day before date when you interact with it. Re-opening as the PR is still open.

**Comment by akus062381** [comment] 2022-05-05 16:54
@kialam I was testing your PR last night and looked for this bug and could not reproduce it. Are you sure that your fix doesn't also fix this problem?

**Comment by InnocentK** [comment] 2022-05-05 17:34
@akus062381 I'm currently investigating this bug and will verify if the 1 day bug is still present and reproducible. I will also verify the changes in [#12163 ](https://github.com/ansible/awx/pull/12163)

**Comment by kialam** [comment] 2022-05-05 17:43
@akus062381 yes, this bug is still happening on devel.

**Comment by InnocentK** [comment] 2022-05-05 20:47
With https://github.com/ansible/awx/pull/12163 merged, this is now resolved

**Closed as completed by InnocentK** 2022-05-05 20:47 UTC
Labels: type:bug, component:ui
