### ISSUE TITLE
No more than 4 jobs running in the same time despite an important RAM addition

### ISSUE THREAD

**Issue by icsm2017** [ansible/awx#1492] opened 2018-03-09 08:45 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
No more than 4 jobs running in the same time despite an important RAM addition.

##### ENVIRONMENT
* AWX version: 1.0.4.48
* AWX install method: docker on linux
* Ansible version: 2.4.3
* Operating System: Red Hat 7.4
* Web Browser: chrome

##### STEPS TO REPRODUCE
Upgrade RAM from 4 to 25Gb and CPU from 2 to 4. Launch multiple job from UI (more 4 jobs).

##### EXPECTED RESULTS
AWX should launch more than 4 jobs in the same time.

##### ACTUAL RESULTS
When I try to run many jobs from same (or different) jobs templates and targeting same (or different) remote hosts, I cannot get more than 4 jobs running in the same time, the others stay in the waiting queue.

##### ADDITIONAL INFORMATION
![awx](https://user-images.githubusercontent.com/32674944/37198127-84db3bac-237d-11e8-94ee-415964b70895.PNG)

I tested the same template (with same project, playbook, inventory) on the trial version of tower and I actually went ~20 jobs simultaneously on the same server configuration.

**Comment by matburt** [comment] 2018-03-09 14:23
can you show me the output of `/api/v2/instancees`... specifically I'm looking for what  the instance capacities and capabilities are... especially *while* jobs are running.

**Comment by icsm2017** [comment] 2018-03-09 14:47
With 9 jobs launch (4 running, 5 pending), we have the following result : 
```
            "uuid": "00000000-0000-0000-0000-000000000000",
            "hostname": "awx",
            "created": "2018-03-06T08:46:33.590584Z",
            "modified": "2018-03-09T14:44:09.596348Z",
            "capacity_adjustment": "1.00",
            "version": "1.0.4.48",
            "capacity": 218,
            "consumed_capacity": 8,
            "percent_capacity_remaining": 96.33,
            "jobs_running": 4,
            "cpu": 4,
            "memory": 25095229440,
            "cpu_capacity": 16,
            "mem_capacity": 218,
            "enabled": true
```

**Comment by simfarm** [comment] 2018-03-09 20:34
@matburt I'm seeing this too on Tower. I reproduced by launching a JT with `allow_simultaneous` fifteen times.

**Comment by simfarm** [comment] 2018-03-09 20:37
We have excess IG capacity:
```
        {
            "id": 7,
            "type": "instance_group",
            "url": "/api/v2/instance_groups/7/",
            "related": {
                "jobs": "/api/v2/instance_groups/7/jobs/",
                "instances": "/api/v2/instance_groups/7/instances/"
            },
            "name": "Instance Group - BuyResident餄",
            "created": "2018-03-09T20:28:53.847976Z",
            "modified": "2018-03-09T20:28:54.116609Z",
            "capacity": 218,
            "committed_capacity": 4,
            "consumed_capacity": 8,
            "percent_capacity_remaining": 96.33,
            "jobs_running": 7,
            "instances": 1,
            "controller": null,
            "policy_instance_percentage": 0,
            "policy_instance_minimum": 0,
            "policy_instance_list": [
                "tower-1-pqw5v"
            ]
        },
```

**Comment by simfarm** [comment] 2018-03-09 20:42
Let me take a deeper dive.

**Comment by simfarm** [comment] 2018-03-09 21:20
@matburt This is what I've seen.
* Get Tower on OpenShift. Get five Tower pods.
* Create new instance group. Give this IG one of your Tower pods.
* Create JT with `allow_simultaneous` that sources this IG.
* Launch JT twenty times in rapid succession.

If you do this....
* I don't see more than four running jobs at any given point in time.
* Instance capacity isn't an issue (in my test case, percentage capacity remaining never went lower than 95%).
* Eventually the instance, disappears from Tower and jobs are slain.
* Jobs fail with:
```
Traceback (most recent call last):
File "/lib/python2.7/site-packages/awx/main/tasks.py", line 888, in run
File "/lib/python2.7/site-packages/awx/main/tasks.py", line 1335, in pre_run_hook
File "/lib/python2.7/site-packages/awx/main/models/projects.py", line 399, in create_project_update
File "/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 379, in create_unified_job
File "/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 819, in save
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/polymorphic/models.py", line 83, in save
return super(PolymorphicModel, self).save(*args, **kwargs)
File "/lib/python2.7/site-packages/awx/main/models/base.py", line 198, in save
File "/lib/python2.7/site-packages/awx/main/models/base.py", line 269, in save
File "/lib/python2.7/site-packages/awx/main/models/base.py", line 164, in save
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
force_update=force_update, update_fields=update_fields)
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
update_fields=update_fields, raw=raw, using=using,
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
for receiver in self._live_receivers(sender)
File "/lib/python2.7/site-packages/awx/main/models/ha.py", line 227, in on_job_create
File "/lib/python2.7/site-packages/awx/main/managers.py", line 87, in me
RuntimeError: No instance found with the current cluster host id
```

**Comment by icsm2017** [comment] 2018-03-12 15:28
@matburt So, It looks like it's a bug (critical for us). Is there a workaround in development ?

**Comment by matburt** [comment] 2018-03-13 17:50
closing since #1534 merged

**Closed as completed by matburt** 2018-03-13 17:50 UTC
Labels: type:bug, component:api
