### ISSUE TITLE
Can you provide the awx offline installation method Or provide an RPM installation

### ISSUE THREAD

**Issue by thisID** [ansible/awx#7332] opened 2020-06-12 09:16 UTC
##### ISSUE TYPE
 - Feature Idea

Can you provide the awx offline installation method Or provide an RPM installation.
I tried for a long time without success,look forward to your reply.

mud in your eye

**Comment by ryanpetrello** [comment] 2020-06-13 17:08
Duplicate of https://github.com/ansible/awx/issues/419

**Closed as completed by ryanpetrello** 2020-06-13 17:08 UTC
