### ISSUE TITLE
Deadlock on single inventory update with multiple sources

### ISSUE THREAD

**Issue by b0urn3** [ansible/awx#2922] opened 2018-12-13 13:51 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Having an AWS dynamic inventory configured with

  - multiple inventory sources pointing to distinct AWS accounts
  - set `overwrite: true`
  - set `overwrite_vars: true`
  - set `update_on_launch: null`

Can result when updating all sources at once in a deadlock. For example when the update of all inventory source is triggered via `launch_type: callback`.

```
django.db.utils.OperationalError: deadlock detected
DETAIL:  Process 19431 waits for ShareLock on transaction 142021; blocked by process 19438.
Process 19438 waits for ShareLock on transaction 142022; blocked by process 19431.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (0,20) in relation "main_group_parents"
```
##### ENVIRONMENT
* AWX version: 2.x
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

Configure AWS dynamic inventory with

  - multiple inventory sources pointing to distinct AWS accounts
  - set `overwrite: true`
  - set `overwrite_vars: true`
  - set `update_on_launch: null`

##### EXPECTED RESULTS

No deadlocks and successful updates from all inventory sources.

##### ACTUAL RESULTS

Deadlock during update of random inventory source in such inventory.

**Comment by ryanpetrello** [comment] 2018-12-14 18:27
@b0urn3,

Could you share the exact version of awx you're encountering this problem with?

**Comment by b0urn3** [comment] 2018-12-16 19:07
@ryanpetrello this issue is happening on Ansible Tower 3.3.2.

**Comment by AlanCoding** [comment] 2019-02-18 21:06
Should be resolved by https://github.com/ansible/awx/pull/3206

**Comment by benapetr** [comment] 2019-02-22 09:59
Same issue with 3.0.1:

```

1
    1.961 INFO     Updating inventory 4: everything_managed
2
    1.973 INFO     Reading Ansible inventory source: /tmp/awx_8225_ekqpx6qx/tmp8pgxqn5l
3
    1.975 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
4
    1.975 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
5
    1.975 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
6
    4.021 ERROR     [ERROR]:   % Total    % Received % Xferd  Average Speed   Time    Time
7
    4.021 ERROR    Time  Current                                  Dload  Upload   Total   Spent
8
    4.021 ERROR    Left  Speed    0     0    0     0    0     0      0      0 --:--:-- --:--:--
9
    4.021 ERROR    --:--:--     0 100 14251    0 14251    0     0  15480      0 --:--:-- --:--:--
10
    4.021 ERROR    --:--:-- 15473 100  137k    0  137k    0     0   148k      0 --:--:-- --:--:--
11
    4.021 ERROR    --:--:--  148k
12
    4.021 ERROR    
13
    4.025 INFO     Processing JSON output...
14
    4.061 INFO     Loaded 317 groups, 413 hosts
15
Traceback (most recent call last):
16
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
17
    return self.cursor.execute(sql, params)
18
psycopg2.extensions.TransactionRollbackError: deadlock detected
19
DETAIL:  Process 12100 waits for ShareLock on transaction 59334670; blocked by process 12089.
20
Process 12089 waits for ShareLock on transaction 59334659; blocked by process 12100.
21
HINT:  See server log for query details.
22
CONTEXT:  while deleting tuple (17,139) in relation "main_group_hosts"
25
The above exception was the direct cause of the following exception:
27
Traceback (most recent call last):
28
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
29
    load_entry_point('awx==3.0.1.0', 'console_scripts', 'awx-manage')()
30
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 140, in manage
31
    execute_from_command_line(sys.argv)
32
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
33
    utility.execute()
34
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
35
    self.fetch_command(subcommand).run_from_argv(self.argv)
36
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
37
    self.execute(*args, **cmd_options)
38
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
39
    output = self.handle(*args, **options)
40
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1049, in handle
41
    raise exc
42
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 994, in handle
43
    self.load_into_database()
44
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 845, in load_into_database
45
    self._delete_group_children_and_hosts()
46
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 553, in _delete_group_children_and_hosts
47
    db_group.hosts.remove(db_host)
48
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 950, in remove
49
    self._remove_items(self.source_field_name, self.target_field_name, *objs)
50
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 1146, in _remove_items
51
    self.through._default_manager.using(db).filter(filters).delete()
52
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 620, in delete
53
    deleted, _rows_count = collector.delete()
54
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/deletion.py", line 302, in delete
55
    count = query.delete_batch(pk_list, self.using)
56
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/subqueries.py", line 45, in delete_batch
57
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
58
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/subqueries.py", line 28, in do_query
59
    cursor = self.get_compiler(using).execute_sql(CURSOR)
60
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
61
    raise original_exception
62
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
63
    cursor.execute(sql, params)
64
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
65
    return self.cursor.execute(sql, params)
66
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
67
    six.reraise(dj_exc_type, dj_exc_value, traceback)
68
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/six.py", line 685, in reraise
69
    raise value.with_traceback(tb)
70
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
71
    return self.cursor.execute(sql, params)
72
django.db.utils.OperationalError: deadlock detected
73
DETAIL:  Process 12100 waits for ShareLock on transaction 59334670; blocked by process 12089.
74
Process 12089 waits for ShareLock on transaction 59334659; blocked by process 12100.
75
HINT:  See server log for query details.
76
CONTEXT:  while deleting tuple (17,139) in relation "main_group_hosts"
```

**Comment by AlanCoding** [comment] 2019-02-22 13:10
This is the first `TransactionRollbackError` error I've seen. Yes, that is related, due to the volume of host-group membership modifications, but 3.0.1 doesn't have the patch either. It also looks like there might have been some stderr output.

**Comment by kdelee** [comment] 2019-04-23 17:15
Confirmed fixes for deadlocks on hosts and groups, closing.

**Closed as completed by kdelee** 2019-04-23 17:15 UTC
Labels: type:bug, component:api
