### ISSUE TITLE
AWX 7.0.0 K8S roles cannot be found during template execution

### ISSUE THREAD

**Issue by philippwiesner** [ansible/awx#4761] opened 2019-09-17 10:39 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Running a template fails, with error message the role was not found:

`ERROR! the role 'generic_loadbalancer' was not found in /tmp/awx_34_fl2ueiip/project/playbooks/roles:/tmp/awx_34_fl2ueiip/requirements_roles:/tmp/awx_34_fl2ueiip/project/playbooks
The error appears to be in '/tmp/awx_34_fl2ueiip/project/playbooks/generic_loadbalancer.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  roles:
    - { role: generic_loadbalancer }
      ^ here
`

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: kubernetes
* Ansible version:  2.8.4, 2.7.16
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Deploy to Kubernetes using AWX 7.0.0 Images
2. Create new Project, Inventory and Template
3. Run Job Template

##### EXPECTED RESULTS

Playbook is successfully executed

##### ACTUAL RESULTS

Playbook cannot be executed as no roles can be found in the paths. However executing the code for project copy manually is working fine inside the pod. 
Tracking the temporary directories with a watch inside the pod shows that the roles are actually copied to /tmp/awx_*/project/roles, but removed shortly afterwards.

**Comment by sumkincpp** [comment] 2019-09-17 17:04
Same here with AWX 7.0.0

**Comment by sumkincpp** [comment] 2019-09-17 17:26
Related to #4675

**Comment by awithrow9** [comment] 2019-09-20 17:29
@AlanCoding can you take a look at this one?

**Comment by AlanCoding** [comment] 2019-09-20 17:56
What means are you using to install roles? I can't find this role on public Ansible Galaxy. Is it checked into your source control, and if so, where? Do you have anything in your project's root-level `ansible.cfg` that is relevant?

**Comment by srinathman** [comment] 2019-09-24 14:38
I believe I'm having a similar issue after updating to 7.0.0.
I have a "roles/requirements.yml" file with a few roles defined (some internal custom roles and other from ansible-galaxy). But when I try to run a template or a project update I get this:

```
TASK [debug] *******************************************************************
ok: [localhost,] => {
    "msg": false   *** <-- this is the value of roles_enabled I added this in project_update.yml
}
TASK [detect requirements.yml] *************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [detect collections/requirements.yml] *************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [fetch galaxy collections from collections/requirements.yml] **************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
```
I seems that "roles_enabled" always resolves to False even when set to True in the UI/DB:

```
awx=# select key,value from conf_setting where key like '%ENABLED' ;
           key           | value 
-------------------------+-------
 AUTH_BASIC_ENABLED      | true
 AWX_ROLES_ENABLED       | true
 AWX_COLLECTIONS_ENABLED | true
(3 rows)

```

**Comment by AlanCoding** [comment] 2019-09-26 16:21
^ when you run a job, it should still be able to access the role. Can you confirm if it does / does not?

**Comment by srinathman** [comment] 2019-09-26 16:41
It does not, it fails when trying to process the roles. 

* For now I reverted back to 6.1.0.

**Comment by AlanCoding** [comment] 2019-09-26 17:50
Could you help give me any more information about what is different between your case and the following test case?

 - playbook: https://github.com/ansible/test-playbooks/blob/with_requirements/use_debug_role.yml
 - requirements: https://github.com/ansible/test-playbooks/blob/with_collection_requirements/collections/requirements.yml

The function is that the role runs before a confirmation task, and then the confirmation task will fail if something very specific to the function of that role was not done. My reading of the information here is that I should be able to get it to fail on `role: grog.debug-variable` because the role is not available, but I cannot do that, and I'm looking for any other information that might help get me there.

**Comment by srinathman** [comment] 2019-09-26 18:29
It seems that the main difference is that I have `roles/requirements.yml` and not `collections/requirements.yml`

**Comment by AlanCoding** [comment] 2019-09-26 18:38
Oh I'm so sorry, I linked the wrong thing.

 - playbook: https://github.com/ansible/test-playbooks/blob/with_requirements/use_debug_role.yml
 - requirements: https://github.com/ansible/test-playbooks/blob/with_requirements/roles/requirements.yml

**Comment by srinathman** [comment] 2019-09-27 20:00
I put 7.0.0 again in a test env. and it works with the test playbook you provided.
I'll retry it later on this test env. with our playbooks to see what's going on.

**Comment by darrenjones24** [comment] 2019-10-03 07:45
I'm having the same issue with 7.0.0, which was working in 6.1.0
I'm not sure how helpful this is but, I found that editing the playbook so that it references the role relative to the play is working. Whereas a reference relative to the roles directory is not.
 
For example if the playbook says:  - system_config/local_sysadmin it's not working but it does when I put: - ../../roles/system_config/local_sysadmin

I removed the ansible.cfg roles_path

**Comment by AlanCoding** [comment] 2019-10-04 20:42
With information from the last comment, I'm closing as duplicate of https://github.com/ansible/awx/issues/4675, which has a proposed patch.

**Closed as completed by AlanCoding** 2019-10-04 20:42 UTC
Labels: type:bug, component:api
