### ISSUE TITLE
Permissions notifications messages don't wrap

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4867] opened 2019-10-01 15:47 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Notifications for permissions management don't wrap, so they run off the screen:
![Screenshot from 2019-10-01 11-42-28](https://user-images.githubusercontent.com/19942822/65978051-020e2780-e441-11e9-9762-2e4269c911ae.png)

Note that if a similar dialog appears elsewhere, it'll need the fix as well. 

##### ENVIRONMENT
* AWX version: latest
* Operating System: Fedora 30
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Create an org
2. Make a normal user an admin of that org
3. Make a team as a member of the same org
4. Logged in as the user from step 2, visit the teams tab and view the team

##### EXPECTED RESULTS
A notification about getting permissions from the admin, correctly wrapped at smaller screen sizes. 

##### ACTUAL RESULTS
No wrapping.

**Comment by humzam96** [comment] 2019-11-30 22:21
I wasn't able to see the expected results- logging in as the second user shows the team since that user is an admin of the org. Are there other steps to reproduce the results?

**Comment by dsesami** [comment] 2019-12-02 15:10
@humzam96 there is a `teams.forms.js` which has a logic line that says:

```ngShow: 'isOrgAdmin && !canEdit'```

That triggers this dialog. I think that there is something wonky there with permissions, maybe they might be an org admin but not a member of that team? @mabashian might have an idea?

**Comment by mabashian** [comment] 2022-04-04 19:23
We don't show this banner anymore and the logged in user seems to have the appropriate permissions to edit roles on the team so I'm gonna close this.

**Closed as completed by mabashian** 2022-04-04 19:23 UTC
Labels: component:ui, good first issue, qe:visual
