### ISSUE TITLE
job output screen - clearing search results does not render expected results

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11935] opened 2022-03-22 16:52 UTC
Related to https://github.com/ansible/awx/pull/11788 and https://github.com/ansible/awx/issues/10281

after the user performs a search in the job output screen, it does not refresh properly unless the user clicks the refresh button after clearing the filter(s).

![image](https://user-images.githubusercontent.com/63685497/159533052-6e2ab394-9c7f-45d4-bcb8-5777e6abeb54.png)

To recreate:

Access the Demo Inventory. In addition to localhost, add two more hosts to this inventory.

Create a new job template and use this inventory, and choose the playbook
image

Run the job template. On the output screen, you will notice that 1 host was ok and 2 were unreachable.

In the search, choose Event, and then in the Filter by Event dropdown menu, select Host Ok, and then Host Unreachable. The filters work correctly.

Now go back to the Filter by Event dropdown and unselect Host Ok and Host Unreachable. You will notice that the output screen does not properly show the output unless you click the refresh button.

**Comment by AlexSCorey** [comment] 2022-03-22 18:36
![output](https://user-images.githubusercontent.com/39280967/159551878-380bab45-2a53-4d57-9fa6-bfa572e91d75.gif)

**Comment by AlexSCorey** [comment] 2022-03-28 13:48
@keithjgrant I assigned you to this because you are doing some refactoring in this area.  Feel free to remove yourself.

**Comment by keithjgrant** [comment] 2022-05-05 16:53
@akus062381 it looks like this has been fixed along with the recent work in job output. can you re-test in devel?

**Comment by InnocentK** [comment] 2022-05-06 20:39
@keithjgrant @akus062381 Just finished testing and I can confirm this is no longer appearing in devel so closing

**Closed as completed by InnocentK** 2022-05-06 20:39 UTC
Labels: type:bug, component:ui
