### ISSUE TITLE
AWX CLI not giving correct rc when job fails with --monitor set

### ISSUE THREAD

**Issue by davidban77** [ansible/awx#6079] opened 2020-02-26 12:15 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hello!

I am testing the awx cli on my CI environment to launch jobs on AWX. First time using **awx cli** so I might be missing something but I was under the impression that if a launched a `job_template` with `--monitor` and this one failed, it was supposed to give an `rc != 0`, so it correctly shows it on the CI interface.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX CLI version: 3.6.2
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Centos 7
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

```shell
$ awx job_template launch "[F5] Onboarding" --monitor -f human
------Starting Standard Out Stream------

PLAY [F5 Onboarding tasks] *****************************************************

TASK [get creds from vault] ****************************************************
fatal: [lab-f5]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Please pip install hvac to use the hashi_vault lookup module."}

PLAY RECAP *********************************************************************
lab-f5       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

------End of Standard Out Stream--------

id  name
=== ===============
374 [F5] Onboarding
```

##### EXPECTED RESULTS

The return code to be different than 0, so is correctly marked as a failed step on the pipeline.

##### ACTUAL RESULTS

Return code equal to 0

```shell
$ echo $?
0
```

**Comment by ryanpetrello** [comment] 2020-02-26 12:33
duplicate of https://github.com/ansible/awx/issues/5920

**Closed as completed by ryanpetrello** 2020-02-26 12:33 UTC
Labels: type:bug
