### ISSUE TITLE
admin user being associated/updated with OAUTH social auth providers (Azure AD, Github)

### ISSUE THREAD

**Issue by lucas-benedito** [ansible/awx#8154] opened 2020-09-16 09:48 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Bug found where if you connect with admin user in rest api and then proceed with Azure AD login in Ansible Tower the admin user in Ansible Tower is updated with Azure AD data after login and the admin user has the tag Social
The user in question would be a non administrative user from Azure AD that after login became the admin user and had full access to tower. This only happened when using Azure AD method but not with SAML method for the same Azure AD.

##### ENVIRONMENT
* Tested in AWX version: > 3.6.5

##### STEPS TO REPRODUCE
Fresh install of Ansible Tower 3.6.5 or above. 
Configure Azure AD with **Azure AD OAUTH2 KEY** and **Azure AD OAUTH2 SECRET**
Login with admin user in Rest API in one tab
Login with the Azure AD in another tab
Check the logged user and user details in Users tab

##### EXPECTED RESULTS
New user created in tower matching Azure AD settings

##### ACTUAL RESULTS
Admin user updated with Azure AD user data and login performed as the admin user

##### ADDITIONAL INFORMATION
Tests performed in different OS versions and Ansible Tower versions 3.6.5 and 3.7.2, both had the same issue.
![Screenshot from 2020-09-16 11-47-58](https://user-images.githubusercontent.com/55454581/93321500-83a5c380-f812-11ea-9999-7f931c5ab1f1.png)

![Screenshot from 2020-09-16 11-46-23](https://user-images.githubusercontent.com/55454581/93321404-67a22200-f812-11ea-9f2e-d8ade980e480.png)

**Comment by ghjm** [comment] 2020-09-23 17:38
I cannot reproduce this.  If I log in to the API in one tab, a new tag gives me a dashboard view with the logged in API user.  If I then navigate to the login page and perform an Azure AD login, it proceeds normally (whether creating a new Tower social account or reusing an existing one).  If I then go back to the API page and click refresh, it shows the newly-logged-in AD user.  I was not able to produce the behavior described.

@lucas-benedito can you give more details on how to reproduce this, like down to exact "click on this" steps?

**Comment by lucas-benedito** [comment] 2020-09-24 13:52
@ghjm sure, I've tested with Ansible Tower 3.6.5 and 3.7.2
- fresh Ansible Tower Installation
- configure Azure AD with **Azure AD OAUTH2 KEY** and **Azure AD OAUTH2 SECRET** ( Azure AD authentication tab ) without any other configuration
- Logout from Ansible Tower
- Open two login tabs being one from https://YOUR-TOWER-ADDRESS/api/login and https://YOUR-TOWER-ADDRESS
- Login with the user **admin** on https://YOUR-TOWER-ADDRESS/api/login
- swith tabs
- Login with Azure AD on https://YOUR-TOWER-ADDRESS
- Check **admin** user details

No other steps were required during my tests.

**Comment by ghjm** [comment] 2020-09-24 14:19
Ok, I can reproduce this now.  The trick is to have both browser tabs open _before_ logging into either one of them.

**Comment by jakemcdermott** [comment] 2020-10-01 03:05
Hi. I've opened a PR to fix this issue: https://github.com/ansible/awx/pull/8299

I've confirmed that this bug isn't specific to Azure AD. It's reproducible for any oauth provider (at least the ones I tried).

For those testing and verifying this issue, I recommend creating a github application to parametrize your social auth settings as it's simpler than azure:
* go to settings ->developer settings ->oauth apps" 

My other recommendation would be to reproduce the bug (undo the code change) before verifying the fix and to use a completely separate user for each attempt. Once you've changed a local user to a social one via this bug, you can't use it for a subsequent test.

**Comment by jakemcdermott** [comment] 2020-10-01 03:14
Hi. I've opened a PR to fix this issue: https://github.com/ansible/awx/pull/8299

I've confirmed that this bug isn't specific to Azure AD. It's likely reproducible for any oauth provider.

For those testing and verifying this issue, I recommend creating a github application to parametrize your social auth settings. It's simpler than azure so it's a great way to make sure you have the bug reproduction steps exactly right before trying any of the other providers: 

* In github, go to settings ->developer settings ->oauth apps

Be aware that once you've changed a local user to a social one via this bug, you shouldn't use it for a subsequent test. Delete all of the user(s) and make new ones.

**Comment by unlikelyzero** [comment] 2020-10-05 14:27
@kdelee , let's 👁️ this next week when doing the social auth automation

**Comment by unlikelyzero** [comment] 2020-10-07 23:34
@kdelee and @tiagodread are going to take this finish verifying this as a part of the Automation Social Auth work

**Comment by kdelee** [comment] 2020-10-22 16:08
1) Have two not logged in browser tabs, one open to api, other open to login page
2) Log in as admin in api
3) Log in as social auth user in UI


In the past:
  - social user logs in, sees that they are admin
  - admin now labeled as "social" user
  
Now:
  - social user logs in, sees they are themselves
  - they are labeled social
  - tab that was logged in admin, now when navigate to new page is now the social user
  - admin is not marked as social (good)
  - log out of API, logs me out of UI too
  
 
 Note: 
  - seems like you become the user you last logged in as in all currently open tabs, whereas in the past you were the user your FIRST logged in as in all open tabs

**Comment by unlikelyzero** [comment] 2020-10-22 16:35
We will not be adding automated coverage for this if you'd like to close this out @kdelee

**Comment by tiagodread** [comment] 2020-10-22 17:21
After a retest like @kdelee post above this bug doesn’t happen anymore, closing this.

**Closed as completed by tiagodread** 2020-10-22 17:22 UTC
Labels: type:bug, component:api, component:ui
