### ISSUE TITLE
Re-Add Description to Hosts List (17.x)

### ISSUE THREAD

**Issue by DanyD** [ansible/awx#9235] opened 2021-02-04 10:47 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The new theme doesn't display the host description field in the table view. As we are using an internal network for managing the AWX instances the hostnames are meaningless local IPs (e.g. 192.168.x.x) (we are using no local DNS) which makes the list very unhandy. If the description is too long for some cases introducing an optional "Host Label"  would be a solution - it could be used in all lists if set - otherwise the hostname is being shown. We experimented with host aliases but then the LIMIT can not be done based on the IP - could be a solution when there would be a suggest for the limit as proposed in #9236

**Comment by jetxeberria** [comment] 2021-11-04 18:52
We also use as hostnames internal codes not meaningful at all. The lack of a short description makes surfing along hosts quite annoying. We would appreciate to recover the previous descriptive view of lists, including at least description or a short label as DanyD suggests.

**Comment by azrdev** [comment] 2022-02-23 12:52
duplicate of #3348 ?

**Comment by mabashian** [comment] 2022-04-04 18:51
Yes, dupe of #3348

**Closed as completed by mabashian** 2022-04-04 18:51 UTC
Labels: component:ui, flag:community
