### ISSUE TITLE
Missing Job Output - Maybe related to failures or error message

### ISSUE THREAD

**Issue by joeywashburn** [ansible/awx#11878] opened 2022-03-09 00:29 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Stdout is stopping part way through some  playbooks.  In the UI you can see gray bars that seem to represent the additional job output.

This seems to be occurring only on jobs that have Errors or Warnings or failures.  At first we thought it was only on jobs that has some no_log requirements.

As an example

`[WARNING]: Module did not set no_log for double_password`

The Stdout stops immediately after this line.  It seems like its trying to protect us from ourselves.  The password is encrypted and cant be seen, but maybe its searching for some standard variable names it thinks should not be there.

But then I noticed it another job.  The Stdout stops right after this
```
[DEPRECATION WARNING]: The 'return_code' return key is deprecated. Please use 
'rc' instead. This feature will be removed from kubernetes.core in version 
4.0.0. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

So it seems like if it hits anything like a warning, or error etc it stops giving Stdout

In our case because there are several steps after the warning message shown in the screenshot, if I actively watch the playbook run and watch the output, I can the additional tasks as expected, but as soon as the playbook finishes everything past the error message dissapears

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Take a vanilla install.  Run a playbook that will cause an error or warning but not fail out.  Make sure to have additional tasks after the error or failure.

Run the playbook, you should notice that Stdout stops at the error message

### Expected results

You should see all the Stdout

### Actual results

you should notice that Stdout stops at the error message

### Additional information

![awx1](https://user-images.githubusercontent.com/58124021/157349026-628e0393-bcb1-498e-bcbf-e2cd4833bea3.png)

Notice the grey lines after the message.  Those seem to represent the Stdout that is being hidden

**Comment by joeywashburn** [comment] 2022-03-09 00:34
I just checked and I can see the stdout via the API.  Just as additional info

**Comment by kurokobo** [comment] 2022-03-09 01:14
Seems duplicate of #11647, #11765, #11818

**Comment by joeywashburn** [comment] 2022-03-09 01:32
Thanks, I did not find those when searching, but looking at them, I agree,
dupes

**Comment by mabashian** [comment] 2022-03-11 18:35
Yea this is almost certainly covered in https://github.com/ansible/awx/issues/11647, https://github.com/ansible/awx/issues/11765, https://github.com/ansible/awx/issues/11818.  If not, please re-open.

**Closed as completed by mabashian** 2022-03-11 18:35 UTC
Labels: type:bug, component:ui, needs_triage
