### ISSUE TITLE
can not start awx_redis [Error response from daemon: OCI runtime]

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9469] opened 2021-03-03 19:00 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After a patch install can not start awx_redis container 

Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/tmp/awxcompose/redis.conf" to rootfs at "/var/lib/docker/overlay2/8b87878234d9f806633c4e714fea086459ba04f3ea43d297613107fcb23cc7ee/merged/usr/local/etc/redis/redis.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: awx_redis

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker
* Ansible version:  2.9.17
* Operating System: RHEL 7.9
* Web Browser:

##### STEPS TO REPRODUCE

[root@ibmd13awx01 awx]# docker start awx_redis
Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/tmp/awxcompose/redis.conf" to rootfs at "/var/lib/docker/overlay2/8b87878234d9f806633c4e714fea086459ba04f3ea43d297613107fcb23cc7ee/merged/usr/local/etc/redis/redis.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: awx_redis
[root@ibmd13awx01 awx]# ansible --version

##### ADDITIONAL INFORMATION

[root@ibmd13awx01 awxcompose]# docker inspect awx_redis
[
    {
        "Id": "566a8ab7369b378c0fac7c76a8ec15c970e4b26a08f5d2c324b1b9720a366abe",
        "Created": "2021-02-01T20:26:56.771216024Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "/usr/local/etc/redis/redis.conf"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 127,
            "Error": "OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting \"/tmp/awxcompose/redis.conf\" to rootfs at \"/var/lib/docker/overlay2/8b87878234d9f806633c4e714fea086459ba04f3ea43d297613107fcb23cc7ee/merged/usr/local/etc/redis/redis.conf\" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type",
            "StartedAt": "2021-02-01T20:30:25.617630033Z",
            "FinishedAt": "2021-03-03T17:41:01.689718579Z"

[root@ibmd13awx01 awxcompose]# pwd
/tmp/awxcompose
[root@ibmd13awx01 awxcompose]# ls -ltr
total 24
drwxr-xr-x 2 root root 4096 Mar  3 11:36 redis_socket
drwxr-xr-x 2 root root 4096 Mar  3 11:36 nginx.conf
drwxr-xr-x 2 root root 4096 Mar  3 11:36 credentials.py
drwxr-xr-x 2 root root 4096 Mar  3 11:36 SECRET_KEY
drwxr-xr-x 2 root root 4096 Mar  3 11:36 environment.sh
drwxr-xr-x 2 root root 4096 Mar  3 12:05 redis.conf
[root@ibmd13awx01 awxcompose]#

**Comment by wenottingham** [comment] 2021-03-03 22:07
Closing as a duplicate of https://github.com/ansible/awx/issues/9401

**Closed as completed by wenottingham** 2021-03-03 22:07 UTC
Labels: type:bug
