### ISSUE TITLE
Parent WFJT Surveys apply extra_vars to child Job Types in inconsistent ways

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2727] opened 2018-11-16 23:51 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Parent WFJT Surveys apply extra_vars to child JTs, SJTs, and WFJTs in inconsistent ways.
- Child SJTs inherit Parent WFJT Surveys as extra_vars even if Child SJT has extra_var prompting disabled. Each slice inherits the surveys as extra_vars.
- Child JTs inherit Parent WFJT Surveys as extra_vars even if Child SJT has extra_var prompting disabled.
- Child WFJTs do not inherit Parent WFJT Surveys as extra_vars. "Grandchildren" do not inherit the extra_vars even if the extra_var prompt setting is enabled.

##### ENVIRONMENT
* AWX version: 3.4.0-workflow-inventory

##### STEPS TO REPRODUCE
1. Create a JT with extra_var prompting enabled. "JT A"
1. Create a JT with extra_var prompting disabled. "JT B"
1. Create a WFJT which contains both JT A and JT B. "Sub WFJT"
1. Create a WFJT which contains Sub WFJT, JT A, JT B. "Overall WFJT"
1. Modify "Overall WFJT" such that it contains survey values including a default value.
1. Run "Overall WFJT" and specify survey extra_vars or use default survey extra_vars.

Note: Sub WFJT and the grandchildren JT A and JT B are the only Jobs executed without inheriting the survey extra_vars.

##### EXPECTED RESULTS
1. extra_var survey prompting should be observed in the same way regardless of Job Type.
1. extra_var surveys prompts should only apply to Jobs which have enabled extra_var prompting.

##### ACTUAL RESULTS
Inconsistent application of extra_vars as surveys

**Comment by AlanCoding** [comment] 2018-11-17 15:24
This is picking up a conversation which was last active here:

https://github.com/ansible/awx/issues/497#issuecomment-370778213

SJTs are JTs, so yes, behavior for both of these should be the same.

> Child WFJTs do not inherit Parent WFJT Surveys as extra_vars. "Grandchildren" do not inherit the extra_vars even if the extra_var prompt setting is enabled.

Yes, this is very detailed documentation of the current and intended behavior. Couldn't have written it better myself.

Workflows "should" not pass variables to jobs they spawn if the JT doesn't prompt for them. Obviously they do. This is because that's the way workflows were introduced. This behavior constitutes a form of permissions escalation, inconsistent with the way prompts are handled generally.

Since introduction of workflows, this exception (bypassing vars prompting rules in the case of WFJTs exclusively) has been painstakingly maintained as the rest of the rules were, in general, made more consistent across the app. With the introduction of workflow-inventory and workflows-in-workflows, we are not worsening the loophole.

Closing this loophole is going to be a difficult conversation. It probably needs to be more than just a release note.

**Comment by AlanCoding** [comment] 2018-11-19 19:42
Also see:

https://github.com/ansible/awx/pull/2342/files#diff-bfd7ef4b08d27476c9dd4c578cb5a4d4R185

**Comment by wenottingham** [comment] 2018-11-26 16:28
How complicated would it be to have child workflows follow the behavior of child JTs?

**Comment by AlanCoding** [comment] 2018-11-26 16:39
Trivial, except that it exposes a permissions leak. I will delay writing an essay on the implications right now, but will try to get back to you on that.

**Comment by ryanpetrello** [comment] 2019-05-03 16:37
Documented known issue: https://docs.ansible.com/ansible-tower/latest/html/userguide/workflows.html#extra-variables

**Closed as completed by ryanpetrello** 2019-05-03 16:37 UTC
Labels: type:bug, component:api
