### ISSUE TITLE
Survey stage in workflow editor

### ISSUE THREAD

**Issue by AndreasDavour** [ansible/awx#11128] opened 2021-09-24 07:26 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

As there are multiple requests to make Surveys more dynamic, and it might necessitate a big rewrite, a smaller change might be to add another node type in the workflow editor. Now we can add templates, approvals and inventory syncs. I would suggest adding a Survey node as another type to maybe inject a bit of dynamism into the flow, as is so often requested.

Ideally this would not be a thing, and Surveys would be programmable.

**Comment by shanemcd** [comment] 2021-10-01 17:33
Dupe of #20

**Closed as completed by shanemcd** 2021-10-01 17:33 UTC
