### ISSUE TITLE
AWS gets stucked in Redis saving.

### ISSUE THREAD

**Issue by maxifox79** [ansible/awx#9972] opened 2021-04-21 13:25 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
While executing "make docker-compose", the process reports a loop in redis task trying to save changes.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: docker
* AWX deployment target: docker
* Operating System: Centos 7.9

##### STEPS TO REPRODUCE
on AWX installer, while executing
make docker-compose

##### EXPECTED RESULTS
Finish AWX configuration

##### ACTUAL RESULTS
Redis saving process is running in loop

##### ADDITIONAL INFORMATION

awx_1_1     | 2021-04-21 12:46:34,834 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redis_1_1   | 1:M 21 Apr 2021 12:49:15.035 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 12:49:15.036 * Background saving started by pid 11
redis_1_1   | 11:C 21 Apr 2021 12:49:15.038 * DB saved on disk
redis_1_1   | 11:C 21 Apr 2021 12:49:15.039 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 12:49:15.136 * Background saving terminated with success
redis_1_1   | 1:M 21 Apr 2021 12:54:16.045 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 12:54:16.046 * Background saving started by pid 12
redis_1_1   | 12:C 21 Apr 2021 12:54:16.048 * DB saved on disk
redis_1_1   | 12:C 21 Apr 2021 12:54:16.048 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 12:54:16.147 * Background saving terminated with success
redis_1_1   | 1:M 21 Apr 2021 12:59:17.014 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 12:59:17.014 * Background saving started by pid 13
redis_1_1   | 13:C 21 Apr 2021 12:59:17.017 * DB saved on disk
redis_1_1   | 13:C 21 Apr 2021 12:59:17.017 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 12:59:17.115 * Background saving terminated with success
redis_1_1   | 1:M 21 Apr 2021 13:04:18.011 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 13:04:18.011 * Background saving started by pid 14
redis_1_1   | 14:C 21 Apr 2021 13:04:18.013 * DB saved on disk
redis_1_1   | 14:C 21 Apr 2021 13:04:18.014 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 13:04:18.111 * Background saving terminated with success
redis_1_1   | 1:M 21 Apr 2021 13:09:19.084 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 13:09:19.084 * Background saving started by pid 15
redis_1_1   | 15:C 21 Apr 2021 13:09:19.086 * DB saved on disk
redis_1_1   | 15:C 21 Apr 2021 13:09:19.087 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 13:09:19.184 * Background saving terminated with success
redis_1_1   | 1:M 21 Apr 2021 13:14:20.097 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 13:14:20.097 * Background saving started by pid 16
redis_1_1   | 16:C 21 Apr 2021 13:14:20.100 * DB saved on disk
redis_1_1   | 16:C 21 Apr 2021 13:14:20.100 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 13:14:20.198 * Background saving terminated with success
redis_1_1   | 1:M 21 Apr 2021 13:19:21.072 * 100 changes in 300 seconds. Saving...
redis_1_1   | 1:M 21 Apr 2021 13:19:21.073 * Background saving started by pid 17
redis_1_1   | 17:C 21 Apr 2021 13:19:21.075 * DB saved on disk
redis_1_1   | 17:C 21 Apr 2021 13:19:21.076 * RDB: 0 MB of memory used by copy-on-write
redis_1_1   | 1:M 21 Apr 2021 13:19:21.173 * Background saving terminated with success

Any ideas how to resolve this?

**Comment by shanemcd** [comment] 2021-04-21 16:51
This just looks like Redis doing its thing. Are you experiencing any functional issues with the system?

**Comment by maxifox79** [comment] 2021-04-21 18:14
Thanks for your feedback. This process is being executed for the last 5 hours, CPU and memory are not being impacted at all. This process seems to be in a loop, and we don´t have any clue about what´s happening with the deploy, any ideas?

top - 15:10:35 up 25 min,  2 users,  load average: 0.00, 0.01, 0.05
Tasks: 173 total,   1 running, 172 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.1 us,  3.1 sy,  0.0 ni, 93.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8009276 total,  6611496 free,   825996 used,   571784 buff/cache
KiB Swap:  3145724 total,  3145724 free,        0 used.  6933768 avail Mem

**Comment by shanemcd** [comment] 2021-04-21 18:17
Is it preventing you from running jobs? I'm not seeing any issues here.

**Comment by maxifox79** [comment] 2021-04-21 18:32
We detected this from logs

awx_1_1     | awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed
awx_1_1     | awx-nginx stdout |
awx_1_1     | 2021-04-21 18:18:28,441 INFO exited: awx-nginx (exit status 2; not expected)
awx_1_1     | 2021-04-21 18:18:28,442 INFO gave up: awx-nginx entered FATAL state, too many start retries too quickly
awx_1_1     | awx-nginx stdout | make[1]: *** [Makefile:263: nginx] Error 1
awx_1_1     | awx-nginx stdout | make[1]: Leaving directory '/awx_devel'

**Comment by shanemcd** [comment] 2021-04-21 18:38
Ah. It's a duplicate of https://github.com/ansible/awx/issues/9552 then.

**Closed as completed by shanemcd** 2021-04-21 18:38 UTC
Labels: type:bug, component:installer

**Comment by maxifox79** [comment] 2021-04-21 18:42
thanks for your help!!!!

**Comment by maxifox79** [comment] 2021-04-21 21:01
while trying to build de User Interface using command <> I get this messages:
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  597.29 KB  build/static/js/2.2dec5330.chunk.js
  303.19 KB  build/static/js/main.2767e07e.chunk.js
  64.95 KB   build/static/css/2.4f9d8bcb.chunk.css
  770 B      build/static/js/runtime-main.a1234c1a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

mkdir -p awx/public/static/css
mkdir -p awx/public/static/js
mkdir -p awx/public/static/media
cp -r awx/ui_next/build/static/css/* awx/public/static/css
cp -r awx/ui_next/build/static/js/* awx/public/static/js
cp -r awx/ui_next/build/static/media/* awx/public/static/media
touch awx/ui_next/.ui-built
make[1]: Leaving directory '/awx_devel'


When trying to reach api at https://localhost:8043/api/v2 everything works as expected
When trying to reach UI at https://localhost:8043/#/home screen stays blank.

What I am missing?

**Comment by ghost** [comment] 2024-02-27 16:42
Hello 
I am trying to install AWX 23.8.0 and having the same issue 
The installation is not completing and the tools_redis_1 is goind in loop with the message similar message 

```
tools_redis_1     | 1:M 27 Feb 2024 16:27:09.033 * 100 changes in 300 seconds. Saving...
tools_redis_1     | 1:M 27 Feb 2024 16:27:09.033 * Background saving started by pid 14
tools_redis_1     | 14:C 27 Feb 2024 16:27:09.038 * DB saved on disk
tools_redis_1     | 14:C 27 Feb 2024 16:27:09.038 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
tools_redis_1     | 1:M 27 Feb 2024 16:27:09.134 * Background saving terminated with success
tools_redis_1     | 1:M 27 Feb 2024 16:32:10.087 * 100 changes in 300 seconds. Saving...
tools_redis_1     | 1:M 27 Feb 2024 16:32:10.088 * Background saving started by pid 21
tools_redis_1     | 21:C 27 Feb 2024 16:32:10.094 * DB saved on disk
tools_redis_1     | 21:C 27 Feb 2024 16:32:10.095 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
tools_redis_1     | 1:M 27 Feb 2024 16:32:10.189 * Background saving terminated with success
tools_redis_1     | 1:M 27 Feb 2024 16:37:11.062 * 100 changes in 300 seconds. Saving...
tools_redis_1     | 1:M 27 Feb 2024 16:37:11.062 * Background saving started by pid 22
tools_redis_1     | 22:C 27 Feb 2024 16:37:11.067 * DB saved on disk
tools_redis_1     | 22:C 27 Feb 2024 16:37:11.067 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
tools_redis_1     | 1:M 27 Feb 2024 16:37:11.163 * Background saving terminated with success
```

I tried to add nginix user in the makefile but got the error saying user already exists. 

Any idea how to solve this ? 

I am tried in MacOs locally  and also in AWS AL2 machine, both have the same error. 


 I also tried to run 
`docker exec tools_awx_1 make clean-ui ui-devel`

but get this 
![Screenshot 2024-02-27 at 18 11 06](https://github.com/ansible/awx/assets/138001614/f4a936b2-70a2-4a51-9ab2-4874f675248c)
 

Thanks

**Comment by netappkr** [comment] 2024-03-14 04:51
Hello @aj-kyriba 
I have the same issue.
are you resolve it?

**Comment by wooyoungAhn** [comment] 2024-03-14 04:53
Hello @aj-kyriba 
I have the same issue
Have you resolved it?

**Comment by ghost** [comment] 2024-03-14 08:37
hi @wooyoungAhn 
After rerunning the `docker exec tools_awx_1 make clean-ui ui-devel` command it was resolved for me. 
Also you might need to wait few minutes for the service to comeup.
