### ISSUE TITLE
Apply role display changes to ui_next

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4765] opened 2019-09-17 14:42 UTC
##### ISSUE TYPE
 - Task

##### SUMMARY
Apply https://github.com/ansible/awx/pull/4529 to ui_next

This issue exists so we don't forget to make this change.

**Comment by unlikelyzero** [comment] 2020-07-27 12:47
@dsesami can you check to make sure this is working?

**Comment by dsesami** [comment] 2020-07-29 16:25
there's a bit of weirdness happening with the UI org/user relationship. I'd like to verify this after https://github.com/ansible/awx/issues/7756 is fixed.

**Comment by dsesami** [comment] 2020-08-19 18:00
This is semi-redundant with https://github.com/ansible/awx/issues/4532 -- do we want to close this one and leave the other open @mabashian ?

**Comment by jakemcdermott** [comment] 2020-08-19 21:20
closing as duplicate of https://github.com/ansible/awx/issues/4532

**Closed as completed by jakemcdermott** 2020-08-19 21:20 UTC
Labels: type:feature
