### ISSUE TITLE
RFE: Add Option to Replace CACERT Bundle for Tower Packages through UI

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#531] opened 2017-10-30 19:15 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Add an interface which allows users to replace the CACERT bundles used within Tower for custom cacerts. This allows users to add a cacert bundle for requests for scenarios such as winrm interfacing with Windows hosts using custom signed certificates. This is to circumvent modifying the cacert bundle on the backend of the Tower server and losing custom changes during upgrades/re-installations.

##### ENVIRONMENT
* AWX version: 3.2+

**Comment by wenottingham** [comment] 2017-10-30 21:17
Would be best tackled in conjunction with https://github.com/ansible/awx/issues/416, even if this is a separate thing.

**Comment by sdirbach** [comment] 2018-05-23 15:10
Is there any progress on this?

**Comment by ericzolf** [comment] 2018-12-06 17:31
It would be a good first step if Tower/AWX respectively Ansible and its modules could use the default system CACERT bundle, which the admins (should) know how to manage, instead of using an unmanageable bundle coming with a blackbox Python library. Searching through some of the (Python) modules, though, it seems each has its own way to handle CACERT bundles, e.g.:

- SSL_CERT_FILE for libcloud
- REQUESTS_CA_BUNDLE or CURL_CA_BUNDLE for requests (according to `sessions.py`,
whereas certs.py rather uses certifi, which isn't installed anymore in 3.3)
- I haven't understood how winrm handles this point...

Looking at this, shouldn't it be rather an Ansible RFE/issue, with the additional difficulty that for each new Python module dependency used by an Ansible module, it might require another approach to configure centrally? The Ansible parameter that would then need to be created could still be exposed in Tower, but that would be a further step.

**Comment by sdirbach** [comment] 2018-12-07 12:32
@ericzolf AFAIR WinRM uses the request lib, which itself uses the certifi lib

**Comment by ghjm** [comment] 2020-08-04 13:45
I would argue that, instead of trying to build a CA cert management GUI, what we should instead be doing is searching for and eliminating any cases where libraries go off and use their own private CA store instead of the system trust.  If WinRM in Ansible-in-AWX is using the certifi CA list instead of the RHEL one, we should fix that.  Adding a cert to the system trust should make it trusted by all Tower services.  Then people can manage their system trust using already-existing CA management tools, such as the `update-ca-trust` CLI and the Cockpit GUI.

**Comment by wenottingham** [comment] 2020-09-14 19:04
Given the different deployment models, and the execution model changes, that does sound like a more correct  approach - closing as a duplicate of #416.

**Closed as completed by wenottingham** 2020-09-14 19:04 UTC
Labels: type:enhancement, component:api, component:ui, help wanted
