### ISSUE TITLE
Rename jobs in workflow

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#5941] opened 2020-02-14 08:13 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now if you put many same templates in the job workflow with different parameters, the name of jobs is same in tree and it's hard to figure out which one is which, it would be nice if you could give them some nickname in tree

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1560121/74513120-2a875180-4f0a-11ea-9d69-adbe41845316.png">

**Comment by sumkincpp** [comment] 2020-02-14 13:25
:+1:
Also, previously it was impossible to distinguish node names via API, which limited understanding of node place/context within current worklfow.

Might be relevant to #2032

**Comment by ryanpetrello** [comment] 2020-02-14 18:04
duplicate of https://github.com/ansible/awx/issues/5824

**Closed as completed by ryanpetrello** 2020-02-14 18:04 UTC
Labels: type:enhancement, component:api
