### ISSUE TITLE
Unable to create Workflow Template.

### ISSUE THREAD

**Issue by miyuk** [ansible/awx#4117] opened 2019-06-20 03:57 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to create workflow template because I cloud not select name area by grayed-out.
I changed browser language and try it, but result was the same.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: CentOS 7.6
* Web Browser: Chrome 75.0.3770.100

##### STEPS TO REPRODUCE
1. Login AWX console.
2. `Templates` -> `+[Workflow Template]`

##### EXPECTED RESULTS
Create Workflow Template.

##### ACTUAL RESULTS
Unable to create Workflow Template because unable to edit `Name`

##### ADDITIONAL INFORMATION
I tried it with 2 browser language `English` and `Japanese`.
But, result was the same.

**Comment by r-okui** [comment] 2019-06-21 08:30
I got the same situation too.
It was the same whether I logged in with admin or another user that has "Organization/Workflow Admin" permission.

**Comment by mabashian** [comment] 2019-06-21 17:35
Yea this is a duplicate of https://github.com/ansible/awx/issues/4091 and was fixed by https://github.com/ansible/awx/pull/4096

**Closed as completed by mabashian** 2019-06-21 17:35 UTC
Labels: type:bug
