### ISSUE TITLE
performance issue while running job on large inventory 

### ISSUE THREAD

**Issue by SpikeShen** [ansible/awx#3859] opened 2019-05-09 06:01 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have 28,497 hosts in my inventory. AWX takes 4 mins to prepare for job start.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker on linux
* Ansible version:  2.7.4
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Start a job on an inventory which have 28,497 hosts.

##### EXPECTED RESULTS

Job should start to run immediately.

##### ACTUAL RESULTS

It takes 4 min to prepare and finished running normally.

##### ADDITIONAL INFORMATION

One Case snapshot.
![awx](https://user-images.githubusercontent.com/29426999/57430606-ce98e980-7262-11e9-9e35-5d617871ff40.png)

**Comment by SpikeShen** [comment] 2019-05-09 08:26
All 28,497 hosts are imported by inventory scripts.

**Comment by shanemcd** [comment] 2019-05-09 12:48
How big is the host you’re running this on?

**Comment by chrismeyersfsu** [comment] 2019-05-09 12:49
@SpikeShen we fixed that in a newer version of AWX. Try upgrading and let us know either way. Thanks!

**Comment by ryanpetrello** [comment] 2019-05-09 13:55
Duplicate of https://github.com/ansible/awx/issues/3214

**Closed as completed by ryanpetrello** 2019-05-09 13:55 UTC
Labels: type:bug
