### ISSUE TITLE
Workflow Approval Templates are currently unexportable

### ISSUE THREAD

**Issue by zedr** [ansible/awx#7946] opened 2020-08-20 12:56 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The CLI command `export` cannot serialize any Approval Template nodes belonging to a Workflow Job Template. The reason given is that the command is "unable to construct a natural key for foreign key 'unified_job_template'". The Workflow is exported but lacks the node, leading to an incomplete workflow.

Perhaps it is due to a missing `identifier` attribute for this type of node?

**Edit**: renamed from "Lack of natural key makes Workflow Approval Templates unexportable"

##### ENVIRONMENT
* AWX version: Tower 7.3.1
* AWX install method: install script
* Ansible version:  2.9.11
* Operating System: RHEL
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1. Create a new Workflow Job Template
2. Add a Job Template node
3. Add an Approval node
4. Run the AWX CLI export command, e.g. ` awx --conf.host=https://tower.local --conf.token=<MYTOKEN> --workflow_job_templates=12 export`
5. Observe the following warning log messages:
    > This object does not have a natural key: /api/v2/workflow_approval_templates/14/
    > Unable to construct a natural key for foreign key 'unified_job_template' of object /api/v2/workflow_job_template_nodes/2/.

##### EXPECTED RESULTS

The Approval node should appear inside `workflow_job_templates[].related.workflow_nodes`.

##### ACTUAL RESULTS

The Approval node is missing, e.g.:
```yaml
workflow_job_templates:
- allow_simultaneous: false

  (...)

  related:

    (...)
    workflow_nodes:
    - all_parents_must_converge: false
      diff_mode: null
      extra_data: {}
      identifier: 67024aa7-36fe-46c4-8665-b0ca825ca386
      inventory: null
      job_tags: null
      job_type: null
      limit: null
      natural_key:
        identifier: 67024aa7-36fe-46c4-8665-b0ca825ca386
        type: workflow_job_template_node
        workflow_job_template:
          name: Test Workflow
          organization:
            name: Default
            type: organization
          type: workflow_job_template
      related:
        always_nodes: []
        credentials: []
        failure_nodes: []
        success_nodes:
        - identifier: 38efaf33-21f2-4049-8bc5-b7537181255e
          type: workflow_job_template_node
          workflow_job_template:
            name: Test Workflow
            organization:
              name: Default
              type: organization
            type: workflow_job_template
      scm_branch: null
      skip_tags: null
      unified_job_template:
        name: Demo Job Template
        organization:
          name: Default
          type: organization
        type: job_template
      verbosity: null
      workflow_job_template:
        name: Test Workflow
        organization:
          name: Default
          type: organization
        type: workflow_job_template
    - !!! APPROVAL NODE SHOULD BE HERE !!!
  scm_branch: null
  survey_enabled: true
  webhook_credential: null
  webhook_service: ''
```

**Comment by snooyen** [comment] 2021-07-30 20:38
I'm running into this as well when using awx.awx collection 16.0.0 (tried via awxkit awx cli 16.0.0 as well)

**Comment by ghost** [comment] 2021-11-20 01:48
Hi,

We are trying to import a workflow with some approval. 
To know the syntax of this part we have tried an export of an existing workflow with some approval but isn't working. 

Even if the export wasn't possible related to this issue.
Does anyone have the syntax to do an import?

```yml
workflow_job_templates:
- allow_simultaneous: false
  name: test_approval
  natural_key:
    name: test_approval
    organization:
      name: my_organisation_test
      type: organization
    type: workflow_job_template
  organization:
    name: my_organisation_test
    type: organization
  related:
    workflow_nodes:
    - all_parents_must_converge: true
      identifier: test-approval
      natural_key:
        identifier: test-approval
        type: workflow_job_template_node
        workflow_job_template:
          name: test_approval
          organization:
            name: my_organisation_test
            type: organization
          type: workflow_job_template
      unified_job_template: # We are looking to write this part
        name: my_approval
        description: "Do this ?"
        timeout: 30
```

In this case I have on the UI of Ansible tower the image bellow. 

![Screen Shot 2021-11-19 at 8 42 49 PM](https://user-images.githubusercontent.com/25638379/142709895-471736dc-cebf-47cf-8186-f092c4676b42.png)

Thank you in advance to any one who may be able to give me some ideas.

**Comment by muchafel** [comment] 2022-02-07 15:04
we are having the same issue with a custom EE
This object does not have a natural key: /api/v2/execution_environments/3/
Unable to construct a natural key for foreign key 'execution_environment' of object /api/v2/job_templates/11

**Comment by jbradberry** [comment] 2022-04-18 15:07
@muchafel you are using a version of awxkit / awx-cli from between when we implemented import/export (June 2020) and when we added support for Execution Environments (March 2021).  Upgrading your version of awxkit should clear that up.

**Comment by jbradberry** [comment] 2022-04-18 16:20
Leaving this here in case anyone else winds up picking this up:

This issue is going to be trickier to deal with than the title would lead you to believe.  Workflow approval templates are a special case of unified job templates, and are exposed in the API in the same way.  However, they get created via a special relation endpoint, `/api/v2/workflow_job_template_nodes/<id>/create_approval_template/`, with a small subset of the fields that are relevant for other unified job templates.

I believe,
- It is not appropriate to export or import approvals as top-level objects.  These are objects that are only relevant tied into some specific workflow node, and are not going to be shared.  Therefore, they should not get a natural key.
- The existing procedure to allow export of dependent objects as just a blob of data is by adding them to the `DEPENDENT_EXPORT` list.  However, this can't be done as-is because it would (probably?) interfere with other types of job templates attached to workflow nodes.  Some refactoring of this machinery will be needed, or a one-off special case injected.
- In addition to the modifications to `DEPENDENT_EXPORT`, we need to make sure that the resulting blob of data gets sent to the `create_approval_template` endpoint.  This will involve either changing the data key it is under on the export side, or special-casing the import when an object of this type is detected.
- It would be nice, though probably not required, if the export is somehow made aware of the reduced set of fields necessary to post to the `create_approval_template` endpoint and exports only those.  I don't have a good idea of how this will work yet, if at all, though.

Semi-related, we should probably update the warning/error messages to something more meaningful to the user, like "Exports of objects of type <whatever> are not supported in this version."

**Comment by aishwaryakulkarni31** [comment] 2022-05-12 18:06
> we are having the same issue with a custom EE This object does not have a natural key: /api/v2/execution_environments/3/ Unable to construct a natural key for foreign key 'execution_environment' of object /api/v2/job_templates/11

**Comment by aishwaryakulkarni31** [comment] 2022-05-12 18:14
Facing the same issue. I have the newest version of awkit and awx tower running. When trying export any resource connected with an execution environment, it gives the following error. 

Unable to construct a natural key for foreign key 'default_environment' of object /api/v2/projects/8/.
{
     "organizations": []
}

When I update the execution_environment parameter to blank, the output is as follows, even though we have 3 execution environments saved on the tower

{
     "organizations": [
          {
               "name": "Ansible Team",
               "description": "",
               "max_hosts": 0,
               **"default_environment": null,**
               "related": {
                    "notification_templates": [],
                    "notification_templates_started": [],
                    "notification_templates_success": [],
                    "notification_templates_error": [],
                    "notification_templates_approvals": []
               },
               "natural_key": {
                    "name": "Ansible Team",
                    "type": "organization"
               }
          }
     ]
}

**Comment by jbradberry** [comment] 2022-05-12 21:38
@aishwaryakulkarni31 this is not the same issue as reported at the top.  Please open a separate issue with enough information to be able to replicate the problem, including whether or not you can directly export execution environments by themselves.

If you can export EEs, what you are describing is a real bug.  If you cannot, you have the same problem as https://github.com/ansible/awx/issues/7946#issuecomment-1101480649

**Comment by aishwaryakulkarni31** [comment] 2022-05-13 12:42
> @aishwaryakulkarni31 this is not the same issue as reported at the top. Please open a separate issue with enough information to be able to replicate the problem, including whether or not you can directly export execution environments by themselves.
> 
> If you can export EEs, what you are describing is a real bug. If you cannot, you have the same problem as [#7946 (comment)](https://github.com/ansible/awx/issues/7946#issuecomment-1101480649)


Hi @jbradberry, The issue I'm facing is because I am **not** able to export EE's. Same problem as https://github.com/ansible/awx/issues/7946#issuecomment-1101480649

Pls suggest..

**Comment by jbradberry** [comment] 2022-05-13 20:03
@aishwaryakulkarni31 I have just confirmed that export of EEs both as full objects and as related objects for job templates, projects, and organizations works in the latest version of awxkit.  Please update your version of awxkit.

If you have further problems with the export (or import) of EEs, please take it to the mailing list or open it as a new ticket instead of commenting on this one.

**Comment by TheRealHaoLiu** [comment] 2022-07-13 13:21
https://github.com/ansible/awx/pull/12513

**Comment by CFSNM** [comment] 2022-07-15 08:36
Validated from QE side. Closing this issue

**Closed as completed by CFSNM** 2022-07-15 08:36 UTC
Labels: type:bug, component:cli
