### ISSUE TITLE
500 error modal contains entire HTML page of error

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6707] opened 2020-04-14 18:34 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
500 errors show as a modal, but they spit out the entire HTML page of failure:

![Screenshot_20200414_143348](https://user-images.githubusercontent.com/19942822/79260883-fb835280-7e5c-11ea-9529-1a46a2b37aa1.png)

There should be more focused error-reporting here.

#### STEPS TO REPRODUCE
To create a 500 artificially within a modal:
1) Create a Job Template. 
2) Get to the delete confirmation modal, then stop
3) Visit `awx/api/serializers.py`, and change this line: 
```'job_template': DEFAULT_SUMMARY_FIELDS,```
to this:
```'job_template': DEFAULT_SUMMARY_FIELDS / 0,```
4) Without refreshing, try to confirm the deletion. a 500 will generate. Ensure that you remove the divide by 0 in order to restore your instance.

**Comment by unlikelyzero** [comment] 2020-09-15 16:14
@dsesami @tiagodread let's add a simple testcase for this

**Comment by dsesami** [comment] 2020-09-17 19:36
This is still an issue with modals -- I triggered this by forcing a bad zero-division error in the API, right when i clicked the final delete button on a job template, so it would cause the 500 to appear in a modal instead of the whole page.
![Screenshot from 2020-09-17 15-35-05](https://user-images.githubusercontent.com/19942822/93518954-8defbc80-f8fb-11ea-8f74-c887b6e29389.png)

**Comment by dsesami** [comment] 2020-09-21 17:01
adding API tag because the response might require them to do something different.

**Comment by dsesami** [comment] 2020-09-21 19:57
also, does the `Description` field have an API character limit? it should.

**Comment by mabashian** [comment] 2021-03-16 20:20
OK lets take a look at the error response when we hit a 500.  If we can pull something useful out, lets show that.  If we cannot then lets not show the entire HTML blob and just indicate that the api responded with a 500.

**Comment by ryanpetrello** [comment] 2021-04-12 19:30
@jakemcdermott @mabashian @unlikelyzero

I don't actually think this is an issue in production builds.

In the *development* environment, 40x and 50x HTTP errors are surfaced as an HTML page with traceback data, and that's what you're seeing in that modal:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/214912/114450647-45079a00-9ba4-11eb-99d5-79e0f3cb1e3e.png">

If I **disable** this in the development environment (by setting Django's `settings.DEBUG = False`, which is what `production.py` uses), I can't reproduce this:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/214912/114450601-34572400-9ba4-11eb-871a-8801a8fb90d3.png">

<img width="944" alt="image" src="https://user-images.githubusercontent.com/214912/114450433-feb23b00-9ba3-11eb-826c-0d200b25fa40.png">

**Comment by jakemcdermott** [comment] 2021-04-12 19:47
:+1: closing as `notabug`

**Closed as completed by jakemcdermott** 2021-04-12 19:47 UTC
Labels: type:bug, component:api, component:ui
