### ISSUE TITLE
Edit node credentials shows overwritten credential as selected

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#9458] opened 2021-03-02 19:13 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1376" alt="Screen Shot 2021-03-02 at 2 09 32 PM" src="https://user-images.githubusercontent.com/9889020/109701528-205de280-7b61-11eb-8ea2-4d781444e8b2.png">

In this scenario, I created a node that overrides the default machine credential on a JT.  After saving the workflow and coming back in, the above screenshot is what I saw when editing the node's credentials.

The `asdf` credential is the default machine cred and should not be shown in the `Selected` section since there another machine credential is attached to the node.

I suspect (but haven't verified) that this same bug applies to other credential types.

**Comment by mabashian** [comment] 2021-03-10 20:21
Working on this as part of #8921

**Comment by tiagodread** [comment] 2021-03-22 13:30
I can't reproduce this bug anymore, closing this issue

**Closed as completed by tiagodread** 2021-03-22 13:30 UTC
Labels: type:bug, component:ui
