### ISSUE TITLE
reopen: AWX doesn't appear to be updating roles based on requirements.yml

### ISSUE THREAD

**Issue by ikke-t** [ansible/awx#2046] opened 2018-07-05 07:31 UTC
Please reopen issue #1559, it is not fixed, it still happens. See comments after closing it, mine is from today.

**Comment by ikke-t** [comment] 2018-07-09 19:06
I'll comment here, instead of the closed issue. Having roles/requirements.yml file with git+ssh URLs fails AWX project updates. The same file works from command line. I suspect it fails to set the ssh-key.

Requirements.yml file with lines:

```
git clone ssh://nas.domain/path/ansible-role-packages.git packages
```

fails with AWX with error code 128, which leads to lot of google hits saying no/incorrect ssh key being used. Which would make sense, as by using key in bash command line (outside of AWX) with ansible-galaxy install command, this works.

```
[WARNING]: - packages was NOT installed successfully: - command git clone ssh://freenas.mynet/mnt/raid/me/git/ansible-role-packages.git packages failed in directory /tmp/tmpUuq6AH (rc=128)
```

**Comment by ikke-t** [comment] 2018-07-09 19:23
Somehow there is error in this playbook: https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L141

All repos in same ssh server under directory git/ do work from command line ansible-galaxy with the very same key. Within AWX, the ansible-galaxy run happens without the key, I suspect.

**Comment by ikke-t** [comment] 2018-09-06 20:50
I was digging a bit more into this. It seems it might not obey the user in ssh+git url. Looking from ssh host server, which hosts git repo for user ikke, I see AWX tries to connect there as root. Which it should never do:

```
Sep  6 23:38:06 nas sshd[99934]: Accepted publickey for ikke from 192.168.1.58 port 39154 ssh2: RSA SHA256:Mof5WxTOrzqk2BxO4uLIfx8k7XXXX
Sep  6 23:38:06 nas sshd[99936]: Received disconnect from 192.168.1.58 port 39154:11: disconnected by user
Sep  6 23:38:06 nas sshd[99936]: Disconnected from user ikke 192.168.1.58 port 39154
Sep  6 23:38:06 nas sshd[99939]: Accepted publickey for ikke from 192.168.1.58 port 39156 ssh2: RSA SHA256:Mof5WxTOrzqk2BxO4uLIfx8k7XXXXXX
Sep  6 23:38:06 nas sshd[99945]: Received disconnect from 192.168.1.58 port 39156:11: disconnected by user
Sep  6 23:38:06 nas sshd[99945]: Disconnected from user ikke 192.168.1.58 port 39156
Sep  6 23:38:14 nas sshd[99992]: Failed password for root from 192.168.1.58 port 39184 ssh2
Sep  6 23:38:14 nas sshd[99992]: Failed password for root from 192.168.1.58 port 39184 ssh2
Sep  6 23:38:14 nas sshd[99992]: Connection closed by authenticating user root 192.168.1.58 port 39184 [preauth]
```

I even modified the git repo url to contain the correct username ikke:
```
ssh://ikke@freenas.mynet/mnt/raid/me/git/ansible-role-packages.git
```
again, this works when project is refreshed by clicking refresh from project, but not when template has "Update Revision on Launch" checked.

AWX uses definately wrong user while trying to refresh git repo.

**Comment by sudomateo** [comment] 2018-09-07 02:24
+1 AWX does not update git+ssh roles from requirements.yml unless I delete the entire project before every update.

**Comment by jakemcdermott** [comment] 2018-10-30 18:27
Hello,

Thanks for creating this issue. This appears to be a duplicate of https://github.com/ansible/awx/issues/1632 and so I am closing. We can track the remaining work to be done for this on the linked issue.

**Closed as completed by jakemcdermott** 2018-10-30 18:27 UTC
Labels: type:bug, component:api
