### ISSUE TITLE
API v2  get stdout not work

### ISSUE THREAD

**Issue by defrancesco** [ansible/awx#607] opened 2017-11-10 14:01 UTC
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
 - API
##### SUMMARY
sdtout api  for example  /api/v2/jobs/216/stdout/ not work the result is always the message
**stdout capture is missing**
But in AWX the standard output of job work fine.

##### ENVIRONMENT
* AWX api v2
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System:RHEL 7.x
* Web Browser:All

##### STEPS TO REPRODUCE
Execute a job on AWX UI
call the api /api/v2/jobs/{ID}/stdout/
where ID = Job ID

##### EXPECTED RESULTS

standard output of executed jobs with JSON format

##### ACTUAL RESULTS

**stdout capture is missing**

**Comment by ryanpetrello** [comment] 2017-11-10 14:28
This is likely a symptom/duplicate of a more general bug:  https://github.com/ansible/awx/issues/146

...which will be resolved via: https://github.com/ansible/awx/issues/200

**Closed as completed** 2017-11-13 18:50 UTC
Labels: type:bug, component:api
