### ISSUE TITLE
Web UI: Footer obscures buttons on some screens

### ISSUE THREAD

**Issue by pchauncey** [ansible/awx#75] opened 2017-09-08 18:17 UTC
### Summary

Web UI: Footer obscures buttons on some screens

### Environment

* AWX version: devel
* Ansible version:  2.3
* Operating System: Centos 7.3
* Web Browser: Firefox 55.0.2 on Fedora 26

### Steps To Reproduce:

Use Firefox, browse to Settings and select LDAP from the Subcategory menu 

### Expected Results:

Should see Cancel and Save buttons when scrolled to the bottom.

### Actual Results:

Footer obscures the buttons.

### Additional Information:
![screenshot from 2017-09-08 13-12-41](https://user-images.githubusercontent.com/908819/30225446-1bf4260e-9498-11e7-8c6e-da53d2f135d6.png)

**Comment by jakemcdermott** [comment] 2017-09-08 18:33
Thanks for creating this. I think this might be a duplicate of ~https://github.com/ansible/awx/issues/75~ https://github.com/ansible/awx/issues/52

**Comment by pchauncey** [comment] 2017-09-08 18:36
Yep, this is the same issue.  Killing #75 then

**Closed as completed** 2017-09-08 18:37 UTC
