### ISSUE TITLE
[UI] [Bug] Next button inactive on inventory promt

### ISSUE THREAD

**Issue by 1it** [ansible/awx#1866] opened 2018-05-10 07:56 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Next button inactive on inventory promt. Can't run job.

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker on linux
* Ansible version:  2.52
* Operating System: Mac OS 10.13.4
* Web Browser: Chrome 66.0.3359.139

##### STEPS TO REPRODUCE
Portal mode -> Run job (with inventory promt) -> Check inventory -> Stuck

##### EXPECTED RESULTS
Job run

##### ACTUAL RESULTS
Job stuck on promt

##### ADDITIONAL INFORMATION
<img width="721" alt="2018-05-10 10 50 14" src="https://user-images.githubusercontent.com/7093190/39858929-c1dda3de-5440-11e8-89b3-48ce2746aca4.png">

**Comment by michaelrcarroll** [comment] 2018-05-11 17:03
I'm seeing this too. 

In a pinch, you can remove the disabled property from the button in an inspection console and continue to spawn the job, but this is a hack.

**Comment by cpatry-poly** [comment] 2018-05-14 09:06
Duplicate of https://github.com/ansible/awx/issues/1824 :-) .

**Closed as completed** 2018-05-15 15:40 UTC
Labels: type:bug, component:ui
