### ISSUE TITLE
inventory script ok with awx 11 / ko with awx 13

### ISSUE THREAD

**Issue by milodanlso** [ansible/awx#7832] opened 2020-08-05 17:14 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have an inventory script that works fine with awx 11. After migrating to awx 13 it no longer works

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.10
* Operating System: Centos 8
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I have uploaded custom inventory script

[script.txt](https://github.com/ansible/awx/files/5029983/script.txt)

##### EXPECTED RESULTS

After execution I have an inventory from my repository in AWX
![image](https://user-images.githubusercontent.com/52068250/89442862-cecab200-d74f-11ea-82df-b7362c11b0a8.png)

##### ACTUAL RESULTS

2020-08-05 17:09:41,725 INFO     awx.main.commands.inventory_import Updating inventory 2: Inventaire Siroco
2020-08-05 17:09:42,783 DEBUG    awx.main.commands.inventory_import Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_760_x_lcay4_/tmpgislgej3 --playbook-dir /tmp/awx_760_x_lcay4_ -vvvvv
2020-08-05 17:09:42,783 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_760_x_lcay4_/tmpgislgej3
2020-08-05 17:09:42,787 INFO     awx.main.commands.inventory_import Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
2020-08-05 17:09:42,787 INFO     awx.main.commands.inventory_import Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2020-08-05 17:09:42,787 INFO     awx.main.commands.inventory_import Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
2020-08-05 17:09:42,812 DEBUG    awx.main.commands.inventory_import Using provided directory '/tmp/awx_760_x_lcay4_' for isolation.
2020-08-05 17:09:42,812 DEBUG    awx.main.commands.inventory_import Running from `/tmp/awx_760_x_lcay4_` working directory.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1149, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1039, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_760_x_lcay4_/tmpgislgej3 as it did not pass its verify_file() method
auto declined parsing /tmp/awx_760_x_lcay4_/tmpgislgej3 as it did not pass its verify_file() method
toml declined parsing /tmp/awx_760_x_lcay4_/tmpgislgej3 as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /tmp/awx_760_x_lcay4_/tmpgislgej3 with script
plugin: failed to parse executable inventory script results from
/tmp/awx_760_x_lcay4_/tmpgislgej3: Expecting value: line 1 column 1 (char 0)
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]:  * Failed to parse /tmp/awx_760_x_lcay4_/tmpgislgej3 with yaml
plugin: We were unable to read either as JSON nor YAML, these are the errors we
got from each: JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error
while loading YAML.   mapping values are not allowed in this context  The error
appears to be in '/tmp/awx_760_x_lcay4_/tmpgislgej3': line 11, column 20, but
may be elsewhere in the file depending on the exact syntax problem.  The
offending line appears to be:   def get_info(param):                    ^ here
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 105, in parse
    raise AnsibleParserError(e)
[WARNING]:  * Failed to parse /tmp/awx_760_x_lcay4_/tmpgislgej3 with ini
plugin: /tmp/awx_760_x_lcay4_/tmpgislgej3:4: Expected key=value host variable
assignment, got: json
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /tmp/awx_760_x_lcay4_/tmpgislgej3 as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by milodanlso** [comment] 2020-08-06 06:05
Hello, for information i have no error if run directly my script on awx-task pod with /usr/bin/python3 script.txt or /usr/bin/python3.6 script.txt. Thanks for your help.

**Comment by blomquisg** [comment] 2020-08-07 14:46
@AlanCoding what's the status of inventory scripts in general in AWX 13?  Can you take a look at this?

**Comment by milodanlso** [comment] 2020-08-11 10:43
no answer? I am very disappointed ... I know that my English is very bad but I am making efforts ... 
FYI 1: I put version 11.2 on my development platform and the inventory is working again. Moreover it works since version 9
FYI 2: it doesn't work in version 14 either (with same error message)
FYI 3; since version 13, the first start of containers under kubernetes goes to CrashLoopBackOff ... after a delete the containers start ... but this is another story

**Comment by ryanpetrello** [comment] 2020-08-11 13:14
> no answer? I am very disappointed

Hey @milodanlso,

AWX is an open source project that we make available free of charge. While we do our best to address reported issues in a timely manner, it’s simply impossible for us to provide immediate hands-on support for every issue.  It may take awhile before somebody has free time to help troubleshoot.

In the meantime, if you're looking for more direct assistance, you might try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by milodanlso** [comment] 2020-08-11 14:59
> > no answer? I am very disappointed
> 
> Hey @milodanlso,
> 
> AWX is an open source project that we make available free of charge. While we do our best to address reported issues in a timely manner, it’s simply impossible for us to provide immediate hands-on support for every issue. It may take awhile before somebody has free time to help troubleshoot.
> 
> In the meantime, if you're looking for more direct assistance, you might try our mailing list or IRC channel:
> 
> http://webchat.freenode.net/?channels=ansible-awx
> https://groups.google.com/forum/#!forum/awx-project

Hello @ryanpetrello
Thanks for your reply... I will open a topic on groups.google...

**Comment by AlanCoding** [comment] 2020-08-11 15:41
The error that matters is:

```
[WARNING]: * Failed to parse /tmp/awx_760_x_lcay4_/tmpgislgej3 with script
plugin: failed to parse executable inventory script results from
/tmp/awx_760_x_lcay4_/tmpgislgej3: Expecting value: line 1 column 1 (char 0)
File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
plugin.parse(self.inventory, self.loader, source, cache=cache)
File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
raise AnsibleParserError(to_native(e))
```

Your script ran, but the output could not be parsed as JSON content.

> Hello, for information i have no error if run directly my script on awx-task pod with /usr/bin/python3 script.txt or /usr/bin/python3.6 script.txt. Thanks for your help.

That still won't use the python used by AWX, and that seems likely related to the root cause. Could you try running again in the container after activating that virtual environment? To do that, you want to run a command like `/var/lib/awx/venv/ansible/bin/activate` (going from memory, it may be slightly different), and then run just `python script.py`

**Comment by milodanlso** [comment] 2020-08-12 06:13
Hello @AlanCoding , if i run /var/lib/awx/venv/ansible/bin/activate in the container (awx-task or awx-web) i have this :
_**sh: /var/lib/awx/venv/ansible/bin/activate: Permission denied**_

**Comment by milodanlso** [comment] 2020-08-12 07:32
@AlanCoding, this new script work well in 11.2 but not in 14 (or 13 i suppose). This is a simulation of what the initial script does except I have a lot more objects. It should allow you to reproduce. 
[script_to_reproduce.txt](https://github.com/ansible/awx/files/5061239/script_to_reproduce.txt)

**Comment by AlanCoding** [comment] 2020-08-14 20:42
Thanks for the reproducer, I ran that in the Ansible venv, and got a similar error from `ansible-inventory`. But it does look like if parses correctly if I just remove the YAML stuff from this:

```python
    return yaml.dump(yaml.safe_load(json.dumps(groups, indent=4)))
```

changing it to:

```python
    return json.dumps(groups, indent=4)
```

Then the command `ansible-inventory -i script.py --list --export` echos back something that looks correct. The format the `ansible-inventory` [expects is JSON](https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-script-conventions).

**Comment by milodanlso** [comment] 2020-08-17 09:29
@AlanCoding I modified my script as indicated and it works ... I don't remember why I put yaml (at least in version 9) but obviously it doesn't work anymore. It doesn't bother me since I work in JSON. Thanks a lot for your help. I can go on vacation in peace :-)

**Comment by blomquisg** [comment] 2020-08-21 17:33
Let us know if you have any further issues with this.  Closing for now.

**Closed as completed by blomquisg** 2020-08-21 17:33 UTC
Labels: type:bug
