### ISSUE TITLE
Workflow cannot be saved when edited.

### ISSUE THREAD

**Issue by jpaulovic** [ansible/awx#1259] opened 2018-02-15 17:23 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When editing an existing workflow in a Workflow job template, the UI doesn't allow me to save the changes - clicking on the save button doesn't do anything. When the page is refreshed, the workflow is changed in a random, undesirable way (e.g. some tasks are moved to new parallel branches, even though the original workflow was just sequential).

##### ENVIRONMENT
* AWX version: 3.2.2
* AWX install method: Clustered Ansible Tower with multiple nodes on separate VMs
* Ansible version:  2.4.2
* Operating System: RHEL 7.4 (Tower), Fedora 26 (client)
* Web Browser: Firefox Quantum 58.0

##### STEPS TO REPRODUCE

1. Create a workflow with multiple steps (e.g. Project sync -> Inventory sync -> Job run) and save it.
2. Edit the workflow (e.g. change Type for a step from On Success to On Failure)
3. Try to save the workflow - the button won't do seemingly anything.
4. Refresh the page in the browser - the workflow will be changed randomly.

##### EXPECTED RESULTS
The workflow would be saved and UI returned to the workflow template settings.
When the page is refreshed, no changes to the workflow should be made.

##### ACTUAL RESULTS

Workflow cannot be saved - the Save button seemingly doesn't do anything.
When the page is refreshed, the workflow is changed randomly.

**Comment by jlmitch5** [comment] 2018-02-20 18:37
@jpaulovic 

I have tested this on a (mostly) up-to-date AWX devel and was not able to reproduce.

Are you using Tower (the 3.2.2 tag of your issue has me wondering)?

**Comment by jaredevantabor** [comment] 2018-02-20 18:38
@jpaulovic can you clarify `AWX version: 3.2.2`? Are you on Tower 3.2.2 or AWX? What browser are you using? Does the web console indicate any errors when you refresh, or when you try to save?

**Comment by jpaulovic** [comment] 2018-02-20 19:00
I'm on Tower 3.2.2. The web interface nor web console in Firefox seem to indicate any errors. This is actually pretty interesting, because I'm only able to reproduce this on some set of Job Templates in the workflow, not all. It seems that it only happens when a dynamic inventory sync task is in the workflow. Just for the record, the dynamic inventory task is one that is configured as follows:

SOURCE: Sourced from a Project
INVENTORY FILE: inventory/generate_inventory.py

**Comment by jlmitch5** [comment] 2018-02-20 19:44
hey @jpaulovic, the github issues are for tracking development/state of AWX releases--recommend going through your Red Hat rep, they should be able to help you get to the bottom of this.

I'm gonna close this for now as I wasn't able to reproduce for the "standard case".

**Closed as completed by jlmitch5** 2018-02-20 19:44 UTC
Labels: type:bug, component:ui

**Comment by jpaulovic** [comment] 2018-02-20 20:04
cc @matburt: I, unfortunately, won't get to test it on some local awx installation in the near future, if you want to look into this in the future I'll be happy to provide you more info on a call or via e-mail.
