### ISSUE TITLE
Please provide a better alternative to Custom Inventory Scripts that are being deprecated

### ISSUE THREAD

**Issue by AndrewSav** [ansible/awx#8081] opened 2020-09-04 11:37 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

[Custom Inventory Scripts](https://docs.ansible.com/ansible-tower/latest/html/administration/custom_inventory_script.html) are being deprecated in favour of [inventory file importing from source control](https://docs.ansible.com/ansible-tower/latest/html/administration/scm-inv-source.html#ag-inv-import). However I feel this is throwing away the baby with water, as it does not cover a few useful use cases.

**Case 1. Inventory Script debugging**

In an enterprise scenario a developer does not always have the luxury of SSHing into the tower box / pod / container. Even if they do, they will not see the nice UI showing groups and hosts and vars on separate tabs, the will see pages of json instead. Thus running the inventory script in the awx environment during development can only be practically done from awx Custom Inventory Script or, now, also inventory script importing from source control.

This means, that in order to test a fix (which could be as minor as a typo and of which a developer would have dozens or even hundreds a day) one need to check that into github repository, and then synchronise awx/tower with that check in.

This is a lot of wasted time and effort, more time is wasted rebasing this terrible commit history in nice isolated commits.

Custom Inventory Script provided a way to quickly test minor changes without the need to go through the whole VCS dance. Having this feature does not hurt any one, so could you please either leave it in or provide a workable alternative.

**Case 2. Ephemeral ongoing changes**

I use awx to provision test, PoC kubernetes / openshift clusters. Those clusters are short lived their life time is may be a day or two. Inventories for them is not something that belong in VCS, again, it litters the history, and adds a temporary stuff in otherwise permanent repository that simply does not belong there.

With Custom Inventory Scripts I can simply paste the temp inventory in the script, and then use that as inventory source for cluster provisioning and customisation. Without Custom Inventory Scripts I'm forced to put these in VCS, which I'm not really interested in, these are not things I want to track in VCS and they do not belong there.

Having Custom Inventory Script does not hamper ability to use inventory script importing from source control, but fullfil this important scenario. Please either leave that in, or provide a workable alternative.

@chrismeyersfsu @jakemcdermott

**Comment by AndrewSav** [comment] 2020-09-04 12:11
>  inventory script importing from source control

It seems that either I'm missing something, or situation is even worse, you can no longer use scripts at all, you have to put your _inventory_ in scm and the ability to run a custom script is completely removed - SCM or not.

Is this right?

**Comment by AndrewSav** [comment] 2020-09-04 12:34
Okay, I've been searching the issues / PRs in this repo:

- https://github.com/ansible/awx/pull/7763
- https://github.com/ansible/awx/issues/7528
- https://github.com/ansible/awx/pull/7577

It appears that there is some mysterious inventory plugin system is coming. 

Concerns:

- At this point there is no documentation but the Custom Inventory Scripts is [already being removed](https://github.com/ansible/awx/pull/7577). Would it be possible to allow some time for user to migrate from Custom Inventory Scripts to the new system?
- I have a handful of customer inventory scripts written in PowerShell. I want to keep using them with minimal effort under the new system. Will that be possible?

**Comment by wenottingham** [comment] 2020-09-04 17:03
@AlanCoding can you provide the explanation here for what we're doing?

**Comment by AlanCoding** [comment] 2020-09-04 18:04
> It seems that either I'm missing something, or situation is even worse, you can no longer use scripts at all, you have to put your inventory in scm and the ability to run a custom script is completely removed - SCM or not.
> 
> Is this right?

No, you can use scripts in SCM. I expect that inventory scripts will be around indefinitely, and the way we suggest using them now is to put them in SCM. I probably have 100s of examples of this, but here is one inventory script in source control that we are testing continuously:

https://github.com/ansible/test-playbooks/blob/master/inventories/dyn_inventory.py

To use this, you make a project from the ansible/test-playbooks github repo and create an inventory source, giving `inventories/dyn_inventory.py` as the location of the inventory.

> With Custom Inventory Scripts I can simply paste the temp inventory in the script, and then use that as inventory source for cluster provisioning and customisation.

Inventory scripts are not a particularly nice format. I don't know how you get a temp inventory in a format that's easy to paste into an inventory script. Maybe this comes from `ansible-inventory`? If you're dumping dynamic [k8s inventory](https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/inventory/k8s.py) to JSON to put into AWX, then I think it would be more productive to talk about a clean way to have AWX import dynamic k8s inventory.

**Comment by AndrewSav** [comment] 2020-09-04 21:08
>  I don't know how you get a temp inventory in a format that's easy to paste into an inventory script. 

@AlanCoding  This way:

```
#!/bin/bash

ansible-inventory -i /dev/stdin --list <<PasteHERE
[kube-master:children]
master

[kube-node:children]
node

[k8s-cluster:children]
master
node
calico-rr

[master]
master1 ansible_host=192.168.90.212 etcd_member_name=etcd1

[node]
node1 ansible_host=192.168.90.214 
node2 ansible_host=192.168.90.213 
node3 ansible_host=192.168.90.211 

[etcd:children]
kube-master

[calico-rr]
PasteHERE
```

The inventory is file is generated by terraform from a [template](https://github.com/AndrewSav/terraform_vsphere_vm_cluster/blob/master/templates/ansible_hosts.tpl).

This is a very low friction solution. What would be an analogue for that when you remove Custom Inventory Scripts?

**Comment by AndrewSav** [comment] 2020-09-04 21:27
> No, you can use scripts in SCM. 

Thank you for that I can see that now. It is not very well documented, so I had to dig through code to understand how it works:

- awx calls awx-manage and passes whatever you put into the "Inventory File" script.
- awx-manage passes that as is to ansible-inventory
- ansible-inventory has internal [plugins](https://github.com/ansible/ansible/tree/bbd4ec13f1a2ceba493054fa6e846d749d9a875e/lib/ansible/plugins/inventory) 
- By default [we have](https://github.com/ansible/ansible/blob/bbd4ec13f1a2ceba493054fa6e846d749d9a875e/lib/ansible/config/base.yml#L1604) 'host_list', 'script', 'auto', 'yaml', 'ini', 'toml'.
- The plugins are tried one after another on a file, they have a [verify_file](https://github.com/ansible/ansible/blob/bbd4ec13f1a2ceba493054fa6e846d749d9a875e/lib/ansible/plugins/inventory/script.py#L70) method that tells whether the file passed is accepted by the particular plugin
- The script plugin in particular [checks](https://github.com/ansible/ansible/blob/bbd4ec13f1a2ceba493054fa6e846d749d9a875e/lib/ansible/plugins/inventory/script.py#L86) that the file has execute bit set, and that it starts with shebang to be accepted by the plugin.

This is of course not news for you, I'm just writing this down for myself and for the next person that may wonder, because when I tried referencing a script from the "Inventory File" it did not work at all since I did not put `+x` on the file in the scm.

It is still not clear:

- How the new awx inventory plugin system will work
- How is it possible to incrementally debug an inventory script in awx without the need to checkout every single change to SCM and sync that checkout back with awx

**Comment by AlanCoding** [comment] 2020-09-05 02:55
Your terraform example goes through a lot data conversions. SCM inventory allows all types of Ansible inventory, so you could cut out the conversion to script and just put the ini-type file in source control instead.

You could even cut out the _templating_ process, but this gets into developing actual Ansible content. Getting the AWX inventory source closer to the ultimate source of truth makes life easier. Maybe your inventory comes from a Terraform state file, or a remote state. I don't know enough about Terraform to say much here, but imagine that you have everything you need for the Terraform CLI in source control (minus secrets). You could write an inventory plugin (or script, they still work) to interact with that CLI. Sure, you would want to debug your inventory before pushing it to source control.

If you already have a file-based inventory you're happy with locally, and it changes frequently, maybe it would be better to have automation that makes calls to the AWX API from your computer, as opposed to doing it indirectly via an inventory source. In #6725, a playbook was discussed which would take the locally available inventory and make a copy of it in an AWX inventory with API calls. That avoids putting source control in your debugging loop.

**Comment by AndrewSav** [comment] 2020-09-06 22:57
> Your terraform example goes through a lot data conversions. SCM inventory allows all types of Ansible inventory, so you could cut out the conversion to script and just put the ini-type file in source control instead.

So this is the problem, the ini file is generated. I do not think that it belongs to SCM, especially knowing that the cluster is not gonna last beyond few days. It will clutter the commit history with something that is not relevant for the repository.

> You could even cut out the templating process, but this gets into developing actual Ansible content. Getting the AWX inventory source closer to the ultimate source of truth makes life easier. Maybe your inventory comes from a Terraform state file, or a remote state. I don't know enough about Terraform to say much here, but imagine that you have everything you need for the Terraform CLI in source control (minus secrets). You could write an inventory plugin (or script, they still work) to interact with that CLI. Sure, you would want to debug your inventory before pushing it to source control.

I understand what you are saying. And it is possible. It just becomes more complicated because you are removing a feature that was useful, and do not provide a straightforward replacement. What I'm requesting, is either to keep the feature in, or provide an alternative, that does not involve SCM.

> If you already have a file-based inventory you're happy with locally, and it changes frequently, maybe it would be better to have automation that makes calls to the AWX API from your computer, as opposed to doing it indirectly via an inventory source. In #6725, a playbook was discussed which would take the locally available inventory and make a copy of it in an AWX inventory with API calls. That avoids putting source control in your debugging loop.

I'm not sure about that playbook, if I'm reading it right it adds _a single host_ not an entire inventory. 

It's not just the case with file-based inventory that changes. It is also the case with developing and debugging an inventory script. 

Additionally, similar to my previous comment in the paragraph above, I can see that it is possible to implement that with some efforts, it's just that used to work without much efforts and this is being removed. To me this feels like a step backward.

**Comment by AlanCoding** [comment] 2020-09-08 12:59
> I'm not sure about that playbook, if I'm reading it right it adds a single host not an entire inventory.

It does more than that. The data model for inventory includes:

 - Host objects
 - Group objects
 - Memberships of hosts inside groups
 - Memberships of groups inside of other groups

The playbook in the issue is an incomplete work. It did hosts, groups, and host-group memberships. However, it can be written to cover all 4 things in the data model, and thus be a complete way to copying a local inventory (which you have already debugged) and put it into an AWX inventory as a single one-off kind of thing.

The way I understand your situation: you have some algorithmic method of producing your inventory. Due to a multitude of potential reasons (system dependencies, cross-dependencies from multiple repos, secret and key management, etc.) it would not be worth it to transfer that to the AWX server. So instead, you want to simply transfer your _current_ local inventory to AWX.

It still makes sense to me to build a complete version of that playbook as a role inside of the `awx.awx` collection.

**Comment by wenottingham** [comment] 2020-09-18 17:31
Closing per comment above: you can either use a project-based inventory, or construct an inventory using the API and/or the awx collection.

**Closed as completed by wenottingham** 2020-09-18 17:31 UTC

**Comment by lals1** [comment] 2022-05-16 12:35
@AlanCoding Is there any prerequisite for python scripts from git repo to show up in the drop down menu when configuring the inventory source in AWX? I can't see any `.py` files appearing in drop down menu in AWX 21.0.0 but it does show .ini files.



> No, you can use scripts in SCM. I expect that inventory scripts will be around indefinitely, and the way we suggest using them now is to put them in SCM. I probably have 100s of examples of this, but here is one inventory script in source control that we are testing continuously:

> https://github.com/ansible/test-playbooks/blob/master/inventories/dyn_inventory.py

> To use this, you make a project from the ansible/test-playbooks github repo and create an inventory source, giving inventories/dyn_inventory.py as the location of the inventory.


<img width="909" alt="Screenshot 2022-05-16 at 15 32 03" src="https://user-images.githubusercontent.com/8269797/168593784-1b34a285-0cbb-4093-838d-03761f5a8647.png">

**Comment by lals1** [comment] 2022-05-17 06:19
> @AlanCoding Is there any prerequisite for python scripts from git repo to show up in the drop down menu when configuring the inventory source in AWX? I can't see any `.py` files appearing in drop down menu in AWX 21.0.0 but it does show .ini files.
> 
> > No, you can use scripts in SCM. I expect that inventory scripts will be around indefinitely, and the way we suggest using them now is to put them in SCM. I probably have 100s of examples of this, but here is one inventory script in source control that we are testing continuously:
> 
> > https://github.com/ansible/test-playbooks/blob/master/inventories/dyn_inventory.py
> 
> > To use this, you make a project from the ansible/test-playbooks github repo and create an inventory source, giving inventories/dyn_inventory.py as the location of the inventory.
> 
> <img alt="Screenshot 2022-05-16 at 15 32 03" width="909" src="https://user-images.githubusercontent.com/8269797/168593784-1b34a285-0cbb-4093-838d-03761f5a8647.png">

Never mind. I assigned the execute permission for the python script in the git repo and they started appearing in the drop down menu in AWX.
