### ISSUE TITLE
RFE: Ability to add multiple hosts at a time in the UI and awx-manage via single API endpoint

### ISSUE THREAD

**Issue by agilleyrh** [ansible/awx#6682] opened 2020-04-13 15:18 UTC
##### ISSUE TYPE
 - When adding a multiple hosts manually you can only do it one at a time. The ability to add hostnames from a list would save time when hosts are manually managed. 

##### SUMMARY
Ability to take a list of hostnames and add them all at one time or via a single API call.

**Comment by ryanpetrello** [comment] 2020-04-13 15:29
This is arguably entering the territory of what inventory scripts/plugins are intended to be used for.

**Comment by wenottingham** [comment] 2020-04-13 16:06
Yeah, I don't know that we'd ever really prioritize this. If you can call awx-manage, you can pass it an inventory file with multiple hosts. If you're doing it in the UI, you really should be using an inventory plugin (or inventory from SCM).

**Comment by agilleyrh** [comment] 2020-05-15 01:35
Another part of this would be the ability to copy and paste a list of hosts all at once in the UI that gets added to an inventory. This is being requested by multiple people now.

**Comment by drinkeroftea7** [comment] 2020-10-22 17:28
Several high-volume (20k+ hosts) users are running into similar problems on scaling to manage a thousand or more hosts at a time. At that scale, large consolidated inventories are unworkable. For many common workflows a large number (1000+) servers need to be managed at a time through on-demand request front-ends. This makes it impractical to manage segmented inventories in an efficient fashion, because the jobs are not being run against predictable subsets of hosts. The common practice is to create inventories on the fly via API calls. But the API only allows adding one host to an inventory at a time. This makes aggregating batches of (for example) 100-200 servers impractical without resorting to non-obvious measures such as custom inventory plugins. The lack of a batch option at this step means that the most natural workflow is to only add a single host per inventory. This is a common factor behind several performances cases driven by attempting to run a large number (1000+ at a time) of jobs against single-host inventories.

An API endpoint to batch add hosts to an inventory would create a discoverable path to managing this scale of hosts with a more efficient number of API requests and running job instances. This will greatly increase the usefulness of of the product for high-volume users.

**Comment by wenottingham** [comment] 2020-10-22 21:26
If this is a (mostly) arbitrary set of hosts defined as a throwaway inventory, I feel as if meta-smart-inventories with a query on demand/launch is a better solution.

**Comment by drinkeroftea7** [comment] 2020-10-26 20:44
Can you clarify what you mean by a "meta-smart-inventory"? Would that be a new feature or an existing one?

**Comment by wenottingham** [comment] 2020-10-26 23:24
New feature. The idea would be that it would act more or less exactly like a smart inventory, except you'd provide the fitler string at runtime/launchtime rather than when you create the inventory.

**Comment by drinkeroftea7** [comment] 2020-10-27 21:09
We would want to make sure that we don't run into the same problems caused by running a filter on a large smart inventory, because that would still leave a strong motivation to work with smaller, on-demand inventories in an environment with tens of thousands of managed hosts.

**Comment by lotaris-xx** [comment] 2020-10-27 21:12
Creating an inventory and adding a list of hosts in a single helper API call would be easiest for the end user.  Using smart filters seems to be expensive against large inventories and requires a somewhat complex syntax.

**Comment by wenottingham** [comment] 2020-10-28 19:03
There are multiple issues with that:
- creating multiple different sorts of objects in single REST call is not the normal paradigm, and introduces a nonzero amount of complexity from a partial creation standpoint (and needing to unroll the transaction)
- creating multiple different objects (inventory, group, hosts) and then deleting them for each job is a much more problematic workflow to optimize than "a slow filter query"

Mostly, this stems from a usage model of using the platform/API not as a mechanism to run defined sets of automation on a defined set of inventory, but instead as a command blaster to arbitrary hosts repeatedly. It's not what it's designed for.

**Comment by agilleyrh** [comment] 2021-09-03 02:51
Where do we stand on this request?

**Comment by ffirg** [comment] 2022-02-15 10:32
We are not going to implement this. The arguments for and against this idea are well documented above. Given it's not taken off to date and there isn't a great deal of demand for this feature, to save it hanging around, I'm closing it. Doing large scale inventory management should be done via other mechanisms - SCM etc. Implementing this idea could also introduce licensing questions and inventory mismanagement on a grand scale.

**Closed as completed by ffirg** 2022-02-15 10:32 UTC
Labels: type:enhancement, component:api

**Comment by lotaris-xx** [comment] 2022-02-15 13:47
I understand, although given the new licensing methodology for AAP (total hosts automated), that piece no longer applies. I'll reach out to the TAM for the main customer that requested to this to let them know it won't be added. Now that we've generally solved the perf issues around thousands of instances of a single job differing only in the single-host inventory created before and then destroyed after the job run, this isn't needed anymore.

**Comment by stoleas** [comment] 2022-04-06 13:19
A very large FSI customer referred me to this issue mid-2021 as something that they wish they had. I'm also working with another large institution who referred me here on 4/5/2022 as their orchestration engine will need this capability.
