### ISSUE TITLE
[RFE] "order: inventory" and "reverse_inventory" does not effect in AWX / Tower

### ISSUE THREAD

**Issue by saito-hideki** [ansible/awx#2952] opened 2018-12-19 23:25 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Inventory

##### SUMMARY
In order to H/A cluster system configuration, Customer have been using "order: inventory" and "order: reverse_inventory" in their playbook. It works fine with ansible core, but does not effect when they launched their playbook as a job from AWX/Tower.

##### ADDITIONAL INFORMATION
The background of this request as follows:

There are the following servers, and they run proprietary software and the high availability (HA) works such that the flow of replication is fe1 -> fe2 -> be1 -> be2.

- fe1
- fe2
- be1
- be2

In order to perform some maintenance operations, the HA needs to be disabled in reverse order (be2, be1, fe2, fe1) using by `order: reverse_inventory`. When the maintenance phase can then be performed on all hosts.
Then, HA needs to be enabled in forward order (fe1 -> fe2 -> be1 -> be2) using by`order: inventory`.

**Comment by rocklob** [comment] 2019-01-02 15:53
The issue is NOT that `order: inventory` and `order: reverse_inventory` do not work.  The main issue is that hosts added to an inventory in Ansible Tower are automatically sorted by hostname.  When the order of the hosts matters (such as when using the `order:` keyword), this is a problem. Contrast this to Ansible Core where hosts in inventory files exist in the order specified by the author of the inventory.  

As such, the enhancement request here is to allow Ansible Tower inventories to have hosts listed in the order specified by the user.  This would involve an option to disable the automatic sorting and perhaps a way to allow the user to drag hosts to reorder them within the inventory.

I think a better name for this issue would be "Allow users to specify order of hosts in an inventory."

**Comment by rocklob** [comment] 2019-01-02 15:59
Here is some additional background to a specific use case to help explain this issue better:

We have a set of servers; let's call them hq1, hq2, dr1, and dr2.  They run proprietary software and the high availability (HA) works such that the flow of replication is hq1 -> hq2 -> dr1 -> dr2.  In order to perform some maintenance operations, the HA needs to be disabled in reverse order (dr2, dr1, hq2, h1); this is where I want to use a play with `order: reverse_inventory`.  The maintenance can then be performed on all hosts.  Finally, HA needs to be enabled in forward order (hq1, hq2, dr1, dr2); this is where I want to use a play with `order: inventory` (the default).

When I create the inventory in Tower, the hosts get lexically ordered as dr1, dr2, hq1, hq2, which prevents the playbook from working as intended.

**Comment by AlanCoding** [comment] 2019-01-08 15:41
> The main issue is that hosts added to an inventory in Ansible Tower are automatically sorted by hostname.

Seems to be a duplicate issue with linked issue?

**Comment by ryanpetrello** [comment] 2019-01-22 17:29
Duplicate of https://github.com/ansible/awx/issues/2980

**Closed as completed by ryanpetrello** 2019-01-22 17:29 UTC
