### ISSUE TITLE
AWX 18.0.0: Inventory Source from a Project not work

### ISSUE THREAD

**Issue by kladiv** [ansible/awx#9704] opened 2021-03-25 15:31 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory Source from a Project seems not work in AWX 18.0.0

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: AWX Operator
* Operating System: Ubuntu 20.04 + k3s v1.20.0+k3s2 (Kubernetes)
* EE: Default EE (built-in in AWX 18.0.0)

##### STEPS TO REPRODUCE

1. Add an SCM Project in AWX + sync the project
2. Add an Inventory in AWX
3. Add Inventory Source (Source from a Project type) and set Inventory file field to `hosts` or `hosts.yml`
4. Run sync

##### EXPECTED RESULTS

Inventory Sourced from a Project correctly works, as in 17.1.0

##### ACTUAL RESULTS

```
ansible-inventory [core 2.11.0b2.post0] 
  config file = /tmp/pdd_wrapper_216_g6ozu0ty/awx_216_8ectkurh/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/tmp/pdd_wrapper_216_g6ozu0ty/awx_216_8ectkurh/project/collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
Using /tmp/pdd_wrapper_216_g6ozu0ty/awx_216_8ectkurh/project/ansible.cfg as config file
host_list declined parsing /runner/project/hosts.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /runner/project/hosts.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /runner/project/hosts.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /runner/project/hosts.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /runner/project/hosts.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /runner/project/hosts.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /runner/project/hosts.yml as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

##### ADDITIONAL INFORMATION

I checked inside `awx-ee` Pod's container and in private-data-dir (e.g. /tmp/pdd_wrapper_216_g6ozu0ty/awx_216_8ectkurh/) i found a file called `args` with content below:

```
bash-4.4$ more /tmp/pdd_wrapper_216_g6ozu0ty/awx_216_8ectkurh/args
ansible-inventory --list --export -i /runner/project/hosts.yml --output /runner/artifacts/output.json --playbook-dir /runner/project -vvvvv
```

It seems wrong 'cause it refers to /runner directory but all project and execution files are placed in /tmp/pdd_wrapper_[...] directories

I dunno if problem is related to all hardcoded /runner os.path in file [https://github.com/ansible/awx/blob/9a61c4368784c421e47551e4175020ced116f56e/awx/main/tasks.py](https://github.com/ansible/awx/blob/9a61c4368784c421e47551e4175020ced116f56e/awx/main/tasks.py#L2521)

At the moment Inventory Source from Project seems unusable in AWX 18.0.0.

I hope this can be analized soon.
Thank you

**Comment by shanemcd** [comment] 2021-03-25 16:21
cc @AlanCoding

**Comment by kdelee** [comment] 2021-03-25 16:46
@yagomarques could you try and reproduce this? Ping me if you need help

**Comment by shanemcd** [comment] 2021-03-25 16:47
Since we are not seeing this in our nightly tests, this might be specific to running in k8s.

**Comment by MaximilianMeister** [comment] 2021-03-25 16:50
> Since we are not seeing this in our nightly tests, this might be specific to running in k8s.

:+1: Same issue here, and yes, it's in Kubernetes

**Comment by ManuelPerrot** [comment] 2021-03-25 16:55
Same issue here using Kubernetes.
It checks in `/runner/project/inventory/`
While the project is actually in `/var/lib/awx/projects/`

**Comment by gmarsay** [comment] 2021-03-25 17:44
Same issue here using Kubernetes.

**Comment by shanemcd** [comment] 2021-03-25 20:59
Hi all. I've recreated the issue and I'm looking at it now.

**Comment by balonik** [comment] 2021-03-26 08:10
I am not sure if it's related, but I am not able to run any Job in Kubernetes deployment.
All jobs fail with

```
[WARNING]:  * Failed to parse /tmp/tmp7c5j7zmg/inventory/hosts with script
plugin: Unable to retrieve file contents Could not find or access
'/runner/tmp9oqcyaz1' on the Ansible Controller. If you are using a module and
expect the file to exist on the remote, see the remote_src option
[WARNING]:  * Failed to parse /tmp/tmp7c5j7zmg/inventory/hosts with yaml
plugin: Unable to retrieve file contents Could not find or access
'/runner/tmp9oqcyaz1' on the Ansible Controller. If you are using a module and
expect the file to exist on the remote, see the remote_src option
[WARNING]:  * Failed to parse /tmp/tmp7c5j7zmg/inventory/hosts with ini plugin:
Unable to retrieve file contents Could not find or access '/runner/tmp9oqcyaz1'
on the Ansible Controller. If you are using a module and expect the file to
exist on the remote, see the remote_src option
[WARNING]: Unable to parse /tmp/tmp7c5j7zmg/inventory/hosts as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by gauravshankarcan** [comment] 2021-03-27 18:57
cant seem to use this feature

**Comment by larueli** [comment] 2021-03-29 13:55
Same issue, you have to set the full path to your project inventory using the inventory source API.

More info here  : https://github.com/ansible/awx/issues/9701#issuecomment-808885957

**Comment by dimatha** [comment] 2021-03-29 20:31
Similar issue when using VMware inventory. Running in K8s via operator. Version 18.0.0. The command runs just fine in the container isolated dir (and the env vars are set accordingly from the json payload):

/tmp/pdd_wrapper_33_b65zji3y/awx_33_zi5340pu$ ansible-inventory -i ./vmware_vm_inventory.yml  --graph -vvvv

The error when triggered from the UI:

`ansible-inventory [core 2.11.0b3.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /runner/vmware_vm_inventory.yml as it did not pass its verify_file() method`

**Comment by minyor** [comment] 2021-04-05 09:43
Can someone share an instructions as to how to install AWX 17.1.0 through operator or sources, docker or any method really, so that one can install stable bug-less version of AWX and use it, whilest latest is being fixed?
Help please?
I would really appreciate it..

**Comment by dsmaugy** [comment] 2021-04-07 16:10
> Same issue, you have to set the full path to your project inventory using the inventory source API.
> 
> More info here : [#9701 (comment)](https://github.com/ansible/awx/issues/9701#issuecomment-808885957)

Doing this allows me to create the inventory source, but it seems like running any job on that inventory still fails:
```
SSH password: 
[WARNING]:  * Failed to parse /tmp/tmp3cqwergz/inventory/hosts with script
plugin: Unable to retrieve file contents Could not find or access
'/runner/tmpcrksr8lp' on the Ansible Controller. If you are using a module and
expect the file to exist on the remote, see the remote_src option
[WARNING]:  * Failed to parse /tmp/tmp3cqwergz/inventory/hosts with yaml
plugin: Unable to retrieve file contents Could not find or access
'/runner/tmpcrksr8lp' on the Ansible Controller. If you are using a module and
expect the file to exist on the remote, see the remote_src option
[WARNING]:  * Failed to parse /tmp/tmp3cqwergz/inventory/hosts with ini plugin:
Unable to retrieve file contents Could not find or access '/runner/tmpcrksr8lp'
```

Looks like [@balonik ](https://github.com/ansible/awx/issues/9704#issuecomment-808024403) came across the same problem.

**Comment by shanemcd** [comment] 2021-04-07 22:49
This should be fixed in AWX 19.

**Closed as completed by shanemcd** 2021-04-07 22:49 UTC
Labels: type:bug, component:api

**Comment by minyor** [comment] 2021-04-08 11:45
> This should be fixed in AWX 19.

Can you please advise, how to install AWX 19?

I used these instructions when installed version 18:
https://github.com/ansible/awx/blob/devel/INSTALL.md

And now, when I execute:
`minikube kubectl apply -- -f awx.yml`
gives: `awx.awx.ansible.com/awx unchanged`

**Comment by minyor** [comment] 2021-04-08 11:49
`minikube kubectl -- apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml`
Also gives:
```
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com configured
clusterrole.rbac.authorization.k8s.io/awx-operator configured
clusterrolebinding.rbac.authorization.k8s.io/awx-operator unchanged
serviceaccount/awx-operator unchanged
deployment.apps/awx-operator configured
```
How to update this thing?

P.S. Thank you in advance for any help!

**Comment by minyor** [comment] 2021-04-09 08:50
Ok, did not found a way to update AWX, instead was trying to delete 18 version and install anew.
But it also was not as simple as it seems,.. Simple, if you know how.
Tried to
```
minikube kubectl delete pod ...
minikube kubectl delete ...
```
Finally what's worked is just:
`minikube delete`

**Comment by AntonOlsen** [comment] 2021-04-09 20:48
Has anyone got this to work? I'm trying to upgrade from an ancient AWX and not having any luck adding my hosts.yml inventory file from a project.

hosts.yml exists in the root of the project, doesn't show in the drop down, attempts to type it into the field get reset to .gitignore when I save.

**Comment by dperez-sct** [comment] 2021-04-09 20:56
> Has anyone got this to work? I'm trying to upgrade from an ancient AWX and not having any luck adding my hosts.yml inventory file from a project.
> 
> hosts.yml exists in the root of the project, doesn't show in the drop down, attempts to type it into the field get reset to .gitignore when I save.

Remove the ".yml" from the hosts and try again. I sync inventory with a "hosts" file only.






> Ok, did not found a way to update AWX, instead was trying to delete 18 version and install anew.
> But it also was not as simple as it seems,.. Simple, if you know how.
> Tried to
> 
> ```
> minikube kubectl delete pod ...
> minikube kubectl delete ...
> ```
> 
> Finally what's worked is just:
> `minikube delete`

Try setting the variable tower_image to quay.io/ansible/awx:19.0.0

If not work, try updating awx-operator first to 0.8.0

**Comment by maveleo** [comment] 2022-01-10 17:13
Same issue is affecting tower quay.io/ansible/awx:19.4.0 and I cannot test in 19.5.0 either as in that version all of my jobs will stay as pending. 
As anyone got this working with any 19.x ?

**Comment by maveleo** [comment] 2022-01-14 12:36
> This should be fixed in AWX 19.

I can confirm the issue has not being fixed in 19.4

**Comment by sebypp** [comment] 2022-03-02 11:06
I'm experiencing the same issue for AWX 20.0.0.

**Comment by ffirg** [comment] 2022-03-02 16:19
Works for me using 20.0.0 
My SCM hosts file is the traditional ini style though. Imports, loads groups etc

**Comment by sebypp** [comment] 2022-03-08 15:28
@ffirg , you are correct, it works on 20.0.0.

My issue was the '---' character in my netbox inventory file. Strangely enough, when executing ansible via CLI it worked fine, but not with AWX. I've fixed this and can confirm everything is working.

**Comment by ideyedi** [comment] 2022-04-25 06:16
@sebypp , 
Did you add or delete the '---' character from your inventory?

**Comment by sebypp** [comment] 2022-07-03 13:24
I've deleted it. 

> @sebypp , 
> 
> Did you add or delete the '---' character from your inventory?
