### ISSUE TITLE
Inventory sourced from project with git submodules

### ISSUE THREAD

**Issue by digifuchsi** [ansible/awx#7900] opened 2020-08-13 15:06 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When sourcing an inventory from a project using git submodules only top git repository submodules are loaded.
If a git submodule includes another git submodule this is ignored.

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.11
* Operating System: CentOS7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Create a GIT repository (1) with an inventory.yml including another GIT repository (2) as a subfolder via git submodules.
In this GIT repository (2) include an inventory2.yml with another GIT repository (3) as a subfolder via git submodules.
In this GIT repository (3) include an inventory3.yml.

You should have the following structure:
```
|- .gitmodules
|- inventory.yml
|- inv2
   |- .gitmodules
   |- inventory2.yml
   |- inv3
      |- inventory3.yml
```

##### EXPECTED RESULTS
When sourcing an inventory from this project using `/ (project root)` as Inventory file I would expect that all three inventory.yml files are loaded.

##### ACTUAL RESULTS
inventory3.yml is not loaded because the directory inv3 is empty.

The inventory job is throwing the warning message:
`[WARNING]: Unable to parse /tmp/awx_27_un9j3oyb/project/inv2/inv3 as an inventory source`

##### ADDITIONAL INFORMATION
The project directory in the awx_task container (/usr/lib/awx/projects) seems to have the inventory3.yml. Just the tmp folder of the Inventory Sync Job does not contain the file.

**Comment by blomquisg** [comment] 2020-08-21 17:14
@AlanCoding are nested submodules something you'd expect to work with the current implementation?  Or something that would have to be added?

**Comment by AlanCoding** [comment] 2020-08-27 13:25
Sorry for the delay in issue triage lately. I'm going to close this as a duplicate of #5248

There have been some new ideas lately, but I will put further comments in that issue.

**Closed as completed by AlanCoding** 2020-08-27 13:26 UTC
Labels: type:bug, component:api
