### ISSUE TITLE
Should not display smart inventory as part of inventory filter when creating a host

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10469] opened 2021-06-17 21:03 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Show not display smart inventory as part of inventory filter when creating a host. Right now, all inventories are being displayed.  Generating the following error:

![image](https://user-images.githubusercontent.com/9053044/122471964-f1437380-cf8d-11eb-97ff-a0404be04c97.png)

**Comment by mabashian** [comment] 2021-06-18 17:20
Dupe of https://github.com/ansible/awx/issues/10222

**Closed as completed by mabashian** 2021-06-18 17:20 UTC
Labels: component:ui
