### ISSUE TITLE
Optional textarea survey fields not optional when min length > 0

### ISSUE THREAD

**Issue by djj106** [ansible/awx#9176] opened 2021-01-27 14:34 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Text area survey fields that are optional (required checkbox unchecked) are not optional if the minimum length is greater than zero. Upon launching, an error message displays saying the field must be X characters. In versions <= 15.0.1, an optional field with a min length of one could be left blank and the variable would not be defined or set. In 17.0.0, awx attempts to define the variable regardless if the field is optional or not.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a survey with an optional text area field
Set the min length to 1
Attempt to launch the job leaving the survey field blank

##### EXPECTED RESULTS

When min length is greater than zero and the field is optional, the variable should be left undefined when the survey field is blank and the job should launch.

##### ACTUAL RESULTS

Launch fails with a message saying the field must be at least one character.

**Comment by nicosalvadore** [comment] 2021-02-04 16:25
This is also an issue for a `text` input type in a survey.
I have a minimal size of 2, and get an error when launching the template.

survey question editor
![image](https://user-images.githubusercontent.com/12870725/106923027-f2c27c80-670d-11eb-9b2d-01e4bcd2e21b.png)

error
![image](https://user-images.githubusercontent.com/12870725/106922969-e0e0d980-670d-11eb-8e8e-96b438e2c73d.png)

**Comment by MrBones757** [comment] 2021-02-08 00:16
i can confirm that i am seeing this issue also.

**Comment by nicosalvadore** [comment] 2021-02-19 09:22
I'm facing another issue that I think can be related to this one.

I have a job template with a survey that contains optional questions : `required` field not checked.
When I start a new job from this template and this optional field has not been filled, AWX is still passing an empty extra variable to the job process. 
I don't think this was the behaviour I experienced in the previous AWX versions.
![image](https://user-images.githubusercontent.com/12870725/108484607-469b9c80-729c-11eb-994a-6290ba98e07d.png)

**Comment by tiagodread** [comment] 2021-04-08 20:21
> I'm facing another issue that I think can be related to this one.
> 
> I have a job template with a survey that contains optional questions : `required` field not checked.
> When I start a new job from this template and this optional field has not been filled, AWX is still passing an empty extra variable to the job process.
> I don't think this was the behaviour I experienced in the previous AWX versions.
> ![image](https://user-images.githubusercontent.com/12870725/108484607-469b9c80-729c-11eb-994a-6290ba98e07d.png)

Hello @nicosalvadore I think this is a different problem and has more to do with #9525. I tried the same steps as you described in the new UI compared to the old UI and the difference between them is that we are not displaying the survey variable on the **preview step** before the JT launch, but we do show on the job details.

Old UI:

![chrome-capture (1)](https://user-images.githubusercontent.com/12464858/114090984-7a537580-988e-11eb-9ce0-7fc4d28739f4.gif)

New UI:

![chrome-capture (2)](https://user-images.githubusercontent.com/12464858/114090987-7b84a280-988e-11eb-927c-1741ff89cb08.gif)

@kmo @jakemcdermott when the survey is optional should we display it on the preview step for the new UI as used to be in the old one?

**Comment by jakemcdermott** [comment] 2021-04-08 20:24
> when the survey is optional should we display it on the preview step for the new UI as used to be in the old one?

yes

**Comment by nicosalvadore** [comment] 2021-04-09 14:37
@tiagodread 
Thanks for your answer, the issue is indeed the one reported in #9525.
My "default var" is in the default/main.yml file in my case, but this is the same behaviour.

**Comment by tiagodread** [comment] 2021-04-09 18:33
The fix for the original issue landed on devel, the issue related to the survey preview should be adressed as part of #9525

**Closed as completed by tiagodread** 2021-04-09 18:33 UTC
Labels: type:bug, component:ui, flag:community
