### ISSUE TITLE
Form error strings from API look unstyled, mismatch other form errors

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7822] opened 2020-08-04 19:44 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Check out this error string:
<img width="1097" alt="Screen Shot 2020-08-04 at 3 36 39 PM" src="https://user-images.githubusercontent.com/9889020/89337111-6fde3d80-d668-11ea-99aa-e45b05619532.png">

compared to this one:
<img width="483" alt="Screen Shot 2020-08-04 at 3 36 50 PM" src="https://user-images.githubusercontent.com/9889020/89337131-75d41e80-d668-11ea-9a83-4b2d12f3c521.png">

The problem is that the value for the `helperTextInvalid` prop that we're passing in the first screenshot is actually an _array_ of strings like: `["some error"]`.  In the second screenshot it's just a string `This field must not be blank.`.  The reason for this is because when we pass the errors to formik to update it's internal form state: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/FormField/FormSubmitError.jsx#L19 we're passing the API's response straight through.  The API provides an array of errors for any given field since some fields could have more than one error.

In order to fix this, I think the best course of action is to write a small converter component that will need to get injected everywhere that we use the `helperTextInvalid` prop.  This component would take the error in and check to see whether or not it's a string or array of strings.  If it's a string it should render normally.  If it's an array it should iterate over that array and render each error on a new line.

`helperTextInvalid={<CustomInvalidHelperText error={meta.error} />}` (thanks @marshmalien)

Alternatively/Additionally we can see if PF would be willing to alter that prop a little bit to handle an array of strings for us.  If this were the case then no changes would be needed on our end.

**Comment by mabashian** [comment] 2020-08-04 20:36
Link to upstream PF issue: https://github.com/patternfly/patternfly-react/issues/4653 (in case they're interested in supporting this).

**Comment by unlikelyzero** [comment] 2020-09-23 20:01
@mabashian is this a dupe of https://github.com/ansible/awx/issues/7562

**Comment by keithjgrant** [comment] 2020-10-08 16:17
This happens when we give the error to the PatternFly form field as an array instead of a string (`['Invalid URL: Missing url scheme (http, https, etc.)']`), which is how the API often returns errors. My refactor of error handling in #8339 now addresses this

**Comment by unlikelyzero** [comment] 2020-10-25 15:26
Need to add visual coverage for this exact spot in credential form

**Comment by unlikelyzero** [comment] 2020-12-14 13:38
this is covered in credential-errors.spec.js

**Closed as completed by unlikelyzero** 2020-12-14 13:38 UTC
Labels: type:bug, qe:visual
