### ISSUE TITLE
Syncing all sources in parallel leads to missing hosts

### ISSUE THREAD

**Issue by binbashroot** [ansible/awx#5571] opened 2019-12-24 16:37 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Using two completely separate satellite sources with the same "Organization" but different "Locations"  results in AWX only importing some, but not all,  of the hosts into a cumulative inventory.

##### ENVIRONMENT
* AWX version: 9.0.1.0
* AWX install method:  docker on linux
* Ansible version:  2.8.5
* Operating System: RHEL 7
* Web Browser: Chrome 79.0.3945.88 
* Red Hat Satellite 6.6

##### STEPS TO REPRODUCE

1. Inventories - > Add -> Enter Name ->Save -> Sources -> Add first Satellite server with creds using "Red Hat Satellite 6" for source-> Save
2. Inventories -> Select previously created inventory -> Sources -> Add -> Add 2nd Satellite server into source -> Save
3. Select Created Inventory -> Sources -> Click Sync All

"Overwrite, Overwrite Variables, or Update on Launch did not change results.

##### EXPECTED RESULTS
Expected a total of 350 hosts in Inventory.  

##### ACTUAL RESULTS
Total number of hosts ingested was 180.   Cumulative RH Satellite sources results in only a partial number of hosts in the inventory.   If two separate inventories are used each utilizing a separate Satellite server, the correct number of hosts are ingested in the inventory.

**Comment by blomquisg** [comment] 2020-02-28 19:05
@jladdjr check if this is fixed with your inventory plugin work

**Comment by jladdjr** [comment] 2020-02-28 19:57
Just ran through the steps to reproduce and I'm also finding that an inventory w/ two satellite inventory sources doesn't have the number of hosts I'd expect (a simple sum of the number of hosts returned by each inv. source). Digging to see what's going on. Wondering if this issue is specific to foreman or if it's a more general issue w/ awx inventories / inv. sources.

Note: In my testing, I used the new foreman plugin which awx is about to adopt.

**Comment by ryanpetrello** [comment] 2020-04-28 15:24
@elyezer @squidboylan @kdelee is this something any of you and yours have bandwidth to test now that we've merged the plugin?

If it doesn't "just work" in the new plugin, we're unlikely to fix it right now.

cc @blomquisg

**Comment by jladdjr** [comment] 2020-05-06 18:42
Got side-tracked, poking at this now.

**Comment by jladdjr** [comment] 2020-05-06 20:43
I believe I'm able to reproduce this. Followed steps given in description and found that an inv source with  59 hosts and another one with 971 yielded an inventory that reported a total of 1023 hosts (instead of 1030).

I got a list of hosts from each inv. source and, sure enough, found seven ids present in both list. When I look for the associated hostnames of the instances, I can only find them listed in one satellite instance. I think this rules out the possibility that the inventory found duplicate hosts shared by the two sat instances.

The fact that:
* seven hosts are missing from the total
* the list of host id's shows seven overlapping ids
* but these id's point to hosts only present on a single sat6 host

.. leads me to think that there's a race condition in awx when hosts are being created.

**Comment by jladdjr** [comment] 2020-05-06 20:48
While I haven't confirmed this, my guess would be that this is not foreman-specific.

**Comment by ryanpetrello** [comment] 2020-05-06 20:59
cc @blomquisg for your awareness, we *suspect* this isn't actually related to the Satellite plugin at all, but may actually just be indicative of a long-standing bug that's likely unrelated to any _recent_ AWX change.  I'm gonna dig into this a bit w/ @jladdjr and see if we find any clues.

**Comment by ryanpetrello** [comment] 2020-05-07 13:51
I can _also_ reproduce this, and I agree that this probably isn't specific to the sat6 inventory plugin, but is likely a pre-existing bug in AWX itself related to simultaneous inventory syncs.  I tried to reproduce this by making two *distinct* inventories, each pointed at the two sources that @jladdjr has.  Then I ran the distinct syncs individually:

```python
In [6]: for i in Inventory.objects.filter(name__contains='Ryan'): print(i.hosts.count())
60
971
```

Next, I created an inventory that used *both* sources, and I ran the "sync all" (and saw the same behavior as @jladdjr).

If I had to guess, there's a bug hiding somewhere down in the hairy, hairy depths of `inventory_import.py`.

```python
In [12]: for i in Inventory.objects.filter(name__contains='Ryan'): print(i.hosts.count())
60
971
1024
```

**Comment by jladdjr** [comment] 2020-05-13 17:45
I've been off dueling other satellite issues. Picking this back up.

**Comment by jladdjr** [comment] 2020-05-19 19:30
It looks like we've known this was possible for a while - [here](https://github.com/ansible/awx/blob/devel/awx/main/management/commands/inventory_import.py#L384-L385)'s a comment from forever ago:

> FIXME: Wait or raise error if inventory is being updated by another source.

I've been poking at inventory_import with @AlanCoding and noticed that we're:
* reading the current state of the inventory (https://github.com/ansible/awx/blob/devel/awx/main/management/commands/inventory_import.py#L998)
* .. well before we create an advisory lock on the inventory (https://github.com/ansible/awx/blob/devel/awx/main/management/commands/inventory_import.py#L1071, https://github.com/ansible/awx/blob/devel/awx/main/management/commands/inventory_import.py#L874)

which ~seems like it would make it possible for~ guarantees this scenario:
* Sync 1 gets a snapshot of the inventory
* Sync 2 gets a snapshot of the inventory
* Sync 1 gets lock and applies update to inventory
* Sync 2 gets lock and applies update to _old_ inventory, as it was before Sync 1

In fact, I think @AlanCoding is correct in putting it more strongly:

> with the sync all, this basically _guarantees_ that it'll have an initial state from before the other sync [my emphasis]

**Comment by jladdjr** [comment] 2020-05-19 19:37
When we added the advisory lock, we needed to make sure that we read in the current state of the inventory _after_ we got the lock:
https://github.com/ansible/awx/pull/3529

**Comment by jladdjr** [comment] 2020-05-19 22:05
Thought https://github.com/ansible/awx/pull/7090 might fix the issue, but I'm still seeing missing hosts even when we force inv. updates to happen serially. Doing some more digging.

**Comment by ryanpetrello** [comment] 2020-10-13 13:01
@AlanCoding @jladdjr @elyezer @elyezer I've put this into `needs_test`, and we're merging https://github.com/ansible/awx/pull/7090, which fixes **this issue** and _also_ fixes https://github.com/ansible/tower/issues/4576

**Comment by one-t** [comment] 2020-10-28 16:02
Verified concurrently with #4576

**Closed as completed by one-t** 2020-10-28 16:02 UTC
Labels: type:bug, component:api
