### ISSUE TITLE
[ui_next] Unable to add multiple custom credential type's credential to job template

### ISSUE THREAD

**Issue by weixiangkoh** [ansible/awx#8878] opened 2020-12-13 14:13 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

New UI Unable to add multiple custom credential to a job template.
steps involved

##### ENVIRONMENT
* AWX version: AWX 16.0.0 
* AWX install method: Kubernetes
* Ansible version:  2.9.15
* Operating System: Centos 8
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Select custom credential type A in job template
- Select custom credential type B in job template - custom credential type A is replaced by type B

##### EXPECTED RESULTS

Both custom credentials are added to job template

##### ACTUAL RESULTS
only latest selected credential is added

![image](https://user-images.githubusercontent.com/56986673/102014312-42c93680-3d90-11eb-8525-e6c9337f563c.png)

**Comment by jakemcdermott** [comment] 2020-12-14 15:15
Hello @weixiangkoh. Thanks for creating this issue. I've opened a pr to address this bug: https://github.com/ansible/awx/pull/8887

This will be fixed for the next AWX community release.

**Comment by weixiangkoh** [comment] 2021-01-06 09:22
> Hello @weixiangkoh. Thanks for creating this issue. I've opened a pr to address this bug: #8887
> 
> This will be fixed for the next AWX community release.

May i know if this has been fixed on the latest update?

**Comment by maksym-bordun-ynd** [comment] 2021-01-27 16:47
@jakemcdermott the issue can still be reproduced even after upgrading from 16.0.0 to 17.0.1. 

Repro steps: 

1. Launch a template, which prompts for credentials on launch
2. Select first credential of custom credential type
3. Select second credential of another custom credential type
4. Observe that a credential selected in step 2 is replaced by credential from step 3

**Comment by dsmaugy** [comment] 2021-01-27 23:08
> @jakemcdermott the issue can still be reproduced even after upgrading from 16.0.0 to 17.0.1.
> 
> Repro steps:
> 
> 1. Launch a template, which prompts for credentials on launch
> 2. Select first credential of custom credential type
> 3. Select second credential of another custom credential type
> 4. Observe that a credential selected in step 2 is replaced by credential from step 3

Have you tried downgrading to 17.0.0? I'm on that version and it works for me

**Comment by maksym-bordun-ynd** [comment] 2021-01-28 09:09
@dsmaugy hmm, haven't tried that yet. Are you sure you are actually launching a template, not just editing it's settings?

**Comment by dsmaugy** [comment] 2021-01-28 15:58
@maksym-bordun-ynd Oh nevermind ;), I misread your first comment. This issue is still present on 17.0.0 when selecting credentials upon launch

**Comment by jakemcdermott** [comment] 2021-02-01 14:20
Thanks, I'll take a look. IIRC I fixed this specifically for the job template form. It's likely a similar variant of the bug exists for the launch prompt.

**Comment by mabashian** [comment] 2021-03-04 21:03
@jakemcdermott whats the status of this?  Does it need to be tested?

**Comment by unlikelyzero** [comment] 2021-03-08 16:46
This was tested without QE and we will need to verify:
1. Unit test coverage
2. Testability
3. Stubs
4. Visual test for Many Credentials added to a JT

**Comment by akus062381** [comment] 2021-03-18 20:58
One unit test is existing
Stubs are present
Testability verified

**Comment by akus062381** [comment] 2021-03-18 20:58
Still need: visual test for Many Credentials added to a JT

**Closed as completed** 2021-03-26 13:41 UTC
Labels: type:bug, component:ui, flag:community
