### ISSUE TITLE
Cleanup multiple jobs at once

### ISSUE THREAD

**Issue by daemenseth** [ansible/awx#4134] opened 2019-06-21 07:35 UTC
##### ISSUE TYPE
 - Feature Idea
In the job windows you can filter on jobs.
But it would be nice if you could delete multiple job result at once

**Comment by ryanpetrello** [comment] 2019-06-21 17:25
Duplicate of https://github.com/ansible/awx/issues/19

**Closed as completed by ryanpetrello** 2019-06-21 17:25 UTC
