### ISSUE TITLE
JOBS execution screen doesn’t show updates from status and tasks automatically on the UI

### ISSUE THREAD

**Issue by irwimscott** [ansible/awx#437] opened 2017-10-16 04:19 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

To see the current job status, the execution steps and the real elapsed time, users must reload the webpage manually. AWX should provide these job informations update on the fly to the UI.

##### ENVIRONMENT
* AWX version:  1.0.1.31
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.0
* Operating System: VirtualBox 5.2.26 - Centos 7 (AWX using official github installation guide)
* Web Browser: MacOS Sierra --> Google ChromeVersion 61.0.3163.100 (Official Build) (64-bit) and Safari Version 11.0 (12604.1.38.1.7)

##### STEPS TO REPRODUCE

1 - Create a job template.
2 - Go to the JOBS view.
3 - Choose it on the list.
4 - Click in the launch/Relaunch(Rocket) button.
5 - The status of the execution will modify to "PENDING" status and it will not be updated any more. 
6 - Reload the webpage and verify the new job status and the tasks log.

##### EXPECTED RESULTS

After launch/Relaunch the Job, the job status view must load all the new job informations automatically. Users wants to see the job changes and its status on the fly. (Like Jenkins Console screen, for example).

##### ACTUAL RESULTS

Users must reload the JOB webpage manually to be able to see the real job status and task logs.

##### ADDITIONAL INFORMATION

Screen Recorder of this issue:

https://youtu.be/gB8X2VSf5XE

**Comment by matburt** [comment] 2017-10-16 12:23
I've noticed this too and it's a major issue... something seems to be happening with the websocket interface on the awx side.  What I have heard is that it can be fixed by stopping and restarting the web container. Can you confirm if that works for you?

**Comment by VenkateshLoganathan** [comment] 2017-10-25 06:59
The same issue persist when the AWX_Web running behind the Nginx Proxy. I'm using the AWX_Version  1.0.0

**Comment by jerrac** [comment] 2017-11-03 19:02
I'm on the devel branch. The various job pages do not auto update for me either.

Restarting the web container did not help.

**Comment by VenkateshLoganathan** [comment] 2017-11-03 23:42
When can I expect the issue to be close?


Regards,
Venkatesh.L

On Nov 4, 2017 00:33, "David Reagan" <notifications@github.com> wrote:

I'm on the devel branch. The various job pages do not auto update for me
either.

Restarting the web container did not help.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ansible/awx/issues/437#issuecomment-341797774>, or mute
the thread

**Comment by matburt** [comment] 2017-11-06 17:07
> When can I expect the issue to be close?

When this bug is fixed

**Comment by xoxys** [comment] 2018-01-10 14:20
Seems to be fixed in 1.0.2.0, right?

**Comment by colandre** [comment] 2018-01-10 14:34
@xoxys, I updated AWX to 1.0.2.0 today and it looks the issue is fixed.

**Closed as completed** 2018-01-26 13:48 UTC
Labels: type:bug, component:api, component:ui
