### ISSUE TITLE
Unable to view notification template in UI

### ISSUE THREAD

**Issue by dsmaugy** [ansible/awx#10435] opened 2021-06-11 19:44 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I am trying to create a webhook notification template. When I first created the notification template, I was greeted with a blank screen and these javascript errors:

```
worker-json.js:1 GET https://my-awx-url.com/worker-json.js 404

react-dom.production.min.js:209 TypeError: console.warning is not a function
    at Ec (CodeEditor.jsx:88)
    at Zo (react-dom.production.min.js:153)
    at Ss (react-dom.production.min.js:261)
    at vl (react-dom.production.min.js:246)
    at ml (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vi (react-dom.production.min.js:122)
    at Yi (react-dom.production.min.js:123)

asyncToGenerator.js:6 Uncaught (in promise) TypeError: console.warning is not a function
    at Ec (CodeEditor.jsx:88)
    at Zo (react-dom.production.min.js:153)
    at Ss (react-dom.production.min.js:261)
    at vl (react-dom.production.min.js:246)
    at ml (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vi (react-dom.production.min.js:122)
    at Yi (react-dom.production.min.js:123)

useWebsocket.js:20 WebSocket is already in CLOSING or CLOSED state.
```
If I go back to my AWX homepage and go to the notifications screen however, I see that the template has still been created. I can edit the template fine, but if I try and click the template: `#/notification_templates/1/details`, I get the same results from above.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: kubernetes
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Add a new notification template and fill out all required fields (I am working with webhook notifications but it seems this problem persists across all notification types)
2. Press "save" on the create notification template screen

##### EXPECTED RESULTS

The notification template to be created and for me to be redirected to its page successfully (e.g. `#/notification_templates/1/details`)

##### ACTUAL RESULTS

I get a blank screen and the javascript errors mentioned above.

**Comment by mabashian** [comment] 2021-06-14 13:50
This _could_ be a dupe of https://github.com/ansible/awx/issues/10192 but lets take a look and see.

**Comment by mabashian** [comment] 2021-06-17 17:40
Disregard my previous comment.  This should be fixed by https://github.com/ansible/awx/pull/10150.  Please try again with 19.2.0 and reopen if you're still having trouble.  If you do still see this in 19.2.0 it may help to know what sorts of data you're entering into each field so that we can try to reproduce this exactly.

**Closed as completed by mabashian** 2021-06-17 17:40 UTC
Labels: type:bug, component:ui
