### ISSUE TITLE
AWX cli export/import feature

### ISSUE THREAD

**Issue by mrwiora** [ansible/awx#4863] opened 2019-10-01 13:21 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I have to setup my awx towers automated by scripts - while I was using tower-cli up to version 6.0.1....
As tower-cli has been replaced by the integrated awx cli (what makes sense IMHO), I am missing a backup/restore option. At least I was unable to find any documentation/parameter to do so.

Did I miss something or is this not implemented yet and subject to be changed? And idea would be to execute all possible combinations of parameters to export the data and to import the relevant/filled ones.

Cheers and thanks,
Matthias

**Comment by ryanpetrello** [comment] 2019-10-01 13:42
Hey @mwiora,

Implementing something like `tower-cli`'s backup/restore functionality is on our list; it's just a huge undertaking and we haven't gotten to it yet 😄.

In the meantime, `tower-cli` isn't _going_ anywhere - we're just not planning on updating it going forward beyond glaring issues (all new functionality will go in the new official AWX CLI).

**Comment by mrwiora** [comment] 2019-10-01 13:55
the point is that we currently have issues on restoring objects (especially credentials and jobs) as mentioned in #4703 Otherwise I would leave it as it is.... 
Already with version 6.0.1 there is an api change that has not yet been implemented (importing credentials did not work any longer). So actually for a full automation solution at least - we - have to move to awx cli asap. I'll try to make first steps using dedicated commands and maybe I can help you with the ex-/import feature ;) Are there any first steps done?

**Comment by ryanpetrello** [comment] 2019-10-01 14:30
> Are there any first steps done?

@mwiora we haven't started working on this feature yet.

**Comment by mrwiora** [comment] 2019-10-01 14:49
ok - thx!

**Comment by ryanpetrello** [comment] 2020-02-20 22:27
Duplicate of https://github.com/ansible/awx/issues/5146

**Closed as completed by ryanpetrello** 2020-02-20 22:27 UTC
Labels: type:enhancement, component:api
