### ISSUE TITLE
The documentation for the lookup plugin, awx.awx.controller_api, was malformed.

### ISSUE THREAD

**Issue by ChandlerSwift** [ansible/awx#10855] opened 2021-08-10 19:23 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Docs

##### SUMMARY
When visiting https://docs.ansible.com/ansible/latest/collections/awx/awx/controller_api_lookup.html, I see the message
> The documentation for the lookup plugin, awx.awx.controller_api, was malformed.
> The errors were:
>    ``` 15 validation errors for PluginDocSchema
>    doc -> options -> host -> env -> 1 -> deprecated -> removed_from_collection
>      field required (type=value_error.missing)
>    doc -> options -> host -> env -> 1 -> deprecated -> why
>      field required (type=value_error.missing)
>    doc -> options -> host -> env -> 1 -> deprecated -> __root__
>      One of `removed_at_date` or `removed_in` must be specified (type=value_error)
>    doc -> options -> oauth_token -> env -> 1 -> deprecated -> removed_from_collection
>      field required (type=value_error.missing)
>    doc -> options -> oauth_token -> env -> 1 -> deprecated -> why
>      field required (type=value_error.missing)
>    doc -> options -> oauth_token -> env -> 1 -> deprecated -> __root__
>      One of `removed_at_date` or `removed_in` must be specified (type=value_error)
>    doc -> options -> password -> env -> 1 -> deprecated -> removed_from_collection
>      field required (type=value_error.missing)
>    doc -> options -> password -> env -> 1 -> deprecated -> why
>      field required (type=value_error.missing)
>    doc -> options -> password -> env -> 1 -> deprecated -> __root__
>      One of `removed_at_date` or `removed_in` must be specified (type=value_error)
>    doc -> options -> username -> env -> 1 -> deprecated -> removed_from_collection
>      field required (type=value_error.missing)
>    doc -> options -> username -> env -> 1 -> deprecated -> why
>      field required (type=value_error.missing)
>    doc -> options -> username -> env -> 1 -> deprecated -> __root__
>      One of `removed_at_date` or `removed_in` must be specified (type=value_error)
>    doc -> options -> verify_ssl -> env -> 1 -> deprecated -> removed_from_collection
>      field required (type=value_error.missing)
>    doc -> options -> verify_ssl -> env -> 1 -> deprecated -> why
>      field required (type=value_error.missing)
>    doc -> options -> verify_ssl -> env -> 1 -> deprecated -> __root__
>      One of `removed_at_date` or `removed_in` must be specified (type=value_error)
> ```
and am told to open an issue here.

**Comment by beeankha** [comment] 2021-08-10 19:49
Hi @ChandlerSwift , there's [a PR](https://github.com/ansible/awx/pull/10807) that _hopefully_ fixes this but I need to dig into how to implement this into the live version of the docs. Another related issue has been filed here: https://github.com/ansible/awx/issues/10776

**Comment by sean-m-sullivan** [comment] 2021-11-10 18:12
I just tested this via the docuementation page of an automation hub and this looks fixed, but its not fixed on the web https://docs.ansible.com/ansible/latest/collections/awx/awx/controller_api_lookup.html

**Comment by sean-m-sullivan** [comment] 2021-11-10 19:09
This seems related to #10776

**Comment by felixfontein** [comment] 2022-01-24 21:02
The errors are caused by the same docs fragment, and should also be fixed by #11599 + what I mentioned there in the comments.

**Comment by isuftin** [comment] 2022-02-02 23:00
While this is being worked out, is there anywhere we can get a PDF or a working link to this piece of the documentation?

**Comment by felixfontein** [comment] 2022-02-03 06:01
If you have the collection installed locally, you can always run `ansible-doc -t lookup awx.awx.controller_api` to look at a text version.

**Comment by isuftin** [comment] 2022-02-03 16:59
Perfect

**Comment by AlanCoding** [comment] 2023-09-29 15:05
resolved

**Closed as completed by AlanCoding** 2023-09-29 15:05 UTC
Labels: type:bug, component:awx_collection
