### ISSUE TITLE
Error indication needs to be next to save button on forms.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6669] opened 2020-04-09 19:14 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Simply put, if there is a long form (like the Job Template form) and there is an error on a field out of view, the user only sees a "Save" button that doesn't appear to do anything.

In this screenshot, the name is missing, but the user has no way of seeing it, and the save button doesn't look like it's doing anything either. We should have a message that says "please correct form errors" or something similar next to the button.

![Screenshot_20200409_150913](https://user-images.githubusercontent.com/19942822/78931986-c0f07300-7a74-11ea-908f-1b2f5ac2564d.png)

##### STEPS TO REPRODUCE

1. Make a job template form where the name is missing.
2. Try to click the save button.

**Comment by unlikelyzero** [comment] 2020-12-13 18:27
Still an issue. Bumping in priority because this keeps getting reported in bug bashes

**Comment by mabashian** [comment] 2021-02-04 16:41
Dupe of https://github.com/ansible/awx/issues/8452

**Closed as completed by mabashian** 2021-02-04 16:42 UTC
Labels: type:bug, component:ui, component:ux
