### ISSUE TITLE
Notifications - missing hosts with webhook notification

### ISSUE THREAD

**Issue by kovaxur** [ansible/awx#4541] opened 2019-08-21 09:44 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We have around 400 hosts in the inventory, however, the notification webhook endpoint receives notification about only around 40-50 hosts. (Sometimes it's working fine reporting all the hosts.)

##### ENVIRONMENT
* AWX version: 6.1.0.0 (Same problem with 6.0.0.0)
* AWX install method: docker on linux (official image from docker hub)
* Ansible version:  2.8.2
* Operating System: Centos7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
- Create a webhook notification
- Start a job (or job-flow), enable notifications.

##### EXPECTED RESULTS

Report from all the hosts in JSON format

##### ACTUAL RESULTS

Most of the times only partial host list in the report, sometimes full list. Differs in a job-flow, some jobs reporting about all hosts, some only about a few)

Workflow with 2 jobs:
Number of hosts, on which the job ran (reported in AWX): 438
Number of hosts reported on the webhook script: 53

##### ADDITIONAL INFORMATION

I also have the same problem with 6.0.0.0 and 6.1.0.0
I tried with different users, with standalon jobs or woth flows, also with different playbooks, the problem looks pretty consistent.

Thx

**Comment by ryanpetrello** [comment] 2020-03-13 21:55
This is almost certainly a duplicate of https://github.com/ansible/tower/issues/4176

**Comment by ryanpetrello** [comment] 2020-03-13 21:55
@kovaxur if you're still interested in this, I have a pull request that I suspect may resolve the issue:

https://github.com/ansible/awx/pull/6290

**Comment by ryanpetrello** [comment] 2020-03-13 21:55
For now, I'm going to close this, though, because it's definitely a duplicate.

**Closed as completed by ryanpetrello** 2020-03-13 21:55 UTC
Labels: type:bug, component:api
