### ISSUE TITLE
UI - Credential usage 

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#11492] opened 2021-12-27 10:10 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It would be interesting to identify the job templates using a credential at the credential level
Example : we have the list of job templates of a project at the project level

![awx-ui](https://user-images.githubusercontent.com/29703972/147461432-b75068c6-f2ae-44a9-baff-416680ffc862.png)

**Comment by shanemcd** [comment] 2022-01-31 18:27
Dupe of https://github.com/ansible/awx/issues/5867

**Closed as completed by shanemcd** 2022-01-31 18:27 UTC
Labels: type:enhancement, component:ui
