### ISSUE TITLE
Customizing playbook-dir

### ISSUE THREAD

**Issue by dangoncalves** [ansible/awx#9789] opened 2021-04-02 08:55 UTC
##### ISSUE TYPE
 - Be able to customize playbook-dir for end-user

##### SUMMARY
Assuming we have the following tree
```
+ Git Repository
    + ansible_directory
        playbook.yml
        + inventory_plugins
            some_plugins.py
        + inventories
            some_plugins.yml
```

With the following content for some_plugins.yml
```
plugin: some_plugins
var1: some_value
var2: another_value
```

If I create an inventory inside awx using some_plugins.yml as source, I have this error:
```
specifies unknown plugin 'some_plugins'
```

If I go verifying the job_args in the api, I have this:
```
"job_args": "[\"ansible-inventory\", \"--list\", \"--export\", \"-i\", \"/some/tmp/dir/project/ansible_directory/inventories/hanuman.yml\", \"--output\", \"/some/tmp/dir/artifacts/output.json\", \"--playbook-dir\", \"/some/tmp/dir/project/ansible_directory/inventories\", \"-vvv\"]"
```
What is interesting here is that the `--playbook-dir` flags point to `inventories` directory instead of `ansible_directory`. Being able to customize the `--playbook-dir` would solve this issue.

**Comment by ryanpetrello** [comment] 2021-04-09 17:26
paging @AlanCoding

**Comment by AlanCoding** [comment] 2021-05-18 12:46
Closing as duplicate of https://github.com/ansible/awx/issues/5019

**Closed as completed by AlanCoding** 2021-05-18 12:46 UTC
Labels: type:enhancement, help wanted
