### ISSUE TITLE
Add 'labels' field to activity_stream api and logging output.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#1668] opened 2018-03-23 17:06 UTC
##### ISSUE TYPE

  - Feature Idea

##### COMPONENT NAME

 - API
 - UI
##### SUMMARY

It would be good to inject the labels field from the Job template into the api for the /api/v2/activity_stream/ endpoint. This could be used to create a custom filter for reporting via external logging aggregators. 

##### ENVIRONMENT
* AWX version: devel
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.3
* Operating System: RHEL 7
* Web Browser: N/A

**Comment by asvirdi** [comment] 2018-03-26 17:01
Tower Job_event should contain Org/Teams/username/Custom fields/Labels and should also allow Include/Exclude Fields/Patterns. Right now it's very difficult to analyze and plot against some of key fields.

**Comment by wenottingham** [comment] 2018-03-29 14:50
> Tower Job_event should contain Org/Teams/username/Custom fields/Labels and should also allow Include/Exclude Fields/Patterns.

That is not planned; that codepath is too performance critical to do significant manipulation of the structures returned from Ansible. We may consider some of the enhancements in the initial report.

**Comment by rmauc** [comment] 2018-07-30 17:55
@wenottingham 
Hi, this issue has been open for some time. Is the addition of Org/Teams/username/Custom fields/Labels expected in any upcoming release?
Thanks

**Comment by wenottingham** [comment] 2018-08-08 18:56
This will be updated if/when someone is looking at this for AWX... at the moment, no one is looking at this.

**Comment by rmauc** [comment] 2019-10-03 14:47
I understand that Ansible Analytics can slice data by Organization now. Is there any plans to work on this RFE so that Tower log aggregation can do the same?
Thanks

**Comment by wenottingham** [comment] 2019-10-03 19:24
Not sure what is meant by that - the Analytics is done by gathering *all* the data, performing the associations, and then showing a view of the data that uses those associations. Log aggregators can do the same.

**Comment by rmauc** [comment] 2019-10-04 12:44
Can you tell me  the data from which logger contains the Tower Organization - awx.analytics.activity_stream or awx.analytics.job_events?
Thanks

**Comment by wenottingham** [comment] 2019-10-04 14:50
job_events  events have a record for the job id.
the job id has a creation event in the activity stream.
the job's organization is inherited from the job template's organization, which usually comes from the project. You may need additional API queries, or to chain additional filtering, to do this.

**Comment by rmauc** [comment] 2019-10-04 15:54
Therein lies the problem Bill.. I am looking to slice the data in Splunk - so only have what is aggregated to it (no additional API queries unfortunately).
Not being able to extract data by organization in either stream is a problem we have had for quite sometime.

**Comment by rmauc** [comment] 2019-10-11 19:48
Hi Bill,
What is the likelihood of this being triaged?

**Comment by wenottingham** [comment] 2019-10-11 20:21
If work happens, it will be linked off of this issue.

**Comment by nixocio** [comment] 2020-04-02 19:05
See: https://github.com/ansible/awx/pull/6337

What is the difference between this issue and https://github.com/ansible/awx/issues/1761 @rebeccahhh ?

**Comment by rebeccahhh** [comment] 2020-04-02 19:32
@nixocio they're different asks, labels are included in API endpoints for job updates. This person wants to have the labels available in job events too, if I'm not mistaken. This probably won't be something we do.

**Comment by wenottingham** [comment] 2020-04-02 19:32
Just to comment: the labels have been in the activity stream for the *job* for a while now - in 3.6 at least, and possibly longer.

They will not be added to job_events.

Closing this as working as designed.

**Closed as completed by wenottingham** 2020-04-02 19:32 UTC
Labels: type:enhancement, component:api

**Comment by erraticx** [comment] 2023-12-07 17:27
@wenottingham, It seems the initial ask was about the UF to contain ORG ID so that jobs can be filtered on ORG ID not specifically for activity stream or job_events. 

Was this closed because the ORG ID is in fact being exported via the UF?
