### ISSUE TITLE
UI : Workflow Visualizer  with more informations

### ISSUE THREAD

**Issue by augabet** [ansible/awx#4344] opened 2019-07-18 09:34 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We have to install components on multiple clusters. 
Clusters are identicals, so we use 1 inventory per cluster.
To do so, we use template workflow and run the same job in parallel. 

The issue here is that we only see on the workflow visualizer the name of the job used and not the inventory used which is the main information that we need.

Except if we use it wrongly, we would like to have the inventories name on the workflow visualizer.

**Comment by mabashian** [comment] 2019-07-30 19:32
Yea, we've talked about adding a tooltip to each node with this type of information in the results view for a workflow.  This is mockup for a slightly different scenario but it would look something like this:

<img width="237" alt="Screen Shot 2019-07-30 at 3 31 12 PM" src="https://user-images.githubusercontent.com/9889020/62159205-27ff3a80-b2df-11e9-8f8e-40c2c588066a.png">

except that it would include things like the Inventory.  @augabet would that be sufficient for your use case?

**Comment by augabet** [comment] 2019-07-31 12:46
Hello, that would be perfect for our use case !

**Comment by MrBones757** [comment] 2019-08-19 01:49
Adding this information would be a great addition for out use also

**Comment by unlikelyzero** [comment] 2021-01-23 16:48
closing as dupe of https://github.com/ansible/awx/issues/2032

**Closed as completed by unlikelyzero** 2021-01-23 16:48 UTC
Labels: type:enhancement, component:ui, component:ux
