### ISSUE TITLE
[ui_next] Many websocket connections created and maintained while navigating through app

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9795] opened 2021-04-02 17:06 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Note: this was on a yolo'd instance -- not a local dev build.

Many websocket connections created while navigating through app. This is normally the case when using 'Disable cache' on chrome, but appears with that option disabled.

Some appear to be duplicated. 
On the Workflow Job Output page, I've seen up to 4 active connections.

##### ENVIRONMENT
* AWX version: 04/01/21

##### STEPS TO REPRODUCE
1. Open Devtools with 'Disable Cache' unchecked.
2. Note that the after page refreshes, page transitions, and on Job output pages, there are duplicate websocket sessions maintained.

**Comment by jakemcdermott** [comment] 2021-04-05 19:58
@unlikelyzero nice find :+1: 

>  there are duplicate websocket sessions maintained.

When you get a moment, can you share details on how to specifically verify this / what was indicating to you that there were multiple connections?

**Comment by unlikelyzero** [comment] 2021-04-06 17:44
To summarize (and expand in the future):
- Functionality is not impaired 
- Multiple websockets connections are initialized on pages which use websockets. All but one are closed on a page refresh or page navigation.
- Job Output pages appear to leave connections open
- Some of the websocket connections appear to be exactly duplicated (potentially from useEffect hook duplication). 

Further exploration:
- Determine if the websocket connections are oprhaned on the tower host
- Determine if useEffect-hook XHR Duplication is causing some duplicate websocket.io connections

**Comment by jakemcdermott** [comment] 2021-04-06 20:32
> Some of the websocket connections appear to be exactly duplicated (potentially from useEffect hook duplication).

^ Plan is to verify and then we can scope further

**Comment by unlikelyzero** [comment] 2021-04-06 20:56
When visiting a running install:

```
netstat sudo netstat -an

...
tcp6       0      0 ::1:54630               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:54534               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:54606               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:54854               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:5432                ::1:54888               ESTABLISHED
tcp6       0      0 ::1:54706               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:54596               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:5432                ::1:38396               ESTABLISHED
tcp6       0      0 ::1:54810               ::1:5432                TIME_WAIT
...
```

```
sudo netstat -an | grep :5432 | grep TIME_WAIT | wc -l
20
sudo netstat -an | grep :5432 | grep ESTABLISHED | wc -l
30
sudo netstat -an | grep :5432 | wc -l
52
```

When navigating between pages and logging out:
```
sudo netstat -an | grep :5432 | grep ESTABLISHED | wc -l
32
sudo netstat -an | grep :5432 | grep ESTABLISHED | wc -l
34
```

**Comment by jakemcdermott** [comment] 2021-05-21 15:08
I've looked into this and also spent some time debugging w/ @nixocio 


I see at least two locations where connections seem to be duplicated:

1. The dashboard page. When switching from the dashboard page to other locations that use websockets (e.g, the jobs list), the socket disconnect code in [the hook cleanup method](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/util/useWebsocket.js#L48) doesn't run. This can be verified with log statements. 

2. The job output page - The status icons are driven by the shared websocket hook, but the output itself is still driven by [separate code with its own connect / disconnect cycle](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx#L203-L243). Unifying the websocket code in this view should address this problem. I would like to see https://github.com/ansible/awx/pull/10053 merged before working on this any further, as the pr has a few changes to the socket-driven ui behavior on the output page.

3. Possibly related and definitely a concern: In the dev environment, navigating to the job template details will disconnect the the auto-reloading dev server. You'll see a proxy middleware error in the logs when this happens:
![proxy-disconnect](https://user-images.githubusercontent.com/9753817/119159931-c2d18780-ba25-11eb-9083-8b85660f298d.png)
  These errors might indicate a configuration issue with the proxy, but the fact that they only happen after navigating to certain pages makes me think there is something not quite right with how we're managing the lifecycle of the `Websocket` objects with respect to page loads / component (un)mounts, etc.

**Comment by mabashian** [comment] 2021-06-08 18:21
Lets recheck this now that we've added logic to prevent attempting to reconnect after a clean closure

**Comment by mabashian** [comment] 2021-06-08 20:06
> The dashboard page. When switching from the dashboard page to other locations that use websockets (e.g, the jobs list), the socket disconnect code in the hook cleanup method doesn't run. This can be verified with log statements.

I've looked at this as well and I think I know what you were seeing.  When the app mounts, we open up a socket connection for the workflow approvals icon up in the top nav.  This socket does not get closed when you navigate around the app since the top nav is always shown.  At first I thought the same thing - we have a socket that never gets closed on the dashboard - but actually I think its just the workflow approvals socket (which is most likely initiated on the dashboard after login).

> The job output page - The status icons are driven by the shared websocket hook, but the output itself is still driven by separate code with its own connect / disconnect cycle. Unifying the websocket code in this view should address this problem. I would like to see #10053 merged before working on this any further, as the pr has a few changes to the socket-driven ui behavior on the output page.

We should apply https://github.com/ansible/awx/pull/10339/files to the job output socket.

> Possibly related and definitely a concern: In the dev environment, navigating to the job template details will disconnect the the auto-reloading dev server. You'll see a proxy middleware error in the logs when this happens:
proxy-disconnect
These errors might indicate a configuration issue with the proxy, but the fact that they only happen after navigating to certain pages makes me think there is something not quite right with how we're managing the lifecycle of the Websocket objects with respect to page loads / component (un)mounts, etc.

I was not able to reproduce this behavior locally.

**Comment by tiagodread** [comment] 2021-06-10 14:28
Ok, I was watching the command `ss -an | grep :5432 | grep ESTAB | wc -l` while navigating across several pages in the dev server and the actual number compared to  the old comment decrease a lot

> When navigating between pages and logging out:
> 
> sudo netstat -an | grep :5432 | grep ESTABLISHED | wc -l
> 32
> sudo netstat -an | grep :5432 | grep ESTABLISHED | wc -l
> 34

```
bash-4.4# ss -an | grep :5432 | grep ESTAB | wc -l
7
```

while navigation through pages this number kept the same, I wonder if https://github.com/ansible/awx/pull/10339 could had fixed this high number of ESTAB connections.

**Comment by tiagodread** [comment] 2021-06-10 14:34
> Possibly related and definitely a concern: In the dev environment, navigating to the job template details will disconnect the the auto-reloading dev server. You'll see a proxy middleware error in the logs when this happens:
> proxy-disconnect
> These errors might indicate a configuration issue with the proxy, but the fact that they only happen after navigating to certain pages makes me think there is something not quite right with how we're managing the lifecycle of the Websocket objects with respect to page loads / component (un)mounts, etc.

@jakemcdermott @mabashian I could see a ton of this log in the terminal runing `npm start` and navigating across pages
```
Compiled successfully!

You can now view ui_next in the browser.

  Local:            https://localhost:3001
  On Your Network:  https://192.168.0.12:3001

Note that the development build is not optimized.
To create a production build, use npm run build.

[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
```

**Comment by tiagodread** [comment] 2021-06-10 14:36
Closing for now

**Closed as completed by tiagodread** 2021-06-10 14:36 UTC
Labels: type:bug, component:ui, qe:regression
