### ISSUE TITLE
queries for jobs that have been running longer than N return no results

### ISSUE THREAD

**Issue by pcfe** [ansible/awx#1858] opened 2018-05-08 19:49 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Getting a list of jobs that are running and have an elapsed time greater than N seconds does not seem to work.

##### ENVIRONMENT
* AWX version: Tower 3.2.2
* AWX install method: 
  * src: "https://releases.ansible.com/ansible-tower/setup-bundle/{{ tower_bundle }}.tar.gz"
  * command: ./setup.sh
* Ansible version:  2.4.2.0
* Operating System: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: any

##### STEPS TO REPRODUCE

Pasting tower-cli commands used for easiness, I get the same bevaviour if I point a browswer of my choice at `https://tower.example.com/api/v2/jobs/?&elapsed__gt=9;status=running` and `https://tower.example.com/api/v2/jobs/?&elapsed__gt=9&status=running` (unsure if *;* or *&* needed when combining the query. I'm told *;* is the correct delimiter)

(It's just easier to paste one shell session than copypasta from multiple queries in the browser)

```
[vagrant@tower ~]$ tower-cli job list --all-pages --query status running                       
=== ============ ======================== ======= ========= 
id  job_template         created          status   elapsed  
=== ============ ======================== ======= ========= 
796           35 2018-05-08T19:30:09.076Z running 62.556298
=== ============ ======================== ======= ========= 
[vagrant@tower ~]$ tower-cli job list --all-pages --query status running --query elapsed__gt 60
No records found.
[vagrant@tower ~]$ tower-cli job list --all-pages --query status running --query elapsed__gt 90
No records found.
[vagrant@tower ~]$ tower-cli job list --all-pages --query status running                       
=== ============ ======================== ======= ========= 
id  job_template         created          status   elapsed  
=== ============ ======================== ======= ========= 
796           35 2018-05-08T19:30:09.076Z running 79.255133
=== ============ ======================== ======= ========= 
```
```
[vagrant@tower ~]$ tower-cli job list --all-pages --query status running --query elapsed__lt 10
=== ============ ======================== ======= ========= 
id  job_template         created          status   elapsed  
=== ============ ======================== ======= ========= 
796           35 2018-05-08T19:30:09.076Z running 88.274961
=== ============ ======================== ======= ========= 
[vagrant@tower ~]$ tower-cli job list --all-pages --query status running --query elapsed__lt 100
=== ============ ======================== ======= ========= 
id  job_template         created          status   elapsed  
=== ============ ======================== ======= ========= 
796           35 2018-05-08T19:30:09.076Z running 91.281971
=== ============ ======================== ======= ========= 
```

Please note that queries on non-running jobs seem to work just fine. So be sure to query for running jobs when reproducing.

##### EXPECTED RESULTS
`elapsed__lt` and `elapsed__gt` should correctly compare the values (but maybe I'm just using it wrong).
* `tower-cli job list --all-pages --query status running --query elapsed__gt 60` should have returned *job 796*
* `tower-cli job list --all-pages --query status running --query elapsed__lt 100` should have returned *No records found.*

##### ACTUAL RESULTS
* `status=running` combined with `elapsed__gt` never returns results
* `status=running` combined with `elapsed__lt` always returns results

**Comment by pcfe** [comment] 2018-05-08 20:02
note that `tower_job_list` module exhibits the same behaviour. (which is how I ran into the behaviour)

**Comment by AlanCoding** [comment] 2018-05-09 15:21
This is probably a client-side problem where tower-cli needs to convert the value into the field type.

```
tower-cli job list --all-pages --query status running --query elapsed__gt 1 -v
*** DETAILS: Getting records. *************************************************
GET http://localhost:8013/api/v2/jobs/
Params: {u'status': u'running', u'elapsed__gt': u'1'}

No records found.

```

**Comment by AlanCoding** [comment] 2018-05-14 15:47
Issue transferred to the tower-cli issue queue.

Thanks!

**Closed as completed by AlanCoding** 2018-05-14 15:47 UTC
Labels: type:bug, component:api

**Comment by wiad** [comment] 2023-02-21 15:28
```
    status=running combined with elapsed__gt never returns results
    status=running combined with elapsed__lt always returns results
```
I do not believe that this issue was resolved and I can reproduce it with the AWX api.

Following query will always return the running job, regardless of how long it has elapsed:  
`api/v2/jobs/?status=running&name=myjob&elapsed__lt=20`

Returns:
```
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 153535,
      "type": "job",
      "status": "running",
      ...
      "elapsed": 47.530305,
      ...
}
```

If instead using `elapsed__gt=20` I get no results. 
As the OP says it is the combination with `status=running` that is the problem, if I leave that out I can filter with  `elapsed__XX`.

**Comment by albmarti-harmonicinc** [comment] 2023-03-02 09:09
I'm facing the same issue, cannot get `status=running combined with elapsed__gt`
Even though I tried to get `status=all_status` and `status!=running` combined with `elapsed__gt` ad it's also not returning results.
Any ETA for the fix?

**Comment by wiad** [comment] 2024-08-23 05:50
Could this issue be reopened since the problem remains?
