### ISSUE TITLE
Copying WFJTs renders a copy with an empty workflow

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6636] opened 2020-04-07 17:53 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When attempting to copy a small workflow (with a single approval node), I found that the copied workflow launched and completed without requesting an approval. Further investigation showed that the copied workflow visualizer showed an empty workflow.

##### ENVIRONMENT
* AWX version: latest

##### STEPS TO REPRODUCE
Both @jakemcdermott and I were able to reproduce this (osx, fedora)

1. Create a new workflow job template.
2. Add one approval node to the workflow. Save it, and launch it. Do not approve the workflow, so it stays in a pending state.
3. Copy the workflow using the copy button in the template list.
4. Attempt to launch the copied workflow.

##### EXPECTED RESULTS
The workflow also waits for approval.

##### ACTUAL RESULTS
The workflow does not wait for approval. Inspection shows that the workflow is empty.

**Comment by dsesami** [comment] 2020-04-07 17:54
@rebeccahhh suggests that this commit might be related: https://github.com/ansible/awx/pull/6291

**Comment by rebeccahhh** [comment] 2020-04-15 17:22
After a meeting with some folks we have determined this bug is no longer reproducible. The working theory is that the switcheroo around memcached was the cause. Closing as this is no longer on our to do list.

**Closed as completed by rebeccahhh** 2020-04-15 17:22 UTC
Labels: type:bug, component:api
