### ISSUE TITLE
Ansible Tower doesn't let browser save password upon login

### ISSUE THREAD

**Issue by byount** [ansible/awx#2854] opened 2018-12-01 23:14 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
After typing in the username and password on the login screen on Tower 3.3.1 and clicking "Sign In", the browser doesn't prompt the user if they want to save their password.

##### ENVIRONMENT
* AWX version: 3.3.1
* AWX install method: bundled
* Ansible version:  2.7.2
* Operating System: RHEL 7.6
* Web Browser: Firefox 63.0.3 and Safari 12.0.1

##### STEPS TO REPRODUCE

1. Browse to the Tower login page
2. Enter username
3. Enter password
4. Click "Sign In"

##### EXPECTED RESULTS

The browser should prompt the user if they want to save their password

##### ACTUAL RESULTS

The browser does NOT prompt the user to save their password

**Comment by mabashian** [comment] 2018-12-03 14:39
@byount I would encourage you to reach out to your Red Hat rep with Ansible Tower specific feedback in the future rather than creating an issue here in the upstream project.  That being said, I think this is a duplicate of https://github.com/ansible/awx/issues/444 which should be addressed by https://github.com/ansible/awx/pull/2117

**Closed as completed by mabashian** 2018-12-03 14:39 UTC
Labels: type:bug, component:ui
