### ISSUE TITLE
Hosts aren't disassociating from Groups even when returning 204 success responses

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6352] opened 2020-03-19 17:38 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When disassociating inventory hosts from a group in bulk, the API returns a 204 success response but the hosts remain in the group. The UI could address this issue by enforcing a single disassociate at a time, or through disassociating the hosts sequentially. There is an API component to this because it shouldn't return a 204 success if it did not successfully disassociate the host. 

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method:  docker for mac
* Ansible version: 2.10.0

##### STEPS TO REPRODUCE
* Navigate to Inventory Group Host List `/inventories/inventory/1/groups/11/nested_hosts`
  * Make sure you have at least 10 hosts in the list
* Check select all hosts
* Click Disassociate button
  * A modal should popup and display the list of selected hosts
* Click Disassociate button in the modal 
  * Watch network requests in browser developer tools
* Modal disappears 
* Inventory group host list remains unchanged even after a hard refresh 

##### EXPECTED RESULTS
* The hosts are removed from the inventory group host list

##### ACTUAL RESULTS
* The hosts remain in the inventory group host list 

##### ADDITIONAL INFORMATION
![disassociate test3](https://user-images.githubusercontent.com/15881645/77095516-65d2df80-69e4-11ea-9085-25a645e774a1.gif)

**Comment by mabashian** [comment] 2021-03-10 14:09
@wenottingham circling back to this one.  We had a question about whether the disassociate(s) were actually happening and the list data was just stale.  Looks like @marshmalien answered that in the description, I just didn't read closely enough:

> Inventory group host list remains unchanged even after a hard refresh

**Comment by mabashian** [comment] 2021-06-02 15:38
If we can't ascertain why hosts aren't being successfully disassociated in bulk then we can simply make the requests serially.  This would cause the action to slow down a bit for larger lists of hosts but I think we could make that work.

**Comment by mabashian** [comment] 2021-06-03 14:09
@rebeccahhh and I have been trying to reproduce this one on latest devel without any luck.  @tiagodread I'm going to throw this over to y'all.  If you cant reproduce then I guess lets close this for now?

**Comment by akus062381** [comment] 2021-06-03 14:55
this is resolved.

**Closed as completed by akus062381** 2021-06-03 14:55 UTC
Labels: type:bug, component:api, component:ui
