### ISSUE TITLE
Bug edition workflow_job_template limit empty key

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#11080] opened 2021-09-14 23:25 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi 

With awx 19.3, after edition in UI on workflow_job_template, it's change the key limit to "", default key is null 

so all limit on children node is erased 

    "inventory": null,
    "limit": "",
    "scm_branch": "towerv2",

### AWX version

19.2

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Operating system

redhat

### Web browser

Chrome

### Steps to reproduce

awx 19.3 

create workflow job 

edit scm branche

check api 

### Expected results

without change on limit stay to null

### Actual results

limit is changed to "" without change on limit

### Additional information

with awx_collection they are no problem, change doesn't affect limit

**Comment by nixocio** [comment] 2021-10-12 18:53
@chris93111, I used the API to create a work flow job template.
```json
{
    "id": 16,
    "type": "workflow_job_template",
    "url": "/api/v2/workflow_job_templates/16/",
    "related": {
        "named_url": "/api/v2/workflow_job_templates/11080++/",
        "created_by": "/api/v2/users/1/",
        "modified_by": "/api/v2/users/1/",
        "workflow_jobs": "/api/v2/workflow_job_templates/16/workflow_jobs/",
        "schedules": "/api/v2/workflow_job_templates/16/schedules/",
        "launch": "/api/v2/workflow_job_templates/16/launch/",
        "webhook_key": "/api/v2/workflow_job_templates/16/webhook_key/",
        "webhook_receiver": "",
        "workflow_nodes": "/api/v2/workflow_job_templates/16/workflow_nodes/",
        "labels": "/api/v2/workflow_job_templates/16/labels/",
        "activity_stream": "/api/v2/workflow_job_templates/16/activity_stream/",
        "notification_templates_started": "/api/v2/workflow_job_templates/16/notification_templates_started/",
        "notification_templates_success": "/api/v2/workflow_job_templates/16/notification_templates_success/",
        "notification_templates_error": "/api/v2/workflow_job_templates/16/notification_templates_error/",
        "notification_templates_approvals": "/api/v2/workflow_job_templates/16/notification_templates_approvals/",
        "access_list": "/api/v2/workflow_job_templates/16/access_list/",
        "object_roles": "/api/v2/workflow_job_templates/16/object_roles/",
        "survey_spec": "/api/v2/workflow_job_templates/16/survey_spec/",
        "copy": "/api/v2/workflow_job_templates/16/copy/"
    },
    "summary_fields": {
        "created_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "modified_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "object_roles": {
            "admin_role": {
                "description": "Can manage all aspects of the workflow job template",
                "name": "Admin",
                "id": 66
            },
            "execute_role": {
                "description": "May run the workflow job template",
                "name": "Execute",
                "id": 67
            },
            "read_role": {
                "description": "May view settings for the workflow job template",
                "name": "Read",
                "id": 68
            },
            "approval_role": {
                "description": "Can approve or deny a workflow approval node",
                "name": "Approve",
                "id": 69
            }
        },
        "user_capabilities": {
            "edit": true,
            "delete": true,
            "start": true,
            "schedule": true,
            "copy": true
        },
        "labels": {
            "count": 0,
            "results": []
        },
        "recent_jobs": []
    },
    "created": "2021-10-12T18:50:50.415882Z",
    "modified": "2021-10-12T18:50:50.415955Z",
    "name": "11080",
    "description": "",
    "last_job_run": null,
    "last_job_failed": false,
    "next_job_run": null,
    "status": "never updated",
    "extra_vars": "",
    "organization": null,
    "survey_enabled": false,
    "allow_simultaneous": false,
    "ask_variables_on_launch": false,
    "inventory": null,
    "limit": "",
    "scm_branch": "",
    "ask_inventory_on_launch": false,
    "ask_scm_branch_on_launch": false,
    "ask_limit_on_launch": false,
    "webhook_service": "",
    "webhook_credential": null
}
```
limit default value is "",

I was not able to re-create this one. 

Can you share a gif what you are seeing?

**Comment by chris93111** [comment] 2021-10-12 23:47
@nixocio Hi i thinks the default value is null, because if you put "" it's erase all children node limit. with collections , the value without change limit is null , i have also compare with awx 15 and the default value is null

**Comment by chrismeyersfsu** [comment] 2021-10-15 17:07
@chris93111 can you include the playbook that is running the collection ?

**Comment by chris93111** [comment] 2021-10-17 15:37
hii @chrismeyersfsu 

```
- name: "create workflow remediation for {{ tower_workflow_prefix }}_{{ env }}"
  tower_workflow_job_template:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_user }}"
    tower_password: "{{ tower_password }}"
    validate_certs: false
    name: "{{ tower_workflow_prefix }}_{{ env }}"
    scm_branch: "{{ tower_jobs_branch[vm_env] }}"
    description: workflow environment remediation
    organization: "{{ tower_organization }}"

```

this is the module used for create the workflow, this work, the limit in workflow api is set to null, but after if you change scm branch in ui , this change limit to ""

all children node have limit set , so limit workflow take over with value ""

**Comment by sean-m-sullivan** [comment] 2021-12-12 12:59
After doing some testing I found that this is NOT the awx.awx module issue. This is an internal awx API issue. 
When a workflow is first created the limit field is set to 'null'
When a limit IS set, it is set to that string value. 
When the limit is deleted, either through the plugin OR the module, it is set to ""
Ideally it should be reset back to 'null'

**Comment by shanemcd** [comment] 2022-01-14 18:16
Closing as a duplicate of #11284

**Closed as completed by shanemcd** 2022-01-14 18:16 UTC
Labels: component:ui, component:awx_collection
