### ISSUE TITLE
not can run job

### ISSUE THREAD

**Issue by MikelPan** [ansible/awx#8187] opened 2020-09-20 01:44 UTC
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1354, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1942, in pre_run_hook RunProjectUpdate.make_local_copy(job.project, private_data_dir, scm_revision=job_revision) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2365, in make_local_copy copy_tree(project_path, destination_folder, preserve_symlinks=1) File "/usr/lib64/python3.6/distutils/dir_util.py", line 124, in copy_tree "cannot copy tree '%s': not a directory" % src) distutils.errors.DistutilsFileError: cannot copy tree '/var/lib/awx/projects/playbook': not a directory

**Comment by AlanCoding** [comment] 2020-09-21 12:52
This looks like it could potentially be fixed by #8174, but we need some more information.

What type of project is being used by the job here? Could you get details of that project from the API browser at `/api/v2/projects/<project id>/`?

**Comment by fosterseth** [comment] 2020-09-24 02:30
are you using manual project or scm? 

same error as this issue https://github.com/ansible/awx/issues/6213#issuecomment-614232632

**Comment by ryanpetrello** [comment] 2020-09-25 17:24
@MikelPan if you're still encountering an error, please open a new ticket with the requested details in our issue template (such as the version of software you're using, and reproduction steps).

**Closed as completed by ryanpetrello** 2020-09-25 17:24 UTC
Labels: type:bug, component:api

**Comment by kt-pham** [comment] 2020-10-21 21:37
I'm also getting this issue. I have a job template that is to slice the inventory in 5, with 50 forks. I'm seeing an issue with 125 hosts in  an inventory.
