### ISSUE TITLE
Fails on Docker setup

### ISSUE THREAD

**Issue by sjkeerthi** [ansible/awx#1342] opened 2018-02-25 01:22 UTC
As per the instruction tried to implement awx setup on my docker

ansible-playbook -i inventory install.yml
After sucessfull installation playbook 

But while I check the docker logs -f awx_task 
I could see error and could not able to see awx web
[2018-02-25 01:20:33,532: DEBUG/MainProcess] pidbox received method active_queues() [reply_to:{u'routing_key': u'5d66ecba-59b2-326b-a05a-4695e6929d2d', u'exchange': u'reply.celery.pidbox'} ticket:3f5ac5a5-7673-4f7d-9523-6531a0a56bd7]
[2018-02-25 01:20:33,534: ERROR/MainProcess] Control command error: error(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/channel.py", line 1734, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/transport.py", line 258, in write
    self._write(s)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

**Comment by jakemcdermott** [comment] 2018-02-25 01:40
Likely a duplicate of #1188 and [#1245](https://github.com/ansible/awx/issues/1245#issuecomment-365693587)

**Closed as completed by jakemcdermott** 2018-02-25 01:40 UTC
