### ISSUE TITLE
main_projectupdateevent already exists

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#11811] opened 2022-02-25 10:02 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello

With many job execution at same time, some job crash with error django.db.utils.ProgrammingError: relation "main_projectupdateevent_xxxxxxx" already exists

awx 20.0.0
rhel 8.4

4 instance of awx in same kubernetes cluster

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Operating system

redhat 8.4

### Web browser

Chrome

### Steps to reproduce

launch many same job with allow override branch scm 

### Expected results

launch without error

### Actual results

some job crash with django.db.utils.ProgrammingError: relation "main_projectupdateevent_xxxxxxx" already exists

### Additional information

worked in 15.0.0

**Comment by nixocio** [comment] 2022-02-25 18:05
hey @chris93111, could you add the full error traceback?

**Comment by chris93111** [comment] 2022-02-25 20:02
Hi @nixocio , they are no trace back only error 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/27526373/155787447-77776069-1ab7-40c6-af16-b6ad99013121.png">

**Comment by chris93111** [comment] 2022-02-26 13:00
@nixocio found un result job
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "main_projectupdateevent_20220226_12" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 449, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 946, in pre_run_hook
    create_partition(local_project_sync.event_class._meta.db_table, start=local_project_sync.created)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/common.py", line 1145, in create_partition
    cursor.execute(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "main_projectupdateevent_20220226_12" already exists

```

**Comment by fosterseth** [comment] 2022-03-15 18:00
refinement note -- we may just need to put a try, catch and pass block around or in our `create_partition` call to prevent the job from error-ing out.

**Comment by fosterseth** [comment] 2022-03-23 19:45
I can re-create this error with

```python3
from awx.main.utils.common import create_partition
from django.utils import timezone
from multiprocessing import Pool

def x(i):
    create_partition('main_projectupdateevent', start=timezone.now())

with Pool(30) as p:
    print(p.map(x, range(29)))
```

**Comment by jbradberry** [comment] 2022-03-29 14:07
Does this PR need to be backported?

**Comment by fosterseth** [comment] 2022-03-30 18:06
needs to be backported to 4.1 and 4.0

**Comment by jbradberry** [comment] 2022-04-27 15:35
All of the associated PRs for this issue have merged, but the issue is still marked as open.  I think this fell through the cracks with QE testing.

**Closed as completed** 2022-06-03 12:51 UTC
Labels: type:bug, component:api
