### ISSUE TITLE
Manual maintiance cleanup Ignores user input.

### ISSUE THREAD

**Issue by dragon2611** [ansible/awx#1751] opened 2018-04-11 13:38 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Values entered during prompt "Set how many days of data should be retained" during manual maintenance job run are ignored.

##### ENVIRONMENT
* AWX version: AWX 1.0.5.22
* AWX install method: , docker on linux, 
* Ansible version:  2.50
* Operating System: Docker-host Centos7 - Client machine Mint 18.3
* Web Browser: Firefox 59.0.2 

##### STEPS TO REPRODUCE

Management Jobs > Launch > Enter non default value in prompt (e.g 2 days)

##### EXPECTED RESULTS

Cleanup of entries over X days old to be cleaned (E.g 2 days)

##### ACTUAL RESULTS

Inputted Value is ignored and the default of 30 days is used.

##### ADDITIONAL INFORMATION

```
`WARNING: Tried to load AngularJS more than once.
app.763b47aa28c5e5fd8aac.js:34:305364
Network UI loaded
app.763b47aa28c5e5fd8aac.js:47:2339678
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/
vendor.3e674a3ba3212cd5dd22.js:29:94434
TypeError
?
columnNumber: 1220605
?
fileName: "http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js"
?
lineNumber: 47
?
message: "scope.prompt_for_days_form is undefined"
?
stack: "onOpen@http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js:47:1220605\nopen@http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js:47:769780\n_trigger@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:11122\nopen@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:501:4391\n$.widget/</proxiedPrototype[prop]</<@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:1968\n$.widget.bridge/$.fn[name]/<@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:3554\neach@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:19:23679\neach@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:19:20998\n$.widget.bridge/$.fn[name]@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:3354\nexports.default</$scope.submitJob/scope.removePromptForDays<@http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js:47:1221679\n$emit@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:150022\ncreate/</<@http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js:47:769058\n$eval@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:148426\n$apply@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:148764\ncreate/<@http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js:47:769034\n"
?
__proto__: {?}
??
constructor: TypeError()
???
length: 1
???
name: "TypeError"
???
prototype: Object { stack: "", ? }
???
__proto__: function Error()
??
message: ""
??
name: "TypeError"
??
stack: ""
??
__proto__: {?}
???
constructor: function Error()
???
message: ""
???
name: "Error"
???
stack: Getter & Setter
???
toSource: function toSource()
???
toString: function toString()
???
__proto__: Object { ? }
vendor.3e674a3ba3212cd5dd22.js:71:122052
ReferenceError
?
columnNumber: 534847
?
fileName: "http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js"
?
lineNumber: 47
?
message: "event is not defined"
?
stack: "$rootScope.removeConfigReady</</<@http://172.21.0.19/static/js/app.763b47aa28c5e5fd8aac.js:47:534847\nprocessQueue@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:134252\nscheduleProcessQueue/<@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:135201\n$digest@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:146077\n$apply@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:148845\ndone@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:101113\ncompleteRequest@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:106024\ncreateHttpBackend/</xhr.onload@http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:71:106783\n"
?
__proto__: {?}
??
constructor: ReferenceError()
???
length: 1
???
name: "ReferenceError"
???
prototype: Object { stack: "", ? }
???
__proto__: function Error()
??
message: ""
??
name: "ReferenceError"
??
stack: ""
??
__proto__: {?}
???
constructor: function Error()
???
message: ""
???
name: "Error"
???
stack: Getter & Setter
???
toSource: function toSource()
???
toString: function toString()
???
__proto__: Object { ? }`
```

**Comment by dragon2611** [comment] 2018-04-11 13:47
Chrome 65.0.3325.181 has the same problem.

```
`[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ vendor.3e674a3ba3212cd5dd22.js:29
ajax @ vendor.3e674a3ba3212cd5dd22.js:29
_transport @ vendor.3e674a3ba3212cd5dd22.js:596
builtInLoadZoneFile @ vendor.3e674a3ba3212cd5dd22.js:596
loadZoneFile @ vendor.3e674a3ba3212cd5dd22.js:596
loadZoneFiles @ vendor.3e674a3ba3212cd5dd22.js:596
init @ vendor.3e674a3ba3212cd5dd22.js:596
(anonymous) @ vendor.3e674a3ba3212cd5dd22.js:596
invoke @ vendor.3e674a3ba3212cd5dd22.js:71
(anonymous) @ vendor.3e674a3ba3212cd5dd22.js:71
forEach @ vendor.3e674a3ba3212cd5dd22.js:71
createInjector @ vendor.3e674a3ba3212cd5dd22.js:71
doBootstrap @ vendor.3e674a3ba3212cd5dd22.js:71
bootstrap @ vendor.3e674a3ba3212cd5dd22.js:71
(anonymous) @ app.763b47aa28c5e5fd8aac.js:47
(anonymous) @ app.763b47aa28c5e5fd8aac.js:47
fire @ vendor.3e674a3ba3212cd5dd22.js:29
fireWith @ vendor.3e674a3ba3212cd5dd22.js:29
ready @ vendor.3e674a3ba3212cd5dd22.js:29
completed @ vendor.3e674a3ba3212cd5dd22.js:19
vendor.3e674a3ba3212cd5dd22.js:71 TypeError: Cannot read property '$setPristine' of undefined
    at onOpen (app.763b47aa28c5e5fd8aac.js:47)
    at HTMLDivElement.open (app.763b47aa28c5e5fd8aac.js:47)
    at $.(/anonymous function).(anonymous function)._trigger (http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:11131)
    at $.(/anonymous function).(anonymous function).open (http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:501:4396)
    at $.(/anonymous function).(anonymous function).open (http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:1974)
    at HTMLDivElement.<anonymous> (vendor.3e674a3ba3212cd5dd22.js:37)
    at Function.each (vendor.3e674a3ba3212cd5dd22.js:19)
    at jQuery.fn.init.each (vendor.3e674a3ba3212cd5dd22.js:19)
    at jQuery.fn.init.$.fn.(/anonymous function) [as dialog] (http://172.21.0.19/static/js/vendor.3e674a3ba3212cd5dd22.js:37:3359)
    at app.763b47aa28c5e5fd8aac.js:47
(anonymous) @ vendor.3e674a3ba3212cd5dd22.js:71
(anonymous) @ vendor.3e674a3ba3212cd5dd22.js:71
$emit @ vendor.3e674a3ba3212cd5dd22.js:71
(anonymous) @ app.763b47aa28c5e5fd8aac.js:47
$eval @ vendor.3e674a3ba3212cd5dd22.js:71
$apply @ vendor.3e674a3ba3212cd5dd22.js:71
(anonymous) @ app.763b47aa28c5e5fd8aac.js:47
setTimeout (async)
create @ app.763b47aa28c5e5fd8aac.js:47
_trigger @ vendor.3e674a3ba3212cd5dd22.js:37
_createWidget @ vendor.3e674a3ba3212cd5dd22.js:37
$.(anonymous function).(anonymous function) @ vendor.3e674a3ba3212cd5dd22.js:37
(anonymous) @ vendor.3e674a3ba3212cd5dd22.js:37
each @ vendor.3e674a3ba3212cd5dd22.js:19
each @ vendor.3e674a3ba3212cd5dd22.js:19
$.fn.(anonymous function) @ vendor.3e674a3ba3212cd5dd22.js:37
(anonymous) @ app.763b47aa28c5e5fd8aac.js:47
$scope.submitJob @ app.763b47aa28c5e5fd8aac.js:47
$scope.chooseRunJob @ app.763b47aa28c5e5fd8aac.js:47
fn @ VM443:4
callback @ vendor.3e674a3ba3212cd5dd22.js:71
$eval @ vendor.3e674a3ba3212cd5dd22.js:71
$apply @ vendor.3e674a3ba3212cd5dd22.js:71
(anonymous) @ vendor.3e674a3ba3212cd5dd22.js:71
dispatch @ vendor.3e674a3ba3212cd5dd22.js:29
elemData.handle @ vendor.3e674a3ba3212cd5dd22.js:29`
```

**Comment by AlanCoding** [comment] 2018-04-11 15:38
Duplicate of https://github.com/ansible/awx/issues/369

**Closed as completed by AlanCoding** 2018-04-11 15:38 UTC
Labels: type:bug, component:ui
