### ISSUE TITLE
Add Inventory source support for Netbox

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#4182] opened 2019-06-27 17:22 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to have Netbox (https://github.com/digitalocean/netbox) as an Inventory source option.

**Comment by ryanpetrello** [comment] 2019-06-27 19:52
Duplicate of https://github.com/ansible/awx/issues/4154

**Closed as completed by ryanpetrello** 2019-06-27 19:52 UTC
