### ISSUE TITLE
"Something went wrong..." when trying to execute command on multiple hosts

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/awx#11547] opened 2021-12-14 12:32 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We have a smart inventory, which includes all hosts. When we're selecting all of them and wants to execute some command by clicking in `Run Command` button, we're getting the error (screenshot and message below)

##### ENVIRONMENT
* AWX version: 19.5.0
* Operator version: 0.15.0
* Kubernetes version: v1.20.7
* AWX install method: via operator on regular Kubernetes cluster

##### STEPS TO REPRODUCE

select multiple hosts and click on `Run Command` button

##### EXPECTED RESULTS

should be able to execute command on multiple hosts

##### ACTUAL RESULTS

![Screenshot 2021-12-14 at 13 23 51](https://user-images.githubusercontent.com/13556249/145998114-74d36d1f-9002-4ae8-9135-2d2843e638d6.png)

![Screenshot 2021-12-14 at 13 23 26](https://user-images.githubusercontent.com/13556249/145998800-a482f987-05f9-4d3c-8302-b6e892503906.png)

```
dv@https://test.domain.local/static/js/main.7b1f208d.chunk.js:1:581425 
Zo@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1419512 
Ss@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1465743 
vl@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1458470 
ml@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1458395 
sl@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1455404 
sl@[native code] 
@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1406774 
@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1482175 
Yi@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1406720 
Xi@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1406655 
R@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1475941 
Yt@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1383925 
Yt@[native code]

**Comment by shanemcd** [comment] 2022-01-31 17:12
Dupe of https://github.com/ansible/awx/issues/11547

**Closed as completed by shanemcd** 2022-01-31 17:12 UTC
Labels: type:bug, needs_triage

**Comment by nixocio** [comment] 2022-03-14 14:08
This seems to be a duplicated of https://github.com/ansible/awx/issues/11611
