### ISSUE TITLE
Integer and float surveys are broken

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8331] opened 2020-10-06 18:07 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
You can't create a survey in a job template of `Integer` type or `Float` type.
Replicating the survey question like in the screenshot + saving results in the console errors shown.

Also, you can't set textarea/text default answers to just a number after you fail the initial Save -- it is interpreted as a number and returns a 400. This will probably go away after the first issue is fixed.

![Screenshot from 2020-10-06 14-05-50](https://user-images.githubusercontent.com/19942822/95242465-339c9a00-07dd-11eb-90cb-8b8d98553b90.png)

**Comment by unlikelyzero** [comment] 2020-10-26 01:45
May be a dupe of https://github.com/ansible/awx/issues/8222

**Comment by tiagodread** [comment] 2020-10-26 18:25
PR already merged and tests in place

**Closed as completed by tiagodread** 2020-10-26 18:25 UTC
Labels: type:bug
