### ISSUE TITLE
Jobs cannot be started when inventory is prompted 

### ISSUE THREAD

**Issue by tikeller** [ansible/awx#1916] opened 2018-05-28 12:43 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Job Templates wich are configured to prompt for inventory cannot be executed. Even when an environment is selected the next button cannot be selected. 

Screenshot: 
![image](https://user-images.githubusercontent.com/4193662/40615052-7c77a44a-6285-11e8-9a17-e9f9a1a2f41b.png)

##### ENVIRONMENT
* AWX version: 1.0.6.x 
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: RHEL 7.4
* Web Browser: Firefox / Chrome 

##### STEPS TO REPRODUCE

Create a Job Template which has the prompt check selected. 
Start the template.

##### EXPECTED RESULTS

Jobs can be launched with changing inventories.

##### ACTUAL RESULTS

Jobs cannot launched if there is no presetted inventory.

**Comment by AlanCoding** [comment] 2018-05-29 12:14
Closing as duplicate of https://github.com/ansible/awx/issues/1860

**Closed as completed by AlanCoding** 2018-05-29 12:14 UTC
Labels: type:bug, component:ui
