### ISSUE TITLE
Saving facts_cache performance enhancements

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#12981] opened 2022-09-29 20:07 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Saving facts for many hosts (think 30k+) after a single job run can take a long time. We may need to reconsider how we doing this

- add log statements for every code path involved in reading the facts. Probably has to be debug level, but we should have them.
- add update_fields to that .save() in https://github.com/ansible/awx/blob/ff6fb3229720a6ba93f18ba287fbe99359a17a26/awx/main/models/jobs.py#L909
- consider batch bulk updates so that we address the root timing problem

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

na

### Current results

na

### Sugested feature result

na

**Comment by AlanCoding** [comment] 2022-10-05 03:03
Related testing content

https://github.com/AlanCoding/utility-playbooks/tree/master/AWX12981

I wanted a fact with a randomized file so I that I could be sure that it changed with every run.

**Comment by AlanCoding** [comment] 2022-10-06 17:50
This may be somewhat of a duplicate of https://github.com/ansible/awx/issues/6807

**Comment by jay-steurer** [comment] 2022-11-17 13:19
Feature implemented. Closing it.

**Closed as completed by jay-steurer** 2022-11-17 13:19 UTC
Labels: type:enhancement, component:api
