### ISSUE TITLE
GCP credential injector missing needed parameters

### ISSUE THREAD

**Issue by apitanga** [ansible/awx#3922] opened 2019-05-18 22:39 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The gce credential injector generates a temporary json file in `GCE_CREDENTIALS_FILE_PATH` but that file is missing needed parameters and has a hard-coded values that are out-of-date

##### ENVIRONMENT
* Ansible version:  2.7.1
* Operating System: Fedora 30
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1. Upload GCP credential file for your GCP service account (json format)
2. Create job template with a playbook using one of the new gcp_ modules 
2. Run job template
3. Error returned as modules need parameters not sent by temporary cred file created by gce injector:
```ValueError: Service account info was not in the expected format, missing fields token_uri.```

##### EXPECTED RESULTS

Temporary GCP credential file in created AWX passes the required parameters to gcp_modules and job succeeds

##### ACTUAL RESULTS

Job template fails and cannot find the credential information

##### ADDITIONAL INFORMATION

The gce injector creates temporary file via `json.dump` containing credential parameters, here:

https://github.com/ansible/awx/blob/f174902bb2d3815b3ec09541fae52a466d7f526c/awx/main/models/credential/injectors.py#L18-L41

But the fields created are missing the following keys that exist in current GCP service accounts credential files:

- private_key_id
- client_id
- auth_uri
- auth_provider_x509_cert_url
- client_x509_cert_url

Also, it appears that the value that's hard-coded for `token_uri` has changed to `https://oauth2.googleapis.com/token`

**Comment by AlanCoding** [comment] 2019-05-20 12:59
Looking into it, link related issue

https://github.com/ansible/awx/issues/351

The reason this field was needed was because the code path for the inventory plugin expects email & token_uri, as per:

https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/service_account.py#L208-L209

**Comment by AlanCoding** [comment] 2019-05-20 15:09
@apitanga could you give an example playbook that reproduced the failure you mentioned? Interested in the specific module name and the parameter names passed to it. Could you also give the playbook output shown in AWX with high verbosity & a traceback?

**Comment by apitanga** [comment] 2019-05-21 21:04
@AlanCoding I'm using this playbook: 

https://github.com/apitanga/ansible-playground/blob/master/playbooks/cloud.google/gcp_compute_disk.yaml

I'm passing the following variables via a `host_vars` file:
```
gcp_compute_disk_size_gb: "25"
gcp_compute_disk_source_image: "projects/gce-uefi-images/global/images/rhel-7-v20190326"
gcp_compute_disk_project: "web-development-238814"
gcp_compute_disk_state: "present"
gcp_compute_disk_auth_kind: "serviceaccount"
gcp_compute_disk_name: "cloud-disk"
gcp_compute_disk_zone: "us-east4-a"
```

...and I'm passing the variable pointing at the credential file via "Extra Variables" in the AWX job template definition:

`gcp_compute_disk_service_account_file: '{{ lookup("env", "GCE_CREDENTIALS_FILE_PATH") }}'`

I ran the job with verbosity 3 (Debug): https://pastebin.com/6LqyWL9E

Additional information: just omitting the `gcp_compute_disk_service_account_file` variable it fails with a different error:

```fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1558472494.34-7699158795230/AnsiballZ_gcp_compute_disk.py\\", line 113, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1558472494.34-7699158795230/AnsiballZ_gcp_compute_disk.py\\", line 105, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1558472494.34-7699158795230/AnsiballZ_gcp_compute_disk.py\\", line 48, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\"/tmp/ansible_gcp_compute_disk_payload_xlwN8r/__main__.py\\", line 667, in <module>\\n  File \\"/tmp/ansible_gcp_compute_disk_payload_xlwN8r/__main__.py\\", line 424, in main\\n  File \\"/tmp/ansible_gcp_compute_disk_payload_xlwN8r/__main__.py\\", line 486, in fetch_resource\\n  File \\"/tmp/ansible_gcp_compute_disk_payload_xlwN8r/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\\", line 76, in get\\n  File \\"/tmp/ansible_gcp_compute_disk_payload_xlwN8r/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\\", line 106, in session\\n  File \\"/tmp/ansible_gcp_compute_disk_payload_xlwN8r/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\\", line 131, in _credentials\\n  File \\"/usr/lib64/python2.7/posixpath.py\\", line 261, in expanduser\\n    if not path.startswith('~'):\\nAttributeError: 'NoneType' object has no attribute 'startswith'\\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by apitanga** [comment] 2019-05-23 23:03
Hi @AlanCoding, if we create a custom credential and add a multi-line field where users can upload the entire contents of the credentials file then create a tempfile with that and point the ENV variable to it it does work.

The problem seems to be because in the current, standard GCP credentials we are not passing the entire contents of the key, but extracting certain fields and creating a new tempfile, which is missing the needed fields and hardcoding others.  I'm not sure historically why this is done this way.

Here's an example of a custom credential that does work:

Input configuration:
```
fields:
  - multiline: true
    secret: true
    type: string
    id: gcp_credential_file
    label: GCP Credential File (JSON)
```
Injector configuration:
```
env:
  GCP_SERVICE_ACCOUNT_FILE: '{{ tower.filename }}'
file:
  template: '{{ gcp_credential_file }}'
```

**Comment by kdelee** [comment] 2019-06-06 15:48
@AlanCoding as we discussed this is not working for me. This is what I get when I use @apitanga 's playbook and a GCE cred for our project:

```
{
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "scopes": [
                "https://www.googleapis.com/auth/compute"
            ],
            "size_gb": null,
            "description": null,
            "source_snapshot": null,
            "source_snapshot_encryption_key": null,
            "labels": null,
            "service_account_contents": null,
            "service_account_file": null,
            "licenses": null,
            "disk_encryption_key": null,
            "source_image_encryption_key": null,
            "source_image": null,
            "name": "elijah-test-gce",
            "zone": "us-east1",
            "service_account_email": null,
            "project": null,
            "state": "present",
            "auth_kind": null,
            "type": null,
            "physical_block_size_bytes": null
        }
    },
    "changed": false,
    "msg": "Credential type 'None' not implemented"
}
```

Note you need to provide these extra vars:
```
gcp_compute_disk_name: "elijah-test-gce"
gcp_compute_disk_zone: "us-east1"
ansible_python_interpreter: "/venv/ansible/bin/python"
```

**Comment by AlanCoding** [comment] 2019-06-06 16:05
My best guess is that that's coming from:

https://github.com/ansible/ansible/blob/56179ad8ef1927b9fd9dbacbb59186d61a8c6da9/lib/ansible/module_utils/gcp_utils.py#L161

@kdelee did you pass this mentioned as being in the host vars file?

```
gcp_compute_disk_auth_kind: "serviceaccount"
```

I figure you could put it in extra_vars as an alternative

**Comment by kdelee** [comment] 2019-06-12 19:17
@AlanCoding ... no I did not put that var in. Will try again

**Comment by kdelee** [comment] 2019-06-12 19:26
tried it in extravars, did not work:

```
{
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "scopes": [
                "https://www.googleapis.com/auth/compute"
            ],
            "size_gb": null,
            "description": null,
            "source_snapshot": null,
            "source_snapshot_encryption_key": null,
            "labels": null,
            "service_account_contents": null,
            "service_account_file": null,
            "licenses": null,
            "disk_encryption_key": null,
            "source_image_encryption_key": null,
            "source_image": null,
            "name": "elijah-test-gce",
            "zone": "us-east1",
            "service_account_email": null,
            "project": null,
            "state": "present",
            "auth_kind": "serviceaccount",
            "type": null,
            "physical_block_size_bytes": null
        }
    },
    "changed": false,
    "msg": "Credential type 'serviceaccount' not implemented"
}
```

**Comment by kdelee** [comment] 2019-06-12 19:39
Same result when I tried with `gcp_compute_disk_auth_kind: "serviceaccount"` in the host vars

**Comment by kdelee** [comment] 2019-06-12 20:00
Ok I think that is failing because of the line:

```
        elif cred_type == 'serviceaccount' and self.module.params.get('service_account_file'):
```

because in this module, 
https://github.com/ansible/ansible/blob/56179ad8ef1927b9fd9dbacbb59186d61a8c6da9/lib/ansible/module_utils/gcp_utils.py#L196-L199

they are looking for `'GCP_SERVICE_ACCOUNT_FILE'` not `        "GCE_CREDENTIALS_FILE_PATH"`,  which is what we set in the `JOB_ENV`

All keys we set for this job:
```
{'ANSIBLE_CALLBACK_PLUGINS',
 'ANSIBLE_FORCE_COLOR',
 'ANSIBLE_HOST_KEY_CHECKING',
 'ANSIBLE_INVENTORY_UNPARSED_FAILED',
 'ANSIBLE_PARAMIKO_RECORD_HOST_KEYS',
 'ANSIBLE_RETRY_FILES_ENABLED',
 'ANSIBLE_SSH_CONTROL_PATH_DIR',
 'ANSIBLE_STDOUT_CALLBACK',
 'ANSIBLE_VENV_PATH',
 'AWX_HOST',
 'AWX_ISOLATED_DATA_DIR',
 'AWX_PRIVATE_DATA_DIR',
 'DJANGO_LIVE_TEST_SERVER_ADDRESS',
 'DJANGO_SETTINGS_MODULE',
 'GCE_CREDENTIALS_FILE_PATH',
 'GCE_EMAIL',
 'GCE_PROJECT',
 'HOME',
 'INVENTORY_ID',
 'JOB_ID',
 'LANG',
 'LD_LIBRARY_PATH',
 'MANPATH',
 'MAX_EVENT_RES',
 'PATH',
 'PKG_CONFIG_PATH',
 'PROJECT_REVISION',
 'PROOT_TMP_DIR',
 'PS1',
 'PWD',
 'PYTHONPATH',
 'SHLVL',
 'SUPERVISOR_ENABLED',
 'SUPERVISOR_GROUP_NAME',
 'SUPERVISOR_PROCESS_NAME',
 'SUPERVISOR_SERVER_URL',
 'TZ',
 'USER',
 'VIRTUAL_ENV',
 'XDG_DATA_DIRS'}
```

```

**Comment by apitanga** [comment] 2019-06-13 22:47
@kdelee I also found the same in my tests.  One possible path forward is to just create a temp file using the contents of the entire GCP credential file and point the GCP_SERVICE_ACCOUNT_FILE env var to it.  Would the dynamic inventory file also work with this approach?

**Comment by AlanCoding** [comment] 2019-06-14 13:02
I added `GCE_CREDENTIALS_FILE_PATH` as an env option for the inventory plugin so that it can be used in a way congruent with the modules.

https://docs.ansible.com/ansible/latest/plugins/inventory/gcp_compute.html

Since this is not preferred, I'm totally fine with deprecating it and adding a new alias, but that will leave us in a weird place for cross-version compatibility, having to duplicate the file reference in the env vars. Also, since it uses the same code in the module_utils, it's possible that the newer reference might already work, but that's speculative.

**Comment by AlanCoding** [comment] 2019-07-08 11:47
Also link https://github.com/ansible/awx/pull/4072

I do wonder if re-testing with devel combined with that change will affect what we've seen, but this is somewhat of a wild guess.

**Comment by rambleraptor** [comment] 2019-07-08 21:25
I'm looking at #4072 again (went off my radar for a bit) and I'm hoping to get the tests fixed ASAP so we can merged in it.

**Comment by rambleraptor** [comment] 2019-07-08 23:05
@apitanga #4072 should fix this. I've got the tests passing, so as soon as it's merged in, I'd love to get feedback from you.

**Comment by kdelee** [comment] 2019-07-30 14:40
I am now getting more environment variables set in the environment:
```
{'ANSIBLE_CALLBACK_PLUGINS',
 'ANSIBLE_COLLECTIONS_PATHS',
 'ANSIBLE_FORCE_COLOR',
 'ANSIBLE_HOST_KEY_CHECKING',
 'ANSIBLE_INVENTORY_UNPARSED_FAILED',
 'ANSIBLE_PARAMIKO_RECORD_HOST_KEYS',
 'ANSIBLE_RETRY_FILES_ENABLED',
 'ANSIBLE_ROLES_PATH',
 'ANSIBLE_SSH_CONTROL_PATH_DIR',
 'ANSIBLE_STDOUT_CALLBACK',
 'ANSIBLE_VENV_PATH',
 'AWX_GROUP_QUEUES',
 'AWX_HOST',
 'AWX_ISOLATED_DATA_DIR',
 'AWX_PRIVATE_DATA_DIR',
 'CURRENT_UID',
 'DJANGO_LIVE_TEST_SERVER_ADDRESS',
 'DJANGO_SETTINGS_MODULE',
 'GCE_CREDENTIALS_FILE_PATH',
 'GCE_EMAIL',
 'GCE_PROJECT',
 'GCP_AUTH_KIND',
 'GCP_ENV_TYPE',
 'GCP_PROJECT',
 'GCP_SERVICE_ACCOUNT_FILE',
 'HOME',
 'HOSTNAME',
 'INVENTORY_ID',
 'JOB_ID',
 'LANG',
 'LANGUAGE',
 'LC_ALL',
 'MAKEFLAGS',
 'MAKELEVEL',
 'MAX_EVENT_RES',
 'MFLAGS',
 'OS',
 'PATH',
 'PROJECT_REVISION',
 'PROOT_TMP_DIR',
 'PS1',
 'PWD',
 'PYTHONPATH',
 'RABBITMQ_HOST',
 'RABBITMQ_PASS',
 'RABBITMQ_USER',
 'RABBITMQ_VHOST',
 'SDB_HOST',
 'SDB_NOTIFY_HOST',
 'SHLVL',
 'SUPERVISOR_ENABLED',
 'SUPERVISOR_GROUP_NAME',
 'SUPERVISOR_PROCESS_NAME',
 'SUPERVISOR_SERVER_URL',
 'TZ',
 'VIRTUAL_ENV',
 '_'}
```

But when I use https://github.com/apitanga/ansible-playground/blob/master/playbooks/cloud.google/gcp_compute_disk.yaml + our gce credentials + these extravars:

```
'{"gcp_compute_disk_name": "elijah-test-gce", "gcp_compute_disk_zone": "us-east1", "ansible_python_interpreter": "/venv/ansible/bin/python"}'
```

I still end up with this error:
```
The error was: ValueError: Service account info
was not in the expected format, missing fields token_uri.
```

**Comment by kdelee** [comment] 2019-07-31 18:52
Working on a more general reproducer, and trying to find modules for which our credentials work.

This is what I've got so far:

https://github.com/kdelee/test-playbooks/blob/more_gcp_modules/cloud_modules/gce.yml
Created ^ by looking at https://docs.ansible.com/ansible/latest/scenario_guides/guide_gce.html

When adding these extra vars and a GCE credential:
extra vars:
```
ansible_python_interpreter: /venv/ansible/bin/python
```

STDOUT showing `missing fields token_url` error for all but the `gce` module:
```
PLAY [localhost] ***************************************************************
TASK [gce] *********************************************************************
ok: [localhost]
TASK [gcp_storage_bucket] ******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Service account info was not in the expected format, missing fields token_uri.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591169.61-168689445032586/AnsiballZ_gcp_storage_bucket.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591169.61-168689445032586/AnsiballZ_gcp_storage_bucket.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591169.61-168689445032586/AnsiballZ_gcp_storage_bucket.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_storage_bucket_payload_5fyH98/__main__.py\", line 1269, in <module>\n  File \"/tmp/ansible_gcp_storage_bucket_payload_5fyH98/__main__.py\", line 819, in ma…
TASK [gcp_compute_network] *****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Service account info was not in the expected format, missing fields token_uri.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591170.21-33654024104957/AnsiballZ_gcp_compute_network.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591170.21-33654024104957/AnsiballZ_gcp_compute_network.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591170.21-33654024104957/AnsiballZ_gcp_compute_network.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_compute_network_payload_r116Nt/__main__.py\", line 416, in <module>\n  File \"/tmp/ansible_gcp_compute_network_payload_r116Nt/__main__.py\", line 227, in m…
TASK [gcp_compute_instance] ****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Service account info was not in the expected format, missing fields token_uri.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591170.76-24595060999661/AnsiballZ_gcp_compute_instance.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591170.76-24595060999661/AnsiballZ_gcp_compute_instance.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591170.76-24595060999661/AnsiballZ_gcp_compute_instance.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_compute_instance_payload_OzbkSE/__main__.py\", line 1553, in <module>\n  File \"/tmp/ansible_gcp_compute_instance_payload_OzbkSE/__main__.py\", line 949…
TASK [gcp_compute_address] *****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Service account info was not in the expected format, missing fields token_uri.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591171.32-268746493940677/AnsiballZ_gcp_compute_address.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591171.32-268746493940677/AnsiballZ_gcp_compute_address.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591171.32-268746493940677/AnsiballZ_gcp_compute_address.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_compute_address_payload_CVLq5e/__main__.py\", line 395, in <module>\n  File \"/tmp/ansible_gcp_compute_address_payload_CVLq5e/__main__.py\", line 234, i…
TASK [gcp_compute_disk] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Service account info was not in the expected format, missing fields token_uri.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591171.87-281010032237818/AnsiballZ_gcp_compute_disk.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591171.87-281010032237818/AnsiballZ_gcp_compute_disk.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/tmp/ansible-tmp-1564591171.87-281010032237818/AnsiballZ_gcp_compute_disk.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_compute_disk_payload_vXYJ9r/__main__.py\", line 705, in <module>\n  File \"/tmp/ansible_gcp_compute_disk_payload_vXYJ9r/__main__.py\", line 456, in main\n  File …
PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=5   
```

This has me thinking that the `gce` module is an outlier and this may have been broken for a while. Would like to checkout out older versions of awx/tower and see if it ever worked

**Comment by AlanCoding** [comment] 2019-08-01 17:51
To give an update, we got pretty good at replicating the error with:

> missing fields token_uri

and the linked PR fixes it. I've applied the `mergit` label, and it is expected that it fixes the issue here.

**Comment by kdelee** [comment] 2019-08-05 20:47
This same scenario is working for me now! https://github.com/ansible/awx/issues/3922#issuecomment-516975643

Calling this done

**Closed as completed by kdelee** 2019-08-05 20:47 UTC
Labels: type:bug, component:api
