### ISSUE TITLE
Template save permission denied but user/team has Admin permission

### ISSUE THREAD

**Issue by DBLaci** [ansible/awx#754] opened 2017-12-01 11:07 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
One template from a project playbook with 1 inventory and 2 credentials. If i grant a team Admin permission on this template it cannot be saved: operation not permitted.

##### ENVIRONMENT
* AWX version: 1.0.1.268
* AWX install method: docker swarm
* Ansible version:  2.4.x
* Operating System: Ubuntu 16.04
* Web Browser: Chromium 63

##### STEPS TO REPRODUCE

- Create a project, credentials, inventories
- Create a template from a playbook with credentials and inventories
- Add a team (user?) Admin permission on the template
- Edit the template
- Save

##### EXPECTED RESULTS

Template is saved when only the template has admin permission for the user.

##### ACTUAL RESULTS

Error on save: ERROR! Operation not permitted (not exact as it is localized to browser language)

In the browser network tab: PUT /api/v2/job_templates/9/ 403 Forbidden

##### ADDITIONAL INFORMATION

When the user has no permission to dependencies of the template it is visible during the page load: the network page:
    /api/v2/credentials/3/  - 403 Forbidden

If I add permission to all credentials/inventories it works. But for credentials teams cannot be granted, only users (but this is another story)

**Comment by AlanCoding** [comment] 2017-12-01 12:42
This is an intentional decision, so that someone can't change things that will affect an inventory that they don't have permission to. Nonetheless, I agree that it's a user pain point, and my suggestion is that we should return a specific message that makes clear what rule is violated.

**Comment by DBLaci** [comment] 2017-12-01 13:33
1.: I agree a specific error would be great. It is not trivial to descide which asset the user needs permission.
2.: The problem occurs saving template WITHOUT any modification. No inventory change, nothing. In fact in my case the user wants to update variables.

AND it works if the user has use access for the inventory, but for executing this is not needed. I think this is not reasonable.

**Comment by AlanCoding** [comment] 2017-12-01 13:43
> The problem occurs saving template WITHOUT any modification. No inventory change, nothing. In fact in my case the user wants to update variables.

This could be some mis-communication between the API and UI. Non-sensitive fields like name and description should be editable to job template admins. I'll try to attempt reproducing later.

**Comment by DBLaci** [comment] 2017-12-01 14:15
Thank you. Meanwhile I tested and can confirm the user doesn't need access to inventories/credentials to run the template, so I think editing any aspect of the template (not affecting inventory/credential) should be allowed with ADMIN permission to the template (and no permission to the credentials/inventories).

I don't know if I am doing some rare practice or not so I tell you this playbook is for deploying application and the users (developer group) run it and they might change variables in the template before running (and save for persisting this change).

**Comment by AlanCoding** [comment] 2017-12-01 14:28
You're right, I'm replicating this. The action is a PUT, I hit this editing the description.

Looking at the payload, I suspect that this is fallout from the multi-credential changes, since the payload includes key like `vault_credential`.

This is an API issue, but it will probably only happen for the old credential pattern. On that theory, I'll reopen this.

The flow in the UI, however, is likely to be fixed as the UI updates to use the `credentials` relationship.

**Comment by DBLaci** [comment] 2017-12-01 14:44
I confirm this particular template uses 2 credentials (ssh + vault password) - I didn't tested with only one or without vault credentials. Thank you!

**Comment by AlanCoding** [comment] 2017-12-01 14:50
You can reproduce this by navigating to `/api/v2/job_templates/22/` and issuing a PUT without changing any of the data. That makes this clearly an API bug.

**Comment by AlanCoding** [comment] 2017-12-04 21:02
Should be fixed in `devel` branch now. Thanks for the report, that was very helpful.

**Closed as completed by AlanCoding** 2017-12-04 21:02 UTC
Labels: type:bug, component:api
