### ISSUE TITLE
Question: does AWX really need over a hundred open ports now?

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9679] opened 2021-03-24 14:06 UTC
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY
After installing AWX 18.0.0 in docker I see over a hundred forwarded ports. No explanation in the documentation what these are needed for, and if the number could be reduced.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

Install AWX in docker as described in https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md

##### EXPECTED RESULTS

I'd expect a running AWX instance with a sensible number of open ports

##### ACTUAL RESULTS

I have a running AWX instance with over a hundred ports being forwarded into the awx container

**Comment by ryanpetrello** [comment] 2021-03-24 14:26
duplicate of https://github.com/ansible/awx/issues/9680

**Comment by shanemcd** [comment] 2021-03-24 14:27
Our development environment uses these ports for the `sdb` debugger we use.

It sounds like you are trying to use the development environment in a production scenario, which is not advised.

**Closed as completed by ryanpetrello** 2021-03-24 14:26 UTC
Labels: component:installer

**Comment by lemmy04** [comment] 2021-03-24 14:38
oh that's what they are for... ok thanks
