### ISSUE TITLE
[ui_next] In WFJT Output view, clicking on an approval node sends user to /jobs/

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8794] opened 2020-12-09 13:44 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In WFJT Output view, clicking on an approval node route the user correctly

##### ENVIRONMENT
* AWX version: 12/9

##### STEPS TO REPRODUCE
1. Make a workflow with an approval node which remains in running state
2. Run workflow
3. Click on the approval node

##### EXPECTED RESULTS
1. Navigated to the Approvals page

##### ACTUAL RESULTS
Empty Job page

##### ADDITIONAL INFORMATION

![Screen Shot 2020-12-09 at 8 43 06 AM](https://user-images.githubusercontent.com/12446869/101637298-94716a00-39fa-11eb-96d0-5f6fab497dcd.png)

**Comment by mabashian** [comment] 2020-12-09 14:57
This is a dupe of #8374.  The page that we needed to link to didn't exist until the last few weeks.

**Closed as completed by mabashian** 2020-12-09 14:57 UTC
Labels: type:bug
