### ISSUE TITLE
Many AWX collection modules deletion not idempotent

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5165] opened 2019-10-30 16:33 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
For most `tower_*` modules in the collection, `state: absent` is not idempotent and will error

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: any
* Ansible version:  2.10
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

https://github.com/ansible/ansible/issues/47915

> Try to delete non-existing objects with tower_inventory and tower_credential module

...and more modules

```yaml
- hosts: localhost
  tasks:
    - name: Delete demo inventory (fails)
      tower_inventory:
        name: "Foo inventory"
        organization: "Default"
        state: absent
```

##### EXPECTED RESULTS

Always success

##### ACTUAL RESULTS

Only successful if the object exists, otherwise errors

##### ADDITIONAL INFORMATION

`fail_on_missing` parameter needed, some modules have it, others do not.

**Comment by beeankha** [comment] 2019-11-25 19:16
Could not reproduce this error in the current version, closing this issue.

**Closed as completed by beeankha** 2019-11-25 19:16 UTC
Labels: type:bug, component:awx_collection

**Comment by PC-Admin** [comment] 2020-11-24 01:32
I experienced this same issue with Ansible 2.9.6 and AWX 15.0.1 using the 'tower_job_template' and 'tower_inventory' modules.

**Comment by AlanCoding** [comment] 2020-11-24 15:32
Could you give a playbook and what error your saw? I'm unclear if your issue is just idempotentency, or you're getting errors, or something else. Thanks.

**Comment by PC-Admin** [comment] 2021-09-28 05:17
Sorry i don't have record of these failing, it has been a while.
