### ISSUE TITLE
Allow job template launch against latest completed inventory sync while new sync is ongoing

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1987] opened 2018-06-13 17:46 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Add option to run a job template against a copy of the last completed inventory sync and allow job to launch without blocking for an ongoing inventory sync.

##### ENVIRONMENT
* Tower 3.2.5

##### STEPS TO REPRODUCE

This allows the launch of jobs that do not depend on the latest inventory sync to launch against a complete, earlier version of the inventory, rather than blocking for the completion of the running sync.

**Comment by AlanCoding** [comment] 2018-06-14 15:42
job templates _do_ run against a snapshot of the inventory taken at the time the job template starts.

The reason we don't let another sync run while the job template is in-progress is because the job result will update details of the hosts in the inventory, like its failed status, host summaries, maybe facts, etc.

**Comment by wenottingham** [comment] 2018-06-14 16:38
Would this be implementable once the computed field process is changed/removed?

**Comment by AlanCoding** [comment] 2018-06-14 17:07
Errors in the compute fields task are ignored anyway, so that doesn't make a difference on way or the other.

To do this, we need an answer of the expected behavior in the event that hosts have changed / been removed when the processing at the end of the job run happens.

**Comment by andersharrisson-ess** [comment] 2019-03-05 14:52
> job templates _do_ run against a snapshot of the inventory taken at the time the job template starts.
> 
> The reason we don't let another sync run while the job template is in-progress is because the job result will update details of the hosts in the inventory, like its failed status, host summaries, maybe facts, etc.

Is there no way of running the inventory sync concurrently with the job templates?

We are using a dynamic inventory, for which we prefer to enable "Update on launch"; this to make sure we're running against the correct inventory. Since, more or less, all job templates use this inventory we end up with a single queue of jobs all waiting for their respective inventory syncs.

Populating facts and job status to the hosts sounds manageable by other means than blocking the sync of the inventory.

> To do this, we need an answer of the expected behavior in the event that hosts have changed / been removed when the processing at the end of the job run happens.

I guess the facts could end up in an unexpected state in case an earlier job takes longer time and completes after a later job on the same inventory; thus effectively revering the host facts to an older state. But maybe the job should skip updating inventory host data if a newer job using the same inventory has already updated the host.

**Comment by ursetto** [comment] 2019-11-07 21:51
Agreed, this has a bad interaction with dynamic inventory and update on launch. A single long-running job (even just a single rogue node) which exceeds the inventory cache time causes every subsequent job on that inventory to hang. Perhaps this is documented somewhere, but it wasn't obvious to me. 

The only workaround I can think of is to have 2 identical dynamic inventories with one dedicated to time-sensitive jobs and the other for non-critical or long-running jobs.

**Comment by AlanCoding** [comment] 2019-11-08 02:26
Thanks for bumping this issue, by my reading, it matches exactly with https://github.com/ansible/awx/issues/4809. That is scoped and on the agenda.

Closing this because it is a duplicate. I give you credit for being first, but we have stuff linked to the new issue.

**Closed as completed by AlanCoding** 2019-11-08 02:26 UTC
Labels: type:enhancement, component:api
