### ISSUE TITLE
Multiline in textarea

### ISSUE THREAD

**Issue by AnstasiaR** [ansible/awx#4343] opened 2019-07-18 09:20 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have some question about textarea field in survey.
When I add the variables and then launch the task, I can`t separate strings by pressing the enter from keyboard (after pressing the enter, button NEXT is activated). In previous version it was possible. How can I fix this?
![image](https://user-images.githubusercontent.com/53037771/61444653-75c98980-a954-11e9-928d-253b34dcbd6b.png)

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: rpm install
* Ansible version:  2.7.10
* Operating System: CentOS 7.6.1810
* Web Browser: Chrome 75.0.3770.100

##### STEPS TO REPRODUCE

Add new textarea variables, press launch, try to add a list separating by enter

##### EXPECTED RESULTS

Can add a list variables

##### ACTUAL RESULTS

Press NEXT button

##### ADDITIONAL INFORMATION

P.S. I know two hacks: to add some prompt on launch and then can separate variables by enter (why I can`t do it at first?). Or I can make a list in notepad and then paste it. But both of them isn`t comfortable =(
![image](https://user-images.githubusercontent.com/53037771/61444664-7eba5b00-a954-11e9-9d90-8de6d0676898.png)

**Comment by ryanpetrello** [comment] 2019-07-18 16:16
@jakemcdermott @mabashian this looks like a duplicate of https://github.com/ansible/awx/issues/4192 (or closely related)?

**Comment by mabashian** [comment] 2019-07-30 18:32
Could be related - there were some changes somewhat recently dealing with the enter button taking you to the next tab in the prompt modal. https://github.com/ansible/awx/pull/3594 and https://github.com/ansible/awx/pull/4003 are possibly related

**Comment by fxfitz** [comment] 2019-08-29 22:08
We have a few members on our team who are experiencing this. Also we noticed that those same affected members are also getting logged out every 30 minutes (the idle timeout) **even though** they are active.

**Comment by dsesami** [comment] 2019-10-09 19:42
Tried it out and it looks like this was repaired along with #4192 with the PR here: https://github.com/ansible/awx/pull/4869. If there are further issues with multiline after incorporating the pull request linked above, please provide updated information.

**Closed as completed by dsesami** 2019-10-09 19:42 UTC
Labels: type:bug, component:ui
