### ISSUE TITLE
How to stop unnecessary upgrade on awx

### ISSUE THREAD

**Issue by akhilbatra898** [ansible/awx#586] opened 2017-11-06 16:28 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
After every system restart, AWX starts upgrading with this message 

> AWX is currently upgrading or installing, this page will refresh when done.

on the browser and I am unable to access the web app while it is upgrading. Is there any way to stop the upgrade or access the API and web UI while it is upgrading.

##### ENVIRONMENT
* AWX version: 1.0.0.550
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: Ubuntu 16.04
* Web Browser: Chrome
![screenshot from 2017-11-06 15-21-17](https://user-images.githubusercontent.com/6381580/32451720-931ca926-c33d-11e7-9d58-fa06a8c38245.png)

**Comment by jakemcdermott** [comment] 2017-11-06 18:32
There is no way to access the API or UI while it is upgrading. 

When you ran the installer, did you configure your inventory to use a postgres data directory other than `/tmp/*`? https://github.com/ansible/awx/blob/devel/installer/inventory#L30

The environment information provided indicates that you are running this on ubuntu. I think ubuntu will clear the `/tmp` directory on each boot.

**Comment by akhilbatra898** [comment] 2017-11-07 13:49
Thanks for pointing out the problem.

So do I need to reinstall the AWX or is there a way to change postgres directory now?

**Comment by jakemcdermott** [comment] 2017-11-08 05:06
Try copying your postgres data directory to a different location outside of `/tmp/*`, then update your installer inventory to point to that new directory and then re-run the installer.

Since this is working as intended and as designed I'm going to close this issue - feel free to drop by our mailing list or IRC channel if you need any help.

**Closed as completed by jakemcdermott** 2017-11-08 05:06 UTC
Labels: type:bug, component:installer
