### ISSUE TITLE
Adding for function "disable entering a password from users and force them to only use 'Prompt on launch'"

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#7212] opened 2020-06-02 03:39 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Ansible Tower users do not want to store their passwords in Ansible Tower database and adding for function "For Machine credentials, disable entering a password from users and force them to only use 'Prompt on launch'". 

![credential](https://user-images.githubusercontent.com/58404577/83477454-9ea82e00-a4d6-11ea-9c66-271242da78c5.png)

**Comment by ryanpetrello** [comment] 2020-06-02 11:29
> disable entering a password from users and force them to only use 'Prompt on launch'".

Even when passwords are prompted at launch time, they're still encrypted and temporarily stored in the database - given that AWX is responsible for scheduling the job run and starting it (potentially on a different server), there's not really any alternative here - we've got to keep the password _somewhere_ between the HTTP request and the eventual forking of the `ansible-playbook` process.

**Comment by wenottingham** [comment] 2020-06-02 15:55
This sounds more like #1126, to be honest.

**Comment by wenottingham** [comment] 2020-06-05 16:28
Closing as a duplicate of #1126, as that is the easiest way to solve this for an org (disable personal credentials, and only give credential creation to specific users).

**Closed as completed by wenottingham** 2020-06-05 16:28 UTC
