### ISSUE TITLE
WF viz needs error handling

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6528] opened 2020-04-01 20:31 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Create a template where one of the nodes is a broken JT, missing an inventory that got deleted or something.

I made one that looks like this:
![Screenshot from 2020-04-01 16-26-30](https://user-images.githubusercontent.com/19942822/78183359-c5de7280-7435-11ea-99c5-e70bbed09dc5.png)

The launch button is disabled, but we aren't told why. Clicking save sends a DELETE and then a POST, which is a bit odd, but the first one 404s and the second one 400s. 

We should:

- [ ] Have error handling that indicates why the job won't launch.
- [ ] Indicate the broken node in the WF viz somehow. 
- [ ] Maybe think of a way to make it more obvious that you need to save the workflow before launching.

**Comment by mabashian** [comment] 2021-03-01 18:39
OK so, this issue was addressed by [this commit](https://github.com/ansible/awx/commit/ca1e597a4dec9f9ef70dbe7a198bca4601b0cd8d) of [this PR](https://github.com/ansible/awx/pull/8399).

We didn't seem to add a lot of unit test coverage though so I'm going to add some in a separate PR.

> Indicate the broken node in the WF viz somehow

This is being tracked by https://github.com/ansible/awx/issues/6805

> Create a template where one of the nodes is a broken JT, missing an inventory that got deleted or something.

Soon this will not be possible with https://github.com/ansible/awx/pull/9439 and https://github.com/ansible/awx/issues/8921

**Comment by mabashian** [comment] 2021-03-02 19:33
cc @unlikelyzero @tiagodread @one-t @akus062381 

Here's a PR with unit tests to cover the different scenarios where we want to show an error on workflow save:

https://github.com/ansible/awx/pull/9460

Feel free to add to those cases as you see fit.

Otherwise, I believe the development work here is done.

**Comment by unlikelyzero** [comment] 2021-03-09 21:31
@mabashian we were unable to reproduce the save errors identified in the unit tests. 

We will have to add an e2e test for:
Error shown when user selects JT which is deleted before Save action occurs. @akus062381 please reach out to me for an explanation

**Comment by akus062381** [comment] 2021-04-23 14:56
This issue has been fixed in the UI and the unit tests provide sufficient coverage.

**Closed as completed** 2021-04-23 18:17 UTC
Labels: component:ui, type:feature
