### ISSUE TITLE
Support approval nodes in awx.awx.tower_workflow_job_template_node

### ISSUE THREAD

**Issue by koki-sato** [ansible/awx#8123] opened 2020-09-10 16:01 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

I want `awx.awx.tower_workflow_job_template_node` to support approval nodes.

Looking at [awx_collection/plugins/modules/tower_workflow_job_template_node.py#L94](https://github.com/ansible/awx/blob/14.1.0/awx_collection/plugins/modules/tower_workflow_job_template_node.py#L94), unfortunately it looks like `not yet implemented` now.

**Comment by blomquisg** [comment] 2020-09-11 17:11
@beeankha @AlanCoding Thoughts on complexity for this?

**Comment by AlanCoding** [comment] 2020-09-11 17:33
Duplicate of https://github.com/ansible/awx/issues/8013, also related to https://github.com/ansible/awx/issues/6367

The API is very unique for approval nodes. The normal patterns don't apply, and I do not know if idempotency can be fully maintained.

**Comment by wenottingham** [comment] 2020-09-11 19:07
Closing, then.

**Closed as completed by wenottingham** 2020-09-11 19:07 UTC
Labels: type:enhancement, component:awx_collection
