### ISSUE TITLE
Unable to edit a new Job Template (creation didn't seem to totally complete)

### ISSUE THREAD

**Issue by cesan3** [ansible/awx#319] opened 2017-09-28 14:34 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
I've deployed using the new ansible/awx_web/task images

##### STEPS TO REPRODUCE
1.  Deploy the project using the official images
2.  Settings:
  port: 8080
  postgres dir: /opt/pgdocker
  awx_secret: XXXXXXX
3. Once deployed, I connect to the server using the default admin/password
4.  Create a new Project
5.  Create a new Job Template, use a playbook from that project
6.  Ask for the rest of variables
7.  Save the JOB
8.  Edit the JOB by clicking on the icon or the name

##### EXPECTED RESULTS

I can edit the job and make some modifications

##### ACTUAL RESULTS

Nothing happened.

Checked the browser console and I saw these errors:

vendor.a4f2158….js:436 TypeError: Cannot read property 'replace' of undefined
    at Object.setUrl (app.4099ea5….js:403)
    at stateDefinitions.generateTree.resolve.edit.canGetInventory (app.4099ea5….js:403)
    at invokeResolveFn (vendor.a4f2158….js:468)
    at processQueue (vendor.a4f2158….js:436)
    at vendor.a4f2158….js:436
    at Scope.$eval (vendor.a4f2158….js:436)
    at Scope.$digest (vendor.a4f2158….js:436)
    at Scope.$apply (vendor.a4f2158….js:436)
    at done (vendor.a4f2158….js:436)
    at completeRequest (vendor.a4f2158….js:436)

##### ADDITIONAL INFORMATION

Screenshot

![image](https://user-images.githubusercontent.com/3269106/30972476-9cab066e-a438-11e7-9bde-cc2604936960.png)

**Comment by jaredevantabor** [comment] 2017-09-28 17:15
Thanks for the issue @cesan3, I have reproduced this locally. It seems to be related to when *only* prompt-for-inventory is checked (and no inventory is provided). The JT gets saved but the user is unable to edit the JT b/c the `canEditInventory` resolve fails. 

This will likely get fixed downstream and fixed on the next 3.2.0 merge

**Comment by jaredevantabor** [comment] 2017-09-28 18:10
This was actually already fixed in downstream, and should get resolved with the next merge into AWX. I'm going to close this issue since this will be resolved when that happens.

**Closed as completed by jaredevantabor** 2017-09-28 18:10 UTC
Labels: type:bug, component:ui
