### ISSUE TITLE
Installer wants to pull 9.3.0 Version of awx_web container

### ISSUE THREAD

**Issue by nwerker** [ansible/awx#6272] opened 2020-03-12 16:10 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I just installed a new AWX test instance and the install playbook threw an error while pulling the images from hub.docker because it wanted to pull version 9.3.0 of the awx_web container, which it obviously couldn't since it's not released yet. I changed the "dockerhub_version" variable in the inventory to 9.2.0 and everything was just fine but maybe change it so other people won't run into this issue!

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.0
* Operating System: CentOS 8
* Web Browser: Firefox 73.0.1

##### STEPS TO REPRODUCE

* Install Prerequesits on CentOS8
* Clone github project (master branch)
* Leave inventory file untouched
* Launch ansible playbook to spinup the instance with local database install

##### EXPECTED RESULTS

Install of latest AWX 9.2.0

##### ACTUAL RESULTS

Installation Fails at following Task:

TASK [local_docker : Start the containers] *************************************************fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"b'manifest for ansible/awx_web:9.3.0 not found'\")"}

**Comment by ryanpetrello** [comment] 2020-03-12 17:33
duplicate of: https://github.com/ansible/awx/issues/6269

**Closed as completed by ryanpetrello** 2020-03-12 17:33 UTC
Labels: type:bug
