### ISSUE TITLE
 Expected a dictionary of items but got type "unicode" Error on SAML Team Map

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#2509] opened 2018-10-23 00:57 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

When set SAML Team Map with JSON format, there is ` Expected a dictionary of items but got type "unicode" ` and cannot save the configuration.

##### STEPS TO REPRODUCE
 Set SAML Team Map as below.
```
{
    "saml_attr": "TestAttribute",
    "team_org_map": [
    {
        "team": "Blue",
        "organization": "Default1"
    },
    {
        "team": "Blue",
        "organization": "Default2"
    },
    {
        "team": "Blue",
        "organization": "Default3"
    },
    {
        "team": "Red",
        "organization": "Default1"
    },
    {
        "team": "Green",
        "organization": "Default1"
    },
    {
        "team": "Green",
        "organization": "Default3"
    }
  ]
}
```

##### EXPECTED RESULTS

There is no error and save the configuration correctly.

##### ACTUAL RESULTS
![screenshot from 2018-10-23 09-39-31](https://user-images.githubusercontent.com/4246532/47327436-3eb99680-d6a8-11e8-97f4-59cb19aa7345.png)

##### ADDITIONAL INFORMATION

Maybe this issue is related to another issue:  #2446

**Comment by matburt** [comment] 2018-10-26 01:36
Dupe of #2446

**Closed as completed by matburt** 2018-10-26 01:36 UTC
Labels: type:bug, component:ui
