### ISSUE TITLE
Not cleaning up after runner properly

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#4010] opened 2019-06-05 16:02 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

1. start AWX
2. run some jobs
3. 
```
bash-4.2$ find /tmp/ansible_runner_pi_*
/tmp/ansible_runner_pi_30tzw1rd
/tmp/ansible_runner_pi_30tzw1rd/tmpi1i_fzlu
/tmp/ansible_runner_pi_30tzw1rd/tmp0f1ilw2p
/tmp/ansible_runner_pi_30tzw1rd/tmp2ulnj3we
/tmp/ansible_runner_pi_30tzw1rd/tmp2ulnj3we/awx_56_8yem_qjj
/tmp/ansible_runner_pi_30tzw1rd/tmp2ulnj3we/.ansible
/tmp/ansible_runner_pi_30tzw1rd/tmp2ulnj3we/.ansible/tmp
/tmp/ansible_runner_pi_30tzw1rd/tmp8llrycho
/tmp/ansible_runner_pi_30tzw1rd/tmpqtoj18nq
/tmp/ansible_runner_pi_86d2289s
/tmp/ansible_runner_pi_86d2289s/tmp18frpsw3
/tmp/ansible_runner_pi_86d2289s/tmpomicqsjd
/tmp/ansible_runner_pi_86d2289s/tmpx6cizphr
/tmp/ansible_runner_pi_86d2289s/tmpx6cizphr/awx_55_v_wfspd3
/tmp/ansible_runner_pi_86d2289s/tmpx6cizphr/.ansible
/tmp/ansible_runner_pi_86d2289s/tmpx6cizphr/.ansible/tmp
/tmp/ansible_runner_pi_86d2289s/tmppcu0cerh
/tmp/ansible_runner_pi_86d2289s/tmpyu6aoyxd
/tmp/ansible_runner_pi_912tri2k
/tmp/ansible_runner_pi_912tri2k/tmppxn6_boj
/tmp/ansible_runner_pi_912tri2k/tmp_l83bqj2
/tmp/ansible_runner_pi_912tri2k/tmp_l83bqj2/_4__demo_project
/tmp/ansible_runner_pi_912tri2k/tmpgbz5b15_
/tmp/ansible_runner_pi_912tri2k/tmpgbz5b15_/awx_54_twtat2xa
/tmp/ansible_runner_pi_912tri2k/tmpgbz5b15_/.ansible
/tmp/ansible_runner_pi_912tri2k/tmpgbz5b15_/.ansible/tmp
/tmp/ansible_runner_pi_912tri2k/tmpgbz5b15_/.ansible/tmp/ansible-tmp-1559750417.89-227469902888907
/tmp/ansible_runner_pi_912tri2k/tmpgbz5b15_/.ansible/tmp/ansible-tmp-1559750417.89-227469902888907/AnsiballZ_setup.py
/tmp/ansible_runner_pi_912tri2k/tmpj4aj_sxx
/tmp/ansible_runner_pi_912tri2k/tmpaaauedm1
...
```

##### ENVIRONMENT
* AWX version: head of devel
* AWX install method: dev env
* Ansible version:  2.8-ish
* Operating System: F30 (host) CentOS 7 (container)
* Web Browser: doesn't matter

##### STEPS TO REPRODUCE

see above

##### EXPECTED RESULTS

no leftover crud in /tmp

**Comment by matburt** [comment] 2019-06-13 18:31
Given the issue is now one where something is holding a reference to the directory we are trying to delete I'm wondering if I can get someone (@Spredzy ?) to run `lsof +D /path` when the problem crops up to see if we can figure out what's holding the reference.

**Comment by chrismeyersfsu** [comment] 2019-06-21 18:01
From my testing of ansible-runner:master it seems like this problem is solved. What am I missing @matburt ?

**Comment by ryanpetrello** [comment] 2019-06-21 18:14
@chrismeyersfsu https://github.com/ansible/ansible-runner/issues/310#issuecomment-499888409

**Comment by ryanpetrello** [comment] 2019-07-01 14:34
Should be resolved by: https://github.com/ansible/awx/pull/4194

**Comment by kdelee** [comment] 2019-08-01 19:10
@ryanpetrello can you clarify if this is the bug that prompted https://github.com/ansible/awx/pull/4409/files ?

**Comment by ryanpetrello** [comment] 2019-08-01 19:11
@kdelee yes, https://github.com/ansible/awx/pull/4409/ should resolve this.

This has been stuck in `needs_test` for awhile, because we attempted to fix it in runner (and our approach didn't work), so we put it on the back burner (until now).

**Comment by kdelee** [comment] 2019-08-01 19:11
thanks

**Comment by Spredzy** [comment] 2019-08-04 21:42
This is fixed now.

**Closed as completed by Spredzy** 2019-08-04 21:42 UTC
Labels: type:bug, component:api
