### ISSUE TITLE
Execution Enviroments have no object_role to add permisions to.

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#11689] opened 2022-02-06 21:27 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
the api endpoint api/v2/execution_environments/ has no related object_roles. While all members of an org have read access to the global and organization execution environments, it is either an all or nothing approach when giving admin access to execution environments in an organization. This should behave like job templates, projects, and inventories, where you can give a user limited admin access to some objects but not all.

**Comment by AlanCoding** [comment] 2022-05-12 19:02
Closing as duplicate of https://github.com/ansible/tower/issues/5728

**Closed as completed by AlanCoding** 2022-05-12 19:02 UTC
Labels: type:enhancement, component:api

**Comment by jbradberry** [comment] 2022-05-12 21:21
@sean-m-sullivan I think the big question I have is, why is there a perceived need to be able to edit EEs often enough to warrant this change?  What is the actual scenario where this is needed?  The original intention of EEs is that they are pretty static, just the image url plus the podman pull behavior.  New images should get a new EE.

**Comment by sean-m-sullivan** [comment] 2022-05-12 22:05
@jbradberry 
I went and checked this out with and this is what I saw. 
Right now an Org admin can create/edit org execution environments no issue. 
An Org member can read and use Execution environments no issue. 
However if you wanted to give someone permission to add/edit a single Execution environment object, There is no option to do so. 

Right now people administering tower can give limited access for a user to use their own little sandbox, a single job template, project, credentials, and have fine grain control over Admin, Update, Use, and Read if they want to. 

I don't think many people are going to take advantage of this, however its good to have feature parity between objects to keep things consistent.

**Comment by AlanCoding** [comment] 2022-05-13 00:04
^ this seems congruent with other organization roles like `project_admin_role`. You want to allow a team to do their work, but don't want to give them org admin, which confers a boatload of permissions (that are hard to even enumerate). Just like some people are going to need to set up with SCM (even to just change branches), some people will be rolling images. You _mainly_ need images to add Ansible collections.

The "right" way to do stuff is that you don't download the whole community collection pack. You start with the minimal EE and add collections that are relevant to your organization's work. That will involve iteration kind of at the individual user level. They also might (justifiably) not want floating tags, so they'll have to rev the tag frequently. This requires editing an EE. This can be solved by either the org-level role of an object-level admin_role.

**Comment by sean-m-sullivan** [comment] 2022-05-13 00:35
Agreed, and I can't read the tower issue that you linked, but I created this issue because
A. After reviewing roles, I thought it was needed.
B. I had no clue how to implement it myself for a PR.

**Comment by jbradberry** [comment] 2022-05-13 14:56
> ^ this seems congruent with other organization roles like project_admin_role. You want to allow a team to do their work, but don't want to give them org admin, which confers a boatload of permissions (that are hard to even enumerate).

@sean-m-sullivan @AlanCoding there exists an `Organization.execution_environment_admin_role`.
