### ISSUE TITLE
Value for 'DISK2_SIZE_GB' expected to be an integer.

### ISSUE THREAD

**Issue by razbag** [ansible/awx#9620] opened 2021-03-18 22:59 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I create survey which is **not** required and set it integer and then when I run my template and do not define value for that Prompt AWX will failed with this ERROR

POST /api/v2/job_templates/11/launch/ 400
Value for 'DISK2_SIZE_GB' expected to be an integer.

![image](https://user-images.githubusercontent.com/18428312/111708120-b6328680-885e-11eb-9983-5c0fcd195515.png)

please see also survey for this Variable 

![image](https://user-images.githubusercontent.com/18428312/111708220-dfebad80-885e-11eb-8b44-5fcaffec0b5c.png)

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.18
* Operating System: Ubuntu 18 LTS
* Web Browser: Firefox

**Comment by razbag** [comment] 2021-03-19 12:28
And please also check from browser console 

Seems this is not working 

If a non-text variable (input type) is marked as optional, and is not filled in, no survey extra_var is passed to the playbook.


**
![image](https://user-images.githubusercontent.com/18428312/111779839-0b5ab080-88d0-11eb-8a3a-2096c941e9f1.png)
**

**Comment by ryanpetrello** [comment] 2021-03-19 17:16
cc @mabashian I think this is a duplicate of another issue

**Comment by mabashian** [comment] 2021-03-19 17:17
Same bug as https://github.com/ansible/awx/issues/9176

**Closed as completed by mabashian** 2021-03-19 17:17 UTC
Labels: type:bug
