### ISSUE TITLE
Job status references a missing job

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#10901] opened 2021-08-17 17:20 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I have a job that failed to deploy. The status message indicates the failure is due to a dependency task which failed, and references that job id. However when viewing jobs, the referenced job ID is not visible. Instead I have to manually enter the job URL into the browser.

### AWX version

19.3.0

### Installation method

minikube

### Modifications

no

### Operating system

Debian 10

### Web browser

Chrome

### Steps to reproduce

In my case, I'm trying to launch a job using a custom source control branch, and it appears that is causing the source control update to fail. Don't know why that's failing, but that issue isn't the one at hand.

### Expected results

Be able to see the referenced job in the job list

### Actual results

Cannot see referenced job in job list. Have to enter URL manually.

### Additional information

Here's the failed job reference (in the `status` field):
![image](https://user-images.githubusercontent.com/1826947/129771367-c6074e28-a737-4166-9d23-759da0d87c29.png)

Here's a list of my jobs, with job 547 missing:
![image](https://user-images.githubusercontent.com/1826947/129771589-f2f3e948-0a03-43e6-a0e1-2532f9154e86.png)

Here's me entering job 547's URL in the browser:
![image](https://user-images.githubusercontent.com/1826947/129771829-74b7d86c-f4eb-4f4d-b6eb-af3779af613f.png)

**Comment by wenottingham** [comment] 2021-08-17 19:48
See https://github.com/ansible/awx/issues/10513 - cc @AlanCoding

**Comment by AlanCoding** [comment] 2021-08-19 13:07
Yes, some project updates are not shown in the global jobs list as a UI decision. They should be linked from the job's "Details" tab

**Comment by shanemcd** [comment] 2021-08-20 17:16
Since this is (somewhat confusing) expected behavior, going to close this.

**Closed as completed by shanemcd** 2021-08-20 17:16 UTC
