### ISSUE TITLE
[ui_next] Job Output Elapsed timer is not functioning

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9624] opened 2021-03-19 12:25 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job Output Elapsed timer is not functioning. Neither real-time output nor completed job output.

##### STEPS TO REPRODUCE
1. Run a JT to completion and view the output page.
Note: Elapsed Timer

1. Start a long-running JT and view the output page.
Note: Elapsed Timer

##### ADDITIONAL INFORMATION
![Screen Shot 2021-03-19 at 8 24 35 AM](https://user-images.githubusercontent.com/12446869/111779466-8e5a1780-888c-11eb-9fc1-f5b2243c3ebd.png)

**Comment by ryanpetrello** [comment] 2021-04-06 17:32
duplicate of https://github.com/ansible/tower/issues/4922

**Closed as completed by ryanpetrello** 2021-04-06 17:32 UTC
Labels: type:bug, component:ui
