### ISSUE TITLE
Request for the schedule name variable when used in a workflow

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#3124] opened 2019-01-31 17:26 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Request for the schedule name variable when used in a workflow.  There is no 'tower_schedule_name' or 'workflow_schedule_name' variable that can be referenced when a workflow is launched by a schedule.

**Comment by ryanpetrello** [comment] 2019-09-06 18:21
To reproduce this:

1.  Set up a job template that runs this playbook:

https://github.com/ansible/test-playbooks/blob/master/debug_extra_vars.yml

Under the extra_vars, use:

![image](https://user-images.githubusercontent.com/214912/64451028-5677ee80-d0b1-11e9-844b-cb1359220573.png)

2.  Set up a workflow that runs this job template on a schedule (every minute, maybe?)

3.  Wait for the workflow to start and then for the *Job Template* to run and look at its output.  Notice that there's not an extra var that tells you the schedule name (but there *is* stuff like `"tower_workflow_job_name": "Testing 1 2 3",`):

![image](https://user-images.githubusercontent.com/214912/64451139-94751280-d0b1-11e9-84f7-6f5d61c0177b.png)

**Comment by kylecurtis-od** [comment] 2019-09-12 15:17
That so precisely states what I wanted... Thank you!

**Comment by rebeccahhh** [comment] 2019-09-17 18:50
@kylecurtis-od that PR merged yesterday covers this and it should be good to go :smiley:

**Comment by kdelee** [comment] 2019-09-17 19:09
Works for me, thanks!

**Closed as completed** 2019-09-17 20:53 UTC
Labels: type:enhancement, component:api
