### ISSUE TITLE
stdout of job not live updated in awx 

### ISSUE THREAD

**Issue by abdel-ops** [ansible/awx#10584] opened 2021-07-04 10:37 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

logs in job stdout not live updated , i check the code a and i find that thes react function onMessage (in jobOutput.jsx) how dispay the log is not defined anywhere , i don't know if that is the explanation of the issue.

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

launch a job in awx 17.1.0

### Expected results

log live updated

### Actual results

log updated after the job finished and not during the job running

**Comment by jakemcdermott** [comment] 2021-07-06 12:28
:wave: Hello. This appears to be a duplicate of https://github.com/ansible/awx/issues/9747

Updating from 17.1.0 -> 19.2.2 _may_ help with the bug you're seeing as we recently patched [a bug having to do with websocket reconnects](https://github.com/ansible/awx/pull/10397/files) but you'd need to check

**Closed as completed by jakemcdermott** 2021-07-06 12:28 UTC
