### ISSUE TITLE
workflow artifacts to be Passed between workflows inside a Super Workflow

### ISSUE THREAD

**Issue by Mithur-Niranjan** [ansible/awx#13843] opened 2023-04-12 14:09 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

We have a 2 WT's inside a Super workflow. 

We are collecting set_stats (artifacts) under one WT which needs to be passed to the Other WT. But Currently the Artifacts arent passed down to the Other WT inside the Super workflow. 

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

1. Configure a Super workflow with 2 WT's 
2. Set Artifact in WT1 and try to pass it to WT2 

### Current results

Artifacts set by WT1 will not be passed to the WT2

### Sugested feature result

Artifacts should persist in the Super workflow rather than the WT1 and WT2 inside the Super Workflow. 

Enable a Checkbox to Persist Artifacts between Workflows inside a Super workflow.

**Comment by AlanCoding** [comment] 2023-04-12 15:12
Is this solved by https://github.com/ansible/awx/pull/12223?

Is this issue a duplicate of the issue https://github.com/ansible/awx/issues/4481

**Comment by Mithur-Niranjan** [comment] 2023-04-13 06:04
Hi Alan, Checking on those Two,.

**Comment by fosterseth** [comment] 2023-04-19 17:59
@Mithur-Niranjan were you able to get artifacts working correctly in the nested workflow scenario?

**Comment by fosterseth** [comment] 2023-05-03 17:48
@Mithur-Niranjan hopefully you are able to resolve this issue, going to close this for now due to inactivity. Please open a new ticket if you believe there is a bug around workflows and artifacts

**Closed as completed by fosterseth** 2023-05-03 17:48 UTC
Labels: type:enhancement, component:api, component:ui, component:awx_collection, needs_triage, community
