### ISSUE TITLE
Feature: move to Ansible 2.7+ (2.8?) inventory plugins

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#171] opened 2017-09-14 19:30 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Ansible 2.4 laid down the framework for 'inventory plugins' (as opposed to inventory scripts).
As the existing inventory scripts are moved to plugins, AWX should move to them as well.

**Comment by wenottingham** [comment] 2017-09-25 19:06
This should also handle `meta: inventory_refresh` sanely.

**Comment by AlanCoding** [comment] 2017-10-03 15:03
Ansible docs link:

http://docs.ansible.com/ansible/latest/meta_module.html

My example: https://github.com/AlanCoding/permission-testing-playbooks/blob/master/meta_examples/refresh_inventory.yml

If you put the refresh _inside_ of a play, it appears to call the script, but the change does not take effect. I might need to raise an issue in core about that.

In AWX, the /script/ endpoint is called in this task.

**Comment by matburt** [comment] 2017-10-03 19:26
> This should also handle meta: inventory_refresh sanely.

This will probably handle the tower side of the inventory okay but will not call the actual backend that the user might expect. tower-cli or direct api access will work but we won't be able to re-run the inventory sync.

**Comment by AlanCoding** [comment] 2017-10-11 16:34
I have some notes on what we'll need to do here:

https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/plugins

For openstack, I've gone through an example use, and I know what we would need to swap out. Instead of just writing 1 file (the openstack auth), we'll need to write 2 files, where one of them is the inventory source that _points to_ the openstack auth. Our system isn't very well configured for writing to multiple files (even the managed_by_tower ones), so this will be interesting to implement.

But another thought occurred to me that's going to be a bigger deal - does this replace cloud credentials?

Consider what we do for openstack:

http://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html#utilizing-cloud-credentials

That setup was shared between inventory imports and running job templates. There was never a problem, because we were just setting an environment variable and laying down a file independently. However, the data we used to pass in via env var `OS_CLIENT_CONFIG_FILE` will now be made available through the `-i openstack.yml` inventory argument. The logical extrapolation is that we would alter our call pattern `ansible-playbook -i awxrest.py -i openstack.yml ...`. There would be enormous difficulty getting that figured out. Now cloud credentials would need some sort of soft link to inventory sources, which needs to be teased out when running against the inventory. Zombie hosts, huge RBAC problems...

Alternatively, say that we only use the plugin model for inventory imports and leave cloud credentials untouched. That means that we'll now be maintaining 2 different redundant paths for adding the openstack information to the run. This is in addition to the fact that the transition to inventory plugins will be superficial.

**Comment by AlanCoding** [comment] 2017-12-19 19:35
I created a project in Github for this

https://github.com/ansible/awx/projects/3

Also, this FYI, this is my work-in-progress branch for the goal of doing openstack

https://github.com/ansible/awx/compare/devel...AlanCoding:pluginification?expand=1

I still don't yet know how I'm going to connect the credential `clouds.yml` file to the inventory file, but I'm getting there.

**Comment by kdelee** [comment] 2018-11-26 19:27
Questions that came up from ansible core folks:
* If UI exposes inventory sync with inventory plugins, what is going to happen when things change across ansible versions?
    * In 2.9 we have plugin X with features a, b,c -- UI is built to that. But they are running with ansible 2.8, plugin X only has features a,b. What happens?
    * In 2.9 we have new plugin Z with features a, b,c -- UI is built to that. But they are running with ansible 2.8, plugin X does not exist. What happens?

@thaumos ^

**Comment by AlanCoding** [comment] 2018-11-26 19:35
Nothing should change in the UI, but the API will have to change to accommodate the plugins.

Right now, we primarily inject credentials for inventory imports via environment variables (and some associated credential files that env vars may point to, and other weirdness). The task at hand is to transition to logic where we build inventory files according to the plugin spec, which mostly contains the same content as we were previously putting in environment variables.

This should present no change to the user of the API or the UI. Since not all plugins are available for all Ansible versions, we will have to intelligently switch from the inventory script to the inventory plugin, based on both the version of Ansible, and the specific type of import happening.

> In 2.9 we have plugin X with features a, b,c -- UI is built to that. But they are running with ansible 2.8, plugin X only has features a,b. What happens?

It breaks, if the unrecognized parameter causes it to error. If not, it gets ignored.

**Comment by AlanCoding** [comment] 2018-11-26 19:39
> In 2.9 we have new plugin Z with features a, b,c -- UI is built to that. But they are running with ansible 2.8, plugin X does not exist. What happens?

I am already planning out how to deal with the reverse problem - in 2.6 plugin X exists, but in 2.5 does not exist.

To complete this, we will _have_ to have a compatibility table that we maintain internally. If detected Ansible version is 2.5, then we will use the pre-existing inventory script. There's no way around this, because AWX supports more versions of Ansible than what the plugins all exist in.

If a plugin was removed in 2.8, then I presume that the inventory script will not be maintained either. Essentially, what you're saying is that support for some cloud provider was deprecated and removed. Like Rackspace. We dealt with that at the time, and it was eventually removed as a built-in credential type. Azure also changed type. What you're describing sounds pretty much like these historical examples.

**Comment by wilmardo** [comment] 2018-11-27 15:15
What is the status of this issue? Has someone tried to tackle this yet?

**Comment by kdelee** [comment] 2019-02-12 21:32
@ryanpetrello re: your comment that we may be able to set some kind of "feature flag" to optionally enable this even if we don't want plugins enabled by default.

I think I would be comfortable with @AlanCoding getting his work in if:

We restrict plugins to only run if:
      a) a (optional) Boolean variable is provided to the inventory source `ansible_use_plugin` is set to `True`
AND
      b) the ansible version available to the inventory update is `ansible-devel`

What do you think about that as a way to keep the the framework from hanging out in a branch forever and allowing us to test it and make improvements to individual plugins?

Otherwise we need to focus on getting openstack and the framework split off from the `inventory_plugins` branch and wait for the openstack fixes to get released in ansible devel.

@AlanCoding I think we'd be better off just targeting enabling plugins for 2.8+ and lighten our load as far as having to do minor version checks on 2.7 and push these backports.

**Comment by kdelee** [comment] 2019-02-12 21:32
There are other ways you could implement that but the above seems like lowest impact (no change to models)

**Comment by ryanpetrello** [comment] 2019-02-12 23:11
@kdelee I'll defer to @wenottingham for an *official* decision, but everything you said above to me sounds totally sane, and also I think trying to boil the oceans and support all of this in 2.7 is going to drive you all insane; it's kind of a pointless exercise given the current state of the world.

Let's get some code in that starts to work on progressive support for this, and keep moving.

**Comment by kdelee** [comment] 2019-03-26 19:52
Going to file issues for outstanding plugins we have strong intentions of picking up in upcoming release:
- [x] vmware https://github.com/ansible/awx/issues/3508
- [x] foreman/sat6 https://github.com/ansible/awx/issues/3509
- [x] azure (needs PR to enable, but fixes are landing in 2.8 as we speak) https://github.com/ansible/awx/issues/3506
- [x] aws_ec2 https://github.com/ansible/awx/issues/3472

Will then close this issue when usage of plugins for 2.8+ is confirmed for 
- [x] gce
- [x] tower
- [x] openstack

**Comment by unlikelyzero** [comment] 2019-04-05 16:01
@kdelee what UI Testing remains for this feature?

**Comment by kdelee** [comment] 2019-04-08 14:46
@unlikelyzero UI elements were actually removed. I think we can close this issue now.

Ping me if you have more questions

**Closed as completed by kdelee** 2019-04-08 14:46 UTC
Labels: type:enhancement, component:api, component:ui
