### ISSUE TITLE
[ui_next] can't cancel a job from the job output view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8848] opened 2020-12-10 22:49 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
can't cancel a job from the job output view. Filing as a bughancement as this missing functionality might actually be desired

##### ADDITIONAL INFORMATION

<img width="616" alt="Screen Shot 2020-12-10 at 5 47 31 PM" src="https://user-images.githubusercontent.com/12446869/101839110-cc1e0600-3b0f-11eb-95c6-6f8e5be43f8b.png">

**Comment by mabashian** [comment] 2020-12-16 16:10
This is a duplicate of https://github.com/ansible/awx/issues/7657

**Comment by adpavlov** [comment] 2020-12-16 16:15
I would say that this is a bug as it was present in previous versions of awx

**Comment by akus062381** [comment] 2021-02-08 19:24
Still in needs test status

**Comment by unlikelyzero** [comment] 2021-02-12 15:47
@akus062381 will be taking this one.
1. Verify that a job in running status can be cancelled from the output view manually
2. Verify that when clicking on the cancel button after a job has already completed does not error. Launch a job, stay on output view, after job completes and in the same view, attempt to interact with the cancel job button.
3. Verify that the cancel button is disabled on previously completed jobs
4. Verify that the button is not actionable for auditors

**Comment by unlikelyzero** [comment] 2021-02-14 19:09
https://github.com/ansible/awx/issues/8207 is a dupe of this functionality

**Comment by akus062381** [comment] 2021-03-05 17:21
stubs in place, manually checked. 
Cancel button is not accessible from the output view after the job has completed- it is only viewable while job is running.

**Closed as completed by akus062381** 2021-03-05 17:21 UTC
Labels: type:bug, component:ui, type:feature
