### ISSUE TITLE
Openstack inventory sources: openstack.yml not overwritten by source variables

### ISSUE THREAD

**Issue by lperrin-obs** [ansible/awx#5840] opened 2020-02-06 15:08 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Openstack Inventory source with inventory plugin: The source variables are not overwritten by source variables

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.8.5
* Operating System: 
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Create an openstack inventory source with theses source variables, using the inventory plugin syntax:
```
plugin: openstack
expand_hostvars: false
private: true
inventory_hostname: name
```

##### EXPECTED RESULTS
The openstack.yml used by the job should be:
```
plugin: openstack
expand_hostvars: false
private: true
inventory_hostname: name
```

##### ACTUAL RESULTS
The openstack.yml stays as default value:
```
expand_hostvars: true
fail_on_errors: true
inventory_hostname: uuid
plugin: openstack
```

**Comment by wenottingham** [comment] 2020-02-07 18:06
cc @AlanCoding @jladdjr but I believe that certain default compatibility variables are automatically used - source variables are not automatically turned into plugin config variables.

**Comment by AlanCoding** [comment] 2020-02-07 19:16
Yes, that's exactly right. I think what @lperrin-obs wants is https://github.com/ansible/awx/issues/4306

**Comment by ryanpetrello** [comment] 2020-02-07 19:21
Yea that sounds about right to me, marking this as a duplicate of https://github.com/ansible/awx/issues/4306

**Closed as completed by ryanpetrello** 2020-02-07 19:21 UTC
Labels: type:bug
