### ISSUE TITLE
django.db.utils.OperationalError: server closed the connection unexpectedly for long jobs

### ISSUE THREAD

**Issue by muchafel** [ansible/awx#11391] opened 2021-11-25 10:53 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Dear AWX-team,
I am running AWX within an Openshift Cluster which connects to a external Postgres (managed service).
Trivial jobs are working fine, however longer jobs fail, because the connection to the database gets terminated (`Task was marked as running but was not present in the job queue, so it has been marked as failed.`). The jobs successfully execute several task, but after a while the seem to loose connection. 

On the logs of the task container I find that Postgres has terminated the connection on server side:
`[...]in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File “/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py”, line 84, in _execute return self.cursor.execute(sql, params) django.db.utils.OperationalError: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.`
caused by
`[...] django.db.utils.InterfaceError: connection already closed`

Postgres logs show that the connection was terminated by the client.
`[...] stderr F 2021-11-24 09:19:28 UTC [ansible-awx-648f997d96-vrkcp-71554-/usr/bin/awx-manage run_disp] [08006] [73428]: [1-1] user=XXX,db=XXX,client=XXX LOG:  could not receive data from client: Connection reset by peer`

We are in a **test**-environment with the following specs:
managed postgres: 3GB ram, 20 GB disc (I know pretty humble, but I checked that ram consumption is about 5%)
AWX: defaults
web: requests: {cpu: 1000m, memory: 2Gi}
task: requests: {cpu: 500m, memory: 1Gi}
execution environment: requests: {cpu: 500m, memory: 1Gi}
Within openshift, I don't see anything obvious w.r.t. resource shortage.

I thought about a problem with loadbalancing in postgres, but the problem is the same, if I address the DB IP directly in the config.

Maybe there is an issue with how psycopg2 sets up the connection? keepalives_idle or something?
I found a somewhat related issues here [#1178](https://github.com/ansible/awx/issues/1178), however not exactly my problem. 

==========
please let me know, if you don't consider this a bug. but rather technical support. However, I think this could be a bug, or at least an optional possibility for additional configuration (if it is actually an issue with keepalives_idle)

 

### AWX version

19.3.0 (Operator Version 0.13.0)

### Installation method

openshift

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

Can be reproduced consistently in our environemnt (external postgres, given resources) 
the error only occurs for jobs which run > 20 minutes. Problem does not always occur in the same step of the job. 

### Expected results

Long job runs run without connection termination, jobs don't fail

### Actual results

jobs fail with Task was marked as running but was not present in the job queue, so it has been marked as failed.

**Comment by yw5vruox7dr** [comment] 2022-03-14 17:12
We also encounter this problem since upgrading to awx 20.0.0

```
2022-03-14 16:43:55,710 ERROR    [-] awx.conf.settings Database settings are not available, using defaults.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
--
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:
--
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```
Credentials are correct. Connection is possible from task container.
The jobs are successfully executed but some of them end up in "Failed" state.

**Comment by rguhr** [comment] 2022-03-15 23:42
AWX 19.5.0 (& 20.0.0) is also affected.

Due to this bug jobs that have actually run successfully are marked as failed. This will trigger awx notifications for failed jobs. Most of our long-running (at least 38 minutes) system upgrade jobs run into this problem and alert us.

**Comment by yw5vruox7dr** [comment] 2022-03-15 23:59
I'm worried the ticket with this major django/db bug may have gone down a bit.
@ryanpetrello @AlanCoding, @fosterseth, @shanemcd can you bring this up in an upcoming dev/prio meeting?

**Comment by AlanCoding** [comment] 2022-03-16 00:50
This doesn't give enough information to definitively say, but I've been looking into other reports that could be the same thing.

I'm considering https://github.com/ansible/awx/pull/11905 as a blunt tool to cover all situations where postgres restarts or drops connections during long-running jobs.

> Database settings are not available, using defaults.

These logs are red-herrings. It prints the stack trace but it continues. The ultimate error that fails the worker responsible for the job is something else... but could be another `InterfaceError`.

**Comment by muchafel** [comment] 2022-03-16 12:29
Possibly helpful, but I can reproduce that restarting the pods (i.e. recreation of pods) solves the problem temporarily. I somewhat suspect that this might be related to active/passive switches from postgres (?)

**Comment by fosterseth** [comment] 2022-03-23 16:18
I found this discussion interesting. Hints that it could be a more broad wsgi issue https://forum.djangoproject.com/t/db-connection-closed-by-uwsgi-in-the-middle-of-handling-a-request/9875

@muchafel can you elaborate on the job failure a bit more? How long do the jobs run before hitting the error? have you noticed any relationship between numbers of jobs running simultaneously, or more generally the system load, with the errors?

**Comment by shanemcd** [comment] 2022-03-24 18:25
We're approaching this from a couple different angles:

- https://github.com/ansible/awx/pull/11905
- https://github.com/ansible/awx/pull/11955

**Comment by muchafel** [comment] 2022-04-14 06:24
@fosterseth sorry your reply got somehow lost on my side. I couldn't really find any systematic so far. The error seems to occur only for Jobs that run longer than 10 minutes. Sometimes the issue also occurs only after > 40 minutes.
I have checked the system load of my Openshift cluster at and it is rather ideling. I don't see any bottle-neck for the AWX containers either.  
I haven#t managed to check the "job-containers" though...

Do you think that this might be related to memory? I could try to beef up the AWX instance...

**Comment by Gaabaa** [comment] 2022-04-14 06:47
I had same issue with those long running jobs in 19.4.0. Suddenly when i upgraded to 20.1.0 all those issues are gone.

**Comment by ikhan2010** [comment] 2022-04-20 21:53
@shanemcd @sarabrajsingh is there any work left on this issue?  It seems it is fixed.  Can we call this complete, please?

**Comment by sarabrajsingh** [comment] 2022-04-21 02:30
backport for this has been merged. this issue needs QE signoff now.

**Comment by CFSNM** [comment] 2022-04-25 15:05
Launched YOLO job with installer suite. This suite has several long job runs that can validate this issue:

https://main-jenkins-csb-aap.apps.ocp-c1.prod.psi.redhat.com/job/AAPQA/job/Test_Tower_Yolo_Express/1135/

**Comment by CFSNM** [comment] 2022-04-26 18:19
Long jobs tests passed successfully. Closing this item

**Closed as completed by CFSNM** 2022-04-26 18:19 UTC
Labels: type:bug, component:api

**Comment by CFSNM** [comment] 2022-04-26 20:20
Issue validated from QE side

**Comment by CMPluto** [comment] 2023-03-10 20:17
@CFSNM , @AlanCoding  On Which AWX release this change has been implemented ?
I am using Awx 21.5.0 but still facing the same issue. 

**Job finished, but status is "Task was marked as running but was not present in the job queue, so it has been marked as failed."**

pls suggest

**Comment by AlanCoding** [comment] 2023-04-10 18:59
^ we've fixed some regressions that could cause that fairly recently. Maybe what you saw is an unrelated issue from that.
