### ISSUE TITLE
AWX 17.0.1 Output is only shown when reloading the page

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#9193] opened 2021-01-29 08:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Output is only shown when reloading the page

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17

##### EXPECTED RESULTS

Output should update automatically in browser

**Comment by hellcry37** [comment] 2021-01-29 10:33
up, this plague my awx also

**Comment by fullgore** [comment] 2021-01-29 11:46
Same: 

**Environment** : 
AWX version: 17.0.1
AWX install method: docker on linux
Ansible version: 2.10.3

**Comment by ryanpetrello** [comment] 2021-01-29 13:12
@jakemcdermott do you think this is related to https://github.com/ansible/awx/issues/8596, or another distinct issue?

**Comment by mabashian** [comment] 2021-01-29 16:44
Yea this sounds like a busted socket.  It could be #8596 or something slightly different.

**Comment by mabashian** [comment] 2021-01-29 16:47
I've got some work in flight for https://github.com/ansible/awx/issues/5906 and https://github.com/ansible/awx/issues/6612 that may impact this.  I'd prefer to let that land and see if it resolves this issue.  I expect to open up the PR early next week.

**Comment by jakemcdermott** [comment] 2021-01-29 17:16
:wave: hello 

Thanks for creating this issue.

The job output update bug you described is caused by a combination of https://github.com/ansible/awx/issues/8596 and possibly https://github.com/ansible/awx/issues/9085.

We'll have a fix for these bugs in one of the upcoming awx releases.

I'm closing this issue for now - we're tracking the work for this in the issues linked above. 

also see: 
  - https://github.com/ansible/awx/issues/8930
  - https://github.com/ansible/awx/issues/8973
  - https://github.com/ansible/awx/issues/9105
  - https://github.com/ansible/awx/issues/9112
  - https://github.com/ansible/awx/issues/9183

**Closed as completed by jakemcdermott** 2021-01-29 17:16 UTC
Labels: type:bug, component:ui

**Comment by aem12f** [comment] 2021-02-23 16:39
This is plaguing me as well running AWX 17.0.1
