### ISSUE TITLE
Source From A Project Doesn't Show Any Inventory

### ISSUE THREAD

**Issue by itamarshpak** [ansible/awx#1288] opened 2018-02-18 17:26 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI
 - Installer

##### SUMMARY
while attempting to create an inventory with a source from project, no inventories are shown in the list.
i tried yaml and ini files but it doesn't show it. 
also tried to change permissions but also 777 permissions didn't worked for me.
any ideas ? 

##### ENVIRONMENT
* AWX version: 1.0.3.41
* AWX install method: docker on linux (+docker compose)
* Ansible version:  2.4.3.0

##### STEPS TO REPRODUCE

created new directory under /var/lib/projects/awx
under it create ini\yaml files with some hosts 
created project in awx 
create inventory 
try to create source from project inventory with no success

**Comment by AlanCoding** [comment] 2018-02-19 13:13
Interesting, in basic terms I've replicated this issue.

 - Created new folder in projects folder
 - Created manual project using this folder
 - Observed that playbooks are populated at `/api/v2/projects/52/playbooks/`
 - Observed that inventories are not populated at `/api/v2/projects/52/inventories/`

I'm trying to remember if there was any problem that prevented us from being able to use manual projects in SCM inventories. I don't see any problem with it, but I don't think it has been tested much.

**Comment by matburt** [comment] 2018-02-19 13:18
I've been wondering about that one too... I was waiting to ask you after your return if that was some sort of artificial limitation imposed for some technical reason.

**Comment by itamarshpak** [comment] 2018-02-19 13:38
This is what I see. I have 2 files in the project directory one with '.ini' ending and one without.

![screen shot 2018-02-19 at 3 35 11 pm copy](https://user-images.githubusercontent.com/35530228/36380403-d3f20ff0-158a-11e8-9926-ff6afc6c77ec.png)

I also tried to write the name of the file, with no success

**Comment by AlanCoding** [comment] 2018-02-19 13:41
You can still type in the relative path manually.

It looks like the listing is due to a particular nuance with the serializers.

https://github.com/ansible/awx/blob/2c71a27630a20acf80f2b523aff62868b840ebc0/awx/api/serializers.py#L1063-L1095

With manual projects, we read directly from the file system in the request-response cycle. I probably hesitated copying that pattern for inventories, but since it creates this issue, I see no reason to not follow that same pattern. I don't know if inventory syncs with manual projects will encounter any other anticipated problems.

**Comment by itamarshpak** [comment] 2018-02-19 13:54
When I write the relative path (e.g: /var/lib/awx/projects/sensu/sensu.ini) I get this error : 
> data : [object Object] status : 400 headers : function (name){if(headersObj||(headersObj=parseHeaders(headers)),name){var value=headersObj[lowercase(name)];return void 0===value&&(value=null),value}return headersObj} config : [object Object] statusText : Bad Request xhrStatus : complete

Also tried ./sensu.ini and just sensu.ini

**Comment by AlanCoding** [comment] 2018-02-19 14:17
That's the absolute path, the relative path would just be `sensu.ini`. Although this might not be enough to solve it, I'll need to replicate the steps and see what the bad request message says.

**Comment by AlanCoding** [comment] 2018-02-19 14:20
The response message

```json
{"source_project":["Cannot use manual project for SCM-based inventory."]}
```

I wish the UI would surface this message up. It's also not filtering out manual projects in the project selector.

**Comment by AlanCoding** [comment] 2018-02-19 14:27
For some history, you can run `awx-manage inventory_import` on the CLI, and this will create a `file` type inventory source. I think the logic here was that a project-based inventory source that points to a manual project is redundant with the file inventory source functionality. Although, it is true that there's no way to use the file type from the API.

**Comment by keitalbame** [comment] 2019-06-06 16:19
Just caught this issue today.
I was able to import the inventory using the cli `awx-manage inventory_import`

**Comment by swaroopv2** [comment] 2020-04-08 17:23
Hello is there any update to this issue?

**Comment by sumkincpp** [comment] 2020-06-24 10:57
Issue relevant to latest AWX 12.0.0 and probably to AWX 13.0.0, sourcing from locally-created project isn't working with `SOURCE_PROJECT: Cannot use manual project for SCM-based inventory.` error.

**Comment by deveb** [comment] 2020-10-28 02:01
Same here. Any updates?

**Comment by pvvanilkumar** [comment] 2021-02-19 13:26
any updates.?

**Comment by shanemcd** [comment] 2021-04-09 14:21
Closing as I can't reproduce this issue. If you see this on a recent version of AWX please open a new issue.

**Closed as completed by shanemcd** 2021-04-09 14:21 UTC
Labels: type:bug, component:api

**Comment by bendem** [comment] 2021-04-09 16:22
The issue was still present in 17.x and the error message is still in devel, I can't test it right now, but either it's fixed and this issue should be left open to cleanup the unused validation code or it's not fixed and the issue should be left open. Would love to know in which commit this was fixed too.

**Comment by vmpr** [comment] 2021-10-01 09:48
still have the problem in 19.3.0 :( just closing it is a strange behaviour if it is not fixed :( @shanemcd

**Comment by arsdragonfly** [comment] 2025-04-13 21:58
> For some history, you can run `awx-manage inventory_import` on the CLI, and this will create a `file` type inventory source. I think the logic here was that a project-based inventory source that points to a manual project is redundant with the file inventory source functionality. Although, it is true that there's no way to use the file type from the API.

Why make this arbitrary restriction? besides you're now [deprecating custom inventory scripts](https://docs.ansible.com/ansible-tower/latest/html/administration/custom_inventory_script.html) so project-based is our only option, and you're putting arbitrary restriction on it (using manual projects should totally be an option) which doesn't make sense to me.
