### ISSUE TITLE
Create Schedule, page display issues? 

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#235] opened 2017-09-21 07:43 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Is the page not rendering correctly?

```
{{ schedulerName || "ADD SCHEDULE"}}{{ schedulerName || "EDIT SCHEDULE"}}
```

```
{{ rrule_nlp_description }}
```

![screenshot from 2017-09-21 00-32-43](https://user-images.githubusercontent.com/1614425/30684110-d229b21a-9e64-11e7-8dbd-d0eaaecb1302.png)

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by matburt** [comment] 2017-09-21 13:00
dupe of https://github.com/ansible/awx/issues/164

**Closed as completed by matburt** 2017-09-21 13:00 UTC
