### ISSUE TITLE
ISSUE: Call to /api/v2/job_templates/12/launch failed. POST returned status: 504.

### ISSUE THREAD

**Issue by codesupremo** [ansible/awx#6492] opened 2020-03-31 01:45 UTC
##### ISSUE TYPE

 - Job Template Run - POST returned status: 504

##### COMPONENT NAME

 - API

##### ENVIRONMENT
* AWX version: How to know the version? This is a newly installed AWX as well
* AWX install method: docker on Linux
* Ansible version:  2.9.6
* Operating System: CentOS 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE
The issue will be reproduced when Launching the Job Template

##### ACTUAL RESULTS
-  Call to /api/v2/job_templates/12/launch failed. POST returned status: 504.

##### ADDITIONAL INFORMATION

GUYS, PLEASE HELP ME WITH THIS ISSUE. :( Let me know if you need more info.

**Comment by ryanpetrello** [comment] 2020-03-31 01:57
<img width="223" alt="image" src="https://user-images.githubusercontent.com/214912/77978957-58193600-72d1-11ea-800b-710056f6090c.png">

The "i" icon in the top right will show you the AWX version.  Can you share it?

**Comment by codesupremo** [comment] 2020-03-31 07:05
HI Ryanpetrello,

The version is AWX 9.3.0 and Ansible 2.9.5. Hope you can help me with this issue. Thanks2x

**Comment by StepBee** [comment] 2020-03-31 08:22
@codesupremo the AWX 9.3.0 devel installation is broken, just install 9.2.0 or follow #6477 - i noticed in #6460 as well and got the recommendation.

**Comment by codesupremo** [comment] 2020-03-31 08:35
Hi Stepbee, 

Do you have the steps on downgrading it to 9.2.0? Thanks a lot

**Comment by ryanpetrello** [comment] 2020-04-03 17:23
@codesupremo @StepBee,

I suspect you all ended up deploying a version of the 9.3.0 image with some of the newer code that landed in `devel` (representing our move from RabbitMQ to Redis).  The 504 you're encountering is likely because you've got code attempting to talk to RabbitMQ when it should be communicating with Redis (or vice-versa).  Would you mind trying a 10.0.0 deployment?  I expect it will resolve your problems.

**Comment by codesupremo** [comment] 2020-04-03 17:25
Hi @ryanpetrello , Thanks for the help. It’s working perfectly fine now using the latest release 10.0.0 :)

**Comment by ryanpetrello** [comment] 2020-04-03 17:32
Thanks for reporting back @codesupremo - I'm gonna close this one.

**Closed as completed by ryanpetrello** 2020-04-03 17:32 UTC
Labels: component:api

**Comment by StepBee** [comment] 2020-04-03 18:52
@ryanpetrello i can confirm my fresh installation of 10.0.0 works like a charm as well. Thanks!

**Comment by anme98** [comment] 2020-05-04 09:00
@ryanpetrello Thanks for the info. Worked for me as well!
