### ISSUE TITLE
Unable to edit survey as admin of job_template after it's created by the admin user

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#905] opened 2018-01-02 16:39 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
When a job_template is created by the admin user and the admin user creates a survey no other users with admin perms on the job_template can edit the survey.

##### ENVIRONMENT
* AWX version: 1.0.1.8
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

1. log in as admin
2. create a new job_template
3. save job_template
4. add a survey and save
5. assign a local user admin rights to job_template
6. log out
7. log in as another local user who has admin rights over job_template
8. try and edit survey

##### EXPECTED RESULTS

Org admin or user that has admin rights to job_template can edit survey

##### ACTUAL RESULTS

Error! You do not have permission to perform this action.

**Comment by AlanCoding** [comment] 2018-02-07 17:48
I have followed the steps to reproduce here, and I cannot reproduce this bug.

I would put my money on this being a duplicate of some other related issues about permission problems with editing job templates. Thank you for the report, please let me know if you still see the issue after pulling new code.

**Closed as completed by AlanCoding** 2018-02-07 17:48 UTC
Labels: type:bug, component:api
