### ISSUE TITLE
Slack notification is not working for job completion (success or failure) but works fine for workflow job

### ISSUE THREAD

**Issue by tchia04** [ansible/awx#753] opened 2017-12-01 01:51 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Slack notification is not working for job completion (success or failure) but works fine for workflow job 

##### ENVIRONMENT
* AWX version: 1.0.1.234 
* AWX install method: docker on linux, 
* Ansible version:  2.4.1.0
* Operating System: Redhat 7
* Web Browser: chrome

##### STEPS TO REPRODUCE

I created a slack chat bot (not using webhook) following the instruction from https://www.linkedin.com/pulse/slack-chat-bot-ansible-tower-rahul-natarajan/

I got the token from slack and it into the Slack notification in AWX.  
The test notificaiton with the bell alarm icon works fine.  However when I associate a job with the slack notificaition, nothing is send to slack when the job completes successful or in error.

##### EXPECTED RESULTS

I expect a message send to the slack channel defined according to the success/fail setting defined in the job template->notification screen.

##### ACTUAL RESULTS

No message appear in the slack channel configured.

**Comment by matburt** [comment] 2017-12-01 13:02
hmm, I can't reproduce this... everything seems to work fine for me. Are there any errors in the console?

**Comment by jmarci** [comment] 2017-12-06 10:56
Appears to be same issue as #711, Success or failure notification settings not being saved and also not functioning.
Appears to be database related, something missing in database field/table missing. Maybe docker installer is broken?

**Comment by matburt** [comment] 2017-12-08 21:02
We'll close this as a dupe of #711 then

**Closed as completed by matburt** 2017-12-08 21:02 UTC
Labels: type:bug, component:api
