### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'host')

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#12506] opened 2022-07-12 09:44 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Opening the output of a job, e.g. https://awx.example.com/#/jobs/playbook/978593/output, may result in the following error:

```
TypeError: Cannot read properties of undefined (reading 'host')
```

But it's not always reproducible.

### AWX version

21.2.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.11.7

### Operating system

Debian 11

### Web browser

Firefox

### Steps to reproduce

Opening a job's output, e.g. https://awx.example.com/#/jobs/playbook/978593/output.

But it's not always reproducible.

### Expected results

The job output is shown.

### Actual results

```
 TypeError: Cannot read properties of undefined (reading 'host')
    at Rae (https://awx.example.com/static/js/main.ae6cdd21.js:2:3360278)
    at oo (https://awx.example.com/static/js/main.ae6cdd21.js:2:1095837)
    at Ks (https://awx.example.com/static/js/main.ae6cdd21.js:2:1148137)
    at Ol (https://awx.example.com/static/js/main.ae6cdd21.js:2:1135378)
    at Tl (https://awx.example.com/static/js/main.ae6cdd21.js:2:1135306)
    at El (https://awx.example.com/static/js/main.ae6cdd21.js:2:1135169)
    at yl (https://awx.example.com/static/js/main.ae6cdd21.js:2:1132135)
    at https://awx.example.com/static/js/main.ae6cdd21.js:2:1081629
    at t.unstable_runWithPriority (https://awx.example.com/static/js/main.ae6cdd21.js:2:1177891)
    at Vi (https://awx.example.com/static/js/main.ae6cdd21.js:2:1081406)
```

**Comment by kialam** [comment] 2022-07-13 18:00
@anxstj I have been unable to reproduce this issue. Do you have a set of instructions to accurately reproduce the bug you're seeing?

**Comment by shanemcd** [comment] 2022-07-20 16:26
@anxstj Did you clean and rebuild the UI after upgrading? https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md#clean-and-build-the-ui Will wait to hear back another week or so before closing this.

**Comment by anxstj** [comment] 2022-07-20 17:50
Yes, I did that.

Could this be caused by slow database queries?

**Comment by akus062381** [comment] 2022-08-03 15:54
Hi @anxstj! 
Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Closed as completed by akus062381** 2022-08-03 15:54 UTC
Labels: type:bug, component:ui

**Comment by aimcod** [comment] 2022-09-27 11:10
I am able to consistently replicate this using awx-operator 0.29.0 and  AWX 21.6.0 on a Kubernetes K8 Cluster with an external postgres database.

Any job I run, if I want to see the json output of a task, I get this.
![image](https://user-images.githubusercontent.com/87487380/192510359-7d0c4dc1-685b-4f2f-bb01-0cf123a88377.png)

If I refresh the page, I can see the output of the task. Selecting another task shows the same error until I refresh again.

I can share my setup, if that helps.

**Comment by deanso** [comment] 2022-09-30 14:53
@aimcod 
I have the same issue (only on running jobs) but not on every task output. It appears to manifest if a task output has multiple lines (> 10).
If the jobs has ended, I don't get the error. 
Currently using the same versions as you: operator 029.0 and awx 21.6. 

Will be trying awx 20.x when I have some time.

**Comment by aimcod** [comment] 2022-09-30 15:49
@deanso are you running awx on an external/remote database?

**Comment by deanso** [comment] 2022-09-30 18:00
I have tested it today on internal postgres db pod on a k8s cluster. But I doubt it's a resourcing issue.

Also have another instance on an external RDS database, so I could try it on that instance next week.

**Comment by 06seasparkle** [comment] 2022-09-30 19:33
Hi ,
we are experiencing the same error while scheculing inventory at AWX 21.6.1 version on docker-compose 
can you help us,please ?

TypeError: Cannot read property 'ask_labels_on_launch' of undefined
TypeError: Cannot read property 'ask_labels_on_launch' of undefined
    at D9 (https://*****static/js/main.1b869fd4.js:2:2542040)
    at oo (https://******/static/js/main.1b869fd4.js:2:850659)
    at Ks (https://*******/static/js/main.1b869fd4.js:2:902959)
    at Al (https://*********/static/js/main.1b869fd4.js:2:890200)
    at Tl (https://*****/static/js/main.1b869fd4.js:2:890128)
    at El (https://********/static/js/main.1b869fd4.js:2:889991)
    at yl (https://*******/static/js/main.1b869fd4.js:2:886957)
    at https://******/static/js/main.1b869fd4.js:2:836451

**Comment by deanso** [comment] 2022-10-03 11:56
@aimcod , just tested this, but I have this issue also on an external RDS database.

**Comment by 0xbentang** [comment] 2022-10-13 01:19
Same error with awx-operator 0.29.0 and AWX 21.6.0 and internal postgres. Can we reopen this issue?

The error is very consistent. Refreshing the page works but it's very annoying

**Comment by omgololo** [comment] 2022-11-15 07:53
+1 here
Error definitely depends on the stdout's size - we are unable to open a specific message inside a very large stdout (thousands of llines) with debug verbosity. A device is being configured with a set of wi-fi commands, all in one block
In stdout it is seen as: 
changed: [10.193.xx.xx] => {
    "changed": true,
    "invocation": {"
......
.....
And when we click on such a message to open it and see additional info - the discussed error pop-ups - and we found no workaround here, tried different browsers, looking through code even - with no success at all.

**Comment by kialam** [comment] 2022-11-15 21:26
@anxstj et al this may be resolved with this PR (https://github.com/ansible/awx/pull/13148). I am happy to re-open if someone can confirm that this is still an issue with the latest `devel`.
