### ISSUE TITLE
Hosts not showing in smart inventory when source inventory script is used

### ISSUE THREAD

**Issue by BenoitCattie** [ansible/awx#3934] opened 2019-05-21 09:45 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONANT NAME
 - UI
- API

##### SUMMARY
When using an inventory source script with smart inventory, hosts are not listed on the smart inventory.

##### ENVIRONMENT
* AWX version: 3.0.1 (reproductible on 2.1.2 too)
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Windows
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create one inventory with script as source.
Create one smart inventory with smart host filter name:'MYHOST'. (MYHOST is showing on the search results). Click Save.
Go to HOSTS tab : MYHOST is not listed.

##### EXPECTED RESULTS

MYHOST listed on the HOSTS tab.

(Please note, that using a static inventory and localhost as host filter is working as expected)

##### ACTUAL RESULTS

MYHOST is not listed on the HOSTS tab.
Is also not listed on API.

**Comment by AlanCoding** [comment] 2019-05-30 19:28
I'd like to see if I can reproduce to confirm this issue, but I will need more information.

> Create one inventory with script as source.

Let me first confirm the obvious - did you update this inventory before you created the smart inventory (from other things you wrote, I think probably so, I want to be sure).

> Create one smart inventory with smart host filter name:'MYHOST'. (MYHOST is showing on the search results). Click Save.

Let me also confirm that the smart inventory is in the same organization as the inventory that ran the script-based update. If they are not in the same organization you cannot do this.

With that out of the way, I would like to narrow in on the fact that MYHOST shows up in the search results but not after you save the smart inventory. Could you open up the network tab in the developer console for Chrome (right click, inspect, network, clear). With that open, perform the search in the screen where you edit the host filter and see the MYHOST result, then copy the URL from the request in the network console. Then save the inventory, copy the URL from that entry. Then share those 2 URLs with us, so that we see the syntax being sent to the backend.

**Comment by awithrow9** [comment] 2019-06-28 17:54
@BenoitCattie can you reply to @AlanCoding 's question above?

**Comment by BenoitCattie** [comment] 2019-07-01 09:12
Hello,

sorry for the late reply.

> did you update this inventory before you created the smart inventory 

Yes. I do not know if it can be related, but no host are reachable (it's a LAB environment)

> Let me also confirm that the smart inventory is in the same organization as the inventory that ran the script-based update. If they are not in the same organization you cannot do this.

Yes, I only have one Org.

I'm looking for Chrome URL after restarting my lab environment.

Regards
Benoit

**Comment by AlanCoding** [comment] 2019-07-01 11:44
I can follow those steps in my server and I do not produce the issue. Take a script such as:

https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/scripts/foobar.py

I replace "foobar" with "foo1", created an inventory in the "alan" organization, added a source using that script, updated it, confirmed "foo1" in this inventory, created a smart inventory with "name:foo1" and then saved it.

The UI does a conversion to add "icontains", but the host shows up in the hosts of the smart inventory here, and in the HOSTS tab

![Screen Shot 2019-07-01 at 7 43 38 AM](https://user-images.githubusercontent.com/1385596/60433969-0de51600-9bd4-11e9-9261-b7793a72e53e.png)

**Comment by unlikelyzero** [comment] 2021-02-03 16:37
Retest with https://github.com/ansible/awx/issues/3934#issuecomment-507230680

**Comment by unlikelyzero** [comment] 2021-03-05 13:42
@akus062381 to retest this using https://github.com/ansible/awx/issues/3934#issuecomment-507230680

**Comment by akus062381** [comment] 2021-03-18 20:07
@unlikelyzero since the Source tab no longer allows the user to add a source to an inventory, I believe this issue would no longer be relevant. Closing.

**Closed as completed by akus062381** 2021-03-18 20:07 UTC
Labels: type:bug, component:ui
