### ISSUE TITLE
Datetime advanced search- datetime format requirement restrictive

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11469] opened 2021-12-15 17:54 UTC
When a user wants to perform an advanced search involving any kind of datetime value, unless the user inputs the search criteria in exactly the right format, the UI throws a 400 error telling the user to add the information in a specific format.

["'12/15/2021' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]

There are a couple of things about this that would potentially frustrate a user:

- the chances of a user knowing the exact, down-to-the-minute datetime information for a resource are extremely small

- a user would expect they could enter a date in a more conventional format and receive a valid result
        Possible suggestion: offer a more conventional way of searching and add a tooltip for the user so they know what format to use

- the purpose of searching for something, many times, is to see if it exists. But the way this is designed, a user can't just say "i want to search for any schedules associated with this job template from November 10th". Instead, the user would a) not be able to search by datetime at all, or b) would have to make an unknown number of guesses about possible datetimes, which is not reasonable, given the fact that seconds are included in the required input.

- icontains is not an offered lookup type. I would think a user would like to add the following search, with icontains in the lookup type field:
![image](https://user-images.githubusercontent.com/63685497/146238463-22454e5a-8595-462e-836b-8121e8f51ab8.png)
But this is not currently possible.

Here is a video to further illustrate:

https://user-images.githubusercontent.com/63685497/146238797-bad82519-fa38-46d9-a79a-b7a7de5a159e.mp4

This happens in any of the resource lists that give the user the ability to search by "Created By", "Modified By", "Next Run", "Last Run", and etc

**Comment by nixocio** [comment] 2021-12-15 19:19
This one seems like a dupe of https://github.com/ansible/awx/issues/9956

**Comment by akus062381** [comment] 2021-12-15 19:33
@nixocio it's not exactly the same. but if you "zoom out", the larger issue is related

**Comment by mabashian** [comment] 2022-05-02 15:15
I think this and https://github.com/ansible/awx/issues/7155 are dupes.  Going to close https://github.com/ansible/awx/issues/7155 in favor of this one since this one has more context.

**Comment by AlexSCorey** [comment] 2022-05-19 19:26
Closing in favor of https://github.com/ansible/awx/issues/9956

**Closed as completed by AlexSCorey** 2022-05-19 19:26 UTC
Labels: type:bug, component:ui
