### ISSUE TITLE
Empty Body for Custom Webhook Notifications on Project Sync

### ISSUE THREAD

**Issue by hjkatz** [ansible/awx#9168] opened 2021-01-26 15:39 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have configured a Webhook Notification template with custom bodies for each message. The webhook is a slack webhook and the body is a slack message (because the implemented Slack notifications is _extremely_ limited). The notification works properly with a Job Template.

Where is the body? I think it's missing.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: kubernetes

##### STEPS TO REPRODUCE

* Create a Project
* Create a Notification Template (of type Webhook) with custom body
* Turn on the Notification Template for the Project
* Sync the Project

##### EXPECTED RESULTS

I expect to see the Notification on (started, success, failed) to run with the custom body defined on the Notification Template.

##### ACTUAL RESULTS

The body is missing.

##### ADDITIONAL INFORMATION

Notification Template: `/api/v2/notification_templates/4/`

```json
{
    "id": 4,
    "type": "notification_template",
    "url": "/api/v2/notification_templates/4/",
    "related": { ... },
    "summary_fields": { ... },
    "created": "2021-01-19T22:39:32.329526Z",
    "modified": "2021-01-26T14:43:10.292602Z",
    "name": "Test Slack Webhook",
    "description": "",
    "organization": 1,
    "notification_type": "webhook",
    "notification_configuration": {
        "username": "",
        "password": "",
        "url": "REDACTED (slack incoming webhook url)",
        "disable_ssl_verification": false,
        "headers": {},
        "http_method": "POST"
    },
    "messages": {
        "started": {
            "message": "",
            "body": "{\n    \"attachments\": [\n        {\n            \"color\": \"#dddddd\",\n            \"blocks\": [\n                {\n                    \"type\": \"section\",\n                    \"text\": {\n                        \"type\": \"mrkdwn\",\n                        \"text\": \":rocket: Launched <{{url}}|Job#{{job.id}}: *{{job.name}}*>\"\n                    }\n                },\n                {\n                    \"type\": \"divider\"\n                },\n                {\n                    \"type\": \"section\",\n                    \"text\": {\n                        \"type\": \"mrkdwn\",\n                        \"text\": \" • *User:* <@{{job.summary_fields.created_by.username}}>\\n • *Project:* {{job.summary_fields.project.name}}\\n • *Playbook:* `{{job.playbook}}`\\n • *Inventory:* {{job.summary_fields.inventory.name}}\"\n                    }\n                }\n            ]\n        }\n    ]\n}"
        },
        "success": {
            "message": "",
            "body": "{\n    \"attachments\": [\n        {\n            \"color\": \"#5CB589\",\n            \"blocks\": [\n                {\n                    \"type\": \"section\",\n                    \"text\": {\n                        \"type\": \"mrkdwn\",\n                        \"text\": \":tada: Success! <{{url}}|Job#{{job.id}}: *{{job.name}}*>\"\n                    }\n                },\n                {\n                    \"type\": \"divider\"\n                },\n                {\n                    \"type\": \"section\",\n                    \"text\": {\n                        \"type\": \"mrkdwn\",\n                        \"text\": \" • *User:* <@{{job.summary_fields.created_by.username}}>\\n • *Project:* {{job.summary_fields.project.name}}\\n • *Playbook:* `{{job.playbook}}`\\n • *Inventory:* {{job.summary_fields.inventory.name}}\"\n                    }\n                }\n            ]\n        }\n    ]\n}"
        },
        "error": {
            "message": "",
            "body": "{\n    \"attachments\": [\n        {\n            \"color\": \"#961D13\",\n            \"blocks\": [\n                {\n                    \"type\": \"section\",\n                    \"text\": {\n                        \"type\": \"mrkdwn\",\n                        \"text\": \":x: Failed! <{{url}}|Job#{{job.id}}: *{{job.name}}*>\"\n                    }\n                },\n                {\n                    \"type\": \"divider\"\n                },\n                {\n                    \"type\": \"section\",\n                    \"text\": {\n                        \"type\": \"mrkdwn\",\n                        \"text\": \" • *User:* <@{{job.summary_fields.created_by.username}}>\\n • *Project:* {{job.summary_fields.project.name}}\\n • *Playbook:* `{{job.playbook}}`\\n • *Inventory:* {{job.summary_fields.inventory.name}}\"\n                    }\n                }\n            ]\n        }\n    ]\n}"
        },
        "workflow_approval": { ... all defaults ... }
    }
}
```

Notification from Job Template: `/api/v2/jobs/2040/notifications/`

```json
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 22,
            "type": "notification",
            "url": "/api/v2/notifications/22/",
            "related": {
                "notification_template": "/api/v2/notification_templates/4/"
            },
            "summary_fields": {
                "notification_template": {
                    "id": 4,
                    "name": "Test Slack Webhook",
                    "description": ""
                }
            },
            "created": "2021-01-26T14:43:23.222076Z",
            "modified": "2021-01-26T14:43:23.222110Z",
            "notification_template": 4,
            "error": "",
            "status": "successful",
            "notifications_sent": 1,
            "notification_type": "webhook",
            "recipients": "REDACTED (slack incoming webhook url)",
            "body": {
                "attachments": [
                    {
                        "color": "#dddddd",
                        "blocks": [
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": ":rocket: Launched <https://awx-sandbox.squarespace.net/#/jobs/playbook/2040|Job#2040: *Testing - Example Job*>"
                                }
                            },
                            {
                                "type": "divider"
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": " • *User:* <@admin>\n • *Project:* Shared Ansible Repo\n • *Playbook:* `playbooks/awx-example/example.yaml`\n • *Inventory:* Shared Ansible Repo - inventory.stage"
                                }
                            }
                        ]
                    }
                ]
            }
        },
        {
            "id": 23,
            "type": "notification",
            "url": "/api/v2/notifications/23/",
            "related": {
                "notification_template": "/api/v2/notification_templates/4/"
            },
            "summary_fields": {
                "notification_template": {
                    "id": 4,
                    "name": "Test Slack Webhook",
                    "description": ""
                }
            },
            "created": "2021-01-26T14:44:34.178597Z",
            "modified": "2021-01-26T14:44:34.178633Z",
            "notification_template": 4,
            "error": "",
            "status": "successful",
            "notifications_sent": 1,
            "notification_type": "webhook",
            "recipients": "REDACTED (slack incoming webhook url)",
            "body": {
                "attachments": [
                    {
                        "color": "#5CB589",
                        "blocks": [
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": ":tada: Success! <https://awx-sandbox.squarespace.net/#/jobs/playbook/2040|Job#2040: *Testing - Example Job*>"
                                }
                            },
                            {
                                "type": "divider"
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": " • *User:* <@admin>\n • *Project:* Shared Ansible Repo\n • *Playbook:* `playbooks/awx-example/example.yaml`\n • *Inventory:* Shared Ansible Repo - inventory.stage"
                                }
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

Notifications from Project Sync: `/api/v2/notifications/26/`

```json
{
    "id": 26,
    "type": "notification",
    "url": "/api/v2/notifications/26/",
    "related": {
        "notification_template": "/api/v2/notification_templates/4/"
    },
    "summary_fields": {
        "notification_template": {
            "id": 4,
            "name": "Test Slack Webhook",
            "description": ""
        }
    },
    "created": "2021-01-26T15:11:25.101478Z",
    "modified": "2021-01-26T15:11:25.101511Z",
    "notification_template": 4,
    "error": "Error sending notification webhook: 400",
    "status": "failed",
    "notifications_sent": 0,
    "notification_type": "webhook",
    "recipients": "REDACTED (slack incoming webhook url)",
    "body": ""
}
```

**Comment by hjkatz** [comment] 2021-01-26 16:04
The same thing occurs when the Organization has the Notification enabled and then an Inventory Sync is initiated:

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 38,
            "type": "notification",
            "url": "/api/v2/notifications/38/",
            "related": {
                "notification_template": "/api/v2/notification_templates/4/"
            },
            "summary_fields": {
                "notification_template": {
                    "id": 4,
                    "name": "Test Slack Webhook",
                    "description": ""
                }
            },
            "created": "2021-01-26T16:02:47.745619Z",
            "modified": "2021-01-26T16:02:47.745652Z",
            "notification_template": 4,
            "error": "Error sending notification webhook: 400",
            "status": "failed",
            "notifications_sent": 0,
            "notification_type": "webhook",
            "recipients": "REDACTED (slack incoming webhook url)",
            "body": ""
        }
    ]
}
```

**Comment by hjkatz** [comment] 2021-01-26 16:06
The same thing occurs when the Inventory Source has the Notification enabled and then an Inventory Source Sync is initiated:

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 41,
            "type": "notification",
            "url": "/api/v2/notifications/41/",
            "related": {
                "notification_template": "/api/v2/notification_templates/4/"
            },
            "summary_fields": {
                "notification_template": {
                    "id": 4,
                    "name": "Test Slack Webhook",
                    "description": ""
                }
            },
            "created": "2021-01-26T16:05:26.318731Z",
            "modified": "2021-01-26T16:05:26.318778Z",
            "notification_template": 4,
            "error": "Error sending notification webhook: 400",
            "status": "failed",
            "notifications_sent": 0,
            "notification_type": "webhook",
            "recipients": "REDACTED (slack incoming webhook url)",
            "body": ""
        }
    ]
}
```

**Comment by jladdjr** [comment] 2021-04-30 23:46
Did some testing with this and am not able to reproduce.

1. Started a [simple server](https://gist.github.com/jladdjr/17ffdb498298652f8e87ac532f5ce1c7) on the awx container that prints the body that gets POST-ed.
2. As a sanity check, first created a webhook notification template _without providing a custom body_, attached to a regular job and to a project. Verified that I received a body in both cases:

**job** payload received:
```
{'created_by': 'admin',
 'credential': 'Credential - SockAir�',
 'extra_vars': '{}',
 'finished': '2021-04-30T21:41:19.256259+00:00',
 'hosts': {'HostClothesHearing542532642499763532550573403488232670691098576485760777486': {'changed': 0,
                                                                                           'dark': 0,
                                                                                           'failed': False,
                                                                                           'failures': 0,
                                                                                           'ignored': 0,
                                                                                           'ok': 1,
                                                                                           'processed': 1,
                                                                                           'rescued': 0,
                                                                                           'skipped': 0}},
 'id': 11,
 'inventory': 'Inventory - TechnologyValuable�',
 'limit': '',
 'name': 'JobTemplate - RevolutionInspector�',
 'playbook': 'ping.yml',
 'project': 'Project - PhysicsDifficulty䏼',
 'started': '2021-04-30T21:41:11.518678+00:00',
 'status': 'successful',
 'traceback': '',
 'url': 'https://towerhost/#/jobs/playbook/11'}
```

**project** payload received:
```
{'created_by': 'admin',
 'finished': '2021-04-30T22:58:10.231668+00:00',
 'id': 14,
 'name': 'Project - PhysicsDifficulty䏼',
 'started': '2021-04-30T22:58:01.748033+00:00',
 'status': 'successful',
 'traceback': '',
 'url': 'https://towerhost/#/jobs/project/14'}
```

3. Set a trivial custom body for the notification template (`{'success': {'body': '{"foo": "bar"}'}}`) and confirmed that both for the job and project sync, the simple webserver received `{'foo': 'bar'}`.
4. Finally, used the custom notification body provided here:
```
"notification_type": "webhook",
    "notification_configuration": {
        "url": "http://localhost:9000",
        "headers": {},
        "http_method": "POST",
        "disable_ssl_verification": false,
        "username": "",
        "password": ""
    },
    "messages": {
        "success": {
            "body": "\n{\n  \"attachments\": [\n \n                    {\n \"color\": \"#dddddd\",\n \n                        \"blocks\": [\n  {\n  \"type\": \"section\",\n \n                                              \"text\": {\n \"type\": \"mrkdwn\",\n \n                                                            \"text\": \":rocket: Launched <{{url}}|Job#{{job.id}}: *{{job.name}}*>\"\n \n                                                        }\n \n                                         },\n \n                                         {\n  \"type\": \"divider\"\n },\n \n                                         {\n  \"type\": \"section\",\n  \n                                              \"text\": {\n \"type\": \"mrkdwn\",\n \n                                                            \"text\": \" • *User:* <@{{job.summary_fields.created_by.username}}>\\n • *Project:* {{job.summary_fields.project.name}}\\n • *Playbook:* `{{job.playbook}}`\\n • *Inventory:* {{job.summary_fields.inventory.name}}\"\n                    \n                                                        }\n  \n                                         }\n\n                                    ]\n \n                    }\n \n                   ]\n\n}"
        },
        "started": null,
        "error": null,
        "workflow_approval": null
    }
```

and confirmed that both a job run and project sync resulted in a webhook:
https://gist.github.com/jladdjr/77050726d7f45d090798512c56f995c6

**Comment by jladdjr** [comment] 2021-04-30 23:47
Closing since I can't reproduce. @hjkatz if you're still seeing the issue and can provide an update, let us know.

**Closed as completed** 2021-04-30 23:48 UTC
Labels: type:bug, component:api

**Comment by dsmaugy** [comment] 2021-06-11 19:30
Hi @hjkatz , were you able to fix your problem? I'm running into a similar issue where a custom body for webhook notifications returns an empty body. This applies to all jobs though, not just project updates.
