### ISSUE TITLE
Clarify what it means for project updates to have a default execution environment

### ISSUE THREAD

**Issue by balonik** [ansible/awx#9715] opened 2021-03-26 07:43 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Execution environment is not used when executing (manual) project sync.

Project sync is an Ansible Playbook run as well, it is expected to honor the Execution Environment setting?

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: AWX Operator
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Change the `Instance Group -> tower` definition to:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: my_custom_awx-ee:latest
      name: worker
      args:
        - ansible-runner
        - worker
```

Create new SCM project and try to sync.
The embedded (default) `awx-ee` container in `awx` pod is still used for the execution of Project Sync.

Add new Execution Environment in AWX.
Edit the SCM project and define Default Execution Environment to the newly created Execution Environment.
The embedded (default) `awx-ee` container in `awx` pod is still used for the execution of Project Sync.

##### EXPECTED RESULTS

Project Sync job will use the `Instance Group -> tower` setting if set.
Project Sync job will use the Default Execution Environment configured for that Project.

##### ACTUAL RESULTS

The embedded (default) `awx-ee` container in `awx` pod is still used for the execution of Project Sync.

**Comment by shanemcd** [comment] 2021-03-26 13:10
This is by design. There is an EE inside of the control plane pod used for Project Updates. Some projects can be really big, and the overhead of cloning them inside of a remote EE and streaming the project back to the control plane would be a major performance impact. You can override the EE used inside of the control plane by supplying `tower_ee_image` on your CR like this: https://github.com/ansible/awx-operator/blob/4eb4abf4f54d84857149ece35bedbaaf907fbaaa/deploy/crds/awx_v1beta1_cr.yaml#L18

**Comment by shanemcd** [comment] 2021-03-26 13:14
I just noticed that we _are_ allowing you to provide an EE in the UI for Projects. This is a bug. Will discuss with the team.

**Comment by jbradberry** [comment] 2021-05-21 20:50
This is not the intended meaning of "Default Execution Environment".  The default environment is one that gets inherited by jobs that make use of this project (or organization or whatever other objects we added a Default Execution Environment field to), when the job does not have an explicitly configured environment of its own.  As noted, project updates are forced to use the system execution environment, but this is not a bug.  I recommend that we close this issue.

**Comment by jbradberry** [comment] 2021-05-21 20:57
cc @shanemcd

**Comment by jbradberry** [comment] 2021-05-25 17:44
Perhaps the label could be something more meaningful.  "Job Inherited Environment"?  "Job Fallback Environment"?

**Comment by balonik** [comment] 2021-05-25 19:15
It's tricky, because Project Sync is still a Job. I would probably go for 'Job Default Execution Environment'. And add a note that this is not for Project Sync in the help dialog (the one you get from the question mark icon).

**Comment by nixocio** [comment] 2021-05-25 21:04
I will update the popovers on the UI where we use `Default Execution Environment` to clarify what was discussed here.

**Comment by shanemcd** [comment] 2021-06-02 19:18
Going to take the liberty of closing this, turned out to be a UI/UX tweak.

**Closed as completed by shanemcd** 2021-06-02 19:18 UTC
Labels: type:bug, component:ui
